### ISSUE TITLE
comply to PEP8

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#10]
Change `camelCase` vars and function names and parameters to `python_style`. This will break backward compatibility, so it best be done all at once (rather than incrementally).

http://groups.google.com/group/gensim/browse_thread/thread/73f4301723cea765

**Comment by mcobzarenco** [comment]
This is not the case anymore, (e.g. pyflake shows 63 warnings for `models/wrappers/fasttext.py`). Happy to PEP8 the whole repo and create a pr if that's cool.

**Comment by piskvorky** [comment]
@mcobzarenco what warnings are these? For example, we care more about readability than a strict 80-char-line limit.

But I also noticed some lapses (vertical indent in word2vec). @menshikh-iv what's the status on code style consistency in gensim?

**Comment by menshikh-iv** [comment]
@piskvorky 
```
(math) ivan@P50:~/release/gensim$ git log | head -n5
commit e92b45d3f83ad670da9cf6ae20ae86a2a1c8558c
Author: jodevak <jodevak@users.noreply.github.com>
Date:   Thu Oct 19 09:37:41 2017 +0300

    Add build_vocab_from_freq to Word2Vec, speedup scan_vocab (#1599)
(math) ivan@P50:~/release/gensim$ find gensim/ -name "*.py" | xargs flake8 --ignore=E501,E731,E12,W503,E402 --show-source
gensim/test/test_lsimodel.py:95:5: E303 too many blank lines (2)
    def testCorpusTransform(self):
    ^
```

**Comment by mcobzarenco** [comment]
Right, fair enough, all of the warnings were of the types you ignore above. Do you think we could we add those ignored rules to `setup.cfg` so they're documented and also ignored by default? I created a PR here #1636
