### ISSUE TITLE
Move "Pattern not installed" warning from import time to when lemmatization is used

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#1009]
It confuses many first time users as the warning is the first thing they see when importing gensim.

**Comment by souravsingh** [comment]
@tmylk I would like to work on the issue. How do I start?

**Comment by shashankg7** [comment]
@tmylk , @souravsingh . I have fixed this issue. I moved 'has_pattern()' method's pattern installation check to lemmatize method. The warning will only occur when user calls the lemmatization method and if the pattern library is not installed. I also modified the call to "has_pattern" in corpora/wikicorpus's constructor.

Please refer to #1018
