### ISSUE TITLE
Raise key error when load word2vec model.

### ISSUE THREAD

**Issue by Sraw** [RaRe-Technologies/gensim#1020]
```
Traceback (most recent call last):
  File "w2vtest.py", line 87, in <module>
    w2vmodel = Word2Vec.load('McModel')
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/word2vec.py", line 1767, in load
    model.make_cum_table()  # rebuild cum_table from vocabulary
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/word2vec.py", line 493, in make_cum_table
    cumulative += self.vocab[self.index2word[word_index]].count**power
KeyError: '2367656837'
```

I know what happen but have no idea to solve it.
When I finish training the model, I manually delete some words in the model.vocab object. It works still well at that time. But after trying save and load back, it raise a key error. It seems the model use another attribution/method to deal with the rebuilding of vocab.
I'm not sure the issue is caused by this, but could you implement a safe way for word2vec to delete some words in vocab?

**Comment by tmylk** [comment]
Would it be easier to delete the words from the initial training corpus in pre-processing?

**Comment by Sraw** [comment]
@tmylk that might be a choice, but the structure of vocab is not safe. User can directly delete  the words in vocab, and before reload model from file, it seems work well. But actually not. I think there should be a method to delete the words more safely or just prevent the user from deleting words.

**Comment by tmylk** [comment]
Word indices are expected to be continuous so agree that deleting from vocab should be prohibited. Do you have an idea for an implementation?

**Comment by Sraw** [comment]
@tmylk Um... I'm not proficient at python. Just an advice:
```
class defaultdict(dict):
    def __init__(self, default=None):
        dict.__init__(self)
        self.default = default

    def __getitem__(self, key):
        try:
            safekey = dict.__getitem__(self, key)
            return safekey
        except KeyError:
            return self.default
```
That maybe work, the `safekey` is another reference of item, the "del" method will only delete this reference, but the dict also handles the original reference. But I don't know will the "del" method also release the memory. Or we also need to identify the item's "__del__" method.

**Comment by gojomo** [comment]
It's not enough to delete words from `vocab`; the `index2word` mapping, of slots to words, must be kept in sync with the `vocab` dictionary. 

You should ideally take out your words at a point where Word2Vec can adjust to a different vocabulary.  See for example the comment for `build_vocab()`, and how it actually takes 3 separate steps.

https://github.com/RaRe-Technologies/gensim/blob/c2d8187431848b828b81e696bdaebc852d708f94/gensim/models/word2vec.py#L518

Instead of calling `build_vocab()`, you should be able to do the `scan_vocab()` yourself, then make your custom vocabulary edits. Then, perform `scale_vocab()` (which finalizes the word-to-index ordering) and `finalize_vocab()`. That may resolve your error, by keeping all internal structures in proper sync.

**Comment by parulsethi** [comment]
For the implementation, we can add a parameter for user to define the words to be deleted and then the code for the deletion can be added in `scan_vocab()` as @gojomo suggested. (by deleting corresponding word key from `raw_vocab`)

@gojomo @tmylk does this approach sound correct?

**Comment by gojomo** [comment]
There's already `trim_rule`, and I believe that it's already safe to manually call `scan_vocab()`, then modify the `raw_vocab` however desired, then the other steps. So I don't think the library needs any more parameters/functionality here – there's already plenty (maybe too many) hooks to allow users to do what they need.

**Comment by tmylk** [comment]
Closing as "wont' implement"
