### ISSUE TITLE
Problem during use  gensim.models and annoy library

### ISSUE THREAD

**Issue by flashkari** [RaRe-Technologies/gensim#1023]
I tried the following code and I got this exception  _**TypeError: 'an integer is required' in <module 'threading' from '/home/xx/anaconda/lib/python2.7/threading.pyc'> ignored**_ . 

I do not know I called the _build_from_doc2vec()_ in a wrong way or something is wrong with  [the code](https://github.com/RaRe-Technologies/gensim/blob/699773a78f32ff2c254cf16a586a5d26a08394fe/gensim/similarities/index.py#L65)

Also, I added `return index` to the __build_from_model()_ function.

```
>>> model= Doc2Vec.load('my_model.doc2vec')
>>> ai=an_index.AnnoyIndexer(model)
>>> t= ai.build_from_doc2vec()
>>> print(t.get_nns_by_item(0, 100))
**TypeError: an integer is required**
>>> print(t.get_nns_by_item(0, 100))
[]
>>> t= ai.build_from_doc2vec()
>>> print t
**TypeError: an integer is required**
```

**Comment by tmylk** [comment]
@flashkari Correct API from [Annoy Tutorial](https://github.com/RaRe-Technologies/gensim/blob/0c5c5ed9024d8ea89e106ebaf926071b4a3a6654/docs/notebooks/annoytutorial.ipynb) is below. It wraps the correct calls to `get_nns`
```
annoy_index = AnnoyIndexer(model, 500)
model.most_similar([vector], topn=5, indexer=annoy_index)
```
Please let me know if it resolves the issue

**Comment by flashkari** [comment]
Thank you @tmylk . 
Yes, it solve the issue.
