### ISSUE TITLE
Pattern not available for python 3.5 Win64 Windows

### ISSUE THREAD

**Issue by JimSEOW** [RaRe-Technologies/gensim#1025]
gensim depends on pattern library for lemmatization to work. Without pattern library, a warning is display
`pattern library is not installed, lemmatization won't be available`

Pattern library can be downloaded from
http://www.clips.ua.ac.be/media/pattern-2.6.zip

I encounter a few errors when install the pattern library for python 3.5 Miniconda Win54 Windows 10

`lib\site-packages\pattern-2.6-py3.5.egg\pattern\text\__init__.py", line 1876 ` 

`return Score(polarity = avg(map(lambda (w, p, s, x) : (w, p), a), weight)`

SyntaxError: invalid syntax [ with ^ pointing at the immediate open bracket after lambda ]

The modification to remove the SyntaxError is 

`return Score(polarity = avg(map(lambda w, p, s, x : (w, p), a), weight)`

**Comment by tmylk** [comment]
Pattern is only [supported](http://www.clips.ua.ac.be/pattern) for Python 2.5 and 2.6 
The porting to py3 work is in progress at https://github.com/pattern3/pattern

**Comment by JimSEOW** [comment]
When I have time, I will try the pattern3 link you have provided. I did not have time to run test on lemmatization. Which test from Gensim should I use to check lemmatization?

**Comment by tmylk** [comment]
@JimSEOW I would rather wait for the full pattern migration to Python 3 but if you wish to test how your patch is doing in Gensim you can try these two classes where lemmatization is used.

https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/test/test_summarization.py and https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/test/test_wikicorpus.py

**Comment by souravsingh** [comment]
Currently the pattern3 codebase is not stable. It will take some time for migration to Python 3

**Comment by JimSEOW** [comment]
@tmylk I git clone https://github.com/pattern3/pattern; python setup.py develop in MiniConda py3.5 Win64
=> First problem: pypiwin32
=> I downloaded [pypiwin32-219-cp35-none-win_amd64.whl](https://pypi.python.org/pypi/pypiwin32)
=> pip install pypiwin32-219-cp35-none-win_amd64.whl
=> repeat python setup.py develop with pattern3
=> Install works ok

FYI: I have not done all test yet!

![applicationframehost_2016-12-01_17-27-00](https://cloud.githubusercontent.com/assets/8244633/20802167/7020cc80-b7eb-11e6-879d-70e7651c037c.png)
![applicationframehost_2016-12-01_17-27-41](https://cloud.githubusercontent.com/assets/8244633/20802183/7dd5bd90-b7eb-11e6-833a-f7b29403a398.png)

**Comment by menshikh-iv** [comment]
As I see this is resolved in a @JimSEOW message.

**Comment by piskvorky** [comment]
@menshikh-iv did you test (possibly with @isamaru if needed).

**Comment by menshikh-iv** [comment]
@piskvorky done
1. Install python 3.5.4 x64 
2. Download wheels from http://www.lfd.uci.edu/~gohlke/pythonlibs/, neeeds: numpy, scipy, gensim, smart_open, lxml, pypiwin32 
3. Install all with pip 
4. Run `python Scripts\pywin32_postinstall.py -install` in root python dir (needed for pypiwin32) 
4. Check lemmatize without pattern lib 
``` 
C:\Users\Юлия\Downloads>python -c "import gensim; print(gensim.utils.lemmatize('The quick brown fox jumps over the lazy dog!'))" 
C:\python3\lib\site-packages\gensim\utils.py:862: UserWarning: detected Windows; aliasing chunkize to chunkize_serial 
warnings.warn("detected Windows; aliasing chunkize to chunkize_serial") 
Traceback (most recent call last): 
File "<string>", line 1, in <module> 
File "C:\python3\lib\site-packages\gensim\utils.py", line 1064, in lemmatize 
raise ImportError("Pattern library is not installed. Pattern library is needed in order to use lemmatize function") 
ImportError: Pattern library is not installed. Pattern library is needed in order to use lemmatize function 
``` 
5. Download pattern3 from https://codeload.github.com/pattern3/pattern/zip/master 
6. Unpack and install with `python setup.py develop` 
7. Check again 🙌
``` 
C:\Users\Юлия\Downloads>python -c "import gensim; print(gensim.utils.lemmatize('The quick brown fox jumps over the lazy dog!'))" 
C:\python3\lib\site-packages\gensim\utils.py:862: UserWarning: detected Windows; aliasing chunkize to chunkize_serial 
warnings.warn("detected Windows; aliasing chunkize to chunkize_serial") 
[b'quick/JJ', b'brown/JJ', b'fox/NN', b'jump/NN', b'lazy/JJ', b'dog/NN'] 
```

**Comment by piskvorky** [comment]
Oh, pattern3 is not on PyPI? I don't we should even support that then, that's too much work.

**Comment by menshikh-iv** [comment]
@piskvorky https://pypi.python.org/pypi/pattern3/3.0.0 is available on PyPI, but I don't check it.
