### ISSUE TITLE
similarity between all the pairs of documents in a subset of my corpus

### ISSUE THREAD

**Issue by foice** [RaRe-Technologies/gensim#1027]
Hello,
 I have been able to make an LSI model of 1M of titles of papers and with 200 features seems to give rise to decent/good results for the cosine calculation. The similarity I can compute are obtained from
`sims = index200[query_lsi]` and it takes about 1s to give an output on my poor core2duo.

To be faster and more targeted, now I want to compute similarity between all the pairs of titles in a _sub-set_ of my 1M. What would be the syntax for that? 

From [similarities.docsim – Document similarity queries](http://radimrehurek.com/gensim/similarities/docsim.htmll) it seems there is smart way to do this, but I cannto really get it from that documentation link. Can anybody help please?

**Comment by tmylk** [comment]
Hi foice, first of all [mailing list](https://groups.google.com/forum/#!forum/gensim) is the best place for such open-ended questions.

Best performing (approximate)cosine lookup solution is actually [Annoy](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/annoytutorial.ipynb). It would be a welcome contribution if you could add a "build index from gensim LSI" code to [gensim](https://github.com/RaRe-Technologies/gensim/blob/699773a78f32ff2c254cf16a586a5d26a08394fe/gensim/similarities/index.py#L31). We already have code for builidng index from word2vec and doc2vec.

**Comment by piskvorky** [comment]
I don't see the mailing list thread, so answering here for now:

To compute similarity between all pairs, use the `for sims in index:` syntax (note there is no query, no `index[xyz]`).

To restrict `index` to a subset of your 1M documents, pick the vectors you need and put them into a new, separate index. That will give you the fastest results.

Or if you don't mind approximate results, you can use Annoy on your original 1M dataset without restricting it, like @tmylk says.

**Comment by foice** [comment]
> To restrict index to a subset of your 1M documents, pick the vectors you need and put them into a new, separate index. That will give you the fastest results.

Thanks for this tip, it is indeed a huge factor faster doing it this way! 

Thanks as well for the suggestion about approximate methods, but here I am looking for exact for now. Still might be useful in the future.
