### ISSUE TITLE
Remove update argument from  scan_vocab() in Word2Vec as it is not used

### ISSUE THREAD

**Issue by CasiaFan** [RaRe-Technologies/gensim#1031]
I find the argument update  is accepted as an input of scan_vocab() function (word2vec.py, line 528), but it doesn't appear inside the function body. So it seems this argument doesn't make any sense for scan_vocab(). Is it a bug or argument update will be discarded?

**Comment by tmylk** [comment]
Agree that this argument should not be present in `scan_vocab`. Thank you for reporting it!

**Comment by piskvorky** [comment]
@gojomo thoughts?
