### ISSUE TITLE
GenSim install failure

### ISSUE THREAD

**Issue by john-jh-lee** [RaRe-Technologies/gensim#1032]
Hi all,

I've been trying hard to install and use GenSim but without any success. I first installed Python 3.5.2 (64). I then downloaded gensim 0.13.3 (win64) py3.5 and executed it but I always get the following prompt: "Cannon install - Python version 3.5-32 required, which was not found in the registry" 

Any help welcome. Thank you very much!

**Comment by tmylk** [comment]
Hi, thanks for reportig it.
Which file and from where did you download it?
The gensim is on pypi https://pypi.python.org/pypi/gensim

**Comment by john-jh-lee** [comment]
Hi, thanks for the reply. Yes I'm familiar with the link you sent me, and I had downloaded and attempted to install the following from that link:
gensim-0.13.3.win-amd64-py2.7.exe (md5) 	
gensim-0.13.3.win-amd64-py3.5.exe (md5) 	
gensim-0.13.3.win32-py2.7.exe (md5) 	
gensim-0.13.3.win32-py3.5.exe (md5)

**Comment by tmylk** [comment]
can you try installing gensim with pip as in `pip3 install gensim`

**Comment by john-jh-lee** [comment]
Please forgive my ignorance. Where do I type that pip command? In Windows command prompt, or in Python IDE?

**Comment by tmylk** [comment]
That is ok. Please see this[ guide](https://docs.python.org/3/installing/) to installing python packages on windows

**Comment by john-jh-lee** [comment]
Thank you so much!
