### ISSUE TITLE
Cannot make ldaseqmodel.py as part of CI

### ISSUE THREAD

**Issue by markroxor** [RaRe-Technologies/gensim#1034]
In PR https://github.com/RaRe-Technologies/gensim/pull/982 the example notebook `ldaseqmodel.ipynb` was converted to a python file `ldaseqmodel.py` so that it can be made part of Travis continuous integration using sphinx-gallery and be checked for any errors/inconsistencies but as can be seen in line 1613 of the [travis output.](https://travis-ci.org/markroxor/gensim/jobs/179994004#L1613) The ldaseqmodel.py is taking over 45 minutes to execute which is more than the time Travis allocates for each build and thereby raising the error `The job exceeded the maximum time limit for jobs, and has been terminated.`

**Comment by markroxor** [comment]
@bhargavvader. Help requested.

**Comment by bhargavvader** [comment]
This can be fixed by maybe using a much smaller sample corpus; but would that mean the notebook would have to be changed accordingly? Like with all the examples and all.

**Comment by markroxor** [comment]
That is Lev's call.
@tmylk

**Comment by tmylk** [comment]
A smaller corpus would be better for a notebook. A link to a bigger corpus should be mentioned but not used.

**Comment by bhargavvader** [comment]
Agreed, but in DTM a bigger corpus better demonstrates evolution of topics in time-slices. One other possibility is loading a pre-trained `ldaseq` model on the larger dataset, and commenting out the code which actually trains the model. 

This way users can still see how to train the model, but the actual code being run will be just loading a model.

**Comment by tmylk** [comment]
Loading a pre trained model is a great idea.

**Comment by bhargavvader** [comment]
Okay, will do this when I get some time!

**Comment by menshikh-iv** [comment]
Unrelevant because now we don't run ipynb in CI.
