### ISSUE TITLE
DTM, raise error, returned non-zero exit status 127

### ISSUE THREAD

**Issue by masoudkavianipartotech** [RaRe-Technologies/gensim#1042]
I write a code to determine DTM model with: https://radimrehurek.com/gensim/models/dtmmodel.html
I use ubuntu 14.04 64bit, and i use dtm-linux64 for DTM model,
but then I want to run the code, it will run an error as follow:

raise error
subprocess.CalledProcessError: Command '['/python-apps/f2/app/../assets/dtm-linux64', '--ntopics=1000', '--model=dtm', '--mode=fit', '--initialize_lda=true', '--corpus_prefix=/tmp/561a27_train', '--outname=/tmp/561a27_train_out', '--alpha=0.01', '--lda_max_em_iter=10', '--lda_sequence_min_iter=6', '--lda_sequence_max_iter=20', '--top_chain_var=0.005', '--rng_seed=0']' returned non-zero exit status 127

**Comment by bhargavvader** [comment]
Running `['/python-apps/f2/app/../assets/dtm-linux64', '--ntopics=1000', '--model=dtm', '--mode=fit', '--initialize_lda=true', '--corpus_prefix=/tmp/561a27_train', '--outname=/tmp/561a27_train_out', '--alpha=0.01', '--lda_max_em_iter=10', '--lda_sequence_min_iter=6', '--lda_sequence_max_iter=20', '--top_chain_var=0.005', '--rng_seed=0']` (with the `,` and `'` removed) in the terminal will tell you the exact nature of the error.

This is also related to issue #703

**Comment by menshikh-iv** [comment]
@masoudkavianipartotech 127 means that path to DTM doesn't exist. Please fix your path.
