### ISSUE TITLE
Multicore Loader

### ISSUE THREAD

**Issue by prakhar21** [RaRe-Technologies/gensim#1043]
Hi, I am trying to load google pre-trained word vectors in gensim.
I am using `gensim.models.Word2Vec.load_word2vec_format(model_path, binary=True)`
But it is taking long time to load. I can see only one thread is being used during load. Can we fasten this process anyhow ?

**Comment by tmylk** [comment]
Hi @prakhar21 the loading is indeed single-threaded. Could you please describe your use case more and your need for the speed up? It will be quite complicated to speed it up. In my experience it is a run-once operation so performance wasn't important.

After loading the model once you can save it in KeyedVecs format to disk and then just memorymap  from disk to avoid loading into memory. Also, if you use word vectors for similarity look-ups then consider [Annoy](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/annoytutorial.ipynb)

**Comment by piskvorky** [comment]
I also think the loading should be IO bound, so multiple cores wouldn't help much.

It will certainly be the case if you use memory-mapping -- the loading from disk should be as fast as your OS allows then.

If `load(mmap')` is fast, but `load_word2vev_format` is slow, then we can think about speeding it up. But looking at the code, there's not a whole lot that can be done, at least not without descending into C...

**Comment by prakhar21** [comment]
Hi @tmylk @piskvorky  my use-case is simply loading word embeddings from google vectors or glove, and using them to enrich the text given to me with the help of them along with some extra text features. So, loading glove (common crawl) is eating up 5-6GB of my memory and that too the loading is very slow. So, i was wondering any work around for this problem. I am not very sure of memorymap, will have to explore.
Thanks

**Comment by gojomo** [comment]
Is the loading causing virtual-memory swapping? That'd cause slowness, and even after loading, any of the most-similar operations that require full-scans would continue being slow. (And, using `mmap` might avoid some premature disk-IO, but would still be slow on full-scans over an array that can't be fully in RAM.) 

If this is the problem and you can't get more RAM, maybe you can work with just a subset of vectors in the file. (Often in word2vec_format-dumps, the most-frequent words are placed first, so truncating the file just drops less-frequent words and thus doesn't lose too much value.) In recent gensim versions `load_word2vec_format()` includes an optional  `limit` parameter which, if present, is a maximum count of vectors to load.

**Comment by tmylk** [comment]
Closing as "won't fix".
