### ISSUE TITLE
Unable to load .bin file

### ISSUE THREAD

**Issue by amr1tv1rd1** [RaRe-Technologies/gensim#1044]
I get this error whenever trying to load .bin file in word2vec model

` File "/usr/local/lib/python2.7/dist-packages/gensim/models/word2vec.py", line 1211, in load_word2vec_format
    weights = fromstring(fin.read(binary_len), dtype=REAL)
ValueError: string size must be a multiple of element size
`
Kindly guide me what would be the possible cause of this

**Comment by tmylk** [comment]
What do the weights look like in the `bin` file? It should be a valid input into [fromstring](https://docs.scipy.org/doc/numpy-1.4.x/reference/generated/numpy.fromstring.html)

**Comment by tmylk** [comment]
Closing as abandoned.
