### ISSUE TITLE
PyPI misformatted

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#1045]
Changes in [this commit](https://github.com/RaRe-Technologies/gensim/commit/c746b7c2d13c422f5abb16d29b9cf671b6f753e6) messed up the way gensim displays at PyPI: https://pypi.python.org/pypi/gensim

PyPI expects README in .rst format, not .md.

Why did that change happen? Please revert.

**Comment by piskvorky** [comment]
@tmylk still broken in the new release.

**Comment by tmylk** [comment]
Readme was changed to markdown when we were moving Changelog to MD format based on your request. Should I revert it?

**Comment by piskvorky** [comment]
PyPI needs .rst.

Also, the "mailing list" badge could be useful, ala https://github.com/rasbt/deep-learning-book

**Comment by piskvorky** [comment]
@tmylk Do we want to add the "gitter chat" badge too, or keep gitter "secret"?

**Comment by tmylk** [comment]
Added gitter and twitter.
