### ISSUE TITLE
Wrapper for LDA form MALLET have a bug in convert format 

### ISSUE THREAD

**Issue by fann1993814** [RaRe-Technologies/gensim#1048]
I cannot using the ldamallet to run LDA, so i check the code in gensim.
I found the function "convert_input" in ldamallet.py.
I think it will generate a proper format for mallet.

In line 147
cmd = self.mallet_path + " import-file --preserve-case --keep-sequence --remove-stopwords --token-regex '\S+' --input %s --output %s"

this code maybe result in wrong format.
So I found the problem happen from --token-regex '\S+'
It cannot correct to token, so I change to this
--token-regex \"\S+\"

It just can run mallet normally.

**Comment by piskvorky** [comment]
Hi @fann1993814 , the code has worked for me.

Is there anything special about your setup? Are you maybe using windows? (the single/double quotes may work differently there, I'm not sure)

**Comment by fann1993814** [comment]
@piskvorky 
Thanks for your reply!

I don't have anything wrong or warning in setup.
My environment is Windows 10 and other package is:
Python 3.5
mallet 2.0.7
JDK 8.0.77 
numpy 1.11 (installed form http://www.lfd.uci.edu/~gohlke/pythonlibs/)

The single quotes cannot run mallet wrapper in my environment, so I replace single quotes to double quotes, and then it can work.

**Comment by tmylk** [comment]
Hi @fann1993814 

May I ask you to update to the latest version of Gensim from PyPi or from github? 

This quote issue was [fixed](https://github.com/RaRe-Technologies/gensim/blob/d7c1055570107e8288a9b5f72506a2f525d3a917/gensim/models/wrappers/ldamallet.py#L147) in this [PR](https://github.com/RaRe-Technologies/gensim/pull/1005/files#diff-220ca1b82d4f1c42d8f4432ff3a2a6ccL148).
