### ISSUE TITLE
Problem in generating the TFIDF Model

### ISSUE THREAD

**Issue by TamouzeAssi** [RaRe-Technologies/gensim#1059]
Hello,

Thank  you in advance for your help. Im new in using gensim.  My problem is, when i transform my corpus to tfidmodel. More precisely, i create a corpus as noted in the tutorial, and i used tfidf to convert it to TFIDF model.

The information concerning my corpus is:
MmCorpus(3 documents, 3 features, 7 non-zero entries).
The vectors corrponding to the documents are:
document1: [(0, 1.0), (1, 1.0), (2, 1.0)]
document2: [(0, 1.0), (1, 1.0)]
docuemnt 3: [(0, 1.0), (2, 1.0)]

but when i generate the corresponding tfidf vectors i get:
document 1: [(1, 0.7071067811865476), (2, 0.7071067811865476)]
document 2:  [(1, 1.0)
document 3: [(2, 1.0)]

Can you please tell me where is the feature 0? Why it is not displayed in the generated vectors?

Thank you

**Comment by tmylk** [comment]
Hi @TamouzeAssi ,

The zeros are [omitted](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/tfidfmodel.py#L156) from TfIdf output.

Let's continue this question in the [mailing list](https://groups.google.com/forum/#!forum/gensim) where this quesiton is more appropriate.

**Comment by TamouzeAssi** [comment]
Hi @tmylk,

The zero in my qiuestion is the feature zero. I know when the idf of any feature is zero this feature will not displayed. 

but in my  question isnt my case
