### ISSUE TITLE
Finding the nearest neighbor - performance issue. 

### ISSUE THREAD

**Issue by jasonMorri90** [RaRe-Technologies/gensim#1063]
Hi...I am very new to machine learning and python. Here is my python code for finding the nearest neighbor.

----------------------------------------------

from gensim import corpora
from nltk.corpus import stopwords
import gensim, os
from gensim.models.word2vec import Word2Vec
import numpy
numpy.version.version

class MyText(object):
    def __iter__(self):
        for line in open("Desktop/splitxtaa"):
           yield line.lower().split()
documents = MyText()

stoplist = set(stopwords.words('english'))
texts = [[word for word in document if word not in stoplist]
         for document in documents]

model = Word2Vec(texts,size =100,min_count=100, workers=12)
model.save("/Users/W2Vsplitaa")
try:
    from gensim.similarities.index import AnnoyIndexer
except ImportError:
    raise ValueError("SKIP: Please install the annoy indexer")

vector = model['home']
annoy_index = AnnoyIndexer(model, 100)
annoy_index.save("Desktop/annoysplitaa")
approximate_neighbors = model.most_similar([vector], topn=20, indexer=annoy_index)
for neighbor in approximate_neighbors:
    print(neighbor)

-----------------------------------------------------------------
 When i run this on 1GB text file. It takes around 45 minutes.  I did install Cython and BLAS. Is there something I could be missing...Plz suggest how can i reduce the time. I have to run this model on a large  corpus. Is there a way  to run this distributed. ?

**Comment by tmylk** [comment]
Hi @jasonMorri90, this open-ended question is better suited for the [mailing list](https://groups.google.com/forum/#!forum/gensim).
Please post there with the log output. Also, which part of the code takes 45 mins? Can you post the how long it takes to run each line? You can use the `%time%` command in Jupyter notebook for that.

**Comment by jasonMorri90** [comment]
Will do, thanks @tmylk
