### ISSUE TITLE
wmdistance returns inf for single words in vocabulary

### ISSUE THREAD

**Issue by Tixierae** [RaRe-Technologies/gensim#1073]
````
import gensim
# loading Google News vectors
model = gensim.models.word2vec.Word2Vec.load_word2vec_format('E:\\GoogleNews-vectors-negative300.bin.gz', binary=True)
````
The following:
````
# computing the Word Mover's Distance of an in-vocab word to itself
model.wmdistance(['obama'],['obama'])
````
returns `inf`, when obviously it should be zero (according to the [documentation](https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec.wmdistance), `float(inf)` is only returned for out-of-vocab words).

Interestingly, `model.wmdistance('obama','obama')` does return zero, and `model.wmdistance(['obama'],['obama','illinois'])`, `model.wmdistance(['obama'],['illinois'])` both work. The problem only seems to arise for *single identical words*.

**Comment by tmylk** [comment]
Hmm... There was a [fix](https://github.com/RaRe-Technologies/gensim/pull/986) for when the dictionary size is 1 and it should have covered this case.

**Comment by Tixierae** [comment]
Thanks! I will update my installation of the module and try again.

**Comment by tmylk** [comment]
@Tixierae did an update fix the issue?

**Comment by tmylk** [comment]
Closing as abandoned.

**Comment by Tixierae** [comment]
Sorry for the delay in response. Updating indeed fixed the issue. Thanks!
