### ISSUE TITLE
fblas in rpmodel.py  --> "AttributeError: 'module' object has no attribute 'fblas'  "

### ISSUE THREAD

**Issue by andrewjOc360** [RaRe-Technologies/gensim#109]
ERROR: AttributeError: 'module' object has no attribute 'fblas' 

"scipy.linalg.blas.fblas" has been replaced by scipy.linalg.blas 

Other have experience this error: https://github.com/Theano/Theano/issues/1144

Changing as shown in the above in the .py and recompiling the .pyc worked for me!

Thanks for a great package!
- Andrew

**Comment by ibrahim-amer** [comment]
I don't understand what you did exactly, even when navigating to the provided link. Please, could you provide me with more details ?
