### ISSUE TITLE
Is there a limit to maximum number of topics for lda?

### ISSUE THREAD

**Issue by koustuvsinha** [RaRe-Technologies/gensim#1090]
Hi, I am trying to run Lda (using LdaMulticore) and have encountered a specific issue : I have 12,000 documents and I want 6,000 topics, where I want two documents to be in a topic at once. The program is stuck for hours (> 10) in this line : `using serial LDA version on this node`. While if I change the number of topics to 4 the program runs as expected. So is there any limit to how much topics I can request? (I am running the program on server where RAM and processing power is not an issue)

**Comment by tmylk** [comment]
There is no limit. Issue discussed on gitter.
