### ISSUE TITLE
Requesting feedback on blogpost on Text Summarization

### ISSUE THREAD

**Issue by dust0x** [RaRe-Technologies/gensim#1092]
@piskvorky @olavurmortensen 

@pranay360 @metalaman and I are working [this blog](https://docs.google.com/document/d/1RO1-hlnSkrBbL-ks-O6Xr4ZfWK92vfo-xFicp5Gb0Qc/edit?usp=sharing) on Text Summarization for RaRe Technology's incubator program with @tmylk and request your feedback on the same. You may write your thoughts and suggestions in the comments section of the document.

We've also raised an issue relating to some of our findings in #1085.

Thanks!

**Comment by piskvorky** [comment]
Very nicely written and structured, thanks!

I commented inside, asking for clarification on some minor points.

**Comment by menshikh-iv** [comment]
Already finished.
