### ISSUE TITLE
How to use gensim word2vect model as a Sklearn FeatureVectorizer (Want to use in keras cnn) ?

### ISSUE THREAD

**Issue by eromoe** [RaRe-Technologies/gensim#1095]
I want to use word2vect and keras cnn to do document classifacation(Chinese Text ). I learned the basic flow of text classification in cnn and want to do a test.

I have seen `word2vec.ipynb` and some `doc2vec *.ipynb` .  All the example are talking about word to word and sequence to sequence similarities, no method like `transform()` in sklearn.

## For example(the steps I imagine):

1. Use a good Cinese Tokenized Text Set to train word2vec model

        model = gensim.models.Word2Vec(new_sentences, workers=10, size=200, min_count=2)

2. Tokenize my sentences dataset to words lists dataset(the longest sentence has over 8000 words)
        
        1     ['你们', '好', '今天', '天气', '真', '好']
        2     ['嗯', '对的']
        ...
        9999  ['好', '就', '这样']

3. Use a method to transform words lists dataset to word2vec dataset

     transform every word in every sencence to a vec by trained model.

        1     [[word2vec size=200], [word2vec size=200], [word2vec size=200], [word2vec size=200], [word2vec size=200], [word2vec size=200]]
        2     [[word2vec size=200], [word2vec size=200]]
        ...
        9999  [[word2vec size=200], [word2vec size=200], [word2vec size=200]]

4. Pad  word2vec dataset (with size=200 zero array)

        1     [[word2vec size=200], [word2vec size=200], [word2vec size=200], [word2vec size=200], [word2vec size=200], [word2vec size=200]]
        2     [[word2vec size=200], [word2vec size=200], [word2vec size=200], [word2vec size=200], [word2vec size=200], [word2vec size=200]]
        ....
        9999  [[word2vec size=200], [word2vec size=200], [word2vec size=200], [word2vec size=200], [word2vec size=200], [word2vec size=200]]

5. go to the CNN

But I can't find a way to do the step 3.

------------

There is a article talk about this http://nadbordrozd.github.io/blog/2016/05/20/text-classification-with-word2vec/
But it can't not work as my understanding of step 3. It transform all sentences to 

        1     [word2vec size=200]
        2     [word2vec size=200]
        ...
        9999  [word2vec size=200]

just as what `gensim.models.doc2vec.Doc2Vec.infer_vector` do.  There is no `infer_vector` method in word2vec model.

So, is there any method in gensim can fit my purpose?

**Comment by tmylk** [comment]
Hi @eromoe one can get a vector representation of a *single word* in word2vec with `model['tree']` command.

A simple way to assigna a word2vec vector to a document is to take a mean of its words. It produces great results in practices. It is the method used in the `transform` method in theh [blog](http://nadbordrozd.github.io/blog/2016/05/20/text-classification-with-word2vec/) you linked to.

Such an open question is better suited for our [mailing list](https://groups.google.com/forum/#!forum/gensim). Let's continue the conversation there.
