### ISSUE TITLE
eta = 'auto' setting does not appear to work

### ISSUE THREAD

**Issue by huihuifan** [RaRe-Technologies/gensim#1096]
`Lda = gensim.models.LdaModel(corpus, id2word=dictionary, num_topics=20, alpha='auto', eta = 'auto')`

produces the error:

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('S32') dtype('S32') dtype('S32')

which does not appear to be related to the corpus or dictionary I generated. Leaving off the eta='auto' parameter runs fine.

**Comment by tmylk** [comment]
Hi, unfortunately unable to reproduce this `numpy` error. The `eta=auto` option works with numpy==1.11.2 and gensim 0.13.4.1

**Comment by tmylk** [comment]
Closing as abandoned.
