### ISSUE TITLE
word2vec  print cost/loss during training

### ISSUE THREAD

**Issue by WenchenLi** [RaRe-Technologies/gensim#1098]
Hi, 
I would like to print out cost/loss during training word2vec to get a sense whether training reached plateau, from the glimpse of word2vec.py I can't find a way to do that. Please help or advice how I can print out loss with the minimum change of your code. Thanks.

**Comment by gojomo** [comment]
There's no existing facility to track or print this. It's a wishlist item. Some discussion about possible approaches in #999, and a similar previous request is #686.

**Comment by tmylk** [comment]
Closing as duplicate
