### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by bhargavvader** [RaRe-Technologies/gensim#1100]
The hyperlink to the gensim citation is broken: https://scholar.google.cz/citations?view_op=view_citation&hl=en&user=9vG_kV0AAAAJ&citation_for_view=9vG_kV0AAAAJ:u-x6o8ySG0sC.

This should be replaced, but when I was looking for a replacement I couldn't find it: would it be one of the results on [this](https://scholar.google.fr/scholar?hl=en&q=gensim+python&btnG=&as_sdt=1%2C5&as_sdtp=) page?

Ping @piskvorky

**Comment by piskvorky** [comment]
@bhargavvader thanks for reporting!

Not sure where that citation is, but the correct link is [this one](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=9vG_kV0AAAAJ&citation_for_view=9vG_kV0AAAAJ:NaGl4SEjCO4C).
