### ISSUE TITLE
Annoy tutorial inconsistency

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#1105]
The [Annoy tutorial](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/annoytutorial.ipynb) states that Annoy is much faster than brute force.

But then cells 108 and 109 show the opposite -- Annoy is 3x *slower* than brute force.

This is confusing to the reader.

The discrepancy could be to any number of reasons (cold caches etc). For a slightly better "micro benchmark", measure a loop of e.g. 1000 random queries.

In case either index is memory-mapped, make sure it's fully in RAM before starting the benchmarking (go over it once with a "dry run", to generate all the page faults). If either index doesn't fit fully in RAM, don't run the benchmark at all.

**Comment by greninja** [comment]
I ran a benchmark test over a random sample of 1000 words from `model.vocab` for similarity queries ( havent tried retrieving indices from disk as of yet) and the wall time taken by Annoy still comes out to be roughly 3 times more.

Also , in cell 112, is the word "army" or "science"?

**Comment by tmylk** [comment]
@greninja This is very different from the [first commit](https://github.com/RaRe-Technologies/gensim/blob/4ce3ce143dcc97bf0a917dbf3a7b828f1890668b/docs/notebooks/annoytutorial.ipynb) where it is 12ms vs 678us.

It needs further investigation:
Does annoy use multiple cores on your machines? Did something take change in the implementation?

**Comment by greninja** [comment]
No change in implementation.

I ran this code : 

`import random
vocab_list = random.sample(model.vocab, 1000)  # to get random queries

# Traditional method
%%time
    ...: for word in vocab_list:
    ...:     vector = model[word]
    ...:     model.most_similar([vector],topn=5)
    ...: 
CPU times: user 1.52 s, sys: 1.6 s, total: 3.12 s
Wall time: 914 ms

# Using Annoy
In [24]: %%time
    ...: for word in vocab_list:
    ...:     vector = model[word]
    ...:     model.most_similar([vector],topn=5,indexer=annoy_index)
    ...: 
CPU times: user 320 ms, sys: 0 ns, total: 320 ms
Wall time: 317 ms
`

It showed results what the notebook doc claims.

**Comment by droudy** [comment]
I put in a PR to address the issue: #1113

**Comment by lgmoneda** [comment]
@tmylk Annoy isn't running in mutiple cores, while traditional implementation does.

Running to 10k words:
**Traditional**
> CPU times: user 20.6 s, sys: 38.7 s, total: 59.3 s
> Wall time: 7.55 s

**Annoy**
> CPU times: user 16.3 s, sys: 236 ms, total: 16.5 s
> Wall time: 16.1 s

So wall time is expected to be greater, since you have more cores in the first task. But total time, that addresses cpu time used and considers multiple cores, should be smaller. So it's running as expected.

Then, for comparing the two, we should indicate that the comparison need to be between Total CPU time and not wall-time.

**Comment by tmylk** [comment]
Yes, let's add the cpu time note

**Comment by piskvorky** [comment]
Yes, as mentioned in the PR, the actual performance depends on a number of factors. For example, whether the brute-force is multicore or not depends on your BLAS settings.

**Comment by tmylk** [comment]
Closing as fixed
