### ISSUE TITLE
HDP, default parameters for truncation swapped ?

### ISSUE THREAD

**Issue by ghost** [RaRe-Technologies/gensim#111]
Hi,

I have not checked very carefully the code or the math but I believe that the default values for K and T in the HDP model might have been erroneously swapped:
## 

http://radimrehurek.com/gensim/models/hdpmodel.html

K=15, T=150
## T: top level truncation level K: second level truncation level

v,.s. 
## 

Wang's 2011 paper

We set the truncations for the corpus and document
levels to K and T . Here, T can be set much smaller than
K, because in practice each document Gj requires far fewer
topics than those needed for the entire corpus

[...]
## We set the top-level truncation K = 150 and the second level truncation T = 15. Here T ≪ K, since documents usually don’t have many topics.

Eric

**Comment by FiorelaDelPilar** [comment]
Hi, please, can anybody explain me what exactly the value of K means? I know that T is the number of topics wanted but in that case what is K? I don't understand the "second level truncation level" phrase. If you can give me an example it could be awesome. Thanks
