### ISSUE TITLE
gensim.corpora not found

### ISSUE THREAD

**Issue by zijwang** [RaRe-Technologies/gensim#1111]
from gensim.corpora import WikiCorpus
ImportError: No module named gensim.corpora

I'm using gensim (0.13.4.1)

**Comment by greninja** [comment]
You might want to check your PYTHONPATH variable. 
Manually add path of your gensim library in your PYTHONPATH variable using 'export' like:
    `export PYTHONPATH="${PYTHONPATH}:/absolute_path/to/library`

**Comment by CarlosDutra** [comment]
Did it work?

**Comment by macanv** [comment]
I use the IDE of pycharm, in the console, it works well, but in IDE the follow error will be throw:
Traceback (most recent call last):
  File "E:/pro/python/topic_model/gensim/train_word2vec.py", line 9, in <module>
    from gensim.corpora import WikiCorpus
ImportError: No module named 'gensim.corpora'

about load model i use:
from gensim.corpora import WikiCorpus
 my python version is anaconda3(3.5.2)
