### ISSUE TITLE
Support sklearn pipeline interface. Continuing #932.

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#1123]
Pipeline interface is not supported in the sklearn wrapper added in #932 .

**Comment by rodrigocesar** [comment]
I tried to create a simple pipeline using the sklearn wrapper and got a an error.

The code is:

`from sklearn.pipeline import Pipeline
text_lda = Pipeline([('vec', CountVectorizer(min_df=10, stop_words='english')),
                     ('clf', SklearnWrapperLdaModel(id2word=id2word,num_topics=5,passes=20)),
])
text_lda = text_clf.fit(data.data)
`

The error i got was:


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-202-beba34394805> in <module>()
----> 1 text_lda = text_clf.fit(data.data)

C:\Users\posgr\Anaconda3\lib\site-packages\sklearn\pipeline.py in fit(self, X, y, **fit_params)
    163         """
    164         Xt, fit_params = self._pre_transform(X, y, **fit_params)
--> 165         self.steps[-1][-1].fit(Xt, y, **fit_params)
    166         return self
    167 

TypeError: fit() takes 2 positional arguments but 3 were given

**Comment by tmylk** [comment]
CC @AadityaJ

**Comment by menshikh-iv** [comment]
Resolved in #1462, #1473, #1437 and another PRs from @chinmayapancholi13.
