### ISSUE TITLE
Relying on numpy.random makes results hard to reproduce

### ISSUE THREAD

**Issue by larsmans** [RaRe-Technologies/gensim#113]
... and it also [confuses users of LDA](http://stackoverflow.com/q/15067734/166749).

In scikit-learn, we've solved this by [requiring](http://scikit-learn.org/dev/developers/index.html#random-numbers) a `random_state` argument to anything that wants random numbers; this may either be an `np.random.RandomState` object, or the seed for one. You might want to borrow this habit.

**Comment by adammenges** [comment]
:+1:

**Comment by piskvorky** [comment]
Here's a link to a pull request that did the same for GloVe; looks simple enough:
https://github.com/maciejkula/glove-python/pull/32

**Comment by cvint13** [comment]
When I run the model I still get different results every time despite using a fixed seed:

```
lda = LdaMulticore(corpus, num_topics=100, workers=4,id2word=dictionary,
                   random_state=np.random.RandomState(seed=10101010),
                  alpha=np.array([.0075] * 100))
```

**Comment by gojomo** [comment]
@cvint13 Anything multithreaded will also be subject to scheduling jitter from the OS – operations won't happen in the same order, and thus results will vary. For full reproduceability, you'd have to move to a (much-slower) single-threaded calculation (`workers=1`).

**Comment by cvint13** [comment]
Ahhh ok, that sucks.

**Comment by piskvorky** [comment]
For completeness -- `LdaMulticore` uses processes, not threads.

@menshikh-iv is it expected that @cvint13 would get different results, despite a fixed seed? Are the individual jobs processed in arbitrary (non-deterministic) order?

**Comment by menshikh-iv** [comment]
@piskvorky yes (for multicore implementation only).
