### ISSUE TITLE
Len used on generator

### ISSUE THREAD

**Issue by BartlomiejLewandowski** [RaRe-Technologies/gensim#1130]
Python 2.7.12
gensim version: '0.13.4.1'

I have a big dataset which I want to learn embeddings on. I'm using the method described here to create an iterable with a single sentence which is a generator which yields a word at a time.

```
#lazily loads file word by word
def file_split(f, delim=' ', bufsize=1024):
    prev = ''
    while True:
        s = f.read(bufsize)
        if not s:
            break
        split = s.split(delim)
        if len(split) > 1:
            yield prev + split[0]
            prev = split[-1]
            for x in split[1:-1]:
                yield x
        else:
            prev += s
    if prev:
        yield prev

class MySentences(object):
    def __init__(self, filename):
        self.filename = filename

    def __iter__(self):
        yield file_split(open(self.filename))

model = gensim.models.Word2Vec(sentences, min_count=1)
```

The code that fails with TypeError: object of type 'generator' has no len()

    def _raw_word_count(self, job):
        """Return the number of words in a given job."""
        return sum(len(sentence) for sentence in job)

Is this not supported? Should I create fake fixed length sentences and feed that to the model?

**Comment by greninja** [comment]
Word2vec does not support `sentences` as  a generator.

Replacing 'yield' with 'return' in '__iter__' method will work because then it wont be a generator anymore.

**Comment by BartlomiejLewandowski** [comment]
This will return a generator which will yield a single word in each sentence. Since we expect a list of lists, we iterate over the character of a word, which results in a dictionary to contain single letters.

**Comment by gojomo** [comment]
`sentences` may be a generator (or any other iterable), but each item from it (`sentence`) is currently expected to have a length. Also, since word-embedding training relies on the mutual-predictiveness of nearby-words within the same `sentence`, single-word sentences won't allow any useful training to happen. (All such sentences are no-ops for training purposes.)

I believe the `LineSentence` class already in the module – see https://github.com/RaRe-Technologies/gensim/blob/dcaa702b3cdd49761eef75132df40b29b69b1604/gensim/models/word2vec.py#L1429 – will do what you need without requiring your own `MySentences` class.

**Comment by BartlomiejLewandowski** [comment]
LineSentence uses the file object and yields each line, spitting the line to return a list of words. My input file does not have any new lines, so I need a different way to lazily fetch a limited amount of words. 
I'll try running this with creating artificial sentences by using zip on the iterable.

**Comment by piskvorky** [comment]
@BartlomiejLewandowski that sounds exactly like the built-in (and perhaps poorly named) [Text8Corpus](https://github.com/RaRe-Technologies/gensim/blob/dcaa702b3cdd49761eef75132df40b29b69b1604/gensim/models/word2vec.py#L1401). See if that sentence generator fits your bill.

**Comment by BartlomiejLewandowski** [comment]
That's looks like exactly what I'm after, I'll check it out in a few hours and will close the issue. Thanks a bunch!

**Comment by piskvorky** [comment]
Np :)

**Comment by greninja** [comment]
@gojomo  Could you please explain how `sentences` can be a generator? Because [Line 449](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/word2vec.py#L449) clearly doesnt allow to pass `sentences` as a generator, right?

**Comment by gojomo** [comment]
@greninja Yes, sorry, you're right - but you can pass in an iterable object that returns a generator, each time an (re-)iteration is requested.

**Comment by piskvorky** [comment]
@greninja a bit of confusion there: `sentences` can be passed into the constructor, or directly into the `train()` and `build_vocab()` methods.

If you pass it directly, the `sentences` variable may be a generator (once-only stream).

If you pass it to the constructor, `sentences` must be an iterable (repeatable stream).

It is perhaps unfortunate both are called the same name... proper type annotations (static typing or at least Python 3) would have made this clearer. Sorry.

**Comment by BartlomiejLewandowski** [comment]
That worked, really great to see such an active community willing to help. Keep it up :)
