### ISSUE TITLE
Preserve article titles in make_wikicorpus.py

### ISSUE THREAD

**Issue by chrisjmccormick** [RaRe-Technologies/gensim#1133]
First let me say that having a ready-to-run script to generate a corpus from Wikipedia is awesome! Thank you guys!

What seems like a major omission, to me, though, is that the titles of the articles aren't saved anywhere, that I can tell. It seems like the corpus isn't really useable unless you can map back from the vector index to its article title...

**Comment by piskvorky** [comment]
Thanks for the kind words.

This functionality is already in gensim: [wikicorpus.extract_pages()](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/corpora/wikicorpus.py#L190) yields 3-tuples `(title, content, page_id)`.

To store the title, you'd have to modify the CLI script a bit, depending on what exactly do you need. The corpus iterator method (which discards the titles right now) is [here](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/corpora/wikicorpus.py#L299).

**Comment by chrisjmccormick** [comment]
Thanks, Radim!

I don't think `extract_pages` is what I want, since `get_texts` does some pruning, so the indeces of the articles wouldn't match, right?

I see that if I set the `metadata` property of the `WikiCorpus` to `True`, then `get_texts()` will yield `(tokens, (pageid, title))`, that’s great. (what’s pageid, by the way?).

`get_texts` is called in the WikiCorpus constructor [here](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/corpora/wikicorpus.py#L279) as part of initializing the `Dictionary`. But the `Dictionary` doesn't preserve the article titles for me, right?

Is `get_texts` called again during `serialize` (maybe [here](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/corpora/textcorpus.py#L72)?)? If so, do the article titles get preserved somehow there if `metadata = True`?

Thanks again!

**Comment by chrisjmccormick** [comment]
I think I've figured this out...

After creating the WikiCorpus [here](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/scripts/make_wikicorpus.py#L92), you just need to set:
``
wiki.metadata = True
``
and it will preserve the article titles.

Then, pass the same to serialize:
``
MmCorpus.serialize(outp + '_bow.mm', wiki, metadata=True, progress_cnt=10000)
``

This will write out the article titles to a pickle file `*_bow.mm.metadata.cpickle`

This metadata feature is really useful but doesn't appear to be [documented](https://radimrehurek.com/gensim/corpora/mmcorpus.html).

Loading the MmCorpus doesn't reload this metadata file, so you just need to use pickle to load it yourself.

Thanks!

**Comment by tmylk** [comment]
Thanks for posting the fix. Created a documentation issue #1161
