### ISSUE TITLE
[Question] Sentence segmentation in gensim

### ISSUE THREAD

**Issue by narenchoudhary** [RaRe-Technologies/gensim#1135]
I need to split corpus text stream into sentences for further processing. I checked [gensim documentation](https://radimrehurek.com/gensim/apiref.html) but could not find anything on sentence segmentation. 

Is there any utility available in gensim for sentence segmentation?

**Comment by gojomo** [comment]
No, gensim generally expects such tokenization to happen elsewhere. Popular Python options for this include NLTK or Spacy.io.

**Comment by narenchoudhary** [comment]
It's a very basic and must have functionality in a nlp library. gensim provides functions for parsing text from corpus. It also has models that take list of sentences as argument. But there is no utility for segmenting text into sentences which is very disappointing. :disappointed:

**Comment by piskvorky** [comment]
I agree. Unsupervised segmentation (into blocks/sentences/words) falls nicely under gensim's mission. Pull requests welcome :)

CC @tmylk .

**Comment by tmylk** [comment]
Added to [wiki](https://github.com/RaRe-Technologies/gensim/wiki/Ideas-&-Feature-proposals)

**Comment by rpedela** [comment]
The summarization code splits text into sentences. Based on the English summary results, it does a great job.

https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/summarization/textcleaner.py
