### ISSUE TITLE
local gensim source code returns the version of global installation

### ISSUE THREAD

**Issue by ymnliu** [RaRe-Technologies/gensim#1138]
While using `gensim.__version__` to check on the version, the current code returns the global version number. This is caused by Line 10 in `gensim.__init__.py`:
`__version__ = __import__('pkg_resources').get_distribution('gensim').version
`. 

In my situation, I have a newer version (0.13.0) installed in my system paths and I try to use an older version (0.10.3) of gensim in a project. I put the source code of the older version in the working directory of the project, so when I do `import gensim`, only the older version of gensim is imported.

However, though the local (older) gensim is imported, `gensim.__version__` will still return the global version number, which is not correct in local configurations. Can the version number be hard-coded like what `scikit-learn` does [here](https://github.com/scikit-learn/scikit-learn/blob/debian/0.17.0-1/sklearn/__init__.py)?

**Comment by tmylk** [comment]
Thanks for reporting this.
