### ISSUE TITLE
Phrases multiprocessing

### ISSUE THREAD

**Issue by AaronWang30** [RaRe-Technologies/gensim#1141]
Is that supported? Since when I'm running word2vec with phrases, the speed is quite slow and I got some info like

2017-02-10 22:26:42,404: INFO: PROGRESS: at 0.23% examples, 156666 words/s, in_qsize 0, out_qsize 0

where in_qsize and out_qsize is always 0 or 1. Is that normal?

**Comment by piskvorky** [comment]
Phrases are quite slow now, because they're written in pure Python. As such, word2vec training consumes its input faster than phrases can supply it (likely reason for the empty queues), so the word2vec training is "starved for data" and slower than it could be.

Rewriting the phrases in Cython/C for performance is pretty easy and high on our TODO list, a much needed feature.

If you want to help out, @tmylk can direct you to the ticket / assist with PR.

**Comment by patcollis34** [comment]
Hey any update on this? I took a quick glance over the code and I see a couple easy wins.  First being replace your defaultdict with a bounter and eliminating this list creation: s = [utils.any2utf8(w) for w in sentence].  I would imagine that one of you have already thought about this and are working on something more C or "Cythony". @tmylk @piskvorky @AaronWang30

**Comment by menshikh-iv** [comment]
@patcollis34 unfortunately, for the current moment no any progress. We also have the more global issue (not only about phrases) https://github.com/RaRe-Technologies/gensim/issues/1654 (bounter integration to all "counting" places).
I never heard about [cytoolz](https://github.com/pytoolz/cytoolz), @piskvorky please have a look.
It will be very nice if you make PR and fix issue @patcollis34, what do you think?

**Comment by piskvorky** [comment]
Cythonizing + bounter ought to be enough, and it's easy to do too (just a few lines).

I think this would be a great easy intro project.

Only one question: do we keep support for "pure Python" = when a person doesn't have a compiler, can they still install and use gensim? Or do we require a compiler (and provide binary wheels where possible)?

**Comment by menshikh-iv** [comment]
@piskvorky as for me, we **should** support "pure python" only if it works fine (stable, fast enough), phrases work OK by performance (not very fast, but it's possible to run it with big corpus).

Ideally, we need to have universal wheels for all platforms, then we can safely remove all "replaced pure python" parts.

**Comment by piskvorky** [comment]
@mleue I think Cython is a great step. I wouldn't worry about parallelization (which is hard to do in Python). But see also #2048 .

Regarding Bounter: it helps with speed too (a little faster than dict). But  yes, lower memory footprint is its main advantage.

But simply rewriting Phrases (the slow inner parts) in Cython sounds like an awesome first step. Easy wins first :)

**Comment by patcollis34** [comment]
The reason I gave up on this is waiting on #1477, refactor the base corpus structure. To do some better/more interesting sampling methods across cores and solve the other bottleneck of the .any2utf8. Do you agree with this @piskvorky? 

But the bounter/cython stuff should be helpful also.

**Comment by patcollis34** [comment]
I can't find docs on how to be allowed to push to a branch to make this suggestion/diffs more readable. but I'm thinking you could delete all .gets in the [_learn_vocab](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/phrases.py#L593) for loop  and have func return only the joined words and then rely on the stdlib Counter to do the counting and joining for you. sorry for the noob screenshots. thoughts?@piskvorky 
![image](https://user-images.githubusercontent.com/7991125/131236047-cc64a357-b2c0-461c-b6e8-443ebd329062.png)
![image](https://user-images.githubusercontent.com/7991125/131236056-07784800-e076-48d2-b1f1-0a6024e6c626.png)

**Comment by piskvorky** [comment]
Why, what would that give us?

**Comment by patcollis34** [comment]
This makes it more map/"reducey" and pushes everything to the stdlib/c. removing 2 gets and +'s here makes this code a good bit faster. I was seeing about ~2x speedups with smaller corpus(~30k sentences) I was using. I forgot the single token append(426) in the first version. IMO this also paves the way for some to multiprocess it in an afternoon or so
![image](https://user-images.githubusercontent.com/7991125/131250894-d3770eea-30d5-4c72-bef5-e05cbb3f1645.png)

**Comment by piskvorky** [comment]
Thanks, a 4x speed up sounds promising. Can you open a PR, to explore your ideas?

I looked up the PR where I cleaned up the code. It includes some timings too: https://github.com/RaRe-Technologies/gensim/pull/2976#issuecomment-705501446 . Let's try your PR on the same corpus (text8), for easy comparison.
