### ISSUE TITLE
Creating a SparseMatrixSimilarity always requires constructing an in-memory sparse matrix even if you provide one

### ISSUE THREAD

**Issue by spearsem** [RaRe-Technologies/gensim#1142]
You can [see in the SparseMatrixSimilarity constructor](https://github.com/RaRe-Technologies/gensim/blob/17a01cfa6363eb0c13600e4abcc7cfe68fd9c38d/gensim/similarities/docsim.py#L664) that there is no code path that would allow you to avoid creating a totally new sparse matrix from a sparse-matrix-based corpus. The constructor makes a call to `matutils.corpus2csc` which [always populates `data`, `indices`, and `indptr` arrays and makes a call to `scipy.sparse.csc_matrix`](https://github.com/RaRe-Technologies/gensim/blob/e4114336591e2dcd311260b7b221e2427335417a/gensim/matutils.py#L111) which materializes a whole new sparse array in memory.

When a user already has a csc sparse array available (say they have saved `data`, `indices`, and `indptr` to disk and can load with mmap and then pass to `scipy.sparse.csc_matrix` all outside of gensim) -- there doesn't appear to be a way to leverage this when constructing the similarity index. For very large arrays, this can be a big problem, because while 1 copy might fit well into memory, two copies might not.

On a side note, I have also found the usage of `num_terms` and `num_docs` parameters a little tricky in the handling of the `scipy.sparse` corpora. When using a Matrix Market format, it is all straight forward and it's clear you are always iterating over the documents dimension.

But consider with the SparseMatrixSimilarity that it [implicitly takes the transpose after converting to the sparse format](https://github.com/RaRe-Technologies/gensim/blob/17a01cfa6363eb0c13600e4abcc7cfe68fd9c38d/gensim/similarities/docsim.py#L685) -- meaning you have to ensure that whatever gets returned from `corpus2csc` has **terms** as the first dimension, as indicated in the [output shape that function chooses](https://github.com/RaRe-Technologies/gensim/blob/e4114336591e2dcd311260b7b221e2427335417a/gensim/matutils.py#L111).

But when you read the code of `corpus2csc` it appears to simply iterate over the sparse array that it's given, with e.g. `for docno, doc in enumerate(corpus):` -- which will iterate the *rows*. 

(Extra aside -- it looks like this section of code does [two passes over each doc (each row)](https://github.com/RaRe-Technologies/gensim/blob/e4114336591e2dcd311260b7b221e2427335417a/gensim/matutils.py#L118) inside the primary loop. This looks like a good place to try to optimize it a little more.)

At any rate, after reading the code several times, it's still not clear to me whether a sparse csc input matrix needs to start out with terms along the rows, or have documents along the rows and then some internal function will automatically transpose it. The for-loop in `corpus2csc` makes it seem like the latter, an iteration over documents (as rows) that somehow ends up with terms as rows by the end. But it's very unclear.

**Comment by tmylk** [comment]
Hi,

Just making sure I understand your suggestion.

What if one passes None as corpus to SparseMatrixSimilarity constructor and then assigns .corpus and .index from mmapped files? Would that work for you?

The [posnext](https://github.com/RaRe-Technologies/gensim/blob/e4114336591e2dcd311260b7b221e2427335417a/gensim/matutils.py#L111) parameter iterates through all the terms in this for loop. That it results in a (num_terms, num_docs) shape. Or did you mean another for loop?

**Comment by tmylk** [comment]
Did you find a way to resolve this problem?

**Comment by spearsem** [comment]
I'm still working on it. I think part of the problem is how the LSI model's transformation gets applied. It assumes you're given a corpous to iterate through in chunks, and apply the transformation to each chunk. During that process, it seems like it's not possible to provide the base corpus in an already-csc format. It will still apply the `corpus2csc` logic to it no matter what you do or what data you provide. So it's not only creating the `SparseMatrixSimilarity`, but also communicating that whatever gets transformed can assume it's starting from something that's already in csc format and doesn't need to be converted again before it is chunk-wise iterated. I need to do more digging though.

**Comment by spearsem** [comment]
@tmylk I think I can articulate the problem a bit better now.

Suppose you have trained an `LsiModel` object and saved it to disk. Now you want to load it and produce a `SparseMatrixSimilarity` based on the documents underlying the trained `LsiModel`.

If you do something like,

```python
corpus = load_corpus_from_csc_files()
lsi_model = load_lsi_model_from_disk()
lsi_corpus = lsi_model[corpus]
```

this will be incredibly slow and memory intensive. The reason is that `__getitem__` from `LsiModel` uses an inherited method, `_apply` from `TransformationABC`. In `_apply`, a set of `chunksize` documents are fed back into `LsiModel.__getitem__` at a time, with `chunksize` explicitly set to `None` so that each chunk's worth of documents gets the "real" processing.

That "real" processing [always involves calling `corpus2csc`](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/lsimodel.py#L440) no matter what you do. You can't circumvent this, and if you pass in a corpus that's already from `Scipy2Corpus`, it can be excessively slow and wasteful of memory to iterate back through each chunk and perform a needless conversion from a sparse format to the same sparse format.

Is there a way to apply the LSI transformation to a sparse matrix of documents that avoids this?

**Comment by piskvorky** [comment]
Combining LSI and sparse vectors is not a good idea. LSI vectors are dense, so this will cost you a lot of memory and performance.

But even then, a conversion between the corpus format (list of tuples) and CSC shouldn't be that slow, I don't think. When you say "incredibly slow and memory intensive", what numbers do you have to back that up?

**Comment by spearsem** [comment]
I think you're misunderstanding. The source data (~25 million input documents, which is actually a subsample of a ~100 million document sparse matrix that this will be extended to) starts out as a sparse matrix. There's no way to change that. I'm not choosing this, it's just the format of the data based on all the other applications that use, and which any gensim-based LSA model would have to interface with to work in our situation.

As for the slow and memory intensive, it's obvious from the code. Once I load the sparse corpus in IPython or some script, I can observe the memory of the process with e.g. `htop`. Then I can watch the memory grow linearly to double the size while it iterates the chunks to transform, until it reaches approx. double. For the matrix I'm dealing with, ~17GB, this pushes the limits of what memory is available.

I know that the topic vectors will be dense. That's not what this about. I'm not trying to store topic vectors in a sparse format. I'm trying to produce the topic vectors for the input set of 25 million sparse bag of words vectors (the documents).

**Comment by spearsem** [comment]
It's also confusing when you say, 'combining LSI and sparse vectors is not a good idea.' The code I'm talking about, [linked here](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/lsimodel.py#L440) implies that when transforming the bag of words documents into LSI topic representation, gensim will *always* convert to a sparse format before hand.

**Comment by piskvorky** [comment]
I'm talking about scipy sparse. The transformation is pretty cheap AFAIK, so I wonder what numbers you're seeing.

Streamed iteration should definitely not consume double the memory -- its overhead is ±0 (just one chunk at a time). So I suspect the extra memory is coming from somewhere else.
