### ISSUE TITLE
build_vocab: TypeError: object of type 'map' has no len()

### ISSUE THREAD

**Issue by riccardo92** [RaRe-Technologies/gensim#1143]
Upon running model.build_vocab I get the following error:

```
 File "/usr/local/lib/python3.6/site-packages/gensim/models/word2vec.py", line 533, in build_vocab
    self.scan_vocab(sentences, progress_per=progress_per, trim_rule=trim_rule)  # initial survey
  File "/usr/local/lib/python3.6/site-packages/gensim/models/doc2vec.py", line 673, in scan_vocab
    document_length = len(document.words)
TypeError: object of type 'map' has no len()
```

For reference:

...$ pip3 show gensim
Name: gensim
Version: 0.13.4.1
Summary: Python framework for fast Vector Space Modelling
Home-page: http://radimrehurek.com/gensim
Author: Radim Rehurek
Author-email: me@radimrehurek.com
License: UNKNOWN
Location: /usr/local/lib/python3.6/site-packages
Requires: smart-open, six, numpy, scipy

**Comment by tmylk** [comment]
@riccardo92 It is the second time we get this report. Maybe we should improve the error message?

**Comment by riccardo92** [comment]
@tmylk This was my mistake. I should have commented that by instead I closed the issue.

Anyway, it was caused by not converting an input map to a list, so the sentences I gave to the model contained maps of words instead of lists of words.
