### ISSUE TITLE
Performance of data streaming from file vs directory of files

### ISSUE THREAD

**Issue by Threynaud** [RaRe-Technologies/gensim#1157]
Hi everyone,

I asked this question on SO [here](http://stackoverflow.com/questions/42368713/performance-of-data-streaming-from-file-vs-directory-of-files) but I thought it might be useful to ask it here as well.

I am using word2vec from Gensim and I am feeding sentences to the model with the following iterator:

```
class SentencesIterator(object):
    def __init__(self, source):
        self.source = source

        if os.path.isdir(self.source):
            self.type_source = 'dir'
        else:
            self.type_source = 'file'

    def __iter__(self):
        if self.type_source == 'dir':
            for fname in os.listdir(self.source):
                with open(os.path.join(self.source, fname)) as f:
                    for line in f:
                        yield line.split()
        else:
            with open(self.source) as f:
                    for line in f:
                        yield line.split()
```
Everything is working as attended but I noticed that the performances are varying a lot depending on the type of input.

For a single file in input: `INFO : PROGRESS: at 5.43% examples, 73483 words/s`

For a directory with 1 file: `INFO : PROGRESS: at 17.09% examples, 71716 words/s`

For a directory with 2 files: `INFO : PROGRESS: at 11.62% examples, 67678 words/s`

For a directory with 30 files: `INFO : PROGRESS: at 1.19% examples, 54004 words/s`

And it goes worse when I add more files in the directory..

I don't understand the decrease in the speed of streaming. To me, all the operations are identical, it is just about opening a file and reading it line by line..

PS:  I get the same behavior with 1 or 4 cores!

**Comment by tmylk** [comment]
@Threynaud Apologies, but it is more of a Python I/O forum question. Once the data is loaded into memory you should get the same word/s from gensim in each situation.

**Comment by piskvorky** [comment]
@Threynaud these progress snapshots seem to be taken at different times, and near the beginning of the training.

They all sound rather low too (I'd expect 10x faster progress).

So my suggestion would be to compare the same data (single file vs. the same file split across many smaller files), and report the speed at the same training point (such as from the end of training).

Otherwise I agree, there's no reason the speed should be any different.

**Comment by gojomo** [comment]
@Threynaud - it takes a while for training to reach peak rate, and the rate can vary based on the text (rare vs common words, length of examples, etc), and those displayed rates are only for the last reporting period (default 1 second, across which rates can jitter somewhat) – so for a true comparison you'd want to ensure you were taking a longer sample, over the exact same kind of text, with absolutely nothing else competing for IO/CPU. 

It's possible the file close/open could introduce a small pause; you could time the iterator alone, on a single file vs the exact same file split into 100 shards, to see if this is a factor. (For example, filesystems may put single files into spinning-disk sector positions that are optimal for streaming reads, but not do the same for sets of files.)

If the extra files actually add new words – making the trained vocabulary larger – that could affect the training rate. (Training involves lookups in a dictionary, and random-access across a large array. A larger vocabulary, spreading that data over more RAM, could make training slower through lower CPU cache efficiency.)
