### ISSUE TITLE
Add metadata to WikiCorpus docs

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#1161]
As mentioned in this [comment](https://github.com/RaRe-Technologies/gensim/issues/1133#issuecomment-278826784) `metadata` parameter  is not well-document in the WikiCorpus.

It needs to be added to [init](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/corpora/wikicorpus.py#L261) and to the wiki script parameters.

**Comment by kirit93** [comment]
Hi! I'd like to get started contributing to Gensim and I thought this would be a nice way to start. As I've understood the issue, documentation about the ```metadata``` parameter is required here https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/corpora/wikicorpus.py#L261 right?
I'm unsure about how to add documentation to the wiki script. If you could point me in the right direction, I'd really appreciate it. Thanks!

**Comment by tmylk** [comment]
Hi. Welcome! Could you please make your question more precise?

**Comment by kirit93** [comment]
When you said ```metadata``` documentation needs to be added to init, does it need to be added to the comments under the ```__init__``` function definition?

**Comment by tmylk** [comment]
Yes, that is the docstring. It is also mentioned in tutorials and on top of the file
