### ISSUE TITLE
what is the 'sample_int' mean in word2vec model?

### ISSUE THREAD

**Issue by luckystar1992** [RaRe-Technologies/gensim#1174]
In the source code of gensim>models>word2vec.py , one of function named train_batch_cbow(...) of Word2Vec class, there;s one variance 'sample_int' , what does it meas?

**Comment by gojomo** [comment]
You can see `sample_int` calculated and assigned for each vocabulary word at:

https://github.com/RaRe-Technologies/gensim/blob/4dc6c74d5ae9b22367e044a4da44a27277f50f5b/gensim/models/word2vec.py#L677

It's an optimization to allow the downsampling of frequent words, as controlled by the `sample` parameter, to be done with entirely int randomization/comparison. 

Please use the project forum, <https://groups.google.com/forum/#!forum/gensim>, for general questions/discussion – reserving this issue tracker for bugs and feature-requests.
