### ISSUE TITLE
EOFError during loading doc2vec model

### ISSUE THREAD

**Issue by flashkari** [RaRe-Technologies/gensim#1175]
I could not load a doc2vec model on my computer and I got the following error. 
This is the code:

```
# coding: utf-8
from gensim.models.doc2vec import Doc2Vec
import gensim.models.doc2vec
from gensim.models.doc2vec import LabeledSentence
import os
import pickle
pth='/home/fatemeh/Step2/input-output/model/iterator'
model= Doc2Vec.load(pth+'/my_model.doc2vec')
```
This is the error:

```
    Traceback (most recent call last):
  File "CreateAnnoyIndex.py", line 16, in <module>
    model= Doc2Vec.load(pth+'/my_model.doc2vec')
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.13.3-py2.7-linux-x86_64.egg/gensim/models/word2vec.py", line 1762, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.13.3-py2.7-linux-x86_64.egg/gensim/utils.py", line 248, in load
    obj = unpickle(fname)
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.13.3-py2.7-linux-x86_64.egg/gensim/utils.py", line 912, in unpickle
    return _pickle.loads(f.read())
```

I create  my model based on the following code:
`allDocs = docIterator(inputPath)
model = Doc2Vec(allDocs, size = 300, window = 5, min_count = 2, workers = 4)`

**Comment by gojomo** [comment]
It is likely the save file has been corrupted or truncated. 

Has this happened once, or does it happen every time you generate a new model, save, and then load?

Do you have logs of the output during the `save()`, and do you have logging on, so you can see if any errors/warnings were reported at that time?  

Note that larger models will be saved to multiple files (with a shared prefix), so if you move the saved-model later, you may need to move multiple files together.

**Comment by flashkari** [comment]
Thanks.
I did not know that larger models is saved to multiple files.

Best Regards,
Fatemeh
