### ISSUE TITLE
If i use lsi.add_documents for information retrieval, how should we generate the dictionary and how does the model merge

### ISSUE THREAD

**Issue by sherlockhoatszx** [RaRe-Technologies/gensim#1178]
Dear Gensim Team:
Thanks for your wonderful work ! Quoting the script from the [LSI API](https://radimrehurek.com/gensim/models/lsimodel.html)

>lsi = LsiModel(corpus, num_topics=10)
>print(lsi[doc_tfidf]) # project some document into LSI space
>lsi.add_documents(corpus2) # update LSI on additional documents
>print(lsi[doc_tfidf])`

What confuse me are:
1. Corpus is a word-doc matrix,right? LSI truncate the corpus (w-d matrix) into U,S,V matrix(by SVD).**corpus1 and corpus2** ,although them got same dimension,but, the**rows'words list could not be the same**,right? so **how could we merge U1,U2 if the rows represent different words**?I do a search and find Radim's awsome [paper](http://radimrehurek.com/phd_rehurek.pdf),but that seems doesn't solve my confusion
2. My scenario is  information retrieval, I use LSI as one step to select topN similartiy docs. To do information retrieval, I should use *dictionary* to **build query BOW** first, and then to do similarity calculation.
>    query_bow = dictionary.doc2bow(que_aft_list)
    query_lsi = lsi[query_bow ]
    sims = index[query_lsi] 

My confusion is the dictionary, *should i use **corpus1+corpus2 to generate dictionary** or i should just use **corpus2(say,the latest one） to generate dictionary**?*

Looking forward to hearing from you
Thanks

**Comment by sherlockhoatszx** [comment]
Hi, I studied the Radim's paper in detail, and found one picture to show your functions
![lsa_algorithms_comparition](https://cloud.githubusercontent.com/assets/14892920/23580643/8e61c656-0140-11e7-85e1-790d777f44ed.jpg)

If the genesim incremental(stream) LSA code was designed as the last row(rehurek2011b), It seems that genesim's LSA support add new documents ,but don't support add new features.

Considering this situation:I need to do the streaming training manually. I got corpus1,corpus2. Cause the LSA doesn't support new features .So here is my idea: 
- Step0: I generate a dictionary based on both corpus1 and corpus2.
- Step1: I trained corpus1. lsimodel1,and dictionary1 was generated. 
- Step2: New documents come in, and I add the document into the model. 

Q1:**My point is should i build a dictionary based on the whole corpus or i just build dictionary1 based on corpus1 to train, and dcitionary2 based on corpus2 to train.**

Further more, what if I have already trained a LSA model based on all documents i got, and one year later, new documents come in. How should i to do with the dictionary ?
-  Option1: I built dictionary based the new documents ,and coding the lsi.add_documents(corpus2) .
- Option2: I re-built the dictionary based on the older and new corpus, and coding the lsi.add_documents(corpus2) according to the new corpus. 
- Option3: I re-built the dictionary and re-trained the whole model.
Q2: which option is right?

**Comment by tmylk** [comment]
@sherlockhoatszx You are right that LSI doesn't support vocabulary expansion. Option 3 is best. N-gram methods like FastText work relatively well with out-of-vocabulary words. There is also a little-researched way to increase the vocabulary though it hasn't been shown to work better than Option 3.

By the way such open-ended questions are better suited for the mailing list. Closing this issue to continue discussion there.
