### ISSUE TITLE
`load()` in 1.0.0 not rebuilding necessary down-sampling `cum_table`

### ISSUE THREAD

**Issue by gojomo** [RaRe-Technologies/gensim#1180]
See: https://groups.google.com/d/msg/gensim/F9SLBpik4Yg/Jz7BhRH_DQAJ

The test in Word2Vec `load()` is only chcking for `index2word` in its old location, thus a necessary structure for continued training isn't rebuilt. 

Surprised no existing save/load tests catch this  as the re-build should even be necessary for a save/load within the same latest gensim version.

**Comment by tmylk** [comment]
Thanks. are you working on a fix or should I submit a pr?

**Comment by piskvorky** [comment]
@tmylk what is the explanation for this bug making it past the unit tests?

**Comment by gojomo** [comment]
Not currently working on this; just wanted to make sure there was an issue that could be triaged/assigned. Not sure the understanding above is fully correct - the code looks broken, but I would have expected any save/load that involves a (default) negative-sampling model to have triggered the error, so aspects of the problem as-reported are still unclear.

**Comment by gojomo** [comment]
To be clearer: any [save, load, train] should trigger the error - perhaps no existing tests try training after load? Adding either a `train()` or some other set of 'model is healthy' assertions after `load()` may make for better tests.

**Comment by tmylk** [comment]
There is no unit test that covers training after load in either doc2vec or word2vec. Adding them now.
