### ISSUE TITLE
MmCorpus init attempting to cast string of format '0.xxx...' into int unsuccessfully

### ISSUE THREAD

**Issue by gabbifish** [RaRe-Technologies/gensim#1184]
I'm attempting to load a tfidf.mm file into an MmCorpus object, and the format of the .mm file is as follows:

```
%%MatrixMarket matrix coordinate real general
1 92 0.0305010044907
1 110 0.0378707913004
1 683 0.0160038229867
....
```

I get the following error:
```
2017-03-06 05:54:46,574 : INFO : initializing corpus reader from wiki_subset_tfidf.mm
Traceback (most recent call last):
  File "lda.py", line 7, in <module>
    mm = gensim.corpora.MmCorpus('wiki_subset_tfidf.mm')
  File "/usr/local/lib/python2.7/dist-packages/gensim/corpora/mmcorpus.py", line 29, in __init__
    matutils.MmReader.__init__(self, fname)
  File "/usr/local/lib/python2.7/dist-packages/gensim/matutils.py", line 754, in __init__
    self.num_docs, self.num_terms, self.num_nnz = map(int, line.split())
ValueError: invalid literal for int() with base 10: '0.0305010044907'
```

It looks like matutils.MmReader.__init__(self, fname) in the MmCorpus class init function is attempting to cast '0.0305010044907' into an int, which 
a) would not work after .split() is called by MmCorpus.init on the lines of the .mm file, which outputs a list of strings, and 
b) seems like an unexpected expectation given that the field self.num_nnz doesn't seem to need to be an integer in the matutilsMmWriter class. I think there may be an issue with the casting of every field in the .mm file as an int(), unless my .mm file was not written correctly?

Thanks!

**Comment by tmylk** [comment]
Hi @gabbifish ,

May I ask about the origin of this MM file? Maybe something changed in the format.

The first non-commented line of an MM file should contain number of rows, columns, and number of non-zero entries - all ints. The `num_nnz` is the number of non-zero entries. That is according to the [Coordinate MM format spec](http://math.nist.gov/MatrixMarket/formats.html)

```
%%MatrixMarket matrix coordinate real general
%=================================================================================
%
% This ASCII file represents a sparse MxN matrix with L 
% nonzeros in the following Matrix Market format:
%
% +----------------------------------------------+
% |%%MatrixMarket matrix coordinate real general | <--- header line
% |%                                             | <--+
% |% comments                                    |    |-- 0 or more comment lines
% |%                                             | <--+         
% |    M  N  L                                   | <--- rows, columns, entries
% |    I1  J1  A(I1, J1)                         | <--+
% |    I2  J2  A(I2, J2)                         |    |
% |    I3  J3  A(I3, J3)                         |    |-- L lines
% |        . . .                                 |    |
% |    IL JL  A(IL, JL)                          | <--+
% +----------------------------------------------+   
%
% Indices are 1-based, i.e. A(1,1) is the first element.
%
%=================================================================================
  5  5  8
    1     1   1.000e+00
    2     2   1.050e+01
    3     3   1.500e-02
    1     4   6.000e+00
    4     2   2.505e+02
    4     4  -2.800e+02
    4     5   3.332e+01
    5     5   1.200e+01
```

**Comment by gabbifish** [comment]
Hi @tmylk! I was following this guide: https://radimrehurek.com/gensim/wiki.html#id6

Which generates a tfidf.mm file using the script gensim.scripts.make_wiki. I took a look at the make_wiki script, which seemed to create the tfidf.mm in the expected manner:

`MmCorpus.serialize(outp + '_tfidf.mm', tfidf[mm], progress_cnt=10000)`

Should I run this script again on a subset of data to see if I get the expected mm file output? I wonder what could account for the unexpected nnz values...

Thanks!

**Comment by tmylk** [comment]
Unfortunately can't reproduce with the small wikipedia fragment we have in automated tests
`make_wiki.py test/test_data/enwiki-latest-pages-articles1.xml-p000000010p000030302-shortened.bz2 /tmp/wiki/`  produces

```
%%MatrixMarket matrix coordinate real general
106 31593 63473                                   
1 29 0.00419966889898
1 34 0.00493286150043
```

Had to modify the script to not filter rare words because the corpus is so small,
`wiki.dictionary.filter_extremes(no_below=0, no_above=0.1, keep_n=DEFAULT_DICT_SIZE)`

Please let me know if you get the same result.

**Comment by gabbifish** [comment]
Resolved by not filtering rare words with smaller test corpora. Thank you so much!

**Comment by tmylk** [comment]
Hi, could you please post your solution here so that future users don't get tripped by it? I am not sure I understand your solution

**Comment by gabbifish** [comment]
^ Following up: I stopped filtering rare words given the small size of the corpus. Instead of using the DEFAULT_DICT_SIZE  of 100000 words in the script gensim.scripts.make_wiki, which seems to have surpassed the number of words that actually existed in the corpus, I started with 10000 words and eventually tested larger dict sizes with larger training corpuses.

Hope this helps! 👍

**Comment by piskvorky** [comment]
MmCorpus format should always be correct, even if you pass in an empty corpus. Otherwise it's a bug.

So I'm still unsure what the cause of the originally reported error was (trying to parse float as int).
