### ISSUE TITLE
Sphinx warnings

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#1192]
Sphinx 1.5.3 [raises 108 warnings](https://gist.github.com/tmylk/11d42f19c2acabbcf9aac466e204dc5f) when generating gensim docs when running
```
cd docs/src
make clean html 
```

All the files are generated correctly even though Sphinx labels some of the warnings as `errors`.

The easiest warnings to fix are in the `rst` files of type `Title underline too short.`

The warnings in the `py` file are hard to fix because the line numbers listed in the error messages don't correspond to the line numbers in the files. For example, there is no docstring on line 41 though sphinx reports
`coherencemodel.py:docstring of gensim.models.coherencemodel.CoherenceModel:41: ERROR: Unexpected indentation.`

**Comment by menshikh-iv** [comment]
Finished in #1442
