### ISSUE TITLE
Error while installing gensim

### ISSUE THREAD

**Issue by markroxor** [RaRe-Technologies/gensim#1197]
While installing gensim for my branch [TF](https://github.com/markroxor/gensim/tree/TF). I came across this error
> running install
running bdist_egg
running egg_info
writing requirements to gensim.egg-info/requires.txt
writing gensim.egg-info/PKG-INFO
writing top-level names to gensim.egg-info/top_level.txt
writing dependency_links to gensim.egg-info/dependency_links.txt
reading manifest file 'gensim.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'COPYING.LESSER'
writing manifest file 'gensim.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating stub loader for gensim/models/word2vec_inner.so
creating stub loader for gensim/models/doc2vec_inner.so
byte-compiling build/bdist.linux-x86_64/egg/gensim/models/word2vec_inner.py to word2vec_inner.pyc
byte-compiling build/bdist.linux-x86_64/egg/gensim/models/doc2vec_inner.py to doc2vec_inner.pyc
copying gensim.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gensim.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gensim.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gensim.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gensim.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/gensim-1.0.0rc2-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
Traceback (most recent call last):
  File "setup.py", line 294, in <module>
    include_package_data=True,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 223, in run
    dry_run=self.dry_run, mode=self.gen_header())
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 467, in make_zipfile
    visit(z, dirname, files)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 460, in visit
    z.write(path, p)
  File "/usr/lib/python2.7/zipfile.py", line 1135, in write
    zinfo = ZipInfo(arcname, date_time)
  File "/usr/lib/python2.7/zipfile.py", line 305, in __init__
    raise ValueError('ZIP does not support timestamps before 1980')
ValueError: ZIP does not support timestamps before 1980

Though I resolved it by switching to a different branch, re-installing gensim and then trying to install gensim again from TF but why this error popped up in the first place? Other users might face the same issue.

**Comment by gojomo** [comment]
Is the error reproducible? (What precise command did you run, from which exact branch/revision, and do you get the error every time from that directory/command?)

The error message reads like it was attempting to make a ZIP file, but with a timestamp before 1980. Is there a chance that either (1) your system clock was wrong; or (2) some file in your working directory has a fake pre-1980 creation/modification date?

**Comment by markroxor** [comment]
> Is the error reproducible? (What precise command did you run, from which exact branch/revision, and do you get the error every time from that directory/command?)

I don't think so. I executed `sudo python setup.py install` from my branch https://github.com/markroxor/gensim/tree/TF . No that is not the case anymore.

> The error message reads like it was attempting to make a ZIP file, but with a timestamp before 1980. Is there a chance that either (1) your system clock was wrong; or (2) some file in your working directory has a fake pre-1980 creation/modification date?

I suspected the same. I've dual boot configuration I generally use Ubuntu but occasionally switch to Windows. My system clock for Ubuntu is correct but is messed up in Windows (because of an issue with Win10) but in either case both clocks are 5hrs 30minutes apart. (because my time zone is 5hrs 30mins ahead of UTC). I am unsure why `ZIP does not support timestamps before 1980` was raised.

**Comment by tmylk** [comment]
Closing as not reproduced.
