### ISSUE TITLE
Wiki Changes

### ISSUE THREAD

**Issue by bhargavvader** [RaRe-Technologies/gensim#1199]
The [roadmap](https://github.com/RaRe-Technologies/gensim/wiki/Roadmap) page seems to be outdated, and the [Word2Vec & Doc2Vec Wishlist](https://github.com/RaRe-Technologies/gensim/wiki/Word2Vec-&-Doc2Vec-Wishlist) also seems redundant.

**Comment by menshikh-iv** [comment]
Extended in #1604
