### ISSUE TITLE
No inference method for ldamallet (pyLDAVis gives an error)

### ISSUE THREAD

**Issue by icepieces** [RaRe-Technologies/gensim#1203]
I am trying to use the pyldavis for visualizing my LDA models built by the wrapper for mallet. The only way I can have the visualization to work is to convert the malletlda to a ldamodel. This doesn't allow to use the Gibbs Sampling Inference in mallet and also somehow ignores my stopwords.

**Comment by tmylk** [comment]
Hi, Conversion from mallet wrapper format to ldamodel is one way so mallet-specific features Like Gibbs Sampling Inference can no longer be used. 
However the stopwords should not be dropped. Do you have a small corpus and code to reproduce?

**Comment by tmylk** [comment]
Closing as abandoned. Please re-open when the details are available.

**Comment by icepieces** [comment]
Hey Sorry but I was in meetings all day, I will try to get a dummy corpus and upload he code later.

**Comment by tmylk** [comment]
@icepieces do you have more exact details to reproduce?

**Comment by shenshifo** [comment]
Hey lev, 

how can I convert a ldamallet model to a ldamodel? I didn't find such method in ldamallet wrapper.  I want to visualize the topics from mallet wrapper using pyLDAVis.  Thanks.

**Comment by menshikh-iv** [comment]
Hi @icepieces, [this function](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/wrappers/ldamallet.py#L359) is needed for you. Example of usage [here](https://github.com/RaRe-Technologies/gensim/blob/db9e2303a84dd240970ca9188b6a18aba9c0ae00/gensim/test/test_ldamallet_wrapper.py#L106)

**Comment by menshikh-iv** [comment]
Hi @YuliyShamaev, are you sure that your ldamallet model is good enough (i.e. not under-fitted)?
Anyway, please prove saved ldamallet model for reproducing a problem.

**Comment by YuliyShamaev** [comment]
It's not about qualitty of lda model itself
I've viewed topics keywords using `ldamallet.show_topics` method
and it doesn't match visualization terms at all
Seems im not alone with this problem:
https://stackoverflow.com/questions/50340657/pyldavis-with-mallet-lda-implementation-ldamallet-object-has-no-attribute-inf

**Comment by menshikh-iv** [comment]
Potentially, `malletmodel2ldamodel` can contain a bug, but for reproducing I need at least mallet model (for a check that topics in mallet look good, but random in gensim), please share your model @YuliyShamaev
