### ISSUE TITLE
cannot import KeyedVectors in Python 3.5

### ISSUE THREAD

**Issue by barryef** [RaRe-Technologies/gensim#1204]
Error if I try to import from gensim.models, as was in the original code.

Also error when I tried to import from gensim.keyedvectors based on the page below.

https://radimrehurek.com/gensim/models/keyedvectors.html

Thx much ...

**Comment by prakhar2b** [comment]
@barryef could you show the error log please

**Comment by tmylk** [comment]
What gensim version are you using?

**Comment by barryef** [comment]
Hi prakhar2b and tmylk, 

My gensim version is 0.13

The traceback is below. The original code is line 14. I am now using lines 13 and 15 without apparent problem, so I have a workaround.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-51-f96276386a43> in <module>()
     12 
     13 #from gensim.models import Word2Vec, keyedvectors # , KeyedVectors
---> 14 from gensim.models import Word2Vec, KeyedVectors
     15 from gensim.models.keyedvectors import KeyedVectors
     16 from gensim.models.word2vec import Text8Corpus

ImportError: cannot import name 'KeyedVectors'

**Comment by barryef** [comment]
Actually, workaround is not working futher along in the code.

The code asks for KeyedVectors.load_word2vec_format

I can't find this function in either 
gensim.models.KeyedVectors or
gensim.models.keyedvectors.KeyedVectors.

**Comment by chinmayapancholi13** [comment]
Hey @barryef! The function `KeyedVectors.load_word2vec_format` has been defined in the file **gensim.models.keyedvectors** as a method of the class `KeyedVectors`. Could you please check again if you are looking in the correct file? If you still face an issue, I'd be happy to help further. :)

**Comment by barryef** [comment]
OK, I've found my solution. There's an updated version of the markroxor ipynb that only imports Word2Vec and runs without breaking at

https://markroxor.github.io/gensim/static/notebooks/Word2Vec_FastText_Comparison.html

Thanks for being around on the weekend ...

**Comment by tmylk** [comment]
@barryef The 1.0.0 version of gensim contains `KeyedVectors.load_word2vec_format`. Is there a reason for using 0.13.x?

**Comment by barryef** [comment]
No. I used pip to install and assumed I had the most recent version. I’ll update. 

 

Thx

**Comment by tmylk** [comment]
Are you using Anaconda? If yes, need to ping them to update.

**Comment by barryef** [comment]
Miniconda. I don’t know how to ping them.

**Comment by barryef** [comment]
Lev, I checked on pip, and pip install gensim is indeed at 0.13 but pip install –U gives gensim 1.01.
