### ISSUE TITLE
Can gensim.word2vec implement an activation function in hidden layer?

### ISSUE THREAD

**Issue by bojone** [RaRe-Technologies/gensim#1221]
the CBOW + HS model has 4 layers: 
one hot -- embedding -- sum -- predict proba

the Skip-Gram + HS model has 3 layers: 
one hot -- embedding -- predict proba

I want to add an non-linear activation on embedding or sum layers. Is it easy to be implemented? I suggust that gensim.word2vec can give us such an option. It has some special useful application.

**Comment by gojomo** [comment]
There's no existing interface for specifying a different activation function, so you'd have to review the code yourself, with a full understanding of what you want to achieve, to see if it's easy. (I'm not sure what benefits you'd be expecting, over the typical word2vec approach. Are you basing this request on some project that's proven benefits of such a change, based on their own implementation/testing?)

**Comment by aneesh-joshi** [comment]
Does Mikolov use any activation in the hidden layer?

**Comment by gojomo** [comment]
IIUC, the original word2vec.c code (and thus also the gensim code modeled after it) uses a sigmoid activation function.

**Comment by menshikh-iv** [comment]
@bojone @aneesh-joshi you can implement it with Keras/TF/Theano/AnyNNFramework.
For gensim, this isn't relevant.
