### ISSUE TITLE
doc2vec

### ISSUE THREAD

**Issue by yuquanle** [RaRe-Technologies/gensim#1223]
hi,everyone！
I have read the doc2vec original paper, but I still do not understand how to generate the document vector for the test set.

**Comment by pranaydeep-af** [comment]
Hi,
Try this I-Python Notebook for a detailed guide on using doc2vec with gensim.[Link](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/doc2vec-IMDB.ipynb)
Also have a look at this detailed explanation. [Link](https://rare-technologies.com/doc2vec-tutorial/)

**Comment by tmylk** [comment]
Please continue on the mailing list
