### ISSUE TITLE
1.0.1 reset_from bug

### ISSUE THREAD

**Issue by knownact** [RaRe-Technologies/gensim#1230]
code should be:

def reset_from(self, other_model):
        """
        Borrow shareable pre-built structures (like vocab) from the other_model. Useful
        if testing multiple models in parallel on the same corpus.
        """
        self.wv.vocab = other_model.wv.vocab
        self.wv.index2word = other_model.wv.index2word

**Comment by Kreiswolke** [comment]
Hi,
I've fixed that bug in my fork 1230. I've tested it in a simple notebook, it works and is ready to pull.

Thanks!

**Comment by tmylk** [comment]
@Kreiswolke Thanks. please submit a pull request and include unit tests
