### ISSUE TITLE
DocvecsArray getitem int64 bug

### ISSUE THREAD

**Issue by knownact** [RaRe-Technologies/gensim#1231]
def __getitem__(self, index):
        """
        Accept a single key (int or string tag) or list of keys as input.

        If a single string or int, return designated tag's vector
        representation, as a 1D numpy array.

        If a list, return designated tags' vector representations as a
        2D numpy array: #tags x #vector_size.
        """
        if isinstance(index, string_types + (int,)):
            return self.doctag_syn0[self._int_index(index)]

        return vstack([self[i] for i in index])

should be 

        if isinstance(index, integer):
            return self.doctag_syn0[self._int_index(index)]

**Comment by gojomo** [comment]
Why? Do you have an example where the chabge works better? Does the change still support indexed-lookup of string doctags?

**Comment by knownact** [comment]
it is because index here may be the numpy.int64 type, and the code here will hurt the indexed-lookup of string doctag, so maybe add a addition compare is ok, like:


from numpy import integer:

    if isinstance(index, string_types + (int,)) or isinstance(index, integer + (int,)) :
        return self.doctag_syn0[self._int_index(index)]

**Comment by gojomo** [comment]
I see. A PR with a test for the new case this enables, & the fix, would be welcome.
