### ISSUE TITLE
Subsampling in fastText wrapper

### ISSUE THREAD

**Issue by akutuzov** [RaRe-Technologies/gensim#1238]
The fastText wrapper currently accepts training hyperparameters as stated by the user and passes them to the fastText binary.  However, there is a problem with `sample` parameter. It specifies the probability of discarding words during training based on their frequency. In the word2vec algorithms it can be safely set to 0 (no subsampling, for example, if one removed stop words from the training corpus beforehand), models still train OK. So, the same wording is copied to the wrapper comments:

> `sample` = threshold for configuring which higher-frequency words are randomly downsampled;
>             default is 1e-3, useful range is (0, 1e-5).

It seems that in fastText something has changed. If one sets the subsampling parameter to 0 (./fasttext skipgram -t 0), the result is that the model essentially remains in the initial random state after the training; the results on gold standard sets are close to random.

I have not found any clues on that in the fastText papers, and I don't know enough C to look it up in the fastText source code. So it would be good if someone checked this finding. If it is true, then we probably need some sort of warning in the Gensim wrapper, which will raise in case `sample` is set to 0.

**Comment by prakhar2b** [comment]
@tmylk  I'll work on this

**Comment by tmylk** [comment]
CC @prakhar2b

**Comment by prakhar2b** [comment]
looking into it asap. Thanks

**Comment by akutuzov** [comment]
Thanks! We definitely need a warning here.

**Comment by menshikh-iv** [comment]
The wrapper will be removed in next release (because we already have our native cythonized implementation), for this reason, I close this issue.
