### ISSUE TITLE
Train a Random Indexing model (RpModel)

### ISSUE THREAD

**Issue by gpassero** [RaRe-Technologies/gensim#1259]
Documentation about the use of RpModel is scarce. Currently, I'm using these docs:
https://radimrehurek.com/gensim/models/rpmodel.html and https://radimrehurek.com/gensim/tutorial.html

I successfully built a LSI model and now I am testing RpModel and LdaModel. However, RpModel seems not to be working. It took some time to generate a TFIDF matrix from portuguese Wikipedia text dumps, but only few seconds to initialize the RpModel. Then, I compare two texts or words using this functions:

```python
    def text2text(self, text1, text2, preprocess=True):
        """Return similarity score between two texts."""
        text1_vector = self.text2vector(text1, preprocess=preprocess)
        text2_vector = self.text2vector(text2, preprocess=preprocess)
        results = cosine(text1_vector, text2_vector)
        return results

    def text2vector(self, text, preprocess=True):
        """Return the vector representation of a text or a list of words."""
        if preprocess:
            tokens = preprocess_text(text, **PREPROCESS_KARGS)
        elif isinstance(text, str):
            tokens = text.split()
        # TODO Some words may not be taken in count (not present in dictionary).
        bow = self.dictionary.doc2bow(tokens)
        bow = self.tfidf[bow]
        return pd.DataFrame(self.model[bow], columns=['dim', 'val'])['val']
```

I compared 'cachorro' (dog) to 'animal' (animal) and similarity is close to 0. The same happens to many other similar and dissimilar words.

Am I doing anything wrong? Is it necessary another step do train the RpModel in Wikipedia texts?

**Comment by gpassero** [comment]
Also, I'd like to reproduce S-Space package RandomIndexing model, which have a parameter "window_size". How can I reproduce window_size=2 in RpModel?

**Comment by tmylk** [comment]
RP model takes a simple BOW(not TF-IDF) as input, please try `self.model[dictionary.doc2bow(['cão'])]`.  Tt is fast to initallize because it is [random](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/rpmodel.py#L67). The context in gensim is the whole document so there is no way to choose the window.

There is more information and useful wrapper around this model in https://pythonhosted.org/shorttext/tutorial_topic.html#topic-models-in-gensim-lda-lsi-and-random-projections

**Comment by gpassero** [comment]
@tmylk I built RpModel just like showed in this notebook https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/Topics_and_Transformations.ipynb (with TFIDF on training matrices), except that I had to built the BOW matrices from Wikipedia.

I tried 300, 500 and 2000 topics, but results are awkward. Here is a comparison of the models I built up to now. Take Word2Vec results as reference (good scores).

|   Word1    |   Word2    | wordnet | word2vec |   lsa   |  lda   | random indexing |
|------------|------------|---------|----------|---------|--------|-----------------|
| computador |  hardware  |  0.1111 |  0.5312  |  0.1491 | 0.9909 |     -0.0100     |
| computador | computação |    0    |  0.3603  | -0.0606 | 0.2859 |     -0.0050     |
| computador |    água    |  0.1429 |  0.0203  |  0.1274 | 0.0010 |     -0.0030     |
| computador |  vegetal   |  0.2000 | -0.0658  |  0.0166 | 0.0011 |      0.0450     |
|  vegetal   |  floresta  |  0.1429 |  0.3866  | -0.0536 | 0.0009 |      0.0140     |
|  vegetal   |   planta   |    1    |  0.5800  | -0.0218 | 0.0225 |      0.0140     |
|  vegetal   |    água    |  0.1250 |  0.2369  |  0.0166 | 0.0155 |     -0.0400     |
|  vegetal   |  plástico  |  0.2000 |  0.1387  |  0.0161 | 0.0000 |      0.0130     |
|  vegetal   |   forno    |  0.1000 |  0.1923  | -0.1010 | 0.0000 |     -0.0050     |
|   forno    |  cozinha   |    1    |  0.4061  | -0.1120 | 0.0072 |     -0.0380     |
|   forno    |   calor    |  0.0714 |  0.2819  | -0.0218 | 0.0034 |     -0.0260     |
|   forno    |   tapete   |  0.1250 |  0.2361  |  0.1559 | 0.0000 |      0.0080     |
|   forno    |  empresa   |  0.0667 |  0.1029  | -0.0142 | 0.0109 |     -0.0280     |

**Comment by tmylk** [comment]
what is the size of the corpus that you trained it on?

**Comment by gpassero** [comment]
Approximately 1 million documents and more than 100 million tokens (stopwords considered). It's the whole Brazillian Wikipedia.

**Comment by tmylk** [comment]
Switched to mailing list https://groups.google.com/d/msg/gensim/1dBA0ez14rA/nAVU_bXcGQAJ
