### ISSUE TITLE
LDA returns only one topic probability

### ISSUE THREAD

**Issue by gpassero** [RaRe-Technologies/gensim#1260]
I trained a LDA model on portuguese Wikipedia texts dump. It worked partially. The problem is that when I use LDA model to transform a TFIDF  bag of words only one topic is returned with probability < 1. Therefore the sum of probabilities of topics is < 1. Did I do anything wrong?

```python

def get_topics(word):
    return lda_model[tfidf_model[dictionary.doc2bow[word]]]

# dog ('cachorro') and cat ('gato') are correctly related. should animal be completely another topic?
get_topics('animal')
[(43, 0.50499999999999989)]
get_topics('gato')
[(77, 0.50499999999999989)]
get_topics('cachorro')
[(77, 0.50499999999999989)]

# shouldn't sport ('esporte'), athlete ('atleta') and soccer ('futebol') share same topic?
get_topics('esporte')
[(54, 0.50499999999999978)]
get_topics('atleta')
[(15, 0.50499999999999978)]
get_topics('futebol')
[(14, 0.50499999603219392)]
```
The only way I could get it to return more than one topic was adding more words. 

Am I doing anything wrong?

**Comment by tmylk** [comment]
Glad you are looking into Brazilian wikipedia!

LDA model takes in a document in bag of words format that is different from TF-IDF. The built-in way to get topics for a term is [`lda_model.get_term_topics('carnaval')`](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/ldamodel.py#L945)

**Comment by gpassero** [comment]
@tmylk unfortunately that didn't work. I got no results when I use get_term_topics. If I set the minimum probability I get this:

```python
m.model.get_term_topics('cachorro', 0)
[(0, 3.9271348297904165e-06), (59, 0.00029506734751964), (77, 0.0025712686882891746)]
m.model.get_term_topics('gato', 0)
[(12, 0.00029402557367460636), (46, 0.0003308770942684363), (68, 0.00019415128803607475), (77, 0.003703965730997977)]
m.model.get_term_topics('animal', 0)
[(12, 0.00039597475944656504), (38, 6.117773995478603e-05), (42, 2.1276272393281373e-05), (43, 0.0036906563752685125), (50, 0.00052273087220773996), (54, 0.0011057641837782211), (65, 0.0002402333023680758), (68, 0.0003081553673880113), (70, 3.2158850671617612e-05), (77, 0.00010682836767217282)]
```

Is it ok to have so low probabilities?  The probabilities returned for 'animal' doesn't totalize 1.

I am rebuilding the model with these parameters:

```python
        model_kargs['chunksize'] = 100000
        model_kargs['update_every'] = 0
        model_kargs['passes'] = 20
```

The parameters I set previously:

```python
        model_kargs['chunksize'] = 10000
```

Currently I am not lematizing or stemming tokens. So the matrices are sparser than normal.

**Comment by tmylk** [comment]
[PyLdavis](https://github.com/bmabey/pyldavis) and the graphs in #1243 are good general ways to assess an LDAModel.

**Comment by tmylk** [comment]
Assume you trained it as in the wiki tutorial and as in this [ipynb](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/Topics_and_Transformations.ipynb)

**Comment by tmylk** [comment]
As this is not a bug report, suggest to continue the discussion in the mailing list https://groups.google.com/forum/#!forum/gensim
