### ISSUE TITLE
faiss integration similar to annoy

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#1265]
Integrate Facebook's L2 and dot product similiarity search for dense vectors in a similar way to Annoy
https://github.com/facebookresearch/faiss/

**Comment by chaitaliSaini** [comment]
I would like to work on this issue.

**Comment by tmylk** [comment]
Great!

**Comment by chaitaliSaini** [comment]
Can you please clarify these two doubts
1. I have to make a new class in index.py file called faissIndexer?
2. I have to use IndexIVFFlat index?

**Comment by tmylk** [comment]
1. Yes. Confirm.
2. Let's start with that one and see how it goes.

**Comment by chaitaliSaini** [comment]
Except save and load functions, i have competed the code. So should i send a PR so that you review and tell if I am on the right track(this is my first contribution to an open source project) .

**Comment by menshikh-iv** [comment]
Close this issue (because faiss license isn't suitable for us)
