### ISSUE TITLE
Monitoring training in word2vec and doc2vec

### ISSUE THREAD

**Issue by amueller** [RaRe-Technologies/gensim#1272]
Is there any way to monitor training and / or estimate convergence or how long it's gonna run?
There seems to be no verbosity, and I'm not sure how you set the maximum number of iterations in the examples.

**Comment by tmylk** [comment]
There is a request for logging some kind of loss in #999 but it's not implemented yet.

**Comment by amueller** [comment]
thanks, closing as duplicate.
