### ISSUE TITLE
Permission denied when loading DtmModel

### ISSUE THREAD

**Issue by geilerloui** [RaRe-Technologies/gensim#1273]
Hi,

I've launched the following code on linux 

`
model = DtmModel(dtm_path,
                 corpus,
                 time_seq,
                 num_topics=2,
                 id2word=corpus.dictionary,
                 initialize_lda=False
                )
`

It loads until

> INFO:gensim.models.wrappers.dtmmodel:serializing temporary corpus to /tmp/f50515_train-mult.dat
INFO:gensim.corpora.bleicorpus:no word id mapping provided; initializing from corpus
INFO:gensim.corpora.bleicorpus:storing corpus in Blei's LDA-C format into /tmp/f50515_train-mult.dat
INFO:gensim.corpora.bleicorpus:saving vocabulary of 546 words to /tmp/f50515_train-mult.dat.vocab
INFO:gensim.models.wrappers.dtmmodel:training DTM with args --ntopics=2 --model=dtm  --mode=fit --initialize_lda=false --corpus_prefix=/tmp/f50515_train --outname=/tmp/f50515_train_out --alpha=0.01 --lda_max_em_iter=10 --lda_sequence_min_iter=6  --lda_sequence_max_iter=20 --top_chain_var=0.005 --rng_seed=0 
INFO:gensim.models.wrappers.dtmmodel:Running command ['/home/app_ab_bigdata/lgeiler/NPS/bin/dtm-linux64', '--ntopics=2', '--model=dtm', '--mode=fit', '--initialize_lda=false', '--corpus_prefix=/tmp/f50515_train', '--outname=/tmp/f50515_train_out', '--alpha=0.01', '--lda_max_em_iter=10', '--lda_sequence_min_iter=6', '--lda_sequence_max_iter=20', '--top_chain_var=0.005', '--rng_seed=0']

And then long story short, I have the following error "[Errno 13] Permission denied", I don't really know where does it come from.

> /product/anaconda/envs/py35dev/lib/python3.5/site-packages/gensim/utils.py in check_output(stdout, *popenargs, **kwargs)
   1155     """
   1156     try:
-> 1157         process = subprocess.Popen(stdout=stdout, *popenargs, **kwargs)
   1158         output, unused_err = process.communicate()
   1159         retcode = process.poll()

 /product/anaconda/envs/py35dev/lib/python3.5/subprocess.py in __init__(self, args, bufsize, executable, 
 stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, 
 restore_signals, start_new_session, pass_fds)
     945                                 c2pread, c2pwrite,
     946                                 errread, errwrite,
 --> 947                                 restore_signals, start_new_session)
     948         except:
     949             # Cleanup if the child failed starting.

 /product/anaconda/envs/py35dev/lib/python3.5/subprocess.py in _execute_child(self, args, executable, 
 preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, 
 c2pwrite, errread, errwrite, restore_signals, start_new_session)
    1549                             else:
    1550                                 err_msg += ': ' + repr(orig_executable)
 -> 1551                     raise child_exception_type(errno_num, err_msg)
    1552                 raise child_exception_type(err_msg)
    1553 

PermissionError: [Errno 13] Permission denied

Thanks for your help

**Comment by tmylk** [comment]
@geilerloui Do you have the same error when running the command from the command line?
`'/home/app_ab_bigdata/lgeiler/NPS/bin/dtm-linux64', '--ntopics=2', '--model=dtm', '--mode=fit', '--initialize_lda=false', '--corpus_prefix=/tmp/f50515_train', '--outname=/tmp/f50515_train_out', '--alpha=0.01', '--lda_max_em_iter=10', '--lda_sequence_min_iter=6', '--lda_sequence_max_iter=20', '--top_chain_var=0.005', '--rng_seed=0']`

**Comment by geilerloui** [comment]
Yes it is the same erorr, actually I've solved it with a chmod but now I have a dependency problem, I can not find "libflags.so.0"  on the internet, I tried to install another version like .2.1 but it doesn't work out.

**Comment by tmylk** [comment]
Hi,
Have you tried using DTM [binaries](https://github.com/magsilva/dtm/tree/master/bin)?
Also there is a [pure python DTM](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/ldaseqmodel.ipynb) in gensim.

**Comment by santoshbs** [comment]
> Yes it is the same erorr, actually I've solved it with a chmod but now I have a dependency problem, I can not find "libflags.so.0" on the internet, I tried to install another version like .2.1 but it doesn't work out.

Chmod worked for me.
