### ISSUE TITLE
wordrank_comparisions typeerror

### ISSUE THREAD

**Issue by luoyangen** [RaRe-Technologies/gensim#1276]
hi,
    I'm trying to run the [wordrank_comparisions](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/Wordrank_comparisons.ipynb), but while training the wordrank model, got the error: TypeError: train() takes at least 4 arguments (7 given).
    I can't figure out whether the code error or my python environment, but other wordrank models is successes trained. waiting for help. thx.

**Comment by tmylk** [comment]
Hi, could you please past the exact line and the full error message?

**Comment by luoyangen** [comment]
@tmylk the line is 
`get_ipython().magic(u'time wr_model = Wordrank.train(WR_HOME, corpus_file,  **wr_params); wr_model')`

the error log is:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-680aa3ec029d> in <module>()
     75         print('\nUsing existing model file {:s}.vec'.format(output_file))
     76 
---> 77 train_models(corpus_file='proc_brown_corp.txt', output_name='brown')

<ipython-input-2-680aa3ec029d> in train_models(corpus_file, output_name)
     59     if not os.path.isfile(os.path.join(MODELS_DIR, '{:s}.vec'.format(output_file))):
     60         print('\nTraining wordrank on {:s} corpus..'.format(corpus_file))
---> 61         get_ipython().magic(u'time wr_model = Wordrank.train(WR_HOME, corpus_file,  **wr_params); wr_model')
     62         locals()['wr_model'].wv.save_word2vec_format(os.path.join(MODELS_DIR, '{:s}.vec'.format(output_file)))
     63         print('\nSaved wordrank model as {:s}.vec'.format(output_file))

/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2156         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2157         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2158         return self.run_line_magic(magic_name, magic_arg_s)
   2159 
   2160     #-------------------------------------------------------------------------

/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2077                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2078             with self.builtin_trap:
-> 2079                 result = fn(*args,**kwargs)
   2080             return result
   2081 

<decorator-gen-59> in time(self, line, cell, local_ns)

/usr/local/lib/python2.7/dist-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/usr/local/lib/python2.7/dist-packages/IPython/core/magics/execution.pyc in time(self, line, cell, local_ns)
   1178         else:
   1179             st = clock2()
-> 1180             exec(code, glob, local_ns)
   1181             end = clock2()
   1182             out = None

<timed exec> in <module>()

TypeError: train() takes at least 4 arguments (7 given)

**Comment by tmylk** [comment]
Thanks for spotting this. Agree that a positional argument is missing
`Wordrank.train(WR_HOME, corpus_file, 'output_dir', **wr_params)`

CC @parulsethi
