### ISSUE TITLE
how do i keep the sentence and paragraph information while processing wiki corpora?

### ISSUE THREAD

**Issue by yunhenk** [RaRe-Technologies/gensim#1282]
I want to train the word2vector model with wiki data.So I'd like to keep the sentence and paragraph splitting information when processing the wiki corpora. How should i modify the code to do so? Thanks very much!

**Comment by tmylk** [comment]
Please see relevant code [here](https://groups.google.com/forum/#!topic/gensim/fVIgE6orinI)

Let's continue this discussion on the mailing list where this question is a better fit:
https://groups.google.com/forum/#!forum/gensim
