### ISSUE TITLE
Create a single notebook for all Tensorboard visualisations

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#1288]
Tensorboard visualisations are now supported for word2vec and [doc2vec](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/Tensorboard_doc2vec.ipynb) by @parulsethi 

It would be good to combine them all in a sinlge notebook.

Adding a way to visualise LDA, LSI and sklearn NMF vectors would be good too.

**Comment by tmylk** [comment]
CC @parulsethi Please comment if you are interested in working on this issue

**Comment by parulsethi** [comment]
Sure, I'll take this up

**Comment by menshikh-iv** [comment]
Fixed in #1396

**Comment by hucklebarryreese** [comment]
Hi @parulsethi are there any status updates on the notebook?
