### ISSUE TITLE
Integrate Conceptnet in Gensim

### ISSUE THREAD

**Issue by souravsingh** [RaRe-Technologies/gensim#1296]
I have found a package for creating a semantic network of common sense knowledge- https://github.com/commonsense/conceptnet5

The word embeddings for the project are available here- https://github.com/commonsense/conceptnet-numberbatch

For a demo on Conceptnet, See here- http://conceptnet.io/

Integrating Conceptnet in Gensim would be really nice feature to have.

**Comment by markroxor** [comment]
@menshikh-iv would this be a good one to take over?

**Comment by menshikh-iv** [comment]
@markroxor yes, why not :+1:

**Comment by menshikh-iv** [comment]
So, I went through concepnet and discuss with @piskvorky, this project is really self-sufficient and integration makes no sense, for this reason, I close this issue.

**Comment by piskvorky** [comment]
Actually, I think integration would be nice, in the sense that we could support operations on ConceptNet models loaded into Gensim (what are these operations? what's the context, use-cases for this proposed feature?).

We certainly don't have to re-implement training or do anything fancy. Just use a sane interface, for using this (presumably practical) tool.

**Comment by menshikh-iv** [comment]
@piskvorky I think we probably can convert models to word2vec format and use it through KeyedVectors class. We'll add it to gensim-data soon.

**Comment by piskvorky** [comment]
So the only difference is in how the models are trained? The functionality and applicability of a trained model is identical to word2vec?

**Comment by menshikh-iv** [comment]
@piskvorky probably yes (maybe with small addition) we'll discuss it later with @markroxor and I'll let you know

**Comment by adrianog** [comment]
Hi

Is this still being considered?
Thanks

**Comment by menshikh-iv** [comment]
@adrianog this was already added as the ready2use pre-trained model, see https://github.com/RaRe-Technologies/gensim-data/releases/tag/conceptnet-numberbatch-17-06-300

**Comment by adrianog** [comment]
Just _superb_.
"The functionality and applicability of a trained model is identical to word2vec (like it was with gloVe)?"-> the answer to this was a "yes"? Any caveats?

**Comment by menshikh-iv** [comment]
@adrianog only thing about term construction (see `"/c/en/beer"` from an example from my link), see also original repo https://github.com/commonsense/conceptnet-numberbatch for more information about it.

**Comment by rlleshi** [comment]
Could you also include an English only version _model = api.load("conceptnet-numberbatch-en-17-06-300")_ into the loading module?

**Comment by nickresearch** [comment]
> Could you also include an English only version (_model = api.load("conceptnet-numberbatch-en-17-06-300")_) into the loading module?

I would like to second this suggestion--that would be fantastic. Thanks.

**Comment by kevinmneal** [comment]
ConceptNet has since come out with a new version (19.08), available in multilingual and English-only. Would it be possible to add this?
