### ISSUE TITLE
Tutorial page overhaul

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#1298]
The tutorials page at the gensim page http://radimrehurek.com/gensim/tutorial.html
should be re-structured to resemble https://github.com/RaRe-Technologies/gensim/blob/develop/tutorials.md

The tutorials in the MD file should also be structured better according to features.

**Comment by mpenkov** [comment]
@piskvorky Closing this in favor of the ongoing numfocus work.
