### ISSUE TITLE
Documentation error in Doc2Vec

### ISSUE THREAD

**Issue by jlorince** [RaRe-Technologies/gensim#1302]
This is super simple, but the documentation says the default value of the `sample` parameter in Doc2Vec is 0:

> sample = threshold for configuring which higher-frequency words are randomly downsampled;
default is 0 (off), useful value is 1e-5.

But the actual default value is 1e-3 (0.001), based on the fact that the DocVec inherits from WordVec, where sample is set to 1e-3. See: https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/word2vec.py#L367

I can confirm this by simply initiating a model with all defaults:

```
>>> from gensim.models import Doc2Vec
>>> model = Doc2Vec()
>>> print(model.sample)
0.001
```

Not sure if the desire behavior is what's reflected in the documentation, in which case the default should be changed, or if the documentation should be updated. Simple fix either way, I imagine, but as is it causes some confusion.

**Comment by gojomo** [comment]
The comment should accurately reflect the current inherited default.
