### ISSUE TITLE
Unexpected keyword argument 'doctag_vec' in Tensorboard_doc2vec tutorial

### ISSUE THREAD

**Issue by Deepak-** [RaRe-Technologies/gensim#1312]
I  am trying to follow the [Tensorboard_doc2vec](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/Tensorboard_doc2vec.ipynb)  tutorial, however when I am trying to save the document embeddings:

`model.save_word2vec_format('doc_tensor.w2v', doctag_vec=True, word_vec=False)`

I get the following error:

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-6-2c72f9e8f214> in <module>()
    ----> 1 model.save_word2vec_format('doc_tensor.w2v', doctag_vec=True, word_vec=False)

    TypeError: save_word2vec_format() got an unexpected keyword argument 'doctag_vec'TypeError: 
    save_word2vec_format() got an unexpected keyword argument 'doctag_vec'

Any ideas what could be wrong?

Gensim==2.0.0
Python 2.7.13 (also happens in Python 3.5.2)
Windows 7

**Comment by Deepak-** [comment]
@parulsethi Okay thank you, I  will try that!

**Comment by menshikh-iv** [comment]
@Deepak- If you would use this now, you can clone `develop` branch from gensim repo.
Another way is wait 1 week, release soon.

**Comment by tmylk** [comment]
Released in 2.1.0
