### ISSUE TITLE
How to compiler word2vec_inner.c into word2vec_inner.pyd?

### ISSUE THREAD

**Issue by jm-huang** [RaRe-Technologies/gensim#1315]
I make some modify on word2vec_inner.c(gensim/models/word2vec_inner.c) but I have no idea of how to compiler it into word2vec_inner.pyd. Can anyone tell me that how to compiler it into word2vec_inner.pyd?(Platform: windows10, 64bit)

I have tried:
gcc word2vec_inner.c -o word2vec_inner.pyd -IC:/Python/include -LC:/Python/libs -lpython27
and get the errors below:
C:\Users\Jimmy\AppData\Local\Temp\ccFDWLcM.o:word2vec_inner.c:(.text+0x11e2d): undefined reference to `__imp_Py_InitModule4'
c:/program files/anaconda2/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.7.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): In function `main':
c:\bb\vista64-mingw32\mingw-x86-x86_64\build\build\mingw\obj/../../../build/mingw/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status

Thank you very much.

**Comment by menshikh-iv** [comment]
`word2vec_inner.c` is autogenerated file from cython, don't change `word2vec_inner.c` manually (you should change `word2vec_inner.pyx` and generate .c file from it with `cython word2vec_inner.pyx`)

**Comment by tmylk** [comment]
Modifying the C code is not supported. Cython code should be modified instead.
Closing as not an issue.
