### ISSUE TITLE
Feature Request: Learning symmetric LDA priors from data

### ISSUE THREAD

**Issue by groceryheist** [RaRe-Technologies/gensim#1316]
It is great that gensim makes it easy to learn asymmetric alpha and eta priors from data.  However, http://dirichlet.net/pdf/wallach09rethinking.pdf recommend using an asymmetric prior for alpha and a symmetric prior for eta to obtain the best quality topics. Gensim does not support learning symmetric priors. It would be a great and useful feature to have.

**Comment by menshikh-iv** [comment]
It's a good idea, thank you @groceryheist, I add this to wishlist

**Comment by menshikh-iv** [comment]
LdaModel from gensim support symmetric/asymmetric alpha and symmetric eta
You can see it [in docstring](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/ldamodel.py#L212)

**Comment by menshikh-iv** [comment]
Small example

```python
from gensim.models import LdaModel
from gensim.corpora import Dictionary
import numpy as np

docs = [["a", "a", "b"], 
        ["a", "c", "g"]]
dct = Dictionary(docs)
corpus = [dct.doc2bow(_) for _ in docs]

lda_sym = LdaModel(corpus, num_topics=3, alpha="symmetric")
lda_asym = LdaModel(corpus, num_topics=3, alpha="asymmetric")

print(lda_sym.alpha)  # [ 0.33333333  0.33333333  0.33333333]
print(lda_asym.alpha)  # [ 0.47662711  0.30216948  0.22120341]
```

**Comment by groceryheist** [comment]
Thanks.
