### ISSUE TITLE
Online NMF

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#132]
Implement online non-negative matrix factorization from http://www.cs.cornell.edu/~chenhao/pub/online-NMF.pdf

**Comment by souravsingh** [comment]
@piskvorky I would like to work on the issue

**Comment by tmylk** [comment]
Hi @souravsingh the best way to proceed is to apply to the RaRe incubator programme https://rare-technologies.com/incubator

**Comment by vene** [comment]
Hi,

Couple of notes:

1. the NMF implementation in scikit-learn has been replaced by a more scalable coordinate descent-based one a couple of releases ago (but it's not online/out-of-core)

2. you might be interested in [libmf](http://www.csie.ntu.edu.tw/~cjlin/libmf/) [(paper)](http://www.csie.ntu.edu.tw/~cjlin/papers/libmf/libmf_journal.pdf) which supports online parallel NMF among others.

**Comment by prakhar2b** [comment]
Hello,

I'm an undergraduate student at IIT Roorkee. I'd like to start working on this project if possible, as I've seen a few projects already being worked on in students-projects section. Kindly let me know about it and also the current status of this project.

Thanks

**Comment by manojpandey** [comment]
Took this up, working with @menshikh-iv 😄
