### ISSUE TITLE
wiki examples: sample code to get from tfidf doc to wikipedia title/uri and vice versa

### ISSUE THREAD

**Issue by joernhees** [RaRe-Technologies/gensim#1322]
I very much like the LSI and LDA [wiki examples](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/src/wiki.rst), but one aspect that i think is missing is: how to get from tf-idf doc vectors (or later LSI / LDA vecs) back to Wikipedia URIs (or titles if easier) and vice versa?

Am i missing something obvious, or do i have to run another pass over the wiki dump, as the titles aren't saved anywhere?

I'll happily make a PR to extend the examples with this...

**Comment by poornagurram** [comment]
@joernhees can you please explain your issue clearly.

**Comment by joernhees** [comment]
i think it's already about as clear as i can...

- how to get from Wikipedia URI to vector?
- how to get from vector to Wikipedia URI?

after following the tutorial, i wasn't able to easily find a link between "topic #0" and its wikipedia article

**Comment by menshikh-iv** [comment]
@joernhees As I remember, Wikipedia doesn't store URI in dumb (but you can re-store it using "Title").

About your questions: you should pass your page bag-of-words to any model (TfIdf, Lsi, Lda, etc), for this you should use `__getitem__` method, for example `model[my_bow]`

From vector, you can't retrieve original article (but you can store mapping `article <-> vector`)

**Comment by piskvorky** [comment]
@joernhees the tutorial doesn't construct any url<->vector mapping by default.

IIRC there was some discussion around adding this, since it's such a useful and commonly requested feature. In fact, it may have been added in one of the recent notebooks -- @menshikh-iv ?

**Comment by piskvorky** [comment]
Found it: https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/corpora/wikicorpus.py#L278

@menshikh-iv @joernhees can you open an issue that will set `metadata=True` in the `make_wiki` script? The vectors without titles are kinda useless, so `True` is a better default.

**Comment by menshikh-iv** [comment]
Hello @AlokDebnath, feel free to contribute! The task is as https://github.com/RaRe-Technologies/gensim/issues/1322#issuecomment-322459901 suggested + some kind of mapping with vectors (as optional thing)

**Comment by Naba7** [comment]
can I take up this issue ?

**Comment by menshikh-iv** [comment]
@Naba7 of course, feel free to contribute!
