### ISSUE TITLE
Not being able to get a FAST VERSION of Gensim

### ISSUE THREAD

**Issue by Chanchal-Hasan** [RaRe-Technologies/gensim#1329]
#### Description

I have installed the C compiler, set path variable, installed cython, and then upgrade the gensim. But still I am not geting the FAST VERSION of gensim. Can you guys help me to find what I am missing here.

#### Steps/Code/Corpus to Reproduce
>>from gensim.models.word2vec import FAST_VERSION
>> FAST_VERSION

#### Expected Results

1

#### Actual Results
-1

#### Versions
Cython version 0.25.2
Python version 2.7.13
gensim version 2.0.0
scipy version 0.18.1

**Comment by prakhar2b** [comment]
@Chanchal-Hasan please check that there is a `word2vec_inner.so` file generated after installation. There must be a compilation error.

**Comment by gojomo** [comment]
What operating system are you using? How are you installing gensim, and are you installing into a virtual environment? Are there any errors shown when you install gensim? 

(When using `pip install gensim`, with the required system development tools available, you usually won't even need cython to be installed. Similarly, if using a conda-based environment, `conda install gensim` won't need cython, either.)

**Comment by tmylk** [comment]
we have wheels for windows and osx that come with pre-compiled C, so there FAST_VERSION should be 1

**Comment by Chanchal-Hasan** [comment]
@prakhar2b I have not found any such .so file. I could see the .pxd, .pyx., and .c extensions of word2vec_inner

**Comment by Chanchal-Hasan** [comment]
Hi @gojomo I am in Windows7, and not installing into any virtual env. I have downloaded and unzipped the tar.gz source for gensim and installed through "python setup.py install", and no errors shown. Actually gensim is working fine, except that parallelizing word2vec is not happening.

@tmylk  I have not found any such wheels. Can you help me where can I get that.

**Comment by gojomo** [comment]
On Windows, using the 'conda' packager and alternate Python distribution from Continuum Analytics is often a good choice, as they handle many Windows-specific compilations/optimizations well. It's a free product from a commercial entity. (Also both preferring installations from 'pip'/PyPI, and using project-specific vertual environments, are good habits to get into unless you have strong reasons for preferring other approaches.)

I tend to use the '[miniconda](https://conda.io/miniconda.html)' variant to only install the minimum number of packages I need.) Separately, Windows7 is a bit on the old side – still getting security updates but a couple years' past Microsoft offering any free 'mainstream' support – so some things may work better in a later version. 

(And, if ever configuring a machine specifically for this kind of work, the underlying stack – from Python itself through libraries to gensim – is all much more extensively developed/tested/used on Linux machines, so usually set-up and troubleshooting will be easiest if you can choose that OS.)

**Comment by tmylk** [comment]
@Chanchal-Hasan please try installing with `pip install gensim` that will download the pre-compiled wheels from PyPi.

**Comment by Chanchal-Hasan** [comment]
Hi @gojomo , thank you for your follow up on this. However, the problem is, due to the firewall protection, I cannot use Conda on this occasion.

**Comment by Chanchal-Hasan** [comment]
Hi @tmylk  I have done that but only with following results. Can yo help me what it means.

![image](https://cloud.githubusercontent.com/assets/28740547/26166637/1d6795ba-3b02-11e7-946c-dfe302627019.png)

**Comment by menshikh-iv** [comment]
@Chanchal-Hasan firewall isn't related with gensim.
About `FAST_VERSION`: try to re-install gensim from pip `pip uninstall gensim; pip install gensim`, or alternative variant - use conda forge package
```
conda config --add channels conda-forge
conda install gensim
```
