### ISSUE TITLE
keyedVectors import unresolved

### ISSUE THREAD

**Issue by TamouzeAssi** [RaRe-Technologies/gensim#1335]
Hello,

I installed gensim  in Anaconda using the command:

conda install gensim

with conda list command we can see that gensim 1.0.1 is installed.
So, Im using eclipse (Pydev) as an editor.

In the code, i can import gensim normaly. But when i write:

from gensim.KeyedVectors import keyedVectors

I get the following exception:
Traceback (most recent call last):
  File "C:\Users\user\workspace\Test\TestKeyed.py", line 2, in <module>
    from gensim.KeyedVectors import keyedVectors
ModuleNotFoundError: No module named 'gensim.KeyedVectors'

Note that the python 3.6.0 is installed by default by anaconda
Any suggestion will be appreciated

#### Description
TODO: change commented example

**Comment by chinmayapancholi13** [comment]
Hey @TamouzeAssi. You'd have to write : `from gensim.models.keyedvectors import KeyedVectors`

**Comment by TamouzeAssi** [comment]
Hello @chinmayapancholi13
Thank you. using the line of code that you provide i can call correctly keyedvectors.

My mistake was that i used the same line in:
https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/keyedvectors.py

for calling keyedvectors.
Thank you again

**Comment by chinmayapancholi13** [comment]
@TamouzeAssi Ah. Thanks a lot for pointing that out. :) I'll go ahead and fix this right away so that this doesn't cause any further confusion.

**Comment by Prisicilla** [comment]
Hi, I have the question "ModuleNotFoundError: No module named 'gensim.models.keyedvectors'" after use"from gensim.models.keyedvectors import KeyedVectors" in python 3.7

from gensim.models import KeyedVectors/from gensim import KeyedVectors  doesn't work also.

Do you have any suggestion for this? THX

**Comment by piskvorky** [comment]
@Prisicilla please open a new ticket (incl. your versions etc, following the issue template).
