### ISSUE TITLE
loading ensemble embeddings take wordrank .word and context file where these files are located i did'nt get this. Is this embeddings are generated by demo script given in wordrank or by your train function given in wordrank wrapper

### ISSUE THREAD

**Issue by gauravsaxenaiiit** [RaRe-Technologies/gensim#1357]
#### Description
TODO: change commented example

**Comment by tmylk** [comment]
CC @parulsethi Let's add more comments in the docstring

**Comment by parulsethi** [comment]
@gauravsaxenaiiit You can set `cleanup_files=False` to keep the .word and .context files generated by wordrank, and then they can be located in wordrank directory. And embeddings are generted by gensim wrapper's train() not demo script. 

@tmylk Sure

**Comment by menshikh-iv** [comment]
Implemented in #1066
