### ISSUE TITLE
the doc of gensim.matutils.kullback_leibler is wrong

### ISSUE THREAD

**Issue by viciousstar** [RaRe-Technologies/gensim#1358]
> gensim.matutils.kullback_leibler(vec1, vec2, num_features=None)
> A distance metric between two probability distributions. Returns a distance value in range **<0,1>** where values closer to 0 mean less distance (and a higher similarity) Uses the scipy.stats.entropy method to identify kullback_leibler convergence value. If the distribution draws from a certain number of docs, that value must be passed.

it should be
Returns a distance value in range **<0,+∞>**

**Comment by souravsingh** [comment]
@viciousstar Can you make a PR regarding the change?

**Comment by viciousstar** [comment]
@ @

**Comment by viciousstar** [comment]
@souravsingh Sorry I do not know how to fix doc, can you make it?

**Comment by menshikh-iv** [comment]
@viciousstar You can change docstring [here](https://github.com/RaRe-Technologies/gensim/blob/df1663fb4dc200d054110aa6f59782e8fa40d966/gensim/matutils.py#L449) and create PR with this change

**Comment by viciousstar** [comment]
OK, I had create a PR #1373.

**Comment by menshikh-iv** [comment]
Fixed in #1373
