### ISSUE TITLE
Better support for training word2vec models on a corpus consisting of multiple files

### ISSUE THREAD

**Issue by michaelwsherman** [RaRe-Technologies/gensim#1364]
models.word2vec.LineSentence offers a simple generator that takes either a file object or a path to a single object and reads each line as a sentence where the tokens are separated by whitespaces. This assumes that the corpus to be trained on is all in a single file, which may not be the case. And adding additional files to a word2vec model after its been trained is very complex, requiring multiple calls and manual management of learning rates.

Rather than force the user to write their own generator, to concatenate their files, or to manually manage learning rates across multiple files, it is desirable if word2vec could take a directory reference or a list of files directly, through LineSentence or a similar generator.

I have code for a generator that takes all files in a directory and makes a generator suitable for training a word2vec model (or any other model compatible with LineSentence). If desired, I can create a pull request with this generator. I can also (attempt to) change LineSentence to detect if it has been passed a file-like object, a file path, or a directory path (and also possibly a list of files) and then generate lists of tokens appropriately, and then submit the pull request.

Please let me know if this is desired. Thank you.

**Comment by menshikh-iv** [comment]
Hi @michaelwsherman, I think this will be useful. Please, submit your PR

**Comment by michaelwsherman** [comment]
Ok, give me a week or two, I've never submitted anything to open source before and I want to make sure I don't create extra work for others by messing something up. But it will come.

Right now its a separate method that just assumes all files in a directory are text files. Should I add some improvements (gzip support? merging it into the LineSentence method and adding input detection?) or just start with what I have?

**Comment by menshikh-iv** [comment]
It's better to start with what you already have, we discuss about another features after your PR

**Comment by gojomo** [comment]
When the work is in a single git branch, you can create the PR, get feedback, and continue to update the branch/PR with improvements – so always OK to start with something rough. (You won't mess anything up unless/until it's reviewed and accepted, and you can mark it as 'in progress'/'for review' to indicate it's not yet ready.)

You should use the `smart_open` package for file-opening - it will automatically detect gzip name-extensions and do the right thing. 

But it's ok to start with whatever you've got, and see what suggestions for extension/refactoring/etc come up once that's concretely viewable via github!

**Comment by michaelwsherman** [comment]
Pull request at https://github.com/RaRe-Technologies/gensim/pull/1423 . Would love to hear any feedback--first time OSS contributor.

**Comment by menshikh-iv** [comment]
Resolved in #1423
