### ISSUE TITLE
"Is this really the text format?"

### ISSUE THREAD

**Issue by deliciousowl** [RaRe-Technologies/gensim#1372]
model.wv.save_word2vec_format('occult1.bin', binary=True)
model = KeyedVectors.load_word2vec_format("occult1.bin",binary=True)

Why would this not work? Gensim is honestly the least intuitive library i've ever used

**Comment by parulsethi** [comment]
@deliciousowl Please paste the error log you get.

**Comment by menshikh-iv** [comment]
@deliciousowl Also please write your python version and gensim version

**Comment by tmylk** [comment]
Closing as this issue is not reproduced in the relevant tests 
https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/test/test_word2vec.py#L232

Please provide code snippets to re-open.
