### ISSUE TITLE
Error with model.infer_vector

### ISSUE THREAD

**Issue by murhafh** [RaRe-Technologies/gensim#1375]
#### Description
I trained a doc2vec model and I was using it on my local machine with no issues, then when moving the model and trying to find similarities on a VM I got the following error. Even though I'm using the same version of gensim and Python 2.7

```
    inferred_docvec = self.model.infer_vector([doc_text])
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/doc2vec.py", line 748, in infer_vector
    doctag_vectors=doctag_vectors, doctag_locks=doctag_locks)
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/doc2vec.py", line 230, in train_document_dm_concat
    learn_hidden=learn_hidden, learn_vectors=False)
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/word2vec.py", line 322, in train_cbow_pair
    gb = (model.neg_labels - fb) * alpha  # vector of error gradients multiplied by the learning rate
AttributeError: 'Doc2Vec' object has no attribute 'neg_labels'
```

#### Steps/Code/Corpus to Reproduce
Running this code:
```
model = Doc2Vec.load('mymodel')
doc_text = "test"
inferred_docvec = self.model.infer_vector([doc_text])
sims = self.model.docvecs.most_similar([inferred_docvec],topn = self.topn)
```

#### Expected Results
get the similarities

#### Actual Results
The error above

#### Versions

Please run the following snippet and paste the output below.
>>> import platform; print(platform.platform())
Linux-3.16.0-4-amd64-x86_64-with-debian-8.7
>>> import sys; print("Python", sys.version)
('Python', '2.7.9 (default, Jun 29 2016, 13:08:31) \n[GCC 4.9.2]')
>>> import numpy; print("NumPy", numpy.__version__)
('NumPy', '1.12.1')
>>> import scipy; print("SciPy", scipy.__version__)
('SciPy', '0.19.0')
>>> import gensim; print("gensim", gensim.__version__)
No handlers could be found for logger "gensim.models.doc2vec"
('gensim', '1.0.1')
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
('FAST_VERSION', -1)

**Comment by tmylk** [comment]
what is the gensim version on your local machine where the model was saved?

**Comment by murhafh** [comment]
The version is 1.0.1 on my machine and the server I used to train the model, however on the server I used to train the model I used Python 3, although this was not an issue on my local machine when tried to load the model with Python 2.7. Could this be the reason for this error?

**Comment by murhafh** [comment]
Actually same result with Python3

**Comment by murhafh** [comment]
Another strange thing is that if I change the text to more than one word string it works 

```doc_text = "test test"```

No errors.

**Comment by gojomo** [comment]
`neg_labels` is only used by the pure-Python code path – so the machine where you're getting this error doesn't have the optimized-cython versions of gensim word2vec/doc2vec training available. You'll want to be sure that the machine has system tools for compilation and for python-extensions – often these are system packages named 'build-essentials' and 'python-dev' – and then re-install gensim, paying close attention to the output during installation for any errors. 

Separately, you example code for calling `infer_vector()` may be a little off - it needs a list of tokens, not a string. So you topmost example manages to call it with `['text', ]`, which will be seen as a one-token text. But if you call it with just `'test test'`, that would be seen as the text ['t', 'e'. 's', 't', ' ', 't', 'e', 's', 't', ]`. (And if none of those one-character tokens are in the vocabulary, the call would be a no-op, which might explain the lack of an error.)

**Comment by murhafh** [comment]
Thank you, it seems like it was due to multiple attempts to install gensim so it lead to some mismatch, I did fresh new OS install and it worked with no issues on the VM
