### ISSUE TITLE
"TypeError: __init__() takes exactly 1 argument (4 given)" error when calling Wordrank 

### ISSUE THREAD

**Issue by shashankg7** [RaRe-Technologies/gensim#1384]
Hi,

I am trying to run wordrank method on a sample corpus (text8) as described on the documentation page. 

>> model = gensim.models.wrappers.Wordrank('./wordrank', corpus_file='text8', out_path='wr_model')

I am getting the following error when I run this command:

TypeError: __init__() takes exactly 1 argument (4 given)

**Comment by gojomo** [comment]
It looks like the example in the class doc-comment is wrong. From a quick glance through the source (https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/wrappers/wordrank.py), it appears the class method `train()` has the parameters matching that example. So please try replacing `Wordrank(` with `Wordrank.train(`. (We'll still need to fix the docs.)

**Comment by shashankg7** [comment]
Thanks for your reply. You are right. Using Wordrank.train seems to be working. 
Although, for users which don't have Intel libraries installed, slight tweaking needs to be done. 

1. Changing compiler from 'ipcc' to 'gcc' in the install.sh script.
2. In wordrank.cpp, removing the code block containing the error message - ""MPI multiple thread not provided!!! (" (I was getting this error when I was trying to run wordrank's executable).

**Comment by parulsethi** [comment]
Thanks for catching incorrect doc example. fixed in https://github.com/RaRe-Technologies/gensim/pull/1378

**Comment by shashankg7** [comment]
Thanks. I have one more doubt. 

Training wordrank model is taking unusually very large time, even for a relatively smaller corpus (brown corpus). Any idea why?

It is utilizing all cores of my machine, still training time is very large. (

**Comment by menshikh-iv** [comment]
Unfortunately, WordRank fits very slowly, you can try other models if you are not comfortable with the learning time @shashankg7.
