### ISSUE TITLE
sed command in Wiki is Darwin specific. Fails on Linux.

### ISSUE THREAD

**Issue by quole** [RaRe-Technologies/gensim#1391]
On the [developer wiki page](https://github.com/RaRe-Technologies/gensim/wiki/Developer-page), there's instructions to "re-generate Cython files" which includes the following `sed` commands, which probably run fine on OSX / Darwin:

```
    sed -i '' -e's/[[:space:]]*$//' gensim/models/word2vec_inner.c
    sed -i '' -e's/[[:space:]]*$//' gensim/models/doc2vec_inner.c
```

However, on Linux with GNU `sed`, each of these commands gives an error:

`sed: can't read : No such file or directory`

But they run successfully if the `''` is removed:

```
    sed -i -e's/[[:space:]]*$//' gensim/models/word2vec_inner.c
    sed -i -e's/[[:space:]]*$//' gensim/models/doc2vec_inner.c
```

I don't have a solution. I'm just bringing it up. There's a [stackoverflow question](https://stackoverflow.com/questions/2320564/variations-of-sed-between-osx-and-gnu-linux) that goes into the details of the variations between the two versions of `sed`, and various workarounds. I'd edit the wiki to include the choices but it'd start to become a mess of separate OSX and Linux commands. Perhaps the `sed` command could be either moved to a separate shell script which detects if Darwin is being used (as explained on the stackoverflow), or someone could find another way without `sed`, or perhaps there's a way to use `sed` that works the same on both platforms.

**Comment by menshikh-iv** [comment]
Thank you @quole, I think the best choice is
> use  sed that works the same on both platforms

**Comment by menshikh-iv** [comment]
Fixed for [developer page](https://github.com/RaRe-Technologies/gensim/wiki/Developer-page)
