### ISSUE TITLE
Fix CI configs (Travis, Appveyor)

### ISSUE THREAD

**Issue by menshikh-iv** [RaRe-Technologies/gensim#1393]
Need to remove manually `test_req` installation (like [this](https://github.com/RaRe-Technologies/gensim/blob/develop/.travis.yml#L17) and [this](https://github.com/RaRe-Technologies/gensim/blob/develop/appveyor.yml#L69)), because all test dependensies will be installed when we run `python setup.py test`

**Comment by souravsingh** [comment]
@menshikh-iv I think the issue can be closed.

**Comment by menshikh-iv** [comment]
@souravsingh  No, previous PR only for Travis.

**Comment by menshikh-iv** [comment]
Resolved in #1522 #1565
