### ISSUE TITLE
Doc2Vec Searching for both similar words and labels

### ISSUE THREAD

**Issue by josephcc** [RaRe-Technologies/gensim#1397]
#### Description
Unable to search for most_similar labels using neither 1) a set of (non-label) words, nor 2) a vector.

version: 2.1.0

#### Steps/Code/Corpus to Reproduce
If I understood doc2vec correctly, it projects both labels (such as 'SENT_0') and words into the same semantic space. In theory I should be able to search for both words and labels at the same time, as also shown here by @piskvorky: https://rare-technologies.com/doc2vec-tutorial/  

However, when I ran the code in the above link, I could only search for words using words
```python
model.most_similar('word')
# only similar words were returned but not labels
```

I could also use `model.docvecs.most_similar` to search for similar labels using labels. For example, `LABEL_0` is similar to `LABEL_23`.

I did manage to search for similar words using labels with the following:

```python
model.docvecs['label']
model.similar_by_vector(label_vec)
# only similar words were returned
```

But I couldn't do the reverse, which is to use a set of words to search for similar labels, since `model.docvecs` doesn't have a `similar_by_vector` method.

**Comment by josephcc** [comment]
Ok I found the solution from these two links:

https://github.com/RaRe-Technologies/gensim/issues/453
https://groups.google.com/forum/#!msg/gensim/Fujja7aOH6E/C3WArofWbNIJ

and here's how to search for similar labels using words:

```python
word_vec = model['word']
model.docvecs.most_similar([word_vec])
# returns similar labels
```

closing for now.

**Comment by piskvorky** [comment]
@menshikh-iv @gojomo is the doc2vec documentation clear on this?

I don't see it in the quick-start on the top either, it only shows load/save:
https://radimrehurek.com/gensim/models/doc2vec.html

**Comment by menshikh-iv** [comment]
@piskvorky What do you think about common cheat-sheet for most popular models (see an [example from plotly](https://media.licdn.com/mpr/mpr/shrinknp_800_800/AAEAAQAAAAAAAAfoAAAAJDUwYmYxYzZmLTc1ZGEtNGI5My1iMmEyLWQwZjQ5OTdjZjYwNQ.jpg)) ?

**Comment by piskvorky** [comment]
That's a good idea!

But we need a proper, inter-linked documentation structure anyway, so people can actually find that information -- no matter if it's in API docs or cheat-sheet or a tutorial...
