### ISSUE TITLE
How to output similarity matrix using word2vec in gensim?

### ISSUE THREAD

**Issue by chengjun** [RaRe-Technologies/gensim#140]
I have tested the nice api of wod2vec. It works perfectly on windows (without cython 8 hours) and ubuntu (with cython 15 minutes). 

I looked into the output model and binary word2vec_format model. However, I can't get a matrix of similarity using word2vec. 

This similarity matrix is necessary, based on which the words could be clustered or visualized using network analysis.

**Comment by AsmaZbt** [comment]
hello , piskvorky 

could you please explaine me what represente  model.init_sims(); matrix = numpy.dot(model.syn0norm, model.syn0norm.T) what is model.syn0norm.T ? 

thank you so much 👍

**Comment by menshikh-iv** [comment]
@AsmaZbt 
- `model.init_sims()` used for initialization of `model.syn0norm`
- `model.syn0norm.T` is transposed version of `model.syn0norm`
- `model.syn0norm` is matrix, that contains normalized word-vectors (i.e. with length = 1)
- `matrix = numpy.dot(model.syn0norm, model.syn0norm.T)` gives you distance matrix between all vectors (i.e. `matrix[i][j]` = distance between word `i` and word `j`)

**Comment by AsmaZbt** [comment]
@menshikh-iv thank you so much its so clear (y) thank you so much

**Comment by tvrbanec** [comment]
It seems weird to me that there is no consistent solution for getting similarity matrix from word2vec.
There are such a solution for tf-idf and many other, even for SoftCosineSimilarity:
```
def softcosinesim(texts):
    model = Word2Vec(texts, size=20, min_count=1)
    termsim_index = WordEmbeddingSimilarityIndex(model.wv)
    dictionary = Dictionary(texts)
    bow_corpus = [dictionary.doc2bow(document) for document in texts]
    similarity_matrix = SparseTermSimilarityMatrix(termsim_index, dictionary)
    docsim_index = SoftCosineSimilarity(bow_corpus, similarity_matrix)
    sims = docsim_index[bow_corpus]  # calculate similarity of query to each doc from bow_corpus
    return sims
```

**Comment by kennedyCzar** [comment]
Thanks for sharing @tvrbanec. For clarity sake I tried ellaborating with a class.

Source: https://radimrehurek.com/gensim/similarities/docsim.html

`class SimilarityMat(object):
    def __init__(self, model, text:np.array):
        self.model = model
        self.text = text
        self.SimilarityMatrix()
        return
    
    def SimilarityMatrix(self):
        termsim_index = WordEmbeddingSimilarityIndex(self.model.wv)
        self.dictionary = Dictionary(self.text)
        bow_corpus = [self.dictionary.doc2bow(document) for document in self.text]
        similarity_matrix = SparseTermSimilarityMatrix(termsim_index, self.dictionary)
        self.docsim_index = SoftCosineSimilarity(bow_corpus, similarity_matrix)
        return self

    def QuerySim(self, query):
        return self.docsim_index[self.dictionary.doc2bow(query)]

#n-->the number of documents or observation in data set..
n, _ = document.shape
model_mv = gensim.models.Word2Vec(document, min_count = 4, size = VOCAB_SIZE)
sim_matrix = np.zeros((n, n)) #nxn similarity matrix
for ii, ij in enumerate(document):
    sim_matrix[ii] = SimilarityMat(model_mv, txy).QuerySim(ij)

#save similarity matrix
np.savez_compressed(join(paths['data'], 'Model/CosineSim.npz'), cs = sim_matrix)

`

**Comment by kennedyCzar** [comment]
Thanks for sharing @tvrbanec. For clarity sake I tried ellaborating with a class.

Source: https://radimrehurek.com/gensim/similarities/docsim.html

`
class SimilarityMat(object):

      def __init__(self, model, text:np.array):
          self.model = model
          self.text = text
          self.SimilarityMatrix()
          return

      def SimilarityMatrix(self):
          termsim_index = WordEmbeddingSimilarityIndex(self.model.wv)
          self.dictionary = Dictionary(self.text)
          bow_corpus = [self.dictionary.doc2bow(document) for document in self.text]
          similarity_matrix = SparseTermSimilarityMatrix(termsim_index, self.dictionary)
          self.docsim_index = SoftCosineSimilarity(bow_corpus, similarity_matrix)
          return self

      def QuerySim(self, query):
          return self.docsim_index[self.dictionary.doc2bow(query)]
  `

n-->the number of documents or observation in data set..
`n, _ = document.shape`
`model_mv = gensim.models.Word2Vec(document, min_count = 4, size = VOCAB_SIZE)`
`sim_matrix = np.zeros((n, n)) #nxn similarity matrix`

` 
for ii, ij in enumerate(document):
     sim_matrix[ii] = SimilarityMat(model_mv, txy).QuerySim(ij)
`

#save similarity matrix
`np.savez_compressed(join(paths['data'], 'Model/CosineSim.npz'), cs = sim_matrix)`
