### ISSUE TITLE
Evaluate similarity search libraries (annoy, faiss, etc).

### ISSUE THREAD

**Issue by menshikh-iv** [RaRe-Technologies/gensim#1412]
It would be nice if we did a benchmark and compare popular libraries like annoy, faiss, nmslib, FLANN, etc.

A good reference is [/erikbern/ann-benchmarks](https://github.com/erikbern/ann-benchmarks) and [/piskvorky/sim-shootout](https://github.com/piskvorky/sim-shootout).

See also [this topic](https://github.com/RaRe-Technologies/gensim/pull/1367#issuecomment-306012642).

**Comment by anxingle** [comment]
didn't compare faiss?

**Comment by anxingle** [comment]
ANN benchmark http://www.itu.dk/people/pagh/SSS/ann-benchmarks/index.html

**Comment by menshikh-iv** [comment]
@anxingle thanks for a link

**Comment by Semen52** [comment]
Latest benchmark : https://erikbern.com/2018/02/15/new-benchmarks-for-approximate-nearest-neighbors.html
