### ISSUE TITLE
duplicate annoy tutorials - annoytutorial.ipynb & annoytutorial-text8.ipynb ?

### ISSUE THREAD

**Issue by gojomo** [RaRe-Technologies/gensim#1415]
There seem to be two (nearly?) identical ANNOY tutorial notebooks:

https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/annoytutorial-text8.ipynb

https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/annoytutorial.ipynb

Maybe a merge error retained the file under an older name? Seems there should be only one, probably the one with the longer more-detailed name.

@quole @vochicong @pmbaumgartner

**Comment by pmbaumgartner** [comment]
I think this is a merge error. I built the new tutorial under `annoytutorial-text8.ipynb`, then renamed the file to `annoytutorial.ipynb` to replace the original, [as requested](https://github.com/RaRe-Technologies/gensim/pull/1355#issuecomment-303251321).

**Comment by souravsingh** [comment]
@menshikh-iv I believe the issue can be closed.

**Comment by menshikh-iv** [comment]
@souravsingh  Not now, because I'll remove all duplicates in new PR (duplicates existing now [here](https://github.com/RaRe-Technologies/gensim/tree/develop/docs/notebooks))

**Comment by Karamax** [comment]
Solved [1640](https://github.com/RaRe-Technologies/gensim/pull/1640).
