### ISSUE TITLE
Do not run python checks on non-python files

### ISSUE THREAD

**Issue by rasto2211** [RaRe-Technologies/gensim#1425]
Travis runs python checks (such as flake8) on non-python files. This causes PRs which make changes in non-pythonic code to fail.

**Comment by gojomo** [comment]
For example, the docs `Makefile` in #1424.

**Comment by menshikh-iv** [comment]
I think we can add files to `--exclude` in flake8.

**Comment by rasto2211** [comment]
Is flake8 the only python check?

**Comment by rasto2211** [comment]
Ok, I see the script in:
`continuous_integration/travis/flake8_diff.sh`
is responsible for this part.

**Comment by rasto2211** [comment]
And it seems that large part of the script was copied from scikit-learn.

**Comment by menshikh-iv** [comment]
Fixed
