### ISSUE TITLE
Export DTM output to excel or txt

### ISSUE THREAD

**Issue by mdDTM** [RaRe-Technologies/gensim#1435]
following this tutorial
https://markroxor.github.io/gensim/static/notebooks/ldaseqmodel.html#topic=0&lambda=1&term=
how could I export the output (evolution of different topics) of DTM  as separate text or excel files (or same file but with the option to track the topic over time)? 
Any code?
Thanks

#### Description
TODO: change commented example

**Comment by menshikh-iv** [comment]
@mdDTM hi, please check [dtm wrapper](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/wrappers/dtmmodel.py#L185), you can modify this code and extract all needed info.
