### ISSUE TITLE
DTM model subprocess.CalledProcessError in new release

### ISSUE THREAD

**Issue by hanhanzhai** [RaRe-Technologies/gensim#1439]
I was generating a DTM model as documentation: 
`model = DtmModel(dtm_path, corpus, time_seq, num_topics)`

An error happened as the following:

> self.train(corpus, time_slices, mode, model)
> check_output(args=cmd, stderr=PIPE)
> in check_output 
> raise error
> subprocess.CalledProcessError: Command '['dtm-path',......]' returned non-zero exit status 1. 

The code was working before, so I'm wondering if I need to update somewhere to cope with the new release? Thanks a lot!

**Comment by hanhanzhai** [comment]
I also tried on Mac by using the same code, but change dtm_path to:
`dtm_path = "dtm-darwin64"`

And get the following error:
  
> File "/gensim/models/wrappers/dtmmodel.py", line 128, in __init__
>     self.train(corpus, time_slices, mode, model)
>   File "/gensim/models/wrappers/dtmmodel.py", line 201, in train
>     check_output(args=cmd, stderr=PIPE)
>   File "/gensim/utils.py", line 1157, in check_output
>     process = subprocess.Popen(stdout=stdout, *popenargs, **kwargs)
>   File "/python2.7/subprocess.py", line 390, in __init__
>     errread, errwrite)
>   File "/python2.7/subprocess.py", line 1024, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

Is this because I'm using python 2.7? Or I didn't specify dtm_path correctly? Thanks a lot!

**Comment by menshikh-iv** [comment]
Hi @hanhanzhai 

> I also tried on Mac by using the same code, but change dtm_path to:
dtm_path = "dtm-darwin64"

You need to specify full absolute path to binary `main` from [blei-lab/dtm](https://github.com/blei-lab/dtm) repo
I re-run all tests for wrappers and can't reproduce your error.
Please, enable logging
```
import logging
logging.basicConfig(level=logging.DEBUG)
```
After you will see a full command for dtm, please write this command here and try to run it without gensim (in console).

**Comment by hanhanzhai** [comment]
Hi @menshikh-iv, 

Thanks for pointing out the full path problem! 
The problem is fixed now, and things are running fine. I am closing this issue. Thanks a lot!
