### ISSUE TITLE
Minimum version for numpy/scipy

### ISSUE THREAD

**Issue by menshikh-iv** [RaRe-Technologies/gensim#1450]
In the last release, I had to "bump" versions for numpy/scipy. This may be a problem for *ops people (need to upgrade old versions). 

For this reason, we should downgrade numpy/scipy version and don't break anything.

**Comment by piskvorky** [comment]
Ticket goal:
* [ ] figure out oldest support version of numpy and scipy.
* [ ] update setup.py to only require the absolute minimum needed (oldest needed versions)
* [ ] update the testing framework (Travis etc) to test the oldest requires versions
