### ISSUE TITLE
AttributeError: 'Doc2Vec' object has no attribute 'syn1neg'

### ISSUE THREAD

**Issue by flowingrain** [RaRe-Technologies/gensim#1451]
#### Description
TODO: change commented example

#### Steps/Code/Corpus to Reproduce

`doc_id = np.random.randint(simple_models[0].docvecs.count)`  
# pick random doc; re-run cell for more examples
`print('for doc %d...' % doc_id)`
`for model in simple_models:`
&emsp;`inferred_docvec = model.infer_vector(alldocs[doc_id].words)`
&emsp;`print('%s:\n%s'% (model, model.docvecs.most_similar([inferred_docvec], topn=3)))`
#### Expected Results

Like this:
for doc 25430...
Doc2Vec(dm/c,d100,n5,w5,mc2,t8):
 [(25430, 0.6583491563796997), (27314, 0.4142411947250366), (16479, 0.40846431255340576)]
Doc2Vec(dbow,d100,n5,mc2,t8):
 [(25430, 0.9325973987579346), (49281, 0.5766637921333313), (79679, 0.5634804964065552)]
Doc2Vec(dm/m,d100,n5,w10,mc2,t8):
 [(25430, 0.7970066666603088), (97818, 0.6925815343856812), (230, 0.690807580947876)]
#### Actual Results

![image](https://user-images.githubusercontent.com/19755864/27529254-61944d2a-5a86-11e7-83fa-d7705fedd41d.png)

#### Versions

gensim 2.2.0

**Comment by gojomo** [comment]
Where did your simple_models come from? Are you sure the instance triggering the error has been initialized/trained? (The `syn1neg` array is only allocated at the end of the `build_vocab()` steps.)

**Comment by flowingrain** [comment]
@gojomo Simple_models come from doc2vec_IMDB.ipynb,  I train these models one by one, like this 
![image](https://user-images.githubusercontent.com/19755864/27539694-02ac795c-5ab0-11e7-8daf-e44554bc5c6e.png)
as suggested. Is there any problem?

**Comment by gojomo** [comment]
This only show training one instance, `simple_models[2]`. Are you sure the exact instance triggering the error has been initialized/trained? (In your `for model in simple_models` loop above, more models than just `simple_models[2]` are being probed.)

Raw text would be easier to read than a screenshot, and general usage questions like this that aren't yet sure (or likely) to be bugs are better addressed on the project forum, <https://groups.google.com/forum/#!forum/gensim>.

**Comment by menshikh-iv** [comment]
@flowingrain this matrix doesn't exist if you don't fit your model, after fitting all works OK.
