### ISSUE TITLE
Pick word matches based on number of times word occurs

### ISSUE THREAD

**Issue by Abiwax** [RaRe-Technologies/gensim#1452]
Hi,
I am having an issue with my similarity results, if i have a list of words before tokenizing.
For example:
Subtotal: Subtotal and Sub total.
Total: Total Tax, Total Number, Total Amount, Amount Total.
If i search for the word Total, i get Subtotal as my result
I would expect that i will get Total as the similar value because it has more total in it, really confused about this, find below my code:

> texts = [[token for token in text if frequency[token] > 1] for text in texts]
> dictionary = corpora.Dictionary(texts)
> corpus = [dictionary.doc2bow(text) for text in texts]
> lsi = models.LsiModel(corpus, id2word=dictionary, num_topics=2)
> doc = word.lower().split()
> vec_bow = dictionary.doc2bow(doc)
> vec_lsi = lsi[vec_bow]
> index = similarities.MatrixSimilarity(lsi[corpus], num_features=300)
> sims = index[vec_lsi]
> sims = sorted(enumerate(sims), key=lambda item: -item[1])

Thanks

**Comment by menshikh-iv** [comment]
@Abiwax  It's OK, if you want to "distinct" this phrases please make different tokens (for example, create bigrams with Phrases module).
