### ISSUE TITLE
Gensim: Loss of Words/Tokens while Training

### ISSUE THREAD

**Issue by djokester** [RaRe-Technologies/gensim#1474]
I have a corpus built out of Wikimedia Dump files stored at sentences.txt I have a sentence say 'नीरजः हाँ माता जी! स्कूल ख़त्म होते सीधा घर आऊँगा' Now a sample code for obtaining word vectors for the sentence with respect to the corpus using Word2Vec would look somewhat like this.

```
from nltk import word_tokenize
import gensim
import logging

sentences = open("sentences.txt", "r+")
sentences = sentences.read().split("\n")
sentence = 'नीरजः हाँ माता जी! स्कूल ख़त्म होते सीधा घर आऊँगा'

sentence = [word_tokenize(i) for i in sentence]
sentences = [word_tokenize(i) for i in sentences]
sentences = sentences + sentence 

logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
model = gensim.models.Word2Vec(sentences, size =10,  min_count=1)

pred = []
for word in sentence:
        pred.append(model.wv[word].tolist())

```
Now when I try to extract the word vectors there is always one word which has been missed out while training (despite being included in the list to be trained upon) and I get the KeyError. Is there any way to improve the training so that it doesn't miss out words that frequently?

Here is a proof that it does happen. `tok.wordtokenize` is a word tokenizer. `sent.drawlist()` as well as `sents.drawlist()` returns a list of sentences from the corpus.

```
>>> sentence = 'नीरजः हाँ माता जी! स्कूल ख़त्म होते सीधा घर आऊँगा'
>>> sentence = tok.wordtokenize(sentence)
>>> sentences = sent.drawlist()
>>> sentences = [tok.wordtokenize(i) for i in sentences]
>>> sentences2 = sents.drawlist()
>>> sentences2 = [tok.wordtokenize(i) for i in sentences2]
>>> sentences = sentences2 + sentences + sentence
>>> "नीरजः" in sentences
True
>>> model = gensim.models.Word2Vec(sentences, size =10,  min_count=1) 
>>> pred = []
>>> for word in sentence:
...         pred.append(model.wv[word].tolist())
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/djokester/anaconda3/lib/python3.5/site-packages/gensim/models/keyedvectors.py", line 574, in __getitem__
    return self.word_vec(words)
  File "/home/djokester/anaconda3/lib/python3.5/site-packages/gensim/models/keyedvectors.py", line 273, in word_vec
    raise KeyError("word '%s' not in vocabulary" % word)
KeyError: "word 'नीरजः' not in vocabulary"
```
As you can see, I check for the word "नीरजः" inside the list of tokenized sentences. It is present in the list that I feed into the Word2Vec trainer and yet after training it is not in the vocabulary.

**Comment by gojomo** [comment]
I've made an attempt to answer where you've asked on SO: https://stackoverflow.com/questions/44964380/gensim-loss-of-words-tokens-while-training/44969553?noredirect=1#comment76926593_44969553

Your code is confused and (as shown) incomplete. If a token isn't in the model, post-training, then your corpus/tokenizer/preprocessing didn't supply it in the proper form. 

The github issues are not for questions, but for bugs and feature requests. Continue discussion on SO, or on the project discussion list <https://groups.google.com/forum/#!forum/gensim>.
