### ISSUE TITLE
Model Persistence for Translation Matrix

### ISSUE THREAD

**Issue by robotcator** [RaRe-Technologies/gensim#1475]
Hi, all,
Currently, I have implemented the training for translation matrix model, which which map the source language to the target language. I want to add save/load method for the trained model. But I have to save several parameters, which are the translation matrix, source language word vector, target language word vector( as a retrieve space). For this, we can only pass the word which to be translated to the translate method. it can get the source word vector from the model itself, then mapping it to target language with translation matrix, finally retrieve the most closet(similar) word vector from the target word vector and return its corresponding word.

I want to know is there any idea to better design this method for model persistence, any suggestions is appreciated.

for more details and the translation matrix usage(refer this [PR](https://github.com/RaRe-Technologies/gensim/pull/1434))

**Comment by gojomo** [comment]
Python pickling works unless/until any internal arrays are gigantic, and thus either better saved separately, or necessarily saved separately (because pickle may have issues with > 2GiB array objects). You can use the way Word2Vec inherits `save()` from a util class as a model.

**Comment by robotcator** [comment]
Yes, if we save the model separately, it needs to be careful when loading the model. Because this model is trained for specific source language and target language, we have not the technique to check the word which is an other language.

**Comment by robotcator** [comment]
@gojomo Thanks, I have solve this problem. So this issue will be closed.
