### ISSUE TITLE
Error During Query Causes Memory Leak

### ISSUE THREAD

**Issue by justinkterry** [RaRe-Technologies/gensim#1487]
This happened when I was trying to get the most distant object and got a severe error that made my system freeze, including the audio, for a second (code run shown in screen show):
http://i.imgur.com/5s37SjI.png Note ram being consumed due to no use.

Identical software specs to here report here (https://github.com/RaRe-Technologies/gensim/issues/1486).

Please tell me if any more info is required.

**Comment by gojomo** [comment]
Please include text code of what you're trying and what error you see - screenshots are much harder to interpret & discuss.

With those synptoms, there's a good chance you're hitting a system-specific resource limit, so pleae

**Comment by justinkterry** [comment]
Code:

path = '/home/justin/Documents/wiki.en/wiki.en.vec'

model = gensim.models.KeyedVectors.load_word2vec_format(path, binary=False)
Traceback (most recent call last):

  File "<ipython-input-2-8aabd1f88989>", line 1, in <module>
    model = gensim.models.KeyedVectors.load_word2vec_format(path, binary=False)

NameError: name 'gensim' is not defined


import gensim

model = gensim.models.KeyedVectors.load_word2vec_format(path, binary=False)

printmodel.wv.most_similar_cosmul( negative=['man'])
Traceback (most recent call last):

  File "<ipython-input-5-6eba0b74735a>", line 1, in <module>
    printmodel.wv.most_similar_cosmul( negative=['man'])

NameError: name 'printmodel' is not defined


print(model.wv.most_similar_cosmul( negative=['man']))
Traceback (most recent call last):

  File "<ipython-input-6-6a6964656f94>", line 1, in <module>
    print(model.wv.most_similar_cosmul( negative=['man']))

  File "/usr/local/lib/python3.5/dist-packages/gensim/models/keyedvectors.py", line 486, in most_similar_cosmul
    raise ValueError("cannot compute similarity with no input")

ValueError: cannot compute similarity with no input

loaded object:
https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md

**Comment by justinkterry** [comment]
OS: Ubuntu 16.04.2
Ram: 12GB
Load size: 6.6GB
CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz

I see no way it was a hardware issue, and given that a catastrophic failure in the middle of a c lib action caused this, it doesn't seem necessarily like hardware to me.

**Comment by justinkterry** [comment]
Issue may be related to https://github.com/RaRe-Technologies/gensim/issues/1486

**Comment by gojomo** [comment]
There's no need to include unrelated code lines, like before `gensim` was even imported. 

Which line triggered the system freeze? (The fact that all the lines you've provided show response output indicates they each completed, without freezing the system.)

How large is the  `wiki.en.vec` file you're loading?

**Comment by justinkterry** [comment]
Retype of code for reability:

import gensim
path = '/home/justin/Documents/wiki.en/wiki.en.vec'
model = gensim.models.KeyedVectors.load_word2vec_format(path, binary=False)
print(model.wv.most_similar_cosmul( negative=['man']))

Line 4 freezes the system temporarily, not permanently, and throws an error because no positives are added (I was trying to find words with word vectors furthest from the input- if you know the correct way to do that please tell me). The memory consumed for the line 4 call isn't released, presumably due to how the error occurs, you can see this happen in linked image of the memory shown in my first post. The file is 6.6GB, and was already fully in ram before I made the similar call (this was done in ipython) so the increase due to it won't show in the ram image.

**Comment by gojomo** [comment]
Since you're executing these lines in IPython, the retained memory is likely just because of its error-capture & reporting. For example, the ability to examine the last error-frame (as via `%debug`) means the full state at the time of the error is retained (at least for a while). So there's no memory leak in gensim code. 

`most_similar()` and `most_similar_cosmul()` require some positive examples. (In fact, the 'cosmul' variant will only give differently-ranked results with a mix of both positive and negative examples.) You could probably supply the origin-vector as a plug value - eg `positive=[np.zeros(model.vector_size)]`. But you won't really be finding the vectors *farthest* from `wv['man']` in such as case, but those *closest* to the negation-of-`wv['man']`. There's no furthest functionality in the existing API; you could instead use a `topn` equal to the total number of word-vectors, so you get *all* other vectors sorted from closest-to-farthest – then just look at the last N. For example:

    furthest = wv.most_similar('man'), topn=len(wv))[-10:]  # 10 furthest vectors from 'man'

**Comment by justinkterry** [comment]
Thanks a ton for your explanation, and you're right that it's iPython. Sorry I missed that; closing. Also, would you be so kind to briefly explain to me (or link me to a simple explanation of) how word negations are found and how they differ from the farthest possible vector? I'm sure it's just because I don't know enough to know what to google, but I haven't been able to find anything.

**Comment by gojomo** [comment]
A negation just flips the sign of all dimensions – essentially mirroring through the origin. Other vectors (when considering raw vector magnitudes) could be even further from the original vector – in any of many directions. 

When considering just cosine-similarity (angular similarity), then yes, I believe that the negated-vector would have the lowest-possible cosine-similarity (-1.0). But that won't necessarily mean the "opposite" in any human-schema-of-meaning – as in the examples above, 'manness' has many possible contrasting 'opposites' depending on context/sense. It *might* be the case that word2vec vectors can model such contrasts – the success on solving analogies suggests it does – but the contrasts are each in a different direction in space (as estimated by subtracting words that are conjectured to be related, finding the vector-direction between them) – *not* all directly opposite through-the-origin.
