### ISSUE TITLE
lp50 ABC dataset from "An Empirical Evaluation of Models of Text Document Similarity", Lee et al.2005

### ISSUE THREAD

**Issue by dinara92** [RaRe-Technologies/gensim#1494]
Hello,

I would like to know if the dataset mentioned in this file ("lee.cor")
gensim/gensim/test/test_data/lee.cor

The file is run from gensim/gensim/test/test_lee.py

is the same dataset used in the paper mentioned in the title of the post.

Thank you!

**Comment by menshikh-iv** [comment]
This question is better to ask in [maillist](https://groups.google.com/forum/#!forum/gensim).
Honestly, I do not know that this dataset is the same or not.

**Comment by Sumitrke88** [comment]
LP 50 dataset is different that was mentioned in the paper.
LP50 is composed of 50 general-purpose news documents with lengths between 50 and 126 words.
i am also looking for download link
