### ISSUE TITLE
2.2.1?

### ISSUE THREAD

**Issue by aldanor** [RaRe-Technologies/gensim#1504]
Hi, wondering if it was in the plans to release a minor version anytime soon? There's a few useful features in master like loading fastText bin files that would be very handy to have in stable.

Thanks!

**Comment by piskvorky** [comment]
Yes, this has been a high priority. A bug-fix release is planned by @menshikh-iv ASAP. Thanks for your patience.

**Comment by menshikh-iv** [comment]
Ok, but new release will be tagged as 2.3.0 (because we already have new features in `develop`)

**Comment by piskvorky** [comment]
@aldanor 2.3.0 released. Let us know if you hit any issues!

**Comment by aldanor** [comment]
Thanks!
