### ISSUE TITLE
mismatched vocab_size and nwords 

### ISSUE THREAD

**Issue by hafizhmakmur** [RaRe-Technologies/gensim#1505]
#### Description
So I was trying to use the FastText wrapper of Gensim and I am using the newest FastText fresh from the github. I also install the newest Gensim from the Git. The function I want to try is the train function for Fast Text and I got AssertionError: mismatched vocab_size (3564) and nwords (2828), extra word "__label__baking" error.

#### Steps/Code/Corpus to Reproduce
I was using Python console and write 

from gensim.models.wrappers import FastText
model = FastText.train('./fasttext', 'cooking.stackexchange.txt')

which is executed in the folder where fast text executable is located. I got the corpus from https://s3-us-west-1.amazonaws.com/fasttext-vectors/cooking.stackexchange.tar.gz

#### Expected Results
I was just expecting the model to be trained and then to play around it.

#### Actual Results
Read 0M words
Number of words:  2828
Number of labels: 736
Progress: 100.0%  words/sec/thread: 37475  lr: 0.000000  loss: 3.048658  eta: 0h0m m
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/gensim/models/wrappers/fasttext.py", line 216, in train
    model = cls.load_fasttext_format(output_file)
  File "/usr/local/lib/python2.7/site-packages/gensim/models/wrappers/fasttext.py", line 244, in load_fasttext_format
    model.load_binary_data(encoding=encoding)
  File "/usr/local/lib/python2.7/site-packages/gensim/models/wrappers/fasttext.py", line 261, in load_binary_data
    self.load_dict(f, encoding=encoding)
  File "/usr/local/lib/python2.7/site-packages/gensim/models/wrappers/fasttext.py", line 310, in load_dict
    'mismatched vocab_size ({}) and nwords ({}), extra word "{}"'.format(vocab_size, nwords, word))
AssertionError: mismatched vocab_size (3564) and nwords (2828), extra word "__label__baking"

#### Versions
Darwin-14.5.0-x86_64-i386-64bit
('Python', '2.7.13 (default, Jul 13 2017, 14:30:38) \n[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]')
('NumPy', '1.13.1')
('SciPy', '0.19.1')
('gensim', '2.2.0')
('FAST_VERSION', 0)

**Comment by menshikh-iv** [comment]
Same as #1498
