### ISSUE TITLE
coercing to str: need a bytes-like object, list found

### ISSUE THREAD

**Issue by gerardogarciag1** [RaRe-Technologies/gensim#1507]
#### Description
TODO: change commented example

TypeError                                 Traceback (most recent call last)
<ipython-input-83-c7c3e8f56404> in <module>()
      1 sentences = MySentences(path) # a memory-friendly iterator
      2 #dictionary = corpora.Dictionary(sentences)
----> 3 corpus = dictionary.doc2bow(sentences, allow_update=True)

C:\AppData\Local\Continuum\Anaconda4\envs\cars\lib\site-packages\gensim\corpora\dictionary.py in doc2bow(self, document, allow_update, return_missing)
    144         counter = defaultdict(int)
    145         for w in document:
--> 146             counter[w if isinstance(w, unicode) else unicode(w, 'utf-8')] += 1
    147 
    148         token2id = self.token2id

TypeError: coercing to str: need a bytes-like object, list found

#### Steps/Code/Corpus to Reproduce

class MySentences(object):
    def __init__(self, dirname):
        self.dirname = dirname
 
    def __iter__(self):
        for fname in os.listdir(self.dirname):
            print (fname)
            os.system('java -jar c:\\jars\\tika-app-1.14.jar -t "'
                      +os.path.join(self.dirname, fname)
                      +'" > file1.txt')
            str1 = ''
            for line in open('file1.txt', mode="rt"):
                if line is list:
                    str1 = " ".join(str(x) for x in line)
                else:
                    str1 = str(line).lower().encode('utf-8')  
                    print (str1 is list)
                yield str1.split()
                
sentences = MySentences(path) # a memory-friendly iterator
corpus = dictionary.doc2bow(sentences, allow_update=True)

#### Actual Results

coercing to str: need a bytes-like object, list found

**Comment by iarroyof** [comment]
Hi... I have the same problem.. Please can someone help me?

**Comment by menshikh-iv** [comment]
@gerardogarciag1 @iarroyof dictionary.doc2bow as input wait only one list of tokens (not a generator of sentences).
For your case, fit dictionary first and after it applies `doc2bow` to each sentence.

**Comment by gauravkoradiya** [comment]
have a same problem after building a dictionary first.


```
def iter_tokenized_documents(input_directory):
    """Iterate over all documents, yielding a document (=list of utf8 tokens) at a time."""
    for root, dirs, files in os.walk(input_directory):
        for file in filter(lambda file: file.endswith('.txt'), files):
            document = preprocess_string(open(os.path.join(root, file),encoding='utf8',errors='ignore').read().strip(),filters=CUSTOM_FILTERS)
            if(len(document)):
                yield document


class MyCorpus(object):

    def __init__(self, corpus_dir, vocab_path, build_dictionary=True):

        self.corpus_dir = corpus_dir
        self.vocab_path = vocab_path
        self.raw_data = iter_tokenized_documents(self.corpus_dir)
        if build_dictionary:
            self.vocabulary = gensim.corpora.Dictionary(document for document in self.raw_data)
            self.vocabulary.save_as_text(self.vocab_path, sort_by_word=True)
            logging.info('Dictionary saved at {}'.format(self.vocab_path))
        else:
            self.vocabulary = gensim.corpora.Dictionary.load_from_text(self.vocab_path)
        logging.info('Dictionary Loaded')

    def __iter__(self):
        yield self.vocabulary.doc2bow(document for document in self.raw_data)
```
Error:
`TypeError: decoding to str: need a bytes-like object, list found`

**Comment by piskvorky** [comment]
@gauravkoradiya your message is missing the stack trace, but I guess it's exactly the same problem as above (with the same solution).
