### ISSUE TITLE
Feature Request: Get entire weight vector and word/doc order in Doc2Vec & Word2Vec

### ISSUE THREAD

**Issue by jolespin** [RaRe-Technologies/gensim#1513]
It would be awesome if there could be an option getting the entire weight matrix all at the same time.  For example, 

`model.wt_` or `model.wt` would return an array of shape `(n_words, m_nodes)` and then `model.words` would return a list of the words in the order of the weight matrix.  Basically enough to do:
`pd.DataFrame(model.wt_, index=model.words)`

Also the same for `docvecs`:
`model.docvecs_.shape = (d_docvecs, m_nodes)`

Here is some code from:
from https://stackoverflow.com/questions/31321209/doc2vec-how-to-get-document-vectors
```
# Import libraries

from gensim.models import doc2vec
from collections import namedtuple

# Load data

doc1 = ["This is a sentence", "This is another sentence"]

# Transform data (you can add more data preprocessing steps) 

docs = []
analyzedDocument = namedtuple('AnalyzedDocument', 'words tags')
for i, text in enumerate(doc1):
    words = text.lower().split()
    tags = [i]
    docs.append(analyzedDocument(words, tags))

# Train model (set min_count = 1, if you want the model to work with the provided example data set)

model = doc2vec.Doc2Vec(docs, size = 100, window = 300, min_count = 1, workers = 4)

# Get the vectors

model.docvecs[0]
model.docvecs[1]
```

**Comment by gojomo** [comment]
This more-or-less already exists:

The raw vectors array of words in a Word2Vec or Doc2Vec model is available in `model.wv.syn0`. The list of words in the index-order of that array is in `model.wv.index2word`. 

Raw doc-vectors for a Doc2Vec model will be in `model.docvecs.doctag_syn0`. If you used string doctags as the keys for document vectors, and *only* string doctags, a list of string doctags in that array's index-order is in `model.docvecs.offset2doctag`. (If you used only plain-int doctags, that list will be empty. If you used a mix of plain-ints and strings, all the ints appear first, then the `offset2doctag` doc-vectors appear after the `model.docvecs.max_rawint` slot.)
