### ISSUE TITLE
TypeError: train() got an unexpected keyword argument 'total_examples'

### ISSUE THREAD

**Issue by xxyy1** [RaRe-Technologies/gensim#1514]
gensim 2.3.0

model = gensim.models.wrappers.fasttext.FastText(sentences=usr_sequence, size=8, min_count=5, window=8, workers=16)

error:
Traceback (most recent call last):
  File "mytest_fasttext.py", line 31, in <module>
    train_poi2vec(s_sequence_file, model_file)
  File "mytest_fasttext.py", line 22, 
    model = gensim.models.wrappers.fasttext.FastText(sentences=usr_sequence, size=8, min_count=5, window=8, workers=16)
  File "/home/anaconda3/lib/python3.6/site-packages/gensim/models/word2vec.py", line 505, in __init__
    start_alpha=self.alpha, end_alpha=self.min_alpha)
TypeError: train() got an unexpected keyword argument 'total_examples'

**Comment by prakhar2b** [comment]
@xxyy1  `model = gensim.models.wrappers.fasttext.FastText('path to fasttext executive', usr_sequence, size=8, min_count=5, window=8, workers=16)`
FastText wrapper is a subclass implementation of word2vec, so wrong initialization/ params might lead to word2vec instead.

For more info - see documentation - https://radimrehurek.com/gensim/models/wrappers/fasttext.html

**Comment by xxyy1** [comment]
hi  @prakhar2b   my params  "usr_sequence" is list like "[[word,....,word],[],[]]"   ,this right ?

**Comment by xxyy1** [comment]
before  "usr_sequence"   must have a file path  ?

**Comment by gojomo** [comment]
Looks like none of the tests (and probably none of the public examples) use the `FastText` class in the same single-shot initialize-and-train-on-supplied-corpus style that` Word2Vec` supports – and that trying to use that style triggers this error, as the `FastText.train()` is not in sync with the parameters of `Word2Vec.train()`. (And, it probably can't/shouldn't be made to match perfectly, as it needs extra literal file paths rather than Python iterables.)

Is there any good reason for `FastText`, as a wrapper, to derive from `Word2Vec`? It appears the only use of `super` is in `save()` and could likely derive instead from `SaveLoad`.

**Comment by xxyy1** [comment]
@gojomo  hi, do you mean params "sequence" must be a file paths ?
like this:
model = gensim.models.wrappers.fasttext.FastText("file path", size=8, min_count=5, window=8, workers=16)

or 
model = gensim.models.wrappers.fasttext.FastText("file path", usr_sequence, size=8, min_count=5, window=8, workers=16)  
?

**Comment by gojomo** [comment]
It looks to me like the FastText class isn't meant to be used at all via the default initializer – which further calls into question whether it should derive from Word2Vec at all. 

Are you working from an example you saw somewhere? All the examples I see (including in the module's doc-comment) user `FastText.train()` directly as a class method. (That's yet another deviation from the norms set by Word2Vec as a superclass.)

Use `FastText.train()` in accordance with its arguments, and limitations as a simple pass-through wrapper for the FB fasttext executable. Ignore the inherited API from Word2Vec – it doesn't appear to make any sense.

**Comment by piskvorky** [comment]
CC @jayantj @chinmayapancholi13 @menshikh-iv

**Comment by zotroneneis** [comment]
When using 'model = FastText.train('/Users/kofola/fastText/fasttext', corpus_file)' how is `corpus_file` supposed to look like? Is it the entire training corpus as one string? Or a list of sentences? Or something else?

**Comment by piskvorky** [comment]
@zotroneneis its documentation says `corpus_file is the filename of the text file to be used for training the FastText model. Expects file to contain utf-8 encoded text.`

The filename is simply passed into the underlying `fasttext` library as a parameter, gensim does nothing with it.

**Comment by zotroneneis** [comment]
Ok, so the text file doesn't have to formatted in any specific way?

**Comment by menshikh-iv** [comment]
@zotroneneis you can find the answer in https://github.com/facebookresearch/fastText.

**Comment by gojomo** [comment]
Use of the fasttext 'wrapper' has been deprecated in recent releases, and is going away entirely in the next major release - so closing this issue.
