### ISSUE TITLE
Re-Training a pre-trained Doc2Vec model with new docs

### ISSUE THREAD

**Issue by ashutoshsaboo** [RaRe-Technologies/gensim#1516]
Hi,
I am new to gensim, and I am trying to use doc2vec for a particular task. I managed to get it successfully working, but now I wish to re-train the same pre-trained doc2vec model (that I have trained till now) with some new document vectors (basically the vocabulary might have to change, as well as the weights will change). Is there a way by which I can accomplish the same?
Or will I have to train the model, again from scratch with the old document vectors+new one's together?
Thanks! :smile:

**Comment by gojomo** [comment]
Please ask advice questions on the project discussion list, <https://groups.google.com/forum/#!forum/gensim>, reserving this issue-tracker for bugs and feature-requests.
