### ISSUE TITLE
Fix python warnings (occur during testing)

### ISSUE THREAD

**Issue by menshikh-iv** [RaRe-Technologies/gensim#1519]
Need to fix warnings from interpreter (during test run).
It's easy to see all:
`python -Wd -t -3` for python2
`python -Wd -b` for python3

**Comment by menshikh-iv** [comment]
I looked at it and realized that it makes no sense to do it separately. This can be done in the process of refactoring tests (in the future).

**Comment by poornagurram** [comment]
@menshikh-iv I would like to submit a PR for this. I am a beginner contributor. can you elaborate on this?.

**Comment by menshikh-iv** [comment]
@poornagurram of course, I'll review #1655

**Comment by poornagurram** [comment]
@menshikh-iv I didn't get a clear idea about this issue can you elaborate more on this.

**Comment by menshikh-iv** [comment]
@poornagurram of course,

Firstly (for simple investigation) you need to run tests with python3 and enabled warnings, howto:
- Clone gensim repo
- Create clean venv
- `pip install -e .[test]` in gensim folder
- python -Wd -b setup.py tests

you'll see many different warnings (about unclosed files, division, etc), you need to go to concrete tests that generate this warning, fix warnings and submit PR.

**Comment by menshikh-iv** [comment]
Many `ResourseWarning` from `smart_open`, this part fixed in [smart_open/140](https://github.com/RaRe-Technologies/smart_open/pull/140), another yet part fixed in #1660

**Comment by ParseThis** [comment]
Is this still a good beginner contrib issue? Would like to have a look. @menshikh-iv

**Comment by menshikh-iv** [comment]
@ParseThis this is a good issue for start, but need to make many small changes (if you have enough time - you are welcome)

**Comment by menshikh-iv** [comment]
I fixed almost all of it in #2191
