### ISSUE TITLE
"Using TensorFlow backend." is displayed every time I import gensim

### ISSUE THREAD

**Issue by yuliji-seedlink** [RaRe-Technologies/gensim#1524]
I am using  Gensim 2.2.0, Python 2.7.12 

Every time I "import gensim", there will be a line "Using TensorFlow backend." printed to the screen output, which is quite annoying. How can I eliminate this line of output?

**Comment by menshikh-iv** [comment]
It's ok, this line shows only when you have installed tf and shows only once.

**Comment by hamid914** [comment]
@menshikh-iv Is there any way to not to use Keras at all?

- I use Gensim to train Word2Vec models without Keras/Tensorflow/Theano.
- On my computer, the training process of Word2Vec model with Gensim using Keras with Tensorflow (if `"backend": "tensorflow"` is set in `~/.keras/keras.josn`) is too much slower than training with Gensim using Keras with Theano (if `"backend": "theano"` is set in `~/.keras/keras.josn`). So I don't want to use Tensorflow.
- When Gensim uses Theano backend, it trains the model faster against using Gensim without Keras. But when I want to compare [Gensim+Keras+Theano] configuration against standalone Gensim, I should uninstall Keras, then test and install Keras again. So I don't want to use Keras sometimes.

What is the right way to switch between these configurations without uninstalling/reinstalling Keras?

**Comment by menshikh-iv** [comment]
@hamid914 Keras/Theano/TF don't use in training process. We used our implementation (written on Cython) for Word2Vec and Doc2Vec. For this reason, it does not matter if it is installed by you. 

Keras needed only for "create Keras embedding layer from our **trained** model". Look at [this notebook with example](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/keras_wrapper.ipynb).
