### ISSUE TITLE
 module 'gensim' has no attribute 'utils'

### ISSUE THREAD

**Issue by fkolokathi** [RaRe-Technologies/gensim#1528]
I run word2vec2tensor.py in Python 3.5 and I take the following error:

 module 'gensim' has no attribute 'utils'

I load the binary and txt files of wordembeddings and still take the same error.Does anyone can help me with that?

Thank you

**Comment by robotcator** [comment]
@fkolokathi  Can you post your code ?

**Comment by menshikh-iv** [comment]
Works correctly for `gensim==3.0.0`, @fkolokathi try to re-install gensim.
