### ISSUE TITLE
Phrases __getitem__() method does not respect chosen scoring function

### ISSUE THREAD

**Issue by SergeyDidenko** [RaRe-Technologies/gensim#1533]
#### Description
Phrases `__getitem__()` method does not respect chosen scoring function, it has 'default' scoring builtin. So when Phrases object is constructed with `scoring='npmi'` it returns wrong results.

See Phrases `export_phrases()` for correct implementation, i.e. `score = scoring_function(count_a, count_b, count_ab)` instead of `score = (pab - min_count) / pa / pb * len(vocab)`

For a while it's better to construct and use Phraser object, i.e. 
`phraser = Phraser[phrases]; res = phraser[sentences]` instead of  `res = phrases[sentences]`

**Comment by piskvorky** [comment]
You're right, looks like a bug, thanks for reporting. Since you already have the solution, can you open a PR with the fix?

CC @michaelwsherman

**Comment by SergeyDidenko** [comment]
Sorry, I don't have the fix yet. I just use Phraser.

**Comment by michaelwsherman** [comment]
Good find--i totally forgot about getitem when I implemented this. I can get a fix together, should be fairly straightforward. Will be a few weeks though, and I assume this isn't a showstopper since Phraser still works.

@sergeididenko -- are you using npmi? That makes me happy.

**Comment by SergeyDidenko** [comment]
@michaelwsherman Yes, I prefer MPI scores over alternatives. Can't say yet if it's better for my current project though.

**Comment by michaelwsherman** [comment]
Fix in PR #1573 .
