### ISSUE TITLE
flake8 F401 error in __init__.py

### ISSUE THREAD

**Issue by zsef123** [RaRe-Technologies/gensim#1551]
Hi, I'm try to refactoring code style.

In PR https://github.com/RaRe-Technologies/gensim/pull/1550

> piskvorky 22 hours ago • edited Owner
> -1: we don't want to litter the code with some tool-specific constructs.
> 
> Instead, open an issue with the tool that requires this, it's a bug on their side if they cannot handle this line.
> 
> If you find such comments in other parts of gensim, please remove them too.

Same case in [sklearn_api/__init__.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/sklearn_api/__init__.py)

ex ) `from .ldamodel import LdaTransformer  # noqa: F401`

For solve F401 error, add noqa comments or add `__all__` list in `__init__.py` file.( [pyflake issue](https://bugs.launchpad.net/pyflakes/+bug/1178905) , [stackoverflow question](https://stackoverflow.com/questions/31079047/python-pep8-class-in-init-imported-but-not-used) )

Which is better in both cases?

**Comment by piskvorky** [comment]
Thanks for digging into this! That pyflake issue really explains it well.

It still looks like a bug in pyflake to me. We could add `__all__` (it's better than the weird comment), but it's still extra code for no reason, so I'm not very thrilled about it. @menshikh-iv thoughts?

**Comment by menshikh-iv** [comment]
So, for my opinion, `noqa` is OK.
We can also add `__all__` directive, but we should "duplicate" import each time in init (I means we should do 2 things: `import somestuff` and add it to `__all__`)

**Comment by zsef123** [comment]
PR https://github.com/RaRe-Technologies/gensim/pull/1550
`+# flake8: noqa`
>piskvorky 4 days ago Owner
This seems to combine the worst of both worlds. Still extra comments, AND no style checking.
I think I prefer even the noqa:F401 version.

In [flake8_diff.sh](https://github.com/RaRe-Technologies/gensim/blob/ed0b03eb061af907c3804b939f4b174ebd3f992c/continuous_integration/travis/flake8_diff.sh), How do ignore F401 error for the `__init__.py` file ?

In `else` block, if `__init__.py`  then add F401 on ignore options, otherwise execute original command

**Comment by zsef123** [comment]
PR https://github.com/RaRe-Technologies/gensim/pull/1550
`+# flake8: noqa`
>piskvorky 4 days ago Owner
This seems to combine the worst of both worlds. Still extra comments, AND no style checking.
I think I prefer even the noqa:F401 version.

How about ignore F401 error for the `__init__.py` file in [flake8_diff.sh](https://github.com/RaRe-Technologies/gensim/blob/ed0b03eb061af907c3804b939f4b174ebd3f992c/continuous_integration/travis/flake8_diff.sh)?

In `else` block, if `__init__.py`  then add F401 on ignore options, otherwise execute original command

**Comment by piskvorky** [comment]
Alright, let's use the `noqa`.

**Comment by menshikh-iv** [comment]
@zsef123 agree with @piskvorky, let's use noqa explicitly.
