### ISSUE TITLE
LDA multicore using high amount of system cpu. upto 30 million kernel context per second

### ISSUE THREAD

**Issue by abhishekbuyt** [RaRe-Technologies/gensim#1566]
48 core, 256 GB machine. no iops recorded.
also checked with strace a very large number of sched_yield() = 0

**Comment by menshikh-iv** [comment]
@abhishekbuyt please add info 
- parameters for LdaMulticore
- python/numpy/scipy/gensim versions

Also, try to set env var `OMP_NUM_THREADS=1`.

**Comment by abhishekbuyt** [comment]
tried with different chunk sizes and num_topics, the issue seems to be there always
lda128 = LdaMulticore(corpus=mm,id2word=dic,num_topics=128,chunksize=2000)

python 3.6.2 ----

backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.4.0.2
bleach==2.0.0
boto==2.48.0
bz2file==0.98
certifi==2017.7.27.1
chardet==2.2.1
Cheetah==2.4.4
cloud-init==0.7.5
configobj==4.7.2
configparser==3.5.0
decorator==3.4.0
entrypoints==0.2.3
enum34==1.1.6
functools32==3.2.3.post2
funcy==1.8
future==0.16.0
gensim==2.3.0
html5lib==0.999999999
iniparse==0.4
IPy==0.75
ipykernel==4.6.1
ipython==5.4.1
ipython-genutils==0.2.0
ipywidgets==6.0.0
Jinja2==2.9.6
joblib==0.11
jsonpatch==1.2
jsonpointer==1.9
jsonschema==2.6.0
jupyter-client==5.1.0
jupyter-core==4.3.0
kitchen==1.1.1
Markdown==2.4.1
MarkupSafe==1.0
meld3==1.0.2
mistune==0.7.4
nbconvert==5.2.1
nbformat==4.3.0
nltk==3.2.4
notebook==5.0.0
numexpr==2.6.2
numpy==1.13.1
pandas==0.20.3
pandocfilters==1.4.1
pathlib2==2.3.0
Pattern==2.6
perf==0.1
pexpect==4.2.1
pickleshare==0.7.4
Pillow==2.0.0
policycoreutils-default-encoding==0.1
prettytable==0.7.2
prompt-toolkit==1.0.15
ptyprocess==0.5.2
py==1.4.34
pycurl==7.19.0
Pygments==1.4
pygobject==3.14.0
pygpgme==0.3
pyLDAvis==2.1.1
pyliblzma==0.5.3
pyparsing==1.5.6
Pyro4==4.61
pytest==3.1.3
python-dateutil==2.6.1
pytz==2017.2
pyudev==0.15
pyxattr==0.5.1
PyYAML==3.10
pyzmq==16.0.2
requests==2.6.0
scandir==1.5
scikit-learn==0.18.2
scipy==0.19.1
selectors34==1.2
seobject==0.1
sepolicy==1.1
serpent==1.23
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.9.0
smart-open==1.5.3
supervisor==3.3.1
terminado==0.6
testpath==0.3.1
tornado==4.5.1
traitlets==4.3.2
urlgrabber==3.10
urllib3==1.10.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==2.0.0
yum-metadata-parser==1.1.4

**Comment by abhishekbuyt** [comment]
have also tried a similar set up in python 2.7 , same issue.

**Comment by abhishekbuyt** [comment]
the OMP_NUM_THREADS=1 seems to have solved the high system cpu usage. ( will report after i have run it for a while longer)
but will seeing very little cpu usage. at any point of time only 4 workers are processing out of the 47 that have been spawned.

**Comment by abhishekbuyt** [comment]
Note: for others who come across similar issue. increasing the chunk size helped for me.

i have read in other similar discussions that it might be a data feeding speed issue. For me loading the whole corpus into memory before hand also did not help.  Increasing chunksize from 2000 to something like 10,000 did the trick.

---- though if the chucksize is too large the marging and interprocess communication seems to take more time. so experiment with your set up to get the most fir chunk size. Also higher chunk sizes need more iterations to converge.

**Comment by menshikh-iv** [comment]
@abhishekbuyt try to set different values to `workers` parameter directly.

**Comment by abhishekbuyt** [comment]
@menshikh-iv  Thanks for getting back. The core issue in this thread i think was solved. its the OMP_NUM_THREADS=1 that got rid of the crazy amount of system cpu usage and context switches.

Non utilization of the full available cpu, i was able to mitigate to some extent by playing with the chunksize. It is still not as good as it should be. Have raised another issue for that. 
If you are happy with that resolution. Will go ahead and close this issue. 

Possible improvement. --- may be in LdaMulticore, we can force set the OMP_NUM_THREAD from inside the python code to an appropriate number. cieling(max_cpu/number_of_workers). Or atleast have a msg that alerts the user, of add it to the tutorial ... 
Hopefully help others who run into a similar issue

**Comment by menshikh-iv** [comment]
Set `OMP_NUM_THREADS` directly isn't a good idea (because this influenced to all code that used OpenMP in the backend, for example numpy/scipy).
The warning message isn't needed because this works well if there are not very many cores.
But, you are right, we **must** add this information (about context-switching and OMP) to our documentation.
