### ISSUE TITLE
Gensim reached 5k stars on github!

### ISSUE THREAD

**Issue by menshikh-iv** [RaRe-Technologies/gensim#1587]
Hooray! :bomb: :fire: Gensim reached 5k stars ⭐️ .

Many thanks to our contributors, you are the best!

As a token of appreciation, we're sending a little gift to our contributors (T-shirts, mugs and other things).

**What's needed to receive the gift?**

1. You must be a contributor (at least 1 merged PR to Gensim, Smart-open or Sqlitedict)

2. Write an email to `opensource@rare-technologies.com` with the subject "Gensim 5k*". In the email body please include:
    - A link to your Github account
    - A link to your contribution (PR)
    - Your preferred T-shirt size
    - Your postal address

Here's an **incomplete** list of people who qualify. If I missed you - don't worry, if you are a contributor - send us an email too!

CC: @tmylk @chinmayapancholi13 @gojomo @cscorley @sotte @sebastien-j @parulsethi @mattilyra @bhargavvader @fbarrios @ziky90 @olavurmortensen @mataddy @prakhar2b @markroxor @dsquareindia @larsmans @hyhan @davechallis @dedan @temerick @jayantj @erbas @phdowling @droudy @quole @macks22 @KCzar @josephcc @hajicj @vlejd @mfcabrera @fedelopez77 @svenkreiss @jesterhazy @Arttii @alekol @tpsatish95 @isohyt @anmolgulati @souravsingh @shubhvachher @buma @luispedro @Tiepies @lechatpito @aneesh-joshi @charliejharrison @metalaman @akutuzov

**Comment by menshikh-iv** [comment]
CC: @jesford @dieterbe @langmore @terramars @benrbray @andreasmadsen @jtmcmc @udibr @timclicks @jmonteromunoz @corradomonti @jonmcoe @einon @loisaidasam @luizcavalcanti @shubhamjain74 @ibrahimsharaf @vochicong @zsef123 @moustaki @strongh @jseabold @prb @radixseven @greninja @renaud @dnouri @chyikwei @jbochi @fccoelho @midnightradio @zygmuntz @lukaselmer @ccwang002 @ylhsieh @wcbeard @seanlaw @andrewjlm @manojpandey @amueller @rhnvrm @mon95 @arifahmed1995 @irinagoloshchapova @accraze @lgmoneda @aadityaj @toliwa

**Comment by menshikh-iv** [comment]
Gensim reached 5k stars on github! Look at first message in issue and receive gifts :gift: 

CC: @jquast @ownport @nrhine1 @Digenis @ecederstrand @pswaminathan @bit @jtatum @vrescobar @shoyu63 @and34 @da4089 @pombredanne @ziky90 @VincTheSecond @pombredanne @salilb @asieira @mpenkov @mcrowson @robottwo @robcowie @jsphpl @gojomo @yupbank @nikicc @skibaa @msabramo @andreycizov @kalaidin @petedmarsh @ellimilial @Janrain-Colin @bbbco @cournape @shaform

**Comment by menshikh-iv** [comment]
We filled out our list, for this campaign, the acceptance of applications is over.
Very soon we will start sending out gifts, I'll write about all updates here :hammer:

We'll repeat this next time when we reached 10k :star2:

**Comment by mpenkov** [comment]
Is there a way to check if my application made it? I sent the email, but didn't get a reply.

**Comment by menshikh-iv** [comment]
@mpenkov you are already in list:+1: 
As I see, all persons that sent emails before current day already in list, don't worry :)

I think it will be a good idea to ping concrete persons here when we'll send a gift.

**Comment by alekol** [comment]
A bit late to the party... just saw the thread and sent an email. Any chance of making it? :D

**Comment by menshikh-iv** [comment]
Unfortunately not anymore @alekol

**Comment by loisaidasam** [comment]
Came home to some mail today...

![gensim-swag](https://user-images.githubusercontent.com/213281/33045236-2a0d50c4-ce1a-11e7-8cea-a38f8c2fb531.jpg)

Thanks @piskvorky for the awesome swag, my new fav shirt, for sure!
