### ISSUE TITLE
lda returns TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by aziyamehboob** [RaRe-Technologies/gensim#1591]
hello
i am working on urdu language and want to do topic modeling in it.i followed this link  https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/lda_training_tips.ipynb but i am getting type error. 
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    top_topics = lda.top_topics(corpus, num_words=5)
  File "/home/aziya/.local/lib/python3.5/site-packages/gensim/models/ldamodel.py", line 880, in top_topics
    for l in top_words[:m_index - 1]:
TypeError: only integer scalar arrays can be converted to a scalar index

i even tried it by reducing num of words to 5.this is my code.kindly help me by guiding me where i am doing something wrong.as i am new in gensim and lda.

**Comment by aziyamehboob** [comment]
versions are:
python :3.5.2
gensim:0.13.3
numpy:1.12.0
scipy:0.18.1
Os is linux mint

**Comment by menshikh-iv** [comment]
@aziyamehboob please update your gensim version to latest `2.3.0` - `pip install --upgrade gensim` and this will work correctly.

**Comment by aziyamehboob** [comment]
@menshikh-iv  thank you so much.it worked .
