### ISSUE TITLE
Can not load LineSentencePath 

### ISSUE THREAD

**Issue by yananchen1989** [RaRe-Technologies/gensim#1595]
`sentences =  gensim.models.word2vec.LineSentencePath('/apsarapangu/disk3/yanan/')`

I try to specify the path to read the files under it. There are many files in the path as sentences.
But it comes that `'module' object has no attribute 'LineSentencePath'`.
What's wrong with it ?
Any example code about how to read huge files as sentences ?

**Comment by menshikh-iv** [comment]
Hi @yananchen1989, try `PathLineSentences` not `LineSentencePath`

**Comment by gojomo** [comment]
Note the `PathLineSentences` class comment made an outdated reference to `LineSentencePath` in an example; I've committed a correction.

**Comment by pramod2157** [comment]
I am using gensim version 1.0.1
This version is neighter having PathLineSentences nor LineSentencePath
<ipython-input-5-489c646288b1> in <module>()
----> 1 from gensim.models.word2vec import PathLineSentences

ImportError: cannot import name PathLineSentences

Any version specific requirement?

**Comment by menshikh-iv** [comment]
@pramod2157 update your gensim version please

**Comment by pramod2157** [comment]
upgraded to 2.1(pip install --upgrade gensim)
Still it's not there.
In [2]: import gensim

In [3]: gensim.__version__
Out[3]: '2.1.0'

In [4]: gensim.models.word2vec.LineSentencePath
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-048651babf04> in <module>()
----> 1 gensim.models.word2vec.LineSentencePath

AttributeError: 'module' object has no attribute 'LineSentencePath'

any specific version requirement?

**Comment by pramod2157** [comment]
Upgraded to 3.3.0, even it's not there.
In [3]: from gensim.models import  word2vec

In [4]: word2vec.LineSentencePath
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-cc570074ae40> in <module>()
----> 1 word2vec.LineSentencePath

AttributeError: 'module' object has no attribute 'LineSentencePath'

In [5]: gensim.__version__
Out[5]: '3.3.0'

**Comment by pramod2157** [comment]
Thanks, @menshikh-iv.
 It's working.
