### ISSUE TITLE
gensim import is very slow

### ISSUE THREAD

**Issue by menshikh-iv** [RaRe-Technologies/gensim#1614]
#### Description
Gensim import works very long if you'll have installed Keras+TF, report from [maillist](https://groups.google.com/forum/#!msg/gensim/HY90TZiBiAA/td4fsmwFBgAJ)

#### Steps/Code/Corpus to Reproduce
```
import gensim
```

#### Expected Results
Fast import (less than 0.5 sec) without any `stdout`

#### Actual Results
Slow import (more that 1 sec) + `Using TensorFlow backend.`

**Comment by ibrahimsharaf** [comment]
Hi @menshikh-iv, how can I start solving this?
