### ISSUE TITLE
Why is this required?

### ISSUE THREAD

**Issue by khyrulimam** [RaRe-Technologies/gensim#1626]
I just curious with the gensim code, then i little bit reading the source, but i dont really understand why is  [this expression](https://github.com/RaRe-Technologies/gensim/blob/351bdeff8e4e013d7cea7828b95cb216d215734d/gensim/models/tfidfmodel.py#L156) required? while [this line](https://github.com/RaRe-Technologies/gensim/blob/351bdeff8e4e013d7cea7828b95cb216d215734d/gensim/models/tfidfmodel.py#L154) exists, because (IMHO) however advanced the compiler is [this line](https://github.com/RaRe-Technologies/gensim/blob/351bdeff8e4e013d7cea7828b95cb216d215734d/gensim/models/tfidfmodel.py#L154) will never be executed

**Comment by khyrulimam** [comment]
ah, maybe you mean if normalize value is other than boolean?

**Comment by piskvorky** [comment]
Exactly -- it can be a user-injected function.
