### ISSUE TITLE
Quick-start possible duplicate

### ISSUE THREAD

**Issue by yurkai** [RaRe-Technologies/gensim#1641]
#### Description
Quick-start tutorial possible duplicated: [One](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim%20Quick%20Start.ipynb), [Two](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/gensim%20Quick%20Start.ipynb). 

Second is in tutorials folder and has links from [main](https://github.com/RaRe-Technologies/gensim) page and [tutorials](https://github.com/RaRe-Technologies/gensim/blob/develop/tutorials.md#tutorials) page. Since first one is in the root and also has few more -- instructions how to install gensim and to work with Jupyter notebooks. Both notebooks are equal except 'how to' introduction. It doesn't looks very confusing. Nevertheless there's no link to first one, it appears in list of files only.

**Comment by menshikh-iv** [comment]
Thanks for reporting @yurkai, I think we should rework our "quick start" tutors.

**Comment by arshjat** [comment]
Hi! @menshikh-iv, I think this issue should be closed now since though the right place of the notebook is in gensim/docs/notebooks (as structured so) but It is also seemingly correct to place the quick start at gensim/ for the newcomers.

**Comment by menshikh-iv** [comment]
@arshjat I don' think so, duplicates still here and tutorial not re-worked.

**Comment by arshjat** [comment]
@menshikh-iv  So would it help if the first is removed and the extra 'how-to' introduction moved to the tutorial notebook?

**Comment by menshikh-iv** [comment]
@arshjat I don't think so, this "tutorial system" need full re-work first.
