### ISSUE TITLE
Fix Regex Deprecation Warnings in Python 3

### ISSUE THREAD

**Issue by franklsf95** [RaRe-Technologies/gensim#1646]
#### Description

When I import gensim in Python 3, I get a lot of deprecation warnings like

```
DeprecationWarning: invalid escape sequence \[
  RE_P2 = re.compile("(\n\[\[[a-z][a-z][\w-]*:[^:\]]+\]\])+$", re.UNICODE)
```

which is a 2 to 3 issue which I believe can be fixed by adding a raw flag before the string.

#### Steps/Code/Corpus to Reproduce

On Python 3...

```
import gensim
```

Observe the warnings.

#### Expected Results

No deprecation warnings.

#### Actual Results

Deprecation warnings.

#### Versions

Python 3.6.3, gensim 3.0.0

**Comment by menshikh-iv** [comment]
Thanks for report @franklsf95

**Comment by franklsf95** [comment]
@menshikh-iv I can fix these warnings and put up a pull request, if you don't mind?

**Comment by menshikh-iv** [comment]
Of course @franklsf95, feel free to contribute :+1:
