### ISSUE TITLE
word2vec.score returns  negative values

### ISSUE THREAD

**Issue by Runingtime** [RaRe-Technologies/gensim#1657]
Hi, I've just trained a word2vec model on a Chinese corpus and the function _score_ seems to not work. It always returns a negative value given a sentence. Is this a bug or it just can't deal with such a  corpus? 
Thanks in advance!

**Comment by menshikh-iv** [comment]
Hi @Runingtime, thanks for the report.
Please share your code (for training/scoring) and dataset OR fitted model and code for scoring (it's needed for reproducing your problem).

**Comment by Runingtime** [comment]
@menshikh-iv thank you for the reply. But I can't upload the dataset or fitted model because they are two large (500+MB). I paste my code and sample text here, hope it helps :)
For training:
```
    train_corpus = []
    num = 0
    for idx, row in train_data.iterrows():
        print(num)
        num += 1
        train_corpus.append(row.title.split())
        train_corpus.extend([rb.split() for rb in re.split('[。！？]', row.body) if rb != ''])

    model = Word2Vec(train_corpus, size=128, sg=1, workers=8, min_count=1, hs=1, negative=0)
    model.save('embeddings')
```

For scoring:
```
from gensim.models import Word2Vec 
model = Word2Vec.load('embeddings') 
print(model.score(["天气 炎热 ，不 利于 游客 出游 。 因此 ， 大多人 选择 避暑 。".split()]))
```
output>>[-736.7088623]

Sample text:
`工人 失足 摔伤   贵州 长顺 消防 成功 营救	图为 救援 现场 7 月 12 日 17 时 21 分 ， 贵州省 长顺县 消防 接到 群众 报警 称 : 在 长顺县 潮顺 洗车场 旁边 的 建筑工地 上 有 一名 工人 在 作业 时 不慎 坠入 房间 中 ， 房间 四周 无 门窗 ， 无法 将 工人 救出 ， 请求 消防队 前往 救援 。 接到 报警 后 ， 消防官兵 迅速 出动 前往 救援 。 17 时 28 分 ， 官兵 到达 现场 后 发现 一名 工人 在 作业 时 失足 踩 空 ， 落入 一个 四周 无 门窗 的 房间内 ， 腰部 受伤 无法 正常 行动 。 根据 现场 情况 ， 消防官兵 立即 展开 救援 ， 由 两名 官兵 下 到 屋内 使用 多功能 担架 固定 并 保护 好 被困 人员 ， 再 与 周围 群众 配合 使用 绳索 将 被困 人员 救出 。 经过 一个 小时 左右 的 紧张 救援 ， 18 时 32 分 ， 被困 人员 被 成功 救出 并 移送 现场 医护人员 。 险情 处置 完毕 后 ， 消防官兵 随即 撤离 现场 。`

**Comment by menshikh-iv** [comment]
@Runingtime  as I understand, the score is "log probability", this means that this value in the range (-inf, +inf) and a negative value is OK (it isn't a bug).

**Comment by menshikh-iv** [comment]
This isn't a bug, for this reason I close this PR.

**Comment by gojomo** [comment]
That's my understanding as well; negative score is valid.

**Comment by Runingtime** [comment]
I see. Thank you! @menshikh-iv @gojomo

**Comment by mataddy** [comment]
yep, logs :-)
