### ISSUE TITLE
model_trimmed_post_training not set on `load()`ed older models

### ISSUE THREAD

**Issue by gojomo** [RaRe-Technologies/gensim#1659]
As seen at: https://stackoverflow.com/questions/46985320/gensim-word2vec-online-training-attributeerror-word2vec-object-has-no-att/46987193#46987193

User received an error because `model_trimmed_post_training` was not present on a model. 

Either `load()` should impute this when missing, or some less-clunky way of tracking stripped-down model state be used, perhaps by testing for actual available properties, rather than adding another flag to be maintained.

**Comment by piskvorky** [comment]
@menshikh-iv @manneshiva is this still unresolved?

**Comment by menshikh-iv** [comment]
I think that this is already resolved, but I can't check, because we have no original model / even gensim version that was used for training.

**Comment by menshikh-iv** [comment]
**UPD** I checked, the last version **without** `model_trimmed_post_training` was `0.13.3`, I save `0.13.3`, load in `3.4.0` and train again - all works fine (without any attribute errors). 

The issue looks fixed, I close it.

**Comment by piskvorky** [comment]
Thanks!
