### ISSUE TITLE
Turn off support of Google Style docstrings

### ISSUE THREAD

**Issue by anotherbugmaster** [RaRe-Technologies/gensim#1663]
**All docstrings should be refactored first**

To prevent contributors from using Google Style docstrings, we need to set

`napoleon_google_docstring = False`,

[like explained here](https://samnicholls.net/2016/06/15/how-to-sphinx-readthedocs/).

**Comment by kaustubhhiware** [comment]
Can I take this up @menshikh-iv @anotherbugmaster ?

**Comment by menshikh-iv** [comment]
@kaustubhhiware no, because we didn't finished with docstrings yet

**Comment by menshikh-iv** [comment]
@jxub we'll make it after finishing all docstrings (that happens soon, I hope)
