### ISSUE TITLE
Refactor API reference gensim.scripts

### ISSUE THREAD

**Issue by anotherbugmaster** [RaRe-Technologies/gensim#1665]
**Check this PR for the soon-to-be-deprecated modules:** #1618 

Documented submodules:

- [ ] `__init__.py`
- [x] `glove2word2vec.py`
-  ~~`make_wiki.py`~~
-  ~~`make_wiki_lemma.py`~~
-  ~~`make_wiki_online.py`~~
-  ~~`make_wiki_online_lemma.py`~~
-  ~~`make_wiki_online_nodebug.py`~~
- [ ] `make_wikicorpus.py`
- [x] `word2vec2tensor.py`
- [x] `word2vec_standalone.py`
- [x] `segment_wiki.py`

**Comment by menshikh-iv** [comment]
UPD: almost done in #1792, the latest thing that should be fixed is `make_wikicorpus`, but this is possible only with refactoring & breaks backward compatibility.

**Comment by menshikh-iv** [comment]
for reason mentioned in my previous comment, I close issue
