### ISSUE TITLE
Refactor API reference gensim.sklearn_api

### ISSUE THREAD

**Issue by anotherbugmaster** [RaRe-Technologies/gensim#1667]
**Check this PR for the soon-to-be-deprecated modules:** #1618 

Documented submodules:

- [ ] `__init__.py`
- [x] `atmodel.py`
- [x] `d2vmodel.py`
- [x] `hdp.py`
- [x] `ldamodel.py`
- [x] `ldaseqmodel.py`
- [x] `lsimodel.py`
- [x] `phrases.py`
- [x] `rpmodel.py`
- [x] `text2bow.py`
- [x] `tfidf.py`
- [x] `w2vmodel.py`

**Comment by gyanesh-m** [comment]
@menshikh-iv Hi, in [tfidf.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/sklearn_api/tfidf.py#L19) the parameters mentioned are the same as done for [tfidmodel.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/tfidfmodel.py#L221) . So should I add a reference to that file in the notes section or mention all the parameters again for tfidf.py ?

**Comment by menshikh-iv** [comment]
@gyanesh-m this already in WIP too in #1895, sorry.
Now, some files remain from `gensim.models`, you can try you can try your hand at this task (for example https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/atmodel.py, https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/hdpmodel.py, etc).

**Comment by gyanesh-m** [comment]
@menshikh-iv Ok, no problem. I will get started with the remaining ones.

**Comment by menshikh-iv** [comment]
Related PR #1895
