### ISSUE TITLE
Refactor API reference gensim.models.wrappers

### ISSUE THREAD

**Issue by anotherbugmaster** [RaRe-Technologies/gensim#1670]
**Check this PR for the soon-to-be-deprecated modules:** #1618 

Documented submodules:

- [ ] `__init__.py`
- [x] `dtmmodel.py`
- [x] `fasttext.py`
- [x] `ldamallet.py`
- [x] `ldavowpalwabbit.py`
- [x] `varembed.py`
- [x] `wordrank.py`

**Comment by menshikh-iv** [comment]
Fixed in #1859
