### ISSUE TITLE
Refactor API reference gensim.corpora

### ISSUE THREAD

**Issue by anotherbugmaster** [RaRe-Technologies/gensim#1671]
**Check this PR for the soon-to-be-deprecated modules:** #1618 

Documented submodules:

- [ ] `__init__.py`
- [x] `bleicorpus.py`
- [x] `csvcorpus.py`
- [x] `dictionary.py`
- [x] `hashdictionary.py`
- [x] `indexedcorpus.py`
- [x] `lowcorpus.py`
- [x] `malletcorpus.py`
- [x] `mmcorpus.py`
- [ ] ~~`shared_corpus.py`~~
- [x] `svmlightcorpus.py`
- [x] `textcorpus.py`
- [x] `ucicorpus.py`
- [x] `wikicorpus.py`

**Comment by gyanesh-m** [comment]
Hi, I would like to help with the remaining ones. Can I take this up ?

**Comment by menshikh-iv** [comment]
@gyanesh-m this is almost done. Last thing - MmCorpus (+reader & writer), but this will be annotated after #1825 will be merged.

**Comment by gyanesh-m** [comment]
@menshikh-iv Ok, no problem. What about  #1666 and #1667 ? Do anyone of these need any help ?

**Comment by menshikh-iv** [comment]
@gyanesh-m #1666 WIP by @CLearERR, pick any model from #1667 that isn't in numpy-style

**Comment by menshikh-iv** [comment]
Fixed in #1729,  #1814 and  #1835
