### ISSUE TITLE
rethink multiprocessing

### ISSUE THREAD

**Issue by chriswi93** [RaRe-Technologies/gensim#1687]
#### Description
I've noticed gensim uses num_cores() - 1 processes for multiprocessing. 
As far as I know from java programming a process doesn't consume any cpu cycles when it is in waiting mode. So when I start 4 processes on a machine which has 4 cores and the main process is waiting for the other processes (process.join() in python?), your machine should be able to parallelize 4 tasks in 4 processes. 

I am not sure about it, because I am no expert in synchronization and multiprocessing - but I can tell you my observations. When I use 3 processes on a machine with 4 cores, cpu usage is roughly at 80 percent. Actually when I use 4 processes on the same machine, cpu usage is exactly at 100 percent.

You should make your own benchmarks, but maybe gensim could effectively use more resources as it is currently doing.

**Comment by piskvorky** [comment]
The main process is typically preparing data for the works, and merging their results. In some algorithms (which model are you talking about?), the main process is actually the bottleneck.

Additionally, each worker may use multiple cores via threading.

Unless you have more concrete suggestions / benchmarks, I'll close this for now. You can always set a higher number of workers manually.
