### ISSUE TITLE
any2unicode in utils.py

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [RaRe-Technologies/gensim#1691]
As `any2unicode` cannot handle floats, I changed it to 

```
def any2unicode(text, encoding='utf8', errors='strict'):
    """Convert a string (bytestring in `encoding` or unicode), to unicode."""
    if isinstance(text, unicode):
        return text
    if isinstance(text, float):
        return unicode(bytearray(struct.pack("f", text)), encoding, errors=errors)
    else:
        return unicode(text, encoding, errors=errors)
```

**Comment by horpto** [comment]
@ErfolgreichCharismatisch Maybe you can just create a PR? It's more closer to code.

**Comment by ErfolgreichCharismatisch** [comment]
What is a pr?

**Comment by piskvorky** [comment]
`any2unicode` is not meant to handle floats (see its docstring).

**Comment by ErfolgreichCharismatisch** [comment]
What is a docstring?

**Comment by piskvorky** [comment]
https://www.google.com/search?q=docstring

**Comment by ErfolgreichCharismatisch** [comment]
Right, I changed the docstring in any2unicode. Now it can handle floats.

**Comment by ErfolgreichCharismatisch** [comment]
The problem was, that gensim detected a float and the program crashed. But it did not point to the line of error.

**Comment by piskvorky** [comment]
@ErfolgreichCharismatisch if you're passing floats where strings are expected, that points to some error in your program's logic. A crash (exception) is the proper behaviour.

A proper solution is to figure out why you have floats where there should be strings, and fix that.
