### ISSUE TITLE
Overflow Error in LDA

### ISSUE THREAD

**Issue by stephenhky** [RaRe-Technologies/gensim#1692]
I report this issue due to an issue from `shorttext`: https://github.com/stephenhky/PyShortTextCategorization/issues/28

When on iPython, on enters

```
import shorttext
trainclassdict = shorttext.data.nihreports(sample_size=None)
topicmodeler = shorttext.generators.LDAModeler()
topicmodeler.train(trainclassdict, 128)
```

If the keras backend was TensorFlow, the following message appears:

```
Error message:
/lib/python2.7/site-packages/gensim/models/ldamodel.py:535: RuntimeWarning: overflow encountered in exp2
perwordbound, np.exp2(-perwordbound), len(chunk), corpus_words
```

But there is no warning for Theano.

However, this line is not really running the inferrence, but logging the perplexity in the step. And this calculation should have nothing to do with keras. Why does it matter if one is using TensorFlow or Theano?

https://github.com/RaRe-Technologies/gensim/blob/c583b28ff3039d18feff70cc2f1e518ad2c03f42/gensim/models/ldamodel.py#L535

**Comment by menshikh-iv** [comment]
> However, this line is not really running the inference

Yes, the hugest part of inference already calculated for this moment, overflow from `np.exp2`. \

I'm very surprised that you have different behavior with tf/theano, we used theano dtype only for SharedCopus
https://github.com/RaRe-Technologies/gensim/blob/e667069e90136c7d7c814e5d75ec8832e45805d1/gensim/corpora/sharded_corpus.py#L37-L44
Keras used for one method in KeyedVectors https://github.com/RaRe-Technologies/gensim/blob/772dae83a81450d2a3eb8f6a0e5b999bf55ae496/gensim/models/keyedvectors.py#L859-L875

As I see, this is completely unrelevant for your example, please ignore this warning.

**Comment by stephenhky** [comment]
Thanks!
