### ISSUE TITLE
Missplaced logging

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#1706]
Running the `segment_wiki.py` scripts prints:

```bash
$ time python -m gensim.scripts.segment_wiki -f /data_hdd/wiki/enwiki-latest-pages-articles.xml.bz2 -o /data_hdd/wiki/enwiki-latest.json.gz

No handlers could be found for logger "gensim.models.doc2vec"

2017-11-10 22:21:25,334 : MainProcess : INFO : running /home/radim/workspace/gensim/gensim/scripts/segment_wiki.py -f /data_hdd/wiki/enwiki-latest-pages-articles.xml.bz2 -o /data_hdd/wiki/enwiki-latest.json.gz
2017-11-10 22:24:40,174 : MainProcess : INFO : Processed #100000 articles
```

which is a bug. The doc2vec module should not log anything on import -- it should behave the same as word2vec, or any other gensim module.

**Comment by pranaydeep-af** [comment]
@piskvorky @menshikh-iv would you want the logs to simply be removed or be relocated? I suspect these are the [lines](https://github.com/RaRe-Technologies/gensim/blob/74dae4ddc2de36b8e656382410ad75ee747374c4/gensim/models/doc2vec.py#L75) causing the issue?

**Comment by menshikh-iv** [comment]
@pranaydeep-af I don't think that problem in this line.
Logging messages should stay as is, but we don't want to see this message when we import something - `No handlers could be found for logger "...."`

**Comment by pranaydeep-af** [comment]
@menshikh-iv I think logging in doc2vec outside any function is the cause of the error. As soon as the user imports the doc2vec file, the logs are executed. In contrast to other modules like word2vec where logging is done only after the import and during object creation. Here are the corresponding [lines](https://github.com/RaRe-Technologies/gensim/blob/74dae4ddc2de36b8e656382410ad75ee747374c4/gensim/models/word2vec.py#L513) in word2vec. 
I may be wildly wrong. But I feel this is the cause.

**Comment by menshikh-iv** [comment]
@pranaydeep-af  you can check it easily (reproduce original problem, remove this lines & try to reproduce again)

**Comment by pranaydeep-af** [comment]
@menshikh-iv Commenting out lines [1](https://github.com/RaRe-Technologies/gensim/blob/09672b369b2ec94a06581efd060be20662d7006c/gensim/models/doc2vec.py#L75l) and [2](https://github.com/RaRe-Technologies/gensim/blob/09672b369b2ec94a06581efd060be20662d7006c/gensim/models/doc2vec.py#L77) removes the issue for doc2vec. Also commenting out the corresponding lines from the fasttext module removes the issue for fasttext too.

**Comment by pranaydeep-af** [comment]
Should I relocate the logs to a more similar structure as in word2vec and other modules?

**Comment by menshikh-iv** [comment]
@pranaydeep-af yes

**Comment by piskvorky** [comment]
(another option is a one-time `warnings.warn` message, but it's best to be consistent in how we do this in other modules)
