### ISSUE TITLE
model.syn0norm[0] TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ahmedahmedov** [RaRe-Technologies/gensim#1716]
#### Description
Error while extracting normalized vectors from syn0norm
model.syn0norm[0] TypeError: 'NoneType' object is not subscriptable

#### Steps/Code/Corpus to Reproduce

```
import gensim

model = gensim.models.KeyedVectors.load_word2vec_format(config.GOOGLE_WORD2VEC_MODEL, binary=True)
print(model.syn0norm[0])
```

#### Expected Results
the first vectors in the syn0norm

#### Actual Results
model.syn0norm[0] TypeError: 'NoneType' object is not subscriptable

#### Versions
Darwin-17.0.0-x86_64-i386-64bit
Python 3.5.4 |Continuum Analytics, Inc.| (default, Aug 14 2017, 12:43:10) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
NumPy 1.13.3
SciPy 1.0.0
gensim 2.3.0
FAST_VERSION 1

**Comment by ahmedahmedov** [comment]
So, the issue is intermittent. Right after I submitted the issue to GitHub, it worked without any problems. Then again, when I reset the python console, and rerun the script I faced the same problem.

**Comment by menshikh-iv** [comment]
Hi @ahmedahmedov, `syn0norm` is the normalized version of `syn0`, it is not stored to save your memory, you have 2 variants:
- use `syn0`
- call `model.init_sims` (better) or `model.most_similar*` after loading, `syn0norm` will be initialized after this call.

**Comment by ahmedahmedov** [comment]
@menshikh-iv Great, thanks. I realized it later.
