### ISSUE TITLE
matutils.unitvec returns vector with different dtype from input vector

### ISSUE THREAD

**Issue by jayantj** [RaRe-Technologies/gensim#1722]
#### Description
`matutils.unitvec` can return a unitvector of a different dtype from the input vector if the input dtype isn't `np.float`.
#### Steps/Code/Corpus to Reproduce
```python
from gensim import matutils
import numpy as np

input_vector = np.random.uniform(size=(100,)).astype(np.float32)
print(input_vector.dtype)
>>> float32

unit_vector = matutils.unitvec(input_vector) 
print(unit_vector.dtype)
>>> float64
```

This seems like mostly an internally used method, so it's probably not super-important but it does lead to some surprises while developing.

**Comment by piskvorky** [comment]
Not a part of the method's contract, but I'd consider it a surprising behaviour too. Let's make the return type consistent with the input type.
