### ISSUE TITLE
Add button for documentation check

### ISSUE THREAD

**Issue by anotherbugmaster** [RaRe-Technologies/gensim#1725]
Scikit-learn developers are using [neat userscript](http://scikit-learn.org/stable/developers/tips.html#viewing-the-rendered-html-documentation-for-a-pull-request) to view documentation of a given PR. I think it would be nice for Gensim to have something like that too.

![image](https://user-images.githubusercontent.com/3992246/32981685-a326c82c-cc9a-11e7-9f08-c818247afe0d.png)

**Comment by menshikh-iv** [comment]
Thanks @anotherbugmaster, I think it's possible in future (but soon).

**Comment by anotherbugmaster** [comment]
Here's the gist:
https://gist.github.com/menshikh-iv/bfe9b8ef2db10e9511aa9fe5935a7289

I think we can close this. :)

**Comment by menshikh-iv** [comment]
Resolved in #1807
