### ISSUE TITLE
Encoding problems when saving/loading dictionary as text

### ISSUE THREAD

**Issue by ifalk** [RaRe-Technologies/gensim#173]
When using Dictionary.save_as_text(), vocabulary words are utf-8 encoded.

However, when reading in the dictionary with Dictionary.load_from_text() gensim uses open (where the encoding cannot be specified) and as a consequence for example French accentuated words end up wrongly encoded and can not be identified using 

```
word in dictionary.token2id
```

**Comment by gauravkoradiya** [comment]
how to resolve it?

**Comment by piskvorky** [comment]
@gauravkoradiya this ticket is old and resolved. If you have an issue, open a new ticket, following the issue template.
