### ISSUE TITLE
Doc2Vec most_similar not ranking docs proprerly

### ISSUE THREAD

**Issue by My3VM** [RaRe-Technologies/gensim#1735]
#### Description
I am on a task to rank a bunch of documents (1000~2000) against set of keyphrases (n grams) associated with given subject.
These are the steps being taken:

1. Extracted keyphrases for all the candidate documents.
2. Trained Gensim's Doc2Vec with list of keyphrases generated at step 1. Each doc has 20-30 keyphrases (2 - 4 grams each)
3. Inferred the target keyphrase vector (for the subject) using the model. Calculate most similar

Upon checking the resultant documents, I find that none of the key phrases from the subject were found in the top documents. Ironically, some of the documents, (which my another frequentist match approach algorithm) find most relevant are ranked negatively by doc2vec.

#### Steps/Code/Corpus to Reproduce

Example:
```
documents = []
for item in resultTextData:
    keyphrases = item["meta_keyphrases"].lower().split(",")
       
    id = []
    id.append(str(item["text_id"]))
    documents.append(TaggedDocument(keyphrases,id))

model = Doc2Vec(size=50, window=8, min_count=5, workers=4, dm=0, negative=0,iter=100)
model.build_vocab(documents)
model.train(documents, total_examples=model.corpus_count,epochs=model.iter)

#inference
kp = model.infer_vector(targetDocument)
# sims = model.docvecs.most_similar([kp],topn=1150)  # gives you top 10 document tags and their cosine similarity
sims = model.docvecs.most_similar(positive=[model.infer_vector(targetDocument)])  # gives you top 10 document tags and their cosine similarity
print "sims", sims
```

**Comment by menshikh-iv** [comment]
@My3VM For quality d2v model needs a lot of data, 1000-2000 documents may not be enough (depends on the length of the document). Also, you can try to change parameters (more iterations for `infer_vector`, enlarge `size` of embedding, smaller window, etc).

For your task, I propose to use LsiModel - fast, simple and very often works nicely.

P/S: this question more suitable for [maillist](https://groups.google.com/forum/#!forum/gensim)
