### ISSUE TITLE
Travis timeout of tests

### ISSUE THREAD

**Issue by souravsingh** [RaRe-Technologies/gensim#1740]
Currently, Travis times out due to the max time limit for the jobs. The time out error can be seen here- https://travis-ci.org/RaRe-Technologies/gensim/jobs/307547006

I suggest adding ``travis_wait`` to increase the max time limit.

**Comment by menshikh-iv** [comment]
I disagree with you:
- Travis sometimes freezes, timeout is a good way to handle this situation.
- Tests in gensim shouldn't be very slow, that's bad for us and for our contributors (nobody wants to wait several hours). Our current time is [~25min for Travis job](https://travis-ci.org/RaRe-Technologies/gensim/builds/306471401?utm_source=github_status&utm_medium=notification) and [~15 min for Appveyor](https://ci.appveyor.com/project/piskvorky/gensim-431bq/build/1.0.859). It would be desirable, that it worked faster (without loss of a test coverage). Compare this time with your results and fix your tests (I see that almost all doesn't pass correctly right now when you fix them, time will be much better:+1: )

**Comment by souravsingh** [comment]
Oh. The time out error in Travis threw me off a bit, since it wasn't able to fully finish the tests for py3. Thanks for the guidance.
