### ISSUE TITLE
total_vec don't exists

### ISSUE THREAD

**Issue by set92** [RaRe-Technologies/gensim#1746]
I wanted to save the most important vectors or similar words, but I tried to cut the length of the embeddings using `model.save_word2vec_format('try.c.w2v', total_vec=10000)` but it says total_vec doesn't exists, but it's in the [documentation](https://radimrehurek.com/gensim/models/keyedvectors.html#gensim.models.keyedvectors.KeyedVectors.save_word2vec_format).

**Comment by menshikh-iv** [comment]
Hi @set92, please upgrade your gensim version `pip install -U gensim`, this feature comes from `2.1.0`.
FYI - documentation **always** for latest version (right now - for `3.1.0`)

**Comment by set92** [comment]
Im in 3.1.0, and before I was in 3.0.1 but I get the same error. I load a model using  `model = gensim.models.Word2Vec.load('../../models/model_w2v_medic_v2.bin')` and then I try to save it with `model.save_word2vec_format('try.c.w2v', total_vec=10000)` and it gives the error `TypeError: save_word2vec_format() got an unexpected keyword argument 'total_vec'`

**Comment by menshikh-iv** [comment]
@set92 you called [this one](https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec.save_word2vec_format) (method of Word2Vec class), but add link to method of KeyedVectors class.
Please try `model.wv.save_word2vec_format('try.c.w2v', total_vec=10000)`

**Comment by set92** [comment]
Yes, you are right, I forgot about wv in `model.wv.save_word2vec_format`, thanks a lot.

**Comment by piskvorky** [comment]
@menshikh-iv what's the difference between `model.save_word2vec_format` and `model.wv.save_word2vec_format`? That's some strange API, we should fix that.

**Comment by menshikh-iv** [comment]
@piskvorky we should remove this deprecated methods, don't fix.

**Comment by piskvorky** [comment]
Sure, but how can this even happen? How did they get out of sync?

**Comment by menshikh-iv** [comment]
@piskvorky 

> I was under the impression the deprecated version is just an alias of the new one (until we remove it for good).

From the beginning, that's exactly the way it was (i.e. full sync of interfaces), but later - https://github.com/RaRe-Technologies/gensim/pull/1256 this PR added `total_vec` param to `KeyedVector.save_word2vec_format` https://github.com/RaRe-Technologies/gensim/pull/1256/files#diff-741f69634ff2e1b2c4ce544e0d82a1e6R121 and doesn't update "deprecated" `Word2Vec.save_word2vec_format`

**Comment by piskvorky** [comment]
Yeah, time to remove it.

Where do we keep the list of deprecated things + their schedule for removal (version)?

**Comment by menshikh-iv** [comment]
@piskvorky I have no idea, I assume that there is no such list (all these "deprecations" make before I came). 

The first time, docstrings "forwarding" was added in https://github.com/RaRe-Technologies/gensim/pull/1251 (April 11), explicit deprecation added in https://github.com/RaRe-Technologies/gensim/pull/1274 (May 3), that looks like a fix for the previous PR.

**Comment by menshikh-iv** [comment]
My plans are release minor (feature version) on next week and major (with change package structure, removing outdated stuff, etc) in next year (probably in January).

**Comment by piskvorky** [comment]
Let's append a clear deprecation plan with each deprecation: in which version will the code be actually removed? (3.2.0 etc)

And then before each release `grep` for deprecations and actually remove the scheduled ones.
