### ISSUE TITLE
Gensim 3.1.0 Phrase loader incompatible with older models due to introduction of common_terms

### ISSUE THREAD

**Issue by dldx** [RaRe-Technologies/gensim#1751]
I have a Phrases model that was computed using Gensim 2.2.0 but because of changes in 3.1.0 (I believe), I cannot load it anymore. This is the error I get:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<timed exec> in <module>()

~/Stuff/Sources/anaconda3/envs/nlp/lib/python3.6/site-packages/gensim/models/phrases.py in __init__(self, phrases_model)
    546         self.delimiter = phrases_model.delimiter
    547         self.scoring = phrases_model.scoring
--> 548         self.common_terms = phrases_model.common_terms
    549         corpus = self.pseudocorpus(phrases_model)
    550         self.phrasegrams = {}

AttributeError: 'Phrases' object has no attribute 'common_terms'
```

Cheers!

**Comment by menshikh-iv** [comment]
Thanks for report @dldx 

ping @alexgarel, can you fix load method in phrases?

**Comment by alexgarel** [comment]
hi @menshikh-iv, I can do it. But should I base on master or develop ?

**Comment by menshikh-iv** [comment]
@alexgarel `develop` please :)

**Comment by dldx** [comment]
Thanks for the quick fix!

**Comment by Raghuvar** [comment]
Had the same issue. Helped me a bit, still heading around.

**Comment by menshikh-iv** [comment]
@Raghuvar please update your gensim version to latest

**Comment by Raghuvar** [comment]
@menshikh-iv Done it and got rid of the issues. Now it's working great. 
Anyway, Thanks @menshikh-iv

**Comment by menshikh-iv** [comment]
@Raghuvar say thanks to @alexgarel (it's a fix from him) :)
