### ISSUE TITLE
ipython notebook starts ipython3 kernel also when choosing python2 Kernel

### ISSUE THREAD

**Issue by rbahumi** [RaRe-Technologies/gensim#1762]
#### Description
ipython notebook starts ipython3 kernel also when choosing python2 Kernel

#### Steps/Code/Corpus to Reproduce
Example:
1. Build a docker and login to it.
2. Open a new jupyter notebook with python2 kernel
3. Try running code that is only suitable to python2 syntax like: 
```
print 1
```

4. On Ubuntu you can also run:
```    
ps -ef | grep jupyter
```
and verify the new notebook was started with ipython3 kernel

#### Expected Results
The new notebook will be ran with ipython2 kernel

#### Actual Results
The new notebook will be ran with ipython2 kernel

### Cause:
Both Kernels has the same command - _python_ as the first _argv_ parameter:
```
root@273133a334a2:/# cat /usr/local/share/jupyter/kernels/python3/kernel.json
{
 "argv": [
  "python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}root@273133a334a2:/# cat /usr/local/share/jupyter/kernels/python2/kernel.json
{
 "display_name": "Python 2",
 "language": "python",
 "argv": [
  "python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ]
}
```

### Solution
Running the following commands (as described [here](https://github.com/jupyter/notebook/issues/2563)):
```
root@273133a334a2:/# ipython2 kernel install
Installed kernelspec python2 in /usr/local/share/jupyter/kernels/python2
root@273133a334a2:/# ipython3 kernel install
Installed kernelspec python3 in /usr/local/share/jupyter/kernels/python3
```
 Fixes the issue:
```
root@273133a334a2:/# cat /usr/local/share/jupyter/kernels/python2/kernel.json
{
 "display_name": "Python 2",
 "language": "python",
 "argv": [
  "/usr/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ]
}root@273133a334a2:/# cat /usr/local/share/jupyter/kernels/python3/kernel.json
{
 "argv": [
  "/usr/bin/python3",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}
```

### Actions Required:
Add the following lines to the Dockerfile:
```
RUN ipython2 kernel install
RUN ipython3 kernel install
```
I'll submit a Pull request containing these changes soon

**Comment by menshikh-iv** [comment]
Thanks for report @rbahumi: +1: we'll wait for the fix from you.

**Comment by rbahumi** [comment]
Sure, thanks.

Here is the fix:
https://github.com/RaRe-Technologies/gensim/pull/1764

I managed to build a new Docker image and verified the issue was resolved.

Please note that I added my changes right before the _check_fast_version.py_ script.
It seemed appropriate to me (and also it was much faster to build a new docker image because of the cache) - but maybe you'll decide it should be added somewhere else in the Dockerfile.
