### ISSUE TITLE
why HDP model topic is always 150?

### ISSUE THREAD

**Issue by data2world** [RaRe-Technologies/gensim#1784]
#### Description
**I use hdp model to get topics，I want to get all topics 。so I set `num_topic = -1`, but get topics number are alway 150。I found some reason [here](https://stackoverflow.com/questions/31543542/hierarchical-dirichlet-process-gensim-topic-number-independent-of-corpus-size/31847553), but it did not working for me。so, how I get all topics**

TODO: change commented example

#### Steps/Code/Corpus to Reproduce

```
import os
import re
import jieba
import codecs
import numpy as np
from gensim.corpora import Dictionary
from gensim.models import hdpmodel

def hdp_train(doc_path, stop_path):
    stop_file = codecs.open(stop_path, 'r', 'utf-8')
    stopwords = [line.strip() for line in stop_file]
    stop_file.close()

    doc_file = codecs.open(doc_path, 'r', 'utf-8')
    documents = [document.strip() for document in doc_file]
    doc_file.close()

    word_counts = []
    for document in documents:
        word_counts_id = []
        tokens = jieba.cut(document)
        for word in tokens:
            if len(word) > 1 and not re.search('[0-9]', word) and word not in stopwords:
                word_counts_id.append(word)
        word_counts.append(word_counts_id)

    dic = Dictionary(word_counts)
    corpus = [dic.doc2bow(i) for i in word_counts]

    return dic, corpus

yuzhang_dic, yuzhang_corpus = hdp_train("data/yuzhang.txt", "data/stopWord.dic")
yuzhang_hdp_model = hdpmodel.HdpModel(corpus=yuzhang_corpus, id2word=yuzhang_dic)
yuzhang_hdp_model.print_topics(num_topics=-1)
```

#### Expected Results
I want get all topics

#### Actual Results
but HdpModel init `T=150`，so `num_topics=-1` get 150 ?。please give some links how do I get all topics (Forgive my poor English.)

**Comment by menshikh-iv** [comment]
Hi @data2world,
Please share your training code and dataset for reproducing your problem.

**Comment by menshikh-iv** [comment]
**UPD**  please share your `"data/yuzhang.txt"`, `"data/stopWord.dic"` @data2world

**Comment by data2world** [comment]
[yuzhang.txt](https://github.com/RaRe-Technologies/gensim/files/1559062/yuzhang.txt)

[stopWord.txt](https://github.com/RaRe-Technologies/gensim/files/1559065/stopWord.txt)

**Comment by data2world** [comment]
github can not surport `.dic`

**Comment by menshikh-iv** [comment]
I checked, HDP **always** produce `T` number of topics (by default, `T=150`, for this reason, you always receive this number of topics)

But you can order it by "importance", and use only top_K topics, this demonstrated in https://stackoverflow.com/a/44393919/8001386 (I do not like it very much, but this is an adequate selection option)
