### ISSUE TITLE
Add contributor information to developers wiki page

### ISSUE THREAD

**Issue by datapythonista** [RaRe-Technologies/gensim#1786]
#1604 mentions that the developer documentation is outdated. Besides updating it, I think there is some information missing for contributors.

The main things I think are missing:
- How to set up a developer environment
- How to build Gensim
- How to send a pull request following the git flow described in the page

While the information provided seems appropriate for core developers of the project, contributors sending pull requests would in my opinion require those additional sections.

Regarding the developer environment, I don't see a requirements.txt (or requirements-dev.txt) file that can be used to install it. I guess there are also other project requirements for the project, and it'd be nice to know how contributors are expected to set up those things.

About the git flow, I think it should be obvious for open source contributors how to send a pull request to master. But given that the pull requests need to be sent to develop, I think it'd be useful to have a short documentation on how the whole flow looks like. It's nicely documented for core developers who can push to the repo, but not for contributors sending pull requests.

May be it could be a good idea to have separate pages for core developers and external contributors. And may be move this content to the CONTRIBUTING.md page.

**Comment by menshikh-iv** [comment]
Thanks for report @datapythonista, I regularly update doc, but more in "how to release" part.

I will try to fix this issue ASAP.
