### ISSUE TITLE
open('aclImdb/alldata-id.txt', encoding='utf-8') doesn't work in Python 2.x 

### ISSUE THREAD

**Issue by gitclem** [RaRe-Technologies/gensim#1789]
In file doc2vec-IMDB.ipynb, this statement is not supported in Python 2.x but is in Python 3.x

`with open('aclImdb/alldata-id.txt', encoding='utf-8') as alldata:
`

This works in Python 2.7:

`import codecs
`
`with codecs.open('aclImdb/alldata-id.txt', encoding='utf-8') as alldata:
`

**Comment by menshikh-iv** [comment]
Thanks for report @gitclem, need to replace all `open` calls to `smart_open` in notebooks to avoid this problem (`encoding` argument appeared only in python3).

**Comment by sharanry** [comment]
hey, I am new here. Can i take this up?

**Comment by menshikh-iv** [comment]
@sharanry of course, feel free to contribute :+1:

**Comment by vasu-dev** [comment]
hey ,
what the progress on the issue, is no one is working i'll like to take this up.

**Comment by menshikh-iv** [comment]
@vasu-dev this is almost done (in more global #1812), there's nothing more to do here
