### ISSUE TITLE
accuracy had KeyError

### ISSUE THREAD

**Issue by lampda** [RaRe-Technologies/gensim#1790]
#### Description
TODO: change commented example

#### Steps/Code/Corpus to Reproduce

while going to have an accuracy computation by calling
```
model.wv.accuracy('question-file-name')
```
I got error message as followings:

```
KeyErrorTraceback (most recent call last)
<ipython-input-123-8a545c3407ef> in <module>()
----> 1 model.wv.accuracy('./questions_words.txt',restrict_vocab=1000000)

/opt/anaconda2/lib/python2.7/site-packages/gensim/models/keyedvectors.pyc in accuracy(self, questions, restrict_vocab, most_similar, case_insensitive)
    662 
    663         """
--> 664         ok_vocab = [(w, self.vocab[w]) for w in self.index2word[:restrict_vocab]]
    665         ok_vocab = dict((w.upper(), v) for w, v in reversed(ok_vocab)) if case_insensitive else dict(ok_vocab)
    666 

KeyError: u'a'
```

When I looked into the code inside the file **keyedvectors.py** for the called function **accuracy** I found this:

```
ok_vocab = [(w, self.vocab[w]) for w in self.index2word[:restrict_vocab]]
```

Then I double checked the size of both `self.vocab` and `self.index2word` , surprisingly I found both size are not matched. That told me that word 'a' is **NOT** in `self.vocab` though it **IS** in `self.index2word`.

My questions raised:

1. why and how happened for the different size of two (self.vocab and self.index2word)?
2. how about change the calculation code to:

```
ok_vocab = [(w, self.vocab[w]) for w in self.index2word if w in self.vocab][:restrict_vocab]
```

Any helps? Thanks.

**Comment by menshikh-iv** [comment]
Hi @lampda,
thanks for the report, can you share the full code here (with train dataset / QA file), I need to reproduce this problem first.

**Comment by lampda** [comment]
@menshikh-iv 

I'd like to share, but how can I post all that you may be interested?
The model file is only <200MB but syn0 file is about 1GB.

The code is running via ipython, and the main part code is here:
```
# check names in sports
for word, sim in model.most_similar(positive=[u'林丹',u'乒乓球'], negative=[u'羽毛球'],topn=50):
    print word, sim
# expected and actual answers of top3 are 
# 张继科 0.800885558128
# 张怡宁 0.704701662064
# 刘国梁 0.699866652489

# check most similarity
for word, sim in model.most_similar(positive=[u'新西兰',u'多伦多'], negative=[u'加拿大'],topn=50):
    print word, sim
# expected and actual answers of top3 are 
# 奥克兰 0.869593858719
# 惠灵顿 0.852988243103
# 墨尔本 0.841493964195

# then check accuracy:
model.wv.accuracy('./question_words.txt')
```

And my question_words.txt (all Chinese characters except the section line)
```
: country-capital-pairs
中国 北京 德国 柏林
中国 北京 日本 东京
中国 北京 法国 巴黎
中国 北京 美国 华盛顿
中国 北京 英国 伦敦
中国 北京 韩国 首尔
德国 柏林 英国 伦敦
德国 柏林 韩国 首尔
日本 东京 德国 柏林
日本 东京 英国 伦敦
日本 东京 韩国 首尔
法国 巴黎 德国 柏林
法国 巴黎 日本 东京
法国 巴黎 美国 华盛顿
法国 巴黎 英国 伦敦
法国 巴黎 韩国 首尔
美国 华盛顿 德国 柏林
美国 华盛顿 日本 东京
美国 华盛顿 英国 伦敦
美国 华盛顿 韩国 首尔
英国 伦敦 韩国 首尔
```

I was expecting to see the accuracy rate (score) computed, in order to examine how good my trained word2vec model is.

However, as I mentioned in previous post, there is NO word 'a' in self.vocab.
```
'a' in model.wv.vocab, 'a' in model.wv.index2word

# returns (False, True)
```

Anything should you need? Thanks.

**Comment by lampda** [comment]
BTW: trainset (text corpus) is about 10GB in my local machine, and about 3.1 Million sentences.

**Comment by lampda** [comment]
I checked the file **word2vec.py** and found this code inside `sort_vocab(self)`:
```
self.wv.index2word.sort(key=lambda word: self.wv.vocab[word].count, reverse=True)
```
So, the size(self.wv.vocab) must be equal to te size(self.wv.index2word). Or for my case, all words presented in self.wv.index2word should also be there in self.vocab.

But what resulted in the KeyError failure for the accuracy?

**Comment by lampda** [comment]
@menshikh-iv 
I think this is something wrong with my use of word2vec. The problem disappeared when I reload the model to ipython.

I think we may close this issue. Sorry for bothering.

**Comment by menshikh-iv** [comment]
@lampda no problem, I'm glad that you resolve your problem :blush:
