### ISSUE TITLE
Use magic "%%time" for timing your code instead of using getting start and end time

### ISSUE THREAD

**Issue by gitclem** [RaRe-Technologies/gensim#1794]
The use of

`%%time
`

to time a cell is much cleaner than explicitly having to get the start and end times.  (%% indicates to time the whole cell.)

See::  http://ipython.readthedocs.io/en/stable/interactive/magics.html

**Comment by gojomo** [comment]
Some notebooks already use `%time` or `%%time` to print timing-info. 

Some cases where an `end - start` calculation are made might require the timing value in a variable for other kinds of reporting (which I don't think you can get from the magics). 

Can you be more specific about the places where you'd suggest a change could beneficially be made, perhaps via Pull Request(s)?

**Comment by menshikh-iv** [comment]
Ping @gitclem

**Comment by menshikh-iv** [comment]
Looks abandoned, I'll close this (anyway, very soon, this will be non-relevant, when we start the process of switching to sphinx-gallery & replace notebooks to good-testable small scripts).
