### ISSUE TITLE
init_ngrams in wrapper filling the wrong dictionary? (syn0 instead of syn0_vocab)? (FastText)

### ISSUE THREAD

**Issue by saroufimc1** [RaRe-Technologies/gensim#1798]
By looking again at the init_ngrams() function used when loading a pre-trained model in fasttext (see fasttext wrapper) in the .bin format, apart from the other issues discussed previously, I was wondering: 

Shouldn't the words embeddings be filled into syn0_vocab and not syn0, and then compute ourselves the average embeddings of word and subwords in order to get syn0? 

Thanks,
Carl

**Comment by manneshiva** [comment]
@saroufimc1 `syn0` is calculated exactly in the way you described but without adding the extra variable -- `syn0_vocab`. The vocabulary embeddings are first filled into `syn0` ([here](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/wrappers/fasttext.py#L404)) and then enriched with subwords embeddings to get final embeddings in `syn0` (look [here](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/wrappers/fasttext.py#L425)).

**Comment by saroufimc1** [comment]
@manneshiva my bad. Didn't notice that second part. I think though that it would be good to have both syn0 and syn0_vocab even if syn0_vocab is not really needed since it is not enriched with the subwords. 

In my particular scenario, if I want to take the embeddings of words and subwords to be used for supervised learning in Keras, I would use syn0_vocab for the words since the Neural Network would do some kind of averaging of the input layer (ie. of words and subwords that are in each sentence or document).
