### ISSUE TITLE
word2vec: is there a way to change the smoothing parameter 0.75

### ISSUE THREAD

**Issue by mucun1988** [RaRe-Technologies/gensim#1810]
I am trying to use word2vec in gensim and reading https://radimrehurek.com/gensim/models/word2vec.html

The negative samples are sampled using `make_cum_table(power=0.75, domain=2147483647)`, which is called internally. I am wondering is there a way to change this smoothing parameter 0.75 when the function `word2vec.Word2Vec()` is called?

Thanks,
Matt

**Comment by menshikh-iv** [comment]
No "clean" way to do it.
But this method calls always with default parameters -> you can "monkeypatch" method directly and change this parameter.

FYI - we have better place for questions - our [maillist](https://groups.google.com/forum/#!forum/gensim)

**Comment by mucun1988** [comment]
Hi menshikh-iv

Thanks for the reply!

Just make sure. So just changing the 0.75 in `def make_cum_table(self, power=0.75, domain=2**31 - 1):` in the file word2vec.py to the number I want (say 0.5) would work?

Best,
Matt

**Comment by menshikh-iv** [comment]
@mucun1988 yes

**Comment by mucun1988** [comment]
great! many thanks!
