### ISSUE TITLE
Re-run & fix all notebooks with python3

### ISSUE THREAD

**Issue by menshikh-iv** [RaRe-Technologies/gensim#1820]
It's hard to support both python versions for notebook (and make completely impossible any testing), for this reason, need to do several things:
- [ ] Re-run all notebooks with python3
- [ ] Add `!pip install` line in the head of the notebook, if notebook required some additional dependencies 
- [ ] Fix PEP8
- [ ] Fix bugs (if exist)
- [ ] Make easier work with downloaded datasets (add to gensim-data or something else)

**Comment by pushpankar** [comment]
I am taking it.

**Comment by menshikh-iv** [comment]
@pushpankar not worth it, I'll do it myself later (also, more requirements will be added)

**Comment by menshikh-iv** [comment]
No more actual, because #1964 and sphinx-gallery will be very soon.
