### ISSUE TITLE
Store images from README directly in repository

### ISSUE THREAD

**Issue by menshikh-iv** [RaRe-Technologies/gensim#1849]
**Problem**: We have [adopters table](https://github.com/RaRe-Technologies/gensim#adopters) that contains concrete companies with logo & additional information. Images (logo) stored everywhere (random CDN, sites, etc) -> can be broken (unavailable) -> README doesn't looks good.

**Solution**: Store all images in repository

**Warning**: We don't want to store large `.jpg`, all images should be optimized before.

**Comment by ibrahimsharaf** [comment]
Hi @menshikh-iv, I am willing to take this one.
Should the images be stored in a separate directory in gensim repo? How big exactly is the large `.jpg` image?

**Comment by menshikh-iv** [comment]
@ibrahimsharaf 
1. Yes, separate dir in `docs/` is good choice
2. As small as possible (preferred `.png` if available, `.jpg` is OK too).

**Comment by ibrahimsharaf** [comment]
@menshikh-iv Do you have a specific image optimization method in mind?

**Comment by menshikh-iv** [comment]
@ibrahimsharaf no, up to you, only one thins - `width` no more than 200-300, we no need large logos here.
