### ISSUE TITLE
Wrong distance in Lexical entailment experiment for Poincare embeddings

### ISSUE THREAD

**Issue by octavian-ganea** [RaRe-Technologies/gensim#1858]
The following line https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/poincare.py#L1522
should be:
```
return -1 * (1 + self.alpha * (norm_2 - norm_1)) * min_distance
```
otherwise `distance` is the last encountered distance, not the smallest one.

**Comment by menshikh-iv** [comment]
Thanks for report @octavian-ganea, looks like a typo (that generates bug here).
@jayantj can you confirm?

**Comment by jayantj** [comment]
Yeah, that looks like a bug. Good catch.

**Comment by hachibaka** [comment]
Hi, Can I take this one?

**Comment by menshikh-iv** [comment]
@hachibaka of course, feel free to contribute!

**Comment by hachibaka** [comment]
completed, PR #1863.
