### ISSUE TITLE
MmCorpus file-like object support bug

### ISSUE THREAD

**Issue by menshikh-iv** [RaRe-Technologies/gensim#1869]
**Into**
We have some "weird" behavior if a user passes a `file-like` object to `MmCorpus`, based on [this mailing list thread](https://groups.google.com/forum/#!topic/gensim/420pRBwexKQ)

**Demonstration**

```python
from gensim.corpora import MmCorpus
import bz2

f = bz2.BZ2File("testcorpus.mm.bz2")
print(f.closed)  # 0
corpus = MmCorpus(f)
print(f.closed)  # 1 ???
```

**What happens**
File-like object was closed when we call `MmReader`, problem located here

https://github.com/RaRe-Technologies/gensim/blob/5342153eb4f4b02bb45bfa3951eef8250ac9f6b6/gensim/matutils.py#L1274

`with` automatically close `file-like` when we out of scope, **this is OK if we open this file**, but we **shouldn't close file-like passed from user**.

Related PR #1867 

**UPD:** another problem here - call `IndexCopus.__init__`, that didn't support `file-like` object at all.

**Comment by sj29-innovate** [comment]
@menshikh-iv  I  am trying to fix this by replacing the with statement with the following code ,
```
lines = utils.file_or_filename(self.input)
''' Further code '''
 if isinstance(self.input, string_types):
            lines.close()
```
Do you have any other suggestions for this ?

**Comment by menshikh-iv** [comment]
@sj29-innovate 
1. About `with` statement, need to use more complicated (but more similar with `with` variant), look at  [SO-thread](https://stackoverflow.com/questions/26096435/is-python-with-statement-exactly-equivalent-to-a-try-except-finally-bloc)
2. About `IndexedCorpus`, is this possible to use `file-like` instead of the filename? What're pros/cons here?

**Comment by sj29-innovate** [comment]
@menshikh-iv  What about reopening the file after the "with" statement if the input was a "file-like" object ?

**Comment by sj29-innovate** [comment]
@menshikh-iv Using with statement will close the file object anyways so do you plan to use the nested try and finally blocks as mentioned in that thread ?

**Comment by menshikh-iv** [comment]
@sj29-innovate about with - yes, this is a problem in this case (because we shouldn't close the file if we didn't open it).

For indexed-corpus - yes, we need both.

**Comment by sj29-innovate** [comment]
@menshikh-iv  I believe we can support both filename and file-like object with a difference that we wont be able to save it to an index file in case of the file object. This can create performance issues if in any subclass we need to call "super" so the "init" function of "IndexedCorpus" will again need to generate a new indexed corpus form the object instead of using a previously saved indexed corpus.

**Comment by menshikh-iv** [comment]
Aha, so, probably this issue impossible to fix (by `IndexCorpus` reason), but you can fix the incorrect behavior of `MmCorpus` anyway.

the current code looks scary (especially formatting), try to publish PR & write tests (I'll look into again on concrete example).
