### ISSUE TITLE
ImportError: cannot import name KeyedVectors

### ISSUE THREAD

**Issue by dhanush987** [RaRe-Technologies/gensim#1877]
Python 2.7.12, Mac OS High Sierra, gensim (0.13.4.1)

from sklearn.externals import joblib
from gensim.models import KeyedVectors

Traceback (most recent call last):
  File "Test_for_ adversariality.py", line 5, in <module>
    from gensim.models import KeyedVectors
ImportError: cannot import name KeyedVectors

I am trying to load the skipgram.txt files.

**Comment by menshikh-iv** [comment]
Hello @dhanush987, you have really old gensim version (1 year ago), please upgrade to latest version `pip install -U gensim`

**Comment by Apollo2Mars** [comment]
It should be from gensim.models.keyedvectors import KeyedVector

**Comment by NeelKanwal** [comment]
Still I have same problem.

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-18-bce169676d59> in <module>
----> 1 wv_embeddings = keyedVectors.load_word2vec_format(
      2     'GoogleNews-vectors-negative300.bin.gz',
      3     binary=True
      4 )

NameError: name 'keyedVectors' is not defined

**Comment by piskvorky** [comment]
@NeelKanwal See above.
