### ISSUE TITLE
How can I create StackedAreaChart with adding focus chart on the botton like lineWithFocusChart()  

### ISSUE THREAD

**Issue by huahuajhu** [RaRe-Technologies/gensim#1881]
How can I create StackedAreaChart with focus chart with slider at the botton like the lineWithFocusChart()

**Comment by menshikh-iv** [comment]
Hi @huahuajhu, this issue page of [Gensim project](https://github.com/RaRe-Technologies/gensim/blob/develop/README.md), probably you should to post your issue to https://github.com/novus/nvd3  (check that this is the needed framework).
