### ISSUE TITLE
cannot import name 'LabeledSentence'

### ISSUE THREAD

**Issue by thepurpleowl** [RaRe-Technologies/gensim#1886]
#### Description
LabeledSentence is not being imported from gensim.models.doc2vec. 

``from gensim.models.doc2vec import LabeledSentence``

the error I am getting is 
``cannot import name 'LabeledSentence'``

**Comment by menshikh-iv** [comment]
@thepurpleowl hello, thanks for the report, right now you can use 
`from gensim.models.deprecated.doc2vec import LabeledSentence`


CC: @manneshiva
