### ISSUE TITLE
`corpus_count` restarts from 0 when adding to trained model

### ISSUE THREAD

**Issue by martinapugliese** [RaRe-Technologies/gensim#1899]
#### Description

I'm using the online training feature of gensim to add to an existing model when I got new data, I've mainly followed the tutorial [here](https://github.com/RaRe-Technologies/gensim/blob/master/docs/notebooks/online_w2v_tutorial.ipynb). 

In the specifics, I've pre-trained a model over roughly 1.5 million sentences, saved it and am now adding more sentences to it.

#### Steps/Code/Corpus to Reproduce

```
import gensim

# Load existing trained model
model = gensim.models.Word2Vec.load('gensim_model')

print('model counts', model.corpus_count, len(model.wv.vocab))

sents = [['new', 'sentence', 'one'], ['new', 'sentence', 'two']]

# Keep training it with new data
model.build_vocab(sents, update=True)
model.train(sents, total_examples=model.corpus_count, epochs=model.iter)

print('model counts', model.corpus_count, len(model.wv.vocab))
```
While the first prints gives `model counts 1470958 126927`, the second gives `model counts 2 126928`, so apparently the counts of texts scanned has restarted while the vocabulary has been added to. I'd have expected the count of corpus texts scanned to be added to as well?

#### Expected Results

Would have expected the second print to give `model 1478023 126933`.

#### Actual Results

The second print gives `model counts 2 126928`.

#### Versions

```
Darwin-17.4.0-x86_64-i386-64bit
Python 3.6.3 (default, Oct  4 2017, 06:09:38)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
NumPy 1.14.0
SciPy 1.0.0
gensim 3.2.0
FAST_VERSION 0
```

**Comment by menshikh-iv** [comment]
Hello @martinapugliese 

About `corpus_count` - this works as awaited - calculate the number of documents based on **latest** `build_vocab` (because after you use it as `total_examples`).

About vocab size:
1. Are you sure, that this words isn't in your model? 
2. This words can be also removed (depends on `min_count` attribute of your model, if too small - model will ignore this words).

**Comment by martinapugliese** [comment]
@menshikh-iv Thank you ver much! Yes, I'm sure the word is not in vocabulary as I just built the sentences as examples. Closing this as solved then!
