### ISSUE TITLE
Add method for showing base info about gensim

### ISSUE THREAD

**Issue by menshikh-iv** [RaRe-Technologies/gensim#1902]
Intro
----
When users report something, we need to know more information (not only gensim version, versions of related packages, OS and so on), and user need to copy-paste&run something like this

````
Please run the following snippet and paste the output below.
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
````

We can easily add it as method to gensim and use as `python -m gensim.scripts.package_info --info`

Todo
-------
Implement this method, information, that should be showed
- gensim version
- python version
- numpy version
- scipy version
- os version
- smart_open version
- `FAST_VERSION` variable
- path (where gensim installed)
- ??? (maybe something else)

**Comment by sharanry** [comment]
I am taking this up.
