### ISSUE TITLE
Support ngram by gensim ?

### ISSUE THREAD

**Issue by xiaoleihuang** [RaRe-Technologies/gensim#1906]
It seems gensim only support bigram by phrase. However, it seems to be hard to extract n-gram (uni, bi, trigram) all together once. The tfidfmodel and other models seems only support one phrase, if I can't use the uni,bi,trigram together in the models. Any solutions for this issue?

**Comment by menshikh-iv** [comment]
@xiaoleihuang this can be easily achieved if you apply Phrases several times, like
1. Train Phrases, apply it to text -> text with bigrams
2. Train new Phrases on text with bigrams, apply it to text with bigrams -> text with trigrams 
...
etc
