### ISSUE TITLE
Training dataset too large to download

### ISSUE THREAD

**Issue by shantanuo** [RaRe-Technologies/gensim#1914]
#### Description
The dataset to be downloaded from baidu site is too large 
I found this URL from page : translation_matrix.ipynb

https://pan.baidu.com/s/1boP0P7D

Is the file available on S3?

**Comment by menshikh-iv** [comment]
Hello @shantanuo, this isn't dataset, this is models (1GB for the model is normal size), more accurately - this is pre-trained word-vectors.

About S3 - I have no idea. You can also load `*.zip` with needed models + some additional stuff from http://clic.cimec.unitn.it/~georgiana.dinu/down/resources/transmat.zip

FYI - for this type of questions, we have [mailing list](https://calendar.google.com/calendar/b/0/r#main_7), issues isn't a good place for it.
