### ISSUE TITLE
Filipino Localization

### ISSUE THREAD

**Issue by cordeta** [RaRe-Technologies/gensim#1921]
I want to Localize your Files in Filipino

**Comment by menshikh-iv** [comment]
Hello @cordeta, what're files you mean? And why this can be useful (what's a pros/cons)?

**Comment by souravsingh** [comment]
I think he is talking about localizing the docs for the Filipino language

**Comment by cordeta** [comment]
Yes sir @souravsingh  im referring about the docs of the projects that needs to be localized . Not the internal source codes  but the docs that need this kind of approach

**Comment by cordeta** [comment]
The Pros of my offer is that i would do this for free as long as you gave me a staging repo  like il8n/tl_ph in your dir. We are heavily funded with our sponsors to offer free localization to open-source projects to promote our language and at the same time to pave a way to some of my fellow Filipino developers

**Comment by menshikh-iv** [comment]
@cordeta that's great, but the situation is ambiguous for me

Pros:
- Translated documentation to Filipino

Cons:
- Who will support it (when we add and change something)? We are working on new documents right now, who will translate new documentation (which is not present now)?
- It is more difficult to maintain the documentation up-to-date, the translation will always lag behind
- It seems that this is not the most popular language, what's the point of adding it to us? For example, I'm native Russian speaker, Russian language definitely more popular that Filipino, but I see no reason to translate the documentation into Russian.

We are really appreciated that you want to help us (and promote Filipino), but I'm -1 on this change.
@piskvorky through?

**Comment by piskvorky** [comment]
I'm not against localization, but it would be a nontrivial project. There's scaffolding we don't have in place yet, both technical and process-wise.

So, this is a bigger part "How to do it properly?" and smaller part "Translate into language X".

**Comment by cordeta** [comment]
Glad to hear your side . Anyways Thank you for an in-depth explanation. The reason behind all of this is because we are sponsored to do localization to open-source projects . Moderators will check our PR and if its credible and close to perfection then are getting paid. Thank you for the time

**Comment by menshikh-iv** [comment]
Thank you for proposal, good luck!
