### ISSUE TITLE
IndexError when passing in num_features into MatrixSimilarity

### ISSUE THREAD

**Issue by drastorguev** [RaRe-Technologies/gensim#1941]
#### Description
Receiving error `IndexError: index 101 is out of bounds for axis 1 with size 100` when passing in number of features into gensim.similarities.docsim.MatrixSimilarity(model_tf_idf[model_corpus], num_features=100)`
`

#### Error
```
Traceback (most recent call last):
  File "~~~~~~~~~~~~~~~~.py", line 14, in <module>
    sims = gensim.similarities.docsim.MatrixSimilarity(model_tf_idf[model_corpus], num_features=100)
  File "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/env/lib/python3.6/site-packages/gensim/similarities/docsim.py", line 523, in __init__
    vector = matutils.unitvec(matutils.sparse2full(vector, num_features))
  File "/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/env/lib/python3.6/site-packages/gensim/matutils.py", line 395, in sparse2full
    result[list(doc)] = list(itervalues(doc))
IndexError: index 101 is out of bounds for axis 1 with size 100
```

**Comment by menshikh-iv** [comment]
Hello @drastorguev, can you provide the full example?
I think that number of features from `tf_idf` is more than 100, for this reason, you receive this error.

**Comment by drastorguev** [comment]
Hey sorry - I can't provide a full example of data as its very long.

It works fine, when I pass in `gensim.similarities.docsim.MatrixSimilarity(model_tf_idf[model_corpus], num_features=len(model_dictionary))` but this file is too large, hence I want to make it smaller by reducing the number of features. `model_dictionary` has 243070.

To calculate `model_corpus `, `model_tf_idf `, `model_dictionary ` I've used `gensim.similarities.docsim`.

**Comment by menshikh-iv** [comment]
`gensim.similarities.docsim.MatrixSimilarity(model_tf_idf[model_corpus], num_features=len(model_dictionary))` - this is right way, how to do it, `num_features` **must be equal** to size of your dictionary, that's bad place for reduce something here.

If you really want to reduce, you should reduce size of your `model_dictionary`, re-calculate  `model_tf_idf` based on this vocab and after - use new updated vocab/vectors for `MatrixSimilarity`
