### ISSUE TITLE
Make add_word part of keyedvectors.py interface

### ISSUE THREAD

**Issue by talbaumel** [RaRe-Technologies/gensim#1942]
Hi, I think it would be very useful to define `add_word` inside the class instead of inside the `load` function in [keyedvectors](https://github.com/RaRe-Technologies/gensim/blob/7127eeef8304852da589465b338e2bba14e881f1/gensim/models/keyedvectors.py).

Thanks ✌🏻

**Comment by menshikh-iv** [comment]
Thanks for report @talbaumel, I saw some message in mailing list from users, who want to modify `KeyedVectors`, for me - sounds like a good idea, I'm +1 for this

**Comment by MritunjayMohitesh** [comment]
Can I take this?

**Comment by menshikh-iv** [comment]
@MritunjayMohitesh yes

**Comment by MritunjayMohitesh** [comment]
@talbaumel isn't it already done?

**Comment by talbaumel** [comment]
It's defiened under `load_word2vec_format `, that means it's not visible to users...

**Comment by MritunjayMohitesh** [comment]
@talbaumel  please check this link out-
https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/keyedvectors.py

I found this in the develop branch. That's why I think it's already been done. I think I am not getting you.Could you please elaborate?

**Comment by englhardt** [comment]
@MritunjayMohitesh 
The `add_word` method that should be publicly exposed is in [utils_any2vec.py#L182](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/utils_any2vec.py#L182) in the development version of the code.

**Comment by MritunjayMohitesh** [comment]
Thanks @englhardt 
As far as I understand, defining `add_word `outside the `load_word2vec_format` will require two additional parameters to be passed . Besides,I don't see this function being used anywhere else. So, I think defining outside would not be very much efficient. Please correct me if I'm still getting it wrong.

**Comment by talbaumel** [comment]
I wanted to add a <PAD> and <EOS> tokens to pre-trained keyedvectors object.
It requiered some hacking since the function was not visible, I tought it might be a common scenario 🤷🏻‍♂️

**Comment by persiyanov** [comment]
@menshikh-iv Greetings, does anyone work on this? If not, I could prepare a PR.

**Comment by menshikh-iv** [comment]
@persiyanov hello, I see no PRs related with this change, feel free to contribute :+1:
