### ISSUE TITLE
[IndexError]

### ISSUE THREAD

**Issue by MrMimic** [RaRe-Technologies/gensim#1943]
Hi all,
I built a huge model (254Mb + 2x2Gb npy) and everything work fine.
However, when entering the term "matrix" in the model to query the top similar concept, it raises the following error.

> 
> Enter: matrix
> Traceback (most recent call last):
>   File "rapid_query.py", line 43, in <module>
>     top_close = model.most_similar(positive=word, topn=3)
>   File "/home/VENV/lib/python3.5/site-packages/gensim/utils.py", line 1368, in new_func1
>     return func(*args, **kwargs)
>   File "/home/VENV/lib/python3.5/site-packages/gensim/models/base_any2vec.py", line 696, in most_similar
>     return self.wv.most_similar(positive, negative, topn, restrict_vocab, indexer)
>   File "/home/VENV/lib/python3.5/site-packages/gensim/models/keyedvectors.py", line 376, in most_similar
>     result = [(self.index2word[sim], float(dists[sim])) for sim in best if sim not in all_words]
>   File "/home/VENV/lib/python3.5/site-packages/gensim/models/keyedvectors.py", line 376, in <listcomp>
>     result = [(self.index2word[sim], float(dists[sim])) for sim in best if sim not in all_words]
> IndexError: list index out of range

I trie to go to the code see what's going wrong, but could not find why in 

`result = [(self.index2word[sim], float(dists[sim])) for sim in best if sim not in all_words]`

**Comment by menshikh-iv** [comment]
Hello @MrMimic, can you provide the full code example (I should reproduce this error)? Also, please metion gensim/python/os version.

**Comment by menshikh-iv** [comment]
ping @MrMimic, we need a full example from you (code + data) for reproducing this error.

**Comment by menshikh-iv** [comment]
Closed (unreproducible)
