### ISSUE TITLE
scripts.segment_wiki invalid argument

### ISSUE THREAD

**Issue by marcoaleixo** [RaRe-Technologies/gensim#1946]
#### Description
segment_wiki.py: error: unrecognized arguments: -i

```
python -m gensim.scripts.segment_wiki -i -f enwiki-latest-pages-articles.xml.bz2 -o enwiki-latest.json.gz
2018-03-01 17:40:37,055 : MainProcess : INFO : running /home/marco/miniconda2/envs/mrturing/lib/python2.7/site-packages/gensim/scripts/segment_wiki.py -i -f enwiki-latest-pages-articles.xml.bz2 -o enwiki-latest.json.gz
usage: segment_wiki.py [-h] -f FILE [-o OUTPUT] [-m MIN_ARTICLE_CHARACTER]
segment_wiki.py: error: unrecognized arguments: -i

```

#### My output versions:

>>> import platform; print(platform.platform())
Linux-4.13.0-36-generic-x86_64-with-debian-stretch-sid
>>> import sys; print("Python", sys.version)
('Python', '2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 17:05:42) \n[GCC 7.2.0]')
>>> import numpy; print("NumPy", numpy.__version__)
('NumPy', '1.13.3')
>>> import scipy; print("SciPy", scipy.__version__)
('SciPy', '1.0.0')
>>> import gensim; print("gensim", gensim.__version__)
('gensim', '3.1.0')
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
('FAST_VERSION', 1)
>>>

**Comment by menshikh-iv** [comment]
@marcoaleixo please upgrade your gensim version ("interlink parser" added in `gensim>=3.3.0`, look to [release notes (3.3.0)](https://github.com/RaRe-Technologies/gensim/releases/tag/3.3.0)
