### ISSUE TITLE
AttributeError: 'DocvecsArray' object has no attribute 'vector_size'

### ISSUE THREAD

**Issue by JonathanHourany** [RaRe-Technologies/gensim#1952]
I have Doc2Vec models that were trained and saved before the Re-design "*2vec" implementations #1777 commit (specifically, they were trained in v3.2) . On trying to use them today, the above attribute error was raised when I tried to use `infer_vector`. This is because in gensim/models/doc2vec.py", line 543, in infer_vector the line:

```doctag_vectors, doctag_locks = self.trainables.get_doctag_trainables(doc_words, self.docvecs.vector_size)```

Attempts to access `self.docvecs.vector_size`, which before version 3.4.0 is not an attribute of the DocVecsArray class.

#### Steps to Reproduce
```
from gensim.models import Doc2Vec

model = Doc2Vec.load('some-3.2-model/model')
model.infer_vector(['foo'])

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-851ff3602fcf> in <module>()
----> 1 model.infer_vector(['foo'])

~/anaconda2/envs/faker/lib/python3.6/site-packages/gensim/models/doc2vec.py in infer_vector(self, doc_words, alpha, min_alpha, steps)
    541 
    542         """
--> 543         doctag_vectors, doctag_locks = self.trainables.get_doctag_trainables(doc_words, self.docvecs.vector_size)
    544         doctag_indexes = [0]
    545         work = zeros(self.trainables.layer1_size, dtype=REAL)

AttributeError: 'DocvecsArray' object has no attribute 'vector_size'
```

**Comment by menshikh-iv** [comment]
@JonathanHourany thanks for the report, yes, this looks like a bug. 

Can you share your model for reproducing a problem? 

CC: @manneshiva please fix it ASAP

**Comment by JonathanHourany** [comment]
@menshikh-iv I wish I could, but the models are for a client that won't approve. If it would help though, I could train a model on a small open corpus like the lee corpus and post that some time today or tomorrow

**Comment by menshikh-iv** [comment]
@JonathanHourany yes, this is a great idea!
