### ISSUE TITLE
ValueError: You must specify either total_examples or total_words, for proper alpha and progress calculations. The usual value is total_examples=model.corpus_count.

### ISSUE THREAD

**Issue by Keramatfar** [RaRe-Technologies/gensim#1956]
I am trying to train a doc2vec model using gensim but i get some confusing errors. i get teh above error when i use this line in a for loop to train:
    model.train(it, epochs=model.iter, total_examples=model.corpus_count)

**Comment by menshikh-iv** [comment]
Hello @Keramatfar,
can you give a full example (code + data) for reproducing your problem?

**Comment by Keramatfar** [comment]
Definitely, but my data is in Persian.

My Code:
import csv
from gensim.models import doc2vec
from collections import namedtuple
from nltk import word_tokenize
from gensim.models.doc2vec import TaggedDocument
import gensim

LabeledSentence = gensim.models.doc2vec.LabeledSentence




docs = []
tags = []
analyzedDocument = namedtuple('AnalyzedDocument', 'words tags')

with open('all.csv', encoding = 'UTF-16') as data:
    r = csv.reader(data, delimiter = '\t')
    for i in r:
        words = word_tokenize(i[1].lower().replace('-', ' '))
        tags.append(i[0])
        docs.append(words)


print(1)


class LabeledLineSentence(object):
    def __init__(self, docs, tags):
       self.labels_list = tags
       self.doc_list = docs
    def __iter__(self):
        for idx, doc in enumerate(self.doc_list):
            yield LabeledSentence(words=doc,tags=[self.labels_list[idx]])

it = LabeledLineSentence(docs, tags)


model = gensim.models.Doc2Vec(size=300, window=10, min_count=5, workers=11,alpha=0.025, min_alpha=0.025) # use fixed learning rate
model.build_vocab(it)
for epoch in range(10):
    model.train(it, epochs=model.iter, total_examples=model.corpus_count)
    model.alpha -= 0.002 # decrease the learning rate
    model.min_alpha = model.alpha # fix the learning rate, no deca
    model.train(it)

#Most Similar Docs
t = word_tokenize("مقایسه اثر گاماگلوبولین وریدی با رژیم کتوژنیک در کودکان مبتلا به صرع مقاوم رژیم کتوژنیک  صرع - رژیم درمانی  گاماگلوبولین مجله علمی دانشگاه علوم پزشکی و خدمات بهداشتی درمانی همدان")
tokens = model.infer_vector(t)
sims = model.docvecs.most_similar([tokens])
print(sims)

data file is a csv file like this:

6189 | مقایسه اثر گاماگلوبولین   وریدی با رژیم کتوژنیک در کودکان مبتلا به صرع مقاوم رژیم کتوژنیک  صرع     رژیم درمانی  گاماگلوبولین مجله   علمی دانشگاه علوم پزشکی و خدمات بهداشتی درمانی همدان با توجه به اینکه در 80   درصد بیماران اپی لپتیک تشنجات از دوران کودکی آغاز می گردد و 20 10 درصد از   بیماران مقاوم به درمان هستند  این تحقیق   به منظور مقایسه اثر گاماگلوبولین وریدی با رژیم کتوژنیک در درمان صرع مقاوم   کودکان انجام گرفت این پژوهش یک مطالعه تجربی از نوع کارآزمایی بالینی است که بر   روی 40 کودک مبتلا به صرع مقاوم مراجعه کننده به بیمارستان کودکان مفید تهران در   سال 1373 صورت گرفته است  بیماران بطور   تصادفی پس از همانند سازی نسبی به دو گروه تقسیم شده که گروه مورد تحت درمان با   گاماگلوبولین وریدی به میزان 400mg/kg/dose هر هفته برای 6 4 ماه و گروه شاهد   تحت درمان با رژیم کتوژنیک از نوع مخلوط قرار گرفتند  تعداد و مدت تشنجات  تغییرات الکتروانسفالوگرافی و تغییرات رفتاری   قبل و بعد از درمان ثبت و نتایج مورد ارزیابی قرار گرفت در گروه مورد 52 درصد و   در گروه شاهد 64 درصد کاهش در میانگین تعداد تشنجات در 24 ساعت مشاهده شد  اختلاف کاهش تعداد تشنجات در دو گروه از نظر   آماری معنی دار نبود در 45 درصد بیماران گروه مورد و 60 درصد گروه شاهد مدت   تشنجات کاهش نشان داد نتیجه نهایی اینکه هر چند اثربخشی دو رژیم درمانی تفاوت   معنی داری نداشت ولی استفاده از گاماگلوبولین وریدی آسانتر و قابل تحمل تر   بود  این روش میتواند بعنوان یک راه   درمان صرع مقاوم بکار رود <?xml:namespace prefix = o ns = "urn:schemas   microsoft com:office:office" />
-- | --
6190 | مقایسه اثر درمانی داروهای گیاهی افشرده آویشن  افشرده مرزه و میکسچر آویشن با ترکیب دو   دارویی رانیتیدین و  متوکلوپراماید در سو   هاضمه فانکشنال سو هاضمه فانکشنال   دارو   درمانی  رانیتیدین  گیاه درمانی    متوکلوپراماید مجله علمی دانشگاه علوم پزشکی و خدمات بهداشتی درمانی   همدان سو هاضمه فانکشنال یک علت عمده مراجعه به مراکز درمانی است که در یک چهارم   افراد جامعه بطور شایع دیده می شود    درمان این عارضه با داروهای پروموتیلیتی نه تنها رضایت بخش نیست بلکه   هزینه سنگینی را نیز به همراه دارد  هدف   از اجرای این پژوهش  سنجش اثربخشی   داروهای گیاهی آویشن و مرزه و میکسچر آویشن در مقایسه با ترکیب دو دارویی   رانیتیدین ـ متوکلوپراماید بود مطالعه ازنوع کارآزمایی بالینی تصادفی شده   بود  در این مطالعه که در سال 1377 انجام   گرفت  با روش نمونه گیری مستمر یکصد و   هشتاد بیمار مبتلا به سو هاضمه که از نظر عادت سیگار کشیدن  نوع رژیم غذایی و گروه سنی مشابه بودند   انتخاب و به طریق تخصیص اتفاقی در چهار گروه درمانی قرار گرفتند  گروههای درمانی بجز گروه چهارم به صورت دو   سوکور به ترتیب قطره افشرده آویشن  قطره   افشرده مرزه  میکسچر آویشن هرکدام به   مقدار 10 قطره سه بار در روز به مدت یکماه و گروه چهارم رانیتیدین و   متوکلوپراماید با مقدار روزانه 2 قرص رانیتیدین به فاصله هر 12 ساعت و 2 قرص   متوکلوپراماید به فاصله هر 8 ساعت و به مدت یکــماه دریافت داشتند  لازم به تذکر است که در هر گروه تست اوره آز   و هیستولوژی ازنظر هلیکوباکترپیلوری انجام گردید و هر گروه به دو زیر گروه   تقریبا مساوی هلیکوباکترپیلوری مثبت و منفی تقسیم شد قطره افشرده آویشن در 6/55%  افشرده مرزه در 3/53%  میکسچر آویشن در 2/42% و ترکیب دو دارویی   رانیتیدین ـ متوکلوپراماید در 2/42% از بیماران سبب برطرف شدن 75 درصد و بیشتر   از علایم بیماری گردید  بهبودی کامل   اختلاف مشاهده شده در میزان بهبودی گروههای   درمانی گیاهی با گروه رانیتدین ـ متوکلوپراماید از نظر آماری معنی دار نبود   p>0 05  براساس مشاهدات مطالعه حاضر   نمی توان فرضیه یکسان بودن تاثیر افشرده آویشن و افشرده مرزه و میکسچر آویشن با   ترکیب دو دارویی رانیتیدین متوکلوپراماید را رد نمود <?xml:namespace prefix   = o ns = "urn:schemas microsoft com:office:office" />
6191 | بررسی نحوه پراکنش ذرات سرب در هوای شهر همدان از   آذرماه 76 تا خردادماه 77 آلوده سازی هوا    سرب مجله علمی دانشگاه علوم پزشکی و خدمات بهداشتی درمانی همدان به منظور   تعیین وضعیت پراکنش ذرات سرب در هوای شهر همدان یکصدودو نمونه از خیابانهای   مختلف  پمپ بنزین ها و پارکینگ عمومی شهر   در میدان آرامگاه بوعلی از آذرماه 76 تا خردادماه77 تهیه گردید برای انجام   عملیات نمونه برداری خیابان های شهر را به سه منطقه پرترافیک  ترافیک متوسط و کم ترافیک تقسیم بندی نموده و   نمونه برداری با استفاده از پمپ نمونه برداری قابل حمل و فیلتر استرسلولزی انجام   گرفت  نمونه ها به آزمایشگاه منتقل و پس   از آماده سازی به وسیله دستگاه جذب اتمی آنالیز گردید  نهایتا داده های بدست آمده با آزمون آماری   پارامتری بارتلت و آزمون غیر پارامتری Kruskal Wallis مورد تجزیه و تحلیل قرار   گرفتند میانگین ذرات سرب در مناطق پرترافیک    ترافیک متوسط و کم ترافیک به ترتیب 99/7    63/4 و 80/3 میکروگرم در متر مکعب بود و بین غلظت ذرات سرب در مناطق کم   ترافیک با غلظت ماده مذکور در پمپ بنزین ها و پارکینگ عمومی شهر که در جوار   مراکز پرترافیک واقع گردیده اختلاف آماری معنی داری وجود داشت مطالعه حاضر نشان   داد که غلظت سرب در هوای شهر همدان بیش از حد مجاز توصیه شده بوسیله سازمان   بهداشت جهانی  WHO   و سازمان حفاظت محیط زیست آمریکا  USEPA    برای هوای آزاد می باشد <?xml:namespace prefix = o ns =   "urn:schemas microsoft com:office:office" />
6192 | بررسی اثرات گزیلوکائین 2% در ایجاد بیدردی پس از عمل   برداشتن لوزه در کودکان 12 4 ساله برداشتن لوزه    درد  لیدوکائین مجله علمی دانشگاه   علوم پزشکی و خدمات بهداشتی درمانی همدان یکی از آزار دهنده ترین عوارض جراحی   برداشتن لوزه  درد بعد از عمل است  لذا در این تحقیق اثر تزریق داروی بیحسی   موضعی گزیلوکائین 2% در پایان عمل جراحی در کاهش درد بیماران بررسی شده است در این   مطالعه که بصورت کارآزمایی بالینی در سال 74 در بیمارستان بوعلی تهران انجام   شده  60 نفر از کودکان 12 4 ساله که   کاندید جراحی لوزه بودند انتخاب و بطور اتفاقی به دو گروه 30 نفری تقسیم شدند  به 30 نفر در پایان جراحی در چینهای لوزه و   زیر بیهوشی عمومی گزیلوکائین 2% و به 30 نفر بقیه که گروه شاهد هستند نرمال   سالین تزریق شد بر اساس نتایج بدست آمده 80% افراد مورد مطالعه کاهش درد چشمگیر   و معنی داری را نشان دادند و بنابراین نشان داده شد که این روش در کاهش درد این   بیماران پس از عمل جراحی کاملا موثر بوده و بیماران با آرامش و بدون تقلا بیدار   میشوند

**Comment by menshikh-iv** [comment]
@Keramatfar this is not a problem that your data in Persian, please share `all.csv` file.

I already see several mistakes (looks like "old" approach")
```python
model = gensim.models.Doc2Vec(size=300, window=10, min_count=5, workers=11,alpha=0.025, min_alpha=0.025) # use fixed learning rate
model.build_vocab(it)
for epoch in range(10):
    model.train(it, epochs=model.iter, total_examples=model.corpus_count)
    model.alpha -= 0.002 # decrease the learning rate
    model.min_alpha = model.alpha # fix the learning rate, no deca
    model.train(it)
```

should be 
```python
model = gensim.models.Doc2Vec(size=300, window=10, min_count=5, workers=11,alpha=0.025, min_alpha=0.025, iter=20)
model.build_vocab(it)
model.train(it, epochs=model.iter, total_examples=model.corpus_count)
```

**Comment by menshikh-iv** [comment]
Ping @Keramatfar, we are waiting for `all.csv` file (needed for reproduce an error)

**Comment by ahmedahmedov** [comment]
I have a similar problem. There is no way to reuse the pre-scanned vocabulary. I have explained the problem in the comments of the following code:
```

vocab = gensim.models.word2vec.Word2VecVocab(min_count=1, sorted_vocab=True)
vocab.scan_vocab(sentences, progress_per=PROGRESS_PER, trim_rule=None)
vocab.save(VOCAB_FILE_NAME)

#LATER
vocab  = gensim.models.word2vec.Word2VecVocab.load(VOCAB_FILE_NAME) 
#Word2VecVocab object doesn't keep total_words and corpus_count info
#it is now impossible for me to know the those variables. These values are returned from scan_vocab instead of being saved as a field of the object

#Create an empty model. 
model = gensim.models.word2vec.Word2Vec(min_count=MIN_COUNT, max_vocab_size=MAX_VOCAB_SIZE, seed=SEED, sg=SG, workers=WORKERS, size=SIZE)

#prepare the vocabulary. This step is also very confusing. I think prepare_vocab should belong to the model object since it actually modifies model's parameters
vocab.prepare_vocab(model.hs, model.negative, model.wv, min_count=MIN_COUNT,  keep_raw_vocab=False)

#This part is evern messier. There is now way I could have known what to do next without having to go thru the source code. 
#model.build_vocab rescans the whole vocabulary again, rendering my first phase useless. 
#instead, I have to use model.trainables.prepare_weights to have a workaround. Once again, what does vocabulary=model.vocabulary does? 
model.trainables.prepare_weights(model.hs, model.negative, model.wv, update=False, vocabulary=model.vocabulary)

#Now, most importantly. How do I set total_examples parameter? and why is it named differently? 
#model.corpus_count returns zero, because the only way of setting it up is to use build_vocab, which will rescan the vocabulary
#since model.corpus_count is zero now, I get this error:
#File "/home/ahmed/anaconda3/lib/python3.5/site-packages/gensim/models/base_any2vec.py", line 135, in _job_producer
#    epoch_progress = 1.0 * pushed_words / total_words
#ZeroDivisionError: float division by zero
#---
#there is no way I can get the total_words info from the vocabulary without scanning it again
model.train(sentences=sentences, total_examples=model.corpus_count, total_words=model.corpus_count, epochs=model.iter)

model.save(MODEL_FILE_NAME)
```

**Comment by menshikh-iv** [comment]
@ahmedahmedov unfortunately, you can't retrieve it correctly if you didn't call `build_vocab` (this attributes keeping directly by model, not in `Wod2VecVocab`).

**Comment by menshikh-iv** [comment]
closed (unreproducible)

**Comment by piskvorky** [comment]
That sounds messy indeed. If what @ahmedahmedov writes is true, that's just bad API.

@menshikh-iv what should @ahmedahmedov 's example look like, "officially", according to you?

**Comment by ahmedahmedov** [comment]
@piskvorky I also didn't understand why the example I provided is not reproducible. One can easily go thru the same steps by just initiating the `sentences` iterable.

**Comment by gojomo** [comment]
Yes, the `Word2VecVocab` class is too closely-coupled to `Word2Vec` to be properly reusable. It's now an 'attractive hazard' – it looks from its name like it might do something useful standalone, but doesn't quite. 

There's no "official" way to prepare a vocabulary for `Word2Vec` separate from instantiating a `Word2Vec` class. After doing that, a sophisticated source-code reading user might be able to save some time on future models by manually patching some properties for re-use around the `build_vocab()` steps. (But, I'm not sure if the same techniques that worked before the #1777 refactoring still work).

**Comment by piskvorky** [comment]
Yeah, we need some clarity around this. Both in terms of fixing the API (where needed), and definitely clearer ELI5 docs with examples / tutorials.

My feeling is that fixing the API needs @gojomo 's hand, or it will keep sinking further.

The tutorial could be written by anyone knowledgeable with the refactored code base (@manneshiva?), but is also non-trivial.

**Comment by Keramatfar** [comment]
@menshikh-iv,
excuse me for delay, all.csv is about 600mb. but the file is a two column csv, the first column is id and the second abstract of a research paper:

6189 | مقایسه اثر گاماگلوبولین   وریدی با رژیم کتوژنیک در کودکان مبتلا به صرع مقاوم رژیم کتوژنیک  صرع     رژیم درمانی  گاماگلوبولین مجله   علمی دانشگاه علوم پزشکی و خدمات بهداشتی درمانی همدان با توجه به اینکه در 80   درصد بیماران اپی لپتیک تشنجات از دوران کودکی آغاز می گردد و 20 10 درصد از   بیماران مقاوم به درمان هستند  این تحقیق   به منظور مقایسه اثر گاماگلوبولین وریدی با رژیم کتوژنیک در درمان صرع مقاوم   کودکان انجام گرفت این پژوهش یک مطالعه تجربی از نوع کارآزمایی بالینی است که بر   روی 40 کودک مبتلا به صرع مقاوم مراجعه کننده به بیمارستان کودکان مفید تهران در   سال 1373 صورت گرفته است  بیماران بطور   تصادفی پس از همانند سازی نسبی به دو گروه تقسیم شده که گروه مورد تحت درمان با   گاماگلوبولین وریدی به میزان 400mg/kg/dose هر هفته برای 6 4 ماه و گروه شاهد   تحت درمان با رژیم کتوژنیک از نوع مخلوط قرار گرفتند  تعداد و مدت تشنجات  تغییرات الکتروانسفالوگرافی و تغییرات رفتاری   قبل و بعد از درمان ثبت و نتایج مورد ارزیابی قرار گرفت در گروه مورد 52 درصد و   در گروه شاهد 64 درصد کاهش در میانگین تعداد تشنجات در 24 ساعت مشاهده شد  اختلاف کاهش تعداد تشنجات در دو گروه از نظر   آماری معنی دار نبود در 45 درصد بیماران گروه مورد و 60 درصد گروه شاهد مدت   تشنجات کاهش نشان داد نتیجه نهایی اینکه هر چند اثربخشی دو رژیم درمانی تفاوت   معنی داری نداشت ولی استفاده از گاماگلوبولین وریدی آسانتر و قابل تحمل تر   بود  این روش میتواند بعنوان یک راه   درمان صرع مقاوم بکار رود 
-- | --
6190 | مقایسه اثر درمانی داروهای گیاهی افشرده آویشن  افشرده مرزه و میکسچر آویشن با ترکیب دو   دارویی رانیتیدین و  متوکلوپراماید در سو   هاضمه فانکشنال سو هاضمه فانکشنال   دارو   درمانی  رانیتیدین  گیاه درمانی    متوکلوپراماید مجله علمی دانشگاه علوم پزشکی و خدمات بهداشتی درمانی   همدان سو هاضمه فانکشنال یک علت عمده مراجعه به مراکز درمانی است که در یک چهارم   افراد جامعه بطور شایع دیده می شود    درمان این عارضه با داروهای پروموتیلیتی نه تنها رضایت بخش نیست بلکه   هزینه سنگینی را نیز به همراه دارد  هدف   از اجرای این پژوهش  سنجش اثربخشی   داروهای گیاهی آویشن و مرزه و میکسچر آویشن در مقایسه با ترکیب دو دارویی   رانیتیدین ـ متوکلوپراماید بود مطالعه ازنوع کارآزمایی بالینی تصادفی شده   بود  در این مطالعه که در سال 1377 انجام   گرفت  با روش نمونه گیری مستمر یکصد و   هشتاد بیمار مبتلا به سو هاضمه که از نظر عادت سیگار کشیدن  نوع رژیم غذایی و گروه سنی مشابه بودند   انتخاب و به طریق تخصیص اتفاقی در چهار گروه درمانی قرار گرفتند  گروههای درمانی بجز گروه چهارم به صورت دو   سوکور به ترتیب قطره افشرده آویشن  قطره   افشرده مرزه  میکسچر آویشن هرکدام به   مقدار 10 قطره سه بار در روز به مدت یکماه و گروه چهارم رانیتیدین و   متوکلوپراماید با مقدار روزانه 2 قرص رانیتیدین به فاصله هر 12 ساعت و 2 قرص   متوکلوپراماید به فاصله هر 8 ساعت و به مدت یکــماه دریافت داشتند  لازم به تذکر است که در هر گروه تست اوره آز   و هیستولوژی ازنظر هلیکوباکترپیلوری انجام گردید و هر گروه به دو زیر گروه   تقریبا مساوی هلیکوباکترپیلوری مثبت و منفی تقسیم شد قطره افشرده آویشن در 6/55%  افشرده مرزه در 3/53%  میکسچر آویشن در 2/42% و ترکیب دو دارویی   رانیتیدین ـ متوکلوپراماید در 2/42% از بیماران سبب برطرف شدن 75 درصد و بیشتر   از علایم بیماری گردید  بهبودی کامل   اختلاف مشاهده شده در میزان بهبودی گروههای   درمانی گیاهی با گروه رانیتدین ـ متوکلوپراماید از نظر آماری معنی دار نبود   p>0 05  براساس مشاهدات مطالعه حاضر   نمی توان فرضیه یکسان بودن تاثیر افشرده آویشن و افشرده مرزه و میکسچر آویشن با   ترکیب دو دارویی رانیتیدین متوکلوپراماید را رد نمود <?xml:namespace prefix   = o ns = "urn:schemas microsoft com:office:office" />
6191 | بررسی نحوه پراکنش ذرات سرب در هوای شهر همدان از   آذرماه 76 تا خردادماه 77 آلوده سازی هوا    سرب مجله علمی دانشگاه علوم پزشکی و خدمات بهداشتی درمانی همدان به منظور   تعیین وضعیت پراکنش ذرات سرب در هوای شهر همدان یکصدودو نمونه از خیابانهای   مختلف  پمپ بنزین ها و پارکینگ عمومی شهر   در میدان آرامگاه بوعلی از آذرماه 76 تا خردادماه77 تهیه گردید برای انجام   عملیات نمونه برداری خیابان های شهر را به سه منطقه پرترافیک  ترافیک متوسط و کم ترافیک تقسیم بندی نموده و   نمونه برداری با استفاده از پمپ نمونه برداری قابل حمل و فیلتر استرسلولزی انجام   گرفت  نمونه ها به آزمایشگاه منتقل و پس   از آماده سازی به وسیله دستگاه جذب اتمی آنالیز گردید  نهایتا داده های بدست آمده با آزمون آماری   پارامتری بارتلت و آزمون غیر پارامتری Kruskal Wallis مورد تجزیه و تحلیل قرار   گرفتند میانگین ذرات سرب در مناطق پرترافیک    ترافیک متوسط و کم ترافیک به ترتیب 99/7    63/4 و 80/3 میکروگرم در متر مکعب بود و بین غلظت ذرات سرب در مناطق کم   ترافیک با غلظت ماده مذکور در پمپ بنزین ها و پارکینگ عمومی شهر که در جوار   مراکز پرترافیک واقع گردیده اختلاف آماری معنی داری وجود داشت مطالعه حاضر نشان   داد که غلظت سرب در هوای شهر همدان بیش از حد مجاز توصیه شده بوسیله سازمان   بهداشت جهانی  WHO   و سازمان حفاظت محیط زیست آمریکا  USEPA    برای هوای آزاد می باشد 
6192 | بررسی اثرات گزیلوکائین 2% در ایجاد بیدردی پس از عمل   برداشتن لوزه در کودکان 12 4 ساله برداشتن لوزه    درد  لیدوکائین مجله علمی دانشگاه   علوم پزشکی و خدمات بهداشتی درمانی همدان یکی از آزار دهنده ترین عوارض جراحی   برداشتن لوزه  درد بعد از عمل است  لذا در این تحقیق اثر تزریق داروی بیحسی   موضعی گزیلوکائین 2% در پایان عمل جراحی در کاهش درد بیماران بررسی شده است در این   مطالعه که بصورت کارآزمایی بالینی در سال 74 در بیمارستان بوعلی تهران انجام   شده  60 نفر از کودکان 12 4 ساله که   کاندید جراحی لوزه بودند انتخاب و بطور اتفاقی به دو گروه 30 نفری تقسیم شدند  به 30 نفر در پایان جراحی در چینهای لوزه و   زیر بیهوشی عمومی گزیلوکائین 2% و به 30 نفر بقیه که گروه شاهد هستند نرمال   سالین تزریق شد بر اساس نتایج بدست آمده 80% افراد مورد مطالعه کاهش درد چشمگیر   و معنی داری را نشان دادند و بنابراین نشان داده شد که این روش در کاهش درد این   بیماران پس از عمل جراحی کاملا موثر بوده و بیماران با آرامش و بدون تقلا بیدار   میشوند 
6193 | مقایسه آزمون مجذور کای بکار رفته در برخی از مقالات   پزشکی با آزمون مجذور کای روند آزمونهای آماری    مجذور کای  مجذور کای برای روند   مجله علمی دانشگاه علوم پزشکی و خدمات بهداشتی درمانی همدان یکی از متداولترین   آزمونهای آماری در مجلات پزشکی و بهداشتی آزمون مجذور کای می باشد  به منظور مقایسه آزمونهای مجذور کای بکار   برده شده در مقالات پزشکی و مقایسه آن با آزمون مجذور کای روند مطالعه ای مقایسه   ای صورت گرفته است در مقایسه این دو روش از نرم افزار EPI6 و زیر برنامه آزمون   روند برای داده های کمی استفاده گردیده است    در این روش از جداول توافقی مندرج در مقالات مجلات علوم پزشکی که برای   آنها آزمون مجذور کای انجام شده بود بهره گرفته شد  همچنین برای هر جدول انتخابی  آزمون مجذور کای روند صورت گرفت بررسی حاضر   نشان داد در حالیکه در برخی اوقات از آزمون مجذور کای  ارتباط دو متغیر را از نظر آماری معنی دار   نشان می دهد  اما اگر از آزمون آماری   مجذور کای روند استفاده شود رابطه از نظر آماری معنی دار نمی شود و بالعکس با   توجه به اینکه استفاده نامناسب از روش آماری در یک تحقیق پزشکی و بهداشتی می   تواند به نتیجه گیری غلط منجر شود و بکارگیری نتایج حاصل از این تحقیقات ممکن   است مخاطراتی برای سلامتی انسانها در برداشته باشد  پیشنهاد می گردد از روشهای آماری مجذور کای   با احتیاط بیشتری استفاده گردد
