### ISSUE TITLE
similarity_matrix: unit tests not run

### ISSUE THREAD

**Issue by nataliedurgin** [RaRe-Technologies/gensim#1961]
#### Description
The unit tests for the gensim.models.keyedvectors similarity_matrix cannot currently be found and are not being run.

https://github.com/RaRe-Technologies/gensim/blob/f9669bb8a0b5b4b45fa8ff58d951a11d3178116d/gensim/test/test_keyedvectors.py#L30

Fix is underway: 
https://github.com/nataliedurgin/gensim/commit/5bb6aea3a92b8e7ff7cecfca054a6057bb9b8fa8

**Comment by menshikh-iv** [comment]
@nataliedurgin nice catch, thank you!
