### ISSUE TITLE
How to adapt gensim.corpora.wikicorpus to work with full Wikipedia revision history?

### ISSUE THREAD

**Issue by crypdick** [RaRe-Technologies/gensim#1969]
I am interested in using doc2vec to study Wikipedia revisions on a per-article and per-author basis.  According to [the docs](https://radimrehurek.com/gensim/corpora/wikicorpus.html#gensim.corpora.wikicorpus.WikiCorpus), Wikicorpus() only supports these dump formats:

> <LANG>wiki-<YYYYMMDD>-pages-articles.xml.bz2
><LANG>wiki-latest-pages-articles.xml.bz2

Is it possible to adapt your code to work with `pages-meta-history.xml.bz2` files?

**Comment by crypdick** [comment]
From what I can tell, I'd have to add a few extra elements to [extract_pages()](https://github.com/RaRe-Technologies/gensim/blob/2ee7a2c3b376d62020992f4b31bdaa79cf9de8db/gensim/corpora/wikicorpus.py#L333) (e.g. author, revision id, parent), turn on `self.metadata` and update [get_texts()](https://github.com/RaRe-Technologies/gensim/blob/2ee7a2c3b376d62020992f4b31bdaa79cf9de8db/gensim/corpora/wikicorpus.py#L598) to yield the extra elements.

**Comment by menshikh-iv** [comment]
Hello @crypdick, yes, you can modify `extract_pages`.
Also, please have a look at https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/scripts/segment_wiki.py script (probably, this will be useful for you).
FYI better to use [our mailing list](https://groups.google.com/forum/#!forum/gensim) for this type of questions.
