### ISSUE TITLE
TypeError: doc2bow expects an array of unicode tokens on input, not a single string

### ISSUE THREAD

**Issue by sandyleong1007** [RaRe-Technologies/gensim#1973]
Hi I using gensim for topic modelling, i am experiencing some errors message that i dont quite understand it please help!

Error message 
```
Traceback (most recent call last):
  File "testTopic.py", line 15, in <module>
    doc_term_matrix = [dictionary.doc2bow(doc) for doc in line]
  File "C:\Python27\lib\site-packages\gensim\corpora\dictionary.py", line 233, in doc2bow
    raise TypeError("doc2bow expects an array of unicode tokens on input, not a single string")
TypeError: doc2bow expects an array of unicode tokens on input, not a single string
```

Here is my code 

```
import os
import gensim
from gensim import corpora


path = "C:\Users\Without_stopwords\\"
filelist = os.listdir(path)
for i in filelist:
    if i.endswith(".txt"):
        with open(path +i, 'r') as f:
            for line in f:


            	dictionary = corpora.Dictionary([line.split()])

            	doc_term_matrix = [dictionary.doc2bow(doc) for doc in line]

            	Lda = gensim.models.ldamodel.LdaModel

            	ldamodel = Lda(doc_term_matrix, num_topics=3, id2word = dictionary, passes=50)

```

Here is the sample content of my txt file

> hi draw date
> my broadband tv contract promotion ongoing
>  promotion lucky draw draw date whats joke

**Comment by menshikh-iv** [comment]
Hello @sandyleong1007,

your `doc` is `str` but should be a `list of str (tokens)`, you forgot to split your line into tokens.
In this case, if your `line` for example `hi draw date`, `doc` (from list comprehansion) will iterate over characters (i.e. `h` `i` ` ` `d` `r` `a` `w` ...).

Also, in your code sample, you create `Dictionary` based on one line from your file & after train `LdaModel`, I'm not sure that this was planned.

FYI better to use [our mailing list](https://groups.google.com/forum/#!forum/gensim) for this type of questions.
