### ISSUE TITLE
MmCorpus file attribute error

### ISSUE THREAD

**Issue by gagangm** [RaRe-Technologies/gensim#1978]
Not able to serialize the corpus into a saved file.

corpora = [dictionary.doc2bow(text) for text in texts]
corpora.MmCorpus.serialize(os.path.join(TEMP_FOLDER,'deerwester.mm'), corpus) #store to disk, for later use
for c in corpus:
    print(c)

It is throwing a following error:

AttributeError                            Traceback (most recent call last)
<ipython-input-9-16983d1bfedb> in <module>()
      1 corpora = [dictionary.doc2bow(text) for text in texts]
----> 2 corpora.MmCorpus.serialize(os.path.join(TEMP_FOLDER,'deerwester.mm'), corpus) #store to disk, for later use
      3 for c in corpus:
      4     print(c)

AttributeError: 'list' object has no attribute 'MmCorpus'

**Comment by menshikh-iv** [comment]
@gagangm your code is incorrect (list really have no attribute MmCorpus)
should be something like this
```python
corpora = [dictionary.doc2bow(text) for text in texts]
MmCorpus.serialize(os.path.join(TEMP_FOLDER,'deerwester.mm'), corpus)
for c in corpus:
    print(c)

```

**Comment by gauravkoradiya** [comment]
can i pass iterator instead of corpus?
like gensim.corpora.MmCorpus.serialize('corpus/email_data.mm', iter(mycorpus))

**Comment by piskvorky** [comment]
@gauravkoradiya Any stream of documents will do, including generators.
