### ISSUE TITLE
Gensim 0.9.1 ImportError: cannot import name interfaces

### ISSUE THREAD

**Issue by blehman** [RaRe-Technologies/gensim#198]
Trying to run a python script (OS X) to generate topic models using the gensim package, I am experiencing an ImportError.

> > > >>>from gensim import corpora
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "gensim/gensim/corpora/**init**.py", line 6, in <module>
> > >     from .indexedcorpus import IndexedCorpus # must appear before the other classes
> > >   File "gensim/gensim/corpora/indexedcorpus.py", line 23, in <module>
> > >     from gensim import interfaces, utils
> > >   File "gensim/gensim/interfaces.py", line 19, in <module>
> > >     from gensim import utils, matutils
> > >   File "gensim/gensim/**init**.py", line 7, in <module>
> > >     from gensim import utils, matutils, interfaces, corpora, models, similarities
> > >   File "gensim/gensim/models/**init**.py", line 7, in <module>
> > >     from .hdpmodel import HdpModel
> > >   File "gensim/gensim/models/hdpmodel.py", line 43, in <module>
> > >     from gensim import interfaces, utils
> > > ImportError: cannot import name interfaces

This problem occurs in Python 2.7.6 installed from Anaconda 1.9.2 (x86_64) using packages with the following versions:

numpy==1.8.0

scipy==0.13.3

gensim==0.9.1

Any ideas on how to debug this issue?

**Comment by loisaidasam** [comment]
It seems there's a thread of people experiencing similar issues:

https://groups.google.com/d/msg/gensim/vk8H6pkkMWU/F_oJU-qXlsIJ

Was there any resolution here?

**Comment by piskvorky** [comment]
Resolution was to install gensim properly. I suspect this error is related to the Anaconda package manager -- other people have reported it [behaves weirdly](https://groups.google.com/forum/#!searchin/gensim/anaconda%7Csort:date/gensim/MejmFuYHxfY/CdJ0vNw1AQAJ) too with gensim.

I don't know any details and there's not much we can do from the gensim side.

**Comment by loisaidasam** [comment]
Can you clarify what you mean by "install gensim properly"? I'm using pip.

**Comment by gojomo** [comment]
I would try variants of (1) starting with a fresh/empty environment; and (2) making sure gensim is only installed via pip. 

Specifically, I've never used full anaconda, instead preferring to start with miniconda, then manually installing packages as needed. (For most packages, I've tried `conda install PKG` first, then used `pip install PKG` only if needed... but for gensim, because typically the latest version has only been in pip/pypi, only using `pip`.) I've not had this problem. 

If starting with a larger many-package anaconda install, before even trying to install gensim, I'd check if there's any indication it's been installed or otherwise made findable – because of the report in the discussion thread @piskvorky links above. (Specifically, I'd check both if it appears in `conda list`, *or* if an attempt to import/reference from source works, because of the post where Eric Vanhove suggests that at one problematic point for him, "gensim isn't showing up in the list of modules installed for Anaconda although it does seem to be in the initial modules provided with an Anaconda/Spyder installation". If ever in such a weird state, start fresh or otherwise figure out how to remove the unintentionally-discoverable gensim, rather than attempting any further installs on top.)

**Comment by loisaidasam** [comment]
Thanks for the response @gojomo. My problem doesn't stem from any sort of `*conda`-related install. I'm using a gensim model on an AWS Elastic Beanstalk environment. It has worked for me previously, but something has changed that leads to it no longer working, unfortunately. My guess is that it's related to some sort of package updates or perhaps even something that changed in my codebase.

I'm experimenting with changing some path names now in my codebase in case there is some sort of collision. Will keep you posted.

**Comment by gojomo** [comment]
Ah, ok. Unless the full-traceback, gensim & python versions, and method-of-install are very similar to prior reports, it may not be the same issue – even if the terminal message ("cannot import name interfaces") is the same. In my experience, sometimes "cannot import…" occasionally means, "some other error happened during import, but that got caught & turned into this less-descriptive import-error".  Trying what @piskvorky suggests in the forum thread you linked (from plain python shell, trying `from gensim import interfaces`) may yield more info.

**Comment by loisaidasam** [comment]
Figured out my issue - turns out it was more of a elastic beanstalk/theano-specific issue.

Full details here: https://github.com/Theano/Theano/issues/3809

Thanks for the thoughts/advice!

**Comment by piskvorky** [comment]
Thanks for letting us know @loisaidasam !

**Comment by shwetatiwari2601** [comment]
Hi, Can anyone help me with the below problem! I am experienced an import error. When I am trying to import gensim in my program I got this error.  Thanks

import numpy
import scipy
 import gensim
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-ec15f3ffe0f1> in <module>()
----> 1 import gensim

/Library/Python/2.7/site-packages/gensim/__init__.pyc in <module>()
      4 """
      5 
----> 6 from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
      7 import logging
      8 

/Library/Python/2.7/site-packages/gensim/models/__init__.py in <module>()
     11 from .rpmodel import RpModel
     12 from .logentropy_model import LogEntropyModel
---> 13 from .word2vec import Word2Vec
     14 from .doc2vec import Doc2Vec
     15 from .ldamulticore import LdaMulticore

/Library/Python/2.7/site-packages/gensim/models/word2vec.py in <module>()
     98 
     99 try:
--> 100     from gensim.models.word2vec_inner import train_batch_sg, train_batch_cbow
    101     from gensim.models.word2vec_inner import score_sentence_sg, score_sentence_cbow
    102     from gensim.models.word2vec_inner import FAST_VERSION, MAX_WORDS_IN_BATCH

__init__.pxd in init gensim.models.word2vec_inner (./gensim/models/word2vec_inner.c:10186)()

ValueError: numpy.dtype has the wrong size, try recompiling

**Comment by piskvorky** [comment]
@shwetatiwari2601 seems unrelated. Feel free to open a new, separate issue.

**Comment by gxyEPFL** [comment]
if already have theano installed, it may fail import interfaces.py. Use anaconda and pip uninstall theano and reinstall gensim, could solve the problem

**Comment by duongtrung** [comment]
I am using windows, anaconda3. Here is the error:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line 65, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line 82, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\idrive\LearningOnTheFly\topic_modeling_lda.py", line 6, in <module>
    from gensim import interfaces, corpora
  File "C:\Anaconda3\lib\site-packages\gensim\__init__.py", line 6, in <module>
    from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
  File "C:\Anaconda3\lib\site-packages\gensim\corpora\__init__.py", line 18, in <module>
    from .sharded_corpus import ShardedCorpus
  File "C:\Anaconda3\lib\site-packages\gensim\corpora\sharded_corpus.py", line 34, in <module>
    import theano
  File "C:\Anaconda3\lib\site-packages\theano\__init__.py", line 55, in <module>
    from theano.compile import \
  File "C:\Anaconda3\lib\site-packages\theano\compile\__init__.py", line 9, in <module>
    from theano.compile.function_module import *
  File "C:\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 18, in <module>
    import theano.compile.mode
  File "C:\Anaconda3\lib\site-packages\theano\compile\mode.py", line 11, in <module>
    import theano.gof.vm
  File "C:\Anaconda3\lib\site-packages\theano\gof\vm.py", line 568, in <module>
    from . import lazylinker_c
  File "C:\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line 117, in <module>
    preargs=args)
  File "C:\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2010, in compile_str
    (status, compile_stderr.replace('\n', '. ')))

**Comment by sletovsky** [comment]
I think I have solved this. It is a problem with how Anaconda handles cyclic dependencies in imports. [This](https://stackoverflow.com/questions/744373/circular-or-cyclic-imports-in-python) article has a discussion of some of the issues, and gave the critical hint, which is to rewrite problematic  lines such as "from gensim import interfaces" lines to 
try:
    from gensim import interfaces
except ImportError:
    interfaces = sys.modules['gensim.interfaces']
This had to be done in about 20 different files, with 1 - 3 imports per file, most commonly involving utils, matutils, and less commonly interfaces, ldamodel, and one other. It took several hours of repeatedly doing "import gensim", observing which line in which file broke, and rewriting the import line, until I got a clean import. I haven't tested extensively yet but from the little I have done it seems to have worked. I am guessing the main gensim developers are not using Anaconda Python 2.7,  but some other distribution that is smarter about cyclic import dependencies, so they never saw this problem.

**Comment by RickOne16** [comment]
Try upgrading your gensim or there are some missing dependencies, use : 
sudo pip install --upgrade gensim
and now try running gensim.

**Comment by nlstmn** [comment]
Hi everyone.
I'm using Python, Django, IDE PyCharm. I imported Gensim for my project, however, seems like Django does not recognize it. Here are my versions: gensim-3.6.0 numpy-1.15.4 scipy-1.1.0 python 3.7.1

The following error is:

I'm using Python, Django, IDE PyCharm. I imported Gensim for my project, however, seems like Django does not recognize it. Here are my versions: gensim-3.6.0 numpy-1.15.4 scipy-1.1.0 python 3.7.1

The following error is:

```
Traceback (most recent call last):
  File "C:/Users/Me/PycharmProjects/sma-capstone-2018/sma_core/brinfluence/lib/doc2vec.py", line 4, in <module>
    import gensim
  File "C:\Users\Me\venv\lib\site-packages\gensim\__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "C:\Users\Me\venv\lib\site-packages\gensim\parsing\__init__.py", line 4, in <module>
    from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2,  # noqa:F401
  File "C:\Users\Me\venv\lib\site-packages\gensim\parsing\preprocessing.py", line 40, in <module>
    from gensim import utils
  File "C:\Users\Me\venv\lib\site-packages\gensim\utils.py", line 40, in <module>
    import scipy.sparse
  File "C:\Users\Me\venv\lib\site-packages\scipy\sparse\__init__.py", line 229, in <module>
    from .csr import *
  File "C:\Users\Me\venv\lib\site-packages\scipy\sparse\csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: DLL load failed: The specified module could not be found.
```

Can someone help me with this?

**Comment by horpto** [comment]
Hi, @nlstmn 
I'm not sure that problem is in django. Can you import gensim (and scipy) from the python shell ? If no, so scipy maybe has not installed properly. Otherwise, it's really problem in django or venv. Maybe something is wrong with sys.path.

**Comment by nlstmn** [comment]
@horpto Thank you for your response. Importing gensim from python sheel gives exactly same error above, however with a command updating or installing it again it says that requirement is already satisfied. I checked sys.path, it doesn't give me any result at all, just three dots. I documentation it says that it suppose to give "False", if there are any errors with path.

**Comment by horpto** [comment]
@nlstmn pip as a many others package installers has an option to force reinstall already installed package. pip has an option `--force-reinstall`. Please, try to reinstall with this option, or else you can just load a wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/ and install manually.

**Comment by menshikh-iv** [comment]
@nlstmn as you see, exception raised by `scipy`, it's better to raise this issue in https://github.com/scipy/scipy/issues
