### ISSUE TITLE
dict2gensim

### ISSUE THREAD

**Issue by bringtree** [RaRe-Technologies/gensim#1982]
#### Description
TODO: change commented example

i have a Word2Vec and it is saved by pickle. it's type is dict .
and now I want to know how can i do, to make the gensim load the dict .
thanks

**Comment by menshikh-iv** [comment]
Hello @bringtree, we have special `save`/`load` methods that should be used for (de)serialization.
I don't understand, where did you get dict? We definitely do not have such a thing.

Please show a code that demonstrates, how you save your model and share this file too, I'll try to help.

FYI use [mailing list](https://groups.google.com/forum/#!forum/gensim) for this kind of questions, issues isn't a good place for it.
