### ISSUE TITLE
Gensim classifies a document as a certain topic despite having no words in common

### ISSUE THREAD

**Issue by lwahedi** [RaRe-Technologies/gensim#1986]
The topic id returned by print_topics is different from the topic id returned when looking at the categorized topics of a document. 

I have trained an LDA model using a tfidf corpus. I then viewed the top 30 words for the top 10 topics with 

`model.print_topics(10,30)`

As expected from the documentation, print_topics gives a list of of tuples, with the first value being the topic id. The first thirty words are enough that the probability of each word is 0 by the end. 

To examine the topics, I use:

```
doc_topics = []
for doc in corpus:
    doc_topics.append(model[doc])
```

`model[doc]` returns a list of tuples containing topic id and probability. But if I examine all documents from the top topic ids returned from` print_topics`, none of the words first thirty words show up. So for example, topic 13 was identified as the top topic, but none of the top thirty words show up at all in the documents that are listed as having some probability of being topic 13. 

To make sure it wasn't an off-by-one error, I also checked 12 and 14, no luck. 

Version information: 

> Linux-4.4.0-66-generic-x86_64-with-debian-8.8
> Python 3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:16:20) 
> [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
> NumPy 1.12.1
> SciPy 1.0.0
> gensim 3.4.0
> FAST_VERSION 1

**Comment by menshikh-iv** [comment]
Hello @lwahedi, "topic" is distribution through all dictionary, i.e. that's OK that you have zero matches in this case (typically, only small number of words have large-enough probabilities in the topic). This means that document contains other words related to 13 topic (but not from top30).

**Comment by lwahedi** [comment]
It's not just one document. None of the top thirty words show up in any of the documents classified as a topic. It could be this was a fluke of my model, but it happened consistently enough that it seemed unlikely to be a coincidence.

**Comment by lwahedi** [comment]
Did some more digging with some toy corpora so that it would be easier to confirm, and they do match up after all. Sorry, thought I'd tried enough examples before posting an issue, but it was just a coincidence with a poor set of topics.

**Comment by menshikh-iv** [comment]
@lwahedi don't worry, all fine, but please next time use mailing list :) Good luck with topic modeling:+1:
