### ISSUE TITLE
KeyError in the LDA model when log is showing the top 5 topics

### ISSUE THREAD

**Issue by epsilon64** [RaRe-Technologies/gensim#1995]
I am running the LDA multicore function using the logging function that will show the top 5 topics as the model passes through the corpus.
After a few passes (occurs randomly) I get the following error

      Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in 
         run_code exec(code_obj, self.user_global_ns, self.user_ns)
      File "<ipython-input-13-378e8a62a33f>", line 1, in <module>
         topic_ = [(self.id2word[id], topic_[id]) for id in bestn]
      File "<ipython-input-13-378e8a62a33f>", line 1, in <listcomp>
          topic_ = [(self.id2word[id], topic_[id]) for id in bestn]
      KeyError: 199704

Problem occurs in the show_topics() function when looping through the chosen_topics (line 881):

        topic = self.state.get_lambda()

        for i in chosen_topics:
            topic_ = topic[i]
            topic_ = topic_ / topic_.sum()  # normalize to probability distribution
            bestn = matutils.argsort(topic_, num_words, reverse=True)

            topic_ = [(self.id2word[id], topic_[id]) for id in bestn]

The last line generates an error as some of the ids are not in my dictionary id2word.
I checked my Document Term Matrix I pass in input and there is no trace of this word anywhere (and if there was, the LDA model wouldn't be able to pass through the corpus several times).

I'm using Python 3.6 with gensim 3.4.
Unfortunately I can't upload any model as it hasn't finished computing.

What I can tell you is that I do have `len(topic_)` equal to `max(self.id2word.keys()) + 1` which is to be expected.

It is important to mention that I am working on a filtered dictionary/DocumentTermMatrix. So the keys in my dictionary are not contiguous as some of the words have been deleted.

The only difference I notice for the topic that triggers the error compared to the others is that the topic_ variable has the same value for all the elements of the vector. I assume that in this case the indices returned by matutils.argsort are somehow random which might cause the error as the index returned will range between 0 and `len(topic_)` but aren't necessarily indices in the dictionary.

So I suspect the problem might come from my dictionary that has gaps between its keys.

Any help on why I get this issue will be much appreciated. Thanks!

**Comment by menshikh-iv** [comment]
Hello @epsilon64,
probably you are right, the problem in your dictionary (gaps isn't a good idea), please call `your_dictionary.compactify()`, convert your data to BoW format with the compactified dictionary and train LDA again.
