### ISSUE TITLE
Feature Suggestion: Save intermediate states of the model while training. 

### ISSUE THREAD

**Issue by ahmedahmedov** [RaRe-Technologies/gensim#1997]
When training a large model, it might take quite a while, sometimes several days, especially if you have set EPOCH to a higher value. 
I think it would be much better if it was possible to save the model in an incremental fashion - that is, save it as soon as Epoch1 is completed, then when Epoch2 is completed and so on. This way, one doesn't have to wait for several days to experiment with the model they created. Or, when, for some reason, one has to cancel the training process in the middle (for example, because the time slot you have reserved on a server has expired), they at least have something, instead of wasting those 3 days with no result at all. 
It should be quite easily, by adding a new parameter to the model.train method (save_icrementally), together with a file_name, and calling model.save every time an Epoch is completed.

**Comment by menshikh-iv** [comment]
Hello @ahmedahmedov, this can be done easily like

```python

for ep in range(10):
    model.train(epoch=1)
    model.save("my_model_ep{}.model".format(ep))
```

Also (if we talk about w2v-based models like w2v, d2v, fasttext, etc), you should write the custom callback that will save your model each epoch.

Probably related issue #451.

**Comment by ahmedahmedov** [comment]
@menshikh-iv Great, thank you!

**Comment by ahmedahmedov** [comment]
> ```
for ep in range(10):
    model.train(epoch=1)
    model.save("my_model_ep{}.model".format(ep))
```
FYI, this doesn't work in the current version. One will get the following error: 

`ValueError: You must specify either total_examples or total_words, for proper job parameters updationand progress calculations. The usual value is total_examples=model.corpus_count.`

The error is closely related to the issue #1981

**Comment by menshikh-iv** [comment]
@ahmedahmedov yes, this is an old headache for us (this was added a long time ago, not in latest refactoring). We definitely need to change it.

**Comment by ahmedahmedov** [comment]
Yeah, I know. thanks for replying.
I wanted to post it just in case someone else faces the same issue. 

On the other hand, saving intermediate states using callables works like a charm.
