### ISSUE TITLE
LDA Python3 - TypeError: '>' not supported between instances of 'float' and 'NoneType'

### ISSUE THREAD

**Issue by budhiraja** [RaRe-Technologies/gensim#2005]
I have trained an LDA model using gensim library and I am using it to extract topic vectors of a document and I am using the following code

    def clean_doc(data_string):    
        global en_stop
        tokenizer = RegexpTokenizer(r'\w+') #Create appropriate tokenizer
        p_stemmer = PorterStemmer() #Create object from Porter Stemmer
        #clean and tokenize document string
        raw = data_string.lower()
        tokens = tokenizer.tokenize(raw)
        # remove stop words from tokens
        stopped_tokens = [i for i in tokens if not i in en_stop]
        # stem tokens
        stemmed_tokens = [p_stemmer.stem(i) for i in stopped_tokens]
        return stemmed_tokens
    
    def infer_lda_vector(s, dictionary, model, dimensions):
        #s = s.decode('utf-8')
        vector = [0.0]*dimensions
        s = clean_doc(s)
        bow_vector = dictionary.doc2bow(s)   
        lda_vector = model[bow_vector]            
        for i in lda_vector:
            vector[i[0]] = i[1]
        return vector

I call it as follows:

    text = "this a test"
    lda_vector = infer_lda_vector(text, dictionary, lda_model, 300)

This exact piece of code was working when I was using Python2.7 but when I updated my system to Python3.x, its throwing the following error:

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-36-723f03d03620> in <module>()
          1 text = "this a a test"
    ----> 2 lda_vector = infer_lda_vector(text, dictionary, lda_model, 300)
          3 lda_vector
    
    <ipython-input-34-885205b68d9e> in infer_lda_vector(s, dictionary, model, dimensions)
         34     s = clean_doc(s)
         35     bow_vector = dictionary.doc2bow(s)
    ---> 36     lda_vector = model[bow_vector]
         37     for i in lda_vector:
         38         vector[i[0]] = i[1]
    
    C:\ProgramData\Anaconda3\lib\site-packages\gensim\models\ldamodel.py in __getitem__(self, bow, eps)
       1158             `(topic_id, topic_probability)` 2-tuples.
       1159         """
    -> 1160         return self.get_document_topics(bow, eps, self.minimum_phi_value, self.per_word_topics)
       1161 
       1162     def save(self, fname, ignore=('state', 'dispatcher'), separately=None, *args, **kwargs):
    
    C:\ProgramData\Anaconda3\lib\site-packages\gensim\models\ldamodel.py in get_document_topics(self, bow, minimum_probability, minimum_phi_value, per_word_topics)
        979         if minimum_probability is None:
        980             minimum_probability = self.minimum_probability
    --> 981         minimum_probability = max(minimum_probability, 1e-8)  # never allow zero values in sparse output
        982 
        983         if minimum_phi_value is None:
    
    TypeError: '>' not supported between instances of 'float' and 'NoneType'

    
What am I doing wrong?

**Comment by menshikh-iv** [comment]
@budhiraja looks strange, can you print `s` and `bow_vector` please

**Comment by budhiraja** [comment]
re-installation fixed it.

**Comment by budhiraja** [comment]
Unfortunately the issue is back again.

```
TypeError                                 Traceback (most recent call last)
<ipython-input-25-598c9bfefa2d> in <module>()
     22             no_docs+=1
     23             continue
---> 24         doc1 = infer_bug_vector(doc.split())
     25         #doc1 = matutils.unitvec(array(doc1)).astype(REAL)
     26         doc = ""

<ipython-input-7-6bbbbe77dea8> in infer_bug_vector(words)
      1 from numpy import array
      2 def infer_bug_vector(words):
----> 3     lda_vector = infer_lda_vector(" ".join(words), dictionary, lda_model, 300)
      4     w2v_vector = infer_vector_w2v(words, w2v_model, 300)
      5     result = lda_vector + w2v_vector

<ipython-input-6-682255facf19> in infer_lda_vector(s, dictionary, model, dimensions)
     34     bow_vector = dictionary.doc2bow(s)
     35     print (bow_vector)
---> 36     lda_vector = model[bow_vector]
     37     print (lda_vector)
     38     vector = [0.0]*dimensions

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\models\ldamodel.py in __getitem__(self, bow, eps)
   1158             `(topic_id, topic_probability)` 2-tuples.
   1159         """
-> 1160         return self.get_document_topics(bow, eps, self.minimum_phi_value, self.per_word_topics)
   1161 
   1162     def save(self, fname, ignore=('state', 'dispatcher'), separately=None, *args, **kwargs):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\models\ldamodel.py in get_document_topics(self, bow, minimum_probability, minimum_phi_value, per_word_topics)
    979         if minimum_probability is None:
    980             minimum_probability = self.minimum_probability
--> 981         minimum_probability = max(minimum_probability, 1e-8)  # never allow zero values in sparse output
    982 
    983         if minimum_phi_value is None:

TypeError: '>' not supported between instances of 'float' and 'NoneType'
```
