### ISSUE TITLE
LDA Python3 - TypeError: '>' not supported between instances of 'float' and 'NoneType'

### ISSUE THREAD

**Issue by budhiraja** [RaRe-Technologies/gensim#2009]
I had reported the same issues some time back and it was fixed by reinstallation but the issue has reappeared and reinstallation is not resolving it.

I have trained an LDA model using gensim library and I am using it to extract topic vectors of a document and I am using the following code

    def clean_doc(data_string):    
        global en_stop
        tokenizer = RegexpTokenizer(r'\w+') #Create appropriate tokenizer
        p_stemmer = PorterStemmer() #Create object from Porter Stemmer
        #clean and tokenize document string
        raw = data_string.lower()
        tokens = tokenizer.tokenize(raw)
        # remove stop words from tokens
        stopped_tokens = [i for i in tokens if not i in en_stop]
        # stem tokens
        stemmed_tokens = [p_stemmer.stem(i) for i in stopped_tokens]
        return stemmed_tokens
    
    def infer_lda_vector(s, dictionary, model, dimensions):
        #s = s.decode('utf-8')
        print (s)
        vector = [0.0]*dimensions
        s = clean_doc(s)
        print (s)
        bow_vector = dictionary.doc2bow(s)   
        lda_vector = model[bow_vector]            
        for i in lda_vector:
            vector[i[0]] = i[1]
        return vector

I call it as follows:

    text = "this a test"
    lda_vector = infer_lda_vector(text, dictionary, lda_model, 300)

This exact piece of code was working when I was using Python2.7 but when I updated my system to Python3.x, its throwing the following error:

```
this is a test on office and firefox
['test', 'offic', 'firefox']
[(4, 1), (85, 1), (1458, 1)]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-ddb10c8f6b5d> in <module>()
      1 text = "this is a test on office and firefox"
----> 2 lda_vector = infer_lda_vector(text, dictionary, lda_model, 300)
      3 lda_vector

<ipython-input-9-62f10637e316> in infer_lda_vector(s, dictionary, model, dimensions)
     36     bow_vector = dictionary.doc2bow(s)
     37     print (bow_vector)
---> 38     lda_vector = model[bow_vector]
     39     print (lda_vector)
     40     vector = [0.0]*dimensions

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\models\ldamodel.py in __getitem__(self, bow, eps)
   1158             `(topic_id, topic_probability)` 2-tuples.
   1159         """
-> 1160         return self.get_document_topics(bow, eps, self.minimum_phi_value, self.per_word_topics)
   1161 
   1162     def save(self, fname, ignore=('state', 'dispatcher'), separately=None, *args, **kwargs):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\models\ldamodel.py in get_document_topics(self, bow, minimum_probability, minimum_phi_value, per_word_topics)
    979         if minimum_probability is None:
    980             minimum_probability = self.minimum_probability
--> 981         minimum_probability = max(minimum_probability, 1e-8)  # never allow zero values in sparse output
    982 
    983         if minimum_phi_value is None:

TypeError: '>' not supported between instances of 'float' and 'NoneType'
```

What am I doing wrong?

**Comment by menshikh-iv** [comment]
@budhiraja looks like a bug (if `self.minimum_probability` is None), you can pass explicitly this parameter to avoid this error.

What's a gensim version you used for training/using LdaModel?

**Comment by budhiraja** [comment]
@menshikh-iv 
I am using version '3.4.0'.
I did the following and its working temporarily:
`lda_model.minimum_probability = 0.001`

However, this error shouldn't be there, right?

**Comment by menshikh-iv** [comment]
@budhiraja right, and I don't understand how this happens (are you sure that you trained LDA with `3.4.0`?)

**Comment by budhiraja** [comment]
No I haven't trained these models on LDA on `3.4.0` but there should be backward compatibility, right?

**Comment by menshikh-iv** [comment]
@budhiraja yes, but backward compatibility can't be infinite, I need exact version of gensim when you trained model (and code for training if you have it)

**Comment by menshikh-iv** [comment]
For clarification, what happens here: 
we have LDA with `self.lda_model.minimum_probability=None`, for this reason, the problem happens. But how we receive `self.lda_model.minimum_probability=None`? Good question, we need more information about versions from @budhiraja.

**Comment by menshikh-iv** [comment]
ping @budhiraja, what's version you used for training?

**Comment by menshikh-iv** [comment]
ping @budhiraja

**Comment by menshikh-iv** [comment]
Not enough information, can't be reproduced.
