### ISSUE TITLE
Dynamic Author Topic Model

### ISSUE THREAD

**Issue by qthurier** [RaRe-Technologies/gensim#2019]
It would be nice to have a dynamic author topic model implemented in gensim. See an [example here](https://www.researchgate.net/profile/Shuo_Xu/publication/257836005_Author-Topic_over_Time_AToT_A_Dynamic_Users'_Interest_Model/links/00463525f3d6b42e65000000.pdf) using Gibbs sampling. Any plan to include something similar?

**Comment by menshikh-iv** [comment]
Hello @qthurier, we already have it (I'm not sure about exact version) as a wrapper: https://radimrehurek.com/gensim/models/wrappers/dtmmodel.html

**Comment by qthurier** [comment]
Thanks menshikh-iv but I'm looking for something that would do both together time   + metadata (for example author) as in the link I mentioned. Maybe I'm missing something, but I don't think it's possible to have both at the same time with dtmmodel or atmmodel?

**Comment by menshikh-iv** [comment]
@qthurier atmmodel can handle only author names (i.e. one modality), about dtmmodel - check [original implementation](https://github.com/magsilva/dtm).

If you want to have any number of modalities for the document simultaneously (i.e. author name, time, special tags, anything else), have a look at [BigARTM](https://bigartm.readthedocs.io/en/stable/), this is slightly complicated from first sight but very flexible and allow to use an arbitrary number of modalities.
