### ISSUE TITLE
Gensim lda update gives index error expElogbetad = self.expElogbeta[:, ids]

### ISSUE THREAD

**Issue by biltu926** [RaRe-Technologies/gensim#2022]
I am using gensim's lda model for topic modelling. I created the id to word mapping using the following : 
dictionary = gensim.corpora.Dictionary(text_content), where text_content is a list of lists containing word tokens.
and then I am creating the model using the following:

```python
corpus = [dictionary.doc2bow(text, allow_update=True) for text in text_content]
lda_model = gensim.models.LdaMulticore(num_topics=number_of_topics, corpus=corpus)
```

the Model is working fine till this point. However, after updating the dictionary with new documents, when I attempt to update the lda model with the new corpus, I get error:

```python
new_corpus = [dictionary.doc2bow(text, allow_update=True) for text in new_text_content]
lda_model.update(new_corpus)

The error:
Traceback (most recent call last):
  File "C:\Users\Parabole\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "C:\Users\Parabole\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Parabole\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 103, in worker
    initializer(*initargs)
  File "C:\Users\Parabole\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\ldamulticore.py", line 277, in worker_e_step
    worker_lda.do_estep(chunk)  # TODO: auto-tune alpha?
  File "C:\Users\Parabole\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\ldamodel.py", line 492, in do_estep
    gamma, sstats = self.inference(chunk, collect_sstats=True)
  File "C:\Users\Parabole\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\models\ldamodel.py", line 444, in inference
    expElogbetad = self.expElogbeta[:, ids]
IndexError: index 50 is out of bounds for axis 1 with size 50
C:\Users\Parabole\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\utils.py:865: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
```

**Comment by menshikh-iv** [comment]
@biltu926 that's expected behavior, you **shouldn't** update dictionary after Lda training (because all inner matrices already allocated and use previous dictionary size for it).

**Possible solutions**
1. (simplest, my recommendation) Fit dictionary only once (on all available data) and use it always (without updates)
2. Use [HashDictionary](https://radimrehurek.com/gensim/corpora/hashdictionary.html) (instead of `Dictionary`), this class using [hashing-trick](https://en.wikipedia.org/wiki/Feature_hashing) and potentially "infinite" (but collision possible)

**Comment by biltu926** [comment]
Thank you for the comment, but is it possible to learn the Model once and keep the flow running so that the Model gets updated with new data. Although i'll try the HashDictionary.

**Comment by menshikh-iv** [comment]
@biltu926 this is possible, but you shouldn't update `Dictionary`. This is right way here: update LDA with **new data** using **old dictionary**.
