### ISSUE TITLE
TypeError: doc2bow expects an array of unicode tokens on input, not a single string

### ISSUE THREAD

**Issue by nvnvashisth** [RaRe-Technologies/gensim#2028]
Hello,

I looked for all suggestion, where everyone says to break the string into tokens by split function. All that has been done already, but still it seems to have same error again and again.

```
for r in words:
        if not r in stop_words:
            processed_txt+=str(str(ps.stem(r) + " "))
    tokenizer = RegexpTokenizer(r'\w+')
    tokens = tokenizer.tokenize(processed_txt)
    #print(tokens)
    dictionary = corpora.Dictionary(tokens)
    #corpus = [dictionary.doc2bow(text) for text in tokens]
    print(dictionary)
```

So now it gives below error.

> raise TypeError("doc2bow expects an array of unicode tokens on input, not a 
> single string")
> TypeError: doc2bow expects an array of unicode tokens on input, not a single 
> string

and the output under "tokens" variable seems like this as below

`['becom', 'effect', 'willingli', 'without', 'need', 'obtain', 'knowledg', 'other', 'obtain', 'acquir', 'must', 'testamentari','claim', 'ownership', 'task', 'establish', 'endow', 'recept', 'willing', 'willsend', 'anoth', 'given', 'efficaci', 'presuppos']`

Please help

**Comment by menshikh-iv** [comment]
Hello @nvnvashisth, first - you need to tokenize your input and after - pass it to the dictionary, like

```python
def my_data():
    tokenizer = RegexpTokenizer(r'\w+')

    for r in words:
            if not r in stop_words:
                processed_txt+=str(str(ps.stem(r) + " "))
            yield tokenizer.tokenize(processed_txt)

dictionary = corpora.Dictionary(my_data())
corpus = [dictionary.doc2bow(text) for text in my_data()]

```
