### ISSUE TITLE
word2vec2tensor.py : Number of tensors do not match the number of lines in metadata

### ISSUE THREAD

**Issue by sashavor** [RaRe-Technologies/gensim#2029]
#### Description
When I used word2vec2tensor.py on my model, the resulting tsv files (_tensor and _metadata) have different dimensions: when I load them into TensorBoard, it tells me that "Number of tensors (10000) do not match the number of lines in metadata (25681)".

Is there a max limit in the number of tensors produced by the code?

#### Expected Results
tensor.tsv and metadata.tsv with the same number 

#### Actual Results
tensor.tsv has 10000 tensors, metadata  has 25681.

#### Versions
"numpy","1.11.0"
"sklearn", "0.17"
"scipy", "0.15.1"
'gensim','3.1.0'

**Comment by menshikh-iv** [comment]
Hello @sashavor, please share your model (needed for reproducing).

**Comment by menshikh-iv** [comment]
So, we have no needed information for reproducing an issue, for this reason, I close it.
@sashavor feel free to re-open when you share a model.
