### ISSUE TITLE
How to use PerplexityMetric with LdaMulticore?

### ISSUE THREAD

**Issue by qthurier** [RaRe-Technologies/gensim#2031]
How can I get the perplexity from LdaMulticore? Since the object doesn't have a callbacks attributes I don't see how to use PerplexityMetric.

**Comment by menshikh-iv** [comment]
@qthurier use this method https://github.com/RaRe-Technologies/gensim/blob/760c6f45420889a78ce5e872e604e3ab9ffb1853/gensim/models/ldamodel.py#L568 

FYI [mailing list](https://groups.google.com/forum/#!forum/gensim) best place for this kind of questions.
