### ISSUE TITLE
Word2Vec evaluate_word_pairs

### ISSUE THREAD

**Issue by sushionthefork** [RaRe-Technologies/gensim#2032]
I am trying to get Pearsons and Spearmans correlation using the method evaluate_word_pairs.
When I run 
`word_vectors.evaluate_word_pairs(os.path.join(module_path, 'test_data','wordsim353.tsv'))`

I get this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 976, in evaluate_word_pairs
    ok_vocab = [(w, self.vocab[w]) for w in self.index2word[:restrict_vocab]]
  File "/usr/local/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 976, in <listcomp>
    ok_vocab = [(w, self.vocab[w]) for w in self.index2word[:restrict_vocab]]
KeyError: '</s>'
```

Versions:
Darwin-17.5.0-x86_64-i386-64bit
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

NumPy 1.14.2
gensim 3.4.0
FAST_VERSION 0

**Comment by menshikh-iv** [comment]
ping @sushionthefork , can you share your model please?

**Comment by sushionthefork** [comment]
I just reloaded my file with my model and it started working, weird.
