### ISSUE TITLE
obsolete python-dateutil requirement

### ISSUE THREAD

**Issue by mirekphd** [RaRe-Technologies/gensim#2034]
#### Description
I had to remove your package from my Dockerfile modeled on the popular Kaggle/docker-python container, because gensim requires indirectly an obsolete version of python-dateutil  [required: <2.7.0,>=2.1]:

The dependency path looks like this:
gensim -> smart-open -> boto3 -> botocore -> python-dateutil

#### Steps/Code/Corpus to Reproduce
```
pip install pipdeptree
pipdeptree --reverse --packages python-dateutil
```

During container building I get this error message:
```
botocore 1.10.4 has requirement python-dateutil<2.7.0,>=2.1, but you'll have python-dateutil 2.7.2 which is incompatible.
```

Output from pipdeptree:
```
python-dateutil==2.7.2
  - arrow==0.12.1 [requires: python-dateutil]
  - bokeh==0.12.15 [requires: python-dateutil>=2.1]
  - botocore==1.10.4 [requires: python-dateutil>=2.1,<2.7.0]
    - boto3==1.7.4 [requires: botocore<1.11.0,>=1.10.4]
      - smart-open==1.5.7 [requires: boto3]
        - gensim==3.4.0 [requires: smart-open>=1.2.1]
[..]
```

**Comment by menshikh-iv** [comment]
Hi @mirekphd, 

you need to upgrade `botocore` to the latest `1.10.6` version for avoid this conflict
https://github.com/boto/botocore/blob/1e34b6be66635d5c1441b074967a38ab0f6b3f84/setup.py#L43

or simply upgrade `boto3` to latest version (dependencies will updated too)
