### ISSUE TITLE
WikiCorpus scans corpus to determine vocabulary when an empty dictionary is provided

### ISSUE THREAD

**Issue by ouromoros** [RaRe-Technologies/gensim#2052]
I have the following code:

```python
wiki = WikiCorpus(inp, dictionary={}, lemmatize=False)
```

When I use it, it tries to scan through the corpus to determine vocabulary, while a dictionary **is** provided.

It clearly violates what is being said in the documentation:
> dictionary (Dictionary, optional) – Dictionary, if not provided, this scans the corpus once, to determine its vocabulary (this needs really long time).

**Comment by piskvorky** [comment]
@ouromoros please report the versions, as per our [issue template](https://raw.githubusercontent.com/RaRe-Technologies/gensim/develop/ISSUE_TEMPLATE.md).

@steremma this seems a bug to introduced here: https://github.com/RaRe-Technologies/gensim/pull/1821/files#diff-eece52d95c280dabe57c803c95d6bb96L335 . That commit changed the logic that worked and that is still documented.

**Comment by ouromoros** [comment]
@piskvorky  Sorry for not including the version, but you're right, that commit is the cause of it. @steremma  's code shoud fix it, so it seems this issue can be closed soon.
