### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by sroder** [RaRe-Technologies/gensim#2054]
#### Description
gensim.model.docvecs.most_similar('A sample string')

**Comment by menshikh-iv** [comment]
@sroder `most_similar` accept list of str (i.e. tokens), not str, see https://radimrehurek.com/gensim/models/keyedvectors.html#gensim.models.keyedvectors.Doc2VecKeyedVectors.most_similar
