### ISSUE TITLE
Error on Gensim based Topic Modeling on Custom Corpus

### ISSUE THREAD

**Issue by telkomops** [RaRe-Technologies/gensim#2055]
After segmentation, when calculating the **Step 2: Probability estimation**
The following error occurs
`per_topic_postings, num_windows = measure.prob(texts=train_texts, segmented_topics=segmented_topics,dictionary=dictionary, window_size=2)`

```python
Anaconda3\lib\site-packages\gensim\topic_coherence\text_analysis.py in __getitem__(self, word_or_words)
125     def __getitem__(self, word_or_words):
126         if isinstance(word_or_words, string_types) or not hasattr(word_or_words, '__iter__'):
--> 127             return self.get_occurrences(word_or_words)
128         else:
129             return self.get_co_occurrences(*word_or_words)

\Anaconda3\lib\site-packages\gensim\topic_coherence\text_analysis.py in get_occurrences(self, word)
193         except KeyError:
194             word_id = word
--> 195         return self._get_occurrences(self.id2contiguous[word_id])
196 
197     def _word2_contiguous_id(self, word):
```

**Windows-8.1-6.3.9600-SP0
Python 3.5.5 |Anaconda, Inc.| (default, Apr  7 2018, 04:52:34) [MSC v.1900 64 bit (AMD64)]
NumPy 1.14.2
SciPy 1.0.0**

Any pointers are greatly appreciated

**Comment by menshikh-iv** [comment]
Hi @telkomops, please provide more information
- python version
- os version
- full example (how to reproduce this error with all input data)
- full traceback

**Comment by menshikh-iv** [comment]
ping @telkomops, please submit needed information

**Comment by menshikh-iv** [comment]
Not enough information, can't be reproduced.
