### ISSUE TITLE
Why I got negative number of model.score(sentences)?

### ISSUE THREAD

**Issue by SefaZeng** [RaRe-Technologies/gensim#2060]
I use Word2Vec model to get the word2vec,and want to classify whether it's a correct sentence or not.
And when i use model.score to get the log probability of this sentence,I got a negative score.Why?
Thx for answering this question:)

**Comment by reneklacan** [comment]
@SefaZeng see scoring implementation https://github.com/RaRe-Technologies/gensim/blob/49e6abdde6bca55b7a5b263c01ecdc94a75fb1ab/gensim/models/word2vec.py#L398-L410 - from my understanding as it's using `log`, negative values are expected
