### ISSUE TITLE
Gensim Summarizer Memory Error

### ISSUE THREAD

**Issue by Shivansh7** [RaRe-Technologies/gensim#2068]
I am getting the Following error while using the Summarizer:
[https://stackoverflow.com/questions/50567108/gensim-summarizer-throws-memoryerror-any-solution](url)

Could you please tell me the workaroud of this problem.

**Comment by Shivansh7** [comment]
I am trying to generate the summary of a large text file using Gensim Summarizer. I am getting memory error. Have been facing this issue since sometime, any help would be really appreciated. feel free to ask for more details.

`from gensim.summarization.summarizer import summarize

file_read =open("xxxxx.txt",'r')
from gensim.summarization.summarizer import summarize


def Summary_gen(content):
    print(len(Content))
    summary_r=summarize(Content,ratio=0.02)
    print(summary_r)


Summary_gen(Content)`

The length of the document is:
`365042`

Error messsage:
`  ---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-6-a91bd71076d1> in <module>()
     10 
     11 
---> 12 Summary_gen(Content)

<ipython-input-6-a91bd71076d1> in Summary_gen(content)
      6 def Summary_gen(content):
      7     print(len(Content))
----> 8     summary_r=summarize(Content,ratio=0.02)
      9     print(summary_r)
     10 

c:\python3.6\lib\site-packages\gensim\summarization\summarizer.py in summarize(text, ratio, word_count, split)
    428     corpus = _build_corpus(sentences)
    429 
--> 430     most_important_docs = summarize_corpus(corpus, ratio=ratio if word_count is None else 1)
    431 
    432     # If couldn't get important docs, the algorithm ends.

c:\python3.6\lib\site-packages\gensim\summarization\summarizer.py in summarize_corpus(corpus, ratio)
    367         return []
    368 
--> 369     pagerank_scores = _pagerank(graph)
    370 
    371     hashable_corpus.sort(key=lambda doc: pagerank_scores.get(doc, 0), reverse=True)

c:\python3.6\lib\site-packages\gensim\summarization\pagerank_weighted.py in pagerank_weighted(graph, damping)
     57 
     58     """
---> 59     adjacency_matrix = build_adjacency_matrix(graph)
     60     probability_matrix = build_probability_matrix(graph)
     61 

c:\python3.6\lib\site-packages\gensim\summarization\pagerank_weighted.py in build_adjacency_matrix(graph)
     92         neighbors_sum = sum(graph.edge_weight((current_node, neighbor)) for neighbor in graph.neighbors(current_node))
     93         for j in xrange(length):
---> 94             edge_weight = float(graph.edge_weight((current_node, nodes[j])))
     95             if i != j and edge_weight != 0.0:
     96                 row.append(i)

c:\python3.6\lib\site-packages\gensim\summarization\graph.py in edge_weight(self, edge)
    255 
    256         """
--> 257         return self.get_edge_properties(edge).setdefault(self.WEIGHT_ATTRIBUTE_NAME, self.DEFAULT_WEIGHT)
    258 
    259     def neighbors(self, node):

c:\python3.6\lib\site-packages\gensim\summarization\graph.py in get_edge_properties(self, edge)
    404 
    405         """
--> 406         return self.edge_properties.setdefault(edge, {})
    407 
    408     def add_edge_attributes(self, edge, attrs):

MemoryError: 

I have tried looking up for this error on the internet, but, couldn't find a workable solution to this.`

**Comment by menshikh-iv** [comment]
Unfortunately, current `summarizer` need to construct a graph from the text in RAM, this is a reason of `MemoryError`

You can try
- reduce the size of your document
- use https://radimrehurek.com/gensim/summarization/mz_entropy.html (but I'm not sure that this what you want)
