### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by anujgupta82** [RaRe-Technologies/gensim#2075]
Getting error :  ZeroDivisionError: float division by zero

https://github.com/RaRe-Technologies/gensim/blob/9481915915bf61aa6e4e719a2f26d509677e6779/gensim/summarization/pagerank_weighted.py#L53

![error](https://user-images.githubusercontent.com/11848354/40821543-3283e832-6585-11e8-9a66-3a4d8ba95eeb.JPG)

**Comment by menshikh-iv** [comment]
Hi @anujgupta82, please give us more information about this problem

- OS version
- Python version
- Gensim version
- Code example for reproducing this error (with all needed data)

**Comment by menshikh-iv** [comment]
ping @anujgupta82

**Comment by LShostenko** [comment]
https://github.com/RaRe-Technologies/gensim/pull/2154

**Comment by menshikh-iv** [comment]
Thank you @LShostenko 

Just duplicate an example for reproducing an issue here
```python
from gensim.summarization import keywords

keywords('gensim')  # raises ZeroDivisionError
keywords('sitio construcción. estaremos línea', deacc=False)  # raises ZeroDivisionError
keywords('sitio construcción. estaremos línea', deacc=True)  # returns empty result
```
