### ISSUE TITLE
Unable to save the Lsi model

### ISSUE THREAD

**Issue by vikash512** [RaRe-Technologies/gensim#2079]
unable to save the LSI model 
/usr/local/lib/python2.7/dist-packages/gensim/interfaces.py:101: UserWarning: corpus.save() stores only the (tiny) iteration object; to serialize the actual corpus content, use e.g. MmCorpus.serialize(corpus)
  "corpus.save() stores only the (tiny) iteration object; "
Code:
bow_vector1=[]
for X in tokenize_data:
    bow_vector1.append(dct.doc2bow(X));

tfidf_vector1=tfidf1_model[bow_vector1]

lsi_vector1=lsi_model[tfidf_vector1]

lsi_vector1.save("/home/vikash/gen/lsi_vector1.lsi", separately=None, sep_limit=10485760, 
                               ignore=frozenset([]), pickle_protocol=2)

**Comment by piskvorky** [comment]
Streamed corpora should be serialized with MmCorpus (not with `save()`). There is a warning that tells you as much if you try to run your code.

See also https://groups.google.com/forum/#!topic/gensim/jgVR5NX-4H0 .
