### ISSUE TITLE
how to give the lsi model as input to train an model in multi layer perceptron

### ISSUE THREAD

**Issue by vikash512** [RaRe-Technologies/gensim#2080]
Here I took the amazon reviews dataset containing two features reviews and sentiment.I had made a model on this using LSI which gives feature vectors.Now I want this model to give as an input to train a model for sentiment analysis using multi layer perceptron. can you tell me the process

**Comment by piskvorky** [comment]
Hi, Github issues are for bugs and enhancements. For general user questions, please use the mailing list: https://radimrehurek.com/gensim/support.html

**Comment by menshikh-iv** [comment]
@vikash512 short answer:
- apply model to dataset (like `model[my_corpus]`)
- convert the result to the dense format (i.e. you have 4 topics and convert output from `[(1, 0.5), (3, 0.3)]` to `[0., 0.5, 0., 3]`
- put it as input to your NN

next time, please use [mailing list](https://groups.google.com/forum/#!forum/gensim) for questions
