### ISSUE TITLE
the probability distribution in LDA

### ISSUE THREAD

**Issue by xiaoxiaofengzi** [RaRe-Technologies/gensim#2082]
After I had trained an LDA model by gensim, I use the statement of get_topics to get the probability distribution of doc and topic. But I find most of them are 0.00, why does this happen? And will it 
influence accuracy？ Thank you very much!

**Comment by menshikh-iv** [comment]
@xiaoxiaofengzi to get distribution for the document, you should use `model[my_document]`, `get_topics` return term-topic matrix (no documents here, see https://radimrehurek.com/gensim/models/ldamodel.html)

Most of them ~0 is expected behaviour (because only some words are significant for topic)
