### ISSUE TITLE
contradiction between the code comments and website tutorial

### ISSUE THREAD

**Issue by adelabdelli** [RaRe-Technologies/gensim#2092]
Hi, 
I found a contradiction between the code comments and the website tutorial, about the sg parameter, so if you look in the code comments you find that if **sg** parameter is **1**, **CBOW** is used, otherwise, **skip-gram** is employed : 
![image](https://user-images.githubusercontent.com/15655871/41426402-65aa7ea8-6ffb-11e8-9265-4f21d2134849.png)

but when i checked [the tutorial website](https://radimrehurek.com/gensim/models/word2vec.html) i found the inverse : 
![image](https://user-images.githubusercontent.com/15655871/41426505-c504ae00-6ffb-11e8-902d-0026048afca7.png)

**Comment by piskvorky** [comment]
Thanks; fixed in #2087.

**Comment by adelabdelli** [comment]
Okey, So sg = 0 is the CBOW model right ?

**Comment by piskvorky** [comment]
Yeah, sg = skip gram.
