### ISSUE TITLE
trying to  get percentage contribution of each topic

### ISSUE THREAD

**Issue by chaithanyateegala** [RaRe-Technologies/gensim#2104]
Hi,
i built the LDA model and getting optimal no. of topics. now i want to get each topic percentage contribution. my first step is
```python
for i, row in enumerate(ldamodel[corpus]):
    row = sorted(row, key=lambda x:x[1], reverse=True)
```
 
but i am getting error  as `TypeError: '<' not supported between instances of 'int' and 'tuple'`

can anyone help me this issue.

Thank you,

**Comment by menshikh-iv** [comment]
This code correct and works with `gensim==3.4.0` and `python2.7`
Double-check that your `corpus` in the correct format.

I used
```python
from gensim.models import LdaModel
from gensim.test.utils import common_corpus as corpus, common_dictionary as dictionary

ldamodel = LdaModel(corpus, id2word=dictionary, num_topics=3)


for i, row in enumerate(ldamodel[corpus]):
    row = sorted(row, key=lambda x:x[1], reverse=True)
    print(row)
```
