### ISSUE TITLE
error i using mallet 

### ISSUE THREAD

**Issue by ahmedbhabbas** [RaRe-Technologies/gensim#2108]
hi 
 i installed mallet in c and it to variable environment in windows 10 and when use it by 
ldamallet = gensim.models.wrappers.LdaMallet(mallet_path, corpus=corpus, num_topics=20, id2word=id2word)  
i got the error 
![image](https://user-images.githubusercontent.com/30591782/41995135-57f71b8c-7a59-11e8-87f3-693a29424513.png)

**Comment by menshikh-iv** [comment]
@ahmedbhabbas please publish
- full stacktrace (not screenshot, just copy it here)
- full code
- corpus/id2word

**Comment by ahmedbhabbas** [comment]
its worked !!!!!!! i don't know whats the matter :)

**Comment by ahmedbhabbas** [comment]
menshikh-iv thank u somuch

**Comment by AbhiRathore** [comment]
> its worked !!!!!!! i don't know whats the matter :)

Hey May you suggest what changes did you made ? I am facing the same issue. Mallet is running from command line ( without using the gensim wrapper) but when I am using the wrapper. It is showing similar error. 'mallet.gz' not found.
