### ISSUE TITLE
Wikipedia : TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by Aarboush** [RaRe-Technologies/gensim#2110]
Hi,

I am following the tutorial about train a doc2vec model with wikipedia corpus on this tutorial : 
https://markroxor.github.io/gensim/static/notebooks/doc2vec-wikipedia.html
i used the function  `TaggedWikiDocument` without the `decode("utf-8")`  in the following manner : 
```python
class TaggedWikiDocument(object)
    def __init__(self, wiki):
        self.wiki = wiki
        self.wiki.metadata = True
    def __iter__(self):
        for content, (page_id, title) in self.wiki.get_texts():
            yield TaggedDocument([c for c in content], [title])
```
After that i trained my model only on PV-DM and i have this problem at the step 10 when i want to use the similarity : 
```python
--> 466             elif doc in self.doctags or doc < self.count:
    467                 mean.append(weight * self.doctag_syn0norm[self._int_index(doc)])
    468                 all_docs.add(self._int_index(doc))

TypeError: '<' not supported between instances of 'str' and 'int'
```
I dont understand why ? if anyone had the same problem. i will be grateful if he answer

Thanks

**Comment by menshikh-iv** [comment]
@Aarboush hello, please add more information
- full code (that reproduced your error)
- full stack-trace
- OS / Python / Gensim version

**Comment by menshikh-iv** [comment]
@Aarboush ping, please submit info mentioned below.

**Comment by menshikh-iv** [comment]
Not enough information to reproduce.
