### ISSUE TITLE
Phrases documentation for threshold argument is misleading

### ISSUE THREAD

**Issue by umangv** [RaRe-Technologies/gensim#2111]
https://github.com/RaRe-Technologies/gensim/blob/37e49971efa74310b300468a5b3cf531319c6536/gensim/models/phrases.py#L252-L255

It feels to me like this should have said the opposite: "**Heavily** depends on concrete scoring-function" rather than "**Hardly** depends on concrete socring-function".

For example, if you choose npmi instead of the default, the threshold has to between -1 and 1, which makes the default (10.0) make no sense. The current documentation suggests that 10.0 will be OK.

**Comment by gojomo** [comment]
I suspect the intended meaning was, as you surmise, "heavily depends"... and the docs around the 'npmi' option should make that acceptable range clear.

**Comment by jenishah** [comment]
**Hardly** has already been replaced by **Heavily**. Would it be a good idea to add the **range** of the score under `returns` in the documentation of the scoring function?
