### ISSUE TITLE
`WmdSimilarity` corpus type mismatch in documentation 

### ISSUE THREAD

**Issue by nooralahzadeh** [RaRe-Technologies/gensim#2112]
#### Description
It seems that the  WmdSimilarity doesn't need the bow_corpus .
The corpus can be in token level, so the following code is not needed:
```python
bow_corpus = [dictionary.doc2bow(document) for document in common_texts]
```

#### Versions
```
Darwin-15.6.0-x86_64-i386-64bit
Python 3.6.3 |Intel Corporation| (default, May  3 2018, 23:25:54) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
NumPy 1.14.3
SciPy 1.1.0
gensim 3.4.0
FAST_VERSION 1
```

**Comment by jagmoreira** [comment]
I'd like to take this issue if no one is working on it already.

**Comment by amartyaamp** [comment]
I think the [documentation page](https://radimrehurek.com/gensim/similarities/docsim.html) still shows the old type - _corpus (iterable of list of (int, float))_

**Comment by menshikh-iv** [comment]
@amartyaamp no, documentation website updates when the new release happens. Last was the 20 of September. Fix was merged 7 of Oct -> documentation will be updated when new release happens

**Comment by horpto** [comment]
@menshikh-iv As I see, many peoples use a dev version of gensim. Maybe is it good idea to show and release version docs and dev version docs?

**Comment by menshikh-iv** [comment]
@horpto we have no way to do that now, but I'm +1 for "documentation versioning" idea (possibility to choose old versions & current `develop`).
