### ISSUE TITLE
Setup script instructions are out of date.

### ISSUE THREAD

**Issue by jtalviste** [RaRe-Technologies/gensim#2118]
Setup script instructions are out of date.

Environment: no C++ build tools.

Running cmd in in windows:
easy_install -U gensim

EDIT: OR running cmd in in windows:
pip install --upgrade gensim

error message:
error: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

Going to http://landinghub.visualstudio.com/visual-cpp-build-tools
Gives 404 - page not found

Suggestion:
replace URL with
https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017

**Comment by menshikh-iv** [comment]
@jtalviste thanks for report! For now - feel free to use `pip install --upgrade gensim` (we have wheels for all popular platforms including windows) or use `conda-forge`.

**Comment by menshikh-iv** [comment]
@jtalviste I don't think so, can you try to `pip install --upgrade gensim`

**Comment by jtalviste** [comment]
yes, that was the first thing I tried. the info is correct

**Comment by menshikh-iv** [comment]
@jtalviste hm, looks suspicious, can you share full log please (from pip install) and try to fully remove & install again?
Also, I still don't understand, where you found http://landinghub.visualstudio.com/visual-cpp-build-tools?

**Comment by jtalviste** [comment]
Sorry, I already got the install working, and it took like hours to download Visual Studio. So at the moment I am not prepared to reproduce it on my end.

I tried easy_install and pip install and they both gave the exact same error message. Just do a search for it in the code base. And replace the URL with what I gave you. Old URL gives 404. I think what I gave is the new correct aadress. Microsoft has changed it. It's the first result in google search for "Microsoft Visual C++ Build Tools"

Again, sorry

**Comment by menshikh-iv** [comment]
Checked, we never mentioned this url, this url from `setuptools` 
```
/.tox/py27-linux/lib/python2.7/site-packages/setuptools/msvc.py:                        r'http://landinghub.visualstudio.com/'
```
https://github.com/pypa/setuptools/blob/master/setuptools/msvc.py#L234

If you want to report an issue, please submit it to [setuptools issue page](https://github.com/pypa/setuptools/issues)

**Comment by jtalviste** [comment]
Okay. Thank you

R, 6. juuli 2018 17:03 Ivan Menshikh <notifications@github.com> kirjutas:
