### ISSUE TITLE
err_rate in IMDB tutorial 

### ISSUE THREAD

**Issue by FMCumhaill** [RaRe-Technologies/gensim#2119]
#### Description
While running the Gensim tutorial notebook on the IMDB sentiment dataset I'm getting an error in cell 8 that err_rate hasn't been defined. I can't see this variable mentioned anywhere above in the notebook either?   

### Error code 
```
`NameError                                 Traceback (most recent call last)
<ipython-input-8-b42daaad37cc> in <module>()
      5     print("\nEvaluating %s" % model)
      6     get_ipython().run_line_magic('time', 'err_rate, err_count, test_count, predictor = error_rate_for_model(model, train_docs, test_docs)')
----> 7     error_rates[str(model)] = err_rate
      8     print("\n%f %s\n" % (err_rate, model))

NameError: name 'err_rate' is not defined`
```

### Notes 
I __am__ running the script with a different dataset, but I __believe__ I have made the correct changes. The only changes where to the first cell dirname 

#### Versions
Windows-10-10.0.16299-SP0
Python 3.6.4 |Anaconda custom (64-bit)| (default, Mar 12 2018, 20:20:50) [MSC v.1900 64 bit (AMD64)]
NumPy 1.14.2
SciPy 1.0.0
gensim 3.4.0
FAST_VERSION 1

**Comment by piskvorky** [comment]
@FMCumhaill Gensim has just been updated, including changes to this notebook.

Can you please try again in Gensim 3.5.0?

**Comment by gojomo** [comment]
It looks like you're already using  the latest notebook – if not from 3.5.0, from post-3.4.0 github develop. The `err_rate` variable is defined and assigned in the line just before (in the destructuring assignment from the 4-tuple return val of `error_rate_for_model()`). So, I'm unsure how a not-defined error can occur a line later. Maybe the IPython magic `%time` isn't working the same in your environment? If so, you could try removing it, at the cost of losing the timing info.

**Comment by FMCumhaill** [comment]
I forked the latest branch and it seems to be working fine now? Thanks for the advice regardless. 

If anyone has this issue in the future I'd suggest trying @gojomo advice, since it seems logically given the issue.
