### ISSUE TITLE
Poincare visualization breaks with plotly 3.0.0    

### ISSUE THREAD

**Issue by brettbj** [RaRe-Technologies/gensim#2123]
#### Description

poincare_2d_visualization - receives the following error - 
ValueError: 
    Invalid value of type 'builtins.str' received for the 'textposition' property of scatter
        Received value: 'bottom'

#### Steps/Code/Corpus to Reproduce
Example:
```
from gensim.viz.poincare import poincare_2d_visualization
import plotly


vis = poincare_2d_visualization(model, tuples, 'Poincare Plot')
```

#### Versions
Please run the following snippet and paste the output below.
Darwin-17.2.0-x86_64-i386-64bit
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.14.3
SciPy 1.1.0
gensim 3.5.0
FAST_VERSION 1
Plotly 3.0.0

**Comment by piskvorky** [comment]
Thanks for reporting @brettbj -- is this a bug in Plotly or in Gensim? Can you fix it?

Ideally in a way that remains compatible: works both in plotly < 3.0.0 and plotly >= 3.0.0 (in case they just renamed or re-ordered some parameters). Cheers.

**Comment by 07Agarg** [comment]
I have installed gensim with the command: ```conda install -c conda-forge gensim``` 

But I am getting the error while importing the library ```gensim.viz```
How to resolve this issue?

**Comment by mpenkov** [comment]
The viz subpackage is no longer part of gensim. It was part of an older version of gensim which is no longer supported.

If you really need gensim.viz, then install an older version of gensim (e.g. 3.8.3), but we can't help you with that.

**Comment by 07Agarg** [comment]
Thank you for quick response!
