### ISSUE TITLE
Can't run Wrapper.LDAmallet via python due to FileNotFoundError & CalledProcessError

### ISSUE THREAD

**Issue by bbiney1** [RaRe-Technologies/gensim#2137]
I posted this issue on a dev branch for mallet, it's about the same problem (and it will probably have more depth cuz I might miss certain details this time around): https://github.com/mimno/Mallet/issues/135#issuecomment-407156116
Based on the response I got, I wanted to bring the issue here. I'm now just going to start copying most of the text from that post. A developer there felt as though the issue is that the gensim wrapper can't quite construct windows directory paths.

I'm using python 3 on windows 10, gensim 3.5.0 and mallet 2.0.8 (with Java SDK 8). I'm alternating between two error messages based on the changes that I make to the `MALLET_BINARY_PATH` variable below. My mallet folder lives in another directory called mallet_unzipped. This is the location to the binary: C:\Users\biney\mallet_unzipped\mallet-2.0.8\bin\mallet

```
from pathlib import Path
home = str(Path.home())
MALLET_BINARY_PATH = home + "\\mallet_unzipped\\mallet-2.0.8\\bin\\mallet" # absolute address
#MALLET_BINARY_PATH ="/c/users/biney/mallet_unzipped/mallet-2.0.8/bin/mallet" # 
doc_term_matrix = [doc_dict.doc2bow(doc) for doc in docs_of_tokens]
Lda_mallet = LdaMallet(mallet_path=MALLET_BINARY_PATH, corpus=doc_term_matrix, id2word=doc_dict, iterations=30)
```

If I run this code as is, with MALLET_BINARY_PATH the first declaration (the one commented with "absolute address"), I get the FileNotFoundError. In this case, MALLET_BINARY_PATH prints: `C:\Users\biney\mallet_unzipped\mallet-2.0.8\bin\mallet`

```
Traceback (most recent call last):
  File "text_mining.py", line 632, in <module>
    main()
  File "text_mining.py", line 563, in main
    mallet_LDA_implementation(name_of_lda="mallet_lda_no_filter_t10", create_dic
t=False, remove_low_freq=False)
  File "text_mining.py", line 458, in mallet_LDA_implementation
    Lda_mallet = LdaMallet(mallet_path=MALLET_BINARY_PATH,  corpus=doc_term_matr
ix, id2word=doc_dict, iterations=30)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 126, in __init__
    self.train(corpus)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 279, in train
    self.word_topics = self.load_word_topics()
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 337, in load_word_topics
    with utils.smart_open(self.fstate()) as fin:
  File "C:\Users\biney\Miniconda3\lib\site-packages\smart_open\smart_open_lib.py
", line 231, in smart_open
    binary, filename = _open_binary_stream(uri, binary_mode, **kw)
  File "C:\Users\biney\Miniconda3\lib\site-packages\smart_open\smart_open_lib.py
", line 318, in _open_binary_stream
    fobj = io.open(parsed_uri.uri_path, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\biney\\AppDa
ta\\Local\\Temp\\db41f1_state.mallet.gz'
```
It seems like what's problematic about this error message is the two backslashes used between directories. However, the way I've been typing in backslashes into python is through the following: '\\' and it's at least printing correctly.
If I comment out the MALLET_BINARY_PATH = home +... and comment in the line below it, I get the following error message:

```
Traceback (most recent call last):
  File "text_mining.py", line 632, in <module>
    main()
  File "text_mining.py", line 563, in main
    mallet_LDA_implementation(name_of_lda="mallet_lda_no_filter_t10", create_dic
t=False, remove_low_freq=False)
  File "text_mining.py", line 458, in mallet_LDA_implementation
    Lda_mallet = LdaMallet(mallet_path=MALLET_BINARY_PATH,  corpus=doc_term_matr
ix, id2word=doc_dict, iterations=30)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 126, in __init__
    self.train(corpus)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 267, in train
    self.convert_input(corpus, infer=False)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 256, in convert_input
    check_output(args=cmd, shell=True)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\utils.py", line 1832,
 in check_output
    raise error
subprocess.CalledProcessError: Command '/c/users/biney/mallet_unzipped/mallet-2.
0.8/bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --
token-regex "\S+" --input C:\Users\biney\AppData\Local\Temp\e0e83e_corpus.txt --
output C:\Users\biney\AppData\Local\Temp\e0e83e_corpus.mallet' returned non-zero
 exit status 1.
```

I've been bouncing back and forth between these errors and I really don't know what they mean or how to set the right foot forward. I have tried copying the command shown in the second error message into git bash and it worked without crashing. I had to make adjustments. This command seems to refer to two temporary files that were created prior to me getting the other two error messages I copied and pasted.

```
~/mallet_unzipped/mallet-2.0.8/bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input ~/AppData/Local/Temp/a0a87d_corpus.txt --output ~/AppData/Local/Temp/a0a87d_corpus.mallet
```

And you may wonder if I tried including `'~'` in the python code... in short, including the `'~'` char gives an "error this character isn't recognizable" message.
Specifying a prefix parameter location seems to always give me an error along the lines of
FileNotFoundError: [Errno 2] No such file or directory: 'mallet_temp/state.mallet.gz'
the 'mallet_temp/state.mallet' used the prefix 'mallet_temp'. Any error message I get shows the prefix location and states that no such file or directory exists with the name and extension shown.

The final attempt I made was the following choices with parameters:

```
prefix_path = "/c/users/biney/Projects/twitter_gmu_2018/mallet_temp/"
Lda_mallet = LdaMallet(mallet_path="/c/users/biney/mallet_unzipped/mallet-2.0.8/bin/mallet", prefix=prefix_path, corpus=doc_term_matrix, id2word=doc_dict, iterations=30)
```
And I get the following error message

```
Traceback (most recent call last):
  File "text_mining.py", line 634, in <module>
    main()
  File "text_mining.py", line 565, in main
    mallet_LDA_implementation(name_of_lda="mallet_lda_no_filter_t10", create_dic
t=False, remove_low_freq=False)
  File "text_mining.py", line 460, in mallet_LDA_implementation
    Lda_mallet = LdaMallet(mallet_path="/c/users/biney/mallet_unzipped/mallet-2.
0.8/bin/mallet", prefix=prefix_path,  corpus=doc_term_matrix, id2word=doc_dict,
iterations=30)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 126, in __init__
    self.train(corpus)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 267, in train
    self.convert_input(corpus, infer=False)
  File "C:\Users\biney\Miniconda3\lib\site-packages\gensim\models\wrappers\ldama
llet.py", line 242, in convert_input
    with smart_open(self.fcorpustxt(), 'wb') as fout:
  File "C:\Users\biney\Miniconda3\lib\site-packages\smart_open\smart_open_lib.py
", line 181, in smart_open
    fobj = _shortcut_open(uri, mode, **kw)
  File "C:\Users\biney\Miniconda3\lib\site-packages\smart_open\smart_open_lib.py
", line 287, in _shortcut_open
    return io.open(parsed_uri.uri_path, mode, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/c/users/biney/Projects
/twitter_gmu_2018/mallet_temp/corpus.txt'
```
What's frustrating from that final error message is that from using file explorer and goingto the /mallet_temp/ directory... there actually is only one file in it called "corpus.txt." So that's suggesting to me that this file is somehow not being found when it actually should be.

**Comment by menshikh-iv** [comment]
> It seems like what's problematic about this error message is the two backslashes used between directories. However, the way I've been typing in backslashes into python is through the following: '\' and it's at least printing correctly.

double-backslashes by "escaping" reason, that's correct path for windows, see an example
```python
>>> a = "\"
  File "<stdin>", line 1
    a = "\"
          ^
SyntaxError: EOL while scanning string literal
>>> a = "\\"
>>> print(a)
\
>>> 
```

> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\biney\\AppData\\Local\\Temp\\db41f1_state.mallet.gz'

can you reproduce this error:
- enable logging
- run your code (and put exact what you run here)
- publish stacktrace + logging messages
- check manually, is this file exist or not (I mean file mentioned in stacktrace)? 

> If I comment out the MALLET_BINARY_PATH = home +... and comment in the line below it, I get the following error message:

`"/c/users/biney/mallet_unzipped/mallet-2.0.8/bin/mallet"` doesn't looks correct for Win system.

> And you may wonder if I tried including '~' in the python code... in short, including the '~' char gives an "error this character isn't recognizable" message.

`~` can't be a part of path, this is an special symbol that "expanded" using console, please use absolute path always

**Comment by Abhishek-Bisht** [comment]
Hi @bbiney1 
In the first case you need to define the OS environment as the below code snippet

```
import os
from gensim.models.wrappers import LdaMallet

os.environ['MALLET_HOME'] = 'C:\\users\\biney\\mallet_unzipped\\mallet-2.0.8'

mallet_path = 'C:\\users\\biney\\mallet_unzipped\\mallet-2.0.8\\bin\\mallet'
ldamallet = LdaMallet(mallet_path,corpus=doc_term_matrix,id2word=doc_dict,iterations=30)
```
It is throwing 'FileNotFoundError' because it is searching for Mallet files it in your base predefined environment.

@menshikh-iv can you please confirm if this works for you as well.

Hope this helps.

**Comment by kothiyayogesh** [comment]
@Abhishek-Bisht : Thanks it works for me :)

**Comment by ismskd** [comment]
dear @Abhishek-Bisht 
i followed ur instruction but still have same error
my code is
`import os
from gensim.models.wrappers import LdaMallet

os.environ['MALLET_HOME'] = 'C:\\mallet-2.0.8'
mallet_path = 'C:\\mallet-2.0.8\\bin\\mallet'
ldamallet = LdaMallet(mallet_path, corpus=corpus, num_topics=20, id2word=id2word)`
and error is
`CalledProcessError: Command 'C:\mallet-2.0.8\bin\mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input C:\Users\ISMAIL\AppData\Local\Temp\a68321_corpus.txt --output C:\Users\ISMAIL\AppData\Local\Temp\a68321_corpus.mallet' returned non-zero exit status 1.`

**Comment by neowangkkk** [comment]
Hi @Abhishek-Bisht ,

I  second @ismskd  that I met the same issue using mac OS. If you could shed lights on this it would be very appreciated.

**Comment by severinsimmler** [comment]
In Python it is generally recommended to use modules like `os` or `pathlib` for file paths – especially under Windows. Since @bbiney1 is already importing `pathlib`, he should also use it:

```python
binary = Path("C:", "users", "biney", "mallet_unzipped", "mallet-2.0.8", "bin", "mallet")
```

So, no more issues handling slashes. And if I remember correctly, one should not use the file `mallet-2.0.8\bin\mallet` under Windows, but `mallet-2.0.8\bin\mallet.bat`.  I have also found that MALLET generally has problems with spaces in file paths, so you should save all resources directly to `C:` if possible.

@neowangkkk, does the MALLET command work _outside_ of Python just as `CalledProcessError` says it does not work? You should try this in a command-line and post the logging here.

**Comment by menshikh-iv** [comment]
Fix of this issue should be in proper checking what exactly we called (related to all `gensim.models.wrappers`, not only Mallet), this is exactly #1485, for this reason, I close that.


@Abhishek-Bisht you variant looks good :+1:

**Comment by neowangkkk** [comment]
@severinsimmler Thanks a lot. I have looked into the command line and did find out the problem.
@ismskd I found the problem is that Mac needs set up for running Mallet:
https://programminghistorian.org/en/lessons/topic-modeling-and-mallet#mac-instructions
After I downloaded the Java SE Development Kit 11 and refreshed (Command + R), my script worked well.

**Comment by matthiaslmz** [comment]
@ismskd

Try adding the `r` infront of your path like this:

mallet_path = r'C:\mallet-2.0.8\bin\mallet'

See if this works!

**Comment by chrysm** [comment]
i fixed it in mac os by removing the tmp dir and running again

**Comment by baranscience** [comment]
Hello there,
I am new in topic modelling, and using google colab for running my project. I have downloaded, and unzipped mallet in google drive, and I wanna use it in my project in google colab:

from google.colab import drive
drive.mount('/content/gdrive')
import os
os.environ['MALLET_HOME'] = '/content/gdrive/My Drive/mallet-2.0.8'
mallet_path = 'content/gdrive/My Drive/mallet-2.0.8/bin/mallet'
model = LdaMallet(mallet_path, corpus=common_corpus, num_topics=20, id2word=common_dictionary)

but i got this error:

/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-37-539820b8f7c0> in <module>()
----> 1 model = LdaMallet(mallet_path, corpus=common_corpus, num_topics=20, id2word=common_dictionary)
      2 vector = model[common_corpus[0]]  # LDA topics of a documents

3 frames
/usr/local/lib/python3.6/dist-packages/gensim/models/wrappers/ldamallet.py in __init__(self, mallet_path, corpus, num_topics, alpha, id2word, workers, prefix, optimize_interval, iterations, topic_threshold)
    124         self.iterations = iterations
    125         if corpus is not None:
--> 126             self.train(corpus)
    127 
    128     def finferencer(self):

/usr/local/lib/python3.6/dist-packages/gensim/models/wrappers/ldamallet.py in train(self, corpus)
    265 
    266         """
--> 267         self.convert_input(corpus, infer=False)
    268         cmd = self.mallet_path + ' train-topics --input %s --num-topics %s  --alpha %s --optimize-interval %s '\
    269             '--num-threads %s --output-state %s --output-doc-topics %s --output-topic-keys %s '\

/usr/local/lib/python3.6/dist-packages/gensim/models/wrappers/ldamallet.py in convert_input(self, corpus, infer, serialize_corpus)
    254             cmd = cmd % (self.fcorpustxt(), self.fcorpusmallet())
    255         logger.info("converting temporary corpus to MALLET format with %s", cmd)
--> 256         check_output(args=cmd, shell=True)
    257 
    258     def train(self, corpus):

/usr/local/lib/python3.6/dist-packages/gensim/utils.py in check_output(stdout, *popenargs, **kwargs)
   1877             error = subprocess.CalledProcessError(retcode, cmd)
   1878             error.output = output
-> 1879             raise error
   1880         return output
   1881     except KeyboardInterrupt:

CalledProcessError: Command '/gdrive/My Drive/mallet-2.0.8/bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input /tmp/e4915d_corpus.txt --output /tmp/e4915d_corpus.mallet' returned non-zero exit status 127.

**Comment by piskvorky** [comment]
@baranscience seems unrelated. Please open a new issue (but check the exact Mallet error first, by running the same command from the command line).
