### ISSUE TITLE
Duplication of code of phrases module

### ISSUE THREAD

**Issue by robguinness** [RaRe-Technologies/gensim#2149]
I was going to submit a minor pull request for the phrases module, but then I noticed that the `__getitem__` methods of the classes `Phrases` and `Phraser` are identical. Would it be a good idea to move this code to a higher level, e.g. the `PhrasesTransformation` class, or somehow merge the duplicated code?

**Comment by menshikh-iv** [comment]
Sounds good @robguinness, thanks for the tip!

**Comment by jenishah** [comment]
If anyone is not working on this, can I take this task?

**Comment by menshikh-iv** [comment]
@jenishah of course, feel free to submit PR

**Comment by robguinness** [comment]
Thanks, @jenishah !
