### ISSUE TITLE
"AttributeError: 'Visdom' object has no attribute 'updateTrace'" when running "Training_visualizations.ipynb"

### ISSUE THREAD

**Issue by yingchengsun** [RaRe-Technologies/gensim#2155]
"updateTrace" has been deprecated in the newest version of  Visdom, but it is still being called in Gensim, so failed to run callbacks in "Training_visualizations.ipynb". Hope this issue can be fixed, thanks!
See
https://github.com/facebookresearch/visdom/issues/358

**Comment by menshikh-iv** [comment]
Thanks for report @yingchengsun.
What should we use now instead of this function? What's concrete version of when this was removed?

**Comment by yingchengsun** [comment]
One author of Visdom (JackUrb) said "Rather than calling updateTrace, you can simply use scatter or line with the update you want to make. ", but I tried to use scatter or line, still could not see the plot results, maybe you can have a try? 
See
https://github.com/facebookresearch/visdom/issues/359

Also, I failed to find the concrete version of when this was removed. No clues.

**Comment by wpf535236337** [comment]
add the  flag (update = 'append') in your line func
