### ISSUE TITLE
Mallet Gensim error. (Non-zero exit status 1)

### ISSUE THREAD

**Issue by shettyprithvi** [RaRe-Technologies/gensim#2163]
Hi all,

Please help me with the following error. I tried a lot to fix it but with no help.

Code:
```python
import os 
os.environ.update({'MALLET_HOME':r'C:/Users/I870648/mallet-2.0.8/'})

mallet_path = 'C:\\Users\\I870648\\mallet-2.0.8\\bin\\mallet\\'
ldamallet = gensim.models.wrappers.LdaMallet(mallet_path, corpus=corpus, num_topics=20, id2word=id2word)
```
Error:
```python
CalledProcessError: Command 'C:\Users\I870648\mallet-2.0.8\bin\mallet\ import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input C:\Users\I870648\AppData\Local\Temp\3c1484_corpus.txt --output C:\Users\I870648\AppData\Local\Temp\3c1484_corpus.mallet' returned non-zero exit status 1.
```
Thank you,

Sincerely,
Prithvi

**Comment by menshikh-iv** [comment]
Hi @shettyprithvi, can you try to run the command from `Error` and check what happens, please?

**Comment by menshikh-iv** [comment]
btw, I know what's wrong in your code: `mallet_path` should be a path to executable, just remove last `\\` from `mallet_path`

**Comment by piskvorky** [comment]
@DongShanHu looks like you might need to escape the `\` characters: `C:\\Users\\` etc.

**Comment by menshikh-iv** [comment]
Great, thank you @vivek2589 :+1:

**Comment by DongShanHu** [comment]
@vivek2589 thank you, I really appreciate your help

**Comment by piyushsharma1812** [comment]
@vivek2589 thank you. i am wondering why it was not working when i unzipped in a different drive

**Comment by ismskd** [comment]
Dear @vivek2589 
 I copied your code but still facing same problem. I also used single quotes as well as double quotes.
My code is
`import os
from gensim.models.wrappers import LdaMallet

os.environ.update({'MALLET_HOME':r'C:/mallet-2.0.8/'})
mallet_path = 'C:\mallet-2.0.8\bin\mallet' # update this path

ldamallet = LdaMallet(mallet_path, corpus=corpus, num_topics=20, id2word=id2word)

result=(ldamallet.show_topics(num_topics=20,num_words=5,formatted=False))
for each in result:
print(each)`

and error is
CalledProcessError: Command 'C:\mallet-2.0.8\bin\mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input C:\Users\ISM\AppData\Local\Temp\1a8a10_corpus.txt --output C:\Users\ISM\AppData\Local\Temp\1a8a10_corpus.mallet' returned non-zero exit status 1.

plz help me

**Comment by domingo-han** [comment]
Dear @vivek2589, 
thank you.

I did that copied your code below but still facing same problem.   i am wondering why it was not working when i unzipped in a same drive and provided path for the same.

----------------------------------------------------------------------------
import os
from gensim.models.wrappers import LdaMallet

os.environ.update({'MALLET_HOME':r'C:/new_mallet/mallet-2.0.8/'})
mallet_path = 'C:/new_mallet/mallet-2.0.8/bin/mallet' # update this path

ldamallet = LdaMallet(mallet_path, corpus=corpus, num_topics=20, id2word=id2word)

-------------------------------------------------------------------------------
result
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-114-d0523dba7637> in <module>()
      4 os.environ.update({'MALLET_HOME':r'C:/new_mallet/mallet-2.0.8/'})
      5 mallet_path = 'C:/new_mallet/mallet-2.0.8/bin/mallet' # update this path
----> 6 ldamallet = LdaMallet(mallet_path, corpus=corpus, num_topics=20, id2word=id2word)

~\Anaconda3\lib\site-packages\gensim\models\wrappers\ldamallet.py in __init__(self, mallet_path, corpus, num_topics, alpha, id2word, workers, prefix, optimize_interval, iterations, topic_threshold)
    124         self.iterations = iterations
    125         if corpus is not None:
--> 126             self.train(corpus)
    127 
    128     def finferencer(self):

~\Anaconda3\lib\site-packages\gensim\models\wrappers\ldamallet.py in train(self, corpus)
    265 
    266         """
--> 267         self.convert_input(corpus, infer=False)
    268         cmd = self.mallet_path + ' train-topics --input %s --num-topics %s  --alpha %s --optimize-interval %s '\
    269             '--num-threads %s --output-state %s --output-doc-topics %s --output-topic-keys %s '\

~\Anaconda3\lib\site-packages\gensim\models\wrappers\ldamallet.py in convert_input(self, corpus, infer, serialize_corpus)
    254             cmd = cmd % (self.fcorpustxt(), self.fcorpusmallet())
    255         logger.info("converting temporary corpus to MALLET format with %s", cmd)
--> 256         check_output(args=cmd, shell=True)
    257 
    258     def train(self, corpus):

~\Anaconda3\lib\site-packages\gensim\utils.py in check_output(stdout, *popenargs, **kwargs)
   1804             error = subprocess.CalledProcessError(retcode, cmd)
   1805             error.output = output
-> 1806             raise error
   1807         return output
   1808     except KeyboardInterrupt:

CalledProcessError: Command 'C:/new_mallet/mallet-2.0.8/bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input C:\Users\CHRISH~1\AppData\Local\Temp\59a66f_corpus.txt --output C:\Users\CHRISH~1\AppData\Local\Temp\59a66f_corpus.mallet' returned non-zero exit status 1.

-----------------------------------------------------------------------------------------------------------

**Comment by ismskd** [comment]
@vivek2589 thank you so much

**Comment by ronykroy** [comment]
> 
> 
> can you create a new folder ('new_mallet') in c:/ drive and unzip the mallet there and try to re-run the code below again
> ----------------------------------Run this code---------------------------------------
> import os
> from gensim.models.wrappers import LdaMallet
> 
> os.environ.update({'MALLET_HOME':r'C:/new_mallet/mallet-2.0.8/'})
> mallet_path = 'C:/new_mallet/mallet-2.0.8/bin/mallet' # update this path
> 
> ldamallet = LdaMallet(mallet_path, corpus=corpus, num_topics=20, id2word=id2word)
> 
> result=(ldamallet.show_topics(num_topics=20,num_words=5,formatted=False))
> for each in result:
> print(each)

Not sure why.. but this worked..

**Comment by clastro** [comment]
> > can you create a new folder ('new_mallet') in c:/ drive and unzip the mallet there and try to re-run the code below again
> > ----------------------------------Run this code---------------------------------------
> > import os
> > from gensim.models.wrappers import LdaMallet
> > os.environ.update({'MALLET_HOME':r'C:/new_mallet/mallet-2.0.8/'})
> > mallet_path = 'C:/new_mallet/mallet-2.0.8/bin/mallet' # update this path
> > ldamallet = LdaMallet(mallet_path, corpus=corpus, num_topics=20, id2word=id2word)
> > result=(ldamallet.show_topics(num_topics=20,num_words=5,formatted=False))
> > for each in result:
> > print(each)
> 
> Not sure why.. but this worked..

I had a same problem with you.
instead of your code, here code is doing well.

 os.environ.update({'MALLET_HOME':r'C:/new_mallet/mallet-2.0.8/'})
 mallet_path = '/mallet-2.0.8/bin/mallet' # update this path

The variable of 'mallet_path' is changed.

**Comment by mpenkov** [comment]
It looks like there have been multiple attempts to hijack this issue. The original issue is marked as closed because it was caused by user error (executable path ends with slash).

> mallet_path = 'C:\\Users\\I870648\\mallet-2.0.8\\bin\\mallet\\'

If anyone is having a similar problem, please open a new ticket, and be sure to fill out the template.
