### ISSUE TITLE
Doc2Vec understanding why are there many docvectors made?

### ISSUE THREAD

**Issue by darvid7** [RaRe-Technologies/gensim#2167]
#### Description
TODO: change commented example

I expected the `Doc2Vec` model to make the number of paragraph vectors equal to the number of tags used to train the model.

In the below code snipped it looks like the count of the `docvecs` is equal to the maximum tag. I'm not too sure why.
#### Steps/Code/Corpus to Reproduce

```python
"""
Doc2Vec learns representations for words and labels simultaneously.
If you wish to only learn representations for words,
you can use the flag train_lbls=False in your Doc2Vec class. Similarly,
if you only wish to learn representations for labels and leave the word
representations fixed, the model also has the flag train_words=False.
"""
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

EPOCHS = 500
LEARNING_RATE = 0.0001
DIMENSIONS = 100

sentences = [
    TaggedDocument(["hi", "there"], [1]),
    TaggedDocument(["byte"], [2]),

]
model = Doc2Vec(vector_size=DIMENSIONS, window=2, min_count=1, alpha=LEARNING_RATE, workers=4)

model.build_vocab(sentences, update=False, trim_rule=None)
print("paragraph embeddings: %s" % len(model.docvecs))  # 3.
print("docvecs count %s" % model.docvecs.count)  # 3.
print(model.docvecs.doctags)  # {}
print("Offset %s" % model.docvecs.offset2doctag)  # []
print(len(model.docvecs.vectors_docs))  # 3.
```

outputs
```
paragraph embeddings: 3
docvecs count 3
{}
Offset []
3
```
Which is along the lines of what I expected because only two tags are used. I don't really get why there are 3 elements in `model.docvecs`?

When I change the max tag to 200 for example

```python
sentences = [
    TaggedDocument(["hi", "there"], [1]),
    TaggedDocument(["byte"], [200]),

]
model = Doc2Vec(vector_size=DIMENSIONS, window=2, min_count=1, alpha=LEARNING_RATE, workers=4)
```
The output changes to 
```
paragraph embeddings: 201
docvecs count 201
{}
Offset []
201
```

Why does this occur? Does this mean 200 vectors are made even though there are only two tags in the corpus?

#### Expected Results

*N/A*
#### Actual Results

*N/A*

#### Versions

Darwin-15.6.0-x86_64-i386-64bit
Python 3.6.4 (default, Jan 6 2018, 11:49:38)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
NumPy 1.15.1
SciPy 1.1.0
gensim 3.5.0
FAST_VERSION 0

**Comment by menshikh-iv** [comment]
@darvid7

> Which is along the lines of what I expected because only two tags are used. I don't really get why there are 3 elements in model.docvecs?

 that's expected behaviour, if doctags are `int`, number of doctags are `max(doctags)` (and doctag#0 never be trained, because this missed in training set).

> Why does this occur? Does this mean 200 vectors are made even though there are only two tags in the corpus?

See previous answer.

If you want to receive "exact" number of doctags, just convert doctags to string, like
```python
from gensim.models.doc2vec import Doc2Vec, TaggedDocument


EPOCHS = 500
LEARNING_RATE = 0.0001
DIMENSIONS = 100

sentences = [
    TaggedDocument(["hi", "there"], ["1"]),
    TaggedDocument(["byte"], ["200"]),

]
model = Doc2Vec(vector_size=DIMENSIONS, window=2, min_count=1, alpha=LEARNING_RATE, workers=4)

model.build_vocab(sentences, update=False, trim_rule=None)
print("paragraph embeddings: %s" % len(model.docvecs))  # 3.
print("docvecs count %s" % model.docvecs.count)  # 3.
print(model.docvecs.doctags)  # {}
print("Offset %s" % model.docvecs.offset2doctag)  # []
print(len(model.docvecs.vectors_docs))  # 3.

```

output:
```
paragraph embeddings: 2
docvecs count 2
{'1': Doctag(offset=0, word_count=2, doc_count=1), '200': Doctag(offset=1, word_count=1, doc_count=1)}
Offset ['1', '200']
2

```
