### ISSUE TITLE
How to use gensim.models.doc2vec.TaggedDocument.count()

### ISSUE THREAD

**Issue by darvid7** [RaRe-Technologies/gensim#2171]
#### Description
How do you use `gensim.models.doc2vec.TaggedDocument.count()` it keeps returning 0 for me?
Also, is it acceptable to pass a list of integers to `TaggedDocument`? It accepts it but the docs say it should be a list of unicode string tokens. 

#### Steps/Code/Corpus to Reproduce

```Python
from gensim.models.doc2vec import TaggedDocument

a = TaggedDocument(words=["1", "2"], tags=[1])
print(repr(a))
b = TaggedDocument(words=["1", "2", "1"], tags=["1"])
print(repr(b))
print(b.count("1"))  # 0

c = TaggedDocument(words=[1, 2, 1], tags=[1])
print(repr(c))
print(c.count(1))  # 0
print(c.count("1"))  # 0
```
#### Expected Results

I assumed `.count()` would return the occurance of a word in the list passed in to `words` so something like:

```python
b = TaggedDocument(words=["1", "2", "1"], tags=["1"])
print(b.count("1"))  # 1

c = TaggedDocument(words=[1, 2, 1], tags=[1])
print(repr(c))
print(c.count(1))  # 1
print(c.count("1"))  # 0
```
#### Actual Results

```python
b = TaggedDocument(words=["1", "2", "1"], tags=["1"])
print(b.count("1"))  # 0

c = TaggedDocument(words=[1, 2, 1], tags=[1])
print(repr(c))
print(c.count(1))  # 0
print(c.count("1"))  # 0
```

Everything had a count of 0.

#### Versions

Darwin-15.6.0-x86_64-i386-64bit
Python 3.6.4 (default, Jan  6 2018, 11:49:38) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
NumPy 1.15.1
SciPy 1.1.0
gensim 3.5.0
FAST_VERSION 0

**Comment by menshikh-iv** [comment]
Hi @darvid7,

`TaggedDocument` class just wrapper for handle tokens + tag for model (inherited from `namedtuple`). 

For give frequency of word you should specify concrete field first, like

```python
d = TaggedDocument(["a", "a", "c", "b", "b"], [1, 2])

assert d.words.count("a") == 2
assert d.words.count("b") == 2
assert d.words.count("c") == 1
assert d.words.count("nonexist") == 0
```

About types - you should pass list of `str` as `words` and list of `int/str` as `tags`.

**Comment by piskvorky** [comment]
@darvid7 if the documentation of `TaggerDocument` is not clear, can you open a PR that makes it clearer? Thanks!
