### ISSUE TITLE
Glove  embeddings

### ISSUE THREAD

**Issue by SriniNaga** [RaRe-Technologies/gensim#2174]
Do we have a python  implementatipn for Glove embeddings  in Gensim?

**Comment by menshikh-iv** [comment]
@SriniNaga we can load pre-trained glove vectors using [KeyedVectors.load_word2vec_format](https://radimrehurek.com/gensim/models/keyedvectors.html#gensim.models.keyedvectors.Word2VecKeyedVectors.load_word2vec_format) but we don't plan to implement training in gensim, feel free to use original stanford implementation https://github.com/stanfordnlp/GloVe

**Comment by SriniNaga** [comment]
@menshikh-iv  Thank you!
