### ISSUE TITLE
Feature suggestion: relative cosine similarity for word2vec 

### ISSUE THREAD

**Issue by viplexke** [RaRe-Technologies/gensim#2175]
Hi all,
Based on this paper, do you think it worths the effort to implement relative cosine similarity measure? 
https://ufal.mff.cuni.cz/pbml/105/art-leeuwenberg-et-al.pdf

Note that I'm not suggesting this as a potential contributor but as a grateful user.
Thank you,
Viktor

**Comment by menshikh-iv** [comment]
Thanks for request @viplexke, I quickly looked at the article: IMO doesn't look very useful for including it to gensim. Also, the formula for `relative cosine similarity` looks pretty simple (i.e. any person who need this can implement it self).

CC: @gojomo @piskvorky

**Comment by gojomo** [comment]
It's interesting that it seems to help highlight synonyms, as opposed to other kinds of related words. If it could be done as a single short method in KeyedVectors, I think it'd be a good contribution – even though it's not hard for other to implement, sometimes people only discover new techniques by browing APIs. (Any implementation should cite this origin paper.)

**Comment by ailsamm** [comment]
@gojomo @menshikh-iv How exactly would I go about implementing this "as a single short method in KeyedVectors" (as you say @gojomo ). Excuse the question - I'm very new to Gensim. Thanks!

**Comment by ailsamm** [comment]
@gojomo Thanks so much! I got it working now.

**Comment by rawannasser** [comment]
> @gojomo Thanks so much! I got it working now.

Hi dear ailsamm
I need to implement the same measure, can you provide me the code please since it works with you 
I really need it :(

**Comment by rawannasser** [comment]
> Hi dear @ailsamm I need to implement the same measure, can you provide me the code please since it works with you
> I really need it :(

**Comment by ailsamm** [comment]
@rawannasser Sure! How should I send it?

**Comment by rawannasser** [comment]
@ailsamm
Thanks so much! 
 I don't know if I can write my email here but maybe you can upload it in your GitHub?

**Comment by gojomo** [comment]
@ailsamm Can you submit your implementation as a pull-request for potential integration to the project?

**Comment by jenishah** [comment]
Hi,
Is anyone working on this?
If not, I would like to take this up.

**Comment by piskvorky** [comment]
@jenishah go ahead please :)

**Comment by rsdel2007** [comment]
If anyone is not working on this can I contribute?

**Comment by menshikh-iv** [comment]
feel free to contribute @rsdel2007

**Comment by rawannasser** [comment]
@rsdel2007 yes, please
