### ISSUE TITLE
Gensim FastText() on custom corpus generates only .bin file ??

### ISSUE THREAD

**Issue by PrithivirajDamodaran** [RaRe-Technologies/gensim#2176]
I am using the Gensim implementation of FastText to train a custom corpus of text (and I don't want to use the pre-trained ones) . But the below command only saves the model as .bin file and there is no equivalent .vec file. Is this by design ? or am I missing something ?

>  model = FastText(sentences, size=embedding_size, window=10, min_count=1, iter=10, word_ngrams=1, sg=0, max_vocab_size=5000)

>  model.save("somename")
> 

please advice

**Comment by menshikh-iv** [comment]
Hi @PrithivirajDamodaran,

File `"somename"` produced by `save` method store model in gensim-custom format that not compatible with FB implementation. By idea, this is same as FB `.bin` (store full model, taining can be continued after loading), can be loaded by Gensim (can't by FB implementation).

About FB `.vec` - it's just word-vectors in text format, see example below 

```
from gensim.test.utils import common_texts
from gensim.models import FastText

model = FastText(common_texts, size=4, window=3, min_count=1, iter=10)

model.wv.save_word2vec_format("my_file.txt")  # this produce same file as FB .vec file
```

Please use [mailing list](https://groups.google.com/forum/#!forum/gensim) for this kind of questions in future, github issues only for bug-reports and feature-requests.

**Comment by PrithivirajDamodaran** [comment]
> Please use mailing list for this kind of questions in future, github issues only for bug-reports and feature-requests.

Noted and Thanks !
