### ISSUE TITLE
Defining alphabet

### ISSUE THREAD

**Issue by BehroozMansouri91** [RaRe-Technologies/gensim#2177]
I trying to use fast text for new language that I made to parse some text. I want to define my own set of characters so for instance, instead of a,b,c  I want to consider a12, b23, c34 as  a character when dealing with n-grams. Can any one inform me where I can edit this part? or how should I do it? is it possible?

**Comment by menshikh-iv** [comment]
Hello @BehroozMansouri91, this can be done in a simple way: just replace each of `a12`, `b23` to 1 character that doesn't happen in the corpus, for example  `"a12b23helloc34" -> "@#hello~"`, where
```haskell
"a12" -> "@"
"b23" -> "#"
"c34" -> "~"
```

please use [mailing list](https://groups.google.com/forum/#!forum/gensim) for this kind of questions in future
