### ISSUE TITLE
Training and accessing word vectors using Doc2Vec

### ISSUE THREAD

**Issue by darvid7** [RaRe-Technologies/gensim#2179]
Hi! I was looking into how to get word vectors after training them using `doc2vec`. Issue #1513 outlined you can get the raw word vectors using `model.wv.syn0`. However, when I access these vectors before and after training the model the values are the same. Am I missing something? How can I access the trained word vectors after training a `Doc2Vec` model?

Also, according to the docs, the parameter `dbow_words=1` will train word vectors simultaneously with `DBOW`. Does this mean `dbow_words=1` only works with `dm=0` (PV-DBOW)? 
Is there a way to train word vectors with `dm=1` (PV-DM)? 

#### Description
How to get trained word vectors after training with `Doc2Vec`?

#### Steps/Code/Corpus to Reproduce

```python
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

corpus = [
    "foo bar fork",
    "water wind fire earth",
    "artificial intelligence is the new electricity"
]


def corpus_generator(corpus):
    tag_template = "%s_special_thing_here"
    for i, sentence in enumerate(corpus):
        yield TaggedDocument([str(c) for c in sentence.split()], [tag_template % i])


model = Doc2Vec(
    vector_size=100,
    min_count=1,
    alpha=0.001,
    workers=1,
    window=1,
    dbow_words=1,  # Trains word vectors in skip-gram fashion simultaneous with DBOW.
    dm=0  # if 1 trains PV-DM (distributed memory), otherwise is 0 and trains PV-DBOW (distributed bag of words).
)

model.build_vocab(corpus_generator(corpus))

# Check wvs are created.
untrained_word_vectors = []
for word_vec in model.wv.syn0:
    untrained_word_vectors.append(word_vec[::])

model.train(
    corpus_generator(corpus),
    epochs=500,
    total_examples=len(corpus)
)

trained_word_vectors = []
for word_vec in model.wv.syn0:
    trained_word_vectors.append(word_vec[::])

for i, untrained_vector in enumerate(untrained_word_vectors):
    trained_vector = trained_word_vectors[i]
    if untrained_vector.all() == trained_vector.all():
        print("wv[%s] has not trained and is the same before and after training the model" % i)
    else:
        print("wv[%s] has been trained" % i)
```
```
Outputs:
wv[0] has not trained and is the same before and after training the model
wv[1] has not trained and is the same before and after training the model
wv[2] has not trained and is the same before and after training the model
wv[3] has not trained and is the same before and after training the model
wv[4] has not trained and is the same before and after training the model
wv[5] has not trained and is the same before and after training the model
wv[6] has not trained and is the same before and after training the model
wv[7] has not trained and is the same before and after training the model
wv[8] has not trained and is the same before and after training the model
wv[9] has not trained and is the same before and after training the model
wv[10] has not trained and is the same before and after training the model
wv[11] has not trained and is the same before and after training the model
wv[12] has not trained and is the same before and after training the model
```
#### Expected Results

Word vectors accessed via `model.wv.syn0` before and after training to be different.
#### Actual Results

Word vectors are the same.
#### Versions

Darwin-15.6.0-x86_64-i386-64bit
Python 3.6.4 (default, Jan  6 2018, 11:49:38) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
NumPy 1.15.1
SciPy 1.1.0
gensim 3.5.0
FAST_VERSION 0

**Comment by gojomo** [comment]
Main issue here is that the numpy-array-slice into `untrained_word_vectors` is saving a *view* on the working array, so changes with the training, so this code will never detect any training that is occurring. Further explanation & other issues with code answered on discussion list: https://groups.google.com/d/msg/gensim/vGrnyFwPqd8/rIBBLarNCQAJ

No bug or feature-request here, so closing.
