### ISSUE TITLE
Mmap not working as expected with KeyedVectors

### ISSUE THREAD

**Issue by neelasha23** [RaRe-Technologies/gensim#2183]
#### Description
Mmap not working as expected when loading KeyedVectors in two different processes. We are working on MAC 10.12.6 , and Python 3.6. We have tried loading the keyedVectors from file using mmap option as mentioned in the documentation: https://radimrehurek.com/gensim/models/keyedvectors.html

#### Steps/Code/Corpus to Reproduce
import os
import psutil
from gensim.models import KeyedVectors
import time
import numpy as np
def memory_usage_psutil():
    import psutil
    process = psutil.Process(os.getpid())
    print ("PID: ", os.getpid())
    mem = process.memory_info()[0] / float(2 ** 20)
    return mem

model=KeyedVectors.load("/Users/coviam/Documents/GloveData/output.kv", mmap='r')
print("Memory consumption in MB : %s",memory_usage_psutil())
print("Done")
time.sleep(100)

#### Expected Results
Memory should have been shared between the two processes and not doubled.

#### Actual Results
For Two separate processes loading .kv file :
Both process have 289M of memory (no sharing) in ‘r’ mode

#### Versions
NumPy 1.15.0
SciPy 1.1.0
gensim 3.5.0
FAST_VERSION 0

**Comment by piskvorky** [comment]
Are you sure you're measuring what you think you're measuring?

Memory management works differently on Mac, and there's no concept of "SHR" like on Linux.

Either way, Gensim simply calls [numpy.load(mmap_mode)](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.load.html) from numpy. If it doesn't work, it's a bug in numpy – please open a ticket there, nothing we can do on our end.
