### ISSUE TITLE
Get some numpy error when running doc2vec

### ISSUE THREAD

**Issue by cjhih456** [RaRe-Technologies/gensim#2193]
Hi i get some numpy error on linux server(amazon ec2 service)
#### tested pc
os : window
python : 3.7
pip : 18.0
numpy : 1.15.1
gensim : 3.5.0
scipy : 1.1.0

#### dev server(has error)
os : linux
instance type : t2.large
python : 3.6
anaconda-client : 1.7.2
anaconda-navigator : 1.8.7
anaconda-project : 0.8.2
numpy : 1.15.1
gensim : 3.5.0
scipy : 1.1.0

i was reinstalled dev server's numpy,gensim and scipy. but disabled to fix it.

doc2vec config
```
config= {
    'dm': 1,  
    'dbow_words': 1,  
    'window': 4,  
    'vector_size': 200,  
    'alpha': 0.025,  
    'sample': 1e-4,
    'seed': 1234,
    'min_count': 3,  
    'min_alpha': 0.025,  
    'workers': multiprocessing.cpu_count(),  
    'hs': 1,  
    'negative': 5,  
    'epochs': 10  
}
model = Doc2Vec(**config)
```
error message
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 164, in _worker_loop
    tally, raw_tally = self._do_train_job(data_iterable, job_parameters, thread_private_mem)
  File "/home/user/.local/lib/python3.6/site-packages/gensim/models/doc2vec.py", line 660, in _do_train_job
    doctag_vectors=doctag_vectors, doctag_locks=doctag_locks
  File "gensim/models/doc2vec_inner.pyx", line 535, in gensim.models.doc2vec_inner.train_document_dm
```

**Comment by menshikh-iv** [comment]
Hi @cjhih456, can you please provide more info

- full stack trace (now I see part of it, but exception missing)
- minimal code example that reproduce this error (not only configuration, don't forget about data),

**Comment by cjhih456** [comment]
now i catched that error.
@menshikh-iv  thank you for your attention.

that was need more data for making model.
thank you!
