### ISSUE TITLE
Version 3.6.0 doesn't install files gensim/models/doc2vec_corpusfile.so, gensim/models/fasttext_corpusfile.so, gensim/models/word2vec_corpusfile.so

### ISSUE THREAD

**Issue by yurivict** [RaRe-Technologies/gensim#2198]
It writes these names into the plist files for the ```--record``` option (```setup.py install --record {plist}```), but doesn't actually install them:
```
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%PYTHON_SITELIBDIR%%/gensim/models/doc2vec_corpusfile.so
Error: Missing: %%PYTHON_SITELIBDIR%%/gensim/models/fasttext_corpusfile.so
Error: Missing: %%PYTHON_SITELIBDIR%%/gensim/models/word2vec_corpusfile.so
```

**Comment by menshikh-iv** [comment]
Hi @yurivict, is you install `gensim` from source (or tarball)? If yes - probably fix already here #2194, if not - I'm not fully understand, what's `--record <ARG>` and why this needed? Can you clarify this point please?

**Comment by yurivict** [comment]
```--record {plsit}``` is a feature of python ```distutils``` that records the list of files that it installs. So it installs the files, and also records the list at the same time. The list should match the files, and in your case there's a mismatch.

We install a tarball from PyPI.

**Comment by menshikh-iv** [comment]
@yurivict can you please check it again with [gensim-3.6.0.tar.gz](https://github.com/RaRe-Technologies/gensim/files/2409496/gensim-3.6.0.tar.gz) (is issue still here or fixed?). This tarball builded from 62687e951dd0667f8257ace826a646529cbaff4c

**Comment by yurivict** [comment]
This tarball is free from this problem.

**Comment by menshikh-iv** [comment]
Great, thanks for verification @yurivict, this means that fix already there in #2194.

**Comment by piskvorky** [comment]
@menshikh-iv and which version is on PyPI? Is there an issue with the latest release for users who install with pip (no wheel), or not?

**Comment by menshikh-iv** [comment]
@piskvorky latest (`3.6.0`).
An issue exists for the person who installs the last version from tarball (no wheels).
