### ISSUE TITLE
How to pick the number of topics with Umass measure?

### ISSUE THREAD

**Issue by guntherzhao** [RaRe-Technologies/gensim#2199]
I am trying to use Umass measure to pick the best number of topics, but I do not know what Umass exactly means? About the coherence score, is it the bigger, the better, or just the opposite? Below is the output of my test with Umass measure. How many topics should I pick?
![image](https://user-images.githubusercontent.com/43496800/45965139-3e52bf00-c05a-11e8-9b23-4e4d9684475a.png)

**Comment by menshikh-iv** [comment]
@guntherzhao answered in https://github.com/RaRe-Technologies/gensim/pull/710#issuecomment-425344644
