### ISSUE TITLE
Pivoted normalization for tfidf model

### ISSUE THREAD

**Issue by javier-artiles** [RaRe-Technologies/gensim#220]
I was wondering if this is of interest to other gensim users. When dealing with a wide range of document sizes pivoted normalization allows a finer tuning of the weight given to terms relative to document size. This is crucial in some document similarity scenarios.

I'm currently testing a modification on the tfidf model code to add this feature. Unfortunately my numpy/scypy knowledge is limited, and right now I have a very inefficient implementation.

A couple of references on the topic:
http://singhal.info/pivoted-dln.pdf
http://nlp.stanford.edu/IR-book/html/htmledition/pivoted-normalized-document-length-1.html

![download](https://cloud.githubusercontent.com/assets/6756638/3592389/5ba18ec0-0c71-11e4-852d-687cd04d09d2.png)

**Comment by tmylk** [comment]
@jotaefea Are you still interested in adding this feature?

**Comment by jotaefea** [comment]
Hi Lev, it's been a while. But I'll be happy to send some code for
review :-)

**Comment by tmylk** [comment]
@jotaefea Will be happy to accept a pivoted normalization PR

**Comment by jotaefea** [comment]
Thank you Lev. I'll try to get something out to you soon.

- J

**Comment by gabrielspmoreira** [comment]
I use (sklearn TfIdfTransformation and cosine_similarity with Eucliean Normalization) and I am running on problems for similarity calculation with long documents , which probably share many of the possible tokens with other documents just because they are long. I am looking for an implementation of Pivoted normalization.

**Comment by tmylk** [comment]
Add to wiki ideas page

**Comment by piskvorky** [comment]
@tmylk is that a note to self, or a suggestion for somebody else to add it?

**Comment by menshikh-iv** [comment]
@javier-artiles hello, right now @markroxor works on this task and we stuck on evaluation step, have you works with TREC dataset ever?

**Comment by javier-artiles** [comment]
Hi @menshikh-iv , I'm afraid I have not worked on TREC tasks. During my researcher years I did mostly organize my own competitive evaluation ([WePS](https://github.com/javier-artiles/weps)) for document clustering.

**Comment by menshikh-iv** [comment]
@javier-artiles thanks, probably we'll try to evaluate pivot normalization using your WePS.

**Comment by javier-artiles** [comment]
I would suggest to use it on more standard information retrieval tasks (ad hoc retrieval for instance). It may be easier to interpret the results that way. Of course it all depends on your end goal regarding this evaluation.

**Comment by javier-artiles** [comment]
Also, I apologize I never got around sending a PR for this feature. To be completely sincere I have not been a contributor to open source. Personal and private projects have always kept me too busy.

**Comment by menshikh-iv** [comment]
@javier-artiles If you could recommend concrete datasets & tasks, it will be really nice for us!

**Comment by javier-artiles** [comment]
It would depend on what your end goal is. Are you just trying to test an implementation of this normalization scheme? If that is the case you can write simple unit tests with minimal data.
If you are looking for a model quality benchmark then traditional dev/test datasets make sense. 
TREC would be the way to go if you want to show public benchmark results that are easy to compare. Unfortunately most TREC data I know of is not freely available. This data is available through the [Linguistic Data Consortium site](https://catalog.ldc.upenn.edu/topten) at pretty steep fees (unless your research institution is footing the bill :-) ).
As an alternative you can look into the [CLEF collections](http://direct.dei.unipd.it/). I can't tell for sure, but it would seem their data is accessible after registration.
Finally, the datasets section of this page may give you some useful pointers https://github.com/harpribot/awesome-information-retrieval#datasets

As for the tasks themselves any standard _ad-hoc IR_ task would make sense IMHO.

**Comment by markroxor** [comment]
@javier-artiles Can we have a small discussion about this on https://gitter.im/RaRe-Technologies/gensim ?
