### ISSUE TITLE
GUnicorn + Flask + Gensim -> Error: dictionary changed size during iteration

### ISSUE THREAD

**Issue by patvdleer** [RaRe-Technologies/gensim#2204]
#### Description
I'm trying to create a microservice for certain functions based on previously built models. To avoid blowing up the RAM I am trying to run the app with `--preload` on gunicorn, since I don't write but only read the models I figured this shouldn't be a problem but as soon as I try to even load gensim the app crashes.

#### Steps/Code/Corpus to Reproduce
```python
import flask
from gensim.models import KeyedVectors, Word2Vec

app = flask.Flask(__name__)

@app.route('/')
def index():
    return ""
```

#### Expected Results
```
$ gunicorn mem_test:app --workers 2
[2018-10-02 10:39:19 +0200] [27406] [INFO] Starting gunicorn 19.9.0
[2018-10-02 10:39:19 +0200] [27406] [INFO] Listening at: http://127.0.0.1:8000 (27406)
[2018-10-02 10:39:19 +0200] [27406] [INFO] Using worker: sync
[2018-10-02 10:39:19 +0200] [27418] [INFO] Booting worker with pid: 27418
[2018-10-02 10:39:19 +0200] [27419] [INFO] Booting worker with pid: 27419
```

#### Actual Results
```
$ gunicorn mem_test:app --workers 2 --preload
[2018-10-02 10:36:17 +0200] [24018] [INFO] Starting gunicorn 19.9.0

Error: dictionary changed size during iteration
```

#### Versions
```
$ python3.6 
Python 3.6.6 (default, Jun 28 2018, 04:42:43) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Linux-4.8.0-58-generic-x86_64-with-Ubuntu-16.04-xenial
>>> import sys; print("Python", sys.version)
Python 3.6.6 (default, Jun 28 2018, 04:42:43) 
[GCC 5.4.0 20160609]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.14.2
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.0.1
>>> import gensim; print("gensim", gensim.__version__)
gensim 3.5.0
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 1
```

**Comment by menshikh-iv** [comment]
Hello @patvdleer 

Note that this is some issues with how `--prefork` exactly works (not a gensim issue), but I'll try to help you.
Please include at least full stack trace (I see only `dictionary changed size during iteration`, but no idea where it comes from) and  describe, what exactly gunicorn do with `--preload` option

**Comment by patvdleer** [comment]
Well....

```python
try:
    import flask
    import traceback

    from gensim.models import KeyedVectors, Word2Vec

    app = flask.Flask(__name__)

    @app.route('/')
    def index():
        return ""


except BaseException as e:
    print(e)
    traceback.print_stack()
```

```
$ gunicorn mem_test2:app --workers 2 --preload
[2018-10-02 11:04:19 +0200] [23511] [INFO] Starting gunicorn 19.9.0

Error: dictionary changed size during iteration
```

**Comment by menshikh-iv** [comment]
@patvdleer I'm not sure that your code works here (just print something else to be sure, because output are same as the previous variant), please understand how exactly
- `gunicorn` run application server (here, you run "gunicorn wrapper", not python)
- how `--prefork` works

after this, you'll have an idea, how to get the full trace.

**Comment by menshikh-iv** [comment]
ping @patvdleer, any updates?

**Comment by menshikh-iv** [comment]
BTW, I ran mentioned code with 
- `python2.7`/ `python3.6, 
- `gensim==3.6.0`
- `gunicorn==19.9.0`

Works as expected, issue doesn't happend.
