### ISSUE TITLE
Phrases not working correctly with both the scoring methods

### ISSUE THREAD

**Issue by prashantbudania** [RaRe-Technologies/gensim#2213]
#### Description
gensim.models.phrases not working correctly with either of the scoring methods

#### Steps/Code/Corpus to Reproduce

Example:
``` 
from gensim.test.utils import datapath
from gensim.models.word2vec import Text8Corpus
from gensim.models.phrases import Phrases, Phraser

sentences = Text8Corpus(datapath('testcorpus.txt'))
phrases = Phrases(sentences, min_count=2, threshold=10)
#phrases = Phrases(sentences, min_count=2, threshold=0.2, scoring='npmi')
phrases.vocab 
```

#### Expected Results
Bigrams with min count of 2

#### Actual Results
Bigrams with count 1 are part of the vocabulary
![screen shot 2018-10-04 at 3 54 12 pm](https://user-images.githubusercontent.com/16194274/46499330-cd47a000-c7ed-11e8-97ee-24666e2282e8.png)

#### Versions
```
Darwin-18.0.0-x86_64-i386-64bit
(u'Python', '2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]')
(u'NumPy', '1.14.3')
(u'SciPy', '1.1.0')
(u'gensim', '3.6.0')
(u'FAST_VERSION', 1)
```

**Comment by piskvorky** [comment]
`phrases.vocab` doesn't represent bigrams. Use `phrases[sentence]` to get bigrams.

See the module documentation at https://radimrehurek.com/gensim/models/phrases.html .
