### ISSUE TITLE
where is Gensim CBOW_mean implemented in the original implementation?

### ISSUE THREAD

**Issue by thegrimreaper1992** [RaRe-Technologies/gensim#2221]
Hi,

I was looking at the original word2vec implementation here at: https://code.google.com/archive/p/word2vec/source/default/source
The part o the code I'm talking about is: (Where CBOW is being trained)
![originalwv](https://user-images.githubusercontent.com/43973925/46698706-c782fd80-cbe5-11e8-940f-1810c800bf52.png)

However I couldn't find any lines corresponding to:
![gensimwv](https://user-images.githubusercontent.com/43973925/46698904-44ae7280-cbe6-11e8-8b24-43703bb7e93f.png)

Which is in the gensim code.  Can anyone please help me understand which part is this analogous to?

I really appreciate your time.

**Comment by menshikh-iv** [comment]
@thegrimreaper1992 GitHub isn't a suitable place for questions (only bug reports or feature requests should be here), please use [mailing list](https://groups.google.com/forum/#!forum/gensim) for questions.

Related: #1873
CC: @gojomo
