### ISSUE TITLE
LdaMulticore parameter alpha: 'auto' not supported but documentation says it is

### ISSUE THREAD

**Issue by johann-petrak** [RaRe-Technologies/gensim#2223]
When using the value 'auto' for parameter "alpha" for LdaMulticore, the following exception is raised:
```
NotImplementedError: auto-tuning alpha not implemented in multicore LDA; use plain LdaModel.
```
(ldamulticore.py, line 146)

However the documentation string of the `__init__` states that "auto" is supported.

This may be a copy/paste error, but is there any chance to see auto get supported for the Multicore version as well? 

#### Versions
```
Linux-4.15.0-35-generic-x86_64-with-debian-buster-sid
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0]
NumPy 1.14.2
SciPy 1.0.0
gensim 3.4.0
FAST_VERSION 1
```

However, the exception code is still present in the latest master as well, I think.

**Comment by menshikh-iv** [comment]
Hello @johann-petrak, thanks for the report: that's really copy-paste issue.

> is there any chance to see auto get supported for the Multicore version as well

Most likely no, sorry

**Comment by johann-petrak** [comment]
> Hello @johann-petrak, thanks for the report: that's really copy-paste issue.
> 
> > is there any chance to see auto get supported for the Multicore version as well
> 
> Most likely no, sorry

Could you explain why? The Mallet implementation does this while being mult-threaded (I understand how multi-processing is different from multi-threaded). I would just like to understand what the limitation is. 
Estimating alpha from the data is something one often wants to do, but having to resort to a single thread is a high cost for that.

**Comment by johann-petrak** [comment]
Created https://github.com/RaRe-Technologies/gensim/pull/2225 for this

**Comment by johann-petrak** [comment]
Also just noticed that 'auto' is not available for LdaModel if it is used in distributed mode, this should also get added to the documentation.

**Comment by menshikh-iv** [comment]
@johann-petrak I think better to ask @piskvorky or @ziky90 about it.
