### ISSUE TITLE
`pyemd` import check is misplaced

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#2228]
Gensim only checks whether `pyemd` in installed once, on module load:
https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/keyedvectors.py#L755

All other calls to `wmdistance` will automatically fail, even if the `pyemd` module has been installed in the meanwhile.

This is unnecessary and annoying. Python is a dynamic language, we can import the module when needed (= where the check is actually happening, in `wmdistance`), not at the top.

Plus let's fix the `werein` typo in `At least one of the documents had no words that werein the vocabulary` and the non-Pythonic `len(document1) == 0` while at it. The code could use some style clean up.

**Comment by kishan3** [comment]
Sir, please explain what is a pythonic way to equality. Also where to import `emd` if not at the beginning.

**Comment by menshikh-iv** [comment]
@kishan3 I think @piskvorky mean "import pyemd when this needed", i.e. directly in `wmdistance` function.

**Comment by kishan3** [comment]
@menshikh-iv ok got you.

**Comment by Naba7** [comment]
Can I be assigned this issue?

**Comment by Naba7** [comment]
@menshikh-iv I have opened a pr.

**Comment by menshikh-iv** [comment]
@Naba7 of course, feel free to contribute (continue with your #2247)

**Comment by menshikh-iv** [comment]
Fixed by #2240
