### ISSUE TITLE
error with the Dictionary attiribute of corpora

### ISSUE THREAD

**Issue by ChandanKumarSahu** [RaRe-Technologies/gensim#2238]
Traceback (most recent call last):
  File "topic_modelling.py", line 11, in <module>
    dictionary = corpora.Dictionary(doc_clean)
AttributeError: module 'corpora' has no attribute 'Dictionary'

**Comment by menshikh-iv** [comment]
Hello @ChandanKumarSahu,

just import it correctly
```python
from gensim.corpora import Dictionary

dictionary = Dictionary(doc_clean)
```
