### ISSUE TITLE
Seems like list of VERY BIG lists caused TypeError  problem

### ISSUE THREAD

**Issue by MOSSupport** [RaRe-Technologies/gensim#2241]
#### Description
Seems like list of VERY BIG lists caused this problem

#### Steps/Code/Corpus to Reproduce
```
import csv
import pandas as pd
import gensim
import pickle
from gensim import corpora, models, similarities

from gensim.models import CoherenceModel
from pprint import pprint  # pretty-printer
from collections import defaultdict

dirname = './'
if __name__ =="__main__":
   texts = []

   with open( dirname+'texts.list','rb') as f: <<< I attached tests.zip file
      texts = pickle.load(f)

#   pprint(texts)
#   for text in texts:
#       print(text)
   dictionary = corpora.Dictionary(texts) <<< error

   n_items = len(dictionary)
```

#### Expected Results
make dictionary with out Type error

#### Actual Results
$ python bug.py > texts.out
Traceback (most recent call last):
  File "bug.py", line 26, in <module>
    dictionary = corpora.Dictionary(texts)
  File "/home/smpark/miniconda3/lib/python3.7/site-packages/gensim/corpora/dictionary.py", line 83, in __init__
    self.add_documents(documents, prune_at=prune_at)
  File "/home/smpark/miniconda3/lib/python3.7/site-packages/gensim/corpora/dictionary.py", line 202, in add_documents
    self.doc2bow(document, allow_update=True)  # ignore the result, here we only care about updating token ids
  File "/home/smpark/miniconda3/lib/python3.7/site-packages/gensim/corpora/dictionary.py", line 245, in doc2bow
    counter[w if isinstance(w, unicode) else unicode(w, 'utf-8')] += 1
TypeError: decoding to str: need a bytes-like object, float found

#### Versions
$ python version.py
Linux-4.15.0-36-generic-x86_64-with-debian-buster-sid
Python 3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0]
NumPy 1.15.2
SciPy 1.1.0
gensim 3.6.0
FAST_VERSION 1

[texts.zip](https://github.com/RaRe-Technologies/gensim/files/2514632/texts.zip)

**Comment by horpto** [comment]
Hi, @MOSSupport 
I've checked your data and found that first doc contains a some NaN (number that not a number)
19440 and 19442 indexes of first doc is wrong. I think other docs also contain float-s

**Comment by MOSSupport** [comment]
Thanks for your comments, actually I did dropna(), but I will look over again.
Best regards,
MOSSupport

**Comment by MOSSupport** [comment]
Dear horpto,
I checked nan from texts.out, so I will check my data.
And thanks for your comments again.
Best regrads,
MOSSupport
