### ISSUE TITLE
indptr, indices, and data in stochastic_svd

### ISSUE THREAD

**Issue by brianayoung** [RaRe-Technologies/gensim#2246]
When I try to run stochastic_svd (from models.lsimodel.py) on its own, I get "has no attribute" error messages with regard to indptr, indices, and data (lines 926-927 and 958-960). It works fine when I run the LSI model as a whole. Where are these defined?

I realize this is a question and not an issue; tried posting on the Google group with nothing yet. Think it might be a bit technical for that forum, so thanks in advance if you can help here.

**Comment by piskvorky** [comment]
@brianayoung what are you running, with what results, what are you expecting?

Please follow the [issue template](https://github.com/RaRe-Technologies/gensim/blob/develop/ISSUE_TEMPLATE.md). Thanks.

**Comment by menshikh-iv** [comment]
@brianayoung `stohastic_svd` is an internal function (i.e. not for public usage), please use `LsiModel` instead.
