### ISSUE TITLE
How to save a dictionary for later using?

### ISSUE THREAD

**Issue by hcji** [RaRe-Technologies/gensim#2255]
#### Description
Is there any way to save a dictionary for later using?

**Comment by menshikh-iv** [comment]
Of course, see `save` and `load` methods in documentation https://radimrehurek.com/gensim/corpora/dictionary.html#gensim.corpora.dictionary.Dictionary.load


```python

my_dict = Dictionary(...)
my_dict.save("/path/to/dict.pth")

loaded_dict = Dictionary.load("/path/to/dict.pth")
```

Next time, please use [mailing list](https://groups.google.com/forum/#!forum/gensim) for questions, github only for bug reports/feature requests.
