### ISSUE TITLE
How to handle word out of vocabulary in word2vec?

### ISSUE THREAD

**Issue by JrSurapaneni** [RaRe-Technologies/gensim#2266]
#### Description
How to handle word out of vocabulary while using word Word2vec keyed vector approach?

**Comment by menshikh-iv** [comment]
Word2Vec can't handle OOV, you need to use FastText for example 
```python

>>> from gensim.models import FastText
>>> sentences = [["cat", "say", "meow"], ["dog", "say", "woof"]]
>>>
>>> model = FastText(sentences, min_count=1)
>>> say_vector = model.wv['say']  # get vector for word
>>> of_vector = model.wv['of']  # get vector for out-of-vocab word
```

More information in [documentation](https://radimrehurek.com/gensim/models/fasttext.html)

Next time, please use [mailing list](https://groups.google.com/forum/#!forum/gensim) for questions, GitHub for bug reports and feature requests.
