### ISSUE TITLE
Word2VecKeyedVectors (& maybe other KeyedVectors) give AttributeError if you try to add() 

### ISSUE THREAD

**Issue by DanielDIQA** [RaRe-Technologies/gensim#2268]
Hi there,

excuses for cross posting with your news group!
Thank you for the superb gensim-module which we find extremely helpful for our text analytics projects!

#### Description
We stumbled upon an issue when we load the pre-trained google news word vectors: 
we are unable to add random word vectors to the map because the "add"-method is not provided. 

#### Steps/Code/Corpus to Reproduce
`import pysvn`
`import numpy as np`
`import gensim`
`# assuming that GoogleNews-vectors-negative300.bin is extracted to local disk drive:`
`# URL: https://github.com/mmihaltz/word2vec-GoogleNews-vectors/blob/master/GoogleNews-vectors-negative300.bin.gz`
`# local path: D:/training-data/word2vec/GoogleNews-vectors-negative300.bin`
`googleNewsModel = gensim.models.KeyedVectors.load_word2vec_format('D:/training-data/word2vec/GoogleNews-vectors-negative300.bin', binary=True) `
`googleNewsModel.add(list('unknown word'), list(np.random.random(300))) `

#### Expected Results
New token, vector are added to the model.

#### Actual Results
`returns error: AttributeError: 'Word2VecKeyedVectors' object has no attribute 'add' `

Traceback (most recent call last):

  File "<ipython-input-1-f0d2181562f3>", line 1, in <module>
    runfile('C:/Users/hansch/../gensim_issue.py', wdir='C:/Users/hansch/../eurolex')

  File "C:\Users\hansch\AppData\Local\conda\conda\envs\gpupy36gensim\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\Users\hansch\AppData\Local\conda\conda\envs\gpupy36gensim\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/hansch/../gensim_issue.py", line 11, in <module>
    googleNewsModel.add(list('unknown word'), list(np.random.random(300))) # add the token and the random wordvector to the google News word vectors

AttributeError: 'Word2VecKeyedVectors' object has no attribute 'add'

#### Versions
windows server 2012
python 3.6
gensim 3.6.0

**Comment by gojomo** [comment]
Gensim's various `KeyedVectors` classes con't support individual additions, via either any `add()` method or other methods. (Did you see something in some docs/examples that suggested they did?)

At best, this is a feature-request for a new capability. 

The shortest-path to achieving it yourself might be to convert the on-disk file to an easier-to-edit format (like the text alternative), then explicitly edit it to append new words/values (while also changing the count of total word that appears at the start).

**Comment by AliceGab** [comment]
Hi, I have a similar issue : 
I want to load only the first 100,000 words of the model and add a few useful words from the complete model that are not present in the 100,000 subset, therefore use add.
This link shows add functions... [https://radimrehurek.com/gensim/models/keyedvectors.html](url)

**Comment by AliceGab** [comment]
Sorry for the late reply @gojomo. 
```
model = KeyedVectors.load_word2vec_format('./inputs/GoogleNews-vectors-negative300.bin',binary = True,limit=100000)  

# Add words that are not in the 100,000 subset but are still useful 
# index = words, values = vectors 
model_rare_words = pd.read_csv('./inputs/model_rare_useful_words.csv', index_col = 0)

model.add(entities = list(model_rare_words.index), weights = model_rare_words.values, replace=False)
```

Getting this error 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-95-7102ab78e8c1> in <module>
      3 model = KeyedVectors.load_word2vec_format('./inputs/GoogleNews-vectors-negative300.bin',binary = True,limit=100000)
      4 
----> 5 model.add(entities = list(model_rare_words.index), weights = model_rare_words.values, replace=False)

AttributeError: 'Word2VecKeyedVectors' object has no attribute 'add'
```

**Comment by menshikh-iv** [comment]
@DanielDIQA @AliceGab @yucc2018 sorry, but it works as expected (issue not reproduced)

python2.7, gensim3.6

```python
import gensim.downloader as api
import numpy as np
from gensim.models import KeyedVectors

path = api.load("glove-wiki-gigaword-50", return_path=True)
model = KeyedVectors.load_word2vec_format(path)

entities = ["@@@", "###"]
vectors = np.random.rand(2, 50)

model.add(entities=entities, weights=vectors, replace=True)

assert np.allclose(model["@@@"], vectors[0])
assert np.allclose(model["###"], vectors[1])
```

BTW, attribute really exists 

```python
from gensim.models.keyedvectors import Word2VecKeyedVectors, Doc2VecKeyedVectors, FastTextKeyedVectors


for m in [Word2VecKeyedVectors, Doc2VecKeyedVectors, FastTextKeyedVectors]:
    assert getattr(m, "add", False)
```
Try to re-install latest gensim.
