### ISSUE TITLE
questions about self.vocabulary

### ISSUE THREAD

**Issue by phoenixzxj** [RaRe-Technologies/gensim#2272]
![image](https://user-images.githubusercontent.com/19839217/48824010-e7d5d880-ed9d-11e8-982d-102c5e80da75.png)
In the script base_any2vec.py, the class BaseWordEmbeddingsModel has a mthed named "build_vocab" (as the picture showing above). I just wonder why the instance self has the attribute "vocabulary". I can't find the place where it is introduced in. It appears as the function of the class Word2VecVocab in the script word2vec.py. However "word2vec.py" is somewhat child script of the "base_any2vec.py". Anyone can explain this?

**Comment by menshikh-iv** [comment]
Hi @phoenixzxj ,

`self.vocabulary` introduced in child classes of `BaseWordEmbeddingsModel`, like `FastText`

https://github.com/RaRe-Technologies/gensim/blob/6fb086f3df289f9ea3ba6b651984a77a21a6567f/gensim/models/fasttext.py#L391-L393

`Word2Vec`
https://github.com/RaRe-Technologies/gensim/blob/6fb086f3df289f9ea3ba6b651984a77a21a6567f/gensim/models/word2vec.py#L772-L774

 and so on. 
`BaseWordEmbeddingsModel` just base "util" class for any2vec models.

Next time please use [mailing list](https://groups.google.com/forum/#!forum/gensim) for questions, GitHub issues for bug report & feature request.
