### ISSUE TITLE
What does total_examples actually use for?

### ISSUE THREAD

**Issue by JoyeBright** [RaRe-Technologies/gensim#2280]
Hello,

As I know, in the previous version of Gensim, using `total_example` was not compulsory but in the latest version, it should be declared explicitly.
I am interested to know what it means and how I should reach the appropriate value.
Is it a figure of rows in the raw or the pre-processed dataset?

Thanks in advance

**Comment by arshjat** [comment]
@JoyeBright  Here is the documentation. [https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec.train](link)

**Comment by menshikh-iv** [comment]
@JoyeBright I confirm @arshjat comment: this needed for calculating learning rate decay.

Next time, please use [mailing list](https://groups.google.com/forum/#!forum/gensim) for questions, GitHub for bug reports and feature requests.
