### ISSUE TITLE
DtmModel error

### ISSUE THREAD

**Issue by JosephPB** [RaRe-Technologies/gensim#2286]
#### Description
When running DtmModel on a dataset of size 1.5M documents, after about 1 hour it raises this error:

```
subprocess.CalledProcessError: Command '['/efs/data/jpb/Qatalog/dtm/dtm/main', '--ntopics=10', '--model=dtm', '--mode=fit', '--initialize_lda=true', '--corpus_prefix=/tmp/2beb46_train', '--outname=/tmp/2beb46_train_out', '--alpha=0.01', '--lda_max_em_iter=10', '--lda_sequence_min_iter=6', '--lda_sequence_max_iter=10', '--top_chain_var=0.005', '--rng_seed=0']' died with <Signals.SIGABRT: 6>.
```

This same DtmModel works on smaller datasets I've tried.

#### Versions
```
import platform; print(platform.platform())
Linux-4.4.0-1072-aws-x86_64-with-debian-stretch-sid
import sys; print("Python", sys.version)
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)[GCC 7.2.0]
import numpy; print("NumPy", numpy.__version__)
NumPy 1.15.4
import scipy; print("SciPy", scipy.__version__)
│SciPy 1.1.0
import gensim; print("gensim", gensim.__version__)
gensim 3.6.0
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 1
```

Thanks for your help

**Comment by horpto** [comment]
@JosephPB 

Check your dmesg. Linux must be abort dtm/main. Also this issue probably do not linked with gensim itself as it is [dtm ](https://github.com/blei-lab/dtm) implementation bug.

**Comment by JosephPB** [comment]
@horpto 

Thanks for your comment. After doing some more testing it seems to be a memory issue, however, I just loaded in my dataset and ran the DTM on it. It's a big dataset but I'm using an AWS instance with 60G of memory so I'm not sure why that should be a problem unless there is some major memory leak.

**Comment by menshikh-iv** [comment]
@JosephPB gensim just a wrapper for https://github.com/blei-lab/dtm (we run like subprocess), in that case, this is some issue with dtm itself (not a gensim bug).

**Comment by liushuiwuhenxi** [comment]
I had the same problem. Have you solved it?
