### ISSUE TITLE
Flake8 Errors: W605 and W504

### ISSUE THREAD

**Issue by rsdel2007** [RaRe-Technologies/gensim#2289]
I have cloned the repository in my ubuntu machine according to the steps provided [here](https://github.com/RaRe-Technologies/gensim/blob/develop/CONTRIBUTING.md).<br>
I run the flake8 test and getting these errors: **W605** and **W504**
Here is the screenshot of the log :
![log](https://user-images.githubusercontent.com/39291744/49643804-af402b00-fa3c-11e8-9572-f4edd123646f.png)<br>
These errors are occurring in the files:
[gensim/utils.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/utils.py)
[gensim/topic_coherence/direct_confirmation_measure.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/topic_coherence/direct_confirmation_measure.py) 
[gensim/topic_coherence/segmentation.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/topic_coherence/segmentation.py)
[gensim/summarization/mz_entropy.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/summarization/mz_entropy.py)
[gensim/corpora/wikicorpus.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/corpora/wikicorpus.py)
[gensim/test/test_matutils.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/test/test_matutils.py)
[gensim/test/test_doc2vec.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/test/test_doc2vec.py)
[gensim/models/word2vec.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/word2vec.py)
[gensim/models/atmodel.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/atmodel.py)
[gensim/models/coherencemodel.py](gensim/models/coherencemodel.py)
[gensim/models/ldamulticore.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/ldamulticore.py)
[gensim/models/phrases.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/phrases.py)

I think these errors are the main reason why **every [PR's](https://github.com/RaRe-Technologies/gensim/pulls)** is failing in one check( _Travis CI build is failed_).
I would like to work on this.

**Comment by horpto** [comment]
I think this issue can  be closed due to this [PR](https://github.com/RaRe-Technologies/gensim/pull/2256l).

@rsdel2007 you should rebase your branches to the develop and repush it.

**Comment by menshikh-iv** [comment]
Thanks @rsdel2007 @horpto: Issue fixed by #2256
