### ISSUE TITLE
How to give weights to different words and also how to add global context while training 

### ISSUE THREAD

**Issue by anuragreddygv323** [RaRe-Technologies/gensim#2293]
I have to give importance to a few words while training. In skipgram model, I use the central word to predict the neighbouring words. I also want to predict the global context like a theme word in every single window size. 

Is there a way to do it  ?

**Comment by menshikh-iv** [comment]
Hello @anuragreddygv323,

we have no "weighting" functionality for window-words.
About predictions, we only have [Word2Vec.predict_output_word](https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec.predict_output_word) method.

Next time, please use [mailing list](https://groups.google.com/forum/#!forum/gensim) for questions, GitHub for bug reports and feature requests.
