### ISSUE TITLE
using  skip-gram of word2vec

### ISSUE THREAD

**Issue by zjzh** [RaRe-Technologies/gensim#2294]
Hello,
        I want to predict context words given a word using skip-gram algorithm.
        I check gensim doc about [word2vec ](https://radimrehurek.com/gensim/models/word2vec.html),  but I can't find the API about predicting context words.
        Does the API exist?

**Comment by menshikh-iv** [comment]
Hello @zjzh,

we only have [predict_output_word](https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec.predict_output_word) method that predicts center word by context words (inverse op to what you want). You should implement it yourself in this case (that's not hard, check the implementation of the mentioned method and write your own).

Next time, please use [mailing list](https://groups.google.com/forum/#!forum/gensim) for questions, GitHub for bug reports and feature requests.

**Comment by menshikh-iv** [comment]
BTW we already have a feature request for it #2152

**Comment by zjzh** [comment]
Thank you very much.  I'm sorry for the wrong place I am writing.
Now I am thinking whether it doesn't need to implement the inverse of method  `predict_output_word`. we can set the context is one word. The top-n words is our contexts word.
Because  the skip-gram or cbow both collect pair word to complete training, they basically same except the input layers.

**Comment by menshikh-iv** [comment]
@zjzh from first look - it really almost same, but in any way, need to
- check if this works exactly as expected in both cases (word / context), write tests for it
- update an documentation, add executable example
- (?) add "alias" method for `predict_output_context` as proxy to `predict_output_word` (make it simpler for a user)

**Comment by AMR-KELEG** [comment]
O/ @menshikh-iv
I have the feeling that the currently implemented predict_output_word isn't sound for a skipgram model since it is generally trained to predict the context words given a single word.
So, would it be meaningful from a probabilistic point of view to give the method a set of context words?

Consequently, getting a context for a word for a skipgram model needs just a feedforward pass through the neutral network.
