### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by Gautamshahi** [RaRe-Technologies/gensim#2304]
Please help me to resolve the issue.

![image](https://user-images.githubusercontent.com/3966230/50269735-405bcc80-0455-11e9-8bc3-dd62c84dd5ee.png)

**Comment by horpto** [comment]
Hi, @Gautamshahi 
Try to something like this:

```
previous_per_word_topics, ldamodel.per_word_topics = ldamodel.per_word_topics, True

for i in ldamodel.get_document_topics(doc_term_matrix, per_word_topics=True):
     doc_topics, word_topics, phi_values = i

ldamodel.per_word_topics = previous_per_word_topics
```

By your a piece of code, I have assumption that doc_term_matrix is actually not a one doc but a corpus.
Yeah, it's a bug.

**Comment by menshikh-iv** [comment]
I don't think that this is a bug, example below works correctly (`gensim==3.6.0`)

```python
from gensim.models import LdaModel
from gensim.corpora import Dictionary
from gensim.test.utils import common_corpus, common_dictionary

model = LdaModel(common_corpus, id2word=common_dictionary, num_topics=3)

for i in model.get_document_topics(common_corpus, per_word_topics=True):
    doc_topics, word_topics, phi_values = i
```

@Gautamshahi can you give us more information, please?
