### ISSUE TITLE
get_document_topics returns and empty list 

### ISSUE THREAD

**Issue by senjed** [RaRe-Technologies/gensim#2306]
I trained the lda model and want to get topic distribution for a new document. However, for some documents the get_document_topics function returns and empty list and I get this warning: 

/home/anaconda2/lib/python2.7/site-packages/gensim/models/ldamodel.py:676: RuntimeWarning: overflow encountered in divide
  gammad = self.alpha + expElogthetad * np.dot(cts / phinorm, expElogbetad.T)

This is the way I call the function:

>  topic_vector = [ x[1] for x in self.ldamodel.get_document_topics(new_doc_bow , minimum_probability= 0.0, per_word_topics=False)]

**Comment by horpto** [comment]
Hi @senjed 

What does  `self.ldamodel.inference([new_doc_bow])` return ?
If this expression returns empty list, so what is the value of `self.ldamodel.num_topics` ?

**Comment by senjed** [comment]
Hi, 
It returns (array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan]], dtype=float32), None)
and num_topics is 20.

**Comment by horpto** [comment]
@senjed 
Please, try to increase epsilon in `gensim/models/ldamodel.py` likeit is said in https://github.com/RaRe-Technologies/gensim/issues/2115#issuecomment-443113360

**Comment by senjed** [comment]
it worked thanks!
