### ISSUE TITLE
Get text embeddings using LDA 

### ISSUE THREAD

**Issue by himanshu-doi** [RaRe-Technologies/gensim#2311]
Im pretty new to NLP and I've ran an LDA model using bag of words embeddings and it gives me an output of the topics and the important words related to those topics. I wanted to know if there is a way to get the document embeddings out of the LDA model to further use them elsewhere. Say for finding out similar documents. 
Any help would be much appreciated. Thanks

**Comment by menshikh-iv** [comment]
Hello @himanshu-doi 

of course, you can get an embedding for document from LDA and use it for any things.

```python
from gensim.models import LdaModel
from gensim.utils import simple_preprocess
from gensim.corpora import Dictionary
import gensim.downloader as api

# prepare dictionary & corpus
corpus = [simple_preprocess(_["data"]) for _ in api.load("20-newsgroups")]
dct = Dictionary(corpus)
dct.filter_extremes()

corpus = [dct.doc2bow(doc) for doc in corpus]

# train LDA
model = LdaModel(corpus, id2word=dct, num_topics=5)

document = corpus[0]

# Infer vectors
print(model[document])  # embedding for single document

for vector in model[corpus]:  # embeddings for all documents in corpus
    print(vector) 
```
See also:
- https://radimrehurek.com/gensim/models/ldamodel.html
- https://radimrehurek.com/gensim/similarities/docsim.html

Next time, please use [mailing list](https://groups.google.com/forum/#!forum/gensim) for questions, GitHub for bug reports and feature requests.
