### ISSUE TITLE
Poor reproducibility of out-of-vocab word vectors after loading native model

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#2315]
See this unit test for reproduction:

https://github.com/mpenkov/gensim/blob/0d30caeb8c6d165d63c050de4bf32a0eab241d48/gensim/test/test_fasttext.py#L891

The test passes only if the tolerance is very high (0.1). For lower tolerance values (e.g. 0.01 and below), the test fails.

**Comment by menshikh-iv** [comment]
Thanks @gojomo 

> Do we have a test in place that when we use gensim Fasttest.load_fasttext_format() on an outside FastText file, then ask for an in-vocabulary word, we get identical results?

Already yes, @mpenkov on it, see #2313

**Comment by gojomo** [comment]
From the descriptions of #2313/#2160, it's not clear they'd verify same-results from a loaded FT model, though it would separately be good if we had a test for that, independent of any other functionality.
