### ISSUE TITLE
No documentation for how tags assigned in Doc2Vec w/corpus_file

### ISSUE THREAD

**Issue by gojomo** [RaRe-Technologies/gensim#2316]
Although the new `corpus_file` mode ostensibly works with `Doc2Vec`, there's no documentation about how per-document `tags` are set in that mode. Is it still possible to set string tags, or more than one tag per document? (Or are documents just given the single tag for their line number in the file?)

At the very least, the docs for the `corpus_file` parameter in the class documentation – https://radimrehurek.com/gensim/models/doc2vec.html#gensim.models.doc2vec.Doc2Vec – should mention how tags are assigned in this mode.

**Comment by gojomo** [comment]
cc @persiyanov

**Comment by persiyanov** [comment]
Yes, document's tag equals its number of a line as if you are using `TaggedLineDocument` class.

**Comment by menshikh-iv** [comment]
@persiyanov can you update docs, please?

**Comment by persiyanov** [comment]
sure, here is the PR https://github.com/RaRe-Technologies/gensim/pull/2320
