### ISSUE TITLE
similar doc tags from new documents

### ISSUE THREAD

**Issue by DreamFlasher** [RaRe-Technologies/gensim#2324]
There is `model.docvecs.most_similar('doctorwho')` to obtain similar docs. Is there any way to retrieve similar docs (doc tags) for a new document? Or is the `TODO: Accept vectors of out-of-training-set docs, as if from inference.` indicating that exactly this is not possible yet? Is there a way to do that manually?

**Comment by menshikh-iv** [comment]
Hello @DreamFlasher 

`is not possible yet?` - yes, at least with `most_similar`, see #2166 

For now, you can get vectors for all available doctags and calculate similarity manually

```python
from gensim.models.doc2vec import TaggedDocument, Doc2Vec
from gensim.utils import simple_preprocess
import gensim.downloader as api

import numpy as np
from scipy.spatial.distance import cdist


# Train model
corpus = [TaggedDocument(simple_preprocess(_["data"]), [idx]) for idx, _ in enumerate(api.load("20-newsgroups"))]
model = Doc2Vec(corpus)


# Extract docvectors (not efficienties way, but simplest)
docvectors = np.array([model[idx] for idx in range(len(corpus))])

# Infer vector for new document
new_vector = model.infer_vector(["hello", "world"])

# Calculate similarities between 'new_vector' and 'docvectors'
similarities = (1 - cdist(new_vector.reshape((1, new_vector.shape[0])), docvectors, metric='cosine')).reshape(-1)
```


Next time, please use [mailing list](https://groups.google.com/forum/#!forum/gensim) for questions, GitHub for bug reports and feature requests.
