### ISSUE TITLE
replace 'sum(time_slice) == num_topics' to 'sum(time_slice) == num_documents'

### ISSUE THREAD

**Issue by neutronest** [RaRe-Technologies/gensim#2332]
https://github.com/RaRe-Technologies/gensim/blob/355ecc68a6ccb07f38418e8c80784b70aac84442/gensim/models/ldaseqmodel.py#L75

As the comments said 'Number of documents in each time-slice', maybe the num_documents is the true meaning for sum(time_slice) ??

**Comment by menshikh-iv** [comment]
СС @bhargavvader
