### ISSUE TITLE
cosine similarity is not giving 1 for two same input documents

### ISSUE THREAD

**Issue by tvrbanec** [RaRe-Technologies/gensim#2351]
https://groups.google.com/forum/#!topic/gensim/YiMDDtLCI7o

Any similarity to a document by itself should be 1. It seems to me it is something wrong with cosine similarity in gensim, because I do not get 1.

def cossim(texts):
    dictionary = corpora.Dictionary(texts)
    corpus = [dictionary.doc2bow(text) for text in texts]
    tfidf = TfidfModel(corpus, dictionary, normalize=True)
    index = MatrixSimilarity(tfidf[corpus], num_features=len(dictionary))
    simmatrix = index[corpus]
    return simmatrix

Input text in the form of 2d list of words is [here](https://groups.google.com/group/gensim/attach/6bb39f0def72f/input_2d_text_list.txt?part=0.1&authuser=0). The cosine similarity scores for these five documents I'v got from above code are:

[[0.4484578  0.03050137 0.01659208 0.03342406 0.11152142]
 [0.01370624 0.31444198 0.1637049  0.14261982 0.05780634]
 [0.00734405 0.16124928 0.38912225 0.14186516 0.03908984]
 [0.01621059 0.15392897 0.1554464  0.34419927 0.06053988]
 [0.07290775 0.08409916 0.05773569 0.08160509 0.3643248 ]]

Numbers in diagonal should be all 1, but they are not.

**Comment by piskvorky** [comment]
@tvrbanec you're comparing `index`, which is `TFIDF[corpus]`, to just `corpus` (bag-of-words).

Try `simmatrix = index[tfidf[corpus]]`.

**Comment by tvrbanec** [comment]
Thank you very much!
