### ISSUE TITLE
Feature Suggestion: Add new parameter that gives topic distribution among all the words

### ISSUE THREAD

**Issue by SHANMUKHA-VENKAT** [RaRe-Technologies/gensim#2354]
#### Description
TODO: change commented example

#### Versions

Complete topic vectors is important for clearer analysis.

**Comment by piskvorky** [comment]
Gensim already gives you topic distributions, what parameter? Please use the [mailing list](https://groups.google.com/forum/#!forum/gensim) to ask open-ended questions, Github is for bug reports.

**Comment by menshikh-iv** [comment]
@SHANMUKHA-VENKAT maybe you need this one https://radimrehurek.com/gensim/models/ldamodel.html#gensim.models.ldamodel.LdaModel.get_topics?
