### ISSUE TITLE
Documentation: Unclear Explanation

### ISSUE THREAD

**Issue by SHANMUKHA-VENKAT** [RaRe-Technologies/gensim#2355]
#### Description
TODO: change commented example

#### Versions

https://github.com/RaRe-Technologies/gensim/wiki/Recipes-&-FAQ#q3-how-do-you-calculate-the-matrix-v-in-lsi-space 
Question 4.

**Comment by piskvorky** [comment]
@SHANMUKHA-VENKAT use the [mailing list](https://groups.google.com/forum/#!forum/gensim) to ask questions. Be specific if you want answers.
