### ISSUE TITLE
WikiCorpus lumps many paragraphs into one

### ISSUE THREAD

**Issue by bhomass** [RaRe-Technologies/gensim#2362]
#### Description
TODO: change commented example

**Comment by bhomass** [comment]
I downloaded some wikipedia english dumps, and tried to use WikiCorpus to convert them to tokens. For every dump, the same thing happens. WikiCorpus.get_text() returns very very long paragraphs, each consists of many paragraphs in the original text. I know, I because I checked against the original wikipedia page. I read somewhere, you should get around 30 million paragraphs when properly parse out the full dump. Instead I only got 4 million. So the process is lumping around 8 paragraphs into 1. How do I fix this? I am surprised no one else reported this. Was there some change in behavior in the recent release?

**Comment by menshikh-iv** [comment]
Hello @bhomass,

> I read somewhere, you should get around 30 million paragraphs when properly parse out the full dump

Not sure where you read that, better to read our documentation for [WikiCorpus.get_texts](https://radimrehurek.com/gensim/corpora/wikicorpus.html#gensim.corpora.wikicorpus.WikiCorpus.get_texts)
```
Iterate over the dump, yielding a list of tokens for each article ...
```
We yield tokens for each article, not for paragraphs.
If you need an paragraphs, I can propose:
- already parsed dump https://github.com/RaRe-Technologies/gensim-data/releases/tag/wiki-english-20171001 (see code example below in page), easy to use.
- [gensim.scripts.segment_wiki](https://radimrehurek.com/gensim/scripts/segment_wiki.html) script that extracts paragraph from wikidump (using this script we generate a dump above)

**Comment by bhomass** [comment]
do you mean to say, you would apply doc2vec to an entire wikipedia article as a single doc, instead of its paragraphs?

**Comment by menshikh-iv** [comment]
@bhomass I wound to say than `get_texts()` yield articles, not paragraphs, no idea how doc2vec related, it's up to you, how to apply doc2vec on wikipedia (on article or paragraph level).

**Comment by bhomass** [comment]
I am just wondering the usefulness of the article granularity. Obviously, someone can easily combine sentences and paragraphs into a single article, but can not decompose an article worth of tokens back into the original sentence or paragraph units.

**Comment by menshikh-iv** [comment]
@bhomass 

> I am just wondering the usefulness of the article granularity

Only one way to check: train both variants and compare :) 

> Obviously, someone can easily combine sentences and paragraphs into a single article, but can not decompose an article worth of tokens back into the original sentence or paragraph units.

read https://github.com/RaRe-Technologies/gensim/issues/2362#issuecomment-458776813 again please, I propose 2 variants how to retrieve paragraphs instead.

**Comment by bhomass** [comment]
I am trying to work with the dump you referenced. The content appears to be long string embedded in some kind of json. I can identify the json header at the beginning of the text 
b'{
"section_texts": [

So I tried using ast.literal_eval(line)
but, it quickly bombs with 
"ValueError: malformed node or string"

Could you please recommend the best tools to use to extract the individual paragraphs from the dump file?

**Comment by bhomass** [comment]
I also applied the supplied post processing code
from smart_open import smart_open
import json

# iterate over the plain text data we just created
for line in smart_open('/data/wikipedia/wiki-english-20171001.gz_00'):
    # decode each JSON line into a Python dictionary object
    article = json.loads(line)

    # each article has a "title", a mapping of interlinks and a list of "section_titles" and "section_texts".
    print("Article title: %s" % article['title'])
    print("Interlinks: %s" + article['interlinks'])
    for section_title, section_text in zip(article['section_titles'], article['section_texts']):
         print("Section title: %s" % section_title)
         print("Section text: %s" % section_text)

to the downloaded files like wiki-english-20171001.gz_00, but for that I get 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by piskvorky** [comment]
@bhomass the code example is also on the page @menshikh-iv linked to: https://github.com/RaRe-Technologies/gensim-data/releases/tag/wiki-english-20171001
