### ISSUE TITLE
crashed when using LdaMulticore in sub-subprocess

### ISSUE THREAD

**Issue by JackYangzg** [RaRe-Technologies/gensim#2379]
ENV:  Unbuntu 16.0.4
python version: 3.6.3

subProcess:
    Process ForkPoolWorker-1:1:
    Process ForkPoolWorker-1:2:
    Process ForkPoolWorker-1:4:
    Process ForkPoolWorker-1:3:

when call LdaMulticore using 4 workers in sub-subprocess, It crashed with:

Traceback:
**Traceback (most recent call last):
  File "xxx/python3.6/multiprocessing/queues.py", line 241, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "xxx/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function __RandomState_ctor at 0x7f30e93e1f28>: it's not the same object as numpy.random.__RandomState_ctor**

When I look at the code of LdaMulticore, I feel the local variable  [job_queue, result_queue] cause this problem.

Did any One who have see the same problem.

**Comment by piskvorky** [comment]
@JackYangzg did you manage to figure this out?
