### ISSUE TITLE
an implementation bug in summarizer

### ISSUE THREAD

**Issue by kwunlyou** [RaRe-Technologies/gensim#2380]
#### Steps/Code/Corpus to Reproduce
If debugging the following piece of code, and get ino the function [`_set_graph_edge_weights`](https://github.com/RaRe-Technologies/gensim/blob/70fa23378da277f60a4cd566375f09d389f08ddb/gensim/summarization/summarizer.py#L74).
`documents` is a variable using BoW representation, however, `_bm25_weights` expects a list of list of plain tokens. If `BoW` is used, `(1, 2)` and `(1, 3)` are treated as different words. Actually, they are the same words which just have different counts in different documents. 

```
from gensim.summarization.summarizer import summarize

text = '''Rice Pudding - Poem by Alan Alexander Milne
What is the matter with Mary Jane?
She's crying with all her might and main,
And she won't eat her dinner - rice pudding again -
What is the matter with Mary Jane?
What is the matter with Mary Jane?
I've promised her dolls and a daisy-chain,
And a book about animals - all in vain -
What is the matter with Mary Jane?
What is the matter with Mary Jane?
She's perfectly well, and she hasn't a pain;
But, look at her, now she's beginning again! -
What is the matter with Mary Jane?
What is the matter with Mary Jane?
I've promised her sweets and a ride in the train,
And I've begged her to stop for a bit and explain -
What is the matter with Mary Jane?
What is the matter with Mary Jane?
She's perfectly well and she hasn't a pain,
And it's lovely rice pudding for dinner again!
What is the matter with Mary Jane?'''

print(summarize(text))
```

#### Versions
3.7.1

**Comment by horpto** [comment]
Hi, @kwunlyou thanks for the report. I've recently refactored summarizer, but I think it's original implementation bug. Can you add or complete with bug description: what I get and what should I get?

**Comment by kwunlyou** [comment]
@horpto apologies for the late response. The `PR` will fix the bug which I reported. Thanks.

**Comment by horpto** [comment]
@kwunlyou that's great but your example gets similar result as for the previous version. Can you provide a test which generates a different results for different versions ?

**Comment by kwunlyou** [comment]
@horpto could you please try the full article from https://www.dailymail.co.uk/news/article-2886654/Christmas-parade-dying-Utah-girl.html? It should give you different results.

**Comment by Witiko** [comment]
Since `summarization.bm25` has been removed from Gensim 4, this issue can be closed.
