### ISSUE TITLE
Different result everytime with Word2Vec

### ISSUE THREAD

**Issue by prabhatM** [RaRe-Technologies/gensim#2383]
Hi,
I am trying out Gensim Word2Vec with a very small and experimental data. It returns the "most_similar" values for my item i.e. "breast cancer" in this case. But every time I print, I get different values for the same item(s) which is evident on the picture I have attached.

What's the reason?

Prabhat

![gensim_erratic](https://user-images.githubusercontent.com/7250780/52802882-cdfb1780-30a6-11e9-83a5-bf9b4f793a8b.png)

**Comment by piskvorky** [comment]
Turn on logging and observe the logs. Anything there that looks suspicious?

**Comment by gojomo** [comment]
This is explained in the FAQ:

https://github.com/RaRe-Technologies/gensim/wiki/Recipes-&-FAQ#q11-ive-trained-my-word2vecdoc2vecetc-model-repeatedly-using-the-exact-same-text-corpus-but-the-vectors-are-different-each-time-is-there-a-bug-or-have-i-made-a-mistake-2vec-training-non-determinism
