### ISSUE TITLE
Readme incorrectly states that HDP implementation is parallel

### ISSUE THREAD

**Issue by ckingdev** [RaRe-Technologies/gensim#2384]
The readme currently (on master) states:

> Efficient multicore implementations of popular algorithms, such as online Latent Semantic Analysis (LSA/LSI/SVD), Latent Dirichlet Allocation (LDA), Random Projections (RP), Hierarchical Dirichlet Process (HDP) or word2vec deep learning.

However, the HDP model is single core (and it looks like RP is as well, though I'm less familiar with the technique) and this is misleading.

**Comment by piskvorky** [comment]
Most of these algos rely on numpy matrix operations, which in turn rely on BLAS, which is typically multi-threaded. With RP, you should see a definite improvement with multicore machines. Not sure how much BLAS helps in HDP.

In the future, it's better to ask the [mailing list](https://groups.google.com/forum/#!forum/gensim) and discuss there.

**Comment by ckingdev** [comment]
I'm well aware that BLAS is used here. You and I both know that that's not what people are going to read "multicore HDP" as. Especially since the package *does* have a parallel implementation of LDA.

**Comment by piskvorky** [comment]
@ckingdev are you a user of HDP? I'm actually considering dropping that model from Gensim altogether.

Some words on where/how HDP is useful, from an actual user, could help us make that decision. Cheers!
