### ISSUE TITLE
Using labeled fasttext data format for domain specific data

### ISSUE THREAD

**Issue by prabhatM** [RaRe-Technologies/gensim#2388]
Hi,

I have (multi) labeled my domain specific data as suggested by FastText. The samples are below:
----
__label__disorder __label__8197001 acrodermatitis
__label__procedure __label__390416006 serum flecainide level
__label__procedure __label__309626003 child referral - school psychologist
__label__finding __label__2663001 palpatory proteinuria
__label__disorder __label__210526006 degloving injury, axilla
__label__disorder __label__6347003 disruption of cesarean wound in the puerperium
__label__specimen __label__258518003 scrotal swab
__label__procedure __label__391570004 m2 mitochondrial antibody (enzyme immunoassay) level
----
The first label is "class" and the second label is the concept ID.
How can I use the dataset in gensim? A little nudge will help. I could see the usage of unlabeled data in gensim for fasttext.

Regards

Prabhat

**Comment by piskvorky** [comment]
Hi, please follow the issue template that you were given.

**Comment by prabhatM** [comment]
Thank you.
