### ISSUE TITLE
Similarity object gone after computer restart

### ISSUE THREAD

**Issue by thereisnospooon** [RaRe-Technologies/gensim#2400]
#### Problem description
I'm trying to load a saved similarity object from disk.
Whenever I'm trying to load the object after I restarted the computer, the loaded object is failing to work.
I believe the problem is that maybe the tmp/ folder is cleaned when the computer restarts.

What are you trying to achieve? What is the expected result? What are you seeing instead?
I'm trying to use the Similarity index that was saved on the disk.

#### Steps/code/corpus to reproduce
I get the following traceback when calling:
index = similarities.Similarity.load("path to .index file") 
index.similarity_by_id(0) // Arbitrary check that the index is working as needed.

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-302-400050246fc0> in <module>
----> 1 index.similarity_by_id(0)

~/.local/lib/python3.6/site-packages/gensim/similarities/docsim.py in similarity_by_id(self, docpos)
    622 
    623         """
--> 624         query = self.vector_by_id(docpos)
    625         norm, self.norm = self.norm, False
    626         result = self[query]

~/.local/lib/python3.6/site-packages/gensim/similarities/docsim.py in vector_by_id(self, docpos)
    593         if not self.shards or docpos < 0 or docpos >= pos:
    594             raise ValueError("invalid document position: %s (must be 0 <= x < %s)" % (docpos, len(self)))
--> 595         result = shard.get_document_id(docpos - pos + len(shard))
    596         return result
    597 

~/.local/lib/python3.6/site-packages/gensim/similarities/docsim.py in get_document_id(self, pos)
    186         """
    187         assert 0 <= pos < len(self), "requested position out of range"
--> 188         return self.get_index().index[pos]
    189 
    190     def __getitem__(self, query):

~/.local/lib/python3.6/site-packages/gensim/similarities/docsim.py in get_index(self)
    162         if not hasattr(self, 'index'):
    163             logger.debug("mmaping index from %s", self.fullname())
--> 164             self.index = self.cls.load(self.fullname(), mmap='r')
    165         return self.index
    166 

~/.local/lib/python3.6/site-packages/gensim/utils.py in load(cls, fname, mmap)
    424         compress, subname = SaveLoad._adapt_by_suffix(fname)
    425 
--> 426         obj = unpickle(fname)
    427         obj._load_specials(fname, mmap, compress, subname)
    428         logger.info("loaded %s", fname)

~/.local/lib/python3.6/site-packages/gensim/utils.py in unpickle(fname)
   1379 
   1380     """
-> 1381     with smart_open(fname, 'rb') as f:
   1382         # Because of loading from S3 load can't be used (missing readline in smart_open)
   1383         if sys.version_info > (3, 0):

~/.local/lib/python3.6/site-packages/smart_open/smart_open_lib.py in smart_open(uri, mode, **kw)
    179         raise TypeError('mode should be a string')
    180 
--> 181     fobj = _shortcut_open(uri, mode, **kw)
    182     if fobj is not None:
    183         return fobj

~/.local/lib/python3.6/site-packages/smart_open/smart_open_lib.py in _shortcut_open(uri, mode, **kw)
    299     #
    300     if six.PY3:
--> 301         return open(parsed_uri.uri_path, mode, buffering=buffering, **open_kwargs)
    302     elif not open_kwargs:
    303         return open(parsed_uri.uri_path, mode, buffering=buffering)

FileNotFoundError: [Errno 2] No such file or directory: '.shrd.0'

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform()) - Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
import sys; print("Python", sys.version) - Python 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0]
import numpy; print("NumPy", numpy.__version__) - NumPy 1.16.1
import scipy; print("SciPy", scipy.__version__) - SciPy 1.2.1
import gensim; print("gensim", gensim.__version__) - gensim 3.7.1
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION) - FAST_VERSION 1
```

**Comment by piskvorky** [comment]
Your reproducibility report is incomplete (how were these files stored?), but the way to specify the output destination is with the `output_prefix` constructor parameter. See also the [Similarity docs](https://radimrehurek.com/gensim/similarities/docsim.html#gensim.similarities.docsim.Similarity).
