### ISSUE TITLE
how to use gensim at centos 6 

### ISSUE THREAD

**Issue by brucegai** [RaRe-Technologies/gensim#2401]
First of all, i want to transform word into vector via gensim, to calculate text similarity between two short paragraph. i can successfully install gensim package at centos6 system with python 3. However, to run my program, i have problem with "import gensim". Keep on getting notice of "No module named _ssl". Has anyone encounter this problem? Really need some help, thank you! 

```

**Comment by mpenkov** [comment]
As you may have already guessed, this isn't a problem with gensim. It's a problem with your Python install: the SSL module is broken. You can verify this using the following command:

    $ python -c "import ssl"

That should print the same exception ("No module named _ssl").

For ideas about fixing the problem, have a look at [this post](https://stackoverflow.com/questions/5128845/importerror-no-module-named-ssl) on stackoverflow and elsewhere. This is a relatively common problem and you should be able to find a solution that works in your particular case.
