### ISSUE TITLE
Regarding Google Season of Docs

### ISSUE THREAD

**Issue by davidcode00** [RaRe-Technologies/gensim#2412]
Hello all, 
I wanted to know that are you going to participate in the upcoming Google Season of docs?

**Comment by piskvorky** [comment]
Hi, can you share a link?

**Comment by davidcode00** [comment]
HI @piskvorky , this is the [link](https://developers.google.com/season-of-docs/) of the program.

**Comment by piskvorky** [comment]
Hmm, that sounds interesting (and vaguely familiar). @mpenkov thoughts?

**Comment by mpenkov** [comment]
This could help with the quality of our documentation, provided we can come up with enough work to keep a technical writer occupied for the 3 months. The org application period is in early April ( https://developers.google.com/season-of-docs/docs/timeline).

One problem I can see is that the actual work happens in September, half a year from now. It's hard for me to imagine what state our docs will be by then.

**Comment by rsdel2007** [comment]
I would like to participate with your organisation if you are participating :smiley: .

**Comment by mpenkov** [comment]
We've decided to not participate this time around. We'll keep our eyes open for future iterations.
