### ISSUE TITLE
LdaMulticore not working so well with corpus in tf_idf form.

### ISSUE THREAD

**Issue by haidangbosco** [RaRe-Technologies/gensim#2414]
First of all, I want to say that  I am not very good English. I hope that you guys can bear with me.

Like I said, I transformed my corpus to tf_idf form and used it with ldamulticore but it took much longer to process than with normal corpus. Can anyone help me with this issue ?

**Comment by piskvorky** [comment]
@haidangbosco your report is missing the necessary details. Please see the issue template you deleted when opening this issue (especially the part about mailing list and reproducibility).
