### ISSUE TITLE
gensim.downloader should accept custom directory for downloading embeddings

### ISSUE THREAD

**Issue by skasturi** [RaRe-Technologies/gensim#2416]
#### Problem description

I am trying to use gensim.downloader for download embeddings. However, it is creating a directory in my home folder where there is not enough space. I would like to specify a custom folder so that the embeddings get downloaded there. 

#### Steps/code/corpus to reproduce

Fill up your C drive and use gensim.downloader to download one of the embeddings. 

#### Versions

Please provide the output of:

```python
import gensim.downloader as api
dataset = api.load("text8")
```

**Comment by mpenkov** [comment]
Can you not symlink the directory to another volume?

**Comment by skasturi** [comment]
That's possible. But it isn't clean to not have the possibility of
providing a directory to download. Moreover, the path to which the download
happens is not returned until the download actually happens. Therefore, in
case this folder changes in the future I would have to re-do the symlink
again.
