### ISSUE TITLE
How to customize a model (beyond doc2vec)?

### ISSUE THREAD

**Issue by sunacc** [RaRe-Technologies/gensim#2426]
#### Problem description

Hello guys,
I want to customize a model beyond doc2vec.

In doc2vec, the probality model for predicting a center word is p(word_center|doc_tag, word_context).

Based on it,  I want to build a model p(word_center|doc_tag,word_attribute,word_context). The word_attribute of word_center may be Place, Name, etc. so that we can add human knowledge on words. 

So how can I implement such a model in gensim?

**Comment by gojomo** [comment]
All the source code is there as an example to model your work after, or build upon, but that wouldn't necessarily be an easy extension - the hooks aren't quite there for such micro-changes to the individual NN training examples.

**Comment by mpenkov** [comment]
Closing this as there is no further action we need to take as maintainers.
