### ISSUE TITLE
Error: -1073741819 (0xC0000005) and computer restarted

### ISSUE THREAD

**Issue by yoshimoncho** [RaRe-Technologies/gensim#2436]
#### Problem description

This issue is about a bug that I found and I think it is important as it restarted my PC.
The problem appears when I use similarities.SparseMatrixSimilarity and the parameter num_features is smaller than the number of elements in the corpus dictionary. 
At the beggining, my computer restarted after I had executed my code and a blue screen appears showing a problem with rzpnk.sys (a driver) , I tried it twice and my computer also restarted. I decided to uninstall the program related to that driver so the driver was deleted, then I executed again the code and I obtained: 
**"Process finished with exit code -1073741819 (0xC0000005)"**
I've been reading on the Internet that this could be caused by an invalid memory access...
Finally I changed my code and assigned num_features the size of the corpus dictionary, so now it works. 

#### Steps/code/corpus to reproduce
```python
dct = Dictionary(documents)
corpus = [dct.doc2bow(line) for line in documents]
model = TfidfModel(corpus)
index = similarities.SparseMatrixSimilarity(model[corpus], num_features=12)
#In this case it returns exit code -1073741819 (0xC0000005)
#The correct code is: 
index = similarities.SparseMatrixSimilarity(model[corpus], num_features=len(dct ))
```
#### Versions

Windows-10-10.0.17134-SP0
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
NumPy 1.16.2
SciPy 1.2.1
gensim 3.7.1
FAST_VERSION 0

**Comment by piskvorky** [comment]
That is correct. If you supply an incorrect value to the `num_features` parameter, scipy (the sparse matrix library used internally) will get confused and segfault.

I think this is the "expected" behaviour; what do you propose should happen instead @yoshimoncho ?

**Comment by yoshimoncho** [comment]
> That is correct. If you supply an incorrect value to the `num_features` parameter, scipy (the sparse matrix library used internally) will get confused and segfault. See also #74 .
> 
> I think this is the "expected" behaviour; what do you propose should happen instead @yoshimoncho ?

**Comment by yoshimoncho** [comment]
> That is correct. If you supply an incorrect value to the `num_features` parameter, scipy (the sparse matrix library used internally) will get confused and segfault. See also #74 .
> 
> I think this is the "expected" behaviour; what do you propose should happen instead @yoshimoncho ?

From my personal point of view, I propose to check if sizes are the same and throw an error if it is possible. If this segfault occurs maybe a blue screen could appear ...
Thank you very much for answering :)

**Comment by mar-sss** [comment]
Hi, I have similar problem, but with FastText model training. 
When I try to run gensim.models.fasttext.FastText with sg=1 in PyCharm console, I get the same error (Process finished with exit code -1073741819 (0xC0000005)). First time, computer restarted, now the console only prints this exit code and nothing else happens. With parameter sg=0, it works.

Versions:
Win10, version 1803, build 17134.706
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
NumPy 1.16.2
SciPy 1.2.1
gensim 3.7.1

**Comment by piskvorky** [comment]
@mar-sss that sounds unrelated. Please open a new ticket, filling in the issue template (how to reproduce, software versions etc)
