### ISSUE TITLE
bz2file dependency considered not neccessary?

### ISSUE THREAD

**Issue by yunhua-deng** [RaRe-Technologies/gensim#2448]
Python has built-in **bz2** module (https://docs.python.org/3/library/bz2.html), don't understand why does gensim depend on **bz2file** which is a old library (see https://pypi.org/project/bz2file/) without updates for a long time. Can I remove this dependency safely?
```
Installing collected packages: bz2file, jmespath, urllib3, botocore, s3transfer, boto3, smart-open, gensim
  Found existing installation: urllib3 1.24.1
    Uninstalling urllib3-1.24.1:
      Successfully uninstalled urllib3-1.24.1
Successfully installed boto3-1.9.130 botocore-1.12.130 bz2file-0.98 gensim-3.7.2 jmespath-0.9.4 s3transfer-0.2.0 smart-open-1.8.1 urllib3-1.22
```

**Comment by menshikh-iv** [comment]
Looks like a [possible issue of smart_open](https://github.com/RaRe-Technologies/smart_open/blob/master/setup.py#L71), @mpenkov though?

**Comment by mpenkov** [comment]
Yes, this is an indirect dependency via smart_open. You can safely remove that dependency if:

- You're using Py3, or
- You're not planning on opening .bz2 files with gensim or smart_open
