### ISSUE TITLE
Lemmatizer fails for some words

### ISSUE THREAD

**Issue by themeo** [RaRe-Technologies/gensim#2464]
**The problem**

```python
from gensim import utils

print (utils.lemmatize('smile')) # other words include 'her', 'smooth'
print (utils.lemmatize('arrived')) #other words include 'ears', 'tattoos', 'campaigning'
```

The first command ('smile') returns an empty array. 
The second command ('arrived') returns unlemmatized word. 
Many other words work just fine. 

**Version info:**
Windows-10-10.0.17134-SP0
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
NumPy 1.16.3
SciPy 1.2.1
c:\Program Files\Python36\lib\site-packages\smart_open\ssh.py:34: UserWarning: paramiko missing, opening SSH/SCP/SFTP paths will be disabled.  `pip install paramiko` to suppress
  warnings.warn('paramiko missing, opening SSH/SCP/SFTP paths will be disabled.  `pip install paramiko` to suppress')
gensim 3.7.2
FAST_VERSION -1

**Comment by piskvorky** [comment]
By default, `lemmatize` returns only tokens that represent verbs, nouns, adjectives and adverbs. See the `allowed_tags` parameter of lemmatize.

```python
print(utils.lemmatize('smile', allowed_tags=re.compile('.*')))
['smile/IN']
```

**Comment by themeo** [comment]
Thanks for your response!

But this leaves open 2 questions: Why 'smile', being both a noun and a verb, is tagged as IN (Preposition or subordinating conjunction)? 

My issue report also mentioned other words that do not get lemmatized at all: arrived, ears, tattoos, campaigning, so this is a separate issue.

**Comment by piskvorky** [comment]
It's an issue for the `pattern` library – feel free to open a ticket there.
