### ISSUE TITLE
models.Doc2Vec retruned model.docvecs size is smaller than input docs

### ISSUE THREAD

**Issue by smartfeature** [RaRe-Technologies/gensim#2470]
models.Doc2Vec retruned model.docvecs size is smaller than input docs

model = models.Doc2Vec(docs,alpha=0.025,min_alpha=0.025,min_count=2,vector_size=30,workers=4,epochs=50)

docs size 2849, 
model.docvecs size 2749

**Comment by piskvorky** [comment]
Please fill in the issue template fully, including the SW versions and reproducible example.

**Comment by gojomo** [comment]
@smartfeature You've probably repeated the tags for some of your documents. The number of learned doc-vectors will not be equal to `len(docs)` (the number of docs), but rather `len(set(itertools.chain(doc.tags for doc in docs)))` (the number of unique document tags).

**Comment by mpenkov** [comment]
@smartfeature Please provide the full information about your problem. Otherwise, we cannot proceed with this ticket, and will have to close it.

**Comment by gojomo** [comment]
No info, likely explanation is user error, closing.
