### ISSUE TITLE
Persistense on disk fails

### ISSUE THREAD

**Issue by bakirillov** [RaRe-Technologies/gensim#2471]
Hello!

I can't get back the model I have saved. 
When I do that:
`from gensim.test.utils import get_tmpfile`
 `fname = get_tmpfile("fasttext.model")`   
 `model.save(fname)`   
 `print(model.wv["afgadfgd"])`   

saving works and word vector is printed but when I load the model with   
`model = FastText.load(fname)`    
and try:    
`print(model.wv["afgadfgd"])`
it fails with an error:    
`AttributeError: 'FastTextKeyedVectors' object has no attribute 'vectors_ngrams'`

Could you please look into that?

```Linux-4.18.0-17-generic-x86_64-with-debian-buster-sid
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0]
NumPy 1.16.3
SciPy 1.2.1
gensim 3.7.2
FAST_VERSION 1
```

**Comment by mpenkov** [comment]
How did you obtain `model`?

I tried reproducing the problem with a model trained from scratch, and failed. Please try the source below:

```python
from gensim.models import fasttext
from gensim.test.utils import common_texts, get_tmpfile
model = fasttext.FastText(size=4, window=3, min_count=1)  # instantiate
model.build_vocab(sentences=common_texts)
model.train(sentences=common_texts, total_examples=len(common_texts), epochs=10)  # train

fname = get_tmpfile("fasttext.model")
model.save(fname)
print(model.wv["afgadfgd"], fname)

loaded_model = fasttext.FastText.load(fname)
print(loaded_model.wv["afgadfgd"], fname)
```

```
(372.env) misha@cabron:~/git/gensim$ python bug.py
[ 0.01567879 -0.03705832 -0.03542715  0.01017484] /tmp/fasttext.model
[ 0.01567879 -0.03705832 -0.03542715  0.01017484] /tmp/fasttext.model
```

and let me know if it works in your environment.

**Comment by mpenkov** [comment]
Also, when reporting errors, please provide the full stack trace.

**Comment by bakirillov** [comment]
Resolved. Still don't know why it happened but it's fine now.
