### ISSUE TITLE
mismatched field names

### ISSUE THREAD

**Issue by gforman44** [RaRe-Technologies/gensim#2477]
Some places in the code use   self._lines_are_documents
while others use  self.lines_are_documents   (no underscore)

https://github.com/RaRe-Technologies/gensim/blob/40792c611ff6d0385fadc6de1f03d9ae22261351/gensim/corpora/textcorpus.py#L512

https://github.com/RaRe-Technologies/gensim/blob/40792c611ff6d0385fadc6de1f03d9ae22261351/gensim/corpora/textcorpus.py#L592

https://github.com/RaRe-Technologies/gensim/blob/40792c611ff6d0385fadc6de1f03d9ae22261351/gensim/corpora/textcorpus.py#L517

**Comment by mpenkov** [comment]
That's by design. It's a @property.
