### ISSUE TITLE
Fasttext - Different order of subwords change similarity 

### ISSUE THREAD

**Issue by datistiquo** [RaRe-Technologies/gensim#2483]
Hi,

I just found that different order of subwords in a OOV-word gives different results.

My example is

sub1sub2 (OOV)

with sub1 and sub2 subwords which are in vocab.

So 

`print(model.wv.similarity("sub1sub2","sub2sub1"))`

should yield `1`, right?

I get for my model depending on the words 80 or even just 60%?

Since for OOVs the vector is just the sum of subwords, why does the order change the result?

gensim: 3.6.0

**Comment by mpenkov** [comment]
Please direct this question at the mailing list. Github issues are for reporting bugs only.

If you think this is a bug, then please fill out the entire issue template, including the reproducible example.
