### ISSUE TITLE
Parameters equivalence in Word2vec

### ISSUE THREAD

**Issue by mmatheuslyra** [RaRe-Technologies/gensim#2484]
Hello, I would like to understand better the difference between the "iter" and "epoch" parameters in the Word2vec algorithm. 

Does the epoch parameter have an equivalent to the Mikolov's implementation? 

Actually, I haven't seen any mention to the Epoch parameter in the Mikolov job, so how could I replicate it? Would be enough an execution like Gensim.Word2vec(iter = 5, epoch = 5) Mikolov.Word2vec(iter = 5) to run the same for these two parameters?

**Comment by piskvorky** [comment]
Hi, please read and follow the issue template.

**Comment by mmatheuslyra** [comment]
Hello, I would like to understand better the difference between the "iter" and "epoch" parameters in the Word2vec algorithm. 

Does the epoch parameter have an equivalent to the Mikolov's implementation? 

Actually, I haven't seen any mention to the Epoch parameter in the Mikolov job, so how could I replicate it? Would be enough an execution like Gensim.Word2vec(iter = 5, epoch = 5) Mikolov.Word2vec(iter = 5) to run the same for these two parameters?

**Steps/code/corpus to reproduce**
**Gensim.word2vec**: model_w2v_skpg = gensim.models.Word2Vec(sg=1, size=200, workers=48, negative=25, window = 5, iter = 5, epoch = 5)
**Mikolov.word2vec** ./word2vec -train text8 -output vectors.txt -cbow 1 -size 200 -window 5 -negative 5 -threads 20 -binary 0 -iter 5

**Versions**
Linux-4.4.0-62-generic-x86_64-with-Ubuntu-16.04-xenial
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
NumPy 1.16.3
SciPy 1.2.1
gensim 3.7.2
FAST_VERSION 1

**Comment by mpenkov** [comment]
@mmatheuslyra From the issue template:

**IMPORTANT**:

**- Use the [Gensim mailing list](https://groups.google.com/forum/#!forum/gensim) to ask general or usage questions. Github issues are only for bug reports.**
- Check [Recipes&FAQ](https://github.com/RaRe-Technologies/gensim/wiki/Recipes-&-FAQ) first for common answers.

---

Please direct your question at the mailing list.
