### ISSUE TITLE
Hi，I wanna know how to retain the information of "title tag" when processing the corpus.xml into plain corpus.txt

### ISSUE THREAD

**Issue by 27232xsl** [RaRe-Technologies/gensim#2488]
I have a entity set， and I wanna extract entity-related page information from Wikipedia, but when the corpus.xml is processed into a corpus.txt, title information is filtered out, so I can't link my entity to the information in Wikipedia corpus. I want to know how to keep "title tag" information. I would appreciate it if you can help me.(Thank you so much!!!)

**Comment by mpenkov** [comment]
Please use the gensim mailing list for questions. Github tickets are for bug requests only.
