### ISSUE TITLE
Provision for enriching just the vocabulary and not the documents

### ISSUE THREAD

**Issue by rupamroy** [RaRe-Technologies/gensim#2495]
#### Problem description

I have a small list of sentences and I am trying to use that to create a document similarity based search. 
Gensim is correctly able to relate the search sentence with closest sentences in the corpus when the most of the words match . But when the input is the same question using a different set of words (synonyms or lexically similar word), it cannot get a match.

In creating the model there are two steps 
1. create_vocab
2. train

In the create_vocab i want to use a large corpus of created say from wikipedia + the training corpus, but the training is done only using the train corpus. 
I expect that by building the vocal of a large corpus it will enrich the word vector embeddings within the model . Then when try to infer the similarity for a new sentence which has synonyms for an existing sentence , it should be able to provide me with the correct match from the train corpus. 

But unfortunately that is not happening, rather what is happening is we are getting answers from the large wikipedia corpus. 

Is what i trying to do even makes sense and if so what is going wrong here.

#### Steps/code/corpus to reproduce

This is my vision 
lets say i have a set of sentences like 
```
[ ' the new rates are effective from this monday', 'If the customer has opted into new rate and wants to remain on their custom rate card, then it will be evaluated on a case by case basis at the SLT level based on a developed exception framework If the customer has opted out of all new rate payment plans, and wants to remain on their custom Singles Card, then they may do so; these exceptions will continue to operate as they do today through DPIC and PIC evaluations', 'Company remains committed to transparent pricing, and also to serving our customer’s needs. The introduction of new rate is in response to directional shifts in the marketplace by our customers. Customers will have the choice of staying on rate cards with transparent pricing or opting in to new rate for more granular pricing', ..........]
```

now if the question is asked
what was the reason for such deviating modification 

it should show me the 3rd sentence to be most similar , it is not doing that but showing some other sentences with very low confidence score.  I believe that is because it does know know that **deviating modification**  and **directional shift** are very close phrases. By introducing a large vocab i expect that knowledge to be imparted to the model thus resulting better results. 

I am using the following code to train  the model
```python
train_corpus = # some small list
vocab_corpus = train_corpus + # huge wikipedia corpus
model = gensim.models.doc2vec.Doc2Vec(vector_size=100, alpha=0.025, min_count=2, min_alpha=0.025, dbow_words=1, dm_concat=1)
model.build_vocab(vocab_corpus)
# There was a huge optimization by running the training repeatedly with a decreasing alpha value. 
for epoch in range(4):
    model.train(train_corpus, total_examples=model.corpus_count, epochs=40)
    model.alpha -= 0.002  # decrease the learning rate
    model.min_alpha = model.alpha  # fix the learning rate, no decay
```

If what i am thinking is not possible , is there any way to enrich the lexical knowledge of the model by introducing synonyms or phrases or n-grams etc. 

#### Versions

Please provide the output of:

```python
Linux-4.15.0-48-generic-x86_64-with-debian-buster-sid
Python 3.7.1 (default, Dec 14 2018, 19:28:38) 
[GCC 7.3.0]
NumPy 1.15.4
SciPy 1.1.0
gensim 3.4.0
FAST_VERSION 1
```

**Comment by gojomo** [comment]
It's not clear what you're asking. Do you want a new feature? Do you think there's a bug? If you just want help using what's available, the forum <https://groups.google.com/forum/#!forum/gensim> is a better channel. 

Other comments on what you've shown: 

* You probably don't want to use `dm_concat=1` mode. It results in much larger, slower-to-train models for unclear benefit. 

* `dbow_words=1` has no effect unless you've switched to PV-DBOW mode (`dm=0`)

* You probably don't want to be changing the default `alpha`, `min_alpha`, nor calling `train()` multiple times in your own loop. (Here, you're calling `train()` 4 times, but then each `train()` is also doing 40 epochs, for a total of 160 passes over the data. Typical `Doc2Vec` published results use 10-20 total passes. And your manual `alpha` management only lowers it to `0.025 - (4 * 0.002)`, which is `0.018`. Proper SGD would bring it down to a negligible value at the end of training, like the default `min_alpha`. 

* `min_count=2` is probably a bad idea: keeping such infrequent words, in a large corpus, in addition to making the model larger and training slower usually makes the final vector-quality worse. 

* You're not showing how you're looking for similar sentences, or examples of unsatisfactory results, so it's hard to guess what you might be doing wrong, or might be going wrong. (In particular, that 'set of sentences' would have to be tokenized to be useful in usual training/inference – `Doc2Vec` does not work on strings, but lists-of-words.)

* Appending some other large corpus to your domain corpus will not necessarily help. Especially if it's larger than your corpus, and uses words/word-senses differently, it could easily hurt, swamping whatever domain-specific word-meanings could be learned from your data with the more generic sense in the outside corpus. The best approach would be to have plenty of data that uses language in ways that match your problem domain. 

You should probably improve these issues in your code/report, and if you're still having problems, show more detail of what's falling short and ask for suggestions in the forum.

**Comment by gojomo** [comment]
No clarifications from reporter in response to questions/suggestions. No clear bug or required feature. Closing.
