### ISSUE TITLE
Get rid of Python implementation of fastText, word2vec, doc2vec

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#2511]
We have Cython implementations for the above models, so that we fall back to Python when Cython is not available.

This is more hassle than it's worth, because:

1. The Python versions are too slow to be practical
2. We have to expend additional effort to test the Python versions (leading to bugs like this: https://github.com/RaRe-Technologies/gensim/issues/2508#issuecomment-497182316)
3. The Cython implementations are available most of the time. For people who don't have a compiler, we offer wheels.

**Comment by gojomo** [comment]
Looking at just word2vec.py, there's still at least two functions that were only used by the pure-Python path remaining: `train_cbow_pair()` & `train_sg_pair()`.

**Comment by amirouche** [comment]
What about PyPy?

**Comment by gojomo** [comment]
@amirouche I doubt the old pure-Python code worked very well under PyPy, but would be interested to learn if you (or anyone) was using it there & getting acceptable performance. My understanding is the Cython optimized code can work with PyPy, if the C code is recompiled there.

So my conjecture would be any PyPy users getting acceptable performance from gensim's "*2Vec" code were already doing that, and can still do that after this change.
