### ISSUE TITLE
gensim.models.Phraser score_item method returns a tuple instead of a float in gensim 3.7.3

### ISSUE THREAD

**Issue by CarlosSanabriaM** [RaRe-Technologies/gensim#2517]
## Problem description

The gensim.models.Phraser score_item method returns a tuple instead of a float.
In gensim 3.4.0, the content of the score_item method of the Phraser class was:

```python

def score_item(self, worda, wordb, components, scorer):
        """score is retained from original dataset
        """
        try:
            return self.phrasegrams[tuple(components)][1]
        except KeyError:
            return -1
```

In gensim 3.7.3, the content of the score_item method of the Phraser class is:

```python

    def score_item(self, worda, wordb, components, scorer):
        """Score a bigram.

        Parameters
        ----------
        worda : str
            First word for comparison.
        wordb : str
            Second word for comparison.
        components : generator
            Contain phrases.
        scorer : {'default', 'npmi'}
            NOT USED.

        Returns
        -------
        float
            Score for given bi-gram, if bi-gram not presented in dictionary - return -1.

        """
        try:
            return self.phrasegrams[tuple(components)]
        except KeyError:
            return -1
```

The **[1]** of the line `return self.phrasegrams[tuple(components)][1]` disappeared.

I don't know if this has an explanation, but without that [1], the method returns a tuple instead of a float. The pythondoc comment of the method in gensim 3.7.3 says that it should return a float, so I think this is a bug.

I had a Phraser model stored on disk that was working fine in gensim 3.4.0, but now fails in gensim 3.7.3, raising the following Exception in the analyze_sentence method, which is the one that compares the score returned by score_item, and the threshold:

```codeblock
...
.../lib/python3.6/site-packages/gensim/models/phrases.py", line 169, in analyze_sentence
    if score > threshold:
TypeError: '>' not supported between instances of 'tuple' and 'int'
```

The code of the analyze_sentence method contains:

```python
def analyze_sentence(self, sentence, threshold, common_terms, scorer):
    <more code ...>
    score = self.score_item(
                    worda=last_uncommon,
                    wordb=word,
                    components=chain,
                    scorer=scorer,
                )
                if score > threshold:
                    <more code ...>
    <more code ...>
```

Here we can see that, if the score_item method returns a tuple, the score variable will contain a tuple, and the expression `score > threshold` will fail.

This exception only gets raised when the 2 words passed to the score_item function generate a bigram. This is because, if the words doesn't generate a bigram, `self.phrasegrams[tuple(components)]` raises a KeyError exception, and the score_item method returns -1 instead of a tuple.

#### Solution
Add again the [1] to the `return self.phrasegrams[tuple(components)]` line of the score_item method, this way:

```python
    def score_item(self, worda, wordb, components, scorer):
        """Score a bigram.

        Parameters
        ----------
        worda : str
            First word for comparison.
        wordb : str
            Second word for comparison.
        components : generator
            Contain phrases.
        scorer : {'default', 'npmi'}
            NOT USED.

        Returns
        -------
        float
            Score for given bi-gram, if bi-gram not presented in dictionary - return -1.

        """
        try:
            return self.phrasegrams[tuple(components)][1]
        except KeyError:
            return -1
```

**Comment by horpto** [comment]
Hi, @CarlosSanabriaM. `score_item` should actually work properly due to [this merged pull request](#2208) in the gensim 3.7.0. Check it out that and especially tests. I think the actual problem not in `score_item` but loading model. How do you load your Phraser model?  What the `phrasegrams` attribute contains: is it tuple or float?

**Comment by mpenkov** [comment]
@CarlosSanabriaM Ping

**Comment by CarlosSanabriaM** [comment]
Hi @horpto @mpenkov. The link you have posted doesn't take me to the pull request.

The fact is that I don't use the save or load methods of gensim.models.Phraser to save/load the model. I have the following:
``` python
# Create a lambda function that given a list of words, generates ngrams (bi, tri or quater)
bigram = gensim.models.Phrases(docs_list, min_count=min_count1, threshold=threshold1)
trigram = gensim.models.Phrases(bigram[docs_list], min_count=min_count2, threshold=threshold2)
bigram_model = gensim.models.phrases.Phraser(bigram)
trigram_model = gensim.models.phrases.Phraser(trigram)
trigram_model_func = lambda x: trigram_model[bigram_model[x]]

# Save the lambda function
with open(path, 'wb') as f:
    dill.dump(trigram_model_func, f, pickle.HIGHEST_PROTOCOL)
```

**Comment by piskvorky** [comment]
Yeah, there were changes around what we keep inside this model.

IIRC we implemented backward compatible loading in `.load()`, so if you use that, even old models continue to work.

But if you stored your old model in some other format, you're on your own I'm afraid.

What you could do is 1) load your existing model in 3.4.0 (where it worked), then 2) save it with `.save()`, then 3) load that in 3.7.3 with `.load()`, and then 4) save that in your custom format again. Basically upgrade your model upgrade. We cannot support all conceivable formats between upgrades, so we focus on our official `load` and `save`.

**Comment by CarlosSanabriaM** [comment]
Thanks for answering 😄! 

I understand. I thought it could be a bug, but seems it's controlled.

I close the issue then.
