### ISSUE TITLE
Bug in models.phraser.original_scorer

### ISSUE THREAD

**Issue by robguinness** [RaRe-Technologies/gensim#2520]
#### Problem description

There seems to be a bug in models.phraser.original_scorer. `min_count` is defined as "Minimum collocation count threshold", which is a bit ambiguous, but this argument actually corresponds to `Phrases.min_count`, which is defined as:

```
min_count : float, optional
            Ignore all words and bigrams with total collected count lower than this value.
```
Given this definition, line 692 is seemingly incorrect:

```
return (bigram_count - min_count) / worda_count / wordb_count * len_vocab
```

When bigram_count == min_count, this will return zero, meaning that either the definition of min_count is wrong, or this formula is incorrect.

#### Versions

I'm using gensim 3.7.3, but this issue seems to go back all the way to the original commit of the phrases module back in 0.10.3.

**Comment by piskvorky** [comment]
@robguinness what is the actual bug? Why do you think the definition is incorrect (the formula is definitely correct)? Can you give an example?

**Comment by robguinness** [comment]
It's been awhile since I've looked at this, but after reviewing it I believe this issue fails somewhere in the gray error between a bug and confusing documentation. The issue is that if you have a document where `ngram count == min_count`, the function will return zero. This is contrary to the definition provided for `min_count`, where one would expect it to return a positive value for the case ngram count == min_count` based on the description. The way the value is actually used though is the return value is compared to the value of `threshold` in `SentenceAnalyzer.analyze_sentence`. So technically-speaking a negative value is allowed. But compare this to the case of `npmi_scorer`:

```
if bigram_count >= min_count:
        pa = worda_count / corpus_word_count
        pb = wordb_count / corpus_word_count
        pab = bigram_count / corpus_word_count
        return log(pab / (pa * pb)) / -log(pab)
    else:
        # Return -infinity to make sure that no phrases will be created
        # from bigrams less frequent than min_count
        return float('-inf')
```
Maybe what happened is somebody copied the description of `min_count` from `npmi_scorer`, but the description really doesn't correspond with how it is used in the case of `original_scorer`.

In fact, now that I review this method, the description of the return value is misleading as well:

```
Returns
    -------
    float
        Score for given bi-gram, greater than or equal to 0.
```

Clearly it can return values less than zero based on the actual function.

**Comment by piskvorky** [comment]
You're right, thanks. We should clean the documentation up. Can you do it?

**Comment by robguinness** [comment]
Not this week at leas...I'm swamped. But I'll keep this on my radar.
