### ISSUE TITLE
Increasing Perplexity with number of topics

### ISSUE THREAD

**Issue by snollygoster123123** [RaRe-Technologies/gensim#2521]
In order to evaluate the best number of topics for my dataset, I split the set into testset and trainingset (25%, 75%, 18k documents alltogether). But somehow my perplexity keeps increasing on the testset. I don't know exactly why.

You can see the perplexity here: https://imgur.com/FE9KF2Z

Corpus can be found here: http://uploaded.net/file/nkru8zi7

I split the corpus the following way (using sklearn)
corpus_train, corpus_test = train_test_split(corpus, test_size=0.25)

Then I apply LDA on the train_set. Then get the perplexity using

perplexity = 2 ** (-1.0 * lda_model.log_perplexity(corpus_test))

on the testset.

I do a new split for every number of topic (So I don't have one split and use it for every number of topics, but do a new split everytime before applying lda)

Any suggestions?

**Comment by mpenkov** [comment]
Please consider asking this question on the [Gensim mailing list](https://groups.google.com/forum/#!forum/gensim).

We typically use github ticket for bug reports and feature requests only.
