### ISSUE TITLE
LdaMallet load_document_topics() fails.

### ISSUE THREAD

**Issue by Sean16SYSU** [RaRe-Technologies/gensim#2522]
#### Problem description

**Trying: ** When I use method `load_document_topics()` in a trained LdaMallet model today, I got the following Error:

```python
RuntimeError                              Traceback (most recent call last)
<ipython-input-138-6d106e31d9f6> in <module>
      1 tot = []
----> 2 for w in model.load_document_topics():
      3     tot.append(list(map(lambda x:x[1], sorted(w))))

d:\code\git\gensim\gensim\models\wrappers\ldamallet.py in read_doctopics(self, fname, eps, renorm)
    560                                     count += 1
    561                     else:
--> 562                         raise RuntimeError("invalid doc topics format at line %i in %s" % (lineno + 1, fname))
    563 
    564                 if renorm:

RuntimeError: invalid doc topics format at line 2946 in ./model\r20_n20doctopics.txt
```

* ` ./model\r20_n20` is the prefix.

I have checked the file and find something wrong with the second columns, like:

```python 
0 0 0.2 0.3 0.5 
1    0.3 0.2 0.5
2 1 0.2 0.1 0.7

...
```

#### Versions

```python
Windows-10-10.0.15063-SP0
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]
NumPy 1.16.2
SciPy 1.1.0
gensim 3.7.3
FAST_VERSION 0
```

**Comment by piskvorky** [comment]
This file is produced by Mallet. Sorry, not much we can do. Try asking the Mallet authors.

Probably unrelated, but the mix of forward and backward slashes in your path is worrying. I'd recommend avoiding backward slashes in your filenames. I wonder how that even works, as a backward slash on Windows can be interpreted as a directory separator…
