### ISSUE TITLE
Word2Vec Threading problem

### ISSUE THREAD

**Issue by balla2081** [RaRe-Technologies/gensim#2526]
#### Problem description

Hi, I am trying to train a word2vec model with gensim.
But, it seems to have a problem.
Training fails when I put more than 2000 sentences into model.

#### Steps/code/corpus to reproduce
![Screen Shot 2019-06-13 at 1 19 04 PM](https://user-images.githubusercontent.com/10040328/59453419-d9084f00-8ddd-11e9-99f9-65f68210186c.png)

#### Versions

Please provide the output of:

```python
Linux-4.4.0-143-generic-x86_64-with-Ubuntu-16.04-xenial
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
NumPy 1.16.2
SciPy 1.2.1
gensim 3.7.2
FAST_VERSION 1
```

**Comment by piskvorky** [comment]
We'll need a minimal reproducible example (incl. relevant data and copy-pastable relevant code) first.

**Comment by balla2081** [comment]
I think I solve the problem.
I passed the total number of corpus in build_vocab_from_freq, and It solved.

model.build_vocab_from_freq(counter, corpus_count = len(corpus))

I think corpus_count is essential when people use build_vocab_from_freq.
