### ISSUE TITLE
"Pattern library is not installed" ... but it is (perhaps because it is called pattern3)

### ISSUE THREAD

**Issue by falconair** [RaRe-Technologies/gensim#2534]
#### Problem description

I am trying to do a gensim tutorial project. I am attempting to lemmatize and getting this error:
ImportError: Pattern library is not installed. Pattern library is needed in order to use lemmatize function

After searching the web, I installed pattern3, I still get the same error. I tried to do 'import pattern3 as pattern' but that doesn't help. Obviously I'm on python 3 (3.6)

#### Steps/code/corpus to reproduce

 import gensim
 from gensim.utils import simple_preprocess, lemmatize
 import pattern3

lemmatize("hello")

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

Darwin-15.6.0-x86_64-i386-64bit
Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.16.4
SciPy 1.2.1
gensim 3.7.3
FAST_VERSION 1

#### Additional info

`from pattern3.web import Twitter`
this works fine

`from pattern.web import Twitter`
this does not (even after I do `import pattern3 as pattern`)

**Comment by piskvorky** [comment]
Does `pattern` support Python 3 now?

If so, we could perhaps upgrade that (optional) dependency in Gensim.

@falconair Can you open a PR with the `pattern` migration? Assuming it offers similar functionality as the old one.

**Comment by Hiyorimi** [comment]
From pattern's [Readme](https://github.com/clips/pattern/blob/master/README.md) it looks like it supports Python 3.

I'll try to take this one.

**Comment by mpenkov** [comment]
I think these may be the same essential package:

- [pattern3](https://pypi.org/project/pattern3/)
- [Pattern](https://pypi.org/project/Pattern/) (not the upper-case P, it matters to PyPI)

and gensim is only looking for one of them.

**Comment by Hiyorimi** [comment]
@mpenkov the latter is the correct PyPl package, referenced from original repo's Readme. It looks like, it should work as a drop-in replacement, so I only fixed 1 line with version dependency, where I could find one

**Comment by onurtimur** [comment]
You can find the pattern official web site from here: https://www.clips.uantwerpen.be/pages/pattern
If you try to install from pip it installs something else. But it looks like it is supporting Python 2.5+ at the moment.

**Comment by JiaxiangBU** [comment]
> You can find the pattern official web site from here: https://www.clips.uantwerpen.be/pages/pattern

This page is invalid.

Not Found
The requested URL was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12 mod_perl/2.0.9 Perl/v5.22.1 Server at www.clips.uantwerpen.be Port 443
