### ISSUE TITLE
streamlining most_similar_cosmul

### ISSUE THREAD

**Issue by eyaler** [RaRe-Technologies/gensim#2535]
this is a feature request to make most_similar_cosmul() more similar (pun intended) to most_similar() by the following changes:

1. add restrict_vocab argument
2. allow positive and negative to be strings instead of list-of-strings in case of single words
3. allow usage in evaluate_word_analogies

**Comment by EinKaiser** [comment]
Hi, can I have a go at this?

**Comment by mpenkov** [comment]
Yes.

**Comment by n3hrox** [comment]
Hey @eyaler, @mpenkov - since there was no open PRs for this I decided to give it a go, let me know what you think
