### ISSUE TITLE
FastText inconsistent normalization in adjust_vectors method vs word_vec

### ISSUE THREAD

**Issue by vackosar** [RaRe-Technologies/gensim#2537]
#### Problem description

There is inconsistency in normalization in ```FastTextKeyedVectors#adjust_vectors``` vs ```WordEmbeddingsKeyedVectors#word_vec```

#### Steps/code/corpus to reproduce

adjust_vectors:
```
            word_vec /= len(ngram_hashes) + 1
```

word_vec method:
```
            return word_vec / len(ngram_hashes)
```

#### Versions

```
Linux-4.18.0-24-generic-x86_64-with-Ubuntu-18.04-bionic
Python 3.7.1 (default, Oct 22 2018, 11:21:55) 
[GCC 8.2.0]
NumPy 1.16.3
SciPy 1.2.1
gensim 3.7.3
FAST_VERSION 1
```

**Comment by vackosar** [comment]
The ```adjustment_vectors``` method adds subword representations to the words themselves, where ```+1``` seems to represent original learned vector of the whole word.

**Comment by piskvorky** [comment]
@vackosar if that's the case, can you add a code comment to the relevant places? It might trip up others too, in the future, so let's be explicit.

**Comment by mpenkov** [comment]
I agree that the two implementations appear to be inconsistent. I think this is a bug.

This is what I rewrote when I worked on fastText a few months ago:

```
b452a5b59 (Michael Penkov       2019-01-12 00:07:40 +0900 2289)             word_vec = np.copy(self.vectors_vocab[v.index])
411f54663 (Michael Penkov       2019-01-24 13:51:40 +0900 2290)             ngram_hashes = ft_ngram_hashes(w, self.min_n, self.max_n, self.bucket, self.compatible_hash)
411f54663 (Michael Penkov       2019-01-24 13:51:40 +0900 2291)             for nh in ngram_hashes:
b1850d948 (Michael Penkov       2019-03-07 15:44:31 +0900 2292)                 word_vec += self.vectors_ngrams[nh]
411f54663 (Michael Penkov       2019-01-24 13:51:40 +0900 2293)             word_vec /= len(ngram_hashes) + 1
b452a5b59 (Michael Penkov       2019-01-12 00:07:40 +0900 2294)             self.vectors[v.index] = word_vec
```

This is the old version of the FastText code:

```
9021ea8b3 (Johannes Baiter      2018-03-01 09:17:43 +0100 2001)             ngrams_found = 0
916e423a1 (Shiva Manne          2018-02-01 21:50:20 +0530 2002)             for ngram in ngrams:
9021ea8b3 (Johannes Baiter      2018-03-01 09:17:43 +0100 2003)                 ngram_hash = _ft_hash(ngram) % self.bucket
9021ea8b3 (Johannes Baiter      2018-03-01 09:17:43 +0100 2004)                 if ngram_hash in self.hash2index:
9021ea8b3 (Johannes Baiter      2018-03-01 09:17:43 +0100 2005)                     word_vec += ngram_weights[self.hash2index[ngram_hash]]
9021ea8b3 (Johannes Baiter      2018-03-01 09:17:43 +0100 2006)                     ngrams_found += 1
916e423a1 (Shiva Manne          2018-02-01 21:50:20 +0530 2007)             if word_vec.any():
9021ea8b3 (Johannes Baiter      2018-03-01 09:17:43 +0100 2008)                 return word_vec / max(1, ngrams_found)
916e423a1 (Shiva Manne          2018-02-01 21:50:20 +0530 2009)             else:  # No ngrams of the word are present in self.ngrams
916e423a1 (Shiva Manne          2018-02-01 21:50:20 +0530 2010)                 raise KeyError('all ngrams for word %s absent from model' % word)
```

I think the change to make here is:

- Before: word_vec /= len(ngram_hashes) + 1
- After: word_vec /= max(len(ngram_hashes), 1)

**Comment by piskvorky** [comment]
@vackosar can you open a PR?

**Comment by vackosar** [comment]
@piskvorky @mpenkov I will submit the PR but are you sure about this?
In the [original implementation](https://github.com/facebookresearch/fastText/blob/979d8a9ac99c731d653843890c2364ade0f7d9d3/src/dictionary.cc#L201) the word itself is appended to its n-grams and then everytime when there is a normalization they just divide by ```ngram.size()``` which would mean there is hidden "+1" there too.

**Comment by vackosar** [comment]
By the way, I posted couple of FastText norm visualizations [here](https://github.com/vackosar/fasttext-vector-norms-and-oov-words), if you are interested.

**Comment by vackosar** [comment]
Here is the PR https://github.com/RaRe-Technologies/gensim/pull/2551

**Comment by gojomo** [comment]
There's no inconsistency. In the `word_vec()` method, the codepath where a simple `return word_vec / len(ngram_hashes)` occurs is *only* for OOV words, where *no* full-word trained vector (from `vectors_vocab`) exists. Thus it's *only* the average of the ngrams. OTOH, the `adjust_vectors()` codepath is specifically calculating the effective vectors only for in-vocabulary words, which are composed from the trained full-word vectors **plus** all the ngram-vectors. That is, one more vector was part of the average.

Of the many oddnesses of the gensim FT implementation, this behavior (as noted by @vackosar in comment https://github.com/RaRe-Technologies/gensim/issues/2537#issuecomment-508346402) is consistent with the FB reference implementation, so there's no bug, and no reason for the associated code-changing PR.

**Comment by mpenkov** [comment]
So if there is no problem, we can close #2551?

**Comment by gojomo** [comment]
> @gojomo So if there is no problem, we can close #2551?

Yes, no bug & thus no fix needed!
