### ISSUE TITLE
Fast version of Word2Vec gone after an update of Gensim

### ISSUE THREAD

**Issue by Jojoteur** [RaRe-Technologies/gensim#2549]
Hi, I'm having trouble with the fast version of Word2Vec after an update of gensim. I am using Windows 10, Python 3.7.3 and Conda 4.7.5. 

Here are the exact steps that I did : 

1. I created a new environment with : `conda create --name envTest`

2. I successfully activated envTest (`conda activate envTest`) and installed gensim (`conda install gensim`).

The latest version available of Gensim on Anaconda seems to be 3.4.0 : 
![screen3](https://user-images.githubusercontent.com/48619415/60570834-a6b19800-9d72-11e9-8c23-fc23b2e1010d.png)

At this moment, there was the fast version of Word2Vec : 
![screen2](https://user-images.githubusercontent.com/48619415/60570880-c1840c80-9d72-11e9-881b-185374d74a42.PNG)

Then, I tried to use WordEmbeddingSimilarityIndex from gensim.models, but it gave me this error : 
![screen1](https://user-images.githubusercontent.com/48619415/60571044-13c52d80-9d73-11e9-9502-58188087843a.PNG)

According to this post [https://stackoverflow.com/questions/54650673/how-to-import-wordembeddingsimilarityindex-function-from-gensim-module](url), my version of gensim is too old to use WordEmbeddingSimiliratyIndex, so I updated it.

I tried to update it with conda, but it told me that there is nothing to update : 
![screen4](https://user-images.githubusercontent.com/48619415/60571197-6a326c00-9d73-11e9-81b0-b6834d5462e1.PNG)

So, I tried with pip, and it works (`python -m pip install --user --upgrade gensim`). Gensim's version is now 3.7.3 and WordEmbeddedSimilarityIndex works perfectly. 
![screen5](https://user-images.githubusercontent.com/48619415/60571281-95b55680-9d73-11e9-8513-a7815cf908e9.PNG)

Finally, the problem is that after the update, the fast version was gone : 
![screen6](https://user-images.githubusercontent.com/48619415/60571298-a49c0900-9d73-11e9-9c4b-8fc916264b3b.PNG)

Does someone knows where this problem comes from ?

**Comment by piskvorky** [comment]
The installation log during `pip install` should tell you what's wrong.

Conda is not really supported, but let us know if you hit any issues with `pip`.

**Comment by gojomo** [comment]
Yes, watching the output carefully during the `pip install` should reveal any problems encountered with that upgrade. Most likely, you're missing the necessary c-compilation tools or other support libraries required for the fully-optimized paths to be compiled. (For the `conda` install process, they may be grabbing pre-compiled versions of all necessary libraries for you instead.)

**Comment by mpenkov** [comment]
@Jojoteur Ping
