### ISSUE TITLE
WikiCorpus.get_text logs ARTICLE_MIN_WORDS instead of article_min_tokens

### ISSUE THREAD

**Issue by 0x0badc0de** [RaRe-Technologies/gensim#2554]
#### Problem description

`WikiCorpus.get_texts` logs `ARTICLE_MIN_WORDS` instead of `article_min_tokens`.
I've passed a custom value for `article_min_tokens` but instead default one gets logged.
See:
https://github.com/RaRe-Technologies/gensim/blob/3.8.0/gensim/corpora/wikicorpus.py#L703
https://github.com/RaRe-Technologies/gensim/blob/3.8.0/gensim/corpora/wikicorpus.py#L712

#### Steps/code/corpus to reproduce

1. Just provide any value for `article_min_tokens` (except 50 obviously) in `WikiCorpus.__init__`
2. Invoke `get_texts`
2. See default one in logs

#### Versions

Please provide the output of:

```python
Python 3.7.3 (default, May  8 2019, 05:28:42)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Linux-4.9.125-linuxkit-x86_64-with-debian-9.9
>>> import sys; print("Python", sys.version)
Python 3.7.3 (default, May  8 2019, 05:28:42)
[GCC 6.3.0 20170516]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.16.4
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.3.0
>>> import gensim; print("gensim", gensim.__version__)
gensim 3.7.3
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 1
```

**Comment by mpenkov** [comment]
Thank you for reporting this. Are you able to make a PR?
