### ISSUE TITLE
`smart_open` dependency requirement outdated?

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#2555]
Gensim claims to require smart_open >= 1.7.0:
https://github.com/RaRe-Technologies/gensim/blob/f97d0e793faa57877a2bbedc15c287835463eaa9/setup.py#L384

but doesn't Gensim depend on `smart_open.open` now, which was introduced only in smart_open >= 1.8.1?

https://github.com/RaRe-Technologies/smart_open/releases/tag/1.8.1

(a suspicion based on seeing user issues on the [mailing list](https://groups.google.com/forum/#!topic/gensim/FSxNYppNpO8); are we CI testing against the *oldest* supported versions of our dependencies?)

**Comment by mpenkov** [comment]
Fixed in f2ad5c2d
