### ISSUE TITLE
"TypeError: '<' not supported between … 'str' and 'int'"

### ISSUE THREAD

**Issue by khalid5454** [RaRe-Technologies/gensim#2557]
#### Problem description

What are you trying to achieve? What is the expected result? What are you seeing instead?

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

**Comment by khalid5454** [comment]
While reading a csv file get
ERROR = "TypeError: '<' not supported between … 'str' and 'int'"

Following is my code
-----------------------

df2 = pd.read_csv(img_category_path, delim_whitespace= True,  header=0, names=['category'], low_memory=False )

df['upper_lower'] = ['1' if i < 21 else '3' if i)  >36   else  '2' for i in df2['category']]

##Then i try to convert like this but got further error
df['upper_lower'] = ['1' if int(i) < 21 else '3' if int(i)  >36   else  '2' for i in df2['category']]

####ERROR########

alueError                                Traceback (most recent call last)
<ipython-input-47-266486f673bf> in <module>
      1 #df['upper_lower'] = ['1' if i < 21 else '3' if   i > 36  else  '2' for i in df2['category']]
----> 2 df['upper_lower'] = ['1' if int(i) < 21 else '3' if int(i)  >36   else  '2' for i in df2['category']]

<ipython-input-47-266486f673bf> in <listcomp>(.0)
      1 #df['upper_lower'] = ['1' if i < 21 else '3' if   i > 36  else  '2' for i in df2['category']]
----> 2 df['upper_lower'] = ['1' if int(i) < 21 else '3' if int(i)  >36   else  '2' for i in df2['category']]

ValueError: invalid literal for int() with base 10: 'category_label'


Any solution please

**Comment by gojomo** [comment]
@khalid5454  I don't see any portion of your code involving `gensim`. Perhaps you should ask in a Pandas or general Python forum? This issue-tracker is for bugs/feature-requests in `gensim`.

**Comment by khalid5454** [comment]
#have a look on my code 

df2 = pd.read_csv(img_category_path, delim_whitespace= True, header=0, skip_blank_lines=True, names=['category'], low_memory=False )

print(img_category_path)
df2.head(5)

#result i get

C:\Users\Muhammad Khalid\Desktop\CRS/Category and Attribute Prediction Benchmark/Anno/list_category_img.txt

#and 


-                                                                           category `
                           image_name                                        |  category_label`

img/Sheer_Pleated-Front_Blouse/img_00000001.jpg         | 3

img/Sheer_Pleated-Front_Blouse/img_00000002.jpg         | 3

and so on the file contain

#Now trying to access like this which give me error

df['upper_lower'] = ['1' if i < 21 else  '3'  if i >36    else  '2' for i in df2['category']]


ERROR >>>>>>>>>>

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-b3000dc6a5a2> in <module>
      1 #df['upper_lower'] = ['1' if i < 21 else '3' if   i > 36  else  '2' for i in df2['category']]
----> 2 df['upper_lower'] = ['1' if i < 21 else  '3'  if i >36    else  '2' for i in df2['category']]

<ipython-input-24-b3000dc6a5a2> in <listcomp>(.0)
      1 #df['upper_lower'] = ['1' if i < 21 else '3' if   i > 36  else  '2' for i in df2['category']]
----> 2 df['upper_lower'] = ['1' if i < 21 else  '3'  if i >36    else  '2' for i in df2['category']]

TypeError: '<' not supported between instances of 'str' and 'int'
