### ISSUE TITLE
word2vec does not find model.wv

### ISSUE THREAD

**Issue by marcalt94** [RaRe-Technologies/gensim#2562]
#### Problem description

What are you trying to achieve? What is the expected result? What are you seeing instead?

Hey,
I am trying to reproduce this [word2vec tutorial](https://radimrehurek.com/gensim/models/word2vec.html), but at a certain point I always run into the same error. When I try to run the ```vector = wv['computer']  # numpy vector of a word``` part of the tutorial, I get  the ```FileNotFoundError: [Errno 2] No such file or directory: 'model.wv'``` error. I have executed all previous tutorial steps, so the file should be created, but the model still does not find it.

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform()) Windows-10-10.0.17134-SP0

import sys; print("Python", sys.version) Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]

import numpy; print("NumPy", numpy.__version__)  NumPy 1.16.4

import scipy; print("SciPy", scipy.__version__) SciPy 1.2.1

import gensim; print("gensim", gensim.__version__) gensim 3.4.0

from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION) FAST_VERSION 1
```

**Comment by mpenkov** [comment]
It's strange that you're experiencing the FileNotFound error while trying to retrieve a vector for a term. Are you sure that's the line that's causing a problem?

I tried running the code in the doc that you linked, and did not encounter the same issue you reported.

Can you copy-paste the relevant parts of that tutorial into a hello.py script, run that script, and post the output (including the full script and the stack trace)?

**Comment by marcalt94** [comment]
I followed the tutorial line for line, and that was the line that came directly before the error

**Comment by marcalt94** [comment]
![warn](https://user-images.githubusercontent.com/44497700/62069713-31ce6280-b239-11e9-82e3-291873b6c645.PNG)

It just gave me this warning this time and stopped. I found a workaround by just using the ```word2vec.model ``` file instead of ```model.wv``` , but I don't think it's correct 

[hello.zip](https://github.com/RaRe-Technologies/gensim/files/3443589/hello.zip)

**Comment by mpenkov** [comment]
What's the point of zipping the file? It's a dozen lines long.

```
from gensim.test.utils import common_texts, get_tmpfile
from gensim.models import Word2Vec

path = get_tmpfile("word2vec.model")

model = Word2Vec(common_texts, size=100, window=5, min_count=1, workers=4)
model.save("word2vec.model")

model = Word2Vec.load("word2vec.model")
model.train([["hello", "world"]], total_examples=1, epochs=1)

vector = model.wv['computer']
print(vector)  # I added this line to show you that the vector gets calculated correctly
```

If I run the above, I get:

```
[ 3.8149676e-03 -1.9192016e-03  2.0597517e-03 -1.6081211e-03
  1.4334370e-03 -9.7547792e-04  2.2860225e-03  1.2791508e-03
  3.5027319e-03 -4.5925891e-03  6.6249981e-04 -2.8255181e-03
 -2.2419044e-03  3.9091078e-03 -1.7945991e-03  1.2338783e-03
  3.2082100e-03 -3.6298032e-03 -2.2599855e-03  2.2338086e-03
 -4.7574658e-03 -8.8325882e-04 -1.4419218e-03  3.8973985e-03
 -1.8553529e-03 -2.7318401e-03 -1.8148198e-03 -3.0513096e-03
  1.7427068e-03  2.0636830e-03  3.8267525e-03 -3.3828167e-03
 -2.5132142e-03 -2.4252769e-03 -3.7351879e-03  3.1133427e-03
 -3.8008378e-03  2.4475739e-03  2.9674028e-03  7.2349585e-04
 -3.6324705e-03 -2.0763003e-03 -9.0555486e-04 -4.8923073e-03
  2.4569121e-03  2.7034292e-03 -9.4034703e-04 -5.1332361e-05
  3.5765632e-03  1.3697346e-03 -2.1170592e-03  2.4727438e-04
 -1.9364065e-03 -6.8788190e-04  2.6225131e-03 -4.2047985e-03
 -1.7229744e-03 -4.8788898e-03  2.7098134e-03 -4.4652150e-04
 -2.8475812e-03  1.0829174e-03 -1.3274085e-03 -2.3356841e-03
 -1.0470717e-03  2.9847166e-03  4.9856864e-04 -2.7741212e-03
  8.0063316e-04 -3.5209041e-03  2.4260061e-04 -1.0546814e-03
  1.5230323e-03  2.2265424e-03  7.1312487e-04  1.5910959e-04
 -5.3506071e-04 -4.1557760e-03  3.0899488e-03 -4.2419755e-03
  2.6035690e-04  2.8313776e-03  3.6424508e-03 -3.6422047e-04
 -4.5842007e-03  8.2056207e-04  3.9327252e-03  1.0889971e-03
 -4.3580285e-03  2.0537744e-03 -4.4477647e-03 -3.1018085e-03
 -4.6383361e-03  4.3541952e-03 -2.6576789e-04  4.4384478e-03
 -1.6556390e-03 -4.6257934e-04 -2.1263708e-03  2.3519332e-03]
```

The warning you posted is not relevant to the problem. If you upgrade gensim to the most recent version, the warning will go away.

Can you please confirm whether there is still a problem? If not, I will close this issue.

**Comment by marcalt94** [comment]
I had to zip the file since GitHub wouldn't let me upload it without zipping. When I run the same file I get this: 
![warn2](https://user-images.githubusercontent.com/44497700/62151442-9b657400-b300-11e9-948c-0d4208b730c7.PNG)

And then I can use the comand line as if I never started the script

**Comment by mpenkov** [comment]
> I had to zip the file since GitHub wouldn't let me upload it without zipping.

You can just copy-paste the source into the text of your messages. See:

https://help.github.com/en/articles/basic-writing-and-formatting-syntax

> And then I can use the comand line as if I never started the script

You seem to be misunderstanding how things are supposed to work. If you need help, please ask on the mailing list.

https://groups.google.com/forum/#!forum/gensim
