### ISSUE TITLE
Preprocessing Inexplicably Removes Term

### ISSUE THREAD

**Issue by JohnCoene** [RaRe-Technologies/gensim#2564]
Sorry if this has already been answered, I went through quite a few closed issues and documentation but can't find an answer: why is the term `computer` removed?

```python
from gensim.parsing.preprocessing import preprocess_string

preprocess_string("Human machine interface for lab abc computer applications")
#> [u'human', u'machin', u'interfac', u'lab', u'abc', u'applic']
```

**Comment by mpenkov** [comment]
Thank U for reporting  Interesting. It may be a bug. Are you able to step through with a debugger?

**Comment by piskvorky** [comment]
`computer` is in stopwords. That's the direct reason.

I'm not sure *why* it's in stopwords though. I think the list of stop words was copied from NLTK or some other authoritative source. I see many words that are common but not necessarily "stop": `computer`, `sixty`, `kg`, `serious` etc, and some downright bizarre ones: `amoungst`.

I'd advise against using the `preprocessing` module altogether. I've been meaning to get rid of it completely for a long time. Preprocessing is not the focus on Gensim, that module is too primitive for pragmatic use. There exist better, more focused packages for that (NLTK, spacy, pattern…).
