### ISSUE TITLE
make Travis check against earliest supported dependencies

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#257]
- SciPy==0.7.0
- NumPy==1.3

The goal is to avoid subtle errors such as the one in #256  (`scipy.sparse.rand` not available in scipy 0.7).

**Comment by menshikh-iv** [comment]
Not relevant for now.

**Comment by piskvorky** [comment]
@menshikh-iv what do you mean? Why is this not relevant?

**Comment by menshikh-iv** [comment]
@piskvorky because we already have minimal dependencies versions (with wheels for all python versions).
