### ISSUE TITLE
C extension not loaded, training will be slow. Install a C compiler and reinstall gensim for fast training.

### ISSUE THREAD

**Issue by Kashif571** [RaRe-Technologies/gensim#2572]
How to solve this User Warning Error in Windows 10. I am running code with Command Prompt and writing it in Notepad++. 

 C extension not loaded, training will be slow. Install a C compiler and reinstall gensim for fast training.

Kindly write such commands that can be executed in cmd.

**Comment by piskvorky** [comment]
Missing information -- we'll have to close unless you fill in the issue template fully.

**Comment by guo18306671737** [comment]
hi, have you solved this problem? I had the same problem ,thanks!

**Comment by guo18306671737** [comment]
@piskvorky in 2015,the solution to "C extension not loaded, training will be slow" was to use version 0.15 of scipy,but the python I'm using now is 3.7,and version 0.15 of scipy can no longer be used on python 3.7.How can I solve this problem now? Please give me some advice. Thanks
 
<img width="857" alt="image" src="https://user-images.githubusercontent.com/25073137/63221623-52e9f980-c1ce-11e9-8e68-7385f06e542b.png">
<img width="840" alt="image" src="https://user-images.githubusercontent.com/25073137/63221629-5f6e5200-c1ce-11e9-9594-43b293fff4ac.png">

**Comment by piskvorky** [comment]
Issue template not followed, information still missing.

 @guo18306671737 how did you install gensim? Did the installation process print any warnings or errors?

**Comment by guo18306671737** [comment]
@piskvorky thank you very much for your reply! I looked at #351 and #2508, I install genism by 'pip install gensim-3.8.0-cp37-cp37m-win_amd64.whl',and the installation procession was successful . I  installed C++,but it didn't seem to work.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/25073137/63223030-38ba1680-c1e2-11e9-87cc-0d833b70fdbb.png">
<img width="212" alt="image" src="https://user-images.githubusercontent.com/25073137/63223035-51c2c780-c1e2-11e9-96eb-7755c15c5e56.png">

**Comment by piskvorky** [comment]
Thanks, that helps. So you installed gensim with `pip` on Windows, but you're seeing a warning when you try to train word2vec.

Can you provide the rest of the information

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

**Comment by guo18306671737** [comment]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/25073137/63226647-e9d6a600-c20e-11e9-8ebb-04319548924b.png">

hi, this is my latest version of the information, and now it doesn't work. The previous version of scipy was 1.3.1,and it didn't work. I also tried  genism-cp36 and genism-cp38, Neither of them worked.

**Comment by piskvorky** [comment]
Thanks. @mpenkov @gojomo any idea why the compiled version would be failing like this?

**Comment by gojomo** [comment]
There was probably an error during pip-installation's attempt to build the DLL. But I'm just guessing; it's been almost a decade since I used Windows for any development. I suspect the default tools on Windows can't build everything on demand, using the default configs/sources, as easily as on the Unix/Linux-y distributions. 

For people who can't switch away from Windows, I think `conda`-based installations usually work, by pulling the right precompiled stuff from Windows-specific conda repositories

**Comment by piskvorky** [comment]
I don't think anything's being built on demand. We're distributing binary wheels.

**Comment by guo18306671737** [comment]
<img width="584" alt="image" src="https://user-images.githubusercontent.com/25073137/63233376-69da2b80-c262-11e9-9e5a-c33486fea752.png">

@gojomo Do you mean that conda installs genism like this ,and it still doesn't work.

**Comment by gojomo** [comment]
@piskvorky I thought Windows-wheels were a separate option a user had to choose somehow, and that a default `pip install gensim` still tried to build from sources. If `pip install gensim` is supposed to already install pre-compiled working wheels, then yes, that would appear to be broken and the expert on Windows-wheels should look into this report!

**Comment by gojomo** [comment]
@guo18306671737 Not sure what you mean by "still doesn't work". Is that all the output of the command? What code is then run and generates what message? (It's be helpful to show it all, and ideally as quoted text rather than screenshots.)

**Comment by piskvorky** [comment]
`pip install gensim` should install from a binary wheel, where available.

AFAIK we automatically build (and upload to PyPI) lots of wheels, for all combinations of {Linux, OSX, Windows} x {2.7, 2.5, 3.6, 3.7}. So @guo18306671737 should be convered too. @mpenkov can you confirm?

**Comment by gojomo** [comment]
@guo18306671737's "C extension not loaded" error message seems to come from an Anaconda-derived path. But the shown "successful" install is just a `pip install [PATH_TO_LOCAL_WHL]` – which might not be installing to the same environment as the error comes from. if using an Anaconda environment, using a conda-driven install may be clearer in its effects (even though `pip` might be expected to work if the conda-env is properly activated.)

**Comment by guo18306671737** [comment]
@gojomo  @piskvorky  It's amazing. I managed to install genism again through conda in anaconda, and I'm not sure which step worked, thanks very much!

**Comment by mpenkov** [comment]
Sounds like problem was solved, closing.

**Comment by alex-arkhipov** [comment]
Hello,
I have the same problem with my windows machine. I have also reinstalled gensim via "conda" and this message disappeared. However, I have found that conda installed gensim 3.4.0 which is way to old. Is thare any way to install genism 3.8.0 with C compiler enabled (via pip or conda - doesn't matter)?

**Comment by mpenkov** [comment]
@alex-arkhipov I think your problem is related to https://github.com/RaRe-Technologies/gensim/issues/2600

That's an entirely different issue.

**Comment by gmnabeel** [comment]
> @gojomo @piskvorky It's amazing. I managed to install genism again through conda in anaconda, and I'm not sure which step worked, thanks very much!

Can u help me out? Same issue

**Comment by piskvorky** [comment]
Open a new ticket, and fill it in fully: your Python version, operating system version, version of Gensim you're installing etc. Then we can help you.
