### ISSUE TITLE
Ldamallet Error ( returned non-zero exit status 1)

### ISSUE THREAD

**Issue by shashalislife** [RaRe-Technologies/gensim#2580]
#### Problem description

What are you trying to achieve? What is the expected result? What are you seeing instead?

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```
Hallo all, please help me with the followin problem. I have tried a lot without sucsses:

os.environ.update({'MALLET_HOME': "C:\\mallet-2.0.8\\"})
mallet_path = "C:\\mallet-2.0.8\\bin\\mallet" # update this path
ldamallet = gensim.models.wrappers.LdaMallet(mallet_path, corpus=corpus, num_topics=20, id2word=id2word)

subprocess.CalledProcessError: Command 'C:\mallet-2.0.8\bin\mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input C:\Users\LENOVO~1\AppData\Local\Temp\c53edf_corpus.txt --output C:\Users\LENOVO~1\AppData\Local\Temp\c53edf_corpus.mallet' returned non-zero exit status 1.

I have put the mallet packet in C, but it didnot work. 

Thank you!

**Comment by piskvorky** [comment]
Try forward slashes `/` in your paths. Python interprets `\` as a character escape.
