### ISSUE TITLE
ldamulticore.LdaMulticore ignoring passes Parameter

### ISSUE THREAD

**Issue by alemol** [RaRe-Technologies/gensim#2581]
#### Problem description

What are you trying to achieve? What is the expected result? What are you seeing instead?

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

**Comment by piskvorky** [comment]
Can you fill the template?

**Comment by alemol** [comment]
I am sorry, it was just an error in my code. I realized that the problem came from a config dictionary with many arguments and  the omission  of `passes=cfg['passes']`. 

```
    model = gensim.models.ldamulticore.LdaMulticore(corpus, id2word=dictionary,
        num_topics=cfg['num_topics'],
        iterations=cfg['iterations'],
        alpha=cfg['alpha'],
        eta=cfg['eta'],
        eval_every=cfg['eval_every'],
        )
```

The correction is to use `**dict` python notation so arguments are loaded implicitly.

```
    model = gensim.models.ldamulticore.LdaMulticore(corpus, id2word=dictionary, **cfg)
```
