### ISSUE TITLE
Is it possible to transform a negative weight given by LSI in to positive value weight respectively

### ISSUE THREAD

**Issue by gauravkoradiya** [RaRe-Technologies/gensim#2587]
#### Problem description

What are you trying to achieve? What is the expected result? What are you seeing instead?

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

**Comment by piskvorky** [comment]
Closing because failed to follow issue template instructions.
