### ISSUE TITLE
Pre-Trained Doc2Vec Models

### ISSUE THREAD

**Issue by JanaPitanga** [RaRe-Technologies/gensim#2596]
I am looking for a french pre-trained model for Doc2Vec. I found a lot of information about the non usability of Word2Vec models in Doc2Vec. I have a corpus of 10,000 little documents, but I think this number is too small to train a performing model? Does anyone have a suggestion for me? Thank you!

**Comment by piskvorky** [comment]
10,000 is alright, if the documents exhibit the type of co-occurrence patterns you're looking for.

Closing here, the mailing list is a better place for such questions.
