### ISSUE TITLE
Import error when loading model

### ISSUE THREAD

**Issue by Wats0ns** [RaRe-Technologies/gensim#2602]
#### Problem description

I'm trying to load a model I created from an other script with SaveLoad class. Everything worked fined when I last checked it, but since a few days I got an import error. I don't remember having changed anything specific to the model loading, so I'm not sure what's happening. Here is the error:
```python
WARNING:this function is deprecated, use smart_open.open instead
Traceback (most recent call last):
  File "bin/advisor.py", line 32, in <module>
    adv.start()
  File "./semantic/advisor.py", line 256, in start
    sentences, relevances = self.compare_sentences()
  File "./semantic/advisor.py", line 198, in compare_sentences
    model = sv.load('models/{id}.mdl'.format(id=self.corpus_id))
  File "/usr/local/lib/python3.5/dist-packages/gensim/utils.py", line 426, in load
    obj = unpickle(fname)
  File "/usr/local/lib/python3.5/dist-packages/gensim/utils.py", line 1384, in unpickle
    return _pickle.load(f, encoding='latin1')
ImportError: No module named 'numpy.random._pickle'
```

#### Steps/code/corpus to reproduce

Here is the code used to loading the model:
```python
sv = SaveLoad()
model = sv.load('models/{id}.mdl'.format(id=id)).
```
It's a Word2Vec model, nothing really 'exotic'. I tried loading the model in the python console with
```python
with open('./my_model.mdl', 'rb') as f:
     res = pickle.load(f)
```
And I get me the same error:
```python
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ImportError: No module named 'numpy.random._pickle'
```
So I think that the problem happens at the model creation more than at the model loading ?
However here is the code for model creation
```python
model = Word2Vec(window=CONTEXT_WINDOW_SIZE, workers=4, sg=0, seed=21, min_count=1, size=300,
                             batch_words=1000, hs=1, negative=0)
[training]
 model.save(my_path + '/../models/{id}.mdl'.format(id=corpus_id))
```
I could provide the pickle file but I'm not sure it's a good idea to provide it on the issue for security reasons, I guess it could seem fishy
#### Versions

```python
>>> import platform; print(platform.platform())
Linux-4.4.0-142-generic-x86_64-with-Ubuntu-16.04-xenial
>>> import sys; print("Python", sys.version)
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.16.3
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 0.19.1
>>> import gensim; print("gensim", gensim.__version__)
gensim 3.7.1
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 1
```
Don't hesitate to point at anything I could provide to help
Thanks a lot ;-)

**Comment by piskvorky** [comment]
Can you try loading using standard `Word2Vec.load()`?

See https://radimrehurek.com/gensim/models/word2vec.html#usage-examples

**Comment by Wats0ns** [comment]
Same error :/

**Comment by piskvorky** [comment]
Did you use a different machine to create the model?

According to [google](https://www.pythonanywhere.com/forums/topic/14613/), this could be some numpy version mismatch in your environment.

**Comment by Wats0ns** [comment]
Okay that was indeed the problem, thanks a lot

**Comment by piskvorky** [comment]
No problem.

**Comment by Rexmiao** [comment]
Same error.
"ModuleNotFoundError: No module named 'numpy.random._pickle'"

Original Code:  "loaded_kmeans = pickle.load(open(kmeans_filename, 'rb'))"

I tried import pickle and install by "conda install -c anaconda cloudpickle "

I got "*** picosat: out of memory in 'resize'"
