### ISSUE TITLE
bm25 score is not symmetrical

### ISSUE THREAD

**Issue by junfenglx** [RaRe-Technologies/gensim#2609]
I think bm25 score is not symmetrical, but the code now fill the graph weights assume it is.

https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/summarization/graph.py#L310

Hope the authors can fix it. And will it influence the summary performance?
Or if I'm wrong, please let me know.

Thanks!

The code:
```python
from gensim.summarization.bm25 import get_bm25_weights
corpus = [
      ["black", "cat", "white", "cat"],
      ["cat", "outer", "space"],
    ["wag", "dog"]
 ]
get_bm25_weights(corpus)
# outputs:
[[1.1237959024144617, 0.1824377227735681, 0],
 [0.11770175662810844, 1.1128701089187656, 0],
 [0, 0, 1.201942644155272]]
```

**Comment by piskvorky** [comment]
@Witiko can you please have a look?

**Comment by junfenglx** [comment]
And also use the bow format corpus has problem when calculates bm25 scores. Because the bm25 code doesn't handle the (word_id, count) format of token. It cause the wrong word frequency and wrong document(sentence) length.

See the entry code:
https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/summarization/summarizer.py#L194

https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/summarization/bm25.py#L95

**Comment by Witiko** [comment]
Where does gensim use BM25 scores to initialize edge weights?

You are correct that BM25 is asymmetric and that `gensim.summarization.graph` implements weighted undirected graph, not directed graph, i.e. it expects edge weights to be symmetric. However, I don't see where the two meet (please excuse my limited insight into summarization.)

**Comment by junfenglx** [comment]
@Witiko Hi，Thanks for reply.
The code entry is at here:
https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/summarization/summarizer.py#L98

**Comment by Witiko** [comment]
Thanks. That does seem wrong.

**Comment by mpenkov** [comment]
@Witiko I've assigned this to you, so we can keep track of things easier. Hope you don't mind. Please let me know if this was inappropriate.

**Comment by Witiko** [comment]
@mpenkov I don't mind. If we assume that the definition of [Barrios et al (2016, sec. 4.1)](https://arxiv.org/pdf/1602.03606.pdf#page=4) is correct, then Gensim must use a directed graph as the representation, not an undirected graph as it does now. The TextRank algorithm [(Mihalcea and Tarau 2004)](https://www.aclweb.org/anthology/W04-3252) is defined for both directed and undirected graphs, so this seems as a reasonable conclusion.

**Comment by Witiko** [comment]
@mpenkov I don't mind.

If we assume that the definition of [Barrios et al (2016, sec. 4.1)](https://arxiv.org/pdf/1602.03606.pdf#page=4) is correct, then we must use a directed graph for the representation, not an undirected graph as Gensim does now. The TextRank algorithm [(Mihalcea and Tarau 2004)](https://www.aclweb.org/anthology/W04-3252) is defined for both directed and undirected graphs, so this seems as a reasonable conclusion.

Nevertheless, I have little practical experience with summarization, so an input by someone more familiar with it (@fbarrios) would be appreciated.

**Comment by Witiko** [comment]
Since `summarization.bm25` has been removed from Gensim 4, this issue can be closed.
