### ISSUE TITLE
Get the 

### ISSUE THREAD

**Issue by gbosetti** [RaRe-Technologies/gensim#2614]
Hello! I think there is a problem with the params spec of the show_topics method in the docs https://radimrehurek.com/gensim/models/hdpmodel.html 

When you pass -1 you don't get any topic. And if you omit such a param, you always get the default number of events (20).

I choose the HdpModel since it is a model that does not require to know, a priori, the number of topics to detect. That's really cool and this is supposed to be the main contribution of Hdp. But this implementation doesn't allow me to profit from such benefit.

Best,

# SEE TEMPLATE BELOW

#### Problem description

What are you trying to achieve? What is the expected result? What are you seeing instead?

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

**Comment by mpenkov** [comment]
Can you please fill out the template for the ticket?

The information you provided is helpful, but it isn't really enough for us to do anything.
