### ISSUE TITLE
Can't reload similarity index shards

### ISSUE THREAD

**Issue by ericchansen** [RaRe-Technologies/gensim#2638]
#### Problem description

I can't reload a similarity index if the location of that index has changed. For example, let's say I create an index following the instructions described [here](https://radimrehurek.com/gensim/similarities/docsim.html#gensim.similarities.docsim.Similarity.save). If I move the shards to a different directory and then load them, they will not be callable as intended.

When we call `similarities.Similarity.load(<path here>)`, there are a few issues.

- `gensim.similarities.docsim.Similarity.output_prefix` is still the old location to where it was originally saved (not from where it was loaded).
- Each shard inside `gensim.similarities.docsim.Similarity.shards` has the attribute `dirname` as the old location where it was saved (not from the new directory where the shards reside).

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

I think you can do this with any similarity index. When I get more time, I'll try to create a small example from one of the included sample datasets.

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

Output

```
Linux-4.15.0-65-generic-x86_64-with-debian-buster-sid
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
NumPy 1.17.2
SciPy 1.3.1
gensim 3.8.0
FAST_VERSION 1
```

**Comment by piskvorky** [comment]
See my previous [reply to you on the mailing list](https://groups.google.com/forum/#!searchin/gensim/check_moved%7Csort:date/gensim/YM05nFgQlb8/0Ani-radDQAJ).

**Comment by ericchansen** [comment]
I apologize that I didn't see the reply on the mailing list. Thank you for pointing me in the right direction. I was able to make it work using roughly the code below.

```
index = similarities.Similarity.load(<new path to index>)
index.output_prefix = <new path to index>
index.check_moved()
```

I really appreciate your help!

**Comment by ericchansen** [comment]
This is definitely a good enough solution.

I _might_ propose having `index.load` automatically update `output_prefix` and run `check_moved`.

Just a thought that might make it easier for noobs like me. Either way, thank you very much for your assistance.

**Comment by piskvorky** [comment]
No problem.

I think we considered running `check_moved` automatically on `load`, but decided against it. Although now I cannot remember why :(

Can you check if there are any comments about this in the code? It sounds like a good idea to me, but I want to make sure we don't introduce regressions.
