### ISSUE TITLE
'>=' not supported between instances of 'str' and 'int' error

### ISSUE THREAD

**Issue by Angelavtc** [RaRe-Technologies/gensim#2641]
Hi! 
I have a the following error in my code that says:

'>=' not supported between instances of 'str' and 'int'

I have a dictionary with dataframes like the following:
`sells={'df1':'Dataframe','df2':'Dataframe','df3':'Dataframe','df4':'Dataframe'}`

While applying the following code the error appears for both codes, does anyone know what am I doing wrong?

`peak={k: df[df["Hour"].between(9, 20)] for k, df in sells.items()}`
`offpeak={k: df[(df["Hour"]< 9)| (df["Hour"] > 20)] for k, df in sells.items()}`

**Comment by piskvorky** [comment]
Sorry, report doesn't follow the mandatory issue template. Closing.
