### ISSUE TITLE
Can you add compute Loss feature (as seen in Word2Vec model) in the fasttext Implementation too. It will help us in sending a callback to monitor the loss at each epoch.

### ISSUE THREAD

**Issue by Abhishek-Rnjn** [RaRe-Technologies/gensim#2658]
I was trying to monitor the loss vs epoch for word2vec and fasttext. But wasn't able to do so for fasttext because of no implementation of compute loss function.

**Comment by gojomo** [comment]
This could be closed in favor of the broad set of related fixes contemplated in #2617.

**Comment by ginward** [comment]
> This could be closed in favor of the broad set of related fixes contemplated in #2617.

Please see #3228. It seems that this issue is not fully resolved.

**Comment by gojomo** [comment]
This issue is closed because a better discussion of the needed fixes is in #2617 - which remains open, because noone has been able to tackle these gaps.
