### ISSUE TITLE
BM25 Average IDF returns negative even with Epsilon correction

### ISSUE THREAD

**Issue by roodrallec** [RaRe-Technologies/gensim#2662]
#### Description

Currently the BM25 algorithm uses the correction formula described by [Barrios et al.](https://arxiv.org/pdf/1602.03606.pdf#page=4) when a calculated IDF is negative. However, this solution returns a negative value when the average IDF is also negative, creating an issue. Perhaps the IDF should be 0 when both the word's IDF and the average IDF is negative.  

#### Code to reproduce

```
>>> from gensim.summarization.bm25 import BM25
>>> corpus = [
    ['people', 'drink', 'bar'],
    ['bear', 'consume', 'drink']
]
>>> BM25(corpus).idf
{'people': 0.0, 'drink': -0.08047189562170502, 'bar': 0.0, 'bear': 0.0, 'consume': 0.0}

```

**Comment by mpenkov** [comment]
@fbarrios Ping

**Comment by Witiko** [comment]
Since `summarization.bm25` has been removed from Gensim 4, this issue can be closed.
