### ISSUE TITLE
No module named 'gensim.models.fasttext_bin'

### ISSUE THREAD

**Issue by TQuy** [RaRe-Technologies/gensim#2668]
[(https://radimrehurek.com/gensim/models/_fasttext_bin.html)](url)
I tried this to load bin file of facebook pretrained fasttext wordembedding, but it warns No module named 'gensim.models.fasttext_bin'.
I have installed gensim 3.8,1

**Comment by piskvorky** [comment]
Please fill in the issue template fully.

**Comment by TQuy** [comment]
I follow the instruction in https://radimrehurek.com/gensim/models/_fasttext_bin.html

> from gensim.test.utils import datapath
from gensim.models.fasttext_bin import load
with open(datapath('crime-and-punishment.bin'), 'rb') as fin:
    model = load(fin)
model.nwords

**Comment by piskvorky** [comment]
@mpenkov what is that doc file?

**Comment by mpenkov** [comment]
That's an internal module. Not sure why it's showing up in https://radimrehurek.com/gensim/apiref.html.

There's two things to do here:

- [ ] update the docstring in that module
- [ ] hide all internal modules from top-level API documentation

@TQuy What are you actually trying to do?

**Comment by TQuy** [comment]
I just try to figure out how to load the facebook pretrained word embeddinh without using all of my ram

**Comment by neoyipeng2018** [comment]
just had this same issue.

if u dir(gensim.models), you will see that it has been renamed `gensim.models._fasttext_bin`. this worked for me.
