### ISSUE TITLE
ModuleNotFoundError: No module named 'gensim.models.keyedvectors'

### ISSUE THREAD

**Issue by alimuham1** [RaRe-Technologies/gensim#2681]
I am running the code of DeepWalk Implementation. While running the code i got the following error.

from gensim.models.keyedvectors import KeyedVectors
ModuleNotFoundError: No module named 'gensim.models.keyedvectors'

**Comment by piskvorky** [comment]
Hi, please fill in the issue template fully.

**Comment by gojomo** [comment]
@alimuham1 Are you sure you have gensim installed in the same Python environment where you're triggering this error? (Does `import gensim` work?)

**Comment by gojomo** [comment]
In absence of reporter response, assuming user error.
