### ISSUE TITLE
Can I  get synonyms from Gensim word2vec model?

### ISSUE THREAD

**Issue by nh111** [RaRe-Technologies/gensim#2685]
Hi

with word2vec model, we are getting most similar words. can I get synonyms?
below are two queries: please clarify.
1) Is there a differentiation of related words vs synonyms from model?
2) can I change the word dimension, when I am trying to get the most similar words from model?

Thanks

**Comment by piskvorky** [comment]
Please follow the issue template (ticket not appropriate).
