### ISSUE TITLE
lda mallet random seed not working

### ISSUE THREAD

**Issue by carlodavid012** [RaRe-Technologies/gensim#2686]
#### Problem description

I tried to use random_seed on ldamallet but its not working

#### Code
```
mallet_path = 'mallet-2.0.8/mallet-2.0.8/bin/mallet' 
ldamallet = gensim.models.wrappers.LdaMallet(mallet_path, corpus=corpus, num_topics=25, id2word=id2word, random_seed = 0)
```

#### Output:

The model shows different output everytime i print out the topics

#### Versions:

Linux-4.15.0-70-generic-x86_64-with-debian-buster-sid
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0]
NumPy 1.15.1
SciPy 1.1.0
gensim 3.8.1
FAST_VERSION 1

**Comment by satmohap** [comment]
why this bug is closed ?  i still get the same error

**Comment by Tetlanesh** [comment]
I get the same error

**Comment by zkmetty** [comment]
random_seed zero is not a good choice. Use any positive integer.
