### ISSUE TITLE
Use linesentence to stream corpus from file

### ISSUE THREAD

**Issue by TQuy** [RaRe-Technologies/gensim#2694]
I have used gensim to train word embedding about 6 months ago. At that time, the code used to stream data works just fine, but now I used it again, I meet so many error, one of them from fasttext model using too much ram. I think the document have not been updated 

```
corpus_file = datapath('sample.txt')
model = FT_gensim(size=100)

# build the vocabulary
model.build_vocab(corpus_file=corpus_file)

# train the model
model.train(
    corpus_file=corpus_file, epochs=model.epochs,
    total_examples=model.corpus_count, total_words=model.corpus_total_words
)

print(model)
```

**Comment by piskvorky** [comment]
> I meet so many error, one of them from fasttext model using too much ram.

Can you post the **full** traceback please?

**Comment by TQuy** [comment]
> > I meet so many error, one of them from fasttext model using too much ram.
> 
> Can you post the **full tracebacks** for these many errors?
I just use the code in the document 
[https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/FastText_Tutorial.ipynb](url)
I have 16 gb ram and the model use it all

**Comment by piskvorky** [comment]
> I just use the code in the document
https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/FastText_Tutorial.ipynb

So you're running that exact tutorial (which uses a super tiny toy corpus) and it consumes >16GB RAM? That's really weird.

**Comment by TQuy** [comment]
Weird, I didn't meet the error when I ran the code again, but I the old code of mine 6 months ago used 
`corpus_file = datapath('sample.txt')`
but now I only need to use 
`corpus_file = 'sample.txt'`
Really sorry for troubling you
