### ISSUE TITLE
Documentation may have code error!

### ISSUE THREAD

**Issue by ChunyuPCY** [RaRe-Technologies/gensim#2699]
#### Problem description

[Similarity Queries](https://radimrehurek.com/gensim/auto_examples/core/run_similarity_queries.html#sphx-glr-auto-examples-core-run-similarity-queries-py)--Part--`Performing queries`
I think there is a code error. Document id error. Please see the code below.

### code

```python
sims = sorted(enumerate(sims), key=lambda item: -item[1])
for i, s in enumerate(sims):
    print(s, documents[i])  # s[0] is the document id, the 'i' is not.
```
corrected code should be
```python
sims = sorted(enumerate(sims), key=lambda item: -item[1])
for i, s in enumerate(sims):
    print(s, documents[s[0]])
```

**Comment by piskvorky** [comment]
The tutorial is correct – documents are identified by their position in the corpus, so in this case `i`.

**Comment by piskvorky** [comment]
Reopening because the code does look wonky.

@mpenkov I believe the code should be

```python
sims = sorted(enumerate(sims), key=lambda item: -item[1])
for doc_position, doc_score in sims:
    print(doc_score, documents[doc_position])
```

The second enumeration was too convoluted, and also wrong. WDYT?

**Comment by mpenkov** [comment]
I agree, I think the second enumeration is erroneous.

@ChunyuPCY May I interest you in making a PR? ;)

**Comment by piskvorky** [comment]
Another user bit by this: https://groups.google.com/forum/#!topic/gensim/31RBvOeKiq4

Can @ChunyuPCY can you open a PR?
