### ISSUE TITLE
Proposal: drop support for Python 3.5; add Python 3.8 to builds

### ISSUE THREAD

**Issue by gojomo** [RaRe-Technologies/gensim#2713]
I recommend the next major gensim release (4.x) also drop official Python 3.5 testing/support. Rationale:

* it's close to full end-of-life (under 10 months to 2020-09-13) – currently receiving only security fixes
* major Python-using cloud services (including Heroku, AWS Lambda, Google Cloud/Colab, etc) already only support Python 3.6+
* some useful features (like the variable annotations needed for dataclasses) only arrive in 3.6
* for most users, moving forward to 3.6.x+ isn't hard; those absolutely stuck on 3.5 can use an earlier gensim version, or try their luck in an unsupported configuration (some modules might still work in Python 3.5)

Meanwhile, Python 3.8 has been out a few months (with support at Heroku & AWS Lambda) and deserves added build/test support. So we could replace the 3.5 builds/test in our CI setup with a new 3.8 target.

**Comment by piskvorky** [comment]
+1: I've always been in favour of 3.6+, but was overruled previously in https://github.com/RaRe-Technologies/gensim/issues/2548.

The numbers also support it: 3.6 is the second most popular Python (after 2.7).

**Comment by gojomo** [comment]
PR #2714 drops 3.5 and adds 3.8, and strips out or updates a bunch of pinning or pre-installation-of-wheels-from-nonstandard-sources – that appeared possibly obsolete. 

It works pretty well at our CI/build services – except the 3.8-on-Appveyor (Windows) build. I've poked at it a little & think the problem is mainly outside our control and may self-resolve as Appveyor or other projects improve their 3.8 coverage. 

May need reconciliation with #2706's appveyor changes.

**Comment by menshikh-iv** [comment]
@piskvorky yes, you are right (according to https://www.jetbrains.com/research/python-developers-survey-2018/)
