### ISSUE TITLE
Mallet Gensim error. (Non-zero exit status 1)

### ISSUE THREAD

**Issue by zhaoyi1025** [RaRe-Technologies/gensim#2717]
Hi all,
please help me to solve the following error, i tried a lot to fix it but with no help. 

#### code

import os 
os.environ.update({'MALLET_HOME':r'C:new_mallet/'})
### 1.bulding LDA mallet model
mallet_path = 'C:\\new_mallet\\bin\\mallet' # update this path
ldamallet = gensim.models.wrappers.LdaMallet(mallet_path, corpus=corpus, num_topics=20, id2word=id2word)

#### error
CalledProcessError: Command 'C:\new_mallet\bin\mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input C:\Users\zhaoyi\AppData\Local\Temp\7a71ac_corpus.txt --output C:\Users\zhaoyi\AppData\Local\Temp\7a71ac_corpus.mallet' returned non-zero exit status 1.
#### log
ldamallet = gensim.models.wrappers.LdaMallet(mallet_path, corpus=corpus, num_topics=20, id2word=id2word)
Traceback (most recent call last):

  File "<ipython-input-45-6e0dbb876ee6>", line 1, in <module>
    ldamallet = gensim.models.wrappers.LdaMallet(mallet_path, corpus=corpus, num_topics=20, id2word=id2word)

  File "D:\anaconda\lib\site-packages\gensim\models\wrappers\ldamallet.py", line 131, in __init__
    self.train(corpus)

  File "D:\anaconda\lib\site-packages\gensim\models\wrappers\ldamallet.py", line 272, in train
    self.convert_input(corpus, infer=False)

  File "D:\anaconda\lib\site-packages\gensim\models\wrappers\ldamallet.py", line 261, in convert_input
    check_output(args=cmd, shell=True)

  File "D:\anaconda\lib\site-packages\gensim\utils.py", line 1918, in check_output
    raise error
#### Versions

Please provide the output of:

```python
platform:Windows-10-10.0.17134-SP0
sys:Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
numpy:NumPy 1.16.4
scipy:SciPy 1.2.1
gensim:gensim 3.8.1
FAST_VERSION:FAST_VERSION 1
```
Thanks a  lot

**Comment by piskvorky** [comment]
What happens when you call Mallet directly, without Gensim?

```bash
C:\new_mallet\bin\mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input C:\Users\zhaoyi\AppData\Local\Temp\7a71ac_corpus.txt --output C:\Users\zhaoyi\AppData\Local\Temp\7a71ac_corpus.mallet
```

**Comment by zhaoyi1025** [comment]
It maybe Mallet's error, thank u for your suggestion.

**Comment by mpenkov** [comment]
Doesn't sound like a gensim bug, closing.
