### ISSUE TITLE
how to implemente get_document_topics()

### ISSUE THREAD

**Issue by zhaoyi1025** [RaRe-Technologies/gensim#2723]
Hi all,
I use the method of AuthorTopicModel() build a model, then i want to get the topic of each document or the document belongs to which topic(assume that i have 10 topics) and the tutorial tell me that the method of get_document_topics() are not be implemented, so how to implemente it.

thanks in advance
yi zhao

**Comment by mpenkov** [comment]
Github tickets are for bug reports only. Please use the mailing list for questions.
