### ISSUE TITLE
C extension not loaded, training will be slow. Install a C compiler and reinstall gensim for fast training.

### ISSUE THREAD

**Issue by gmnabeel** [RaRe-Technologies/gensim#2726]
Im trying to run naive-bayes.py from the following file(https://github.com/rockash/Fake-news-Detection) but i get the error mentioned in the title, i have tried uninstalling gensim and reinstalling it again using both pip and conda but nothing seems to work.i also have mingw installed and have added /bin to path as the warning suggests but it doesnt work either.I'm using windows 10 64 bit
![Screenshot (2)](https://user-images.githubusercontent.com/36754286/72397510-21b62b00-3766-11ea-913b-6a283d85fff3.png)

**Comment by piskvorky** [comment]
Please fill in the issue template fully, or we'll have to close this.

**Comment by piskvorky** [comment]
Can you show the console output from when you installed Gensim? Did your installation use the binary Windows wheel?

**Comment by gmnabeel** [comment]
I'm sorry this is my first issue that i have raised, what more details do you need?

Problem : The gensim is showing c extension not loaded.
But i have installed all necessary packages and mingw is also installed and the versions are above in the picture

**Comment by gmnabeel** [comment]
> Can you show the console output from when you installed Gensim? Did your installation use the binary Windows wheel?

Yes i used pip install gensim and conda install gensim later on after uninstalling pip version

**Comment by gojomo** [comment]
Your console output shows you are using Python 3.8; gensim build/testing for that Python version isn't yet working on your (Appveyor-based) Windows test environment, for unknown reasons, so the same thing is probably affecting you. 

Until that's fixed, you should have better luck with Python 3.7. 

Personally I'd suggest for Windows users:

- using a `conda`-based installation, and specifically creating an environment based on Python 3.7. (I prefer to install just what's needed via the miniconda approach.) For example, create your working environment with `conda create --name my_working_environment python=3.7`, then activate it in the usual way.  
- installing major packages that the conda team keeps up-to-date via `conda install PKGNAME` - such as `numpy`, `scipy`, `sklearn`, etc
- installing gensim into that same environment using `pip install gensim` - as the conda repository's version often lags

**Comment by gojomo** [comment]
(Specifically the Python 3.8 Appveyor failure is described in , and visible in the CI links from, this PR/PR-comment: <https://github.com/RaRe-Technologies/gensim/pull/2715#issuecomment-569457589>. I suspect it's actually a problem with one of the packaging, build, or prerequisite libraries we depend on not yet being 3.8-ready, and so may resolve itself in time as more of the Python world fully tests with Python 3.8 on Windows. In the meantime we may want to add an official note that gensim-on-Python-3.8-on-Windows is not yet an officially recommended/supported combination.)

**Comment by gojomo** [comment]
Closing assuming recommendation to use Python 3.7 on WIndows worked.
