### ISSUE TITLE
[QUESTION] Update LDA model

### ISSUE THREAD

**Issue by loretoparisi** [RaRe-Technologies/gensim#2728]
## Problem description
Update an existing LDA model with an incremental approach. We create a LDA model for a collection of documents on demand basis. We save the resulting model file on the cloud. When a new LDA request arrives with fresh data, I need a way to incrementally update the model (live training) wit the these data. Typically I would use `lda.update()`. But what happens when the `lda.update()` takes as input a corpus that includes the same documents of the previous model?

Assumed to have `model1` trained on `corpus1` and a new `corpus2`, which is the best approach to do the incremental training of the new `model2` against `corpus2`?

I have seen a `lda.diff` function. So one could train `model2` and then run `mdiff, annotation = model1.diff(model2)`, then check `diff` and `annotation` and decide to promote `model2`. Does it make sense? Which is the best criterion to promote the new model then?

Thank you in advance!

#### Steps/code/corpus to reproduce

```python
from smart_open import open

# load the existing LDA model
current_model = LdaModel.load(open(s3_model_path))

# load the corpus
data = TextCorpus( open(s3_corpus_path) )
corpus_sentences = data.get_texts()
dictionary = Dictionary(corpus_sentences)
corpus = [dictionary.doc2bow(text) for text in corpus_sentences]

# update current model on the corpus
current_model.update(corpus)
```

#### Versions
```
Linux-5.0.0-36-generic-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
NumPy 1.17.4
SciPy 1.0.0
gensim 3.8.1
FAST_VERSION 1
```

**Comment by mpenkov** [comment]
As explained in the issue template, please ask such questions on the [mailing list](https://groups.google.com/forum/#!forum/gensim). Github issues are for bug reports only.
