### ISSUE TITLE
Pickle issue with LdaMulticore

### ISSUE THREAD

**Issue by cwharland** [RaRe-Technologies/gensim#273]
I'm trying to use LdaMulticore to speed up model training and I'm running into a pickle error:

```
PicklingError: Can't pickle <function worker_e_step at 0x0000000036D26748>: it's not found as gensim.models.ldamulticore.worker_e_step
```

The error occurs when running:

```
lda = gensim.models.ldamulticore.LdaMulticore(corpus=corpus, id2word=dictionary, num_topics=10)
```

Single threaded works just fine with no error:

```
lda = gensim.models.ldamodel.LdaModel(corpus=corpus, id2word=dictionary, num_topics=10)
```

I'm running this on Windows with gensim 0.10.3.  Haven't tried on another platform so can't rule out platform problem.  I can pickle other things just find so I don't think my pickle library is messed up.  It looks like this is some kind of serialization issue possibly related to [this](http://matthewrocklin.com/blog/work/2013/12/05/Parallelism-and-Serialization/) post on pickle vs. dill

**Comment by maifeng** [comment]
Got the same error on Windows.

**Comment by az0** [comment]
I also have the same error on Windows 7 and Python 2.7.9 64-bit

**Comment by piskvorky** [comment]
Can you guys move the inner `worker_e_step` function in `ldamulticore.py` (or any other function that fails on Windows) into module scope, and open a pull request?

**Comment by maifeng** [comment]
I just tested the suggestion under Windows and it is working now. I also opened a pull request.

**Comment by piskvorky** [comment]
I've merged @maifeng 's fix.

@az0 @cwharland can you test, using the `develop` branch?

**Comment by cwharland** [comment]
Sorry for the late response but it worked for me too from develop branch
