### ISSUE TITLE
remove_stopwords doesn't remove capitalized stopwords

### ISSUE THREAD

**Issue by ab-10** [RaRe-Technologies/gensim#2740]
### Problem description

I'm trying to remove stopwords from sentences and I've noticed that capitalized stopwords do not get removed from the sentence using `gensim.parsing.preprocessing.remove_stopwords`.

#### Steps/code/corpus to reproduce

```
from gensim.parsing.preprocessing import remove_stopwords
remove_stopwords("My dog ate my homework.")
actual output:
>>> 'My dog ate homework.'
expected output:
>>> 'dog ate homework.'
```

#### Versions

Linux-4.14.137+-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
NumPy 1.17.5
SciPy 1.4.1
gensim 3.6.0
FAST_VERSION 1

**Comment by piskvorky** [comment]
`remove_stopwords` is not meant to be used in isolation; use the [other filters](https://github.com/RaRe-Technologies/gensim/blob/eef4cbadb45808567091d6e30e7330f1cc6ba260/gensim/parsing/preprocessing.py#L330) to do lowercasing and other transformations.

As mentioned in https://github.com/RaRe-Technologies/gensim/pull/2741#issuecomment-580421091, this whole `preprocessing.py` module is deprecated. We'll be removing it soon, not extending it.

**Comment by ab-10** [comment]
Makes sense, thanks for the prompt response.
