### ISSUE TITLE
Rackspace account discontinued 

### ISSUE THREAD

**Issue by ogrisel** [RaRe-Technologies/gensim#2747]
https://github.com/MacPython/gensim-wheels is using the rackspace account for the release process and on top of that some gensim maintainers have dedicated gensim containers on our shared rackspace cloud storage infrastructure.

However the free hosting offer for open source projects has ended:

More details: https://mail.python.org/pipermail/scipy-dev/2020-February/023990.html

So we need to move on to something else. Please delete the files you own and no longer need in the rackspace admin interface and let's join on https://github.com/matthew-brett/multibuild/issues/304 to discuss how to setup a new release infrastructure.

**Comment by mpenkov** [comment]
Ok, I will deal with the gensim files tomorrow

**Comment by ogrisel** [comment]
Thanks.

**Comment by mpenkov** [comment]
@piskvorky I think we can safely delete all those old wheels. We don't need them anymore, because those releases have been made, and are available via PyPI. @menshikh-iv agrees that it's safe to delete them.

Shall I proceed? Or would you like a backup of these things somewhere?

**Comment by piskvorky** [comment]
I have no idea what these files are, or why they're there. Can I leave this with you?

**Comment by mpenkov** [comment]
Sure.

**Comment by mpenkov** [comment]
@ogrisel I deleted gensim-wheels and gensim-windows-wheels containers, please let me know if I need to do anything further.

**Comment by ogrisel** [comment]
Thank you very much. I am current configuring a replacement container using anaconda.org for nightly builds for the scipy ecosystem. I will first configure it for scikit-learn and once it works I will let you know about the details.

**Comment by ogrisel** [comment]
If you want to use anaconda for release staging, you can update end of your scripts to upload to anaconda.org instead of rackspace. Here is the configuration I used for scikit-learn (using Azure Pipelines instead of travis and appveyor):

https://github.com/MacPython/scikit-learn-wheels/blob/c0f96681684657dc94a7c0db1d7a93b7435408f4/azure/windows.yml#L111-L148

The important line is:

```bash
 anaconda -t $TOKEN upload --force -u $ANACONDA_ORG wheelhouse/*.whl
```

the resulting wheels will be available at:

    https://pypi.anaconda.org/$ANACONDA_ORG/simple

You can create your own anaconda organization for staging gensim wheels (e.g. `gensim-wheels-staging`) and create a token in the Settings / Access menu (URL should be: https://anaconda.org/gensim-wheels-staging/settings/access). You will need the following 2 permissions:

- "Allow write access to the API site"
- "Allow uploads to PyPI repositories"

If you want to also push your nightly build wheels to the shared `scipy-wheels-nightly` organization, please give me the identifier of your anaconda account and I can grant you some permissions or generate a token for you.

**Comment by ogrisel** [comment]
If you do not have conda already installed, you can use pip to install the `anaconda-client` that provides the upload command line interface. However the version on PyPI is too old. You should rather install it from the github tag instead:

```
pip install -q git+https://github.com/Anaconda-Platform/anaconda-client@1.7.2
```

**Comment by mpenkov** [comment]
Ok, thank you. I'm a little busy with other stuff right now, but will look into this later.

**Comment by mpenkov** [comment]
@ogrisel We ended up using S3 for staging our wheels. I'm closing this issue as there is nothing else left to do.

@piskvorky Tagging you just FYI.
