### ISSUE TITLE
 CalledProcessError: returned non-zero exit status 127

### ISSUE THREAD

**Issue by avissens** [RaRe-Technologies/gensim#2748]
####

I saw similar issues reported before and tried different suggestions but still get the CalledProcessError. 

#### Steps/code/corpus to reproduce
My code:

```
mallet_path = 'Users/av/DS/mallet-2.0.8/bin/mallet'
ldamallet_model = gensim.models.wrappers.LdaMallet(mallet_path, corpus=corpus, num_topics=40, id2word=dictionary)

```
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-77-9a6d0211c7fd> in <module>
      1 mallet_path = 'Users/av/DS/mallet-2.0.8/bin/mallet'
----> 2 ldamallet_model = gensim.models.wrappers.LdaMallet(mallet_path, corpus=corpus, num_topics=40, id2word=dictionary)

/Applications/anaconda3/lib/python3.7/site-packages/gensim/models/wrappers/ldamallet.py in __init__(self, mallet_path, corpus, num_topics, alpha, id2word, workers, prefix, optimize_interval, iterations, topic_threshold, random_seed)
    129         self.random_seed = random_seed
    130         if corpus is not None:
--> 131             self.train(corpus)
    132 
    133     def finferencer(self):

/Applications/anaconda3/lib/python3.7/site-packages/gensim/models/wrappers/ldamallet.py in train(self, corpus)
    270 
    271         """
--> 272         self.convert_input(corpus, infer=False)
    273         cmd = self.mallet_path + ' train-topics --input %s --num-topics %s  --alpha %s --optimize-interval %s '\
    274             '--num-threads %s --output-state %s --output-doc-topics %s --output-topic-keys %s '\

/Applications/anaconda3/lib/python3.7/site-packages/gensim/models/wrappers/ldamallet.py in convert_input(self, corpus, infer, serialize_corpus)
    259             cmd = cmd % (self.fcorpustxt(), self.fcorpusmallet())
    260         logger.info("converting temporary corpus to MALLET format with %s", cmd)
--> 261         check_output(args=cmd, shell=True)
    262 
    263     def train(self, corpus):

/Applications/anaconda3/lib/python3.7/site-packages/gensim/utils.py in check_output(stdout, *popenargs, **kwargs)
   1916             error = subprocess.CalledProcessError(retcode, cmd)
   1917             error.output = output
-> 1918             raise error
   1919         return output
   1920     except KeyboardInterrupt:

CalledProcessError: Command 'Users/avs/DS/mallet-2.0.8/bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input /var/folders/pp/mw9ffc953kq3wx770qqwrm2httlj5s/T/3c2a5c_corpus.txt --output /var/folders/pp/mw9ffc953kq3wx770qqwrm2httlj5s/T/3c2a5c_corpus.mallet' returned non-zero exit status 127.

#### Versions

Please provide the output of:

```
Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.17.2
SciPy 1.3.1
gensim 3.8.1
FAST_VERSION 1
```

**Comment by gojomo** [comment]
Some of your paths (starting `/Applications/...`) & output (`Darwin`) suggest you're on MacOS, while other paths, beginning `C:\`, appear to be Windows-based. Are you sure that `C:\`-path is a valid path to a `mallet` executable that works on your actual system?

**Comment by avissens** [comment]
I copied the wrong part when I was trying different way of solving the problem. I updated the code I use on my Mac. The same error. It used to work ok previously, so I'm not sure what is wrong now.

**Comment by avissens** [comment]
Oh, ok, my bad - I was missing / before the path. All works now.

**Comment by marziehoghbaie** [comment]
Hi, I had the same problem but I solved it by installing Java and setting the java_home path same as [https://vitux.com/how-to-setup-java_home-path-in-ubuntu/](url).
