### ISSUE TITLE
"Pattern library is not installed" -- this still is a problem

### ISSUE THREAD

**Issue by rtalexander** [RaRe-Technologies/gensim#2756]
#### Problem description
I am having the same problem that was reported in issue #2534, which has subsequently been closed. I am attempting to literally do the same exact thing that the author of  that was doing:

> I am trying to do a gensim tutorial project. I am attempting to lemmatize and getting this error:
ImportError: Pattern library is not installed. Pattern library is needed in order to use lemmatize function.

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

The following is from the [Topic Modeling for Fun and Profit](https://github.com/piskvorky/topic_modeling_tutorial) tutorial:

```python
import numpy
import scipy
import gensim
    
gensim.utils.lemmatize("The quick brown fox jumps over the lazy dog!")
--------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ipython-input-5-23224c08425f> in <module>
1 import gensim
----> 2 gensim.utils.lemmatize("The quick brown fox jumps over the lazy dog!")
    
anaconda3/lib/python3.7/site-packages/gensim/utils.py in lemmatize(content, allowed_tags, light, stopwords, min_length, max_length)
1676     if not has_pattern():
1677         raise ImportError(
-> 1678             "Pattern library is not installed. Pattern library is needed in order to use lemmatize function"
1679         )
1680     from pattern.en import parse
    
ImportError: Pattern library is not installed. Pattern library is needed in order to use lemmatize function
```

#### Versions

Please provide the output of:

```python
>>>import platform; print(platform.platform())
Darwin-17.7.0-x86_64-i386-64bit

>>> import sys; print("Python", sys.version)
Python 3.7.4 (default, Aug 13 2019, 15:17:50)
[Clang 4.0.1 (tags/RELEASE_401/final)]

>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.17.2

>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.3.1

>>> import gensim; print("gensim", gensim.__version__)
gensim 3.8.0

>>> pattern3.__version__
'2.6'

>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 1
```

**Comment by piskvorky** [comment]
CC @Hiyorimi is this expected?

**Comment by rtalexander** [comment]
Is anybody going to look at this??

**Comment by piskvorky** [comment]
@rtalexander Maybe you?

**Comment by stephantul** [comment]
Hi @rtalexander,

I don't think this requires a fix. you can just `pip install pattern` and it will work. `pattern` has been fully migrated to python `3.x`, so AFAIK there is no need to use the `pattern3` package, which is what is causing the problem in the first place. So this is actually not a gensim issue 😅

**Comment by piskvorky** [comment]
@rtalexander what pattern library did you install? What version?

**Comment by Uttam580** [comment]
@rtalexander is this issue fixed. i got same error

**Comment by JishnuJayaraj** [comment]
it is still existing for me, pip freeze give pattern3 3.0.0

**Comment by piskvorky** [comment]
Try the recommendation above: https://github.com/RaRe-Technologies/gensim/issues/2756#issuecomment-606697350

Beyond that, we'll be removing `pattern` from `gensim` completely in future versions. So there'll be no additional support.
