### ISSUE TITLE
DeprecationWarning: Calling np.sum(generator) is deprecated - LDA. (2020-Feb)

### ISSUE THREAD

**Issue by shishir13** [RaRe-Technologies/gensim#2759]
#### Problem description

I am trying to extrac topics from from a dataset using LDA.

#### Steps/code/corpus to reproduce

```
LDA = gensim.models.ldamodel.LdaModel

# Build LDA model
#lda_model = LDA(corpus=doc_term_matrix, id2word=dictionary, num_topics=10, random_state=100,chunksize=1000, passes=50)

lda_model =  LDA(corpus=doc_term_matrix, id2word=dictionary, num_topics=10, chunksize=1000, passes=50)
```
#### Versions

version output :

```python
Linux-4.14.137+-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
NumPy 1.17.5
SciPy 1.4.1
gensim 3.6.0
FAST_VERSION 1
```

#### Error Message

`DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead. score += np.sum(cnt * logsumexp(Elogthetad + Elogbeta[:, int(id)]) for id, cnt in doc`

**Comment by piskvorky** [comment]
Why do you use such old version of Gensim? AFAIK this warning was already fixed some time ago.

**Comment by shishir13** [comment]
This is the default version in colab. I updated it using `pip install -U gensim'. It is showing version 3.8, hopefully, should work fine. I will update in some time.

**Comment by shishir13** [comment]
This is resolved. Updated gensim to the latest version 3.8. Thanks @piskvorky
