### ISSUE TITLE
Proper tokenizers for pretrained word embeddings models?

### ISSUE THREAD

**Issue by IvanLazarevsky** [RaRe-Technologies/gensim#2760]
#### Problem description

I wan't to tokenize the text the same way it was tokenized when the model was trained. For example, google-news word2vec has separate vectors for common phrases, like San Francisco. It is also not clear which tokenizer to use for other models, like, how to handle apostrophes in words like "shouldn't".

Is there any general way to do so?

**Comment by piskvorky** [comment]
Please use the mailing list for questions – github is for bug reports (see the issue template you deteleted).
