### ISSUE TITLE
AttributeError: 'MmCorpus' object has no attribute 'get_texts'

### ISSUE THREAD

**Issue by joanPlepi** [RaRe-Technologies/gensim#2768]
#### When loading wiki corpus cannot use get_texts method.
I have serialized a wiki corpus after processed with the following method:

`MmCorpus.serialize('deWikiProcessed.gensim', wiki)
`
However when I load it and try to use get_texts attribute I get an error. 

```python
wiki = MmCorpus('deWikiProcessed.gensim')
wiki.metadata = True
for content, (page_id, title) in wiki.get_texts():
         pass
```

I need to load the wiki in order to train a new doc2vec model. I use the .get_text() method to get the articles again.
Is there any way I can retrieve the method get_texts, or I just need to reprocess the wiki corpus again and not use MmCorpus format? I was hoping there was a way to convert MmCorpus to WikiCorpus object in order to get the .get_texts() method

#### Versions

```python
Linux-5.0.7-kd-cluster-x86_64-with-debian-9.12
Python 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0]
NumPy 1.17.3
SciPy 1.4.1
gensim 3.8.0
FAST_VERSION 0
```

**Comment by piskvorky** [comment]
Sorry, there's no way to convert `MmCorpus` (a matrix of numbers) back into a `WikiCorpus` (stream of wikipedia articles). The two are different things.
