### ISSUE TITLE
Topic coherence

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#278]
The AKSW group of Michael Röder did a nice comparison of various methods for evaluating topic coherence:  http://svn.aksw.org/papers/2015/WSDM_Topic_Evaluation/public.pdf

They also released an implementation (Java) and a live web demo: http://palmetto.aksw.org/palmetto-webapp/

Release note here: https://groups.google.com/forum/#!topic/gensim/z925_KI8hGs

Check what method is the "best" and implement it in gensim.

**Comment by christofs** [comment]
+1

**Comment by tmylk** [comment]
FYI: UMass coherence implemented in #311 . Implementation of the best method from Roder can build on top of that.

**Comment by dsquareindia** [comment]
Can this be closed?

**Comment by dsquareindia** [comment]
ping @tmylk
