### ISSUE TITLE
failed to load projection (LSA model)

### ISSUE THREAD

**Issue by Evarln** [RaRe-Technologies/gensim#2781]
Hi,
I have a problem with gensim (0.13.3) on python 2.7: when I want to load a LSA model, I receive an error message saying that we cannot find a file named projection. The message is as follows: WARNING:root:failed to load projection from .../LSA/lsaModel.npy.projection: [Errno 2] No such file or directory: '.../LSA/lsaModel.npy.projection' Anyone have a solution?
For informations:
-python 2.7
- gensim 0.13.3
- scipy (0.18.1)
- scikit-learn (0.17.1)
- numpy (1.16.6)

**Comment by piskvorky** [comment]
Looks like you're missing a file. The file was created when you stored the LSA model, and you need the file to load that model back.

**Comment by Evarln** [comment]
> Looks like you're missing a file. The file was created when you stored the LSA model, and you need that file to load the model back.

Yes, I understand this problem. But why don't I have this file? Is it because the model was not correctly stored?  Yet I do have the file "LsaModel.npy" ...

**Comment by piskvorky** [comment]
Yes, possibly. Did you store it yourself? To the same location? Or did you somehow copy the files from elsewhere?

Btw Gensim 0.13.3 is really old, why do you use it?

**Comment by isakruas** [comment]
Hi [piskvorky](https://github.com/piskvorky),

I hope you're doing well. I'm encountering the same issue when trying to load the models from an S3 bucket. Have you ever faced similar problems?

```
numpy==1.26.1
pandas==2.1.2
gensim==4.3.3
scipy==1.10.1
```
