### ISSUE TITLE
gensim/utils.py is referencing the old boto package

### ISSUE THREAD

**Issue by andreamoro** [RaRe-Technologies/gensim#2784]
#2250 ## Problem description

I'm installing gensim on a new computer. I noticed the installation log to have imported boto3 and boto

```
Collecting boto3
  Downloading boto3-1.12.36-py2.py3-none-any.whl (128 kB)
Collecting boto>=2.32
  Using cached boto-2.49.0-py2.py3-none-any.whl (1.4 MB)
```
but on the first run I got the ModuleNotFoundError error

#### Steps/code/corpus to reproduce

```
import sys
!{sys.executable} -m pip install gensim

from gensim import corpora
```

#### Versions

Please provide the output of:

Darwin-19.4.0-x86_64-i386-64bit
Python 3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]
NumPy 1.18.1
SciPy 1.4.1
gensim 3.8.1
FAST_VERSION 0

**Comment by piskvorky** [comment]
Can you provide a full stacktrace? Which module fails to import, exactly, and why do you think it's related to `boto`?

Possibly duplicate to #2779 . @mpenkov if so, we'll have to make a bugfix release ASAP (priority).

**Comment by andreamoro** [comment]
Can't reproduce anymore :( 
The module seems installed now
