### ISSUE TITLE
metrics.precision_score and the not supported zero_division 

### ISSUE THREAD

**Issue by andreamoro** [RaRe-Technologies/gensim#2785]
#### Problem description

If I try to use the zero_division argument to ignore the errors I get the `unexpected keyword argument 'zero_division' ` error message

#### Steps/code/corpus to reproduce

metrics.precision_score(y, y_pred, average="weighted", zero_division='warn')
```

print(len(y))
>>> 608

print(len(y_pred))
>>> 608
```

#### Versions

Please provide the output of:
Darwin-19.4.0-x86_64-i386-64bit
Python 3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]
NumPy 1.18.1
SciPy 1.4.1
gensim 3.8.1
FAST_VERSION 0

**Comment by piskvorky** [comment]
Your steps to reproduce are not complete / reproducible. This seems unrelated to gensim.

**Comment by andreamoro** [comment]
My bad, wrong place.
