### ISSUE TITLE
Do test instructions still work?

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#2788]
In our [README](https://github.com/RaRe-Technologies/gensim#installation), we tell users to run `python setup.py test`.

One user [reported on our mailing list](https://groups.google.com/forum/#!topic/gensim/JfeV2phNTjk) that this doesn't actually work.

We should fix the docs or the tests – whichever is at fault here.

**Comment by piskvorky** [comment]
@mpenkov apparently Gensim requires 3.5+ already:
https://github.com/RaRe-Technologies/gensim/blob/develop/setup.py#L23

That means we shouldn't work off `develop` for 3.8.3. Which branch should I use?

**Comment by piskvorky** [comment]
Worse: does 3.8.2 have the same problem too? I don't see any py2.7 wheels on PyPI:
https://github.com/RaRe-Technologies/gensim/blob/develop/setup.py#L23

**Comment by piskvorky** [comment]
I tracked the problem down to this commit: https://github.com/RaRe-Technologies/gensim/commit/e859c11f6f57bf3c883a718a9ab7067ac0c2d4cf (part of PR https://github.com/RaRe-Technologies/gensim/pull/2630, merged 6 months ago). It claims to remove native Python implementations, but also silently drops support for Python2.

@mpenkov I'm not sure how to proceed, so I'll pause work on 3.8.3. Silently dropping Python2 support is terrible, we cannot do that.

**Comment by mpenkov** [comment]
Created #2811 to deal with the Py2 issue.

**Comment by mpenkov** [comment]
> @mpenkov I'm not sure how to proceed, so I'll pause work on 3.8.3.

@piskvorky We've successfully patched our develop HEAD to work on Py2 (https://github.com/RaRe-Technologies/gensim/pull/2812), so please proceed as previously discussed.

**Comment by piskvorky** [comment]
Great, will do. Thanks @mpenkov @menshikh-iv

**Comment by piskvorky** [comment]
> We've successfully patched our develop HEAD

@mpenkov I don't see that in `develop`. Should I work off the `release-3.8.3` branch?

**Comment by mpenkov** [comment]
Because the changes for Py2.7 are essentially only 3.8.3, we won't be merging them into develop (there is no point, because we'd be removing them as soon as we ditch Py2.7).

Please work off `develop`. We will merge that into 3.8.3 before the actual release (as opposed to the other way around).

**Comment by menshikh-iv** [comment]
btw about original topic: `python setup.py test` no relevant for last years, should be `tox -e py<version>-<os>`, like `tox -e py37-linux`
