### ISSUE TITLE
how to do Incremental training on an existing doc2vec model?

### ISSUE THREAD

**Issue by GD-Susan** [RaRe-Technologies/gensim#2807]
hi,

I am an newer in deep learning. I tried to train a doc2vec model for about 1000docs, but when I get another new 1000 docs, I don't know how to do the incremental training in which I can get the exact vector of the new docs, not by using "infer_vector".

Please help me ,thanks very much!

**Comment by piskvorky** [comment]
Hi, please follow the issue template you deleted – such questions belong on the mailing list, not here.
