### ISSUE TITLE
Investigate Py2.7 support

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#2811]
[This PR](https://github.com/RaRe-Technologies/gensim/pull/2630) silently removed Py2.7 support as a side-effect. There is no mention of it in the PR description, commit messages or discussion with the reviewers.

I'm the one who made the change, but it was several months ago, and I myself don't remember what the original intention was.

We need Python 2.7 support for the 3.8.3 release, because a significant number of users (not sure how many) still use that version of Python.

- [x] Get gensim building on Py2.7 again. Try working of the current develop branch, if not, consider alternatives.
- [x] Start a new branch to bring back Py2.7 builds in the gensim-wheels repo (see https://github.com/MacPython/gensim-wheels/pull/24).

**Comment by piskvorky** [comment]
My 2 cents: we don't need the whole automated machinery for 3.8.3. Further development will happen in the 4.0 branch without py2 anyway.

We just need to get py2 working, test it, and release it (once), for legacy users. And keep that branch around for potential critical bugfixes in the future (3.8.4…). But no need to introduce complex automation headaches for ourselves.

**Comment by mpenkov** [comment]
This is done, closing.
