### ISSUE TITLE
Set up Azure pipelines for gensim

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#2819]
@piskvorky basic config is ready https://github.com/menshikh-iv/gensim/pull/2, waiting when you activate `azure` for gensim (please make sure than pipeline runs in separate PR, after that I'll continue)

_Originally posted by @menshikh-iv in https://github.com/RaRe-Technologies/gensim/pull/2814#issuecomment-621950805_

**Comment by piskvorky** [comment]
I tried setting up Azure Pipelines and got as far as here:

![Screenshot (2)](https://user-images.githubusercontent.com/610412/80923406-e7f44900-8d83-11ea-9f76-91ed00e5fcd5.png)

Do I understand correctly the app wants read-write access to all repos, including private ones? If so, that's a show stopper.

**Comment by piskvorky** [comment]
I think I figured it out. Instead of logging in to Azure Pipelines and then creating a Pipeline from there (= OAuth above = no go), I went to the Github marketplace and installed Azure Pipeline from there.

That allowed me to select which Github repositories I want. I selected all our open source repos.

**Comment by menshikh-iv** [comment]
@piskvorky azure pipelines aren't really active, see https://github.com/RaRe-Technologies/gensim/pull/2823 (no azure job spawned)

by `please make sure than pipeline runs in separate PR, after that I'll continue` I mean that you test it first (run any random build from gensim repository), so, please, fix that and make sure than my PR trigger azure build, after I'll continue.

**Comment by piskvorky** [comment]
If I understand correctly you want me to:

1. create a new github branch and add that azure `yml` file to it
2. create a new azure pipeline at https://dev.azure.com/rare-technologies/gensim-ci by selecting that github branch
3. ?do something about your PR?

**Comment by menshikh-iv** [comment]
I want that you make my PR trigger azure pipeline (no need to create new one, just edit my PR)
I have no access to https://dev.azure.com/rare-technologies/gensim-ci, only you have an access.

**Comment by menshikh-iv** [comment]
UPD: something wired with microsoft auth system & permissions, let me dig in ...

**Comment by piskvorky** [comment]
That's weird. This is how it's set up:

![azureadmin](https://user-images.githubusercontent.com/610412/80947901-676c3180-8df1-11ea-9a14-718e7ef56a41.png)

**Comment by menshikh-iv** [comment]
I can open your link only If I don't log in (and have no settings controls)

**Comment by menshikh-iv** [comment]
![image](https://user-images.githubusercontent.com/15094669/80948260-65f33700-8dfa-11ea-8adb-aa7545f5652e.png)
Looks like you should add us to organization @piskvorky

**Comment by piskvorky** [comment]
I already added you to the org – otherwise I couldn't have added you to the project:

<img width="1440" alt="Screen Shot 2020-05-04 at 10 40 44" src="https://user-images.githubusercontent.com/610412/80949155-c0d56000-8df3-11ea-944f-d69b0df550a2.png">

**Comment by menshikh-iv** [comment]
@piskvorky no emails (even in spam), still no access :(

**Comment by piskvorky** [comment]
Hm. I'll try to see if there's any help/support in Azure DevOps.

**Comment by menshikh-iv** [comment]
NLP <3

![image](https://user-images.githubusercontent.com/15094669/80950122-ef583880-8dfd-11ea-8023-ae997cbf5fff.png)

**Comment by piskvorky** [comment]
https://developercommunity.visualstudio.com/content/problem/1016416/users-added-but-have-no-access.html

**Comment by menshikh-iv** [comment]
@piskvorky I'm digging into the documentation and have an idea: can you try to fully delete us from azure and add though GitHub usernames (instead of emails)?

**Comment by piskvorky** [comment]
OK. The Azure support team responded, I'll try that first.

**Comment by piskvorky** [comment]
> Note:

That's what I did before. I re-did it again now – did you receive an email now?

**Comment by menshikh-iv** [comment]
No, I changed subscription setting in profile to "get all emails", can you try to resend?

**Comment by piskvorky** [comment]
@menshikh-iv Invite resent:

<img width="1434" alt="Screen Shot 2020-05-04 at 14 09 59" src="https://user-images.githubusercontent.com/610412/80964344-fb012a80-8e10-11ea-9c24-6d99821d7552.png">

**Comment by menshikh-iv** [comment]
@piskvorky got them, I have an access

**Comment by piskvorky** [comment]
Good. Because adding Github usernames (instead of emails) is not possible. I tried and adding a new user requires their email.

**Comment by menshikh-iv** [comment]
@piskvorky still can't run build: looks like lack of permissions to RaRe organization, can you create default python pipeline thought https://dev.azure.com/rare-technologies/gensim-ci/_build yourself?

**Comment by piskvorky** [comment]
Unfortunately not; it's asking for those crazy OAuth permissions on `piskvorky` again.

What permissions do you need? You should have the same as me (admin) = full access.

**Comment by menshikh-iv** [comment]
> What permissions do you need?

No idea, I'm getting the same OAuth (without options) as you

**Comment by menshikh-iv** [comment]
PAT tokens maybe https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml ? This shouldn't be such crazy as oauth

**Comment by piskvorky** [comment]
I made you an admin for `Gensim` on Github too, as well as admin for Azure `Gensim-CI`. I don't see any higher permissions than that.

**Comment by menshikh-iv** [comment]
![image](https://user-images.githubusercontent.com/15094669/80966416-2722a880-8e1d-11ea-8c59-da07eae290e8.png)

No idea what's wrong here =/

**Comment by menshikh-iv** [comment]
![image](https://user-images.githubusercontent.com/15094669/80966857-0149d380-8e1e-11ea-907c-1664236a95e5.png)
moving forward (thanks to https://developercommunity.visualstudio.com/content/problem/642369/pipelines-creation-falls-back-to-github-oauth-auth.html thread), but that's not the end

**Comment by menshikh-iv** [comment]
Finally, it running

![image](https://user-images.githubusercontent.com/15094669/80973616-4bd04d80-8e28-11ea-8c11-1e50911ac914.png)

**Comment by menshikh-iv** [comment]
So, travis & azure have around 1m difference in the building, no more "slowdown" from appveyor :) 


![image](https://user-images.githubusercontent.com/15094669/81143907-a4fcc600-8f7b-11ea-92b1-16f66ace4fca.png)
![image](https://user-images.githubusercontent.com/15094669/81143914-a6c68980-8f7b-11ea-8fd4-e478821176b2.png)

Possible next step - make a similar replacement in `gensim-wheels`

**Comment by gojomo** [comment]
I think a side-effect of this switchover is causing me major git headaches on both Ubuntu & MacOS. I suspect especially this git config change:

https://github.com/RaRe-Technologies/gensim/commit/93385d331935fd8eeedb3f52b4dd8883dc86695c#diff-fc723d30b02a4cca7a534518111c1a66

I'm getting lots of spurious indications that files are modified in ways that `git` can't reverse in the usual ways, blocking usual operations – and possibly even mangling of the contents of binary files. They're easy to reproduce even in a fresh, vanilla `clone`. I've posted more details on SO in the hopes of getting some git expert advice or a canonical fix:

https://stackoverflow.com/questions/61720528/simple-git-clone-mangles-many-files-with-phantom-un-resettable-modified-state

Even if this *can* be worked-around with some local git config change by every dev, it seems something to fix in the repo if at all possible. 

Separately, can these new Windows-only Azure builds be listed *after* the faster/more-central CircleCI/Travis builds? (They don't seem to show as much info, while in progress, as the others.)

**Comment by gojomo** [comment]
The 1st comment response at SO suggests the `.gitattributes` set up to help this Azure process is overbroad, and may inadvertently modify non-text files: https://stackoverflow.com/questions/61720528/simple-git-clone-mangles-many-files-with-phantom-un-resettable-modified-state?noredirect=1#comment109174230_61720528 

On the good chance that deleting this file is a step towards a solution, I've started #2836 to do that. Cloning that branch (`git clone -b del-gitattributes-text-eol-lf git@github.com:gojomo/gensim.git`) yields a usable working-directory without the problem.

**Comment by piskvorky** [comment]
> … yields a usable working-directory without the problem

Are the files already mangled, or is it safe to continue from such branch?

**Comment by gojomo** [comment]
> > … yields a usable working-directory without the problem
> 
> Are the files already mangled, or is it safe to continue from such branch?

In the clone from the branch-without-`.gitattributes`, I believe they're unchanged. The phantom-change indication seems to be a warning of imminent automatic rewriting on next commit. 

Indeed, take a look at PR #2837 - it's what happens if one of the 'modified' files is committed. It's definitely been changed in the repo at that point. However, while preparing the commit (at the `add` step, git gave its error:
```
warning: CRLF will be replaced by LF in docs/notebooks/index.
The file will have its original line endings in your working directory.
```
And indeed, the local file hasn't changed - it's sha1sum is the same as before, and the same as a 'raw' download from the changed-years-ago PNG from github:
```
$ sha1sum jupyter_home.png 
4832400ee0650c5140ce1261c57106d9fdd1df05  jupyter_home.png
```
