### ISSUE TITLE
Prepare gensim 3.8.3

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#2820]
OK guys, looks like we're getting close to releasing this thing. I've just updated the CHANGELOG - @piskvorky please have a look and make any changes as necessary. Each update will require a re-run of the CI and a rebuild of the wheels, so please keep that in mind.

Some other relevant things to check:

- [Release checklist](https://github.com/RaRe-Technologies/gensim/wiki/Developer-page#making-a-new-release)
- [Release milestone](https://github.com/RaRe-Technologies/gensim/milestone/2?closed=1)
- [Diff with current develop HEAD](https://github.com/RaRe-Technologies/gensim/compare/develop...release-3.8.3?expand=1)

I've gone through the above myself and think like we're ready to release. @piskvorky @menshikh-iv Please let me know if you feel the same and we'll get this thing out the door.

**Comment by menshikh-iv** [comment]
@mpenkov I merged https://github.com/RaRe-Technologies/gensim-wheels/pull/1, so, after build done (~6h, thanks to Appveyour and `wheelhouse_uploader` bug), we will be ready to release.

I think we are ready

**Comment by piskvorky** [comment]
I went through the tickets yesterday, all good.

Except I saw this new comment in the diff:
<img width="930" alt="Screen Shot 2020-05-03 at 09 15 51" src="https://user-images.githubusercontent.com/610412/80908285-ef353b80-8d1e-11ea-9ca3-f4ea8b46b9ef.png">

and went to look at the `nmslib` module and that's another rabbit hole (lots of fixes, probably buggy). I'll open a PR soon, but probably not critical for 3.8.3.

**Comment by piskvorky** [comment]
I also replace all references to MacPython on the [Release checklist](https://github.com/RaRe-Technologies/gensim/wiki/Developer-page without) with our new mirror.

**Comment by menshikh-iv** [comment]
@piskvorky about nmslib: this stuff NEVER works on `py2` as I investigate, but works on python3.
Current impoirt are the simplest workaround for this problem (and will be no needed when we drop py2)

**Comment by piskvorky** [comment]
Nothing major in the end. I opened the PR: #2821.

@mpenkov up to you whether we include that in 3.8.3 or not, WDYT?

**Comment by mpenkov** [comment]
Let's leave it out, it's not critical.

**Comment by mpenkov** [comment]
OK, we're done!

- https://github.com/RaRe-Technologies/gensim/releases/tag/3.8.3
- https://github.com/RaRe-Technologies/gensim-wheels/releases/tag/3.8.3
- https://pypi.org/project/gensim/3.8.3/#files

Huge thanks to @menshikh-iv for "help" (he really did most of the work) with this release!
