### ISSUE TITLE
can't install gensim to conda because of python version 3.8

### ISSUE THREAD

**Issue by engmrgh** [RaRe-Technologies/gensim#2826]
#### Problem description

I wanted to install gesim in my condo environment. I have used both the command suggested in the [conda page](https://anaconda.org/anaconda/gensim) `conda install -c anaconda gensim` and which suggested in the [gensim page](https://radimrehurek.com/gensim/index.html) `conda install -c conda-forge gensim`. I think the issue is the gensim version on conda is not updated to support python version 3.8. My OS is Ubuntu 20.04.

#### Steps/code/corpus to reproduce
Traceback for `install -c anaconda gensim`:
<pre>(regenv) <font color="#4E9A06"><b>➜  </b></font><font color="#06989A"><b>reg</b></font> <font color="#3465A4"><b>git:(</b></font><font color="#CC0000"><b>master</b></font><font color="#3465A4"><b>) </b></font><font color="#C4A000"><b>✗</b></font> <font color="#4E9A06">conda</font> install -c anaconda gensim
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                        

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - gensim -&gt; python[version=&apos;&gt;=2.7,&lt;2.8.0a0|&gt;=3.6,&lt;3.7.0a0|&gt;=3.7,&lt;3.8.0a0|&gt;=3.5,&lt;3.6.0a0&apos;]

Your python: python=3.8

If python is on the left-most side of the chain, that&apos;s the version you&apos;ve asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2

</pre>
TraceBack for `conda install -c conda-forge gensim`:
<pre>(regenv) <font color="#CC0000"><b>➜  </b></font><font color="#06989A"><b>reg</b></font> <font color="#3465A4"><b>git:(</b></font><font color="#CC0000"><b>master</b></font><font color="#3465A4"><b>) </b></font><font color="#C4A000"><b>✗</b></font> <font color="#4E9A06">conda</font> install -c conda-forge gensim
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                        

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - gensim -&gt; python[version=&apos;2.7.*|3.5.*|3.6.*|&gt;=2.7,&lt;2.8.0a0|&gt;=3.6,&lt;3.7.0a0|&gt;=3.7,&lt;3.8.0a0|&gt;=3.5,&lt;3.6.0a0&apos;]

Your python: python=3.8

If python is on the left-most side of the chain, that&apos;s the version you&apos;ve asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0
  - feature:|@/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2

</pre>
#### Versions
```python
Linux-5.4.0-28-generic-x86_64-with-glibc2.10
Python 3.8.2 (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0]
NumPy 1.18.1
SciPy 1.4.1
```
Thanks.

**Comment by piskvorky** [comment]
Try installing with normal pip: `pip install --upgrade gensim`.

The conda package is often not up to date and mostly unsupported.

**Comment by WildZes** [comment]
Hello.

Are any else solutions to such a problem?
Tried different ways to solve my problem and still getting 
`Requirement already satisfied: gensim in /home/mrp/anaconda3/lib/python3.7/site-packages (4.1.2)
Requirement already satisfied: numpy>=1.17.0 in /home/mrp/anaconda3/lib/python3.7/site-packages (from gensim) (1.21.2)
Requirement already satisfied: scipy>=0.18.1 in /home/mrp/anaconda3/lib/python3.7/site-packages (from gensim) (1.3.0)
Requirement already satisfied: smart-open>=1.8.1 in /home/mrp/anaconda3/lib/python3.7/site-packages (from gensim) (5.2.1)
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-775224418cd7> in <module>
      1 get_ipython().system('python -m pip install gensim --user')
----> 2 import gensim

ModuleNotFoundError: No module named 'gensim'`
in jupyter notebook.

I've tried to create absolutly new enviroment and install gensim with 'conda install gensim', 'conda install -c anaconda gensim', 'pip install gensim', 'python -m pip install gensim --user' and maybe somehow else, but I've already forgot about other methods.

TraceBack for `pip install --upgrade gensim`
`Collecting gensim
  Downloading gensim-4.1.2-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (24.1 MB)
     |████████████████████████████████| 24.1 MB 52 kB/s 
Requirement already satisfied, skipping upgrade: smart-open>=1.8.1 in /home/mrp/anaconda3/envs/ml_business/lib/python3.8/site-packages (from gensim) (3.0.0)
Requirement already satisfied, skipping upgrade: scipy>=0.18.1 in /home/mrp/anaconda3/envs/ml_business/lib/python3.8/site-packages (from gensim) (1.6.2)
Requirement already satisfied, skipping upgrade: numpy>=1.17.0 in /home/mrp/anaconda3/envs/ml_business/lib/python3.8/site-packages (from gensim) (1.20.3)
Requirement already satisfied, skipping upgrade: requests in /home/mrp/anaconda3/envs/ml_business/lib/python3.8/site-packages (from smart-open>=1.8.1->gensim) (2.24.0)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/mrp/anaconda3/envs/ml_business/lib/python3.8/site-packages (from requests->smart-open>=1.8.1->gensim) (1.25.11)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /home/mrp/anaconda3/envs/ml_business/lib/python3.8/site-packages (from requests->smart-open>=1.8.1->gensim) (2.10)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/mrp/anaconda3/envs/ml_business/lib/python3.8/site-packages (from requests->smart-open>=1.8.1->gensim) (2020.6.20)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /home/mrp/anaconda3/envs/ml_business/lib/python3.8/site-packages (from requests->smart-open>=1.8.1->gensim) (3.0.4)
Installing collected packages: gensim
  Attempting uninstall: gensim
    Found existing installation: gensim 4.0.1
    Uninstalling gensim-4.0.1:
      Successfully uninstalled gensim-4.0.1
Successfully installed gensim-4.1.2
`

Linux 5.4.0-84-generic #94~18.04.1-Ubuntu SMP Thu Aug 26 23:17:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Python 3.8.5
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
scipy 1.6.2
numpy 1.20.3
