### ISSUE TITLE
api.load of fasttext vectors returns Word2VecKeyedVectors 

### ISSUE THREAD

**Issue by johntiger1** [RaRe-Technologies/gensim#2834]
![image](https://user-images.githubusercontent.com/14852840/81504015-09d65a00-92b5-11ea-8b6c-21082e4479ff.png)

Firstly, thanks for the great library. 
When loading FastText using the API, the model returned is actually one with Word2VecKeyedVectors , not FastTextKeyedVectors, hence this causes issues for OOV loading
```
Linux-4.19.104+-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
NumPy 1.18.4
SciPy 1.4.1
gensim 3.6.0
FAST_VERSION 1
```

**Comment by piskvorky** [comment]
Yeah that's weird. I remember coming across this ?problem? ?strange behaviour? in the past, although I cannot find the issue or mailing list thread right now.

@mpenkov @menshikh-iv  do you remember why the fastText model loads word2vec vectors instead of fastText (ngram) vectors?

**Comment by menshikh-iv** [comment]
@piskvorky that's correct behavior because this is word-vectors (nothing else), you can see them on the top of page https://fasttext.cc/docs/en/english-vectors.html

**Comment by johntiger1** [comment]
Wow, thanks for the quick response! @menshikh-iv inside the zip file they actually give us access to both the `.bin` and `.vec` versions, perhaps we can add some functionality to leverage the `.bin` side natively? Thanks

**Comment by menshikh-iv** [comment]
@johntiger1 that's possible, of course. Feel free to contribute https://github.com/RaRe-Technologies/gensim-data#want-to-add-a-new-corpus-or-model
