### ISSUE TITLE
KeyedVectors importing keras instead of tensorflow.keras?

### ISSUE THREAD

**Issue by vrmpx** [RaRe-Technologies/gensim#2842]
Hello there,

I got a super quick question regarding the function `get_keras_embeddings` of KeyedVectors.py. Is there a reason behind requiring keras package to be installed (specifically referring to [these lines](https://github.com/RaRe-Technologies/gensim/blob/2360459e0014f5db8fc587005933a6399efab435/gensim/models/keyedvectors.py#L1415-L1419)) instead of going through tensorflow 2.0 API (i.e., `import tensorflow.keras`)?

**Comment by vrmpx** [comment]
I just realized there is a PR addressing this particular issue (https://github.com/RaRe-Technologies/gensim/pull/2729)

**Comment by piskvorky** [comment]
Yeah, that PR is unfinished. Can you help fix it?

It won't get completed unless people who actually use these Keras workflow(s) assist.

**Comment by piskvorky** [comment]
Ping @vrmpx can you help?
