### ISSUE TITLE
doc2vec - infer_vector gives different values on every run

### ISSUE THREAD

**Issue by vr25** [RaRe-Technologies/gensim#2847]
Hi,

I used doc2vec to train the documents following the post [here](https://www.thinkinfi.com/2019/10/doc2vec-implementation-in-python-gensim.html
)

I get different values for infer_vector - most similar documents on every run. I tried to set a seed value to avoid the initial randomization but that didn't seem to fix this issue. Any better suggestions would be helpful!

Thanks!

**Comment by piskvorky** [comment]
Hi, check out the FAQ:
https://github.com/RaRe-Technologies/gensim/wiki/Recipes-&-FAQ#q11-ive-trained-my-word2vecdoc2vecetc-model-repeatedly-using-the-exact-same-text-corpus-but-the-vectors-are-different-each-time-is-there-a-bug-or-have-i-made-a-mistake-2vec-training-non-determinism
