### ISSUE TITLE
CalledProcessError: non-zero returned non-zero exit status 1. Gensim Mallet

### ISSUE THREAD

**Issue by jhuang12** [RaRe-Technologies/gensim#2851]
I was trying to run ldaMallet for modeling, but ran into the CalledProcessError. 

![image](https://user-images.githubusercontent.com/4327768/83911368-fd60e800-a720-11ea-9a3d-ee86ea0eb9c9.png)

Then, we I run the following code:

`model_list, coherence_values = compute_coherence_values(dictionary=words_id2word, corpus=words_corpus, texts=data_words_nonstop_trigrams, start=2, limit=40, step=6)`

I encountered the calledprocesserror:

'CalledProcessError: Command 'C:/mallet-2.0.8/bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input C:\Users\jia\AppData\Local\Temp\aa34be_corpus.txt --output C:\Users\jia\AppData\Local\Temp\aa34be_corpus.mallet' returned non-zero exit status 1.
'
I tried the solutions in https://github.com/RaRe-Technologies/gensim/issues/2163, as well as stackoverlow solutions, but none of them worked. Please help. Thank you in advance. 

#### Versions

```python
Windows-10-10.0.18362-SP0
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
NumPy 1.16.4
SciPy 1.4.1
gensim 3.8.0
FAST_VERSION  1
```

**Comment by gojomo** [comment]
What happens when you try to run exactly the command-line shown in the error yourself? In the case of the error above, that'd be...

```
C:/mallet-2.0.8/bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input C:\Users\jia\AppData\Local\Temp\aa34be_corpus.txt --output C:\Users\jia\AppData\Local\Temp\aa34be_corpus.mallet
```

...but ideally you'd want to run exactly the version you've just seen in the immediately-preceding error. You'll likely get more error details.

**Comment by mattpodolak** [comment]
I have gotten this exact same error, but when I run the command as suggested in the command-line it runs successfully and outputs the expected file...

**Comment by piskvorky** [comment]
Thanks for the report @mattpodolak . I'm afraid this Mallet mystery awaits an adept user-engineer, who will look into it properly.

None of us core developers use Windows, so it's unlikely to solve it. Step one might be teasing out what the "non-zero exit status 1" means. Bad path? File not executable? No permissions? Missing input files?

**Comment by mattpodolak** [comment]
@piskvorky I was able to resolve this issue on my machine. I had installed the Java JDK but had not restarted my Jupyter Notebook, I looked at the console log of the notebook server and noticed it was printing out `'Java' is not recognized as an internal or external command` every time I tried running:
```
ldamallet = gensim.models.wrappers.LdaMallet(mallet_path, corpus=corpus_4, num_topics=10, id2word=id2word_4, workers=7)
```

Adding the JDK to PATH and restarting Jupyter Notebook (and Git Bash) has resulted in success!

**Comment by piskvorky** [comment]
That's great, thanks for following up.

@jhuang12 I'll close this ticket but let us know if your problem persists.
