### ISSUE TITLE
Reduce gensim surface area

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#2852]
Are there subpackages/submodules that we're not maintaining anymore, and could remove?

- [x] summarization
- [x] HDP
- [x] wordrank
- [x] dependency on pattern
- [x] various wrappers (incl. sklearn) and others.
- [x] simserver documentation
- [x] viz

The goal is to reduce the maintenance burden of the project.

**Comment by piskvorky** [comment]
@mpenkov any other modules to be removed?

I'd like to finalize this even before the pre-release, so the documentation is up-to-date. Thanks.

**Comment by piskvorky** [comment]
`PoincareModel` is another such candidate. Not touched by the recent refactoring and upgrades, it's probably out of date and useless.

**Comment by mpenkov** [comment]
@piskvorky I had a look at Poincare model. Yes, it's old and hasn't changed much recently, but it's fairly well tested (I eyeballed the [tests](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/test/test_poincare.py) and they make sense to me, and they all pass). Do you really want to remove it?

**Comment by piskvorky** [comment]
No, if it's good, we can keep it.

I don't remember many user complaints / bug reports about the Poincare model, although that may be simply because nobody uses it.

**Comment by mpenkov** [comment]
@piskvorky Perhaps we can remove just the visualization subpackage? That doesn't look like it belongs in a library like gensim

https://github.com/RaRe-Technologies/gensim/tree/develop/gensim/viz

**Comment by piskvorky** [comment]
`viz` seems to contain a single module, with two functions related to Poincare embeddings. So if we keep Poincare, maybe move those two functions to its module? (without introducing new dependencies, so import-on-demand)

Or perhaps move those functions to the particular documentation / tutorial that needs `viz`? Or remove them altogether? I really don't know the context, sorry. But it's a silly subpackage for sure.

**Comment by mpenkov** [comment]
The viz stuff is untested and requires plotly as a dependency (which is in setup.py, meaning all installs include it). My suggestion is to remove viz altogether, and remove the dependency. Visualization is too use case-specific, everyone will want to do it differently anyway.

**Comment by piskvorky** [comment]
Yes, but why is it there? Used by some tutorial / notebook / guide?

**Comment by mpenkov** [comment]
As far as I can tell, it isn't used or mentioned anywhere outside of the automatically generated documentation.

**Comment by piskvorky** [comment]
Hm, double weird. I guess we can just remove it then.

> dependency (which is in setup.py, meaning all installs include it)

You mean all installs require plotly? I hope not.

**Comment by mpenkov** [comment]
No, on second examination, only docs builds require it, but nevertheless, it isn't something we need to keep.

**Comment by mpenkov** [comment]
OK, I think I've addressed all the candidates we discussed the last time we talked about this. Is there anything else we need to remove?

**Comment by mpenkov** [comment]
Misha TODO

- [ ] Check that docs build from scratch (locally)
- [ ] Close this ticket

**Comment by mpenkov** [comment]
Related: #3077
