### ISSUE TITLE
mallet wrapper return non-zero exit status 126

### ISSUE THREAD

**Issue by allenren97** [RaRe-Technologies/gensim#2855]
#### Problem description

I am using the cloudera data science workbench for my Latent Dirichlet Allocation project, I am training a model using the command

```python
mallet_path = '../mallet-2.0.8/bin/mallet' # update this path
ldamallet_nv7 = gensim.models.wrappers.LdaMallet(mallet_path, corpus=nv_corpus, num_topics=7, id2word=nv_id2word, iterations = 5000, random_seed = 1997)
ldamallet_nv7.print_topics()
```
here mallet_path is the relative path I put in my project folder.

When I run the code, I have the error like this:
```python
'''Command '../mallet-2.0.8/bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input /tmp/f58d7e_corpus.txt --output /tmp/f58d7e_corpus.mallet' returned non-zero exit status 126.'''
```

There is no commonly asked questions about this issue so I am thinking posting a new issue

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)

##output:
##Linux-3.10.0-862.14.4.el7.x86_64-x86_64-with-debian-buster-sid
##Python 3.6.9 (default, Dec  4 2019, 05:05:08) 
##[GCC 7.4.0]
##NumPy 1.17.2
##SciPy 1.3.3
##gensim 3.8.3
##FAST_VERSION 1
```

**Comment by piskvorky** [comment]
From https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html

```
If a command is found but is not executable, the return status is 126.
```

Is your mallet binary executable?

**Comment by allenren97** [comment]
I copied the mallet file from my other project now it is giving me return status 127 now

**Comment by piskvorky** [comment]
Try executing it outside of gensim, to make sure it's really executable.

**Comment by allenren97** [comment]
I can execute it no problem on my mac, but when I put it on cloudera thats when the issue happens
