### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by somah1411** [RaRe-Technologies/gensim#2870]
Hi,
I used python code uisng gensim , and I  got error and the output not printed.
![image](https://user-images.githubusercontent.com/20572241/86201124-f7381d00-bba1-11ea-972c-50866402f156.png)

/_**usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:56: DeprecationWarning:

Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).**_

**Comment by piskvorky** [comment]
Hi, follow the error instructions (and the issue template when creating issues).
