### ISSUE TITLE
Finetuning gensim doc2vec

### ISSUE THREAD

**Issue by rafikg** [RaRe-Technologies/gensim#2877]
#### Problem description

My question is about fine-tune a pretrained doc2vec model on Gensim. Suppose that we have a doc2vec model pretrained on Wikipedia corpus, and we have another specified small corpus. My aim is to fine-tune the pretrained model on my own corpus. Is it make sense in this context? Because, fine-tuning in this context means we want to increase the vocab of the pretrained model and consequently change the structure of the network! I have read several tutorial on the website but nothing  mentioned fine-tuning.

**Comment by wassimseif** [comment]
Did you figure it out ?
