### ISSUE TITLE
LdaMulticore doesn't use more than 4 cores when workers=31 (32-core aws machine)

### ISSUE THREAD

**Issue by romovpa** [RaRe-Technologies/gensim#288]
I've tried to estimate a speed-up curve for LdaMulticore on 32-core AWS machine (c3.8xlarge, see [here](http://aws.amazon.com/ec2/instance-types/?nc2=h_ls) for more characteristics) using English Wikipedia corpus (constructed with `gensim.scripts.make_wiki`). The speed-up ratio by number of parallel workers looks very strange:
![speedup_gensim](https://cloud.githubusercontent.com/assets/152387/5992175/f5a8319a-aa2d-11e4-8d5e-a0f5fd560c01.png)

The code of a run:
```python
model = gensim.models.LdaMulticore(
                corpus=corpus,
                id2word=id2word,
                num_topics=100,
                chunksize=10000,
                passes=1,
                batch=False,
                alpha=0.1,
                eta=0.1,
                decay=0.5,
                eval_every=0,
                iterations=20,
                gamma_threshold=0.001,
                workers=num_processors-1, # minus one because `workers`
                                          # is the number of extra processes
            )
```
was performed for num_processors in [1, 2, 4, 8, 12, 16, 24, 32].

Running time results:
num_processors=1, time: 12378.28 sec, speedup=1.000000
num_processors=2, time: 8901.31 sec, speedup=1.390613
num_processors=4, time: 3590.29 sec, speedup=3.447710
num_processors=8, time: 3406.73 sec, speedup=3.633478
num_processors=12, time: 3429.75 sec, speedup=3.609091
num_processors=16, time: 3390.78 sec, speedup=3.650570
num_processors=24, time: 3444.80 sec, speedup=3.593323
num_processors=32, time: 3426.00 sec, speedup=3.613041

I saw `htop` when the training was running with num_processors=32, I've noticed that only 4 cores was 100% loaded.

Could you explain, what I did wrong?

**Comment by romovpa** [comment]
Gensim version: gensim-0.10.3-py2.7

**Comment by piskvorky** [comment]
How fast is your input iterator? That is, how fast can you read documents off your `corpus` variable?

CC @ziky90

**Comment by romovpa** [comment]
Yes, It seems like it.

Just passing through the corpus takes 2542 sec.
```python
In [1]: import gensim

In [2]: id2word = gensim.corpora.Dictionary.load_from_text('data/enwiki-20141208-pages-articles_wordids.txt.bz2')

In [3]: train_corpus = gensim.corpora.MmCorpus('data/wiki_bow_train.mm')

In [4]: print train_corpus
MmCorpus(3518495 documents, 100000 features, 545608177 non-zero entries)

In [5]: %%time
   ...: for doc in train_corpus:
   ...:     pass
   ...: 
CPU times: user 42min 17s, sys: 3.28 s, total: 42min 20s
Wall time: 42min 22s
```

**Comment by romovpa** [comment]
[Gist with a log of training at debug level](https://gist.github.com/romovpa/13cd4b0b2e681b72e538)

So. Is there are ways to read corpus faster?

**Comment by romovpa** [comment]
Guys? 
The corpus iterator is too slow to use LdaMulticore effectively.
I want to fix this. Could you guide me what to do?

**Comment by ziky90** [comment]
My one idea here is that the corpus iterator should work also in some distributed way (distributed to different cores using multiprocessing). 
Eg. split somehow the corpus file, read one part by one core and at the end create some Queue from which you'll yield documents. (It's just an idea and I'm not sure if that's gonna work)

From what I've seen in the code it seems to me like you'll need to implement something like MmReaderMulticore, that will do the same thing like matutils.MmReader, but faster. 

It's just my idea where I'd try to implement it, but honestly I don't understand corpus iteration that much in detail. So I'm not sure for example if .mm files are possible to split in some easy way and I'm also not sure if the output queue would not be a too big bottle neck at the end.

**Comment by piskvorky** [comment]
@romovpa you can try the "sharded corpus" from this pull request: https://github.com/piskvorky/gensim/pull/284

Let me know if that solves your troubles (=save your corpus in this new format, which should be much faster to read/write).

Also, simply gzipping your large `.mm` file may help too.

**Comment by tmylk** [comment]
@romovpa did sharded corpus resolve the issue?

**Comment by BoPengGit** [comment]
Did anyone solve this problem, and if so can you print the solution code?

Thank you.

**Comment by tmylk** [comment]
Closing as workaround suggested(ShardedCorpus) but then issue abandoned
