### ISSUE TITLE
KeyedVectors.load_word2vec_format('w2v.bin',binary=False) raise Value Error

### ISSUE THREAD

**Issue by laomagic** [RaRe-Technologies/gensim#2881]
#### Problem description

A value exception was thrown while loading the word vector file.

#### Steps/code/corpus to reproduce
```
from gensim.models import Word2Vec
from gensim.models import KeyedVectors


common_texts = [['human', 'interface', 'computer',' '],
 ['survey', 'user', 'computer', 'system', 'response', 'time'],
 ['eps', 'user', 'interface', 'system'],
 ['system', 'human', 'system', 'eps'],
 ['user', 'response', 'time'],
 ['trees'],
 ['graph', 'trees'],
 ['graph', 'minors', 'trees'],
 ['graph', 'minors', 'survey']]
model = Word2Vec(common_texts, size=10, window=5, min_count=1, workers=4)
model.wv.save_word2vec_format('w2v.bin',binary=False)
# load word embedding
KeyedVectors.load_word2vec_format('w2v.bin',binary=False)
```

问题：加载训练语料的词向量文件过程中抛出值异常：
When there is a space in the corpus, the loading word vector file will throw a ValueError.
抛出异常的文件位置
**gensim/models/utils_any2vec.py**
```
parts = utils.to_unicode(line.rstrip(), encoding=encoding, errors=unicode_errors).split(" ")
if len(parts) != vector_size + 1:
    raise ValueError("invalid vector on line %s (is this really the text format?)" % line_no)
word, weights = parts[0], [datatype(x) for x in parts[1:]]
```

解决方案：去除预料中的空格或者使用加载模型的方式
Solution: remove the space in the corpus and load model

#### Versions

Please provide the output of:

Linux-4.4.0-142-generic-x86_64-with-debian-stretch-sid
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]
NumPy 1.18.1
Sc```iPy 1.4.1
gensim 3.8.3
FAST_VERSION 1

**Comment by piskvorky** [comment]
I believe that's expected behaviour. Tokens are not allowed to contain whitespace in the text word2vec format.

Use Gensim's native `save()` / `load()` if you need a more flexible serialization format. Closing here – I don't see any bug here.
