### ISSUE TITLE
Measure performance of gensim 4.0.0 vs previous versions

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#2887]
Not every 1-line decision; just ones that are in inner loops of hot-spot code.

Definitely a big TODO: compare performance before/after.

_Originally posted by @piskvorky in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0MzQ5Mjk1NTk1/timeline/more_items_

Fixes #2960.

**Comment by piskvorky** [comment]
This link is also broken. @mpenkov this way of creating tickets seems more trouble than worth, with the context missing.

**Comment by mpenkov** [comment]
I'll take it up with github support. It's convenient, but only when it works.

**Comment by mpenkov** [comment]
@piskvorky From github support:

> This might be an uncaught edge case on our end. I have raised this up with our engineering team to investigate further.

I'll keep my eyes open for the problem in case it recurs.

**Comment by piskvorky** [comment]
Some Word2vec measurements here: https://github.com/RaRe-Technologies/gensim/pull/2939#issuecomment-691729995

**Comment by piskvorky** [comment]
Comparing current `develop` (at ea87470e) against 3.8.3:
(identical training params, identical HW, text9 corpus, measured with [benchmark.py](https://gist.github.com/piskvorky/85015d52254df77cd23ca43bc2e8322d))

### fasttext 3.8.3

training on a 124301826 raw words (88163974 effective words) took 107.3s, 821794 effective words/s
2:53.89 elapsed
4318564k max mem

### fasttext develop

training on a 124301826 raw words (88166519 effective words) took 96.4s, 914282 effective words/s
2:17.43 elapsed
1318592k max mem

### word2vec 3.8.3

training on a 124301826 raw words (88162276 effective words) took 52.3s, 1684982 effective words/s
1:41.36 elapsed
373612k max mem

### word2vec develop

training on a 124301826 raw words (88166114 effective words) took 50.0s, 1762436 effective words/s
1:13.82 elapsed
348060k max mem
