### ISSUE TITLE
Document the X2Vec refactoring in the change log.

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#2889]
Document the X2Vec refactoring in the change log.

What changed from the user's perspective?

_Originally posted by @mpenkov in https://github.com/RaRe-Technologies/gensim/pull/2698/review_comment/create_

**Comment by piskvorky** [comment]
In the changelog, plus also in our Wiki page documenting the migration steps:
https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4

**Comment by piskvorky** [comment]
Overview included by @gojomo at https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4
