### ISSUE TITLE
LdaMallet eta parameter 

### ISSUE THREAD

**Issue by cbravo93** [RaRe-Technologies/gensim#2895]
Hi!

Thanks for this great package! I have noticed that when using LdaMallet there is no option to adjust the eta parameter, which by default is 0.01 (in mallet train-topics).  Is there any plan to add this option?

Thanks!

C

**Comment by piskvorky** [comment]
Probably not, sorry. There's a plan to discontinue these external wrappers (such as Mallet), so we're not planning any new extensions there.
