### ISSUE TITLE
TypeError: summary() got an unexpected keyword argument 'sentenses'

### ISSUE THREAD

**Issue by devennsk** [RaRe-Technologies/gensim#2900]
#### Problem description

What are you trying to achieve? What is the expected result? What are you seeing instead?

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

**Comment by gojomo** [comment]
You haven't shown the code that caused this, nor the full error stack – both of which would help determine what's happening. And `sentenses`, as a misspelling of `sentences`, is not a parameter, keyword or other, to any gensim API. 

Unless you're fairly sure an issue is a bug needing a fix, requesting help for any issue with you code is better done through the project discussion list: https://groups.google.com/forum/#!forum/gensim

(This can be reopened if you can add info showing a real bug, rather just than a typo in your code.)
