### ISSUE TITLE
"Wrong" default parameter for [sum]alpha for LdaMallet

### ISSUE THREAD

**Issue by jonaschn** [RaRe-Technologies/gensim#2903]
The [original Mallet](https://github.com/mimno/Mallet/blob/3bda6c73b2ff90d2e91a35dc6e9d604fbea8248e/src/cc/mallet/topics/tui/TopicTrainer.java#L152) default parameters are 
--alpha DECIMAL
  SumAlpha parameter: sum over topics of smoothing over doc-topic distributions. [alpha_k = [this value] / [num topics]](https://github.com/mimno/Mallet/blob/12487de1aa6433bdcf5af0ee0a17b368e64c7acf/src/cc/mallet/topics/ParallelTopicModel.java#L181)
  Default is 5.0
--beta DECIMAL
  Beta parameter: smoothing parameter for each topic-word. beta_w = [this value]
  Default is 0.01

The default value provided by gensim is confusing, as could be seen here:
https://stackoverflow.com/questions/52989568/lda-gensim-mallet-documentation-on-alpha

https://github.com/RaRe-Technologies/gensim/blob/27bbb7015dc6bbe02e00bb1853e7952ac13e7fe0/gensim/models/wrappers/ldamallet.py#L78

**Comment by piskvorky** [comment]
What's wrong exactly? Feel free to propose a better wording, if this is a request for better docs.

If there's a bug somewhere, please post a minimal reproducible example.

**Comment by jonaschn** [comment]
As gensim dropped the support for the Mallet wrapper, I will close this issue.
You can find the improved and fixed (!) version of the Mallet wrapper for LDA and Labeled LDA here:
https://github.com/jonaschn/gensim/tree/labeled-lda

I further improved the documentation of Mallet's hyperparameter optimization as well as "gensimified" the parameter usage of alpha and eta.
There was a conflict in how Mallet expected the alpha parameter and how gensim provided it via gensim's LdaMallet wrapper. This way, an uninformed gensim user didn't use Mallet's default parameters but an inappropriate alpha prior (dependent on the number of topics).

**Comment by piskvorky** [comment]
That's great, thanks! Is your `labeled-lda` a full replacement for the Mallet wrapper that used to be in Gensim?

If so, we could link to it from the Gensim documentation.

**Comment by jonaschn** [comment]
It makes definitely sense to keep compatibility with gensim's API.
I never published a package to PyPI.
I am not sure how to deal with the Java dependency and it's build tool (Mallet and ant).

**Comment by piskvorky** [comment]
We didn't deal with that either. Installing Mallet was outside of Gensim's purview.

**Comment by mpenkov** [comment]
> I never published a package to PyPI.

It's a lot easier than you think. I'd encourage you to do it simply for the learning experience. 

> I am not sure how to deal with the Java dependency and it's build tool (Mallet and ant).

Probably nothing as far as packaging goes. You could have a script in your package that runs a sanity check (ensures that java and mallet executables are available, and maybe even runs mallet to check its version), but it'd be diminishing returns beyond that.

**Comment by jonaschn** [comment]
Thanks for your advice!
