### ISSUE TITLE
Add 32/64-bit reporting to issue template

### ISSUE THREAD

**Issue by gojomo** [RaRe-Technologies/gensim#2906]
It's be useful if the issue template also requested whether the local Python is a 32-bit or 64-bit executable. Adding this line to the "Please provide the output of" code should be enough:

```python
import struct; print(8 * struct.calcsize("P"))
```

**Comment by piskvorky** [comment]
Sure. Feel free to edit the [template file](https://github.com/RaRe-Technologies/gensim/blob/develop/ISSUE_TEMPLATE.md) directly.

**Comment by gojomo** [comment]
Aha, my search for how to change the template had pointed to a Github project 'Settings' tab & I'd never noticed it was driven by an in-project file. Added in bc95bcb509bdc49241346163a519252394bdc3bd.

**Comment by piskvorky** [comment]
Yeah, Github has some new style of doing templates now, that I haven't explored yet. We're still using the "older" way, with `ISSUE_TEMPLATE.md`.
