### ISSUE TITLE
Change parameter used in dtm_coherence() (in DTM wrapper) to avoid persistent warning

### ISSUE THREAD

**Issue by MeganStodel** [RaRe-Technologies/gensim#2925]
Within the DTM wrapper, using `dtm_coherence()` always produces a warning:

> "The parameter `num_words` is deprecated, will be removed in 4.0.0, use `topn` instead."

Although the function works, obviously the intention is to deprecate the parameter at some point. 

This can be tracked back to `show_topic()`, which is where `num_words` has switched to `topn`. It is a very simple fix to just change the parameter used in the `dtm_coherence()` function accordingly. 

PR incoming with fix.

**Comment by piskvorky** [comment]
Thanks. @MeganStodel what do you use DTM for? What's your motivation, context?

We're seriously considering removing all third party wrappers from Gensim: Mallet, DTM, etc. So any feedback on which parts are still in use & relevant, and why, are appreciated. Thanks.

**Comment by MeganStodel** [comment]
Thanks @piskvorky, that's interesting!

I use Mallet regularly and have just started exploring DTM. With DTM, I know there is another implementation in gensim (ldaseqmodel) but I found this much, much slower than using the wrapper. The wrappers in gensim are the only route I know for applying Mallet and DTM models in python, so would definitely feel their loss.

**Comment by piskvorky** [comment]
Thanks Megan, duly noted.
