### ISSUE TITLE
ImportError: cannot import name 'logsumexp' on KeyedVectors

### ISSUE THREAD

**Issue by luisaheise** [RaRe-Technologies/gensim#2929]
####Problem description

I'm unable to import KeyedVectors.

I guess replacing 
`from scipy.misc import logsumexp`
 to
`from scipy.special import logsumexp`
on the source code should fix it, but I'm not quite sure.

#### Steps/code/corpus to reproduce

from gensim.models import KeyedVectors

#### Versions

Linux-5.3.0-61-generic-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]
Bits 64
NumPy 1.19.1
SciPy 1.5.2

**Comment by piskvorky** [comment]
Can you add the full stacktrace + gensim version?

**Comment by luisaheise** [comment]
gensim==2.0.0
![image](https://user-images.githubusercontent.com/43735789/91854426-1b63b900-ec3a-11ea-9b96-e242ce4c9e84.png)

**Comment by luisaheise** [comment]
I just noticed that this error only happens in a jupyter notebook

**Comment by piskvorky** [comment]
Gensim 2.0.0 is more than 3 years old. I recommend upgrading.
