### ISSUE TITLE
Word2Vec docs indicate sents can be a generator, but it can't

### ISSUE THREAD

**Issue by polm** [RaRe-Technologies/gensim#2934]
#### Problem description

Tried to pass a generator as the `sentences` argument when training Word2Vec, as suggested [in the docs](https://radimrehurek.com/gensim/models/word2vec.html#usage-examples:~:text=sentences%20can%20be%20a%20generator). But then I get this error:

    TypeError: You can't pass a generator as the sentences argument. Try a sequence.

#### Steps/code/corpus to reproduce

```

from gensim.models import Word2Vec

def get_sents():
    for ii in range(100):
        yield ['hi']

sents = get_sents()
model = Word2Vec(sents, size=100, window=5, min_count=1, workers=4)
```

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import struct; print("Bits", 8 * struct.calcsize("P"))
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```
```
Linux-5.8.5-arch1-1-x86_64-with-glibc2.2.5
Python 3.8.5 (default, Jul 27 2020, 08:42:51) 
[GCC 10.1.0]
Bits 64
NumPy 1.19.1
SciPy 1.4.1
gensim 3.8.3
FAST_VERSION 1
```

**Comment by piskvorky** [comment]
Yeah, that doc section is weird. It also refers to an undefined (at that point) variable `sentences`.

@polm Could you open a PR to fix the docs please?
