### ISSUE TITLE
Issue with calculation of `new_words` and `pre_exist_words`

### ISSUE THREAD

**Issue by geopapa11** [RaRe-Technologies/gensim#2943]
https://github.com/RaRe-Technologies/gensim/blob/bb947b38a23f10c40948ec6876bc0a850eafbcf6/gensim/models/word2vec.py#L602

`new_words` and `pre_exist_words` are initialized by reference as follows:
```python
new_words = pre_exist_words = []
```
This has a result every time an append happens to one of the two, both variables change because they refer to the same underlying list. Therefore, the calculation of `new_words` and `pre_exist_words` is not correct.

The solution would simply be:
```python
new_words = []
pre_exist_words = []
```

This has downstream implications. The calculation of `retain_words` (`retain_words = new_words + pre_exist_words`)  is also not correct because of that.

**Comment by piskvorky** [comment]
Thanks. That does look like a bug!
