### ISSUE TITLE
Documentation of strip_punctuation vs strip_punctuation2 in gensim.parsing.preprocessing

### ISSUE THREAD

**Issue by sciatro** [RaRe-Technologies/gensim#2961]
Thanks for all the hard work on this fantastic library. I found a small quirk today, not really a bug, just a bit of a rough edge:

In `gensim.parsing` [preprocessing.py ](https://github.com/RaRe-Technologies/gensim/blob/e210f73c42c5df5a511ca27166cbc7d10970eab2/gensim/parsing/preprocessing.py#L121) `strip_punctuation2` is defined: `strip_punctuation2 = strip_punctuation`.

In the [documentation](https://radimrehurek.com/gensim/parsing/preprocessing.html) the description of [`strip_punctuation2`](https://radimrehurek.com/gensim/parsing/preprocessing.html#gensim.parsing.preprocessing.strip_punctuation2) is a duplication of [`strip_punctuation`](https://radimrehurek.com/gensim/parsing/preprocessing.html#gensim.parsing.preprocessing.strip_punctuation) rather than a statement of equality.

I noticed this while reading the documentation and, assuming I was missing an obvious distinction, attempting to hand diff the the docs for the two functions. When I gave up and flipped to the source it became obvious how the two functions are related.

**Comment by piskvorky** [comment]
I have no idea why we have two identical functions there. Would you be able to check the code and see which one is used where? Maybe we can keep just one? (which would solve the problem with duplicate documentation automatically)

Thanks!

**Comment by sciatro** [comment]
To the uninformed eye on a first pass neither [strip_punctuation](https://github.com/RaRe-Technologies/gensim/search?q=strip_punctuation) nor [strip_punctuation2](https://github.com/RaRe-Technologies/gensim/search?q=strip_punctuation2) seem to be used widely within the library. Conceptually they seem to me to be on the user facing edge of the API so that is not surprising. 

Of the two, based on the linked results, `strip_punctuation` has it over `strip_punctuation2` 2:1.

**Comment by piskvorky** [comment]
Yeah looks useless. Can you open a PR to get rid of `strip_punctuation2`?

**Comment by sciatro** [comment]
I don't know how to use any of the actual github functionality but I can try learn how to do so (assuming someone who knows doesn't deletes the line first). Thx again for the fantastic library.
