### ISSUE TITLE
Runtime error when producing topic document matrix (MALLET) 

### ISSUE THREAD

**Issue by yijingch** [RaRe-Technologies/gensim#2989]
#### Problem description

I'm using the gensim's mallet wrapper to infer the topic modeling results. I came across `RuntimeError: invalid doc topics format at line 2 in .../...doctopics.txt` and I thought the error only occurred in mallet==2.0.7 (it seems there's sth wrong with the `read_doctopics()`). I can read the output using revised function in #599 but I wonder why they are again not compatible... Did anyone run into the same issue and have a solution for this? (Thanks in advance!)

#### Versions
gensim==3.8.0
mallet==2.0.8

The error message:

```python---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)
<ipython-input-16-090396c3cd0e> in <module>
----> 1 fetch_topic_doc(model)

<ipython-input-7-db74820da1a0> in fetch_topic_doc(model)
      1 def fetch_topic_doc(model):
      2     model.prefix = f"{ROOT_PATH}/temp/2666_"
----> 3     matrix = [*model.load_document_topics()]
      4     print(f"# of docs: {len(matrix)}")
      5     return matrix

~/.local/lib/python3.7/site-packages/gensim/models/wrappers/ldamallet.py in read_doctopics(self, fname, eps, renorm)
    559                                     count += 1
    560                     else:
--> 561                         raise RuntimeError("invalid doc topics format at line %i in %s" % (lineno + 1, fname))
    562 
    563                 if renorm:

```

**Comment by yijingch** [comment]
Problem solved. Just as @cscorley [pointed out](https://github.com/RaRe-Technologies/gensim/issues/599#issuecomment-215979873), setting --doc-topics-threshold would return a sparse output (from mallet v2.0.8).

**Comment by piskvorky** [comment]
@yijingch thanks for following up. Is there anything we should change in Gensim?

**Comment by yijingch** [comment]
@piskvorky so far, no, thanks!
