### ISSUE TITLE
No explanation of the languages supported by Gensim various modules

### ISSUE THREAD

**Issue by rubmz** [RaRe-Technologies/gensim#2990]
#### Problem description

Many NLP libraries exist today that support many NLP related tasks. Unfortunately not all of them support more beyond English and few other languages. My GUESS here is Gensim does support more languages. But Does it?
It would be nice if anywhere in the docs it would be specified that Gensim supports languages X.Y.Z (supports Unicode, has language models, ...) - or even better - language agnostic.

#### Reproduce

A usual search would be "gensim supported languages".

#### Versions

<= 3.8.3

**Comment by piskvorky** [comment]
Yeah Gensim is language agnostic. It relies on distributional semantics (word co-occurrences) to do unsupervised learning.

Check the specific algo you're interested in (LSI, LDA, word2vec, etc) to see if it's suitable for your type of data / language. Gensim itself is not concerned with NLP text preprocessing.
