### ISSUE TITLE
KeyedVectors.most_similar() API has a confusing wrinkle

### ISSUE THREAD

**Issue by simonwiles** [RaRe-Technologies/gensim#2998]
There is a shorthand written into the API for `KeyedVectors.most_similar()` that can result in confusion:

https://github.com/RaRe-Technologies/gensim/blob/a28a3e79f4c4cbd97106fc9b35034707295994cd/gensim/models/keyedvectors.py#L745-L747

I imagine this reduces more confusion than it causes, but it can cause the unexpected result that 
```python
model.mv.most_similar(positive="dog")
```
works as expected, but 
```python
model.wv.most_similar(negative="dog")
```
raises a potentially confusion exception.  While neither is "correct" according to the docs, this result can be unexpected (see https://twitter.com/quinnanya/status/1318398096041078784).

It seems like it would be straightforward to either accept a `KEY_TYPES` argument in *either* case, or to catch the error earlier and return a more helpful error message.

**Comment by simonwiles** [comment]
Would you accept a PR that simply adds
```python
 if isinstance(negative, KEY_TYPES) and not positive: 
     negative = [negative] 
```

(and changes comments appropriately)?

**Comment by gojomo** [comment]
Personally I'm not a fan of how much type-sensitive parameter-swizzling happens in `most_similar()` - I think it'd be more Pythonic to be more explicit, offer a few distinctly-named  entry-methods for the different common-cases (by key, by vector, by mix of vectors), and pull out the specific `positive` + `negative` mixing routine for separate use. (Separately, it might also offer parameters for when/whether unit-norming occurs, how missing-words are handled, etc.)

Another similar issue: supplying a single string-key works, but supplying a single vector doesn't - as the type-interrogation misinterprets that as an intended array-of-vectors.

Your suggestion does seem a low-risk way to improve the symmetry of the current behavior for people who (like in your highlighted tweet) intuit that it "should" work, so I would view such a PR favorably, subject to @piskvorky's opinion also.

**Comment by piskvorky** [comment]
I agree. Parameter overloading was a bad idea (by me), I wish I'd made the API more explicit, less "clever".

A PR will be welcome – as well as fixing that "single vector" input that @gojomo mentions if possible.
