### ISSUE TITLE
TypeError: cannot unpack non-iterable numpy.float32 object in gensim 3.8.3

### ISSUE THREAD

**Issue by soumonos** [RaRe-Technologies/gensim#3002]
I am using the gensim 3.8.3 implementation of gensim.models.doc2vec.Doc2Vec and even after seeing the issue already fixed and resolved I have encountered the same problem:

After training the model, I have passed a list of 2 words (present in the vocabulary) to find most similar doctags. 
vec= model.infer_vector(['culture', 'livre'])
model.docvecs.most_similar(positive= vec, topn= 10)[1:]
In the 1st line, the vector is correctly inferred with given vector size and after executing most_similar(), it throws: 

line 1725 in most_similar of keyedvector.py    
    for doc, weight in positive + negative:

TypeError: cannot unpack non-iterable numpy.float32 object

I have looked into solutions given in earlier posts but none of them seems to solve it. I shall be delighted to hear from the team about the issue. My python version is 3.8.5

**Comment by soumonos** [comment]
@Witiko It'd be really helpful if you'd please look into the issue.

**Comment by Witiko** [comment]
@soumonos You have to pass an array to [the `positive` parameter of `most_similar`](https://radimrehurek.com/gensim_3.8.3/models/keyedvectors.html#gensim.models.keyedvectors.Doc2VecKeyedVectors.most_similar), like this:

``` python
>>> from gensim.test.utils import common_texts
>>> from gensim.models.doc2vec import Doc2Vec, TaggedDocument
>>> 
>>> documents = [TaggedDocument(doc, [i]) for i, doc in enumerate(common_texts)]
>>> model = Doc2Vec(documents, vector_size=5, window=2, min_count=1, workers=4)
>>> vec = model.infer_vector(['culture', 'livre'])
>>> vec
array([ 0.05347068, -0.08420665,  0.04036214,  0.05470511, -0.06519038],
      dtype=float32)
>>> model.docvecs.most_similar(positive=[vec], topn=10)[1:]
[(1, 0.456624835729599), (7, 0.0926382839679718), (0, -0.022776544094085693), (2, -0.3210035562515259), (6, -0.32428452372550964), (3, -0.6623260974884033), (4, -0.7514891624450684), (5, -0.7817525267601013)]`
```

**Comment by soumonos** [comment]
Thank you. I passed the vector without a list declaration on it. Your fix works. Thank you so very much for this. With your consent, I can close the issue.

**Comment by Witiko** [comment]
@soumonos Of course, happy to help.
