### ISSUE TITLE
clarification on DM / DBOW in gensim corresponding to original implementation by Mikolov

### ISSUE THREAD

**Issue by jwijffels** [RaRe-Technologies/gensim#3010]
I'm presuming doc2vec is gensim is a variant of the original code at https://groups.google.com/g/word2vec-toolkit/c/Q49FIrNOQRo/m/J6KG8mUj45sJ namely https://03685169118318071335.googlegroups.com/attach/9be32365f286a227/word2vec.c?part=0.1&view=1&vt=ANaJVrGehlFBJs1M13VrxygRr6SeaBU66Nb7lJiHrohilyEFoIJFUdQON-sAIMJFaSHt9rxn7HfnbX64-w8W7f_LMk7Xi_u2cwrqg6zdune49gLT81uYWkw

- Does the Distributed Memory (DM) option you have in gensim correspond to training that original word2vec.c 'doc2vec' implementation to specifying cbow = 1 or to cbow = 0 or something else
- Does the Distributed Bag Of Words (DBOW) option you have in gensim  correspond to training that original word2vec.c 'doc2vec' implementation to specifying cbow = 1 or to cbow = 0 or something else

**Comment by piskvorky** [comment]
All parameters and their values match the original implementation 1:1.

Any divergences (if they exist) would be due to more recent development of the C implementation, which we do not track.

**Comment by jwijffels** [comment]
So does the distributed memory option in gensim correspond to specifying cbow = 1 or to cbow = 0 in the original implementation?

**Comment by piskvorky** [comment]
Enabling DM implies disabling CBOW AFAIR (so `0`); CC @gojomo .

**Comment by gojomo** [comment]
`dm=1` enables the "PV-DM" mode in the 'Distributed Representation of Sentences & Documents' paper, which is most-like `cbow`. 

`dm=0` enables the "PV-DBOW" mode, which is most like skip-gram. (If you add `dbow_words=1` to `dm=0`, then the doc-vector-only training will be interleaved with actual skip-gram word-training on the same corpus - a mode not explicitly described in the original paper, but used in the followup 'Document Embedding with Paragraph Vectors' paper.)
