### ISSUE TITLE
Update unittests to work with the newest version of scikit.learn

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#3016]

**Comment by mpenkov** [comment]
```
self = <gensim.test.test_sklearn_api.TestHdpTransformer testMethod=testPipeline>

    def testPipeline(self):
        with open(datapath('mini_newsgroup'), 'rb') as f:
            compressed_content = f.read()
            uncompressed_content = codecs.decode(compressed_content, 'zlib_codec')
>           cache = pickle.loads(uncompressed_content)
E           ModuleNotFoundError: No module named 'sklearn.datasets.base'
```

The `sklearn.datasets.base` submodule was deprecated in the latest version of scikit-learn.

**Comment by piskvorky** [comment]
Didn't we remove sklearn completely? What is that even doing here.

**Comment by mpenkov** [comment]
No, we haven't removed it yet.

https://github.com/RaRe-Technologies/gensim/blob/eff2faf0eca0da7ad41d20e17b5ef46c11874148/setup.py#L278

**Comment by piskvorky** [comment]
OK. Getting rid of it seems a more sensible action than fixing it. I'm pretty sure we have a ticket for that already, so closing here.
