### ISSUE TITLE
Gensim wrappers ldamallet is very slow when generating topics for unseen documents

### ISSUE THREAD

**Issue by ZhuohanX** [RaRe-Technologies/gensim#3018]
#### Problem description

Is there any way to accelerate generating topics for unseen documents using Gensim wrappers ldamallet model? I find it very slow compared to gensim.models.LdaMulticore model. And I would like to generate topics for 300k documents using ldamallet model.

I find the ldamallet model could boost the c_v performance of topic modelling from 0.46 to 0.58.

#### Steps/code/corpus to reproduce

mallet_model = LdaMallet(path_to_mallet_binary, corpus=bow_corpus, num_topics=47, id2word=dictionary)

#### Versions
Darwin-19.5.0-x86_64-i386-64bit
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)]
Bits 64
NumPy 1.17.2
SciPy 1.4.1
gensim 3.8.3
FAST_VERSION 0

**Comment by piskvorky** [comment]
How are you inferring the topics for the unseen documents? Can you share your code?

**Comment by ZhuohanX** [comment]
Hi,

Thank you for replying.

I use the following code to infer the topic distribution and use the maximum probability as the topic for the unseen document

distribution = mallet_model[dictionary.doc2bow(preprocess(unseen_document))]
topic_distribution = np.asarray([i for (_,i) in dis], dtype= np.float64).tolist()
topic = max(distribution,key=itemgetter(1))[0]

I find it generally took me around 4-5mins for 100 documents.

I have tried to use multiple cores to generate topics for my documents separately, but it seems it would easily get into the subprocess issues and seem not to be the best solutions. Therefore, I am wondering if there is a better solution to speed it up?

Thank you very much!

**Comment by piskvorky** [comment]
Can you submit multiple documents at once?

```python
distributions = mallet_model[[dictionary.doc2bow(preprocess(unseen_document)) for unseen_document in unseen_documents]
```

That way, you amortize the high cost of loading up Mallet *for each document*. Instead, you'll load it once, and then use it to infer all documents at once. Should be much faster.

Does that make sense?

**Comment by ZhuohanX** [comment]
Hi, 

I rewrote in this way. And it only took around 4 mins to get all distributions on my laptop...
I had no idea loading up Mallet could take so much time in the case..

thank you very much!

**Comment by piskvorky** [comment]
OK great! I'll close this but let me know if improving the docs somewhere would help you (and others) avoid this pitfall.
