### ISSUE TITLE
can not import ENGLISH_CONNECTOR_WORDS from gensim.models.phrases

### ISSUE THREAD

**Issue by syedarehaq** [RaRe-Technologies/gensim#3019]
#### Problem description
When I try to load the gensim ENGLISH_CONNECTOR_WORDS,  it seems to be missing in my current version. I am trying to use common stopwords in my Phrase detection training.

#### Steps/code/corpus to reproduce

Here is what I tried to do by following the [gensim Phrase Detection documnetation](https://radimrehurek.com/gensim/models/phrases.html).

```python
from gensim.models.phrases import Phrases, ENGLISH_CONNECTOR_WORDS
```
Here is the output:
```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-f038e2aaf034> in <module>
----> 1 from gensim.models.phrases import Phrases, ENGLISH_CONNECTOR_WORDS

ImportError: cannot import name 'ENGLISH_CONNECTOR_WORDS' from 'gensim.models.phrases' (/project/venv/lib/python3.9/site-packages/gensim/models/phrases.py)
```

#### Versions
```python
macOS-10.15.7-x86_64-i386-64bit
Python 3.9.0 (default, Oct 30 2020, 16:46:27) 
[Clang 12.0.0 (clang-1200.0.32.2)]
Bits 64
NumPy 1.19.4
SciPy 1.6.0
gensim 3.8.3
FAST_VERSION 0
```

**Comment by piskvorky** [comment]
Hi @syedarehaq – check the red banner on top of that documentation page. You're viewing documentation for Gensim 4.0.0, but using Gensim 3.8.3.

I recommend upgrading to 4.0.0 – phrases are much faster and also more stable:
https://github.com/RaRe-Technologies/gensim/releases/tag/4.0.0beta
