### ISSUE TITLE
Custom Keyword inclusion

### ISSUE THREAD

**Issue by Vignesh9395** [RaRe-Technologies/gensim#3025]
#### Problem description

Our need is the generated summary should have specific keywords from the input text.

#### Steps/code/corpus to reproduce

We need the summarize function to have accept keywords as input parameter.

output = summarize(text, word_count=9, **custom_keywords=keywords**)

**For example,**
```
from gensim.summarization.summarizer import summarize

keywords = ['apple', 'red', 'yellow']
text = "Apple is red. Grape is black. Banana is yellow"

output = summarize(text, word_count=9, custom_keywords=keywords)

print(output) 

```
#### Output

**Apple** is **red.** 
Banana is **yellow**

As in above example, we need a parameter to include custom keywords and those keywords must be present in the summarized text.
(i.e) The sentences with the keywords should be present in the output.

**Comment by piskvorky** [comment]
Thanks for the feature suggestion. We've phased out the summarization module from Gensim completely though, it's gone from Gensim 4.0.0: [release notes](https://github.com/RaRe-Technologies/gensim/releases/tag/4.0.0beta).

So if you wish to extend that module, you can fork the old Gensim code and work on it in a separate project, outside of Gensim.
