### ISSUE TITLE
text8 download is super slow

### ISSUE THREAD

**Issue by sezanzeb** [RaRe-Technologies/gensim#3027]
#### Problem description

I get ~40KB/sec for https://github.com/RaRe-Technologies/gensim-data/releases/download/text8/text8.gz

Could it be hosted on https://radimrehurek.com/gensim/ instead?

It's much faster today than a few days ago though.

#### Steps/code/corpus to reproduce

```
import gensim.downloader as api
docs = api.load('text8')
```

#### Versions

Linux-4.20.0-042000-generic-x86_64-with-glibc2.29
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
Bits 64
NumPy 1.17.4
SciPy 1.3.3
gensim 4.0.0.dev0
FAST_VERSION 1

**Comment by piskvorky** [comment]
I'm getting > 5MB/s:

<img width="1438" alt="Screen Shot 2021-01-16 at 12 56 00 1" src="https://user-images.githubusercontent.com/610412/104811180-2a6a9280-57fa-11eb-9b4a-624bcd120b58.png">

Maybe it's some local issue with your connection?

I cannot host large public files on my servers, sorry. Github has deeper pockets :)

**Comment by sezanzeb** [comment]
weird, my internet is fine otherwise, it's really just that file.

**Comment by piskvorky** [comment]
You could try tracing the route, see which point is the bottleneck between your computer and the github S3 storage.
