### ISSUE TITLE
keyword argument 'vector_size' not in Word2Vec

### ISSUE THREAD

**Issue by ma-ji** [RaRe-Technologies/gensim#3034]
```
Linux-4.15.0-106-generic-x86_64-with-debian-buster-sid
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0]
Bits 64
NumPy 1.19.2
SciPy 1.5.2
gensim 3.8.3
FAST_VERSION 1
```

Error:

```
----> 4 model = Word2Vec(sentences=docs, vector_size=200, min_count=5, workers=40)

TypeError: __init__() got an unexpected keyword argument 'vector_size'
```

**Comment by piskvorky** [comment]
Looks like you're using documentation for Gensim 4.0.0 but have Gensim 3.8.3 installed.

You can either:
1)  Upgrade Gensim to 4.0.0: https://github.com/RaRe-Technologies/gensim/releases/tag/4.0.0beta
2) or use the older documentation (click the big red banner on top): https://radimrehurek.com/gensim/
