### ISSUE TITLE
How does Gensim handling pad index and UNK index in W2V models? 

### ISSUE THREAD

**Issue by FullDataAlchemist** [RaRe-Technologies/gensim#3037]
I'm using Gensim for building W2V models and, I didn't find a way for adding a vector for Unkown words or padding parts in Gensim and, I have to do it manually.
I also check the index of 0 in the created embedding and, it is also used for a specific word. This matter could cause a problem for padding words because they have the same index.

Am I missing something in here? Is Gensim handle this problem?

P.S: For handling this issue, I always append two vectors in the model weights after I train the model.

**Comment by mpenkov** [comment]
Use the [Gensim mailing list](https://groups.google.com/forum/#!forum/gensim) to ask general or usage questions. Github issues are only for bug reports.
