### ISSUE TITLE
Understanding the topic significance of LDA

### ISSUE THREAD

**Issue by simon19891101** [RaRe-Technologies/gensim#3044]
#### Problem description

Hi there, I noticed that the print_topics() of LDA models says "Get the most significant topics" and "The number of topics to be selected, if -1 - all topics will be in result (ordered by significance)" in the documentation https://radimrehurek.com/gensim/models/ldamodel.html. However, I failed to identify the logic behind it. May I know what mechanisms are utilised to calculate the topic significance? Much appreciated :)

**Comment by piskvorky** [comment]
Hi, please follow the issue template regarding general questions and discussions.
