### ISSUE TITLE
Release 3.8.3: vector_size in docs doesn't match release constructor argument for word2vec and fasttext

### ISSUE THREAD

**Issue by hakunanatasha** [RaRe-Technologies/gensim#3051]
A fix seems to be currently in the develop branch, but the pypi release branch (release-3.8.3) [Word2Vec](https://github.com/RaRe-Technologies/gensim/blob/release-3.8.3/gensim/models/word2vec.py#L477) and [FastText](https://github.com/RaRe-Technologies/gensim/blob/release-3.8.3/gensim/models/fasttext.py#L355) files use 'size' as their constructor argument not 'vector_size'. [doc link here](https://radimrehurek.com/gensim/models/word2vec.html)

Marginally related, the  [developer's guide](https://github.com/RaRe-Technologies/gensim/wiki/Developer-page#git-flow) suggests the master branch head is the latest release, but it looks like release-3.8.3 is the one I would get from `pip install gensim` (note, the [master branch](https://github.com/RaRe-Technologies/gensim/blob/8624aa2822f885c56996f9a2f84490c9166c84ca/gensim/models/fasttext.py#L274) correctly uses vector_size).  

Minimal code to test:
```
from gensim.test.utils import common_texts
from gensim.models import Word2Vec

# this is currently on the doc website. Will fail for the pip install gensim version
model = Word2Vec(sentences=common_texts, vector_size=100, window=5, min_count=1, workers=4)

# Using 'size' instead will pass for the default release
model = Word2Vec(sentences=common_texts, size=100, window=5, min_count=1, workers=4)
```

In case it helps:
Linux-5.8.0-43-generic-x86_64-with-glibc2.29
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
Bits 64
NumPy 1.19.2
SciPy 1.4.1
gensim 3.8.3
FAST_VERSION 1

**Comment by piskvorky** [comment]
> Word2Vec and FastText files use 'size' as their constructor argument not 'vector_size'. [doc link here](https://radimrehurek.com/gensim/models/word2vec.html)

You can click the red banner on top of your documentation link, to get to the documentation for 3.8.3.
