### ISSUE TITLE
FastTextKeyedVectors' object has no attribute 'key_to_index'

### ISSUE THREAD

**Issue by Zast996** [RaRe-Technologies/gensim#3052]
#### Problem description

I am doing some tests on the [italian fasttext model](https://fasttext.cc/docs/en/crawl-vectors.html) using the gensim library on version 3.8.3.
I would like to see if a word is present in the model vocabulary, but it seems that the function is not recognized.

I am using a kaggle notebook and the code to reproduce the error is the following:

```python
from gensim.models.fasttext import load_facebook_model

mod = load_facebook_model('path_to_model/wiki.it.bin')
model = mod.wv
print('sviluppatore' in model.key_to_index)
```
error:

> FastTextKeyedVectors' object has no attribute 'key_to_index'

**Comment by piskvorky** [comment]
Why didn't you fill in the issue template? My guess is Gensim 3.8.3 vs 4.0.0.
