### ISSUE TITLE
Provide Python3.9 Wheels 

### ISSUE THREAD

**Issue by FredHappyface** [RaRe-Technologies/gensim#3056]
#### Problem description

I'm attempting to install this on Windows as it is a dependency for a program I wish to run however, to install from source Microsoft Visual C++ 14.0 is required. 

Would it be possible to provide wheels for this version? 

#### Steps/code/corpus to reproduce

do `pip install gensim` on Python3.9 Windows 10

```
Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/   
```

#### Versions

Windows-10-10.0.19041-SP0
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
Bits 64
NumPy 1.20.1
SciPy 1.6.1
gensim N/A (attempting to install 3.8.3)

Thanks

**Comment by mpenkov** [comment]
Related PR: https://github.com/RaRe-Technologies/gensim/pull/2966
