### ISSUE TITLE
Add +1 inside the math.log in the idf computation of bm25.

### ISSUE THREAD

**Issue by jeromebedard12** [RaRe-Technologies/gensim#3064]
https://github.com/RaRe-Technologies/gensim/blob/e889fa3d45a406cabbc7e180fa9a8ee3f76ac6f0/gensim/summarization/bm25.py#L137

As it is right now, you can end up with negative idf values. It's counter intuitive. The right formula for idf computation (from [https://en.wikipedia.org/wiki/Okapi_BM25]) is: 
![Screenshot from 2021-03-05 16-41-53](https://user-images.githubusercontent.com/48964470/110180235-63c18680-7dd7-11eb-9391-43bac72ca2ce.png)

You just need to add +1 inside the log.

Also, you won't need the warning in `if self.average_idf < 0:` anymore.

**Comment by mpenkov** [comment]
Are you interested in making a PR, with ~blackjack and hookers~ comments and unit tests?

**Comment by jeromebedard12** [comment]
Done

**Comment by Witiko** [comment]
Since `summarization.bm25` has been removed from Gensim 4, this issue can be closed.
