### ISSUE TITLE
How to compare the topic similarity between topics from two different Hdp Models?

### ISSUE THREAD

**Issue by yudhiesh** [RaRe-Technologies/gensim#3072]
#### Problem description

I am trying to compare the topic similarity between topics from two different Hdp Models. 
With LDA Models I have previously done so using the example below:
```
# lda_brand_last_week and lda_user_last_week are two LDA models 

topic_terms1 = sorted(lda_brand_last_week.show_topic_terms(0, topn=lda_brand_last_week.num_terms))
topic_terms2 = sorted(lda_user_last_week.show_topic_terms(0, topn=lda_user_last_week.num_terms))
gensim.matutils.hellinger(topic_terms1, topic_terms2)
```

When I try testing it out on Hdp Models with the same method I get this error:
```
AttributeError: 'HdpModel' object has no attribute 'show_topic_terms'
```
 I tried  checking the methods available and in fact it does not exist on the Hdp Model:
```
>>>[m for m in dir(lda_user_last_week) if not m.startswith('__')]
['_adapt_by_suffix',
 '_apply',
 '_load_specials',
 '_save_specials',
 '_smart_save',
 'chunksize',
 'corpus',
 'doc_e_step',
 'evaluate_test_corpus',
 'get_topics',
 'hdp_to_lda',
 'id2word',
 'inference',
 'lda_alpha',
 'lda_beta',
 'load',
 'm_D',
 'm_Elogbeta',
 'm_K',
 'm_T',
 'm_W',
 'm_alpha',
 'm_eta',
 'm_gamma',
 'm_kappa',
 'm_lambda',
 'm_lambda_sum',
 'm_num_docs_processed',
 'm_r',
 'm_rhot',
 'm_scale',
 'm_status_up_to_date',
 'm_tau',
 'm_timestamp',
 'm_updatect',
 'm_var_converge',
 'm_var_sticks',
 'm_varphi_ss',
 'max_chunks',
 'max_time',
 'optimal_ordering',
 'outputdir',
 'print_topic',
 'print_topics',
 'random_state',
 'save',
 'save_options',
 'save_topics',
 'show_topic',
 'show_topics',
 'suggested_lda_model',
 'update',
 'update_chunk',
 'update_expectations',
 'update_finished',
 'update_lambda']
```

But in the documentation this method `show_topic_terms` [exists](https://radimrehurek.com/gensim/models/hdpmodel.html#gensim.models.hdpmodel.HdpTopicFormatter.show_topic_terms).  

So how would I do this without using `show_topic_terms` to get the sequence of topic terms and their probabilities? 

#### Versions
Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
Python 3.7.10 (default, Feb 20 2021, 21:17:23) 
[GCC 7.5.0]
Bits 64
NumPy 1.19.5
SciPy 1.4.1
gensim 3.8.3
FAST_VERSION 1

**Comment by mpenkov** [comment]
Use the [Gensim mailing list](https://groups.google.com/forum/#!forum/gensim) to ask general or usage questions. Github issues are only for bug reports.
