### ISSUE TITLE
HPD random seed not working

### ISSUE THREAD

**Issue by evangeliazve** [RaRe-Technologies/gensim#3075]
#### Problem description

I am  trying to reproduce results using the same random seed (all other elements remain equal), but the results is different everytime I run the model.

#### Code

Here is my code :

```python
hdpmodel = HdpModel(corpus=bowCorpus, id2word=dictionary, alpha = 0.5, random_state = 1)
```

Is there any way to fix this on my side or it is a technical problem / missing developpement ?

Best Regards,
Evangelia ZVE

**Comment by piskvorky** [comment]
Hi Evangelia, unfortunately support for HDP had been discontinued in Gensim 4.0.0. The model had no maintainer, no one to answer user questions (like yours).

If you're interested, you can copy the HDP code from Gensim 3.8.3 and use / extend that. Best of luck!

**Comment by piskvorky** [comment]
Exactly. HDP saw little use, and no maintenance. We weren't comfortable keeping such code in Gensim, giving users false hope.

**Comment by evangeliazve** [comment]
Ok thank you pour the reply !
Appart from LDA is there any other gensim topic modeling algorithm that has active community and updates are regular?

**Comment by piskvorky** [comment]
If you take "topic modelling" to mean broadly "find relationships between words and documents using distributional semantics", then there's LDA, LSI, Random Projections, word2vec, doc2vec, fasttext…

If you mean specifically the latent Dirichlet architecture, then that's just LDA, AFAIR.

**Comment by evangeliazve** [comment]
I am looiking for a solution that clusters texts automatically. I know LDA does the job. But for the other ones, I have to build it on my side. 
From your exeprience what is the LSI advantage ? From what I know LSI has a similar usage.
