### ISSUE TITLE
Handle migration away from travis-ci.org

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#3083]
They are expecting projects to migrate from travis-ci.org to travis-ci.com. It looks like a free process for open-source projects.

We should consider whether to continue using Travis (and move to travis-ci.com) or use the opportunity to migrate everything possible to GitHub Actions.

We probably can't leave Travis entirely, because they support some platforms that GHA does not (IIRC).

**Comment by piskvorky** [comment]
Really? What are we using Travis for now?
I thought it was already gone entirely.

**Comment by mpenkov** [comment]
Right now the gensim-wheels repo is entirely Travis-backed. I'd have to search through past discussions to find the cases that Travis covers that GHA doesn't.

**Comment by mpenkov** [comment]
https://github.com/RaRe-Technologies/gensim-wheels

**Comment by mpenkov** [comment]
@piskvorky Can you please perform the migration process detailed [here](https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#migrating-a-repository)? The organization owner for RaRe-Technologies needs to do it.

**Comment by piskvorky** [comment]
The authentication / migration was a mess. I *think* I did all the steps, working around various errors and inconsistencies in the documentation.

In the end I manage to migrate: https://travis-ci.com/github/RaRe-Technologies/gensim/settings

<img width="1295" alt="Screen Shot 2021-03-28 at 10 40 46" src="https://user-images.githubusercontent.com/610412/112746876-34570180-8fb2-11eb-8470-ba9020a6986a.png">

Is that it, do you need anything else?

**Comment by mpenkov** [comment]
Thanks @piskvorky, that looks sufficient.

@janaknat We migrated to .com, but there are still problems. Can you please have a look?

https://travis-ci.com/github/RaRe-Technologies/gensim/jobs/494302890

**Comment by piskvorky** [comment]
Hm, is this experimentation happening over the main branch? Visible to all visitors?

<img width="947" alt="Screen Shot 2021-03-28 at 12 42 15" src="https://user-images.githubusercontent.com/610412/112749533-1f369e80-8fc3-11eb-82db-801102b69ea9.png">

**Comment by mpenkov** [comment]
OK, I will disable the build on the develop branch while we work this out.

My expectation was that the build pass (because of the previous history of the PR), but it appears there's still some work to be done.

**Comment by mpenkov** [comment]
The migration is complete, so I'm closing this ticket. @janaknat and I will deal with the failing Travis build in a separate ticket.
