### ISSUE TITLE
Release 4.0.0

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#3086]
- [x] Update CHANGELOG.md (@piskvorky)
- [x] Build wheels, release to PyPI (@mpenkov)
- [x] Champagne and cigars (everyone)

**Comment by mpenkov** [comment]
@piskvorky Please let me know when the change log is in the shape we want it to be for the final release. Once that's done, it'll take a few hours to get the wheels built and finalize the release.

**Comment by piskvorky** [comment]
Only the champagne & cigar left :)

Great job @mpenkov!

How did the latest release go, relative to 3.8.3, 4.0.0beta and 4.0.0rc1?

**Comment by piskvorky** [comment]
I see the last two steps from the release plan are missing: https://github.com/RaRe-Technologies/gensim/wiki/Developer-page#update-gensim-version-to-report-the-next-release

Should I do update `setup.py` (an omission), or did you have other plans, still in progress?

**Comment by mpenkov** [comment]
About the same as RC1 (everything built on the first attempt, very little intervention). Slightly better than the beta, and miles ahead of 3.8.3.

Yes, please update setup.py - I missed that step.

**Comment by piskvorky** [comment]
That's good to hear.

Closing here – big thanks to you and @gojomo for getting 4.0.0 through. It was a major cleanup of accumulated mess, much needed.

Smoother sailing from here on :)
