### ISSUE TITLE
randomness array in each execusion using gensim 4.0.0 r

### ISSUE THREAD

**Issue by nnadine25** [RaRe-Technologies/gensim#3093]
hi,

i have the problem of random values of the wor2vec numpy array in each iteration i have differents values and the values look like this

[-8.2428008e-03  9.2994776e-03 -1.9798672e-04 -1.9678262e-03
  4.6040486e-03 -4.0951525e-03  2.7427832e-03  6.9398358e-03
  6.0658492e-03 -7.5107692e-03  9.3822163e-03  4.6720100e-03
  3.9662290e-03 -6.2438129e-03  8.4602311e-03 -2.1501693e-03
  8.8252556e-03 -5.3621214e-03 -8.1291245e-03  6.8251640e-03
  1.6709357e-03 -2.1988999e-03  9.5134163e-03  9.4941529e-03
 -9.7744269e-03  2.5053187e-03  6.1569042e-03  3.8723361e-03
  2.0231656e-03  4.3065284e-04  6.7393208e-04 -3.8206491e-03
 -7.1407887e-03 -2.0886613e-03  3.9240932e-03  8.8188900e-03
  9.2590870e-03 -5.9758825e-03 -9.4028115e-03  9.7647989e-03
  3.4301477e-03  5.1660105e-03  6.2828050e-03 -2.8041711e-03
  7.3227654e-03  2.8304099e-03  2.8714100e-03 -2.3807921e-03
 -3.1285468e-03 -2.3705100e-03  4.2769113e-03  7.5900040e-05
 -9.5843915e-03 -9.6656363e-03 -6.1486219e-03 -1.2847317e-04
  1.9973496e-03  9.4323577e-03  5.5845254e-03 -4.2911354e-03
  2.7836411e-04  4.9645100e-03  7.6985597e-03 -1.1440248e-03
  4.3236283e-03 -5.8146389e-03 -8.0403656e-04  8.0998391e-03
 -2.3598999e-03 -9.6636890e-03  5.7792189e-03 -3.9302204e-03
 -1.2229439e-03  9.9810045e-03 -2.2564454e-03 -4.7571408e-03
 -5.3297863e-03  6.9811749e-03 -5.7088151e-03  2.1141327e-03
 -5.2556521e-03  6.1207935e-03  4.3572038e-03  2.6060962e-03
 -1.4909664e-03 -2.7461778e-03  8.9928163e-03  5.2160276e-03
 -2.1625054e-03 -9.4707683e-03 -7.4262242e-03 -1.0637412e-03
 -7.9504057e-04 -2.5630123e-03  9.6824588e-03 -4.5879601e-04
  5.8742040e-03 -7.4474830e-03 -2.5062521e-03 -5.5501163e-03]

**Comment by piskvorky** [comment]
Hi, please see the FAQ and the issue template you deleted..

**Comment by nnadine25** [comment]
can you give me the link
