### ISSUE TITLE
Getting CalledProcessError while getting each document topic probability from LdaMallet model

### ISSUE THREAD

**Issue by BaljinderSmagh** [RaRe-Technologies/gensim#3102]
#### Problem description

What are you trying to achieve? What is the expected result? What are you seeing instead?

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

If your problem is with a specific Gensim model (word2vec, lsimodel, doc2vec, fasttext, ldamodel etc), include the following:

```python
print(my_model.lifecycle_events)
```

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0]
import struct; print("Bits", 8 * struct.calcsize("P"))
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__) 
3.8.3
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```
os.environ['MALLET_HOME']='/home/b/bks46/covid_misinfo/Task2_with_LDA_Mallet/mallet-2.0.8' 

mallet_path = '/home/b/bks46/covid_misinfo/Task2_with_LDA_Mallet/mallet-2.0.8/bin/mallet'

ldamallet = gensim.models.wrappers.LdaMallet.load('/home/b/bks46/covid_misinfo/Task2_with_LDA_Mallet/lda_mallet/lda_mallet.model')
dictionary=gensim.corpora.Dictionary.load('/home/b/bks46/covid_misinfo/Task2_with_LDA_Mallet/lda_mallet/dictionary.dict')

doc_term_matrix=[dictionary.doc2bow(tokens) for tokens in task1_dataset['processed_text']]
topic_prob=ldamallet[doc_term_matrix]

CalledProcessError                        Traceback (most recent call last)
<ipython-input-17-24bf1b3b5c38> in <module>
----> 1 topic_prob=ldamallet[doc_term_matrix]

~/anaconda3/lib/python3.7/site-packages/gensim/models/wrappers/ldamallet.py in __getitem__(self, bow, iterations)
    312             bow = [bow]
    313 
--> 314         self.convert_input(bow, infer=True)
    315         cmd = \
    316             self.mallet_path + ' infer-topics --input %s --inferencer %s ' \

~/anaconda3/lib/python3.7/site-packages/gensim/models/wrappers/ldamallet.py in convert_input(self, corpus, infer, serialize_corpus)
    259             cmd = cmd % (self.fcorpustxt(), self.fcorpusmallet())
    260         logger.info("converting temporary corpus to MALLET format with %s", cmd)
--> 261         check_output(args=cmd, shell=True)
    262 
    263     def train(self, corpus):

~/anaconda3/lib/python3.7/site-packages/gensim/utils.py in check_output(stdout, *popenargs, **kwargs)
   1930             error = subprocess.CalledProcessError(retcode, cmd)
   1931             error.output = output
-> 1932             raise error
   1933         return output
   1934     except KeyboardInterrupt:

CalledProcessError: Command '/home/b/bks46/covid_misinfo/Task2_with_LDA_Mallet/mallet-2.0.8/bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex "\S+" --input /scratch/6699dc_corpus.txt --output /scratch/6699dc_corpus.mallet.infer --use-pipe-from /scratch/6699dc_corpus.mallet' returned non-zero exit status 1.

**Comment by piskvorky** [comment]
Ticket not intelligible. Please fill in the template and try again if you want help.

**Comment by BaljinderSmagh** [comment]
I have updated the template, can you please check the issue?

**Comment by piskvorky** [comment]
Thanks for filling in the template. We removed Mallet from Gensim, so it's no longer supported.

But if you want to continue using it (via older versions of Gensim), you can. From the error you shared, I'd try running the same command from the command line, to see why / with what error Mallet failed. But unfortunately we cannot support Mallet tickets any more.

**Comment by BaljinderSmagh** [comment]
Hi RaRe-Technologies/gensim,

Can you help me in knowing the date at which the mallet model was removed
as I was using this model in my research project.It will be really helpful.

Thanks & Regards
[image: NJIT logo] <https://www.njit.edu/> *Baljinder K Smagh*


***@***.***

**Comment by piskvorky** [comment]
Mallet was removed in Gensim 4.0. So you'll need to use Gensim < 4.0.

**Comment by BaljinderSmagh** [comment]
if you check my template , I am using the gensim 3.8.3 still getting this
error.

[image: NJIT logo] <https://www.njit.edu/> *Baljinder K Smagh*


***@***.***
