### ISSUE TITLE
cannot import name 'softcossim' from 'gensim.matutils'

### ISSUE THREAD

**Issue by plauthor** [RaRe-Technologies/gensim#3109]
I get the following error when trying to running a tutorial script. First I attempted to upgrade gensim:

pip3 install --upgrade gensim
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: gensim in ./.local/lib/python3.7/site-packages (4.0.1)
Requirement already satisfied: smart-open>=1.8.1 in ./.local/lib/python3.7/site-packages (from gensim) (5.0.0)
Requirement already satisfied: scipy>=0.18.1 in /usr/lib/python3/dist-packages (from gensim) (1.1.0)
Requirement already satisfied: numpy>=1.11.3 in ./.local/lib/python3.7/site-packages (from gensim) (1.20.1)

Then attempted to run the script:

python3 kosinus.py
Traceback (most recent call last):
  File "kosinus.py", line 7, in <module>
    from gensim.matutils import softcossim 
ImportError: cannot import name 'softcossim' from 'gensim.matutils' (/home/user1/.local/lib/python3.7/site-packages/gensim/matutils.py)

python3 -m kosinus
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user1/kosinus.py", line 7, in <module>
    from gensim.matutils import softcossim 
ImportError: cannot import name 'softcossim' from 'gensim.matutils' (/home/user1/.local/lib/python3.7/site-packages/gensim/matutils.py)

This is the script in question:

#!/usr/bin/python3
# -*- coding: utf-8 -*-

# upgrade gensim if you can't import softcossim

from gensim import corpora
from gensim.matutils import softcossim 
from gensim.utils import simple_preprocess
from sklearn.feature_extraction.text import CountVectorizer # nebo TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import gensim
import gensim.downloader as api
import numpy as np
import pandas as pd

print(gensim.__version__)

# Download the FastText model
fasttext_model300 = api.load('fasttext-wiki-news-subwords-300')

# Define the documents
doc_trump = "Mr. Trump became president after winning the political election. Though he lost the support of some republican friends, Trump is friends with President Putin"

doc_election = "President Trump says Putin had no political interference is the election outcome. He says it was a witchhunt by political parties. He claimed President Putin is a friend who had nothing to do with the election"

doc_putin = "Post elections, Vladimir Putin became President of Russia. President Putin had served as the Prime Minister earlier in his political career"

doc_soup = "Soup is a primarily liquid food, generally served warm or hot (but may be cool or cold), that is made by combining ingredients of meat or vegetables with stock, juice, water, or another liquid. "

doc_noodles = "Noodles are a staple food in many cultures. They are made from unleavened dough which is stretched, extruded, or rolled flat and cut into one of a variety of shapes."

doc_dosa = "Dosa is a type of pancake from the Indian subcontinent, made from a fermented batter. It is somewhat similar to a crepe in appearance. Its main ingredients are rice and black gram."

documents = [doc_trump, doc_election, doc_putin]

# Create the Document Term Matrix
count_vectorizer = CountVectorizer(stop_words='english')
sparse_matrix = count_vectorizer.fit_transform(documents)

# OPTIONAL: Convert Sparse Matrix to Pandas Dataframe if you want to see the word frequencies.
doc_term_matrix = sparse_matrix.todense()
df = pd.DataFrame(doc_term_matrix, 
                  columns=count_vectorizer.get_feature_names(), 
                  index=['doc_trump', 'doc_election', 'doc_putin'])

#df

# Compute Cosine Similarity
#print(cosine_similarity(df, df))
#> [[ 1.          0.48927489  0.37139068]
#>  [ 0.48927489  1.          0.38829014]
#>  [ 0.37139068  0.38829014  1.        ]]

################ soft kosinus

documents = [doc_trump, doc_election, doc_putin, doc_soup, doc_noodles, doc_dosa]

# Prepare a dictionary and a corpus.
dictionary = corpora.Dictionary([simple_preprocess(doc) for doc in documents])

# Prepare the similarity matrix
similarity_matrix = fasttext_model300.similarity_matrix(dictionary, tfidf=None, threshold=0.0, exponent=2.0, nonzero_limit=100)

# Convert the sentences into bag-of-words vectors.
sent_1 = dictionary.doc2bow(simple_preprocess(doc_trump))
sent_2 = dictionary.doc2bow(simple_preprocess(doc_election))
sent_3 = dictionary.doc2bow(simple_preprocess(doc_putin))
sent_4 = dictionary.doc2bow(simple_preprocess(doc_soup))
sent_5 = dictionary.doc2bow(simple_preprocess(doc_noodles))
sent_6 = dictionary.doc2bow(simple_preprocess(doc_dosa))

sentences = [sent_1, sent_2, sent_3, sent_4, sent_5, sent_6]

# Compute soft cosine similarity
#print(softcossim(sent_1, sent_2, similarity_matrix))
#> 0.567228632589

def create_soft_cossim_matrix(sentences):
    len_array = np.arange(len(sentences))
    xx, yy = np.meshgrid(len_array, len_array)
    cossim_mat = pd.DataFrame([[round(softcossim(sentences[i],sentences[j], similarity_matrix) ,2) for i, j in zip(x,y)] for y, x in zip(xx, yy)])
    return cossim_mat

#create_soft_cossim_matrix(sentences)

Would anyone happen to have any idea of what might be wrong please. Thank you very much in advance.

**Comment by piskvorky** [comment]
There is indeed no `softcossim` in `gensim.matutils`, so the error is expected.

@Witiko was there ever `softcossim` there? Do you know what this might be about?

**Comment by Witiko** [comment]
The `softcossim` method has been deprecated in favor of `inner_product` and removed in Gensim 4.0.0. Please, see [our up-to-date tutorial](https://radimrehurek.com/gensim/auto_examples/tutorials/run_scm.html).

**Comment by plauthor** [comment]
The code comes from https://www.machinelearningplus.com/nlp/cosine-similarity/

Thank you.

**Comment by abu-rayyan** [comment]
I uninstalled the gensim using `pip uninstall gensim` and reinstalled using conda: `conda install -c anaconda gensim` and it worked!

**Comment by plauthor** [comment]
Thank you.

**Comment by mpenkov** [comment]
> I uninstalled the gensim using pip uninstall gensim and reinstalled using conda: conda install -c anaconda gensim and it worked!

`pip install gensim==3.8.3` would have also "worked"
