### ISSUE TITLE
No module named 'gensim.summarization'

### ISSUE THREAD

**Issue by jay2017-git** [RaRe-Technologies/gensim#3112]
i'm using gensim version 4.0

from gensim.summarization.bm25 import BM25

How do I implement BM25 or summarization using Genism.

**Comment by piskvorky** [comment]
Gensim 4 removed summarization altogether. See https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4#12-removed-gensimsummarization.
