### ISSUE TITLE
Link in documentation Removed

### ISSUE THREAD

**Issue by uomodellamansarda** [RaRe-Technologies/gensim#3122]
The tutorial in the link inside the documentation for doc2vec  [here](https://radimrehurek.com/gensim/models/doc2vec.html#gensim.models.doc2vec.LabeledSentence) redirect to GitHub, but in that page the tutorial was removed. 

[here](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/doc2vec-lee.ipynb)

Best, 
Andrea

**Comment by piskvorky** [comment]
Thanks – can you open a PR, to update the link?

**Comment by AdityaSoni19031997** [comment]
Ahh, I can send the PR but i am not able to figure out where exactly i should change that URL? Thanks;
