### ISSUE TITLE
Phrases model's saved connector_words not getting loaded, while loading saved phrases model

### ISSUE THREAD

**Issue by aloknturing** [RaRe-Technologies/gensim#3124]
#### If we have saved the trained phrases model in this version i.e gensim version 4.0.0 or 4.0.1, while giving non empty connector_words. And If we try to load the saved model in this version itself. Then the connector_words of the loaded phrases model will be wrongly assigned empty frozen set. This is a functional bug and will result in some of the words not getting grouped in ngram

PR has been sent for this bug here: https://github.com/RaRe-Technologies/gensim/pull/3116

What are you trying to achieve? What is the expected result? What are you seeing instead?

I am trying to save and load a phrases model with non empty connector words after freezing it.
Expectation is that connector_words won't become empty after loading it after saving it.
But they become empty
#### Steps/code/corpus to reproduce

Go to this PR: https://github.com/RaRe-Technologies/gensim/pull/3116
Go to this commit where test has been added: https://github.com/RaRe-Technologies/gensim/pull/3116/commits/49dfe1b56a6a2f16a85af374e69d2f78917c0ff3
This test will reproduce the bug

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import struct; print("Bits", 8 * struct.calcsize("P"))
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

Linux-5.4.0-72-generic-x86_64-with-debian-buster-sid
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]
Bits 64
NumPy 1.19.4
SciPy 1.3.0
gensim 4.0.1
FAST_VERSION 1

**Comment by piskvorky** [comment]
I don't understand. Are you reporting an issue that already has a fix submitted? Or did you find some problem with the fix?

**Comment by aloknturing** [comment]
Yes I am trying to report this issue whose PR fix was submitted. In the guidelines its mentioned that issue needs to be raised before sending PR

**Comment by aloknturing** [comment]
Let me delete it. I think its not required

**Comment by piskvorky** [comment]
Yeah I don't think this adds anything here.

"Issue before PR" makes sense for a discussion whether something is a bug, and what the solution should be. We're past that stage now.
