### ISSUE TITLE
NameError: name 'Nmf' is not defined

### ISSUE THREAD

**Issue by TheCidRMC** [RaRe-Technologies/gensim#3130]
#### Problem description

Trying to run NMF using gensim, but it doesn't work.

#### Steps/code/corpus to reproduce

I tried to run what documentation suggests:

```python
from gensim.test.utils import common_texts
from gensim.corpora.dictionary import Dictionary

# Create a corpus from a list of texts
common_dictionary = Dictionary(common_texts)
common_corpus = [common_dictionary.doc2bow(text) for text in common_texts]

# Train the model on the corpus.
nmf = Nmf(common_corpus, num_topics=10)
```
but it throws the error in subject. 

I tried to inspect the package and it seems it's not installed or doesn't exist. I don't understand why.

#### Versions

gensim 3.8.3

**Comment by mpenkov** [comment]
You're not importing the Nmf class anywhere.

What documentation are you getting this from?

**Comment by TheCidRMC** [comment]
Hey there, I was looking at 

https://radimrehurek.com/gensim_3.8.3/models/nmf.html

**Comment by piskvorky** [comment]
Thanks for reporting. NMF is a contributed module, sorry about this.

@TheCidRMC can you open a PR fixing the docs? The solution is of course to import `Nmf` first.

**Comment by properGrammar** [comment]
I've submitted a PR for this, @piskvorky: [https://github.com/RaRe-Technologies/gensim/pull/3131](url)
