### ISSUE TITLE
Fix documentation link to mycorpus.txt download

### ISSUE THREAD

**Issue by rohit901** [RaRe-Technologies/gensim#3144]
#### Problem description

Trying to reproduce Corpora and Vector Space tutorial given in the documentation, but the link to download txt file is not working. The link given in the tutorial [here](https://radimrehurek.com/gensim/auto_examples/core/run_corpora_and_vector_spaces.html#corpus-streaming-one-document-at-a-time) is giving 404 error.

#### Steps/code/corpus to reproduce

Just visit this [link](https://radimrehurek.com/gensim/mycorpus.txt) which is used in the code given in the documentation, it is not working.

**Comment by piskvorky** [comment]
You're right, the link should be https://radimrehurek.com/mycorpus.txt.

@rohit901 Can you open a PR with a fix? Thanks.

**Comment by rohit901** [comment]
done, please check.
