### ISSUE TITLE
Fix FastText documentation to reflect changed parameter names

### ISSUE THREAD

**Issue by jvahl** [RaRe-Technologies/gensim#3151]
The docstring of `gensim.models.fasttext.FastText` says:

> size (int, optional) – Dimensionality of the word vectors.

Should be changed to:

> **vector_size** (int, optional) – Dimensionality of the word vectors.

**Comment by mpenkov** [comment]
Thank you. Are you interested in making a PR?

**Comment by Cyclopstark** [comment]
@mpenkov I would love to make a PR on this.

**Comment by Ansh-Sarkar** [comment]
@mpenkov I would love to work on this and create a PR for the same.
