### ISSUE TITLE
doc2vec's infer_vector has `epochs` and `steps` input parameters - `steps` not in use

### ISSUE THREAD

**Issue by gohjunlin** [RaRe-Technologies/gensim#3158]
Refer to doc2vec.py, `infer_vector` function seems to be using `epochs` for the number of iterations and `steps` is not in used.

However, in the `similarity_unseen_docs` function, `steps` is used when calling the infer_vector function.

![image](https://user-images.githubusercontent.com/62754326/119926239-9085d400-bfa9-11eb-838b-dae98da26c3f.png)

**Comment by gojomo** [comment]
Yes, that's broken - `steps` is the older name for that parameter, & pre-4.0 would be accepted & copied into `epochs`. It looks like it's now just ignored by `infer_vector()`, thus this caller thinks it's doing the right thing, but isn't. The fix will be to:

* eliminate `steps` entirely from the signature of `infer_vector()` (as was intended)
* correct `similarity_unseen_docs()` to use `epochs`
