### ISSUE TITLE
Issue importing gensim utils package 

### ISSUE THREAD

**Issue by cjfarnold** [RaRe-Technologies/gensim#3175]
I am getting the following error while importing gensim utils package below is the error

 File "C:\ProgramData\Anaconda3\lib\site-packages\gensim\parsing\preprocessing.py", line 26, in <module>
    from gensim import utils

  File "C:\ProgramData\Anaconda3\lib\site-packages\gensim\utils.py", line 62, in <module>
    default_prng = np.random.default_rng()

AttributeError: module 'numpy.random' has no attribute 'default_rng'

This is the environment details of my setup:
Windows-10-10.0.19041-SP0
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
Bits 64
NumPy 1.16.5
SciPy 1.2.1

**Comment by piskvorky** [comment]
Gensim requires numpy >= 1.17, as per https://github.com/RaRe-Technologies/gensim/blob/develop/setup.py#L318.

Not sure how you installed Gensim, but you could let the maintainer of your packaging system know something's wrong with their packaging.
