### ISSUE TITLE
Incompatible types of unicode strings in `gensim.similarities.fastss.editdist`

### ISSUE THREAD

**Issue by Witiko** [RaRe-Technologies/gensim#3177]
#### Problem description

In #3146, a new algorithm for fast Levenshtein distance computation has been added. However, the algorithm currently cannot cope with different internal representations of Unicode strings, resulting in cryptic errors:

#### Steps/code/corpus to reproduce

``` python
$ pip install git+https://github.com/RaRe-Technologies/gensim.git@develop
$ python3
>>> from gensim.similarities.fastss import editdist
>>>
>>> editdist('Žižka', 'šiška')
2
>>> editdist('Žižka', 'Zizka')
gensim/similarities/fastss.pyx in gensim.similarities.fastss.editdist()

ValueError: incompatible types of unicode strings
```

#### Suggested patch

See #3178.

#### Versions

```python
>>> import platform; print(platform.platform())
Linux-4.15.0-108-generic-x86_64-with-glibc2.10
>>> import sys; print("Python", sys.version)
Python 3.8.3 (default, Jul  2 2020, 16:21:59) 
[GCC 7.3.0]
>>> import struct; print("Bits", 8 * struct.calcsize("P"))
Bits 64
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.20.3
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.6.3
>>> import gensim; print("gensim", gensim.__version__)
gensim 4.1.0.dev0
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 1
```

**Comment by piskvorky** [comment]
+1 on the patch. I thought this "kind" value was constant across a Python installation (some compile-time setting). But apparently I was wrong, sorry.

**Comment by Witiko** [comment]
It's surprising to me as well. Apparently, Cython uses a single byte per a character for ASCII strings, whereas it uses wider characters for non-ASCII Unicode strings: https://stackoverflow.com/a/46289090/657401

**Comment by Witiko** [comment]
I have tested the patch and created a pull request for it in #3178.
