### ISSUE TITLE
how to use FastTextKeyedVectors.load_word2vec_format 

### ISSUE THREAD

**Issue by wqh17101** [RaRe-Technologies/gensim#3187]
#### Problem description

error to use FastTextKeyedVectors.load_word2vec_format to load word vector.

#### Steps/code/corpus to reproduce

Hi, i train a fasttext model and save wv by
```
model.wv.save_word2vec_format("./test.vec", binary=False)
```
when i use 
```
FastTextKeyedVectors.load_word2vec_format("./test.vec")
```
i get 
![image](https://user-images.githubusercontent.com/26429138/124581702-e771a980-de83-11eb-98e8-8382fc920416.png)
i don`t know how to make it work

However, this can load
```
KeyedVectors.load_word2vec_format("./test.vec")
```
but can not work with OOV problem,which is the most important feature of Fasttext

#### Versions

Please provide the output of:

```python
Windows-10-10.0.19041-SP0
Python 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
Bits 64
NumPy 1.21.0
SciPy 1.6.2
gensim 4.0.1
FAST_VERSION 1
```

**Comment by mpenkov** [comment]
Please direct questions like this at the mailing list. Github tickets are for bug reports only.
