### ISSUE TITLE
cannot import name 'nmf' from 'gensim.models'

### ISSUE THREAD

**Issue by silviatti** [RaRe-Technologies/gensim#3189]
#### Problem description
Hi!
When I try to import NMF from gensim (version 3.6.0) using colab, I get an ImportError exception. It seems to happen on colab and not on Windows. And it doesn't happen if I use version 3.8.0. 

#### Steps/code/corpus to reproduce

```python
from gensim.models import nmf
```

I get this error:
```python
ImportError: cannot import name 'nmf' from 'gensim.models' (/usr/local/lib/python3.7/dist-packages/gensim/models/__init__.py)
```

#### Versions

```
Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
Python 3.7.10 (default, May  3 2021, 02:48:31) 
[GCC 7.5.0]
Bits 64
NumPy 1.19.5
SciPy 1.4.1
gensim 3.6.0
FAST_VERSION 1
```

**Comment by piskvorky** [comment]
NMF probably wasn't there in 3.6.0? That release is 3 years old.

Please use a recent release, ideally 4.0.0+.
