### ISSUE TITLE
mallet falls asleep

### ISSUE THREAD

**Issue by nako21** [RaRe-Technologies/gensim#3204]
i'm using mallet-2.0.8 with Python 3 and Jupyter Notebook. Recently it worked just fine. But now it falls asleep while showing it's still working even with a small dataset. 
The problem is with following function:
def compute_coherence_values(dictionary, corpus, texts, limit, start=2, step=1):
    """
    Compute c_v coherence for various number of topics
    Parameters:
    ----------
    dictionary : Gensim dictionary
    corpus : Gensim corpus
    texts : List of input texts
    limit : Max num of topics
    Returns:
    -------
    model_list : List of LDA topic models
    coherence_values : Coherence values corresponding to the LDA model with respective number of topics
    """
    coherence_values = []
    model_list = []
    for num_topics in range(start, limit, step):
        model = gensim.models.wrappers.LdaMallet(mallet_path, corpus=corpus, num_topics=num_topics, id2word=id2word)
        model_list.append(model)
        coherencemodel = CoherenceModel(model=model, texts=texts, dictionary=dictionary, coherence='c_v')
        coherence_values.append(coherencemodel.get_coherence())
    return model_list, coherence_values

**Comment by piskvorky** [comment]
Hi, sorry, we removed Mallet from Gensim in Gensim release 4.0 and no longer support it.
