### ISSUE TITLE
Continue training existing fasttext model on multicore

### ISSUE THREAD

**Issue by bwang482** [RaRe-Technologies/gensim#3205]
Is it possible to specify `workers` when continue training an existing fasttext model?

```
from gensim.models.fasttext import FastText
model = api.load("fasttext-wiki-news-subwords-300")
model.build_vocab(sentences, update=True)
total_words = model.corpus_total_words
model.train(sentences, total_examples=len(sentences), total_words=total_words, epochs=model.epochs)
```

It doesn't seem I can change the parameter of this existing model. Any advice would be much appreciated! Thanks!

**Comment by piskvorky** [comment]
Please use the mailing list for questions (its link was in the issue template).
