### ISSUE TITLE
has anyone tried changing this codes to inverted dirchlet instead of just dirchlet?

### ISSUE THREAD

**Issue by iamnothingCC** [RaRe-Technologies/gensim#3207]
would like to ask if has anyone tried changing this codes to inverted dirchlet instead of just dirchlet?
[dirichlet_expectation.txt](https://github.com/RaRe-Technologies/gensim/files/6910689/dirichlet_expectation.txt)
[update_dir_prior.txt](https://github.com/RaRe-Technologies/gensim/files/6910690/update_dir_prior.txt)

**Comment by piskvorky** [comment]
Please follow the issue template.
