### ISSUE TITLE
NameError: name 'Similarity' is not defined

### ISSUE THREAD

**Issue by km5ar** [RaRe-Technologies/gensim#3211]
#### Problem description

What are you trying to achieve? What is the expected result? What are you seeing instead?
1) I'm trying to use Similarity from the offcial document
2) but it shows the NameError: name 'Similarity' is not defined
3) I used the latest version of genism 4.0.1
<img width="1114" alt="WeChat6b985efad4404452e7652c9a65ae08cd" src="https://user-images.githubusercontent.com/54015474/128584699-c3a34e18-491b-47cd-b0af-8b7210b0a95a.png">

#### Steps/code/corpus to reproduce
`from gensim.test.utils import common_corpus, common_dictionary, get_tmpfile

index_tmpfile = get_tmpfile("index")
query = [(1, 2), (6, 1), (7, 2)]

index = Similarity(index_tmpfile, common_corpus, num_features=len(common_dictionary))  # build the index
similarities = index[query]`

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

If your problem is with a specific Gensim model (word2vec, lsimodel, doc2vec, fasttext, ldamodel etc), include the following:

```python
print(my_model.lifecycle_events)
```

#### Versions

Please provide the output of:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-17-027d9974da56> in <module>
      4 query = [(1, 2), (6, 1), (7, 2)]
      5 
----> 6 index = Similarity(index_tmpfile, common_corpus, num_features=len(common_dictionary))  # build the index
      7 similarities = index[query]

NameError: name 'Similarity' is not defined

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import struct; print("Bits", 8 * struct.calcsize("P"))
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

macOS-10.16-x86_64-i386-64bit
Python 3.8.8 (default, Apr 13 2021, 12:59:45) 
[Clang 10.0.0 ]
Bits 64
NumPy 1.21.1
SciPy 1.7.0
gensim 4.0.1
FAST_VERSION 1

**Comment by km5ar** [comment]
`from gensim.similarities import Similarity` solved the problem

Please add this line to the official tutorial

**Comment by piskvorky** [comment]
Which tutorial are you talking about?

Added a comment into the Python `docsim` module in https://github.com/RaRe-Technologies/gensim/pull/3203/commits/11c3fba58872cbfbf7256fe68d40deec760c1fbd#diff-da5f51494aa51bd7240e8a97bccf242a7ac3146bddc793f52f73b2a13971a6b7R30 .

**Comment by km5ar** [comment]
This one 
https://radimrehurek.com/gensim/similarities/docsim.html

![image](https://user-images.githubusercontent.com/54015474/128612678-b9aa6c4d-a7c8-47af-9d29-93d5982fee18.png)

Thank you so much for your help!!!
