### ISSUE TITLE
Number of workers when working on multicore systems

### ISSUE THREAD

**Issue by sandrastampibombelli** [RaRe-Technologies/gensim#3216]
Hello,

I am trying to run FastText on huge corpus of newspaper text, and on a multicore server at my University. I have requested 48 cores to run this operation, and I wondering if in the FastText parameters I have to specify workers=48 too. I don't understand from the documentation whether it has to be like this.

`bsub -W 12:00 -n 48 -N -B -R "rusage[mem=8GB]" python scriptname.py`

Thanks a lot.
Sandra

**Comment by piskvorky** [comment]
Please follow the issue template – don't just delete.
