### ISSUE TITLE
Get travis-ci.com working with this repo

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#3217]
@piskvorky Could you please go through the steps described in the tutorial below? Only the project owner can do it, unfortunately.

https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github

We need TravisCI to build for certain platforms that github actions does not support yet (e.g. aarm64).

**Comment by piskvorky** [comment]
AFAIK all these steps were already done, a while ago. What specifically doesn't work, which step is missing?

**Comment by mpenkov** [comment]
TravisCI isn't picking up new gensim builds. The last time it ran a build was half a year ago, which was still under the old .org platform.

**Comment by piskvorky** [comment]
OK. I'll try talk to Travis support, to see what's wrong.

**Comment by mpenkov** [comment]
> I thought we stopped using Travis (moved to Github Actions instead)?

We still need TravisCI for some platforms that GHA does not support, like aarm.

> This is all for rare-technologies/gensim, right? 

Yes.

> Where should a new gensim build be "picked up"?

https://www.travis-ci.com/github/RaRe-Technologies/gensim

> In 9f5355b, it looks like you explicitly disabled it.

That build is "disabled" for develop only. It should still run for the release branches.

**Comment by mpenkov** [comment]
Ah, I see what's going on. The release branches weren't being pushed to github for some reason.

It looks like travis is working as expected now.
