### ISSUE TITLE
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'

### ISSUE THREAD

**Issue by icanhasmath** [RaRe-Technologies/gensim#3225]
Building gensim from source on Python 3.9 I consistently get this error:
```
  File "setup.py", line 108, in finalize_options
    __builtins__.__NUMPY_SETUP__ = False
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
```

My current workaround is this:
https://github.com/RaRe-Technologies/gensim/blob/919b4154a5696a544b87f792992f25f5e4d59d3e/setup.py#L109

```
        try:
            __builtins__.__NUMPY_SETUP__ = False
        except AttributeError:
            print("Cannot set '__builtins__.__NUMPY_SETUP__ = False' This is not needed if numpy is already installed.")
```

**Comment by mpenkov** [comment]
What platform?

**Comment by icanhasmath** [comment]
Windows.

**Comment by jaymegordo** [comment]
+1 same thing on mac M1

**Comment by icanhasmath** [comment]
Noting this thread may be relevant: https://github.com/pyvista/pyacvd/pull/23#issue-1298467701
They dropped the `__builtins__.__NUMPY_SETUP__` as outdated.

**Comment by anthonymichaelclark** [comment]
+1 Also experiencing on M1 Mac

I'm beyond my depth re PEP 517 and the accompanying argument to `pip`, just wanted to call out [this comment](https://github.com/python-poetry/poetry/issues/3433) from the poetry maintenance team in case it sheds some light on potential solutions.

**Comment by hangingman** [comment]
This problem is fixed in gensim4, but is there any backport release ?
I want to use gensim3 instead of gensim4.
I'm happy if gensim 3.8.4 is released for backport , which will be resolved this `__NUMPY_SETUP__` issue.

**Comment by hangingman** [comment]
I write this for those who missed reading it;

> Gensim is being [continuously tested](https://radimrehurek.com/gensim/#testing) under all [supported Python versions](https://github.com/RaRe-Technologies/gensim/wiki/Gensim-And-Compatibility). Support for Python 2.7 was dropped in gensim 4.0.0 – install gensim 3.8.3 if you must use Python 2.7.

**Comment by gojomo** [comment]
No further 3.8.x releases are expected, so you'd have to backport any fixes, or apply workarounds, on your own. 

But also: improvements in a number of aspects of Gensim mean any such custom efforts might be better exerted porting code/models to use Gensim 4.x. 

Further, any specific barriers you're facing, in upgrading to 4.x, that can be well-described could potentially get code/doc help in a future 4.x release – potentialy of public value to many users – while fixing things for a 4-year-old release on a Python that is itself within 18mo of end-of-life may only have idiosyncratic private value to you.

**Comment by hangingman** [comment]
@gojomo Thank you for your explanation. 
Finally, I've used Python 3.8 + gensim3, then the problem is resolved.

In the first place why I'm using gensim3, because I would like to avoid the error of #3127 (I think, the issue point is the Doc2Vec model trained by gensim3 can't be used by gensim4.) .
Then, I've encountered this #3225 because of I'm using latest python and gensim.

> Further, any specific barriers you're facing, in upgrading to 4.x, that can be well-described could potentially get code/doc help in a future 4.x release – potentialy of public value to many users

In this point of view, I expect you to described how to resolve a issue , such a #3127. I speculate there is only one way (?). This is to say; training model by gensim4.

**Comment by gojomo** [comment]
@hangingman - Thanks, could you add a comment on #3127 describing the way you're seeing that problem? (Specifically: whether you're hitting the first variant originally reported  – the model loads but then errors on subsequent use – or a failure-on-load, perhaps with exact same stack as others have shown? If you know the exact version(s) in which your model was created or successfuly loaded/used, those would be good to know, too.)
