### ISSUE TITLE
Word2Vec model callbacks property not accessible

### ISSUE THREAD

**Issue by ginward** [RaRe-Technologies/gensim#3229]
#### Problem description

It seems that the callbacks property in the Word2Vec model is not callable: 

#### Steps/code/corpus to reproduce

```python
from gensim.models.callbacks import CallbackAny2Vec
from pprint import pprint as print
from gensim.models.word2vec import Word2Vec
from gensim.test.utils import datapath

class callback(CallbackAny2Vec):
    '''Callback to print loss after each epoch.'''

    def __init__(self):
        self.epoch = 0

    def on_epoch_end(self, model):
        loss = model.get_latest_training_loss()
        print('Loss after epoch {}: {}'.format(self.epoch, loss))
        self.epoch += 1

# Set file names for train and test data
corpus_file = datapath('lee_background.cor')

model = Word2Vec(vector_size=100, callbacks=[callback()])

# build the vocabulary
model.build_vocab(corpus_file=corpus_file)

# train the model
model.train(
    corpus_file=corpus_file, epochs=model.epochs,
    total_examples=model.corpus_count, total_words=model.corpus_total_words,
    callbacks=model.callbacks, compute_loss=True,
)

print(model)
```

> 
> AttributeError                            Traceback (most recent call last)
> <ipython-input-1-4a4736964107> in <module>
>      27     corpus_file=corpus_file, epochs=model.epochs,
>      28     total_examples=model.corpus_count, total_words=model.corpus_total_words,
> ---> 29     callbacks=model.callbacks, compute_loss=True,
>      30 )
>      31 
> 
> AttributeError: 'Word2Vec' object has no attribute 'callbacks'
> 
> 
> 

#### Versions

```>>> import platform; print(platform.platform())
macOS-10.16-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.9.5 (default, May 18 2021, 12:31:01)
[Clang 10.0.0 ]
>>> import struct; print("Bits", 8 * struct.calcsize("P"))
Bits 64
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.20.3
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.7.1
>>> import gensim; print("gensim", gensim.__version__)
gensim 4.1.0
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 0
```

**Comment by gojomo** [comment]
Effective starting Gensim 4.0, any `callbacks` provided are *not* stored in the model, but only applied for duration of the exact method where the callback was provided. Storing the callbacks presented a lot of usability problems when saving/reloading models = see #2136 for the discussion leading to the change. 

You should have seen a warning message explaining this when supplying the callbacks as part of the line:

    model = Word2Vec(vector_size=100, callbacks=[callback()])

(Have you done something to suppress such warnings, or discard logging/console-output?)

The workaround & recommended approach is to supply the callbacks upon any future calls to `.train()` - without counting on them being held in the model.
