### ISSUE TITLE
Ask travis-ci.com for more credits

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#3233]
Sounds like RaReTech ran out of Travis credits again:

https://app.travis-ci.com/github/RaRe-Technologies/gensim/requests

>  Owner RaRe-Technologies does not have enough credits.

Can you please ask them for more? It's not urgent, we only need travis for aarch64 wheel builds, and we can deal with them later, but it'd be good to have that working soon.

**Comment by piskvorky** [comment]
Oh wow. OK, I'll write to them again.

**Comment by gojomo** [comment]
Earlier this month, Travis-CI had a bug where anyone's PR against a project could potentially access the project's build secret environment-variables:

https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/

I see that we do have two project secrets there - WHEELHOUSE_UPLOADER_USERNAME &  WHEELHOUSE_UPLOADER_SECRET. I'm not sure of their significance, but I'd guess knowing them might allow someone to replace our wheels in downstream places like AWS or PyPI. 

I'm not sure if we had any PRs/builds that could have been affected, giving others access to these credentials, but it'd probably be wise to rotate those secrets to new values *as soon as practical*, and double-check that any uploads at places controlled by those values are exactly those intended by Gensim authorized users/processes.

**Comment by piskvorky** [comment]
Thanks. @mpenkov do we actually still need Travis CI? That's not a flattering write-up, looks like a shit show.

Github actions (Microsoft) might not be that much safer, but at least it's just one service, not two.

**Comment by mpenkov** [comment]
> @mpenkov do we actually still need Travis CI?

We use TravisCI for aarch64 wheel builds. Github actions does not support that platform yet.

In our case, TravisCI never runs for PRs (other from the original contributor of the aarch64 code), so it's likely the other PRs were unable to take advantage of the vulnerability even if they wanted to.

> but I'd guess knowing them might allow someone to replace our wheels in downstream places like AWS or PyPI.

In practice, leaked AWS credentials would give an attacker access to our AWS account. They could use AWS services and we'd have to pay for that usage (bad). They wouldn't be able to affect PyPI wheels: that's a completely different system.

We _do_ have our (my) PyPI creds in github action secrets for smart_open, for easier releases.

**Comment by mpenkov** [comment]
> I'm not sure if we had any PRs/builds that could have been affected, giving others access to these credentials, but it'd probably be wise to rotate those secrets to new values as soon as practical, and double-check that any uploads at places controlled by those values are exactly those intended by Gensim authorized users/processes.

Good idea. @piskvorky Can you rotate the AWS keys? From memory, the account belongs to RaRe.

**Comment by piskvorky** [comment]
>  @piskvorky Can you rotate the AWS keys?

I cannot find it. Is there any way to check which key / user / org the Github secret uses?
