### ISSUE TITLE
Clean up gensim project on PyPI

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#3237]
We've hit the 10GB limit for projects on PyPI. This is preventing some of the 4.1.2 wheels from being uploaded.

https://pypi.org/help/#project-size-limit

We need to clean up the project area before we can upload new wheels.

**Comment by mpenkov** [comment]
I think the safest thing to do immediately is to delete all 4.1.0 and 4.1.1 wheels because they are buggy. That would allow the 4.1.2 wheels to be uploaded properly.

I'd do this myself, but I don't have the permissions.

**Comment by piskvorky** [comment]
Oh wow. That's weird, where did 10 GB go? I'll have a look. Thanks for reporting!

**Comment by piskvorky** [comment]
@mpenkov I requested a quote increase on PyPI: https://github.com/pypa/pypi-support/issues/1315

**Comment by mpenkov** [comment]
OK, thank you.

I uploaded the remaining wheels, so the 4.1.2 release contains all the wheels that it needs now, including aarm64.

**Comment by piskvorky** [comment]
Are you sure? Github still reports 4.1.1 as the latest:
https://github.com/RaRe-Technologies/gensim/releases/

**Comment by mpenkov** [comment]
Not sure why it was missing, but I manually pushed the tag and updated the release, so it's there now.

https://github.com/RaRe-Technologies/gensim/releases/tag/4.1.2
