### ISSUE TITLE
I cannot import remove_stopword_tokens

### ISSUE THREAD

**Issue by gloriamacia** [RaRe-Technologies/gensim#3241]
#### Problem description
Following the [documentation ](https://radimrehurek.com/gensim/parsing/preprocessing.html) I attempt to import in Colab as follows: 
`from gensim.parsing.preprocessing import remove_stopword_tokens
`
#### Steps/code/corpus to reproduce

```
from gensim.parsing.preprocessing import remove_stopword_tokens

ImportError Traceback (most recent call last)
<ipython-input-16-dbd838c83237> in <module>()
----> 1 from gensim.parsing.preprocessing import remove_stopword_tokens

ImportError: cannot import name 'remove_stopword_tokens' from 'gensim.parsing.preprocessing' (/usr/local/lib/python3.7/dist-packages/gensim/parsing/preprocessing.py)
```
I observe also the same problem with `remove_short_tokens` for which also no example is provided in the docs.

#### Versions

```python
Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
Python 3.7.12 (default, Sep 10 2021, 00:21:48) 
[GCC 7.5.0]
Bits 64
NumPy 1.19.5
SciPy 1.4.1
gensim 4.0.0
FAST_VERSION 1
```

**Comment by piskvorky** [comment]
Can you try upgrading Gensim? The documentation is for version 4.1.2, but you're using Gensim 4.0. IIRC there were some changes to `preprocessing` in between.

**Comment by gloriamacia** [comment]
Thanks a lot @piskvorky, for the great library as well as for your help in the issue. It works now. 

I would suggest maybe updating the red banner from the docs saying that it is for version 4.1.2 (it currently says 4.0.0) to avoid users facing this kind of issues in the future.

**Comment by piskvorky** [comment]
Good point. @mpenkov how about we get rid of the banner altogether? The 4.0 migration is successfully behind us, hopefully.
