### ISSUE TITLE
Computing WmdSimilarity each-with-each

### ISSUE THREAD

**Issue by erehulka** [RaRe-Technologies/gensim#3242]
Right now I am working on a model, where for a given dataset of sentences I need to compute WmdSimilarity between each of them. Thus the result is a (n x n) matrix, that is **symmetric**. Right now the only way is to compute similarity for each sentence with each sentence in the dataset. But half of the steps is reduntant, because the matrix is symmetric, so we only need to compute the _lower triangular portion_.

The only need is to create a method that computes this matrix and then sets the upper triangular portion according to the lower one (I believe this is easily done with numpy). This way the computing time can be reduced by 50%.

**Comment by mpenkov** [comment]
This issue tracker is for bug reports only.

Please use the mailing list for discussions.
