### ISSUE TITLE
default estimation method of gensim's word2vec skipgram?

### ISSUE THREAD

**Issue by petershan1119** [RaRe-Technologies/gensim#3243]
I am now trying to use word2vec by estimating skipgram embeddings via NCE (noise contrastive estimation) rather than conventional negative sampling method, as a recent paper did (https://asistdl.onlinelibrary.wiley.com/doi/full/10.1002/asi.24421?casa_token=uCHp2XQZVV8AAAAA%3Ac7ETNVxnpqe7u9nhLzX7pIDjw5Fuq560ihU3K5tYVDcgQEOJGgXEakRudGwEQaomXnQPVRulw8gF9XeO). The paper has a replication github repository (https://github.com/sandeepsoni/semantic-progressiveness), and it mainly relied on gensim for implementing word2vec, but the repository is not well organized and in a mess, so I have no clue about how the authors implemented NCE estimation via gensim's word2vec.

The authors just used gensim's word2vec as a default status without including any options, so my question is what is the default estimation method for gensim's word2vec under skipgram embeddings. NCE? According to your manual, it just says there is an option for negative sampling, and if set to 0, then no negative sampling is used. But then what estimation method is used? negative (int, optional) – If > 0, negative sampling will be used, the int for negative specifies how many “noise words” should be drawn (usually between 5-20). If set to 0, no negative sampling is used.

Thanks you in advance, and look forward to hearing from you soon!

**Comment by piskvorky** [comment]
Hi, please use the mailing list for questions. The link and instructions were in the issue template (that you deleted).
