### ISSUE TITLE
Log level control

### ISSUE THREAD

**Issue by cosmozhang** [RaRe-Technologies/gensim#3245]
https://github.com/RaRe-Technologies/gensim/blob/5bec27767ad40712e8912d53a896cb2282c33880/gensim/models/tfidfmodel.py#L447

I think it a good idea to control this logger output (give an option to disable) to avoid spamming the terminal.

**Comment by piskvorky** [comment]
Each Gensim module has its own logger. So you can disable the `tfidf` logger, even temporarily:

```python
# set a higher logging threshold, temporarily
old_threshold = tfidfmodel.logger.level
tfidfmodel.logger.level = logging.WARNING

# do some work
model = TfidfModel(corpus)
…

# set threshold back to INFO
tfidfmodel.logger.level = old_threshold
```

For such generic questions, please use the mailing list (see the link in the issue template, that you deleted).
