### ISSUE TITLE
Partial support of compressed corpora in FastText model

### ISSUE THREAD

**Issue by dchaplinsky** [RaRe-Technologies/gensim#3246]
#### Problem description

Seems that vocab part of the FastText model are totally fine with compressed files. I.e you can pass bzipped file to `build_vocab` method and be perfectly fine. Until you try to train the model on the same file. It seems that `train_epoch_sg`/`train_epoch_cbow` (or more precisely, `CythonLineSentence`) doesn't support the same logic and only can accept text files.

Nevertheless you can pass bzip file to train method and it won't object at all. It'll even train on it. But as you can imagine, results are peculiar

This is a bit misleading. While I understand why it happens it took me sometime to debug why my vectors are rubbish.

#### Steps/code/corpus to reproduce

```python
    model = FastText()
    model.build_vocab(corpus_file="/my/corpus.txt.bz2")

    model.train(
        corpus_file="/my/corpus.txt.bz2",
        total_words=model.corpus_total_words,
        total_examples=model.corpus_count,
    )
```

#### Versions

Please provide the output of:

```python
macOS-11.5.2-x86_64-i386-64bit
Python 3.8.12 (default, Aug 31 2021, 04:09:21)
[Clang 12.0.5 (clang-1205.0.22.9)]
Bits 64
NumPy 1.21.2
SciPy 1.7.1
gensim 4.1.2
FAST_VERSION 0
```

**Comment by dchaplinsky** [comment]
Hello Radim and thanks for the prompt reply!

Ideal solution for me is of course support of compressed files in compiled code (actually I just bought 2TB of space for my google colab exactly because of this :)). Working with compressed files might be faster, especially on slow io, when reading is a bottleneck.

But I understand, that probably this might be too much of burden to add the proper support (or at least to do it now).
An alternative solution might be a warning that is issued by the compiled reader when reading (presumably) binary files and a note in the documentation

**Comment by piskvorky** [comment]
> An alternative solution might be a warning that is issued by the compiled reader when reading (presumably) binary files and a note in the documentation

Okay, thanks. Are you able to open a PR?

**Comment by dchaplinsky** [comment]
I do not have a solution yet (otherwise I'd opening PR rather than reporting an issue). Will look into it.

On a similar note, when I'm initializing training like this:
```python

    model = FastText()

    logger.info("Building vocabulary...")
    model.build_vocab(corpus_file=str(settings.corpus_path))

    model.train(
        corpus_file=str(settings.corpus_path),
        total_words=model.corpus_total_words,
        total_examples=model.corpus_count,
    )
```

I'm receiving strange log messages like this:
```
gensim.models.word2vec:INFO 2021-10-10 12:55:38,419 EPOCH 2 - PROGRESS: at 123.22% examples, 233055 words/s, in_qsize -1, out_qsize 1
```

**Comment by piskvorky** [comment]
> I'm receiving strange log messages like this:

This is still for the case where your `settings.corpus_path` is compressed?

If so, nonsensical log statistics are expected: the (correct) `model.X` stats created in `build_vocab()` do not match the (incorrect) stats that `train()` calculates from the mishandled binary stream.

**Comment by dchaplinsky** [comment]
> This is still for the case where your settings.corpus_path is compressed?
No, I'm not :) Everything is uncompressed now :)

> Yeah, extra dependencies are not great. Simply looking at the file extension (using built-in mimetypes)
Okay, deal.
