### ISSUE TITLE
Incorrect CBOW implementation in Gensim leads to inferior performance

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#3266]
#### Problem description

According to this article https://aclanthology.org/2021.insights-1.1.pdf:

<img width="636" alt="Screen Shot 2021-11-09 at 15 47 21" src="https://user-images.githubusercontent.com/610412/140945923-7d279468-a9e9-41b4-b7c2-919919832bc5.png">

#### Steps/code/corpus to reproduce

I haven't tried to verify / reproduce. Gensim's goal is to follow the original C implementation faithfully, which it does. So this is not a bug per se, more a question of "how whether / how much we want to deviate from the reference implementation". I'm in favour if the result is unambiguous better (more accurate, faster, no downsides).

#### Versions

All versions since the beginning of word2vec in Gensim.

**Comment by piskvorky** [comment]
@gojomo @mpenkov WDYT?

**Comment by gojomo** [comment]
I [remain as unconvinced](https://github.com/RaRe-Technologies/gensim/issues/1873#issuecomment-753668405) as when this was raised earlier this year. I'll add more comments there. I suggest this be closed as dupe.

**Comment by piskvorky** [comment]
Thanks! I remember that discussion now.

Closing as duplicate of #1873.
