### ISSUE TITLE
ImportError : Ensemble LDA

### ISSUE THREAD

**Issue by AbhiPawar5** [RaRe-Technologies/gensim#3267]
Hi Team, I am trying to use Ensemble version of LDA which I found [here](https://radimrehurek.com/gensim/models/ensemblelda.html) and a tutorial [here](https://radimrehurek.com/gensim/auto_examples/tutorials/run_ensemblelda.html)

But, I am seeing an import error for
```
from gensim.models import EnsembleLda
```
Error String:
```
ImportError: cannot import name 'EnsembleLda'
```
#### Versions
Linux-4.4.0-148-generic-x86_64-with-Ubuntu-14.04-trusty
Python 3.6.8 (default, Dec 25 2018, 00:00:00) 
[GCC 4.8.4]
Bits 64
NumPy 1.19.5
SciPy 1.5.4
gensim 3.6.0
FAST_VERSION 1

**Comment by piskvorky** [comment]
Hi Abhi, unfortunately we do not support Gensim versions < 4.0 any more. Please install the latest version.
