### ISSUE TITLE
Variable num_docs not set after calling load_from_text() in Dictionary

### ISSUE THREAD

**Issue by cedricdeboom** [RaRe-Technologies/gensim#327]
After calling the load_from_text() function on a Dictionary object, the num_docs variable is not set, causing functions like filter_extremes() to fail to produce the wanted result.

**Comment by piskvorky** [comment]
The text format has no concept of `num_docs`. It's not a substitute for normal `save`/`load`.

If you need `num_docs` (and other Dictionary variables), you'll have to save the full object.

Or do you see a way to extend the text format without making it too complicated? (no special headers, backward compatible)

**Comment by cedricdeboom** [comment]
OK, I see. I had some ideas, but that would indeed break backward compatibility...
Sorry for bothering :).

**Comment by vlejd** [comment]
I believe this is fixed by #1402

**Comment by menshikh-iv** [comment]
@vlejd you are correct, @cedricdeboom now it's work correctly after `save_as_text` + `load_from_text`, I checked it for `gensim==2.3.0`.
