### ISSUE TITLE
LSI add_documents 

### ISSUE THREAD

**Issue by inferense** [RaRe-Technologies/gensim#3296]
While updating LSI with new documents, my kernel shuts down. It seems like there's a memory issue, though I'm testing this out on a miniature set of documents and vocab size.

here's what I do:

```python
model = models.LsiModel(corpus=corpus_tfidf, id2word=id2word, num_topics=best_k) # train LSI 
corpus_bow, id2word, corpus_tfidf, tfidf = preprocess(all_docs) # rebuild the vocab with the new doc included
model.add_documents(corpus_tfidf[-1:]) # add the new doc from the rebuilt corpus to the lsi
```

help appreciated!

**Comment by piskvorky** [comment]
Please follow the issue template. This is neither the right place nor format for such questions.
