### ISSUE TITLE
evaluate_word_pairs gives ValueError: x and y must have length at least 2.

### ISSUE THREAD

**Issue by Filco306** [RaRe-Technologies/gensim#3315]
#### Problem description

I am trying to run an evaluation on a pair of trained vectors on a datafile, namely [this one](https://github.com/tca19/near-lossless-binarization/blob/master/datasets/MEN.txt). However, when using the function `wordembeddingmodel.evaluate_word_pairs(datapath("MEN.txt"))` (it is stored in the datapath folder) I get the error `ValueError: x and y must have length at least 2.`. I suspect this has to do with the formatting, but I cannot figure out what the issue is. 

#### Steps/code/corpus to reproduce

Traceback: 

```bash
File "/.../src/evaluate.py", line 25, in evaluate_wordsimilarity
    ] = wordembeddingmodel.evaluate_word_pairs(datapath(worddataset))[0][0]
  File "/home/users/filip/.conda/envs/sskgnn/lib/python3.9/site-packages/gensim/models/keyedvectors.py", line 1321, in evaluate_word_pairs
    pearson = stats.pearsonr(similarity_gold, similarity_model)
  File "/home/users/filip/.conda/envs/sskgnn/lib/python3.9/site-packages/scipy/stats/stats.py", line 4016, in pearsonr
    raise ValueError('x and y must have length at least 2.')
ValueError: x and y must have length at least 2.
```
Dataset: Downloaded from [here](https://raw.githubusercontent.com/tca19/near-lossless-binarization/master/datasets/MEN.txt). I download it and create it using: 

```python3
import requests
from gensim.test.utils import datapath
import os.path as osp

fpath = datapath("")
file = "https://raw.githubusercontent.com/tca19/near-lossless-binarization/master/datasets/MEN.txt"
r = requests.get(file)
filename = file.split("/")[-1]
with open(osp.join(fpath,filename), "wb") as f:
    f.write(r.text.encode("utf-8").strip())
```

```python
>>> print(wordembeddingmodel.lifecycle_events)
*** AttributeError: 'Word2VecKeyedVectors' object has no attribute 'lifecycle_events'
```

#### Versions

Please provide the output of:

```python
>>> import platform; print(platform.platform())
ec.FAST_VERSION)Linux-5.4.0-90-generic-x86_64-with-glibc2.31
>>> import sys; print("Python", sys.version)
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
>>> import struct; print("Bits", 8 * struct.calcsize("P"))
Bits 64
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.21.2
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.7.1
>>> import gensim; print("gensim", gensim.__version__)
gensim 3.8.3
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 1
```

Any help is greatly appreciated! Thank you :)

Cheers
Filip

**Comment by piskvorky** [comment]
Please upgrade your Gensim first, we no longer support the 3.X versions.

**Comment by Filco306** [comment]
Alright, I upgraded it, such that: 

```python3
>>> import gensim; print("gensim", gensim.__version__)
gensim 4.1.2
```

The error persist however :/

**Comment by piskvorky** [comment]
It looks like none of the words from the judgements file appear in your model, all words are out-of-vocabulary.
And then scipy.pearson blows up on empty input further down the line with `x and y must have length at least 2.`

I agree that error is atrociously uninformative, sorry. I've pushed a fix in PR #3318 that:

a) Logs all lines from the judgement file that are OOV
b) Fails with a different error if all lines were OOV

**Comment by Filco306** [comment]
Thank you for this! Is this in the current version of genim now, or is it still to be released?

Maybe a file validator function can be called to check the correct format even before trying to run these?

**Comment by piskvorky** [comment]
To be released.
