### ISSUE TITLE
KeyedVector most_similar() use too much CPU

### ISSUE THREAD

**Issue by MrKZZ** [RaRe-Technologies/gensim#3333]
#### when using KeyedVector  most_similiar() function, my process is always killed because of using too much CPU resourse. 

I have 20 cpu but  running with 2200%. And i don't find any where to limit this setting. for example : Can i use only 5 cpus to run this code? 

#### gensim==4.1.2

from gensim.models import KeyedVectors
model = KeyedVectors.load("word2vec")
similar_words = model.most_similar(positive=[query], topn=50)

Note that my server will kill the process which using more than 100% cpu or mem.

![image](https://user-images.githubusercontent.com/18312628/165009607-53386924-eedd-4933-9e8d-9a32e12f60d0.png)

and the part in the red box is my problem. How can i solve these parts, this is monitor by another machine and the problem machine is killed .
![problem](https://user-images.githubusercontent.com/18312628/165009990-e33519a8-7074-4004-909b-a8e41349e49a.png)

**Comment by mpenkov** [comment]
You haven't given us enough information to reproduce the problem.

Please provide a reproducible example of the problem (read the issue template for details) or we will have to close the issue.

**Comment by MrKZZ** [comment]
Added !!!

**Comment by piskvorky** [comment]
Why did you delete the issue template party?Especially the BLAS part, which is vital to your problem (restricting BLAS threads).

**Comment by MrKZZ** [comment]
> Why did you delete the issue template block? Especially the BLAS part, which is vital to your problem (restricting BLAS threads).
> 
> Please fill it in fully or we cannot help you.

**Comment by MrKZZ** [comment]
> 

I open a new issue and using this template. 3335. By the way, what's BLAS part?

**Comment by mpenkov** [comment]
#3335
