### ISSUE TITLE
Parsing Error in Docs

### ISSUE THREAD

**Issue by MattYoon** [RaRe-Technologies/gensim#3336]
#### Problem description

There seems to be a parsing error in [modesl.fasttext,FastTextKeyedVectors docs](https://radimrehurek.com/gensim/models/fasttext.html#gensim.models.fasttext.FastTextKeyedVectors).

It is in between `bucket_word` and `__getitem__` attributes.
![doc error](https://user-images.githubusercontent.com/57797966/165233852-fc93c467-3c07-4131-bf9f-59420aa9042a.PNG)

**Comment by piskvorky** [comment]
Yeah, that's weird. Are you able to find the cause and submit a PR @MattYoon ? Thanks.

**Comment by piskvorky** [comment]
Actually, reading the misformatted text, I think we can remove it completely. There's not enough information there make it actionable ("may be decorated with attributes that associate with its attributes" – what?), which makes it bad documentation.
