### ISSUE TITLE
Ways to speed up LDA Seq model?

### ISSUE THREAD

**Issue by jacobceles** [RaRe-Technologies/gensim#3350]
Hi,

Already posted this on google groups but did not get any response so asking here.

I am trying to do the LDA Sequence model on 8 decades worth of data containing 13,774 documents and 164,318 dictionary elements and noticed that it takes a lot of time to run. I tried running the code in Sagemaker with a compute-optimized cluster (ml.c5.12xlarge - 48 vCPU & 96 GiB Memory) for almost 10 hours with no results. Is there any way to speed this up? Here's the code I am using for reference:
```
time_slice = [1051, 2900, 1258, 1771, 1520, 2010, 2852, 412]
lda_seq = LdaSeqModel(corpus=corpus, time_slice=time_slice, id2word=dictionary, num_topics=20, chunksize=200, passes=1)
```
Any input is highly appreciated, thanks.

#### Versions
gensim 4.2.0

**Comment by gojomo** [comment]
I've posted some thoughts on the discussion list. As this is a tracker for bugs & feature-requests, not general usage questions, I'm closing this issue.
