### ISSUE TITLE
can Gensim compute collocation metrics?

### ISSUE THREAD

**Issue by randomgambit** [RaRe-Technologies/gensim#3351]
Hello!

I am trying to reproduce some of the classical measures of collocations (PMI, likelihood ratios, etc) and I was wondering if `gensim` handles some of these computations? To be clear, I would like to find to rank the bigrams in my data according to statistical measures of association.

Thanks!

**Comment by mpenkov** [comment]
This tracker is for bug reports only. Questions should go to the mailing list. The link to the mailing list is in the issue template that you deleted.
