### ISSUE TITLE
Can't use CoherenceModel.get_coherence() on AWS Lambda

### ISSUE THREAD

**Issue by jlin99** [RaRe-Technologies/gensim#3355]
#### Problem description

Seems like AWS Lambda doesn't support Python's multiprocessing module so trying to use the function get_coherence() throws the error `Function not implemented`. Just wondering if there might already exist some easy workaround to run this function without multiprocessing. 

#### Steps/code/corpus to reproduce

Logs: 
<img width="1121" alt="Screen Shot 2022-06-13 at 5 26 56 PM" src="https://user-images.githubusercontent.com/8921721/173448264-2f4a5e20-9a05-480f-9f5f-01c1c42656de.png">

#### Versions

Tried with multiple versions of Python (`3.7`, `3.8`, `3.9`) and gensim (`3.8.3`, `4.2.0`)

**Comment by mpenkov** [comment]
Unfortunately, no.

https://stackoverflow.com/questions/34005930/multiprocessing-semlock-is-not-implemented-when-running-on-aws-lambda
