### ISSUE TITLE
Upgraded from version 4.0.1. to 4.2.0, now KeyedVectors.most_similar() throws error

### ISSUE THREAD

**Issue by brunoj** [RaRe-Technologies/gensim#3358]
#### Problem description

Using KeyedVectors.most_similar() as follows:

learn_language.most_similar(positive=[class_vectors[classname]], negative=[class_vectors[aclassname]], topn=max_topn)

where class_vectors[X] are some vectors created by averaging a number of KeyedVectors (of the size 75 or shape (75,)) from the same KeyedVectors object.

WORKS perfectly well in version 4.0.1, but on version 4.2.0 throws the following error:

learn_language.most_similar(positive=[class_vectors[classname]], negative=[class_vectors[aclassname]], topn=max_topn)
  File "/usr/local/lib/python3.9/site-packages/gensim/models/keyedvectors.py", line 842, in most_similar
    mean = self.get_mean_vector(keys, weight, pre_normalize=True, post_normalize=True, ignore_missing=False)
  File "/usr/local/lib/python3.9/site-packages/gensim/models/keyedvectors.py", line 512, in get_mean_vector
    mean += weights[idx] * key
ValueError: operands could not be broadcast together with shapes (100,) (75,) (100,) 

#### Steps/code/corpus to reproduce

```python
import gensim
import numpy as np
learn_language = gensim.models.KeyedVectors.load("embeddings.english", mmap="r")
learn_language.most_similar(positive=[learn_language["great"]], negative=[learn_language["terrible"]], topn=100)

learn_language.most_similar(positive=[learn_language["great"]], negative=[learn_language["terrible"]], topn=100)
  File "/usr/local/lib/python3.9/site-packages/gensim/models/keyedvectors.py", line 842, in most_similar
    mean = self.get_mean_vector(keys, weight, pre_normalize=True, post_normalize=True, ignore_missing=False)
  File "/usr/local/lib/python3.9/site-packages/gensim/models/keyedvectors.py", line 512, in get_mean_vector
    mean += weights[idx] * key
ValueError: operands could not be broadcast together with shapes (100,) (75,) (100,) 
```

#### Versions

>>> import platform; print(platform.platform())
Windows-10-10.0.19041-SP0
>>> import sys; print("Python", sys.version)
Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)]
>>> import struct; print("Bits", 8 * struct.calcsize("P"))
Bits 64
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.22.4
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.8.1
>>> import gensim; print("gensim", gensim.__version__)
gensim 4.2.0
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 0

**Comment by piskvorky** [comment]
@rock420 seems related to your PR #3188. Can you check what's going on? Thanks.

**Comment by rock420** [comment]
@brunoj, It seems like your model (learn_language) has a word vector length of `100`, but the vector length of what you are passing as arguments to `most_similar` function is `75`. please confirm if both are of same length or not

**Comment by piskvorky** [comment]
Also, your "minimal reproducing example" is incomplete. Crucially, what is `kv`?

**Comment by brunoj** [comment]
> @brunoj, It seems like your model (learn_language) has a word vector length of `100`, but the vector length of what you are passing as arguments to `most_similar` function is `75`. please verify if both are of the same length or not. function call will fail if they have different length which is expected

@rock420 I have verified that neither the model nor any of the passed parameters has a word vector length any other than 75 (as do the passed arguments).

Please note that the SAME code with the SAME model works as expected in version 4.0.1.

@piskvorky Here is another example:

In Gensim Version 4.2.0:

>>> import aick
>>> eng = aick.language("eng")
>>> eng.most_similar(positive=[eng["good"]], negative=[eng["bad"]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\gensim\models\keyedvectors.py", line 842, in most_similar
    mean = self.get_mean_vector(keys, weight, pre_normalize=True, post_normalize=True, ignore_missing=False)
  File "C:\Python39\lib\site-packages\gensim\models\keyedvectors.py", line 512, in get_mean_vector
    mean += weights[idx] * key
ValueError: operands could not be broadcast together with shapes (100,) (75,) (100,)
>>> eng
<gensim.models.keyedvectors.KeyedVectors object at 0x0000029A0AA90160>
>>> eng.vectors.shape
(1641937, 75)
>>> eng["good"].shape
(75,)
>>> eng["bad"].shape
(75,)
>>>

the SAME code and model in Gensim 4.0.1:

>>> import aick
>>> eng = aick.language("eng")
>>> eng.most_similar(positive=[eng["good"]], negative=[eng["bad"]])
[('unfailing', 0.5650630593299866), ('appreciation', 0.56245356798172), ('simplicity', 0.5576601624488831), ('devotionally', 0.5331001281738281), ('generosity', 0.5323244333267212), ('unselfishly', 0.5246316194534302), ('unstinted', 0.5210593938827515), ('unostentatious', 0.5195757150650024), ('humbleness', 0.5176042914390564), ('untiring', 0.5143886804580688)]
>>> eng
<gensim.models.keyedvectors.KeyedVectors object at 0x000001F803F50190>
>>> eng.vectors.shape
(1641937, 75)
>>> eng["good"].shape
(75,)
>>> eng["bad"].shape
(75,)
>>>

**Comment by brunoj** [comment]
@piskvorky @rock420 I have detected the problem:

In the trained model (which is old and has been edited), the "vector_size" variable was set to 100, despite the actual vector size being 75.

After adapting this manually in the model, the problem is fixed. Maybe it's a good idea to add a sanity check on this.

Apologies for any inconvenience.
