### ISSUE TITLE
KeyedVectors.load_word2vec_format() can't load GoogleNews-vectors-negative300.bin

### ISSUE THREAD

**Issue by xwz-19990627** [RaRe-Technologies/gensim#3360]
#### Problem description

KeyedVectors.load_word2vec_format() can't load GoogleNews-vectors-negative300.bin,
This is the my code.
```
from gensim.models.keyedvectors import KeyedVectors

gensim_model = KeyedVectors.load_word2vec_format(
    './GoogleNews-vectors-negative300.bin', binary=True, limit=300000)
```
This is the error code.

#### Versions
```
Traceback (most recent call last):
  File "D:\desktop\2\word2vec.py", line 4, in <module>
    gensim_model = KeyedVectors.load_word2vec_format(
  File "C:\Users\admin\anaconda3\envs\dl\lib\site-packages\gensim\models\keyedvectors.py", line 1723, in load_word2vec_format
    return _load_word2vec_format(
  File "C:\Users\admin\anaconda3\envs\dl\lib\site-packages\gensim\models\keyedvectors.py", line 2063, in _load_word2vec_format
    vocab_size, vector_size = [int(x) for x in header.split()]  # throws for invalid file format
ValueError: not enough values to unpack (expected 2, got 0)
```
Please provide the output of:
python 3.9.1
gensim 4.2.0

**Comment by lukelaurence** [comment]
When I ran this code it worked fine; are you sure the problem is with this line and not another line or the file? Try updating gensim's dependencies (smart_open, etc.) and redownloading the file. If that doesn't work, try replacing the first line with:
`from gensim.models import KeyedVectors`

**Comment by xwz-19990627** [comment]
thanks,This is my problem, GoogleNews-vectors-negative300.bin didn't download successfully, but I thought it did
