### ISSUE TITLE
How to find gensim's release notes (API changes)?

### ISSUE THREAD

**Issue by Saltsmart** [RaRe-Technologies/gensim#3372]
Hello! We have a project based on gensim. After gensim was updated to 4.2.0, some APIs have changed (e.g. `size` to `vector_size` in `Word2Vec`). We have to fix our references.  
Where can we find the list of API changes? We have locate some points but that's far from all.
Thank you♥!

**Comment by piskvorky** [comment]
Hello! Please check https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4
