### ISSUE TITLE
how  can I  load  model  from hdfs ?  

### ISSUE THREAD

**Issue by NYcleaner** [RaRe-Technologies/gensim#3385]
when i submit my job on yarn ,  i need load model from the hdfs, but  it  turn over  error like :
` 
INFO : loading Word2Vec object from hdfs://example1/w2v_models/word2vec_200_online
cat: `example1/w2v_models/word2vec_200_online': No such file or directory
Ran out of input
`

most because  the numpy code on which Gensim relies to load subsidiary files doesn't support remote paths like hdfs or S3?

how can I do ? thanks for anwser and help

**Comment by piskvorky** [comment]
Some of the Gensim models expect a file on disk, because they use memory-mapping for efficiency.

Hard to say what you're (trying to) load, your report is misformatted and incomplete. But probably something expects some file of disk.

**Comment by NYcleaner** [comment]
hello, i just want to load the trained model from the hdfs,  i have  move the  model to the hdfs  from local, but  when i  use the  Word2Vec.load(model_path) ,  model_path like 'hdfs://example1/w2v_models/word2vec_200_online', it give an error : 
`INFO : loading Word2Vec object from hdfs://example1/w2v_models/word2vec_200_online cat:example1/w2v_models/word2vec_200_online': No such file or directory
Ran out of input`

**Comment by NYcleaner** [comment]
another problem is :  i want to retrain my word2vec model everyday, but the raw_data is saved  on hive , so  i should use spark applicaton to get the raw_data , and then use gensim word2vec to retrain the model ,  all those must work on the  yarn cluster , but   gensim.models.Word2Vec.load(path)  and  gensim.models.Word2Vec.save(path)   api  only  support  local_path ,  it cant  support  hdfs_path, so how can i do with that ? 
thanks

**Comment by mpenkov** [comment]
This issue tracker is for bug reports only. For questions about gensim, please see the mailing list.

- Use the [Gensim mailing list](https://groups.google.com/forum/#!forum/gensim) to ask general or usage questions. Github issues are only for bug reports.
