### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by Manjusmnr** [RaRe-Technologies/gensim#3391]
Planning to use the library
Licensed under : GNU Lesser General Public License v2.1
we are not doing any modifications in the source code of the library
GPL, or our application can be made proprietary.
Can you share more insights on the same.

**Comment by piskvorky** [comment]
We use the standard LGPL license, with restrictions. I'm no lawyer but my understanding is that you only have to make public and distribute any changes you make to the LGPL library that you distribute to others.

Github issues are for issues and bugs, please see the link in the issue template (that you deleted) for general questions.
