### ISSUE TITLE
Word2Vec & Doc2Vec distributed

### ISSUE THREAD

**Issue by tschohanna** [RaRe-Technologies/gensim#3396]
I would like to implement a distributed Topic Modeling Pipeline based on Gensim. Unfortunately, Gensim only supports distributed LSA and LDA. I read that Word2Vec and Doc2Vec tend to have better results than LSA and LDA. However, I also read about pretrained Word2Vec and Doc2Vec models. Is there a way to use Word2Vec or Doc2Vec in a distributed manner?

**Comment by piskvorky** [comment]
Hi, please follow the issue template in asking questions. Thanks!
