### ISSUE TITLE
Word2Vec & Doc2Vec distributed

### ISSUE THREAD

**Issue by tschohanna** [RaRe-Technologies/gensim#3399]
#### Problem description

I would like to implement a distributed Topic Modeling Pipeline based on Gensim. Unfortunately, Gensim only supports distributed LSA and LDA. I read that Word2Vec and Doc2Vec tend to have better results than LSA and LDA. However, I also read about pretrained Word2Vec and Doc2Vec models. Is there a way to use Word2Vec or Doc2Vec in a distributed manner?

#### Steps/code/corpus to reproduce

no steps taken yet

#### Versions

newest version

**Comment by piskvorky** [comment]
Hi, please use the discussion forum linked from the issue template for discussions. Thanks.

But the short answer is no, not a good idea – given the level of sophistication of your query, distributed computation would be way over the top. Just prepare your data and train the models as per the tutorials.
