### ISSUE TITLE
Can't import OkapiBM25Model

### ISSUE THREAD

**Issue by lidija-jovanovska** [RaRe-Technologies/gensim#3403]
#### Problem description

I'm trying to use OkapiBM25Model. I installed the latest version of gensim, using the command `pip install gensim==4.2.0` and when I try to import the model using `from gensim.models.bm25model import OkapiBM25Model` the file is not found. From inspecting the library in my local folder site-packages I can see that the bm25model file is not there. However, when I search for the same file on the github repo, I see that the file is there. I also checked using the previous version (4.1.2) but I got the same issue. 

#### Steps/code/corpus to reproduce

`pip install gensim==4.2.0`
```python
from gensim.models.bm25model import OkapiBM25Model
```

#### Versions

```
macOS-10.16-x86_64-i386-64bit
Python 3.9.13 (main, Aug 25 2022, 18:29:29) 
[Clang 12.0.0 ]
Bits 64
NumPy 1.23.1
SciPy 1.9.1
gensim 4.2.0
FAST_VERSION 1
```

**Comment by piskvorky** [comment]
IIRC the OkapiBM25Model hasn't been released yet, it only lives in the active pre-release branch. @Witiko @mpenkov can you confirm?

**Comment by lidija-jovanovska** [comment]
Ok, that makes sense. I was checking on the default github repo which is `develop`. Any ideas as of when will this be released? Thanks!

**Comment by piskvorky** [comment]
@mpenkov Misha what's a good time for a sync call, to go over what we need to make a new release?

Not urgent, but let's plan ahead. Thanks.

**Comment by Witiko** [comment]
@piskvorky Gensim has not had a release since 4.2.0 in May, whereas #3304 has only been merged in September.
