### ISSUE TITLE
 arm64-graviton2 wheels for Py3.10 and 3.11 fail to build under Travis

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#3418]
https://app.travis-ci.com/github/RaRe-Technologies/gensim/builds/258974284

@janaknat Any idea how to work around this? Looks like it's failing while trying to install psutil.

We're planning to do a release soon, it'd be great if you could have a look.

@piskvorky Just in case, if we cannot get these wheels built, should that delay the release? IMHO we can release anyway, and whoever needs the wheels for that platform can help get them building properly.

**Comment by janaknat** [comment]
@mpenkov This is weird. For python3.9 build, it is able to get psutil_5.9.4.tar.gz but not for python 3.10. Python 3.11 build is even weirder. Says can't find python3.11 binary.

**Comment by mpenkov** [comment]
>  Says can't find python3.11 binary.

Where do you see this?

**Comment by mpenkov** [comment]
I think the problem is with nmslib because that is the last package it collected (the psutil stuff looks like a red herring to me).

The nmslib guys don't provide wheels for Py3.10 and 11, so that's causing the CI to build the wheels and fail for some reason.

**Comment by mpenkov** [comment]
OK, for 3.10, I was able to get things going by disabling nsmlib and visdom (they are test-only dependencies that we don't need for wheel building).

For 3.11, there's nothing we can do at this stage. The corresponding multibuild docker image https://index.docker.io/search?q=multibuild was built a year ago, when Python 3.11 was not around. Until they provide a newer image, we cannot build a gensim wheel for Py3.11 on that platform.

Anyway, thanks for your help!

**Comment by piskvorky** [comment]
Nmslib is a fringe dependency (a very remote and rare use-case), and definitely not required for Gensim. Also not bundled inside Gensim.

How / why is it required for our wheel building?

**Comment by mpenkov** [comment]
We run tests on the wheels after we build them. Nmslib gets installed as a dependency for those tests.

**Comment by piskvorky** [comment]
You're too fast :) I just edited my comment.

About "multibuild" – how about I simply build & upload the wheel for linux + macos locally? Is there any special magic happening in `multibuild`?

**Comment by piskvorky** [comment]
According to [this](https://github.com/multi-build/multibuild/pull/486), isn't 3.11 already supported?

I find it strange that a package-building-package hasn't been updated for a year, and after a major Python version release.

**Comment by mpenkov** [comment]
Yeah, I think there's tons of magic in there. The problem is building binaries that work on a wide range of platforms. Multibuild makes solving that problem easier.

We do our own thing for Windows (see the .github/workflows/build-wheels.yml) simply because there's no multibuild support for Windows. We wouldn't want to be doing that for MacOS and Linux - it's a significant amount of effort.

And yes, multibuild supports 3.11. I think the problem is with 3.11 support for this particular architecture (graviton or aarch64). All the 3.11 builds for other architectures worked fine.

**Comment by mpenkov** [comment]
https://github.com/multi-build/multibuild/issues/492
