### ISSUE TITLE
Out of space on PyPI again

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#3419]
4.3.0 is ready for release, but

```
Error during upload. Retry with the --verbose option for more details.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Project size too large. Limit for project 'gensim' total size is 10 GB. See https://pypi.org/help/#project-size-limit
```

We need another 500MB to release 4.3.0.  We can also look at reducing the size of the releases (I recall that being proposed in the past, but I don't remember where that proposal went).

Our potential courses of actions:

- [ ] Ask for more space
- [ ] Remove old releases

**Comment by piskvorky** [comment]
Discussed here: https://github.com/pypa/pypi-support/issues/1315

**Comment by mpenkov** [comment]
Sounds like 100GB is unrealistic for them. Let's ask for 15GB and say that we expect this to last us several years (we release once/twice a year at most, and each release is 500MB).

**Comment by piskvorky** [comment]
Okay. I'll reopen the ticket above.

**Comment by piskvorky** [comment]
Hm, I guess. Which one?

Definitely not the oldest (historical value), but also not the latest. So, something from the middle? Ideally some RC or beta release(s)?

**Comment by piskvorky** [comment]
@mpenkov I went ahead and deleted all `rc*` releases of Gensim from PyPI.

PyPI now reports "9.5 GiB" (out of 10 GB limit) – is that enough for this release?

**Comment by mpenkov** [comment]
OK, that did the trick.

I went through the release steps: all that's left is to tweet about the update 🍾

**Comment by mpenkov** [comment]
Release is complete, so closing
