### ISSUE TITLE
Which corpus is used as reference for NPMI calculation in Gensim?

### ISSUE THREAD

**Issue by Zay-Ben** [RaRe-Technologies/gensim#3439]
According to Hoyle et al. (2021) in their paper "Is Automated Topic Model Evaluation Broken?: The Incoherence of Coherence", the calculation of coherence scores can vary depending on the reference corpus used.
_"As a result, the choice of reference corpus determines the strength of human correlation (Lau et al., 2014; Röder et al., 2015)."_
Can you tell me which reference corpus Gensim uses for calculating NPMI? Thank you.

**Comment by mpenkov** [comment]
This issue tracker is for bug reports only. Please ask questions on the mailing list.

The link to to the mailing list is in the issue template that you deleted.

**Comment by Zay-Ben** [comment]
Thank you that will be noted. :)
