### ISSUE TITLE
while trying to downlaod gensim from pip official page i get an error on every machine i test it

### ISSUE THREAD

**Issue by GeorgeApos** [RaRe-Technologies/gensim#3444]
I am building a Dockerfile running gensim and when it gets to the point to download gensim from pip i get this error. Is there a way to bypass this? Is it a general issue, or it's just in my machines?

#9 5.973 Collecting gensim
#9 6.019   Downloading gensim-4.3.0.tar.gz (23.3 MB)
#9 11.93      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/23.3 MB 3.8 MB/s eta 0:00:00
#9 12.64   Preparing metadata (setup.py): started
#9 35.86   Preparing metadata (setup.py): finished with status 'error'
#9 35.89   error: subprocess-exited-with-error
#9 35.89
#9 35.89   × python setup.py egg_info did not run successfully.
#9 35.89   │ exit code: 1
#9 35.89   ╰─> [305 lines of output]
#9 35.89       /usr/lib/python3.9/site-packages/setuptools/__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
#9 35.89         dist.fetch_build_eggs(dist.setup_requires)
#9 35.89       WARNING: The wheel package is not available.
#9 35.89         error: subprocess-exited-with-error
#9 35.89
#9 35.89         × Building wheel for numpy (pyproject.toml) did not run successfully.
#9 35.89         │ exit code: 1
#9 35.89         ╰─> [257 lines of output]
#9 35.89             Running from numpy source directory.
#9 35.89             setup.py:67: DeprecationWarning:
#9 35.89
#9 35.89               `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
#9 35.89               of the deprecation of `distutils` itself. It will be removed for
#9 35.89               Python >= 3.12. For older Python versions it will remain present.
#9 35.89               It is recommended to use `setuptools < 60.0` for those Python versions.
#9 35.89               For more details, see:
#9 35.89                 https://numpy.org/devdocs/reference/distutils_status_migration.html
#9 35.89
#9 35.89
#9 35.89               import numpy.distutils.command.sdist
#9 35.89             Processing numpy/random/_bounded_integers.pxd.in
#9 35.89             Processing numpy/random/_pcg64.pyx
#9 35.89             Processing numpy/random/bit_generator.pyx
#9 35.89             Processing numpy/random/_generator.pyx
#9 35.89             Processing numpy/random/_common.pyx
#9 35.89             Processing numpy/random/_bounded_integers.pyx.in
#9 35.89             Processing numpy/random/_philox.pyx
#9 35.89             Processing numpy/random/_sfc64.pyx
#9 35.89             Processing numpy/random/mtrand.pyx
#9 35.89             Processing numpy/random/_mt19937.pyx
#9 35.89             Cythonizing sources
#9 35.89             INFO: blas_opt_info:
#9 35.89             INFO: blas_armpl_info:
#9 35.89             INFO: customize UnixCCompiler
#9 35.89             INFO:   libraries armpl_lp64_mp not found in ['/usr/local/lib', '/usr/lib']
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: blas_mkl_info:
#9 35.89             INFO:   libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: blis_info:
#9 35.89             INFO:   libraries blis not found in ['/usr/local/lib', '/usr/lib']
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: openblas_info:
#9 35.89             INFO:   libraries openblas not found in ['/usr/local/lib', '/usr/lib']
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: accelerate_info:
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: atlas_3_10_blas_threads_info:
#9 35.89             INFO: Setting PTATLAS=ATLAS
#9 35.89             INFO:   libraries tatlas not found in ['/usr/local/lib', '/usr/lib']
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: atlas_3_10_blas_info:
#9 35.89             INFO:   libraries satlas not found in ['/usr/local/lib', '/usr/lib']
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: atlas_blas_threads_info:
#9 35.89             INFO: Setting PTATLAS=ATLAS
#9 35.89             INFO:   libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib']
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: atlas_blas_info:
#9 35.89             INFO:   libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib']
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             /tmp/pip-wheel-hjd0k3x7/numpy_ec54adfc1ee341f4acdc89ed995b3b83/numpy/distutils/system_info.py:2077: UserWarning:
#9 35.89                 Optimized (vendor) Blas libraries are not found.
#9 35.89                 Falls back to netlib Blas library which has worse performance.
#9 35.89                 A better performance should be easily gained by switching
#9 35.89                 Blas library.
#9 35.89               if self._calc_info(blas):
#9 35.89             INFO: blas_info:
#9 35.89             INFO:   libraries blas not found in ['/usr/local/lib', '/usr/lib']
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             /tmp/pip-wheel-hjd0k3x7/numpy_ec54adfc1ee341f4acdc89ed995b3b83/numpy/distutils/system_info.py:2077: UserWarning:
#9 35.89                 Blas (http://www.netlib.org/blas/) libraries not found.
#9 35.89                 Directories to search for the libraries can be specified in the
#9 35.89                 numpy/distutils/site.cfg file (section [blas]) or by setting
#9 35.89                 the BLAS environment variable.
#9 35.89               if self._calc_info(blas):
#9 35.89             INFO: blas_src_info:
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             /tmp/pip-wheel-hjd0k3x7/numpy_ec54adfc1ee341f4acdc89ed995b3b83/numpy/distutils/system_info.py:2077: UserWarning:
#9 35.89                 Blas (http://www.netlib.org/blas/) sources not found.
#9 35.89                 Directories to search for the sources can be specified in the
#9 35.89                 numpy/distutils/site.cfg file (section [blas_src]) or by setting
#9 35.89                 the BLAS_SRC environment variable.
#9 35.89               if self._calc_info(blas):
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             non-existing path in 'numpy/distutils': 'site.cfg'
#9 35.89             INFO: lapack_opt_info:
#9 35.89             INFO: lapack_armpl_info:
#9 35.89             INFO:   libraries armpl_lp64_mp not found in ['/usr/local/lib', '/usr/lib']
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: lapack_mkl_info:
#9 35.89             INFO:   libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: openblas_lapack_info:
#9 35.89             INFO:   libraries openblas not found in ['/usr/local/lib', '/usr/lib']
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: openblas_clapack_info:
#9 35.89             INFO:   libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib']
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: flame_info:
#9 35.89             INFO:   libraries flame not found in ['/usr/local/lib', '/usr/lib']
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: atlas_3_10_threads_info:
#9 35.89             INFO: Setting PTATLAS=ATLAS
#9 35.89             INFO:   libraries tatlas,tatlas not found in /usr/local/lib
#9 35.89             INFO:   libraries tatlas,tatlas not found in /usr/lib
#9 35.89             INFO: <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: atlas_3_10_info:
#9 35.89             INFO:   libraries satlas,satlas not found in /usr/local/lib
#9 35.89             INFO:   libraries satlas,satlas not found in /usr/lib
#9 35.89             INFO: <class 'numpy.distutils.system_info.atlas_3_10_info'>
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: atlas_threads_info:
#9 35.89             INFO: Setting PTATLAS=ATLAS
#9 35.89             INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
#9 35.89             INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib
#9 35.89             INFO: <class 'numpy.distutils.system_info.atlas_threads_info'>
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: atlas_info:
#9 35.89             INFO:   libraries f77blas,cblas,atlas not found in /usr/local/lib
#9 35.89             INFO:   libraries f77blas,cblas,atlas not found in /usr/lib
#9 35.89             INFO: <class 'numpy.distutils.system_info.atlas_info'>
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: lapack_info:
#9 35.89             INFO:   libraries lapack not found in ['/usr/local/lib', '/usr/lib']
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             /tmp/pip-wheel-hjd0k3x7/numpy_ec54adfc1ee341f4acdc89ed995b3b83/numpy/distutils/system_info.py:1902: UserWarning:
#9 35.89                 Lapack (http://www.netlib.org/lapack/) libraries not found.
#9 35.89                 Directories to search for the libraries can be specified in the
#9 35.89                 numpy/distutils/site.cfg file (section [lapack]) or by setting
#9 35.89                 the LAPACK environment variable.
#9 35.89               return getattr(self, '_calc_info_{}'.format(name))()
#9 35.89             INFO: lapack_src_info:
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             /tmp/pip-wheel-hjd0k3x7/numpy_ec54adfc1ee341f4acdc89ed995b3b83/numpy/distutils/system_info.py:1902: UserWarning:
#9 35.89                 Lapack (http://www.netlib.org/lapack/) sources not found.
#9 35.89                 Directories to search for the sources can be specified in the
#9 35.89                 numpy/distutils/site.cfg file (section [lapack_src]) or by setting
#9 35.89                 the LAPACK_SRC environment variable.
#9 35.89               return getattr(self, '_calc_info_{}'.format(name))()
#9 35.89             INFO:   NOT AVAILABLE
#9 35.89             INFO:
#9 35.89             INFO: numpy_linalg_lapack_lite:
#9 35.89             INFO:   FOUND:
#9 35.89             INFO:     language = c
#9 35.89             INFO:
#9 35.89             Warning: attempted relative import with no known parent package
#9 35.89             /tmp/pip-build-env-2lwz3kp6/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
#9 35.89               warnings.warn(msg)
#9 35.89             running bdist_wheel
#9 35.89             running build
#9 35.89             running config_cc
#9 35.89             INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
#9 35.89             running config_fc
#9 35.89             INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
#9 35.89             running build_src
#9 35.89             INFO: build_src
#9 35.89             INFO: building py_modules sources
#9 35.89             creating build
#9 35.89             creating build/src.linux-x86_64-3.9
#9 35.89             creating build/src.linux-x86_64-3.9/numpy
#9 35.89             creating build/src.linux-x86_64-3.9/numpy/distutils
#9 35.89             INFO: building library "npymath" sources
#9 35.89             WARN: Could not locate executable armflang
#9 35.89             WARN: Could not locate executable gfortran
#9 35.89             WARN: Could not locate executable f95
#9 35.89             WARN: Could not locate executable ifort
#9 35.89             WARN: Could not locate executable ifc
#9 35.89             WARN: Could not locate executable lf95
#9 35.89             WARN: Could not locate executable pgfortran
#9 35.89             WARN: Could not locate executable nvfortran
#9 35.89             WARN: Could not locate executable f90
#9 35.89             WARN: Could not locate executable f77
#9 35.89             WARN: Could not locate executable fort
#9 35.89             WARN: Could not locate executable efort
#9 35.89             WARN: Could not locate executable efc
#9 35.89             WARN: Could not locate executable g77
#9 35.89             WARN: Could not locate executable g95
#9 35.89             WARN: Could not locate executable pathf95
#9 35.89             WARN: Could not locate executable nagfor
#9 35.89             WARN: Could not locate executable frt
#9 35.89             WARN: don't know how to compile Fortran code on platform 'posix'
#9 35.89
#9 35.89
#9 35.89             [Errno 2] No such file or directory: 'gcc'
#9 35.89
#9 35.89
#9 35.89             Traceback (most recent call last):
#9 35.89               File "/usr/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#9 35.89                 main()
#9 35.89               File "/usr/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#9 35.89                 json_out['return_val'] = hook(**hook_input['kwargs'])
#9 35.89               File "/usr/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
#9 35.89                 return _build_backend().build_wheel(wheel_directory, config_settings,
#9 35.89               File "/tmp/pip-build-env-2lwz3kp6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 230, in build_wheel
#9 35.89                 return self._build_with_temp_dir(['bdist_wheel'], '.whl',
#9 35.89               File "/tmp/pip-build-env-2lwz3kp6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
#9 35.89                 self.run_setup()
#9 35.89               File "/tmp/pip-build-env-2lwz3kp6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 267, in run_setup
#9 35.89                 super(_BuildMetaLegacyBackend,
#9 35.89               File "/tmp/pip-build-env-2lwz3kp6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
#9 35.89                 exec(compile(code, __file__, 'exec'), locals())
#9 35.89               File "setup.py", line 479, in <module>
#9 35.89                 setup_package()
#9 35.89               File "setup.py", line 471, in setup_package
#9 35.89                 setup(**metadata)
#9 35.89               File "/tmp/pip-wheel-hjd0k3x7/numpy_ec54adfc1ee341f4acdc89ed995b3b83/numpy/distutils/core.py", line 169, in setup
#9 35.89                 return old_setup(**new_attr)
#9 35.89               File "/tmp/pip-build-env-2lwz3kp6/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
#9 35.89                 return distutils.core.setup(**attrs)
#9 35.89               File "/tmp/pip-build-env-2lwz3kp6/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
#9 35.89                 dist.run_commands()
#9 35.89               File "/tmp/pip-build-env-2lwz3kp6/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
#9 35.89                 self.run_command(cmd)
#9 35.89               File "/tmp/pip-build-env-2lwz3kp6/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
#9 35.89                 cmd_obj.run()
#9 35.89               File "/tmp/pip-build-env-2lwz3kp6/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
#9 35.89                 self.run_command('build')
#9 35.89               File "/tmp/pip-build-env-2lwz3kp6/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
#9 35.89                 self.distribution.run_command(command)
#9 35.89               File "/tmp/pip-build-env-2lwz3kp6/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
#9 35.89                 cmd_obj.run()
#9 35.89               File "/tmp/pip-wheel-hjd0k3x7/numpy_ec54adfc1ee341f4acdc89ed995b3b83/numpy/distutils/command/build.py", line 62, in run
#9 35.89                 old_build.run(self)
#9 35.89               File "/tmp/pip-build-env-2lwz3kp6/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
#9 35.89                 self.run_command(cmd_name)
#9 35.89               File "/tmp/pip-build-env-2lwz3kp6/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
#9 35.89                 self.distribution.run_command(command)
#9 35.89               File "/tmp/pip-build-env-2lwz3kp6/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
#9 35.89                 cmd_obj.run()
#9 35.89               File "/tmp/pip-wheel-hjd0k3x7/numpy_ec54adfc1ee341f4acdc89ed995b3b83/numpy/distutils/command/build_src.py", line 144, in run
#9 35.89                 self.build_sources()
#9 35.89               File "/tmp/pip-wheel-hjd0k3x7/numpy_ec54adfc1ee341f4acdc89ed995b3b83/numpy/distutils/command/build_src.py", line 155, in build_sources
#9 35.89                 self.build_library_sources(*libname_info)
#9 35.89               File "/tmp/pip-wheel-hjd0k3x7/numpy_ec54adfc1ee341f4acdc89ed995b3b83/numpy/distutils/command/build_src.py", line 288, in build_library_sources
#9 35.89                 sources = self.generate_sources(sources, (lib_name, build_info))
#9 35.89               File "/tmp/pip-wheel-hjd0k3x7/numpy_ec54adfc1ee341f4acdc89ed995b3b83/numpy/distutils/command/build_src.py", line 378, in generate_sources
#9 35.89                 source = func(extension, build_dir)
#9 35.89               File "numpy/core/setup.py", line 755, in get_mathlib_info
#9 35.89                 raise RuntimeError(
#9 35.89             RuntimeError: Broken toolchain: cannot link a simple C program.
#9 35.89             [end of output]
#9 35.89
#9 35.89         note: This error originates from a subprocess, and is likely not a problem with pip.
#9 35.89         ERROR: Failed building wheel for numpy
#9 35.89       ERROR: Failed to build one or more wheels
#9 35.89       Traceback (most recent call last):
#9 35.89         File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 97, in _fetch_build_egg_no_warn
#9 35.89           subprocess.check_call(cmd)
#9 35.89         File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
#9 35.89           raise CalledProcessError(retcode, cmd)
#9 35.89       subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpef_6u8tt', '--quiet', 'numpy>=1.18.5']' returned non-zero exit status 1.
#9 35.89
#9 35.89       The above exception was the direct cause of the following exception:
#9 35.89
#9 35.89       Traceback (most recent call last):
#9 35.89         File "<string>", line 2, in <module>
#9 35.89         File "<pip-setuptools-caller>", line 34, in <module>
#9 35.89         File "/tmp/pip-install-5gk3sr0k/gensim_594c40f3fe5540f8bd35b410876e6627/setup.py", line 356, in <module>
#9 35.89           setup(
#9 35.89         File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
#9 35.89           _install_setup_requires(attrs)
#9 35.89         File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
#9 35.89           _fetch_build_eggs(dist)
#9 35.89         File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 85, in _fetch_build_eggs
#9 35.89           dist.fetch_build_eggs(dist.setup_requires)
#9 35.89         File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 894, in fetch_build_eggs
#9 35.89           return _fetch_build_eggs(self, requires)
#9 35.89         File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 39, in _fetch_build_eggs
#9 35.89           resolved_dists = pkg_resources.working_set.resolve(
#9 35.89         File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 815, in resolve
#9 35.89           dist = self._resolve_dist(
#9 35.89         File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 851, in _resolve_dist
#9 35.89           dist = best[req.key] = env.best_match(
#9 35.89         File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1123, in best_match
#9 35.89           return self.obtain(req, installer)
#9 35.89         File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1135, in obtain
#9 35.89           return installer(requirement)
#9 35.89         File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 99, in _fetch_build_egg_no_warn
#9 35.89           raise DistutilsError(str(e)) from e
#9 35.89       distutils.errors.DistutilsError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpef_6u8tt', '--quiet', 'numpy>=1.18.5']' returned non-zero exit status 1.
#9 35.89       [end of output]
#9 35.89
#9 35.89   note: This error originates from a subprocess, and is likely not a problem with pip.
#9 35.90 error: metadata-generation-failed
#9 35.90
#9 35.90 × Encountered error while generating package metadata.
#9 35.90 ╰─> See above for output.
#9 35.90
#9 35.90 note: This is an issue with the package mentioned above, not pip.
#9 35.90 hint: See above for details.
------
executor failed running [/bin/sh -c pip3 install --no-cache --upgrade pip setuptools     && pip3 install         pylint         pytest         pytest-cov         ez_setup         nltk         gensim         astor         pipreqs     && python3 -m nltk.downloader punkt]: exit code: 1

**Comment by piskvorky** [comment]
Looks like an error with numpy installation. I don't think there's anything we can do, sorry.

**Comment by GeorgeApos** [comment]
Thank you very much for your reply.
