### ISSUE TITLE
Questions about word2vec_model.wv.most_similar

### ISSUE THREAD

**Issue by JJery-web** [RaRe-Technologies/gensim#3449]
Thanks to this project for the opportunity to learn. I encountered two confusions while building the dictionary and would like answers. Thanks.

1、When using the function of 
"word2vec_model.wv.most_similar", I set topn=300 and 500 respectively and found that the first 300 words of the two results are not exactly the same (I think if the word is not changed, the first 300 words should theoretically be exactly the same based on the cos method to rank). 

2、I set topn=500, but the final number of words I get in expanded_dict.csv is 520. Why is the final number of words not equal to 500?

I look forward to receiving a reply!

**Comment by mpenkov** [comment]
Github issues are for bug reports only.

Please direct questions to the mailing list. The URL is in the issue template that you deleted when you created the issue.
