### ISSUE TITLE
Out of TravisCI credits again

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim#3453]
Another instance of https://github.com/RaRe-Technologies/gensim/issues/3233

@piskvorky Could you please ask them for more credits? When you talk to them, please mention that it'd be good if they could somehow cover for us automatically instead of us asking them (the same way that github days).

**Comment by piskvorky** [comment]
I couldn't figure out where to add "open source credits". I only see options to *buy* credits.

I'll try asking at Travis support.

**Comment by mpenkov** [comment]
Actually, good question, we may not need them anymore. @nikaro your PR builds wheels for the platform that TravisCI is building for, right?

**Comment by mpenkov** [comment]
@piskvorky I checked, we have the aarch64 wheels now, so we can say goodbye to TravisCI. Hooray!

http://gensim-wheels.s3-website-us-east-1.amazonaws.com/
