### ISSUE TITLE
Replace copy of FuzzyTM in gensim/models/flsamodel.py with dep

### ISSUE THREAD

**Issue by pabs3** [RaRe-Technologies/gensim#3457]
The [gensim/models/flsamodel.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/flsamodel.py)
file is an outdated, modified copy of [FuzzyTM/FuzzyTM.py](https://github.com/ERijck/FuzzyTM/blob/master/FuzzyTM/FuzzyTM.py)
from [FuzzyTM](https://github.com/ERijck/FuzzyTM/) by @ERijck.

In addition, the copy in gensim does not attribute the original author and does not state the license of the file as GNU GPLv2.

Please replace flsamodel.py with a wrapper that depends on and uses FuzzyTM, or at minimum, correctly state the origin, copyright holder and license of the file.

If any changes are needed to FuzzyTM, please send a pull request for them and then depend on the release that adds the changes.

**Comment by piskvorky** [comment]
The license of that file is LGPL (not GPL) – same as the rest of Gensim.

I already fixed the header in https://github.com/RaRe-Technologies/gensim/pull/3437 , PR pending Emil's completion.

**Comment by pabs3** [comment]
Hmm, that is confusing.

Why is the license different between the two copies of the same code?

Will the changes to FuzzyTM in flsamodel.py be sent back to FuzzyTM?

Or is flsamodel.py a permanent fork of FuzzyTM?

PS: the license link in that PR points at LGPLv3, it needs fixing.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by piskvorky** [comment]
Authors can use whatever license they like for their code – including multiple licenses.

In this case, the primary author is @ERijck . And I guess after #3437, also me, to a lesser degree.
