### ISSUE TITLE
How to open doc2vec trained on an older version of gensim?

### ISSUE THREAD

**Issue by ashay-quant** [RaRe-Technologies/gensim#3495]
I have a large number of models trained on older gensim ? I recently updated my python library, and gensim was bumped to the latest version. The problem is the Doc2Vec.load is refusing to load the older versions. Is there a compatibility mode available ? Or what's the cleanest way to load old models and save them in the new format. I am getting the following error:

attributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 model = Doc2Vec.load(r'Z:\process\edgar\business_doc2vec\20230731.model')

File C:\Anaconda3\envs\base_small\lib\site-packages\gensim\models\doc2vec.py:815, in Doc2Vec.load(cls, *args, **kwargs)
    810 except AttributeError as ae:
    811     logger.error(
    812         "Model load error. Was model saved using code from an older Gensim version? "
    813         "Try loading older model using gensim-3.8.3, then re-saving, to restore "
    814         "compatibility with current code.")
--> 815     raise ae

File C:\Anaconda3\envs\base_small\lib\site-packages\gensim\models\doc2vec.py:809, in Doc2Vec.load(cls, *args, **kwargs)
    786 """Load a previously saved :class:`~gensim.models.doc2vec.Doc2Vec` model.
    787 
    788 Parameters
   (...)
    806 
    807 """
    808 try:
--> 809     return super(Doc2Vec, cls).load(*args, rethrow=True, **kwargs)
    810 except AttributeError as ae:
    811     logger.error(
    812         "Model load error. Was model saved using code from an older Gensim version? "
    813         "Try loading older model using gensim-3.8.3, then re-saving, to restore "
    814         "compatibility with current code.")

File C:\Anaconda3\envs\base_small\lib\site-packages\gensim\models\word2vec.py:1949, in Word2Vec.load(cls, rethrow, *args, **kwargs)
   1947 except AttributeError as ae:
   1948     if rethrow:
-> 1949         raise ae
   1950     logger.error(
   1951         "Model load error. Was model saved using code from an older Gensim Version? "
   1952         "Try loading older model using gensim-3.8.3, then re-saving, to restore "
   1953         "compatibility with current code.")
   1954     raise ae

File C:\Anaconda3\envs\base_small\lib\site-packages\gensim\models\word2vec.py:1942, in Word2Vec.load(cls, rethrow, *args, **kwargs)
   1923 """Load a previously saved :class:`~gensim.models.word2vec.Word2Vec` model.
   1924 
   1925 See Also
   (...)
   1939 
   1940 """
   1941 try:
-> 1942     model = super(Word2Vec, cls).load(*args, **kwargs)
   1943     if not isinstance(model, Word2Vec):
   1944         rethrow = True

File C:\Anaconda3\envs\base_small\lib\site-packages\gensim\utils.py:487, in SaveLoad.load(cls, fname, mmap)
    484 compress, subname = SaveLoad._adapt_by_suffix(fname)
    486 obj = unpickle(fname)
--> 487 obj._load_specials(fname, mmap, compress, subname)
    488 obj.add_lifecycle_event("loaded", fname=fname)
    489 return obj

File C:\Anaconda3\envs\base_small\lib\site-packages\gensim\models\word2vec.py:1958, in Word2Vec._load_specials(self, *args, **kwargs)
   1956 def _load_specials(self, *args, **kwargs):
   1957     """Handle special requirements of `.load()` protocol, usually up-converting older versions."""
-> 1958     super(Word2Vec, self)._load_specials(*args, **kwargs)
   1959     # for backward compatibility, add/rearrange properties from prior versions
   1960     if not hasattr(self, 'ns_exponent'):

File C:\Anaconda3\envs\base_small\lib\site-packages\gensim\utils.py:518, in SaveLoad._load_specials(self, fname, mmap, compress, subname)
    516     logger.info("loading %s recursively from %s.* with mmap=%s", attrib, cfname, mmap)
    517     with ignore_deprecation_warning():
--> 518         getattr(self, attrib)._load_specials(cfname, mmap, compress, subname)
    520 for attrib in getattr(self, '__numpys', []):
    521     logger.info("loading %s from %s with mmap=%s", attrib, subname(fname, attrib), mmap)

File C:\Anaconda3\envs\base_small\lib\site-packages\gensim\utils.py:1522, in deprecated.<locals>.decorator.<locals>.new_func1(*args, **kwargs)
   1515 @wraps(func)
   1516 def new_func1(*args, **kwargs):
   1517     warnings.warn(
   1518         fmt.format(name=func.__name__, reason=reason),
   1519         category=DeprecationWarning,
   1520         stacklevel=2
   1521     )
-> 1522     return func(*args, **kwargs)

File C:\Anaconda3\envs\base_small\lib\site-packages\gensim\models\doc2vec.py:328, in Doc2Vec.docvecs(self)
    325 @property
    326 @deprecated("The `docvecs` property has been renamed `dv`.")
    327 def docvecs(self):
--> 328     return self.dv

AttributeError: 'Doc2Vec' object has no attribute 'dv'

**Comment by gojomo** [comment]
From your stack dump, it seems likely your console has shown you the message: 

> Model load error. Was model saved using code from an older Gensim version? Try loading older model using gensim-3.8.3, then re-saving, to restore compatibility with current code.

Have you tried downgrading your Gensim installation to version 3.8.3, loading your model(s), and if that succeeds, re-saving them to new file paths. Then, upgrading to current Gensim, and loading those new saves?

Note that you can install a specific older version of Gensim by specifying a version to to your usual installation command. (For example, `pip install gensim==3.8.3` with `pip` or `conda install gensim=3.8.3` with `conda`.)

Though: rolling back a single package can sometimes create compatibility mismatches with other related packages, so you may want to start in a fresh virtual environment and go from no-Gensim to `gensim-3.8.3` (pulling in other matched packages), then move forward (or again use another fresh environment) to use current Gensim.

**Comment by ashay-quant** [comment]
I will create a new environment with gensim 3.8.3, load and resave the older models. I was hoping there was a cleaner alternate solution, perhaps some kind of legacy parameters for older files.

**Comment by gojomo** [comment]
Note that if your models are old enough, there's a *chance* you might need to load/save using an even-earlier version, first. (And, there may be a few other special cases of versions/modes/rare-usages that need extra work because of other once-upon-a-time bugs.)

But, 3.8.3 was the last version with a bunch of special-casing for a long range of older models, and (mostly) saves models that current-Gensim can load-forward, so should be the 1st workaround tried, and often is the only intermediate step needed.
