### ISSUE TITLE
Get word from vector

### ISSUE THREAD

**Issue by sheavalentine** [RaRe-Technologies/gensim#381]
It would be useful to have a method which returns the closest word when the model is given a vector.

**Comment by piskvorky** [comment]
What model?

**Comment by sheavalentine** [comment]
Sorry... word2vec.  Eg

```python
vectors =  Word2Vec.load_word2vec_format(file)
vectors.word_from_vec(vectors['cat']) == 'cat'
```

**Comment by gojomo** [comment]
You can already do this by passing a single positive example to `most_similar()`, like so:

    vectors.most_similar(positive=[vectors['cat']],topn=1) 

I suppose as a convenience, it could detect a single ndarray (like it detects a single string) and just assume this is what the caller wants...

**Comment by sheavalentine** [comment]
! Oh... that's not entirely obvious.  The expectation was that `positive` needed to be a list of strings.

**Comment by gojomo** [comment]
Yes, the doc-comment should be more clear... and any future/revised tutorials should include a few examples of the multiple styles of arguments it takes.

**Comment by sheavalentine** [comment]
Thank you - also thank you for making this tool.

**Comment by piskvorky** [comment]
Good point.

We'll probably split this API into two distinct methods (`similar_by_word`, `similar_by_vector`) if we want to promote it. Overloading arguments ultimately brings too much trouble and confusion, this was originally supposed to be just an internal quick hack.

**Comment by sheavalentine** [comment]
I can do it, but it'll take me a few days to get the bandwidth.  :)

**Comment by piskvorky** [comment]
No problem.

We plan to make a new release this weekend, so this change will be in the release after that, then.

**Comment by tmylk** [comment]
@sheavalentine Is this still a needed feature? Do you think we could include your Pull Request into the January release?

**Comment by tmylk** [comment]
Closing as abandoned
