### ISSUE TITLE
Word2Vec/Doc2Vec offer model-minimization method

### ISSUE THREAD

**Issue by gojomo** [RaRe-Technologies/gensim#446]
If you're sure you're done training a model, a bunch of its memory-consumptive parts can be discarded: 
- syn0 (non-normalized; be sure to save aside normalized versions 1st)
- syn1, syn1neg, syn0_lockf
- doctag_syn0, doctag_syn0_lockf (in Doc2Vec)

There should be a documented method (such as `finished_training`) to discard these, and testing to ensure there are no lingering unintended dependencies on those sticking around. 

Semantics: As a tradeoff, `finished_training` discards as many model attributes as possible, while still being able to answer `infer_vector` and `__getitem__` queries on the resulting trimmed model. No more continued training on that word2vec/doc2vec model is possible, and any attempt to do so results in a clear, understandable exception.

(Note though that a Doc2Vec model used for future `infer_vector()` ops needs to keep the syn0 & syn1\* values.)

**Comment by gojomo** [comment]
Since I initially wrote this, I've seen cases where the non-unit-normalized `syn0` is preferable to the unit-normed version. (Sometimes the magnitude of the vectors is relevant, with their magnitude in some sense being an indicator of stron/unambiguous meaning.) Also, some Doc2Vec users only want the model for inference, but others would consider the `doctag_syn0` to be what they want to keep around for lookups/similarity-rankings. 

So utility functions for this model-slimming need to be very carefully named and documented to set expectations properly - and perhaps factored to separate operations, rather than one big `finished_training()`.

**Comment by tmylk** [comment]
Fixed in #987
