### ISSUE TITLE
allow initialization with `max_vocab` in lieu of `min_count`

### ISSUE THREAD

**Issue by gojomo** [RaRe-Technologies/gensim#465]
In some scenarios, a user may prefer to target a specific final vocabulary size, after discarding less-frequent words, rather than a minimum-frequency. Right now, they'd have to achieve this via manual analysis (after `scan_vocab()`), or trial-and-error supplying alternate values to `scale_vocab(dry_run=True)` then stopping when they find nice values. Let's just let them specify a target vocab size, and let the code figure out the matching `min_count`. 

(Perhaps similarly: it may make more sense to specify min-frequencies as proportions rather than absolute counts. A `min_count` of 100 might discard a lot in a small corpus, but be meaningless in a corpus for tens/hundreds-of-billions of words...)

**Comment by chinmayapancholi13** [comment]
Hey @gojomo . I want to work on this issue but I was hoping to get a little clarity regarding the finer details of our objective. I understood that we want to select a value of `min_count` by ourselves when the user passes the desired value of the max vocab size that he/she wants. But what would we want to do in a case like : count[word1] = 2, count[word2] = 2, count[word3] = 2, count[word4] = 2 and `max_vocab` = 4. Clearly, we can only include two among the 4 words in the vocab to satisfy the `max_vocab` criterion but how do we choose among those words? Do we make the choice alphabetically? randomly? any other strategy?

**Comment by gojomo** [comment]
I think it would be a defensible/consistent choice to make the interpretation of `max_vocab` be: "automatically pick a `min_count` for me that results is vocabulary no larger than this value".

In your example, the only `min_count` which could match the `max_vocab=4` constraint would be 3. 

If both a `min_count` and `max_vocab` are specified, they should both be satisfied - which in practice would mean whichever implies the higher `min_count`.

**Comment by chinmayapancholi13** [comment]
@gojomo Thanks a lot for the explanation. So, I'll get started with this then.

**Comment by aneesh-joshi** [comment]
Hey @gojomo 
Would it be a good idea to implement this using some sort of parameter search with `dry_run=True` ?

Hey @chinmayapancholi13
Have you worked on this yet?

**Comment by gojomo** [comment]
Implementation should not require a parameter-search - once the initial word-frequency count is competed, there's enough info to satisfy any pre-specified `max_vocab` via simple tallying/sorting. 

Nor should it require any presentation of alternate options to the user, if they've already specified a `max_vocab`. (But, it could be nice to offer a convenience method for reporting a range of possibilities, similar to the `prepare_vocab(dry_run=True)` reporting, if it's easy/compact/logical to do so.)

**Comment by aneesh-joshi** [comment]
Hey @gojomo please review this rough implementation and let me know if it is in the right direction.

**Comment by gojomo** [comment]
There's no need for a `use_max_vocab` - just check if `max_vocab` is non-`None`.

`scan_vocab()` is designed to just discover vocabulary. Destructive trimming only occurs later in `prepare_vocab()`. So this functionality probably shouldn't touch `scan_vocab()` at all. 

There's already a sort by frequency happening somewhere later; can the redundant sort for this feature be avoided? 

There's already a trimming of surviving words happening later; doing it yet again here, according to a different parameter, with yet another temporary dict, just adds memory use & redundancy. 

This should to work in parallel and logical consistency with `min_count`. As mentioned above, I think it would be a defensible/consistent choice to make the interpretation of max_vocab be: "automatically pick a min_count for me that results is vocabulary no larger than this value". If the code's choosing to do something other than that, explain why the alternate approach is better.

**Comment by aneesh-joshi** [comment]
Hi @gojomo @menshikh-iv 

Please consider the latest commit to the PR : https://github.com/RaRe-Technologies/gensim/pull/1915

> There's no need for a use_max_vocab - just check if max_vocab is non-None.

I have made it just one variable with `None`

> scan_vocab() is designed to just discover vocabulary. Destructive trimming only occurs later in prepare_vocab(). So this functionality probably shouldn't touch scan_vocab() at all.

I have moved it to `prepare_vocab`

>There's already a sort by frequency happening somewhere later; can the redundant sort for this feature be avoided?

Unfortunately, the sorting cannot be avoided as the final word counts and frequencies are finished after `min_count` trimming has been done. We have to get the sort done before the trimming

>There's already a trimming of surviving words happening later for min_count; doing it yet again here, according to a different parameter, with yet another temporary dict, just adds memory use & redundancy

In this implementation, I have removed the creation of a dict and just used the sorted values to get the value of min_count which is then further used

>The interface to prepare_vocab() allows dry_run to see the effect of certain choices o other vocabulary-affecting parameters. max_vocab should be handled the same way, net in a separate method with less ability to test changes.

If the current implementation is satisfactory, I will look into including it with `dry_run = True`

>This should work in parallel with min_count. As mentioned above, I think it would be a defensible/consistent choice to make the interpretation of max_vocab be: "automatically pick a min_count for me that results is vocabulary no larger than this value". If the code's choosing to do something other than that, explain why the alternate approach is better.

It has been done so. My part of the code only calculates the min_count and assigns it if `max_vocab` is set.

Further details of implementation can be found in the comments of the PR.
