### ISSUE TITLE
use AppVeyor to test on Windows and upload wheels

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#472]
AppVeyor is free for open source projects:
http://www.appveyor.com/

**Comment by tmylk** [comment]
Windows build merged in #492 

TODO to provide Windows wheel:
-  [ ] setup a rackspace fileshare
-  [ ] uncomment code in appveyor.yaml to upload wheel to the fileshare
-  [ ] add steps to release wiki to download wheel from the share and upload to PyPi using wheelhouse-uploader and twine

**Comment by tmylk** [comment]
Wheels uploaded in #551

**Comment by piskvorky** [comment]
Nice!

Is this issue finished then?

**Comment by tmylk** [comment]
What's left is to generate a wheel during a release and try on my Windows
laptop.

**Comment by menshikh-iv** [comment]
Already implemented (latest PR is #1565)
