### ISSUE TITLE
LDAModel DepracationWarning under Python 3

### ISSUE THREAD

**Issue by mattilyra** [RaRe-Technologies/gensim#494]
I noticed that when training an LDA model under Python 3 with NumPy 1.10 or 1.9 I get a long long list of `DepracationWarning`s from NumPy, so much so that it kills the browser running a notebook. This doesn't happen under Py2 with NumPy 1.10.

I think it's because the `ids` is a list not a `ndarray`. The warning refers to two lines in `ldamodel.py`
- https://github.com/piskvorky/gensim/blob/develop/gensim/models/ldamodel.py#L375
- https://github.com/piskvorky/gensim/blob/develop/gensim/models/ldamodel.py#L401

Both use the `ids` list to index a `ndarray`. The `ids` are just feature ids from the current document (?) so I tried a quick fix of just changing the `ids` to `ndarray` which makes the warnings go away, but I haven't tested if it has some other consquences, I don't see why it would.

The `DepracationWarning`s (just two of them, there are many more actually produced)

```
/Volumes/LocalDataHD/conda/envs/py34/lib/python3.4/site-packages/gensim/models/ldamodel.py:375: DeprecationWarning: non integer (and non boolean) array-likes will not be accepted as indices in the future
  expElogbetad = self.expElogbeta[:, ids]
/Volumes/LocalDataHD/conda/envs/py34/lib/python3.4/site-packages/gensim/models/ldamodel.py:401: DeprecationWarning: non integer (and non boolean) array-likes will not be accepted as indices in the future
  sstats[:, ids] += numpy.outer(expElogthetad.T, cts / phinorm)
```

**Comment by piskvorky** [comment]
I think this may be related to this discussion: https://github.com/piskvorky/gensim/pull/448#issuecomment-139839622

Yes, we definitely want to get rid of these warnings!

**Comment by mattilyra** [comment]
So the offender is actually 561 which passes the `numpy`ified doc(s) into `.inference()`

    for chunk_no, chunk in enumerate(utils.grouper(corpus, chunksize, as_numpy=True)):                                                                                                                                                           
        reallen += len(chunk)  # keep track of how many documents we've processed so far
        if eval_every and ((reallen == lencorpus) or ((chunk_no + 1) % (eval_every * self.numworkers) == 0)):
            self.log_perplexity(chunk, total_docs=lencorpus)

Changing `as_numpy=False` seems to work, my suggested change above actually created some other weirdness.

**Comment by tmylk** [comment]
These DeprecationWarnings are not present in the latest build. Closing.
