### ISSUE TITLE
Passing `sentences=` to Doc2Vec() gives AttributeError: 'Doc2Vec' object has no attribute 'docvecs'

### ISSUE THREAD

**Issue by aleSuglia** [RaRe-Technologies/gensim#511]
Hi to all,
as stated in the issue's title, when I create the Doc2Vec object I receive the error _'Doc2Vec' object has no attribute 'docvecs'_ using this code:

```
    labeled_docs = [gensim.models.doc2vec.TaggedDocument(words=words, tags=[label])
                         for words, label in sentences]
    model = gensim.models.Doc2Vec(sentences=labeled_docs) 
```

I'm using the latest gensim version (0.12.2) on Archlinux. I've tried also with these versions:
- gensim 0.12.1 - same error
- gensim 0.10.3 - correctly works (using the appropriate method's parameters)

I think that there is something wrong in the current version of the library. 
May you help me with this kind of issue? 

Thank you in advance,
Alessandro

**Comment by gojomo** [comment]
In gensim 0.12+, the parameter to provide the (iterable) corpus in the Doc2Vec constructor is called `documents`, not `sentences`, to better hint that each text may be quite long (many sentences, often including punctuation as tokens). 

(I'll look into improving the error message that's triggered, since this is a natural mistake to make.)

**Comment by aleSuglia** [comment]
@gojomo Thank you for your answer. I have solved the problem changing the constructor call to:

      model = gensim.models.Doc2Vec(documents=labeled_docs, **parameters)

Effectively, using *sentences* as a parameter, generates the error that I've reported in the issue. This happens only with the latest versions. 

Cheers,
Alessandro

**Comment by gojomo** [comment]
(Re-opening as a TODO for myself to make the error better.)
