### ISSUE TITLE
Feature suggestion: wrapper for BigARTM

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#512]
A BSD library in C for Latent Dirichlet Allocation two times faster than VowpalWabbit. 

http://bigartm.org/

Would be good to use it from gensim seamlessly.

**Comment by piskvorky** [comment]
It looks like it implements the authors' own algorithm, [ Additive Regularization of Topic Models](http://www.machinelearning.ru/wiki/images/1/1f/Voron14aist.pdf), rather than LDA.

But yes, an investigation, comparison + gensim wrapper would be cool.

**Comment by dselivanov** [comment]
Yes, it implements non-bayesian framework for topic modelling.

**Comment by tmylk** [comment]
Update: new algo from https://linis.hse.ru/data/2016/12/08/1111900182/Parallel%20Non-blocking%20Deterministic%20Algo..ine%20Topic%20Modeling%20%D0%90%D0%BF%D0%B8%D1%88%D0%B5%D0%B2,%20%D0%A4%D1%80%D0%B5%D0%B9.pdf

**Comment by jayantj** [comment]
BigARTM has an existing (Python interface](https://github.com/bigartm/bigartm#interactive-python-interface). 
I haven't looked into how extensive the API is though.

**Comment by menshikh-iv** [comment]
Agree with @jayantj, not relevant for now.
