### ISSUE TITLE
GPU extension of Word2Vec needs self. chunksize and __init__(... chunksize=100 ...

### ISSUE THREAD

**Issue by niitsuma** [RaRe-Technologies/gensim#572]
I wrote extension Word2Vec using Keras an Theano.
https://github.com/niitsuma/word2vec-keras-in-gensim/blob/master/word2veckeras.py
This extension enables GPU train via Theano.
But chunksize is not the member variable of Word2Vec.
This makes writing simple extension difficult.

Plz add 
self. chunksize and __init__(... chunksize=100 ...
to gensim.models.word2vec.Word2Vec

**Comment by piskvorky** [comment]
@niitsuma @bhargavvader Can't you just add the attribute yourself? `my_model.chunksize = 100`.

Adding random dead (unused) code to gensim just so other libraries work seems very strange. That's a very peculiar API that these other libraries enforce.

The link in the issue description doesn't work, so I can't check what this is about.

**Comment by bhargavvader** [comment]
Makes sense. I made that addition because I figured it would be in more than one place, I was wrong. Do we just ignore this issue then?

**Comment by Sandy4321** [comment]
Thanks

**Comment by niitsuma** [comment]
I think it is better all tunable parameters(not only chunksize) are class member variables.
Let us consider the case model parameters are tuned by using sklearn GridSearchCV.
For example, in this code  https://github.com/niitsuma/word2vec-keras-in-gensim/blob/master/example/sentence-classify.py   the parameters of doc2vec  are tuned by using sklearn GridSearchCV.
sklearn GridSearchCV implicitly assumes all tunable parameter are class member variables.
Thus this simple implementation (  Doc2VecClassifier in  https://github.com/niitsuma/word2vec-keras-in-gensim/blob/master/word2veckeras/doc2veckeras.py ) can not tune chunksize by GridSearchCV.

**Comment by piskvorky** [comment]
Class member variables serve a special purpose in OOP and should definitely not be mixed with object variables.

I don't think sklearn expects any class variables either -- or I don't understand what you mean.

**Comment by tmylk** [comment]
@niitsuma You are using `word2vec` instead of `word2veckeras` in the `doc2veckeras`. May I ask why?

If you used `word2veckeras` then we wouldn't have to change the non-GPU w2v.

**Comment by niitsuma** [comment]
> You are using word2vec instead of word2veckeras in the doc2veckeras

That is for debugging.
Maybe you see test code part which tests whether the results of word2veckeras and gensim  are close enough or not.

**Comment by tmylk** [comment]
Just tyring to understand the reason for adding chunksize variable to Word2Vec. Is it to enable easier debugging/testing of Word2Veckeras?

**Comment by gojomo** [comment]
IIUC, it's because `chunksize`

**Comment by tmylk** [comment]
Closing as abandoned.
