### ISSUE TITLE
LDA convergence parameters

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#58]
There are variational parameters VAR_MAXITER and VAR_THRESH that guide convergence of LDA inference (both during training and document transformations). 

Currently they are set to a magic value which works well for online training over large corpora, but perhaps not so well for batch training over different corpora: http://groups.google.com/group/gensim/browse_thread/thread/d394a1fd8ee86450#

Add an option (**on** by default?) that sets these parameters automatically and transparently, based on the training dataset.

**Comment by menshikh-iv** [comment]
Resolved in #174
