### ISSUE TITLE
Make n_similarity return nan if one of the vectors is empty

### ISSUE THREAD

**Issue by aewhatley** [RaRe-Technologies/gensim#589]
Right now, Word2vec.n_similarity will return an array of nan values if one of its inputs is an empty list. I think that for consistency, it should return only one nan element.

**Comment by menshikh-iv** [comment]
Hi @aewhatley, can you show a concrete example (with dataset and model)?

**Comment by menshikh-iv** [comment]
Close, because it doesn't reproducible.
