### ISSUE TITLE
word2vec: Easily find number of words in vocabulary

### ISSUE THREAD

**Issue by hlin117** [RaRe-Technologies/gensim#618]
I posted [this question](http://stackoverflow.com/questions/35596031/gensim-word2vec-find-number-of-words-in-vocabulary) on stackoverflow a few days ago with not much success. Is there a way to find the number of words in word2vec's vocabulary?

It looks like it's not documented on the [web page](https://radimrehurek.com/gensim/models/word2vec.html) either.

**Comment by gojomo** [comment]
I've answered there. A better place for questions is the project discussion list, https://groups.google.com/forum/#!forum/gensim – Github issues should be reserved for bugs/feature-requests.

**Comment by hlin117** [comment]
Thanks gojomo. 

I guess the original intention of my post was to perhaps add a feature to word2vec such that 1. It's easier to get the number of words in the vocabulary, and 2. To document this feature.

Do you think a PR that defines the following function is appropriate?

```
def __len__(self):
    return len(self.vocab)
```

We could even do a property

```
@property
def n_words(self):
    return len(self.vocab)
```

What do you think?

**Comment by gojomo** [comment]
Since directly working with dicts is so idiomatic in Python, I think I'd prefer highlighting the dict as a de facto part of the API. For example, have the module/class doc comments mention 'vocab', & perhaps show examples of using it for finding the overall vocabulary size or the count of particular tokens. (Thoughts @piskvorky ?)

**Comment by cscorley** [comment]
That's a similar/same idea as in #566.

**Comment by tmylk** [comment]
Duplicte of #566
