### ISSUE TITLE
Update doc2vec tutorial

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#629]
The [doc2vec tutorial](http://rare-technologies.com/doc2vec-tutorial/) is obsolete post release 0.12.0 but people still use it and report errors.

A notebook which is more introductory than [IMDB tutorial ](https://github.com/piskvorky/gensim/blob/develop/docs/notebooks/doc2vec-IMDB.ipynb) is needed,

**Comment by gojomo** [comment]
Some ideas that could be in one or several improved demo/tutorial notebooks:

* a super-beginner demo, perhaps based on the same toy-sized bundled dataset used for unit-testing (lee_background.cor: 300 docs of a couple hundred words each) – would illustrate a few different options, highlight common points-of-confusion like:
 * can do it all in one step by supplying corpus to constructor, or manually `build_vocab()`/`train()`
 * use logging output to verify proper version, optimizations, progress, memory-usage
 * can use `iter` to set passes
 * DBOW doesn't train words without `dbow_words`
 * docvecs & wordvecs accessed/compared separately
 * inferring vector for a new text

* something based on 20newsgroups to demonstrate classification tasks
 * most basic would do unspervised doc-vec training, then use sklearn classifier(s)
 * advanced tips would tune/search Doc2Vec parameters, or re-infer vectors, or try mixing in known-labels, for incremental classification improvement

* a reordering/simplification/expansion of the existing IMDB-sentiment notebook 
 * one very simple pass to demo the basics
 * later steps to compare training modes or apply other tricks

* a notebook applying Doc2Vec to a Wikipedia dump in the style of the 'Document Embedding With Paragraph Vectors' paper, including its word+doc vector algebra and category-based quality evaluation

**Comment by ziky90** [comment]
In addition to gojomo's ideas:

- If you'd be interested I can create small example of how to use Doc2Vec also on biological sequences, particularly protein primary structures. It would be more or less based on this paper: http://arxiv.org/abs/1503.05140

**Comment by piskvorky** [comment]
@ziky90 sure! More docs are always welcome.

**Comment by Piezoid** [comment]
@ziky90 I did some basic experiments with doc2vec on Uniprot sequences (same setup : 3 delayed frames yielding 3 characters words). I find it amazing because it doesn't require any prior knowledge about the amino-acids. (It can be applied to exobiology !)
I'm also interested in modeling sequences with gaps (for example, Pfam seeds) and annotated with active sites localization. I'm wondering how it fits in the NLP embedding framework (custom contexts ?).

Anyway, if this is really a thing, maybe we should start a separate thread elsewhere...

**Comment by ddofer** [comment]
It would be useful to avoid too much "black box magic" when building the tutorials: i.e the data loading and format.

**Comment by tmylk** [comment]
Fixed in

https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/doc2vec-lee.ipynb
 https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/doc2vec-IMDB.ipynb
https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/doc2vec-wikipedia.ipynb
https://github.com/RaRe-Technologies/movie-plots-by-genre
