### ISSUE TITLE
Publish Linux wheels

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#639]
pip now supports wheels for Linux and we should add this support to make Gensim installation easier.

https://github.com/pypa/manylinux

**Comment by souravsingh** [comment]
I would like to work on the issue. How do I start?

**Comment by tmylk** [comment]
@souravsingh Thanks a lot for stepping up! 

The task is to contribute a PR to this repo https://github.com/matthew-brett/manylinux-builds

You can use this [build](https://github.com/matthew-brett/manylinux-builds/blob/master/build_sklearns.sh) as a template. Also the [gensim on OSX](https://github.com/MacPython/gensim-wheels) repo might be relevant.

**Comment by tmylk** [comment]
@droudy has created the wheels in https://github.com/tmylk/gensim-manylinux

It needs some finishing touches

**Comment by piskvorky** [comment]
@droudy @tmylk any progress on the finishing touches?

**Comment by souravsingh** [comment]
@droudy Can you tell me what was the problem with the manylinux repo? Looking here https://github.com/matthew-brett/manylinux-builds/pull/10, it seems there is a problem with scipy build.

**Comment by droudy** [comment]
@souravsingh There were issues with several packages failing to build for python 2.6 and 3.3 and the decision was to remove support for python 2.6 and 3.3.

**Comment by tmylk** [comment]
The latest is in https://github.com/tmylk/gensim-manylinux

**Comment by Sandy4321** [comment]
Lev
thank you very much for you tube video in Russian
only may youhelp find notbook file you used with code
Spasibo
Sander

**Comment by yuvipanda** [comment]
Can those wheels be published to PyPI now? :D It would be pretty awesome!

**Comment by menshikh-iv** [comment]
@tmylk @droudy @souravsingh what're staus here?

**Comment by souravsingh** [comment]
Nothing was done about fixing the manylinux repo. Should we have linux wheels for gensim, considering we have tarballs for gensim on conda and ``pip install`` works fine?

**Comment by menshikh-iv** [comment]
@souravsingh wheels needed only for linux users **without** compiler. For my opinioun, this can be useful, but it's not obligatory

**Comment by markroxor** [comment]
@menshikh-iv
