### ISSUE TITLE
Adding cores leads pre built similarites error

### ISSUE THREAD

**Issue by VikingMew** [RaRe-Technologies/gensim#647]
i tried to add one core in my virtual macine to speed up.
Then I found the cache in similarities is different from the vector calculated on demand.
When I remove the core, the behaviour is recovered.
Is there any ideas for the problem?

**Comment by piskvorky** [comment]
I don't understand the report. Please follow the [bug reporting instructions](https://github.com/piskvorky/gensim/blob/develop/CONTRIBUTING.md) (always displayed when you create a new issue).

**Comment by tmylk** [comment]
Closing as abandoned
