### ISSUE TITLE
Find keywords using entropy with Montemurro and Zanette algorithm

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#665]
The algorithm identifies words that are significant to the structure of the document - these often correspond to the major themes. It does so independently of a corpus.

Dr Peter J. Bleackley has kindly suggested [his implementation](https://sourceforge.net/p/entropy-calculator/code/HEAD/tree/trunk/EntropyCalculator.py)

**Comment by PeteBleackley** [comment]
However, I feel that it will need a few modifications to its API for fit in nicely with the rest of Gensim, and would like some advice form the core Gensim developers.
My questions are

1. Where would be the best place to fit this algorithm into the Gensim project structure?
2. In what format should the algorithm ingest data? The current implementation is designed for XML, mainly for historic reasons.
3. In what format should the algorithm return its results?

Once I have answers to these questions, it shouldn't take too long to modify my code accordingly.

**Comment by tmylk** [comment]
Nice meeting you again yesterday. I will put this algo on our student page.

**Comment by PeteBleackley** [comment]
I'll be happy to advise any student who takes this project on.

**Comment by bhargavvader** [comment]
If there is interest for this and no one else wishes to take it up, I would like to give it a shot. :)

**Comment by piskvorky** [comment]
@bhargavvader sounds good, thanks!

@tmylk can you add some context to this ticket? What is "Montemurro and Zanette algorithm"?

**Comment by PeteBleackley** [comment]
Here's a link to a paper describing the algorithm.

https://arxiv.org/abs/0907.1558

**Comment by piskvorky** [comment]
@tmylk ticket context still missing, update.

**Comment by tmylk** [comment]
@piskvorky Could you please suggest a way to add context? The context is clear to me, with relevant links. There is even a volunteer contributor.

**Comment by piskvorky** [comment]
Sure -- something along the lines of "Here's a problem / motivation; here's what we could do to solve it".

The first part is missing -- from the link it's not apparent to me what "Montemurro and Zanette algorithm" does, and the link to the implementation doesn't explain it either.

If this is implemented, what will it actually do? Who is it for?

**Comment by PeteBleackley** [comment]
The algorithm identifies words that are significant to the structure of the document - these often correspond to the major themes. It does so independently of a corpus.

**Comment by piskvorky** [comment]
Aha, thanks. So this is a candidate to replace the `summarization.keywords` package, if I understand correctly.

It would be interesting to compare them side-by-side, see which algo works better (and deprecate the other one -- we don't want to maintain dead weight in gensim).

Or if the algorithms have non-overlapping strengths/weaknesses, document what they are. When should users use one or the other? Is there a standard benchmark? (@tmylk Qs for the incubator project)

**Comment by PeteBleackley** [comment]
I've implemented this in https://github.com/RaRe-Technologies/gensim/pull/1738. However, there is a merge conflict in summarization/__init__.py that needs to be resolved.
