### ISSUE TITLE
default-value of 'hs' (hierarchical-softmax) parameter changed w/o explicit warning in 0.12.4

### ISSUE THREAD

**Issue by Tensordry** [RaRe-Technologies/gensim#673]
In vs. 0.12.4, the new default of 'hs=0' stays in accordance with the online documenation, but is in contrast to the default-behavior of versions <= 0.12.2. 
If not set explicitely set to 'hs=1', the w2vec.score() function will fail with the error message "we have only implemented score for hs". In a productive environment, this error message might appear as not trivial, and is assumed to be more productive when pointing directly to the change-need of the model-parameters.

**Comment by piskvorky** [comment]
Thank you for reporting @Tensordry! I agree the message is not very illuminating, especially if this comes up as "default" now.

@gojomo @mataddy can you look into this and suggest a fix?

**Comment by gojomo** [comment]
@Tensordry – Would simply having the error repeat the same language from the doc-comment be sufficient? The doc-comment presently says:

    We have currently only implemented score for the hierarchical softmax scheme, so you need to have run word2vec with hs=1 and negative=0 for this to work.

**Comment by Tensordry** [comment]
Hello Gordon,

  * From my point of view: an additional reference to the changed default-value, as a likely
    cause for the surprising stopping behavior of the lib, would have been a time-saver for me.
    So I guess, the error message gets even more improved, by adding your proposal plus such a
    reference ... ;-)




Am 20.04.2016 um 11:07 schrieb Gordon Mohr:
