### ISSUE TITLE
how to compute the loss?

### ISSUE THREAD

**Issue by arianhosseini** [RaRe-Technologies/gensim#686]
Hi, I'm working on a paper, after reading the python code, it looks like the "**gradient** of loss" is calculated in:
`fb = 1. / (1. + exp(-dot(l1, l2b.T)))`
`gb = (model.neg_labels - fb) * alpha`

I want to be able to get the **loss** of an input and not the gradient of it, is there anyway to get that? is there any function that does so? 

thanks for sharing

**Comment by menshikh-iv** [comment]
Looks like resolved in #1201.
