### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by lucasrodes** [RaRe-Technologies/gensim#687]
Hi, 
I am working on Mac OS El Capitan. I just cloned the "develop" branch and first did the test:
`$ python setup.py test`

Which seems that outputs some errors, find the last lines below:
```

======================================================================
FAIL: test_getitem_sparse2sparse (gensim.test.test_sharded_corpus.TestShardedCorpus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lucasrodes/Documents/Git/gensim/gensim/test/test_sharded_corpus.py", line 169, in test_getitem_sparse2sparse
    self.assertTrue(isinstance(ilist, sparse.csr_matrix))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 273 tests in 422.680s

FAILED (failures=1, skipped=8)
```
Afterwards I install it:

`$ sudo python setup.py install`

And it looks like it finished correctly: 
```
Using /Library/Python/2.7/site-packages/boto-2.40.0-py2.7.egg
Finished processing dependencies for gensim==0.12.4
```

Once installed, I wanted to test it following the example published by Radim (http://rare-technologies.com/word2vec-tutorial/) but it crashed:

```
>>> model = gensim.models.Word2Vec(sentences)
2016-05-02 00:03:10,575 : INFO : collecting all words and their counts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gensim/models/word2vec.py", line 448, in __init__
    self.build_vocab(sentences, trim_rule=trim_rule)
  File "gensim/models/word2vec.py", line 512, in build_vocab
    self.scan_vocab(sentences, progress_per=progress_per, trim_rule=trim_rule)  # initial survey
  File "gensim/models/word2vec.py", line 523, in scan_vocab
    for sentence_no, sentence in enumerate(sentences):
  File "<stdin>", line 5, in __iter__
NameError: global name 'os' is not defined
```

What am I doing wrong?

**Comment by gojomo** [comment]
You likely need to `import os` before where the `MySentences` class is defined. The tutorial should probably show that step. (cc @piskvorky)

**Comment by piskvorky** [comment]
@tmylk please fix it = add the import before `MySentences`.

Be careful that you **edit the blog post in "text mode"**, as Wordpress messes up raw formatting and inline tags if you switch to "visual". Double check that everything works after you save, including the demo app.

**Comment by tmylk** [comment]
Fixed in https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/word2vec.ipynb

Such problems will be avoided in the future as we run ipynb code in CI.
