### ISSUE TITLE
PyPI stats

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#693]
I just noticed gensim has had 0 downloads in the past week(s).

That is very unlikely, and probably points to some issue with download / install / PyPI repo / PyPI stats.

Look into what's happening & fix ASAP.

**Comment by piskvorky** [comment]
Actually, it seems all PyPI packages have the same problem. I tried installing gensim and it worked fine... so probably just a bug in PyPI download stats, nothing critical.

I'll leave this open in case anyone knows what's going on.

**Comment by cscorley** [comment]
PyPI seems to be aware of the issue: https://bitbucket.org/pypa/pypi/issues/396

**Comment by tmylk** [comment]
Fixed at pypi

**Comment by piskvorky** [comment]
@tmylk I suggest we remove / comment out the "PyPI downloads" badge, until this is resolved.

Right now, it just looks weird and serves no purpose.

**Comment by piskvorky** [comment]
@tmylk ping. All the other badges seem broken too at the moment, not sure what's going on.

**Comment by piskvorky** [comment]
@tmylk PyPI still displays the download stats, even though the rc1 should have them already removed?

**Fix before the full release** -- we don't want to be displaying `0 downloads/month`, that's just silly.

**Comment by tmylk** [comment]
No downloads info at https://pypi.python.org/pypi/gensim
