### ISSUE TITLE
ImportError: No module named six.moves

### ISSUE THREAD

**Issue by lucasrodes** [RaRe-Technologies/gensim#694]
Hi,
I am trying to install gensim in a remote server I do not have root privileges at and I am having some problems. By the way, it uses Linux:
```
$ cat /proc/version
Linux version 3.9.10-100.fc17.x86_64 (mockbuild@bkernel01.phx2.fedoraproject.org) (gcc version 4.7.2 20120921 (Red Hat 4.7.2-2) (GCC) ) #1 SMP Sun Jul 14 01:31:27 UTC 2013
```

As stated in [Installation](http://radimrehurek.com/gensim/install.html) (point 3 under **Install gensim**), I simply downloaded the file (i.e. i did a `git clone`) and changed the PYTHONPATH at the bash_profile file as:

```
export PYTHONPATH="/directory/gensim"
```

where `directory` is my my working directory. I think this is OK, since:
 
```
$ echo $PYTHONPATH
/directory/speech00/gensim
```

However, wen running python I get this error:

```
$ python
Python 2.7.3 (default, Jul 24 2012, 10:05:38) 
[GCC 4.7.0 20120507 (Red Hat 4.7.0-5)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gensim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/directory/gensim/gensim/__init__.py", line 6, in <module>
    from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
  File "/directory/gensim/gensim/parsing/__init__.py", line 6, in <module>
    from .porter import PorterStemmer
  File "/directory/gensim/gensim/parsing/porter.py", line 35, in <module>
    from six.moves import xrange
ImportError: No module named six.moves
```

I have done some research and have found some threads. However they talk about installing the last update of gensim, which I already have, or about upgrading six, which I do not know what it is and since I do not have root privileges might be difficult to do.

I appreciate your time and help.
Thanks!

**Comment by lucasrodes** [comment]
# Solution

This can be easily solved by installing six in my user directory, i.e. :

```
$ pip install --user six
```

Afterwards, I compiled the project using `$ python setup.py install --user`. Finally, I upgraded numpy since I had a very old version by typing `$ pip install --user numpy --upgrade`. Now seems to work.

**Comment by tmylk** [comment]
Can't reproduce. `six` is a dependency is in setup.py so should have been installed.
