### ISSUE TITLE
Change word2vec default to avoid lowercasing

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#714]
Make default `model.accuracy("file", use_lowercase=False)`.
to fix the [mailing list question](https://groups.google.com/d/msg/gensim/Zq-ZAutQdF8/ORbw1KKBBAAJ)

See related PR https://github.com/piskvorky/gensim/pull/607

**Comment by gojomo** [comment]
Even though this fixes things for the case of loading the GoogleNews vectors, I'm not sure this will improve things other common cases – people often lowercase their training data.

**Comment by piskvorky** [comment]
What does the C tool do, these days? Let's emulate that.

**Comment by gojomo** [comment]
A quick glance suggests compute-accuracy.c in the original package force-uppercases for all string-comparisons, with the effect that they count the analogy as 'correct' if the closest-word is any of the potentially case-varied versions in the vocabulary. Unfortunately, the `use_lowercase` parameter forced in either way doesn't quite emulate that behavior – the comparison of `predicted` & `expected` would need to be changed instead. Still pretty easy – but the parameter should probably be named 'case_insensitive' instead, and not just transform the question-words.

**Comment by piskvorky** [comment]
OK, let's do that.

I'll leave this issue open with the `easy` label.

**Comment by jayantj** [comment]
Came across this issue too when I noticed the gensim word2vec model using a lower number of analogies for computing accuracy, as compared to some other implementations. It might not be as easy as making the comparison of `predicted` and `expected` case-insensitive. 
```
try:
    if use_lowercase:
        a, b, c, expected = [word.lower() for word in line.split()]  # assumes vocabulary preprocessing uses lowercase, too...
    else:
        a, b, c, expected = [word for word in line.split()]
except:
    logger.info("skipping invalid line #%i in %s" % (line_no, questions))
if a not in ok_vocab or b not in ok_vocab or c not in ok_vocab or expected not in ok_vocab:
    logger.debug("skipping line #%i with OOV words: %s" % (line_no, line.strip()))
    continue
```
[Source](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/word2vec.py#L1602-L1626)

The key check of the analogy word existing in the vocab would return false and the analogy would be skipped.

The original C code works around this by creating an all-uppercase vocabulary from the model files (specifically for `compute-accuracy.c`), and uppercasing all analogy words too.

The only way to completely emulate that seems creating a new copy of the vocabulary which would be case-insensitive/uppercase. That might increase memory usage too much. Suggestions?

**Comment by gojomo** [comment]
In a sense, the `compute-accuracy.c` approach could even be considered a form of cheating on the analogies: all varied-case variants of a word survive, as repeat all-caps entries, and if any of them are the top-match for the target vector, it's counted as correct.

Still, I see the value in offering an option that mimics its calculation. It's typical to trim such tests to some set of most-frequent words in any case, so the memory overhead of an extra dict of "ALLCAPS" keys to indices is probably survivable. A user willing to destructively modify their model could, as a workaround, change `model.vocab` to have all-caps keys, then test accuracy. But an option on the method should probably use a temporary non-destructive case-forced existence-lookup.

**Comment by jayantj** [comment]
Yep, it does seem a little like cheating. Best to make `case_insensitive=False`, by default?

I'll submit a fix for this then?

**Comment by gojomo** [comment]
We've generally copied to word2vec-package defaults, for minimum surprise when converting over or comparing results. And, the main reason for this 'accuracy' being included is the way it was popularized as an evaluation by that paper/package. 

So even though I'd personally consider  `case_insensitive=False` the more flexible/defensible choice, the actual default should be the same behavior as `compute-accuracy.c`. 

But, still be sure that case-sensitive behavior is a prominent well-documented alternate option, for people who may be training case-sensitive tokens and care about case-varied distinctions. 

Thanks!
