### ISSUE TITLE
Getting started datasets

### ISSUE THREAD

**Issue by bartjkdp** [RaRe-Technologies/gensim#717]
The [tutorial dataset](http://radimrehurek.com/gensim/tut1.html) is rather small and the [Wikipedia dataset](http://download.wikimedia.org/enwiki/) is rather large. It would be nice to provide some datasets that are somewhere in between to help people getting started.

We could also provide a nice interface to download these datasets, similar to [scikit-learn](http://scikit-learn.org/stable/datasets/) that aids at downloading these datasets. This will simplify the tutorials.

**Comment by robotcator** [comment]
Hello, I also think it is nice to provide a nice API to download the corpus. So anyone works on this?
As I often use the text8.zip dataset in my experiment, I write an script to download from the Internet. (https://gist.github.com/robotcator/1fb0cdc1437515f5662d33368554f4c8)

**Comment by macks22** [comment]
Some good candidate datasets are:
* [20 Newsgroups](http://qwone.com/~jason/20Newsgroups/)
* [NSF Research Award Abstracts 1990-2003](https://archive.ics.uci.edu/ml/datasets/NSF+Research+Award+Abstracts+1990-2003)
* [Reuters-21578 Text Categorization Collection](https://archive.ics.uci.edu/ml/datasets/Reuters-21578+Text+Categorization+Collection)
* [Reuters Corpus Volume I (RCV1) v2](http://www.jmlr.org/papers/volume5/lewis04a/lyrl2004_rcv1v2_README.htm)
* [WebKB](http://www.cs.umb.edu/~smimarog/textmining/datasets/) -- [original here](http://www.cs.cmu.edu/~webkb/)
* [USPTO Patent Grant Full Text subsets](https://www.google.com/googlebooks/uspto-patents-grants-text.html)

**Comment by macks22** [comment]
Some nice references for how to implement:
* [scikit 20 newsgroup fetch function](https://github.com/scikit-learn/scikit-learn/blob/14031f6/sklearn/datasets/twenty_newsgroups.py#L154)
* [streaming file download in Python](https://stackoverflow.com/a/5397438/2486302)
* [nltk downloader code](https://github.com/nltk/nltk/blob/develop/nltk/downloader.py)

**Comment by menshikh-iv** [comment]
Resolved in #1705.

**Comment by piskvorky** [comment]
@menshikh-iv which of the datasets from @macks22 are there? #1705 is rather sparse on information.

We **especially** want all the practical, domain-specific corpora: USPTO patents, the Quora QA duplicates dataset, the PubMed corpus…
