### ISSUE TITLE
testGetDocumentTopics and testTermTopics fail in Appveyor and OSX in MultiCoreLDA

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#740]
See comments in https://github.com/piskvorky/gensim/pull/656 for details.

it is blocking the 0.13.0rc1 from becoming a release.

**Comment by bhargavvader** [comment]
Do you mean #704 ? 
It's weird that this is happening - it worked fine before. PR #741 addresses (hopefully!) `testGetDocumentTopics`, I'll open a PR to deal with `testTermTopics`.

**Comment by bhargavvader** [comment]
@tmylk , any luck with this?

**Comment by bhargavvader** [comment]
@tmylk , has this been resolved?

**Comment by tmylk** [comment]
Fixed in #741 and #742
