### ISSUE TITLE
In the model of DBOW,why didn't use the concatenation or mean of the paragraph vector with the word vectors to predict other words in a text window.

### ISSUE THREAD

**Issue by MingJiaAn** [RaRe-Technologies/gensim#745]
@gojomo ,Hi~gojomo ,i'm a novice of doc2vec,my understanding for DBOW of doc2vec is not very good.
In the model of DBOW,why didn't use the concatenation or mean of the paragraph vector with the word vectors to predict other words in a text window? I think it maybe add more semantics information to the paragraph vector.

**Comment by gojomo** [comment]
Hi, @MingJiaAn. The project forum at https://groups.google.com/forum/#!forum/gensim is a better place for open-ended discussions/suggestions about the library. These issues are intended for specific bugs and feature-requests. 

(With regard to your question: the original ['Paragraph Vectors' paper](https://arxiv.org/abs/1405.4053) defines PV-DBOW as only using the overall paragraph-vector to predict words. In contrast, it offers PV-DM as an alternative which combines the overall paragraph-vector with context-window words to predict. Gensim's Doc2Vec follows those definitions in its implementations.)
