### ISSUE TITLE
Link to common datasets

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/gensim#746]
There's a bunch of datasets and even trained models, that are suitable as gensim input.

Collect them and create and promote a page that links to these resources.

Example:
- GloVe vectors by NLP stanford: http://nlp.stanford.edu/data/glove.840B.300d.zip
- various LSI/LDA/word2vec models trained on Wikipedia (I think I saw English, German, Spanish)

**Comment by panamantis** [comment]
Here's another resource.  I'm still looking for a doc2vec
https://github.com/3Top/word2vec-api#where-to-get-a-pretrained-models

**Comment by tmylk** [comment]
Hi @panamantis Thanks for the link. Did you come across any pre-trained doc2vec models?

**Comment by joyjeni** [comment]
I m checking pretrained word2vec and topicmodelling models mentioned  in https://github.com/ai-ku/wvec
and
http://www.pdhillon.com/code.html

**Comment by chinmayapancholi13** [comment]
Hey! I found the following resources to be relevant as well. 
https://github.com/alexandres/lexvec
http://cistern.cis.lmu.de/meta-emb/
https://github.com/icoxfog417/fastTextJapaneseTutorial
https://levyomer.wordpress.com/2014/04/25/dependency-based-word-embeddings/
http://www.socher.org/index.php/Main/ImprovingWordRepresentationsViaGlobalContextAndMultipleWordPrototypes

**Comment by tmylk** [comment]
More pre-trained word2vec models from @akutuzov 

http://ltr.uio.no/semvec/en/about#models

**Comment by akutuzov** [comment]
@tmylk the preferred link to the WebVectors service has changed:
http://ltr.uio.no/semvec/ is deprecated, the correct URL now is http://vectors.nlpl.eu/explore/embeddings/

**Comment by menshikh-iv** [comment]
Will be resolved in #1492

**Comment by menshikh-iv** [comment]
Resolved in #1705

**Comment by piskvorky** [comment]
@menshikh-iv which of the resources above (from @akutuzov , @chinmayapancholi13 , @joyjeni , @panamantis ) are already included? Any plans to include others (where relevant)? Thanks.
