### ISSUE TITLE
Attribute naming inconsistency between HdpModel and LdaModel

### ISSUE THREAD

**Issue by pbellon** [RaRe-Technologies/gensim#747]
When using `model.show_topics` on these two different models there is an inconsistency between parameters names:
- In `LdaModel` we can see `num_topics`, `num_words` 
- where in `HdpModel` those attributes are written `topics` and `topn`.

**Comment by tmylk** [comment]
Fixed in https://github.com/RaRe-Technologies/gensim/pull/755
