### ISSUE TITLE
Inconsistent behavior between 0.12.1 and 0.12.3

### ISSUE THREAD

**Issue by document-distillery** [RaRe-Technologies/gensim#759]
I'm running LdaMulticore on ~500k line corpus. On my laptop (gensim 0.12.3 installed), with 7 workers it uses about 1GB per worker and 2.5GB on the driver. When I move this to a hadoop cluster and run the same code with 7 workers (using a shell action in an oozie workflow) the memory blows out the YARN container with a whopping 80GB memory footprint. The hadoop cluster is running version 0.12.1. 

Are there differences between the LdaMulticore implementations in 0.12.1 and 0.12.3 that could explain this? Or could there be issues with running multicore Python processes from within YARN containers?  

Thanks!

**Comment by tmylk** [comment]
@document-distillery There have been changes to LDA in 0.12.2 and 0.12.3 See [CHANGELOG](https://github.com/RaRe-Technologies/gensim/blob/develop/CHANGELOG.md)

Could you please run 0.12.3 on Hadoop and see if it is better?

If it is still using a lot of RAM then a log and code would be helpful. Thanks

**Comment by tmylk** [comment]
Abandoned. Guessing it was fixed with 0.12.3

**Comment by document-distillery** [comment]
Yes, that fixed it. Thanks
