### ISSUE TITLE
questions-words.txt not available in google code repository

### ISSUE THREAD

**Issue by iCoolchar** [RaRe-Technologies/gensim#760]
in this file
https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/word2vec.py
line 1567
> See https://code.google.com/p/word2vec/source/browse/trunk/questions-words.txt for an example.

the file mentioned in the comment is not available
I found one in
https://github.com/arfon/word2vec/blob/master/questions-words.txt
But I don't know if it's official, maybe you should update the comment to refer to a stable one.

Thanks!

**Comment by tmylk** [comment]
Thanks. Fixed. 
The official one is linked in our [tutorial](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/word2vec.ipynb) to  https://storage.googleapis.com/google-code-archive-source/v2/code.google.com/word2vec/source-archive.zip

**Comment by LeBrave2015** [comment]
Thanks!
