### ISSUE TITLE
MalletWrapper load_word_topics()  to return value

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#764]
load_word_topics() doesn't return anything but stores the word topics internally in self.wordtopics.

It shouldn't set internal vars, but rather return the result to the caller (train), who should then assign it to internal object attributes.

https://github.com/RaRe-Technologies/gensim/commit/db70d04c650633cf2d1c0735c3cbd60cc3b36d77#commitcomment-18054588

**Comment by bhargavvader** [comment]
I'll take this up.

**Comment by bhargavvader** [comment]
We can close this now.
