### ISSUE TITLE
LDA u_mass coherence calculation triggers numpy deprecation warning

### ISSUE THREAD

**Issue by masscognition** [RaRe-Technologies/gensim#765]
Using Python 2.7.11, latest gensim , latest numpy.

Line 41 of segmentation.py:

for w_star in top_words[:w_prime_index]:

triggers this warning from numpy:

DeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future

fix is to cast w_prime_index to int 

Also via Devashish: 

"the comment right next to

w_prime_index = np.where(top_words == w_prime)[0] should be # To get index of w_prime in top_words (apologies for my mistake)."

**Comment by dsquareindia** [comment]
Thanks for raising this issue! Would you mind raising a PR fix for this? You can follow a workflow similar to that given here: http://scikit-learn.org/stable/developers/contributing.html#contributing-code. Would be happy to help if you encounter any problems.

**Comment by dsquareindia** [comment]
Sorry @masscognition I addressed this issue in #793 since I happened to be working on the same thing. Thanks for raising the issue though!

**Comment by masscognition** [comment]
No problem :-)
