### ISSUE TITLE
Usage of topn in dtmmodel breaks print_topics and show_topics.

### ISSUE THREAD

**Issue by bhargavvader** [RaRe-Technologies/gensim#769]
After #755 was merged, `topn` was changed to be `num_words`, but because this was not changed everywhere (line [283](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/wrappers/dtmmodel.py#L283), line [300](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/wrappers/dtmmodel.py#L300)) it would throw up `NameError: name 'topn' is not defined` whenever `self.print_topics` or `self.show_topics` was called (because of line [274](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/wrappers/dtmmodel.py#L274)).

This pretty much means that dtm wrapper is unusable wrt displaying any topics, putting in a PR to fix this.

**Comment by piskvorky** [comment]
@tmylk how do you review these PRs before merging?

There are too many errors, we cannot merge code so carelessly.

**Comment by bhargavvader** [comment]
No, this was after that in 0.13.2. 
I noticed it because when I was testing the #768 solution, `print_topics` was failing.
