### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'int' objects

### ISSUE THREAD

**Issue by vsuriya93** [RaRe-Technologies/gensim#787]
Hi, I am trying to build a word2vec model. When I am calling 

model=Word2Vec(sentences,min_count=1)

It gives the following error.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-d892adca4bd3> in <module>()
----> 1 model=Word2Vec(sentences,min_count=1)

/usr/local/lib/python2.7/dist-packages/gensim-0.12.4-py2.7-linux-x86_64.egg/gensim/models/word2vec.py in __init__(self, sentences, size, alpha, window, min_count, max_vocab_size, sample, seed, workers, min_alpha, sg, hs, negative, cbow_mean, hashfxn, iter, null_word, trim_rule, sorted_vocab, batch_words)
    442             if isinstance(sentences, GeneratorType):
    443                 raise TypeError("You can't pass a generator as the sentences argument. Try an iterator.")
--> 444             self.build_vocab(sentences, trim_rule=trim_rule)
    445             self.train(sentences)
    446 

/usr/local/lib/python2.7/dist-packages/gensim-0.12.4-py2.7-linux-x86_64.egg/gensim/models/word2vec.py in build_vocab(self, sentences, keep_raw_vocab, trim_rule)
    508         self.scan_vocab(sentences, trim_rule=trim_rule)  # initial survey
    509         self.scale_vocab(keep_raw_vocab=keep_raw_vocab, trim_rule=trim_rule)  # trim by min_count & precalculate downsampling
--> 510         self.finalize_vocab()  # build tables & arrays
    511 
    512     def scan_vocab(self, sentences, progress_per=10000, trim_rule=None):

/usr/local/lib/python2.7/dist-packages/gensim-0.12.4-py2.7-linux-x86_64.egg/gensim/models/word2vec.py in finalize_vocab(self)
    638             self.vocab[word] = v
    639         # set initial input/projection and hidden weights
--> 640         self.reset_weights()
    641 
    642     def sort_vocab(self):

/usr/local/lib/python2.7/dist-packages/gensim-0.12.4-py2.7-linux-x86_64.egg/gensim/models/word2vec.py in reset_weights(self)
    984         for i in xrange(len(self.vocab)):
    985             # construct deterministic seed from word AND seed argument
--> 986             self.syn0[i] = self.seeded_vector(self.index2word[i] + self.seed)
    987         if self.hs:
    988             self.syn1 = zeros((len(self.vocab), self.layer1_size), dtype=REAL)

TypeError: cannot concatenate 'str' and 'int' objects

How to fix this? Is there anything wrong with the way input is specified?

Thanks

**Comment by piskvorky** [comment]
```python
--> 986 self.syn0[i] = self.seeded_vector(self.index2word[i] + self.seed)
```

I don't see any such line in gensim. Please follow the bug-reporting-process from our [CONTRIBUTING.md guide](https://github.com/RaRe-Technologies/gensim/blob/develop/CONTRIBUTING.md).

**Comment by prateekg** [comment]
Is the issue resolved or is it still showing any error ?
Can you provide a exact syntax error.

**Comment by tmylk** [comment]
Closing as abandoned.
