### ISSUE TITLE
Fail Update corpus

### ISSUE THREAD

**Issue by carlos386386** [RaRe-Technologies/gensim#790]
hi,
I'm trying update the corpus

My code is:

ldamodel = gensim.models.ldamodel.LdaModel(corpus=corpus1, id2word=dictionary, update_every=500, passes=20)

ldamodel.update(corpus=corpus2)

but i catch this exception:
![image](https://cloud.githubusercontent.com/assets/10063469/16831691/a803e1cc-49a6-11e6-930f-5655cab1deca.png)

How can i solve?

Thank you in advance

**Comment by tmylk** [comment]
@carlos386386 How did you resolve it? Interesting to know for future users.

**Comment by carlos386386** [comment]
Hy tmylk, i have posted in the next link: 
https://groups.google.com/d/msg/gensim/T0GMxE7YZqM/7rY-sxwaMAAJ

**Comment by carlos386386** [comment]
Hy tmylk, i have posted in the next link:

**Comment by tmylk** [comment]
Answered on the mailing list in https://groups.google.com/d/msg/gensim/T0GMxE7YZqM/7rY-sxwaMAAJ
