### ISSUE TITLE
Doc2Vec defaults shouldn't override Word2Vec defaults without good reason

### ISSUE THREAD

**Issue by gojomo** [RaRe-Technologies/gensim#795]
Following #534, Word2Vec matches the word2vec.c defaults (as of the time Google stopped updating/maintaining that code). However, where our Doc2Vec class takes its own parameters – `hs`, `negative`, `sample`, `window`, and `dm_mean` – it's still using the older defaults. There's not really any case that these older defaults are better – and in some cases they're probably worse. 

Unless there's a reason for different defaults, Doc2Vec should use the same values as Word2Vec... ideally by not specifying them at all (to avoid duplication). This probably means removing those params from the `__init__()` signature – but still documenting them in the doc-comment – so that the extra keywords just pass through to `Word2Vec.__init__()` if/when present.

**Comment by SebastinSanty** [comment]
Hi! I would like to work on this bug.
