### ISSUE TITLE
Make gensim not import theano

### ISSUE THREAD

**Issue by Waateur** [RaRe-Technologies/gensim#802]
Hello, 
I'm looking for a way to not import theano when I import gensim. 

Sometime I just want to import corpus made with gensim and if I import theano in the same script, gensim mess with my theano session.

Do you know any way to do this ?

**Comment by piskvorky** [comment]
Yes, there's an open issue for not importing theano: https://github.com/RaRe-Technologies/gensim/issues/696#issuecomment-218332228

CC @tmylk , that ticket is very old and needs resolution.

@Waateur Not sure what you mean by "gensim mess with mu theano session"... how can importing  theano from gensim mess with your theano session?

**Comment by Waateur** [comment]
As pointed out this was a theano related issue. 
Re importing theano  raised an exception. 
I updated theano  and it's working fine now. 
Thanks for the pointer. 

Also having a way to force the fall-back on the non theano methods can still be usefull is some case but way less important than I thought. 

Anyhow problem solved, I close the issue.
Thanks again.
