### ISSUE TITLE
Lsi distributed fail

### ISSUE THREAD

**Issue by carlos386386** [RaRe-Technologies/gensim#807]
Hi, 
I've got a problem with the lsi distributed. When i executed the example:

https://radimrehurek.com/gensim/dist_lsi.html

First configure the server (enviroment variables), then i run  the server, worker and dispatcher.

And all without errros. But when i executed the code. I have this fail:
![image](https://cloud.githubusercontent.com/assets/10063469/17175207/799856c8-5406-11e6-8713-ca7ad342baf8.png)

Why does this happens? How can i solve?

Thank you in advance.

**Comment by piskvorky** [comment]
Hello @carlos386386 -- what version of pyro & gensim? (output of `pip freeze`)

See `https://github.com/RaRe-Technologies/gensim/blob/develop/CONTRIBUTING.md` for reporting issues.

**Comment by carlos386386** [comment]
Pyro4==4.46
gensim==0.12,1

**Comment by menshikh-iv** [comment]
I think adding `@exposure` decorator to methods that called remotely fix this problem

**Comment by carlos386386** [comment]
Where is the decorator @exposure?? How can import??

**Comment by menshikh-iv** [comment]
@carlos386386 Need to decorate methods that call remotely (some inner methods in lsi_worker) like [this](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/lda_worker.py#L42)

**Comment by carlos386386** [comment]
I have modify the file lsi_worker??

**Comment by menshikh-iv** [comment]
@carlos386386  yes

**Comment by piskvorky** [comment]
Must be some recent, breaking change in Pyro API.

Your Pyro version (4.46) doesn't indicate any major API change though. So not sure what's happened -- will need deeper investigation.

**Comment by tmylk** [comment]
@menshikh-iv Are you suggesting that we should add annotations to [lsi_worker](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/lsi_worker.py#L42) same way as [lda_worker](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/lda_worker.py#L42)? May I kindly ask for a PR for this?

**Comment by menshikh-iv** [comment]
@tmylk Yes, but a little later, right now I have no time :(

**Comment by markroxor** [comment]
@tmylk should this be closed?

**Comment by tmylk** [comment]
@markroxor the annotations are still missing in [`lsi_worker`](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/lsi_worker.py)
