### ISSUE TITLE
Topic Coherence for DTM (or any model)

### ISSUE THREAD

**Issue by bhargavvader** [RaRe-Technologies/gensim#808]
Wanted to know if there was any way to plug in the topics (topic-term distributions, doc-topic distributions, vocabulary counts, etc) to the coherence pipeline and get a measure.

Right now the [notebook ](http://nbviewer.jupyter.org/github/dsquareindia/gensim/blob/280375fe14adea67ce6384ba7eabf362b05e6029/docs/notebooks/topic_coherence_tutorial.ipynb) talks about using models (either the LdaModel or a wrapper), but if trained through an external source, I am unsure of how to do it.

pyLDAvis does this neatly in it's [prepare](http://pyldavis.readthedocs.io/en/latest/modules/API.html) method where it allows just matrices as inputs if you don't have a model object. 

This [post](http://rare-technologies.com/what-is-topic-coherence/) also mentions using individual pipeline modules for your own coherence measure - is there any documentation/tutorial on how to the same?

@dsquareindia , would love help regarding this.

**Comment by dsquareindia** [comment]
@bhargavvader thanks for raising the issue! I'll answer this in two parts.

__Plugging in another model__ :
Apart from accepting the different models and wrappers, the pipeline also takes as input a list of tokenized topics. Sorry for not putting this feature into the notebook yet. You can find a good example of how to do in the coherence pipeline tests ([this](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/test/test_coherencemodel.py#L50) line to be specific). You can simply plug in the tokenized topics into the pipeline like it has been done [here](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/test/test_coherencemodel.py#L70). So suppose I have a trained HDP model called `hm`, I can simply get the topic terms by:
```python
topics = []
for id, dist in hm.show_topics(formatted=False):
    topic = []
    for t, prob in dist:
        topic.append(t)
    topics.append(topic)
```
and then plug in the topics into the coherence model. Can this be done with the DTM wrapper? Sorry I don't have too much experience with it.

__Making your own coherence pipeline__:
You can make your own custom coherence measure by basically using the different pipeline stages as individual modules. To be more precise you can check the code [here](https://github.com/RaRe-Technologies/gensim/pull/793/files#diff-98ffbaea85e211a046e4de45c497aa3fR146). The `c_uci` measure was built simply by choosing the different functions from the different modules. However there are still some functions which have not been coded yet however it's pretty easy to code them.

I hope this clarifies your doubts a little.

**Comment by bhargavvader** [comment]
Ah yes, this certainly clears things up, thanks @dsquareindia . :)
Would be awesome if you could do a notebook with more examples of both, will be helpful for other users as well!

**Comment by dsquareindia** [comment]
Yeah I'll do that asap. Please keep this open so that I can reference this in my PR later.

**Comment by bhargavvader** [comment]
@dsquareindia any update on the tutorial notebook for this?

**Comment by dsquareindia** [comment]
Sorry for the delay @bhargavvader. I'll also write a blog post soon for this.

**Comment by dsquareindia** [comment]
Hey @bhargavvader I've also added a small gist [here](https://gist.github.com/dsquareindia/ac9d3bf57579d02302f9655db8dfdd55) where I have included a small snippet of how to make your own pipeline. Hope this helps too.

**Comment by bhargavvader** [comment]
This is great! You should add it to the notebook.

**Comment by bhargavvader** [comment]
Thanks for all the help. I'm closing the issue.
