### ISSUE TITLE
topic document mapping output

### ISSUE THREAD

**Issue by puneetjindal** [RaRe-Technologies/gensim#810]
@dsquareindia : I have run LdaMulticore on my text data which has id as 1 column and text in other column and built BOW data structure and built the model. I want the output as topic number and document id mapping with probability
For eg output by R code here
https://eight2late.wordpress.com/2015/09/29/a-gentle-introduction-to-topic-modeling-using-r/

**Comment by dsquareindia** [comment]
Hey @puneetjindal from what I understood, you can simply use the [] feature of your `LdaMulticore` instance to get the document id->topic distribution mapping. Eg.
```python
texts = [['human', 'interface', 'computer'],
         ['survey', 'user', 'computer', 'system', 'response', 'time'],
         ['eps', 'user', 'interface', 'system'],
         ['system', 'human', 'system', 'eps'],
         ['user', 'response', 'time'],
         ['trees'],
         ['graph', 'trees'],
         ['graph', 'minors', 'trees'],
         ['graph', 'minors', 'survey']]
dictionary = Dictionary(texts)
corpus = [dictionary.doc2bow(text) for text in texts]

# Suppose you train your LdaMulticore instance on the first 5 documents:
tm1 = LdaMulticore(corpus=corpus[:5], id2word=dictionary, num_topics=5)
# To get document topic assignment with probabilities for next 5 documents (say test set)
# you can simply do:
for n, doc in enumerate(corpus[5:]):
    print '{} ---> {}'.format(n, tm1[doc])
```
You will get an output such as
```
0 ---> [(0, 0.1005300848826758), (1, 0.10062912198785541), (2, 0.59023150118499101), (3, 0.10430185191018596), (4, 0.10430744003429186)]
1 ---> [(0, 0.066970801503935001), (1, 0.067027348017717578), (2, 0.069006804336045585), (3, 0.72790836812589454), (4, 0.069086678016407263)]
2 ---> [(0, 0.050216777226965235), (1, 0.050257024499947955), (2, 0.051727858445397117), (3, 0.79612676799791893), (4, 0.051671571829770641)]
3 ---> [(0, 0.050229893235541771), (1, 0.32583065173897491), (2, 0.051784168328799521), (3, 0.051771644963446418), (4, 0.52038364173323737)]
```
Did I understand your doubt correctly?

**Comment by tmylk** [comment]
@puneetjindal Glad you are using gensim.

Such open-ended questions are better suited for th mailing list: groups.google.com/forum/#!forum/gensim

If you could post some code that you tried there, it would make it possible for the community to help.

**Comment by dsquareindia** [comment]
We can close this since this isn't an issue
