### ISSUE TITLE
Doc2Vec Convergence

### ISSUE THREAD

**Issue by bkj** [RaRe-Technologies/gensim#820]
I'm trying to get intuition about how `Doc2Vec` works.  I started with a corpus of 10K sentences, and included every sentence twice, with a different tag:

```
docs = [
TaggedDocument('this is a test'.split(), tags=['a-0']),
TaggedDocument('this is a test'.split(), tags=['a-1']),
TaggedDocument('this is another test'.split(), tags=['b-0']),
TaggedDocument('this is another test'.split(), tags=['b-1']),
...
]
```

I assume that a trained and converged `Doc2Vec` model would map `*-0` and `*-1` to the same vectors, but that does not appear to be happening.  Is there an algorithmic explanation for why this wouldn't work, or is there maybe something wrong with my implementation?  Here's the code (cribbed from the `gensim` IMDB notebook):

```
model = Doc2Vec(dm=1, dm_concat=1, size=100, window=5, negative=5, hs=0, min_count=2, workers=cores)
model.build_vocab(documents)

alpha, min_alpha, passes = (0.025, 0.001, 20)
alpha_delta = (alpha - min_alpha) / passes
for epoch in range(passes):
    shuffle(documents)
    model.alpha, model.min_alpha = alpha, alpha
    _ = model.train(documents)    
    alpha -= alpha_delta
```

The cosine similarity between identical documents flattens at ~0.5 w/ those settings.  If I increase `model.iter` to `10`, it flattens at ~0.7.  

Is this just a matter of fiddling w/ `model.iter` and `model.alpha`? Or is there something fundamentally wrong with this test?  Are the differences perhaps a function of the different state of the model when it predicts the two different documents?  Or could I perhaps circumvent this by initializing all `docvecs` to `0`?

**Comment by bkj** [comment]
This behaves much closer to expected w/

```
model = Doc2Vec(dm=1, dm_concat=1, size=100, window=5, negative=0, hs=1, min_count=2, workers=cores)
```

**Comment by gojomo** [comment]
There's randomness in the Doc2Vec algorithm - both starting initialization of vectors, and in training (which involves random sampling and window-sizes). So the two tags for the same texts will start from different random points, and receive slightly different training updates. Still, they should wind up close to each other, and moreso with more training iterations. (If each example is especially small – just a few or few dozen words – then it is also the case that the doc-vectors will need more iterations to improve/settle.)

Some other notes on your setup:

* `dm_concat` is the least-well-tested and least-well-understood mode. The original PV paper speaks highly of this mode. But, that paper also has errors/omissions which have prevented external reproduction of their results (especially on the small SST dataset). `dm_concat` results in the largest & slowest-to-train models, and such models would require much more data or training cycles to converge. And, I haven't yet seen any dataset/task where it outperforms simpler modes. I would suggest sticking to simpler modes, especially the fast-and-often-best DBOW (`dm=0`, with or without `dbow_words=1`), until you're in an advanced/experimental/expert mood. 

* 10K sentences is a fairly small dataset; typical datasets for  interesting Doc2Vec results often have hundreds of thousands or millions of documents

* without specifying an `iter` argument, the default is 5; so each of your epoch loops is actually doing 5 training passes - and every pass is itself descending `alpha` from 0.025 to 0.001. If you're going to call `train()` multiple times yourself, set `iter` to 1. Or, just set `iter` to your desired number of epochs, and call `train()` once. (Current gensim versions should be showing warnings in the logs when you call `train()` repeatedly like you're doing.)

**Comment by tmylk** [comment]
@bkj Do you have more questions or can this be closed?
