### ISSUE TITLE
LdaMallet inference breaks when run in multiprocessing

### ISSUE THREAD

**Issue by davidjurgens** [RaRe-Technologies/gensim#822]
I trained an LdaMallet model and was successfully able to use it to infer the topic distribution for new documents but when I try to parallelize the inference, the code crashes. 

```python
# standard imports go here
from joblib import Parallel, delayed

def main():
     # [Code that loads the models is here...] 
    topic_assignments = Parallel(n_jobs=4)(delayed(infer)(doc, loaded_dict, loaded_lda) for doc in docs)

def infer(doc, loaded_dict, loaded_lda):
    vec = loaded_dict.doc2bow(doc)`
    topics = loaded_lda[vec]`
    return topics`
```

The code above works flawlessly if `n_jobs=1`, when it runs single process.  However, once `n_jobs` is set so the code runs in multiple processes, it crashes.  I've seen a few different errors; below are the final log messages for two different ones:

```
$HOME/.local/lib/python2.7/site-packages/gensim/models/wrappers/ldamallet.py in __getitem__(self=<gensim.models.wrappers.ldamallet.LdaMallet object>, bow=[[(9, 1), (16, 1), (33, 1), (34, 1), (35, 1), (36, 1), (37, 1)]], iterations=100)
    176         cmd = self.mallet_path + " infer-topics --input %s --inferencer %s --output-doc-topics %s --num-iterations %s --doc-topics-threshold %s"
    177         cmd = cmd % (self.fcorpusmallet() + '.infer', self.finferencer(), self.fdoctopics() + '.infer', iterations, self.topic_threshold)
    178         logger.info("inferring topics with MALLET LDA '%s'", cmd)
    179         check_output(cmd, shell=True)
    180         result = list(self.read_doctopics(self.fdoctopics() + '.infer'))
--> 181         return result if is_corpus else result[0]
        result = []
        is_corpus = False
    182 
    183     def load_word_topics(self):
    184         logger.info("loading assigned topics from %s", self.fstate())
    185         wordtopics = numpy.zeros((self.num_topics, self.num_terms), dtype=numpy.float32)

IndexError: list index out of range
```

```
$HOME/.local/lib/python2.7/site-packages/gensim/utils.py in check_output(*popenargs=('mallet.infer --use-pipe-from /tmp/b40f33_corpus.mallet',), **kwargs={'shell': True})
   1157             cmd = kwargs.get("args")
   1158             if cmd is None:
   1159                 cmd = popenargs[0]
   1160             error = subprocess.CalledProcessError(retcode, cmd)
   1161             error.output = output
-> 1162             raise error
        error = CalledProcessError()
   1163         return output
   1164     except KeyboardInterrupt:
   1165         process.terminate()
   1166         raise

CalledProcessError: Command 'bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex '\S+' --input /tmp/b40f33_corpus.txt --output /tmp/b40f33_corpus.mallet.infer --use-pipe-from /tmp/b40f33_corpus.mallet' returned non-zero exit status 1
```

For the second error, if I actually run the command itself `bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex '\S+' --input /tmp/b40f33_corpus.txt --output /tmp/b40f33_corpus.mallet.infer --use-pipe-from /tmp/b40f33_corpus.mallet`  the command exits normally with exit code 0, which leads me to believe it has something to do with how the subprocess call is waited for.  

I'm not sure how to track down the issue but I've attached two files that can be used to reproduce the error.  

[lda_debug_infer_parallel.py.txt](https://github.com/RaRe-Technologies/gensim/files/412556/lda_debug_infer_parallel.py.txt)
[lda_debug_train.py.txt](https://github.com/RaRe-Technologies/gensim/files/412557/lda_debug_train.py.txt)

**Comment by tmylk** [comment]
@davidjurgens Thanks for reporting it.
What happens when you run several instances of this shell command in parallel? It will show the mallet error.
`bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex '\S+' --input /tmp/b40f33_corpus.txt --output /tmp/b40f33_corpus.mallet.infer --use-pipe-from /tmp/b40f33_corpus.mallet`

**Comment by tmylk** [comment]
Closing as abandoned
