### ISSUE TITLE
Different vectors for duplicate paragraphs

### ISSUE THREAD

**Issue by franciscovargas** [RaRe-Technologies/gensim#827]
I have the following text file (play4):

```
hello its me
hello its me
hello its me
````

And its been read in and trained like this:

```python
doc = TaggedLineDocument("play4")
model = Doc2Vec(size=20, window=8, min_count=2, workers=1, alpha=0.025, min_alpha=0.025, batch_words=1)
model.build_vocab(doc)
for epoch in range(1000):
    model.train(doc)
np.array(model.docvecs)
```

The three resulting vectors are rather different. Reading the paper behind it there is not enough specifics on how matrix D which equates to np.array(model.docvecs).T is initialised and updated.
The assumption ive made is that they are all initialised randomly ?

**Comment by gojomo** [comment]
Yes, each doc-vector starts with random initialization, as in word2vec. And the process typically (in larger examples) includes other randomness, with each vector's updates during training cycles depending on the incrementally-different current state of the model at each example. Same texts should trend toward similar vectors over time. 

But also, toy-sized tests often don't create typical or usefully illustrative results. With 20 dimensions and only 3 examples and 3 words, and no contrast between different documents, the internal neural network can improve on its prediction-goals (perhaps becoming perfect at them) without ever forcing any continuous structure on the trained doc-vector values. They really only obtain meaning in a tug-of-war contrast/competition with other potential values, with varied training data. 

That said, questions are best handled on the project discussion-list, https://groups.google.com/forum/#!forum/gensim – reserving github issues for bugs, feature-requests, or specific change discussions.
