### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'int' objects

### ISSUE THREAD

**Issue by loretoparisi** [RaRe-Technologies/gensim#846]
```python
Traceback (most recent call last):
  File "imdb_embedding_w2v.py", line 160, in <module>
    model.build_vocab(combined)
  File "/Library/Python/2.7/site-packages/gensim/models/word2vec.py", line 510, in build_vocab
    self.finalize_vocab()  # build tables & arrays
  File "/Library/Python/2.7/site-packages/gensim/models/word2vec.py", line 640, in finalize_vocab
    self.reset_weights()
  File "/Library/Python/2.7/site-packages/gensim/models/word2vec.py", line 986, in reset_weights
    self.syn0[i] = self.seeded_vector(self.index2word[i] + self.seed)
TypeError: cannot concatenate 'str' and 'int' objects
```

Current version
```shell
$ pip list | grep gensim
gensim (0.12.4)
```
This error does not happen for `gensim==0.10.2`

**Comment by piskvorky** [comment]
Looks like old version of gensim (0.12.4) had some bug.

@tmylk is this covered by tests now? CC @gojomo

**Comment by piskvorky** [comment]
Actually, looking at the code of 0.12.4, it says

```python
    self.syn0[i] = self.seeded_vector(self.index2word[i] + str(self.seed))
```

which doesn't match your traceback.

So I don't understand this report -- @tmylk @gojomo ideas?

**Comment by appierys** [comment]
Here is a test case that would trigger an error:

```python
    from gensim.models import Word2Vec

    walks = [
        [1, 2, 2, 2, 1, 3],
        [1, 2, 2, 2, 1, 3],
        [1, 2, 2, 2, 1, 3],
        [1, 2, 2, 2, 1, 3],
        [1, 2, 2, 2, 1, 3],
        [1, 2, 2, 2, 1, 3],
        [1, 2, 2, 2, 1, 3],
    ]

    model = Word2Vec(walks, size=4, window=3, min_count=0)
```

```
    Traceback (most recent call last):
      File "w2v.py", line 13, in <module>
        model = Word2Vec(walks, size=4, window=3, min_count=0)
      File "/env/lib/python3.4/site-packages/gensim/models/word2vec.py", line 459, in __init__
        self.build_vocab(sentences, trim_rule=trim_rule)
      File "/env/lib/python3.4/site-packages/gensim/models/word2vec.py", line 525, in build_vocab
        self.finalize_vocab()  # build tables & arrays
      File "/env/lib/python3.4/site-packages/gensim/models/word2vec.py", line 661, in finalize_vocab
        self.reset_weights()
      File "/env/lib/python3.4/site-packages/gensim/models/word2vec.py", line 1013, in reset_weights
        self.syn0[i] = self.seeded_vector(self.index2word[i] + str(self.seed))
    TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

Apparently, to avoid this error @loretoparisi has modified the code and removed `str`. However, this would cause the reversed error `TypeError: cannot concatenate 'str' and 'int' objects` when input is strings.

For more information, see https://github.com/phanein/deepwalk/issues/3.

**Comment by loretoparisi** [comment]
@appierys Hi, so what I did was changing
```
self.syn0[i] = self.seeded_vector(self.index2word[i] + self.seed)
```

to 
```
self.syn0[i] = self.seeded_vector(self.index2word[i] + str(self.seed) )
```

to fix it. Without the `str` I get the error.

**Comment by appierys** [comment]
@loretoparisi 
Deepwalk would fail if we have
```python
self.syn0[i] = self.seeded_vector(self.index2word[i] + str(self.seed) )
```

Normal text-based word2vec would fail if we have
```python
self.syn0[i] = self.seeded_vector(self.index2word[i] + self.seed)
```

So the best solution should be what @tigerneil proposed:
```python
self.syn0[i] = self.seeded_vector(str(self.index2word[i]) + str(self.seed) )
```

**Comment by loretoparisi** [comment]
weird! Ok I will change in that way, regarding gensym version it still need an update to have bot the `str` right?

**Comment by piskvorky** [comment]
Word2Vec expects a sentence to be "list of strings", not "list of ints". I suspect you'll have other issues too, if you break that contract.

Can't you just make strings out of your ints (`'1'` instead of `1`)?

**Comment by tmylk** [comment]
@loretoparisi Did this issue disappear after converting input `int`s to `str`s?

**Comment by tmylk** [comment]
Closing as abandone.

**Comment by markroxor** [comment]
@tmylk I simulated the error and indeed "Word2Vec expects a sentence to be "list of strings", not "list of ints"."

**Comment by tmylk** [comment]
Once ints are converted to strings, is there still an error?

**Comment by loretoparisi** [comment]
@tmylk I did not converted the input actually, by the way it happens as @markroxor explains.

**Comment by markroxor** [comment]
@tmylk I converted it to string and it works fine.

**Comment by loretoparisi** [comment]
@markroxor so the solution will to convert to string the input? What about precision i.e. how did you convert to string?

**Comment by markroxor** [comment]
For the sake of testing I manually converted each of the int to str. One should be careful while inputting "sentence" parameter to "Word2Vec" function.

**Comment by shivam13juna** [comment]
I confirm, converting int to str worked perfectly. like I converted word_to_int[i] to str(word_to_int[i])
