### ISSUE TITLE
'iter' parameter is not passed on to word2vec

### ISSUE THREAD

**Issue by usmanshahid** [RaRe-Technologies/gensim#850]
Hi, I was just looking at the code of Doc2Vec class, it seems like it takes a parameter iter which is the number of iteration which should be used in the initialization of Word2Vec object but it is not passed on? Is this a bug in the code or something is wrong with documentation?

**Comment by piskvorky** [comment]
@gojomo is this the case?

**Comment by gojomo** [comment]
No. It's taken by `Doc2Vec.__init__()` in  `**kwargs`, and passed to `Word2Vec.__init__()` the same way.
