### ISSUE TITLE
ZeroDivisionError: float division by zero in pagerank_weighted.py

### ISSUE THREAD

**Issue by bofinbabu** [RaRe-Technologies/gensim#851]
Got ZeroDivisionError: float division by zero in **pagerank_weighted.py**

Input Text: BYAnonymousArabe

Error thrown at:  `summarize(text_to_sum, word_count=50)`

![gensim error](https://cloud.githubusercontent.com/assets/5749350/18311490/44da660a-7522-11e6-8812-7390ebca8ef6.png)

I know word_count is 50 and I'm just giving a word. But ideally it should output that single word instead of throwing an error isn't it?

Please throw some light

**Comment by pranay360** [comment]
@tmylk for changes to be made what should be the expected output should it raise an error saying "not enough text to summarize", or just output the single word as it is(if its length is > 10 i.e. INPUT_MIN_LENGTH)?

**Comment by metalaman** [comment]
For Input Text : "Ab", build_probability_matrix method doesn't give any error, only keywords method is giving ZeroDivisionError.

**Comment by tmylk** [comment]
Output less than word_count should be allowed

**Comment by bofinbabu** [comment]
@tmylk Yes. I agree with you

**Comment by tmylk** [comment]
Fixed in #887
