### ISSUE TITLE
add wordspace model?

### ISSUE THREAD

**Issue by Ronggui** [RaRe-Technologies/gensim#855]
Hi, it seems that wordspace model is very useful (http://infomap-nlp.sourceforge.net/doc/algorithm.html and https://cran.r-project.org/web/packages/wordspace/index.html). It is  similar to the lsa model except that wordspace decomposes a co-occurrence matrix instead of term-document matrix.

**Comment by tmylk** [comment]
Thanks. Looks interesting! Added to student projects https://github.com/RaRe-Technologies/gensim/wiki/Student-Projects#implement-wordspace-in-python
