### ISSUE TITLE
DTM ldaseqmodel tutorial notebook - Corpus and cleaning instructions

### ISSUE THREAD

**Issue by einon** [RaRe-Technologies/gensim#857]
In code cell 2, neither of these files are available, with no instructions on how to obtain them:
# loading our corpus and dictionary

dictionary = Dictionary.load('Corpus/news_dictionary')
corpus = bleicorpus.BleiCorpus('Corpus/news_corpus')

**Comment by bhargavvader** [comment]
Hello @einon , I didn't include these test files and they were just an example. You can find the data set here: [link](https://github.com/derekgreene/dynamic-nmf/tree/master/data).

Thanks for pointing this out, I'll add this information to the notebook as well.

**Comment by tmylk** [comment]
Do you have the pre-processing code somewhere? It would be great to add it to the tutorial.

**Comment by tmylk** [comment]
Ping @bhargavvader

**Comment by bhargavvader** [comment]
@tmylk I was wondering if I should just upload the corpus and dictionary to load - it's easier, because my cleaning and pre-processing wasn't very pretty.

**Comment by tmylk** [comment]
Sounds good if it's not too big

**Comment by piskvorky** [comment]
@bhargavvader @tmylk status here? I see some data files have been merged, but have the notebook instructions been updated?

**Comment by bhargavvader** [comment]
I've included the necessary data files and mentioned it requires basic pre-processing, and linked to basic [gensim pre-processing](https://radimrehurek.com/gensim/tut1.html#from-strings-to-vectors). I haven't included detailed instructions on the pre-processing.

**Comment by einon** [comment]
This fixes the original issue, so happy to close. Thanks!

**Comment by bhargavvader** [comment]
:)
