### ISSUE TITLE
Adding Word Prediction

### ISSUE THREAD

**Issue by cdzech** [RaRe-Technologies/gensim#863]
Hi,

I have noticed that, at least for my use case, a crucial feature is missing in the Word2Vec module: Word prediction. There is no function that takes a context as an input and outputs the probability distribution for the center word (in CBOW).

For my project, I implemented such a function. Is there any interest of the community to provide such a method for the users? If so, I would look into porting it.

Best,
Chris

**Comment by gojomo** [comment]
Yes! That capability has occasionally been requested, or been relevant to experiments people want to do, so a PR would be welcome.

**Comment by cdzech** [comment]
Sounds good. I'll need some time, though. I'll get back when I'm ready.

**Comment by metalaman** [comment]
Are we looking at a language model implementation for this feature?

**Comment by gojomo** [comment]
The Word2Vec model already is trained via implicit word-predictions, so no extra model implementation should be necessary – just providing another way to run the trained model and report the results (across all possible word-predictions).

**Comment by chinmayapancholi13** [comment]
Hey @gojomo I would like to work on this issue. If I understood it correctly, once the model has been learned and we are given a set of context words, we need to predict the most probable center word. To do this, we could create a function as follows : 

```python

def predict_word_from_context(model, context_words_list):

    word_vocabs = [model.wv.vocab[w] for w in context_words_list if w in model.wv.vocab]

    word2_indices = []
    for pos, word in enumerate(word_vocabs):
        word2_indices.append(word.index)

    l1 = np_sum(model.wv.syn0[word2_indices], axis=0) 
    if word2_indices and model.cbow_mean:
        l1 /= len(word2_indices)

    l2a = model.syn1  # 2d matrix, vocab_size x layer1_size
    fa = expit(dot(l1, l2a.T))  # propagate hidden -> output

    return model.wv.index2word[numpy.argmax(fa)]

``` 
Here, `context_words_list` is a list containing unicode encoded context words.

Could you please guide me regarding the approach that I am following above and tell me if I am on the right track?
