### ISSUE TITLE
Add MemoryMapping example to Annoy tutorial

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#891]
Add example to AnnoyTutorial where 2 parallel processes load the same model from disk and mmap the same index file.

**Comment by harshul1610** [comment]
How can I save model to disk?

**Comment by harshul1610** [comment]
I did prepared the code to save and fetch the model from disk by 2 parallel processes. What do we mean by mmap the same index file? What is the use case for this scenario? I will add description too.

**Comment by tmylk** [comment]
@harshul1610 Thanks for taking this up. Could you please move `annoy_index.load('index')` into the thread and also output memory used? Memory should not increase much as the index stays on disk. 

Also, it would be more professional to choose a less controversial word example instead of 'army'.

**Comment by harshul1610** [comment]
sure

**Comment by harshul1610** [comment]
Is it good?

**Comment by tmylk** [comment]
To be more explicit Each process should have its own indexer

**Comment by harshul1610** [comment]
Done

**Comment by harshul1610** [comment]
Is it good?

**Comment by tmylk** [comment]
Hi @harshul1610 The code looks good.
Could you please add some text above cell 10 to provide motivation for the code?
Best would be add a new cell where 2 separate indices are created and used without saving/loading. It should use much more memory than cell 10.
Your text will explain that memory mapping saves RAM.

**Comment by tmylk** [comment]
Also, no need to create new pr to update code. you can just keep pushing to existing branch

**Comment by harshul1610** [comment]
@tmylk It is the time that surely increases when we don't use memory mapped index. But, memory space used by processes is approximately the same.

when Index file not memory mapped
```
%%time
from gensim import models
from gensim.similarities.index import AnnoyIndexer
from multiprocessing import Process
import os
import psutil

model.save('/tmp/mymodel')

def f(process_id):
    print 'Process Id: ', os.getpid()
    process = psutil.Process(os.getpid())
    new_model = models.Word2Vec.load('/tmp/mymodel')
    vector = new_model["science"]
    annoy_index = AnnoyIndexer(new_model,100)
    approximate_neighbors = new_model.most_similar([vector], topn=5, indexer=annoy_index)
    for neighbor in approximate_neighbors:
        print neighbor
    print 'Memory used by process : ', process.memory_percent(), '%'

p1 = Process(target=f, args=('1',))
p1.start()
p1.join()
p2 = Process(target=f, args=('2',))
p2.start()
p2.join()
```
Results are:
Process Id:  8348
('organisations.', 0.6213910579681396)
('klusener', 0.6172938048839569)
('version', 0.6145751178264618)
('beveridge,', 0.6114714741706848)
('silence', 0.6113320291042328)
Memory used by process :  2.72561627241 %
Process Id:  8363
('organisations.', 0.6213910579681396)
('klusener', 0.6172938048839569)
('version', 0.6145751178264618)
('beveridge,', 0.6114714741706848)
('silence', 0.6113320291042328)
Memory used by process :  2.72561627241 %
CPU times: user 180 ms, sys: 20 ms, total: 200 ms
Wall time: 6.95 s

Index file memory mapped:
```
%%time
from gensim import models
from gensim.similarities.index import AnnoyIndexer
from multiprocessing import Process
import os
import psutil

model.save('/tmp/mymodel')

def f(process_id):
    print 'Process Id: ', os.getpid()
    process = psutil.Process(os.getpid())
    new_model = models.Word2Vec.load('/tmp/mymodel')
    vector = new_model["science"]
    annoy_index = AnnoyIndexer()
    annoy_index.load('index')
    annoy_index.model = new_model
    approximate_neighbors = new_model.most_similar([vector], topn=5, indexer=annoy_index)
    for neighbor in approximate_neighbors:
        print neighbor
    print 'Memory used by process : ', process.memory_percent(), '%'

p1 = Process(target=f, args=('1',))
p1.start()
p1.join()
p2 = Process(target=f, args=('2',))
p2.start()
p2.join()
```

Results are as follows: 
Process Id:  8314
('organisations.', 0.6213910579681396)
('klusener', 0.6172938048839569)
('version', 0.6145751178264618)
('beveridge,', 0.6114714741706848)
('silence', 0.6113320291042328)
Memory used by process :  2.93171783021 %
Process Id:  8329
('organisations.', 0.6213910579681396)
('klusener', 0.6172938048839569)
('version', 0.6145751178264618)
('beveridge,', 0.6114714741706848)
('silence', 0.6113320291042328)
Memory used by process :  2.93171783021 %
CPU times: user 112 ms, sys: 24 ms, total: 136 ms
Wall time: 353 ms

Is there something I am missing?

**Comment by tmylk** [comment]
Let me understand correctly what you are saying:
"RAM used by 2 processes with memory mapping from disk" = "RAM used by 2 processes, each created its own index"
That means mmaping claim by Annoy is not true: ["It also creates large read-only file-based data structures that are mmapped into memory so that many processes may share the same data."](https://github.com/spotify/annoy)

**Comment by harshul1610** [comment]
@tmylk  updated the statistics

**Comment by tmylk** [comment]
Thanks, that is more clear now. So it is using less memory in total, as it is shared. Shared memory is included in RSS so it was confusing before.

Please add some text and this output to the notebook.

**Comment by tmylk** [comment]
Thanks for the pr!
