### ISSUE TITLE
Adding a conda-forge recipe for Gensim

### ISSUE THREAD

**Issue by souravsingh** [RaRe-Technologies/gensim#892]
Adding a conda-forge recipe would help with installation of gensim across multiple platforms.

https://conda-forge.github.io/

**Comment by tmylk** [comment]
BTW There is an Anaconda recipe by @ljstokes from #526 at  https://anaconda.org/ijstokes/gensim

**Comment by souravsingh** [comment]
@tmylk The Pull request for the conda-forge recipe has been sent here-https://github.com/conda-forge/staged-recipes/pull/1689

**Comment by tmylk** [comment]
Thanks for taking it up @souravsingh . Please have a look at `install_requres` and `test_requires` in [setup.py](https://github.com/RaRe-Technologies/gensim/blob/develop/setup.py#L176) Some of them needed to be aded to the recipe.

**Comment by tmylk** [comment]
@menshkih-iv let's rebuild conda forge recipe with the recent changes to the test_requires

**Comment by souravsingh** [comment]
The PR for Conda-forge recipe is here- https://github.com/conda-forge/staged-recipes/pull/1689.
 
It is currently facing problems with running ``unittest`` tests, otherwise rest looks good.

If we skip the test in the ``test`` section, we can get the recipe to pass all the tests.

**Comment by tmylk** [comment]
The tests absolutely must pass in conda.

**Comment by souravsingh** [comment]
@tmylk I have updated the recipe to reflect the new version of Gensim here- https://github.com/conda-forge/staged-recipes/pull/1689

**Comment by souravsingh** [comment]
@menshikh-iv I have made a PR for the conda-forge recipe here- https://github.com/conda-forge/staged-recipes/pull/3225

**Comment by souravsingh** [comment]
The recipe is now available here- https://github.com/conda-forge/gensim-feedstock
The recipe works for Linux and Windows 64-bit, while the recipe has problem running tests for OSX, which needs investigating.

The issue can now be closed.

**Comment by menshikh-iv** [comment]
Thank you @souravsingh, good work:+1:
