### ISSUE TITLE
Use efficient normalization in LDA

### ISSUE THREAD

**Issue by olavurmortensen** [RaRe-Technologies/gensim#894]
The Hierarchical Dirichlet Process model in Gensim uses a clever trick to efficiently normalize some variational parameters. It does this using a function called `log_normalize`, see [line 49](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/hdpmodel.py#L49) and [line 342](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/hdpmodel.py#L342) in the HDP code.

This could also be used in `ldamodel.py`, to make the normaization faster.

**Comment by ArifAhmed1995** [comment]
I am working on this.

**Comment by olavurmortensen** [comment]
On a related note, it would be nice if the `log_normalize` function was able to take a 2D array, and normalize along a *single axis*. At the moment it does support normalizing along both axes in a 2D array.

**Comment by olavurmortensen** [comment]
I just discovered something you might find useful. From the usage of `log_normalize` in the HDP code, it seemed to me that if you want to normalize a vector `v`, you pass it to the function and obtain a normalized `log v` in return. That is *not* the case, you need to pass `log v` to the function, and then return a normalized `log v`.

This has caused me a lot of pain and confusion lately, so I though I'd warn you :)

**Comment by ArifAhmed1995** [comment]
The time taken for the `ldamodel` tests to run worsens for the small file `testcorpus.mm`.Maybe log normalization will perform better for a larger corpus.I will test it out and post results soon.
