### ISSUE TITLE
Documentation overhaul

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#907]
We need a new website hosted on github, for example on [github-pages](https://pages.github.com/).

Docs should be part of continuous integration, for example using [travis-sphinx](https://github.com/Syntaf/travis-sphinx). If a new python file is missing from API reference that it should be clearly seen. Probably Coala/gitmate can do that.

The actual tools are open to discussion. We don't have to keep using Sphinx and rst, and it doesn't have to be github-pages.

**Comment by tmylk** [comment]
@dsquareindia has expressed interest in this task

**Comment by dsquareindia** [comment]
Yep I'll get to it in some time!

**Comment by souravsingh** [comment]
@tmylk We can make use of doctr to push docs to Github pages.Sympy makes use of it

**Comment by tmylk** [comment]
Sounds great! Can you implement it?

**Comment by souravsingh** [comment]
I should be able to do it. I would only need some time to do it.

**Comment by markroxor** [comment]
@souravsingh can I lend a hand somehow?

**Comment by tmylk** [comment]
@markroxor this project is the inspiration http://xarray.pydata.org/en/stable/
You can start by adding the [`readthedocs.yml`](https://github.com/pydata/xarray/blob/stable/readthedocs.yml)

**Comment by souravsingh** [comment]
@tmylk I made a WIP PR for making use of doctr for deployment of docs to Github Pages here- https://github.com/RaRe-Technologies/gensim/pull/939.

You can check doctr here- https://github.com/drdoctr/doctr

I am against using Read the Docs since we are somewhat limited in terms of what we can show as docs( like showing executable IPython

**Comment by markroxor** [comment]
@tmylk I was about to send a PR for `readthedocs`. What to do?

**Comment by tmylk** [comment]
@souravsingh Thanks. How do you suggest we link to the ipynb tutorials instead of RST?
Our doc web-site looks very 90s compared to readthedocs and it doesn't have a side-bar.

**Comment by souravsingh** [comment]
@tmylk Can we utilize the ipynb tutorials to create a cookbook?

**Comment by tmylk** [comment]
@souravsingh Cookbook would be good. Did you have some specific format in mind? Can you elaborate more?

**Comment by tmylk** [comment]
Another good documentation example: [Spacy docs](https://github.com/explosion/spaCy/tree/master/website) using jade templates.

**Comment by souravsingh** [comment]
Something like what is done by Shogun Machine Learning- http://www.shogun-toolbox.org/showroom

**Comment by tmylk** [comment]
@souravsingh That looks great way to deal with ipynb. how is it done?

**Comment by piskvorky** [comment]
Yeah, looks cool. Any progress on this @tmylk @souravsingh ?

The current situation with web vs notebooks is confusing (and extra work for maintenance).

**Comment by souravsingh** [comment]
@markroxor wants to work on the documentation website.

**Comment by markroxor** [comment]
Also continued in #1091 but instead using sphinx templates.

**Comment by mpenkov** [comment]
@piskvorky Closing in favor of the ongoing numfocus work
