### ISSUE TITLE
per_word_topics for a corpus

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#908]
As reported on the [mailing list](https://groups.google.com/d/msg/gensim/RgiN22vtPKU/3K3TpxjKBgAJ) 
`lda.get_document_topics(clipped_corpus, per_word_topics=True)` doesn't return per_word_topics.

This [line](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/ldamodel.py#L924) should be changed to pass all the params including `per_word_topics` through the `apply` call.

**Comment by saksham15082** [comment]
@tmylk is this issue still open.

**Comment by tmylk** [comment]
@saksham15082 It is still open and a fix would be appreciated.  We need to pass *all* the params including per_word_topics through the apply call.

**Comment by saksham15082** [comment]
@tmylk i am new to open source and often find it difficult to locate the file in which the changes are required.Any suggestions?

**Comment by markroxor** [comment]
@tmylk The link to "mailing list" redirects elsewhere for a better understanding of this issue. Please fix. thanks.

**Comment by tmylk** [comment]
@markroxor Thanks for pointing it out. Link updated to https://groups.google.com/d/msg/gensim/RgiN22vtPKU/3K3TpxjKBgAJ

**Comment by saksham15082** [comment]
@markroxor  please go ahead with this issue.

**Comment by tmylk** [comment]
Fixed in https://github.com/RaRe-Technologies/gensim/pull/978/ Just needs better tests
