### ISSUE TITLE
Remove "No handlers could be found for logger "gensim.models.word2vec" message during import

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#910]
Instead print the actual message that word2vec is trying to print

**Comment by souravsingh** [comment]
@tmylk I would like to work on the issue.How do I start?

**Comment by markroxor** [comment]
@tmylk Check [logging.basicConfig](https://docs.python.org/2/library/logging.html#logging.basicConfig). 

> Does basic configuration for the logging system by creating a StreamHandler with a default Formatter and adding it to the root logger. The functions debug(), info(), warning(), error() and critical() will call basicConfig() automatically __if no handlers are defined for the root logger.__

I believe adding logging.basicConfig() to *gensim.models.word2vec* should do the trick.

Implementing this on my system pops the following WARNING in compliance with the logger warning [here](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/word2vec.py#L107)
![image](https://cloud.githubusercontent.com/assets/11366315/19198816/9b9bb9f2-8cde-11e6-836c-c19338e69644.png)

Do want to print this message?

**Comment by tmylk** [comment]
Yes, that text is very important. Let's print it

**Comment by SebastinSanty** [comment]
On OSX, the following message, is printed 
```
Slow version of gensim.models.word2vec is being used
Slow version of gensim.models.doc2vec is being used
```
So, I guess, it works correctly on OSX.

**Comment by shrutiag95** [comment]
i got Slow version of gensim.models.doc2vec is being used error....pls help

**Comment by markroxor** [comment]
@shrutiag95 have you tried installing cython and then
`python setup.py build_ext --inplace`
