### ISSUE TITLE
input and  output matrix

### ISSUE THREAD

**Issue by anish9208** [RaRe-Technologies/gensim#917]
hi ,
I am  new  to gensim  and working with word2vec recently. Can anyone  tell  me  how  to get input  matrix and  output  matrix  for skipgram and  CBOW models (or  how  to  get  weights  of model )

(for example  in  cbow model input  matrix  is  of  size ( V x N)   N= size of hidden layer  , V = size  of Vocab  and  output matrix  would be NxV )

**Comment by tmylk** [comment]
Hi, @anish9208 
Such open ended questions are better for our mailing list https://groups.google.com/forum/#!forum/gensim

The matrices in question are  syn0 and syn1 attributes of the model.
