### ISSUE TITLE
Add tests for #837

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/gensim#918]
This PR is almost done, just needs tests https://github.com/RaRe-Technologies/gensim/pull/837

Great issue to fix while getting familiar with Gensim

**Comment by souravsingh** [comment]
@tmylk I am willing to take this.How do I proceed?

**Comment by tmylk** [comment]
Do you have ideas on how to test this? Let's write them here to discuss.

**Comment by tmylk** [comment]
Also let's talk in https://gitter.im/RaRe-Technologies/gensim
