### ISSUE TITLE
how to change the min_count when update the word2vec model

### ISSUE THREAD

**Issue by v-chuqin** [RaRe-Technologies/gensim#935]
Hi guys,
I have a pr-trained word2vec model and set min_count = 5, now I want to update this model using the **online word2vec** with the following code:

```
sentences = LineSentence('newCorpus')
model = Word2Vec.load('pretrainModel') # I have set min_count = 5
model.build_vocab(sentences , update=True)
model.train(testsentences)
```

 I hope to change the min_count, because the new dataset relatively small, if don't change the min_count, many new words won't be embedded. 

Thanks.

**Comment by isohyt** [comment]
Hi, @v-chuqin . I'm online word2vec developer.

In your use case, your should set min_count  before build_vocab using new corpus as follows:
`
sentences = LineSentence('newCorpus')
model = Word2Vec.load('pretrainModel') # I have set min_count = 5
model.min_count = 0 # any number you want
model.build_vocab(sentences , update=True)
model.train(testsentences)
`

Thanks :)

**Comment by v-chuqin** [comment]
It works, @isohyt thanks for your help.
