### ISSUE TITLE
The automated tests for notebooks from #874 do not run during CI 

### ISSUE THREAD

**Issue by mon95** [RaRe-Technologies/gensim#936]
I'm working on the same.

**Comment by bhargavvader** [comment]
Awesome, we certainly need this done.

**Comment by dsquareindia** [comment]
However they should all run on "pseudo toy-datasets" just to ensure that the notebooks execute from start to finish. We don't want `wgets` inside the notebooks as some might take a long long time to execute on the actual datasets! `sklearn` does that pretty well and we can look into their tests.

**Comment by bhargavvader** [comment]
+1 to what Devashish said. @mon95 , for the notebooks which fail, could you notify on this issue? We could accordingly modify the notebooks to accommodate this.

**Comment by mon95** [comment]
@dsquareindia The prescribed method of testing ipython notebooks is to execute cell by cell and check for errors in the output. So, in order to use 'toy datasets', my guess is that we'll need to modify the tutorials. 

@bhargavvader I just ran into this: 

`Testing ./docs/notebooks/Similarity_Queries.ipynb
ERROR

======================================================================
ERROR: test_notebooks (gensim.test.test_notebooks.TestNotebooks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/ssreehari10/gdrive/gensim/gensim/test/test_notebooks.py", line 66, in test_notebooks
    nb, errors = _notebook_run(notebook)
  File "/media/ssreehari10/gdrive/gensim/gensim/test/test_notebooks.py", line 43, in _notebook_run
    raise e
CellExecutionError: An error occurred while executing the following cell:
------------------
from gensim import corpora, models, similarities

dictionary = corpora.Dictionary.load('/tmp/deerwester.dict')
corpus = corpora.MmCorpus('/tmp/deerwester.mm') # comes from the first tutorial, "From strings to vectors"
print(corpus)
------------------

IOError: [Errno 2] No such file or directory: '/tmp/deerwester.dict'
`
This is because the line throwing the error depends on cell number 5 here https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/Corpora_and_Vector_Spaces.ipynb 

This needs to be changed

**Comment by tmylk** [comment]
Let's unite them into one ipynb then as there is a dependency.

**Comment by tmylk** [comment]
If the dataset is not available then the ipynb is skipped. See #874 for 
`raise ValueError(\"SKIP: Please download the Corpus/news_dictionary dataset.\")`

**Comment by mon95** [comment]
Encountered a couple of other errors while testing

Testing gensim_news_classification.ipynb:
```
import pyLDAvis.gensim
pyLDAvis.enable_notebook()
pyLDAvis.gensim.prepare(ldamodel, corpus, dictionary)

Traceback (most recent call last):
  File "test_notebooks.py", line 66, in test_notebooks
    nb, errors = _notebook_run(notebook)
  File "test_notebooks.py", line 43, in _notebook_run
    raise e
CellExecutionError: An error occurred while executing the following cell:

pyLDAvis.gensim.prepare(ldamodel, corpus, dictionary)

TypeError: cannot sort an Index object in-place, use sort_values instead
```

Testing topic_coherence_tutorial.ipynb:

```
pyLDAvis.enable_notebook()
pyLDAvis.gensim.prepare(goodLdaModel, corpus, dictionary)

Traceback (most recent call last):
  File "test_notebooks.py", line 66, in test_notebooks
    nb, errors = _notebook_run(notebook)
  File "test_notebooks.py", line 43, in _notebook_run
    raise e
CellExecutionError: An error occurred while executing the following cell:

pyLDAvis.gensim.prepare(goodLdaModel, corpus, dictionary)

TypeError: cannot sort an Index object in-place, use sort_values instead
```

**Comment by parthoiiitm** [comment]
Hi, the problem you are facing is due to pyLDAvis bug. I upgraded to pandas 0.19 and changed this line : https://github.com/bmabey/pyLDAvis/blob/master/pyLDAvis/_prepare.py#L267

to  ```term_ix.sort_values()```. Then I compiled pyLDAvis on my system.  Hope this will help you to some extent.

**Comment by menshikh-iv** [comment]
Unrelevant for now.
