### ISSUE TITLE
HdpModel does not document inference using []

### ISSUE THREAD

**Issue by dsquareindia** [RaRe-Technologies/gensim#937]
`HdpModel` does not document inference using `[]` operator as in LDA. Documentation should be added along with small code snippet.

**Comment by bhargavvader** [comment]
@dsquareindia could you elaborate on this a bit? What would a fix be?

**Comment by dsquareindia** [comment]
@bhargavvader a fix would be adding something like [this](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/ldamodel.py#L205) to the `HdpModel` documentation.

**Comment by dsquareindia** [comment]
Sorry @bhargavvader I addressed this issue in #1029. Needed a green square too :stuck_out_tongue:

**Comment by bhargavvader** [comment]
No problem!
