### ISSUE TITLE
Create single API/base class for all topic models

### ISSUE THREAD

**Issue by dsquareindia** [RaRe-Technologies/gensim#938]
As discussed on gitter, it would be nice to have a single API/base class which can be extended by all topic models. This will include common functions such as `print_topic()` which are needed by all models. eg. `show_topic()` is not present in `HdpModel` currently and adding this function would incur code duplication.

**Comment by bhargavvader** [comment]
Also related - #945. :)
Any ideas on how to start doing this?

**Comment by markroxor** [comment]
I've submitted a pull request #946 for a unified base class. Not sure if this you are actually looking for but review and let me know if I'm going in the right direction. thanks
