### ISSUE TITLE
LDA Multicore Windows Error 

### ISSUE THREAD

**Issue by hiral2cool** [RaRe-Technologies/gensim#940]
os : windows 10
version : Python 2.7.10 
all latest numpy,scipy everything upgraded 
when i start ldamulticore error is like this 
--------------------------------------------------

PYTHON 
------------
lda = gensim.models.LdaMulticore(corpus=corpus, id2word=id2word, num_topics=10)

ERROR
-------------
File "C:\Python27\lib\multiprocessing\forking.py", line 361, in get_command_line
    is not going to be frozen to produce a Windows executable.''')
RuntimeError:
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.

working perfect on Ubuntu but problem in windows version
any help will be useful

**Comment by tmylk** [comment]
Does anyone have windows 10 to try  if adding `if __name__ == '__main__':` helps as in [SO](http://stackoverflow.com/questions/18204782/runtimeerror-on-windows-trying-python-multiprocessing)?

**Comment by hiral2cool** [comment]
but at where i have to add this code ?? 
first i try to add this in main my python code file from which i am going to run LDA module 

if __name__ == '__main__':
      freeze_support()

i try this but same error

**Comment by tmylk** [comment]
It should be in the main module of your program as in https://docs.python.org/dev/library/multiprocessing.html#multiprocessing.freeze_support

May I ask for the full code that reproduces the error?

**Comment by hiral2cool** [comment]
import logging

import os

import gensim

from gensim import corpora, models, similarities

logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)



path = os.path.exists('/home/hduser/Downloads')

print path



if (path):

    id2word = corpora.Dictionary.load('/home/hduser/Downloads/newsgrp_all_topic.dict')

    corpus = corpora.MmCorpus('/home/hduser/Downloads/newsgrp_all_topic.mm')

    print("Used files generated from existing one")

else:

    print("File did not Find")



lda = gensim.models.ldamodel.LdaModel(corpus=corpus, id2word=id2word, num_topics=50, passes=10,distributed=True)

#lda = gensim.models.LdaMulticore(corpus=corpus, id2word=id2word, num_topics=50, passes=10)

#lda.print_topics(4)



corpus_lda = lda[corpus] # create a double wrapper over the original corpus: bow->tfidf->fold-in-lsi

#for doc in corpus_lda:

 #   print(doc)



print("Dooooooooooooooooooooooooooooone")


Here i put all the files of 
LDA multicore , Debug Console , Log files after execution

http://www.pastefile.com/hkNFWB

LDA single core working fine 
but LDA multicore and LDA distributed both have same error and same problem

**Comment by tmylk** [comment]
Hmm probably ` if name == 'main': freeze_support() ` should be on the top of `code.py`?

**Comment by hiral2cool** [comment]
yes i tried just now & everything is same 
console output , log file ,error 
everything same no change 

don't know what is the problem i also try to debug code but not understand well

**Comment by tmylk** [comment]
hmm maybe that line needs to be in `LDAMultiCore`?
This is not a specifically gensim issue though. It relates to forking on windows.

**Comment by hiral2cool** [comment]
yup i know that it is problem of forking on windows 
but it should work and something somewhere this library code will change to support new win 10 os

and i also try LDAMulticore 
same issue remaining with same errors

**Comment by hiral2cool** [comment]
adding this to main source code 
if __name__ == '__main__':

run working of program successfully LDAmulticore 
so Issue Fixed..
Thank you

**Comment by tmylk** [comment]
@hiral2cool Thanks a lot for reporting your fix!
Which file was it added to?
May I kindly ask you to submit a Pull Request so that the community can benefit from your solution.

**Comment by tmylk** [comment]
Ping @hiral2cool could you copy paste your fixed code here?

**Comment by hiral2cool** [comment]
yaa sure here is my code 
no need to change any files in gensim 
just simply add line in main source code where parallel starts 

http://www.pastefile.com/PZKSa3

**Comment by tmylk** [comment]
Resolved by adding this code:

```
if __name__ == '__main__':
    freeze_support()
	lda = gensim.models.LdaMulticore(corpus=corpus, id2word=id2word, num_topics=4)
```
