### ISSUE TITLE
Notation Mismatch : Documentation LDA and HDP

### ISSUE THREAD

**Issue by budhiraja** [RaRe-Technologies/gensim#941]
Hi,
I have come across an instance where the notations in examples and APIs is different. In LDA and HDP the  `show_topics` function takes arguments - `num_topics=20 and num_words=20` where as in the following places, it is mistakenly reported as something else.
1. http://christop.club/2014/05/06/using-gensim-for-lda/ : model.show_topics(topics=5, topn=5)
2. https://radimrehurek.com/gensim/models/hdpmodel.html : hdp.print_topics(show_topics=20, num_words=10

It will be good to rectify these.

Thanks,
Amar

**Comment by bhargavvader** [comment]
@dsquareindia , @tmylk , HDP is coming up often with regard to this... needs some cleaning up.

**Comment by budhiraja** [comment]
Hi @bhargavvader  is there an HDP tutorial somewhere? If I am right HDP build a topic hierarchy, is there a way to look at it? Even in a crude way - say parent-child relationship?

Thanks,
Amar

**Comment by bhargavvader** [comment]
As far as I know, there is no tutorial nor is there a way to look at the topic hierarchy - though I have not used it extensively, and am unaware if it might exist. I'm going to raise an appropriate issue so someone can tackle it, but will wait for @tmylk or @dsquareindia to confirm if we have more HDP examples.

**Comment by tmylk** [comment]
@markroxor should this be updated post #946 merge?

**Comment by markroxor** [comment]
Not sure what you mean, do you want me to work on #945 ?

**Comment by markroxor** [comment]
HDPModel now includes `print_topics` so 'hdp.print_topics(num_topics=20, num_words=10)' can now be executed but the tutorial for hdpmodel [here](https://radimrehurek.com/gensim/models/hdpmodel.html) should be updated as it states `show_topics` as an input parameter instead of `num_topics`.

**Comment by bhargavvader** [comment]
Can this be closed now that the base class is made?

**Comment by tmylk** [comment]
The doc has been regenerated  at  https://radimrehurek.com/gensim/models/hdpmodel.html
