### ISSUE TITLE
HDP improvements: Topic Hierarchy and Tutorial

### ISSUE THREAD

**Issue by bhargavvader** [RaRe-Technologies/gensim#945]
As mentioned in #941, and previously in #262, HDP isn't very consistent with `LdaModel`. Also #901, #937 are other documented issues to do with HDP. We could use a complete overhaul in the way these Topic Models are organised (ideally with a parent topic-model class), but for the time-being, HDP needs improvements in it's documentation and structure.

Particularly, it would be useful to have a comprehensive tutorial of what HDP is and what it does.

I would like to take this up in the future, but if someone else has time on their hand and would like to go ahead right away, we could use this issue to discuss the same!

Edit: #938 has already talked about a topic model class.

**Comment by markroxor** [comment]
I am up for it. What more changes can we incorporate? For a start I guess editing the tutorial should do like the [one here.](https://radimrehurek.com/gensim/models/hdpmodel.html)
` hdp = HdpModel(corpus, id2word)`
` hdp.print_topics(show_topics=20, num_words=10)`

show_topics should be changed to num_topics without altering the API.

**Comment by tmylk** [comment]
@markroxor Creating a [tutorial](https://github.com/RaRe-Technologies/gensim/tree/develop/docs/notebooks) in the tutorial folder would be a great place to start

**Comment by bhargavvader** [comment]
Sounds good! About the tutorial, it will be nice to have it like a 'story' so it is interesting. Would look even better after we have a Topic Hierarchy functionality. 
@markroxor could you look at the [ldaseqmodel](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/ldaseqmodel.ipynb) tutorial, and the [news-classification](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/gensim_news_classification.ipynb) to get an idea of how to make it more read-friendly? Even the doc2vec and topic coherence tutorials are good examples.

**Comment by bhargavvader** [comment]
@tmylk could you add appropriate labels to this please?

**Comment by markroxor** [comment]
@bhargavvader It will take some time but be assured it will be done. Will catch up with you on this.

**Comment by markroxor** [comment]
I am available to take this now. If I am right, it is required to create a hdpmodel tutorial in the [tutorial](https://github.com/RaRe-Technologies/gensim/tree/develop/docs/notebooks) folder?

**Comment by tmylk** [comment]
The folder is correct. The notebook content is in the main description of this issue.

**Comment by tmylk** [comment]
Ping @markroxor

**Comment by bhargavvader** [comment]
@tmylk , I was looking up how to maybe do the topic hierarchy, but couldn't find anything.
[This](https://groups.google.com/forum/#!msg/gensim/yHh4JBLPbBo/Mgu4_wYQBAAJ;context-place=searchin/gensim/heirarchy%7Csort:relevance) post, and [this](https://groups.google.com/forum/#!msg/gensim/UWODpcSbnIA/-PsXuOvgAwAJ;context-place=searchin/gensim/heirarchy%7Csort:relevance) ask for the same as well. Is there any resource, paper, video or anything which maybe hints at how to do this?

**Comment by menshikh-iv** [comment]
Resolved in #1055.

**Comment by zeyd31** [comment]
The selection of number of topics at the end of the process is still unclear
