### ISSUE TITLE
Add more tests for HdpModel

### ISSUE THREAD

**Issue by markroxor** [RaRe-Technologies/gensim#952]
In the file [test_hdpmodel.py](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/test/test_hdpmodel.py) meant for continuous integration for testing builds. The only tests that are conducted are for `hdpmodel.show_topics()`. Need to create more tests for better build evaluation.

**Comment by bhargavvader** [comment]
Added appropriate tests in #1055. Can this be closed?

**Comment by markroxor** [comment]
Thanks. :)
