### ISSUE TITLE
Directory names on Windows 10 failing. ( '/tmp' )

### ISSUE THREAD

**Issue by Shabukc** [RaRe-Technologies/gensim#955]
I was trying to run "gensim/docs/notebooks/word2vec.ipynb" on windows 10 with Anaconda-Jupyter.

![image](https://cloud.githubusercontent.com/assets/3529477/19418022/16923aea-93d9-11e6-9bbf-78ce3a03f815.png)

Can we have a better way of handling folder/path  (especially temporary ) independent of Operating System ?

**Comment by piskvorky** [comment]
Hello @Shabukc , thanks for reporting.

Yes, I'd consider this is a bug -- even the notebooks should be OS independent (using `tempfile` and `os.path.join` properly).

**Comment by mamamot** [comment]
working on it

**Comment by tmylk** [comment]
Fixed in #1004

**Comment by piskvorky** [comment]
@tmylk ping.
