### ISSUE TITLE
most_similar() from Word2Vec use all CPU.

### ISSUE THREAD

**Issue by Ulitochka** [RaRe-Technologies/gensim#959]
Hello!
Thanks for your work.
I use pretrained model - binary file and method load_word2vec_format() for loading.
But if I use most_similar() method I find 8 (max) threads in my system.
Can you help me?

gensim 0.13.2
ubuntu 14.04
scipy 0.18.00
numpy 1.11.1

`            try:
                quasi_synonyms = [el[0] for el in
                                       self.model.most_similar(positive=[tokens_with_transform_tags],
                                                                              topn=self.feature_options[0])]
            except KeyError:
                quasi_synonyms = ['<null>' for i in range(self.feature_options[0])]`

**Comment by tmylk** [comment]
Hi, 
do you expect more or less threads?
Also consider Annoy https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/annoytutorial.ipynb

**Comment by Ulitochka** [comment]
Hi, thanks for your answer.
In method most_similar() if argument indexer=None this version use all CPU.
If we use Annoy, create index, and give most_similar() indexer=annoy_index - that's ok.

In this tutorial https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/annoytutorial.ipynb I see this: You can save and load your indexes from/to disk... and exaple: annoy_index.save(fname) But in index.py not method save? How I can save my index?

**Comment by tmylk** [comment]
@Ulitochka This [functionality](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/similarities/index.py#L38) will be available in our next release this month. For now, you can use develop branch on github

**Comment by tmylk** [comment]
Closing as resolved

**Comment by tmylk** [comment]
We can continue this conversation on the mailing list groups.google.com/forum/#!forum/gensim
