### ISSUE TITLE
LDA on Unseen Document

### ISSUE THREAD

**Issue by hiral2cool** [RaRe-Technologies/gensim#972]
I have 5 million documents, want to apply LDA on that and system is that another document may be come that are unseen for topic modeling so i do like this

first train model with 5 million docs and save it then if new 1 million document come then i try to use that saved model but so i use 1 million document corpus_new with dict_old that built from 5 million docs 
so again and again i did not have to apply LDA on each and every document 
sample code is here 

http://www.pastefile.com/cJauPz

now my question is 

1. if unseen document contain totally new and unseen words that may be not in old trained doc dict then how that can be find important topics from new documents bcoz they used old dict 
so can we have to again train 5 million doc model with unseed doc ?? 
then time taken will be very much or every time i have to train model when new doc comes ??

I also read may be hashdictionary is solution but same thing how to use that no idea and what is about time ??? 
 
can you help me out this ?

**Comment by bhargavvader** [comment]
Hello @hiral2cool , this kind of issue would be better served on the gensim [mailing list](https://groups.google.com/forum/#!forum/gensim).

That being said, you cannot perform a topic analysis on new words (words outside the trained dictionary). You don't need to train LDA on unseen documents if you want to find the topic proportions. If you wish to update your model, like mentioned previously, it would need to contain the same vocabulary.

I think @dsquareindia faced the same issues before and managed to get it resolved so you can contact him (though gitter or the mailing list would be a better forum to discuss this.)
