### ISSUE TITLE
LSA when get u martix ,how to show  associated word for every vector line

### ISSUE THREAD

**Issue by whybangbang** [RaRe-Technologies/gensim#974]
thanks your gensim ,it's powerful
we want to get the relationship between words, so i use lsimodel.projection.u, but u is a martix but not show associated word, how can i get this?

**Comment by bhargavvader** [comment]
Hello @whybangbang , this kind of question will be better addressed on the gensim mailing list or on gitter.

The github issues page is to report bugs or request features.

**Comment by tmylk** [comment]
The mailing list is https://groups.google.com/forum/#!forum/gensim

**Comment by whybangbang** [comment]
thanks
