### ISSUE TITLE
gensim doc2vec doesn't have the same doc id's in docvecs

### ISSUE THREAD

**Issue by IoDmitri** [RaRe-Technologies/gensim#977]
Python version: 2.7.10
Gensim: 13.02

Here is my [SO](http://stackoverflow.com/questions/40230532/gensim-doc2vec-documents-not-found-by-id) post detailing the problem in depth and offering code examples.

**Comment by gojomo** [comment]
Answered on SO but also note the project forum is a better place than the bug/feature tracker for asking about or discussing unexpected behavior, unless/until you're more certain it is a bug or missing-feature.
