### ISSUE TITLE
WMD Earth mover Distance for sentences that contain a single word return inf

### ISSUE THREAD

**Issue by rbahumi** [RaRe-Technologies/gensim#979]
`import gensim
from reuse import load_model

if **name** == "**main**":
    print "gensim version: %s" % gensim.**version**

```
path = "models_no_short_text_20.10"
model = load_model(path)

sentence_obama = 'Obama speaks to the media in Illinois'.lower().split()
sentence_president = 'The president greets the press in Chicago'.lower().split()
print model.wmdistance(sentence_president, sentence_obama)

obama = "Obama".lower().split()
print 'Result for sentence "%s": %s' % (" ".join(obama), model.wmdistance(obama, obama))


obama = "Obama".lower().split() * 5
print 'Result for sentence "%s": %s' % (" ".join(obama), model.wmdistance(obama, obama))`
```

Will   ##output:

> gensim version: 0.13.2
> 3.69295766061
> Result for sentence "obama": inf
> Result for sentence "obama obama obama obama obama": inf

**Comment by rbahumi** [comment]
This is caused by the np_sum(distance_matrix) is equal to 0 when the distance matrix is a 1*1 matrix

[https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/word2vec.py#L1415](url)

**Comment by tmylk** [comment]
Thanks for highlighting this. What would be a better value to return?

**Comment by rbahumi** [comment]
@tmylk, thanks for your replay. I suggest it should return float 0.0. If you agree, I have attached a pull request that deals with it. [Please take a look.](https://github.com/RaRe-Technologies/gensim/pull/986)

**Comment by tmylk** [comment]
How d
